j/tree.c

The good news is, this is pretty funny.
Maybe some day there will be a jet fuzzer.
This fixes #238.

Fix de:aesc jet

---

Makefile
i/j/q.h
i/j/w.h
j/e/scr.c
j/tree.c
outside/scrypt/Makefile
outside/scrypt/crypto_scrypt-sse.c
outside/scrypt/crypto_scrypt.h
outside/scrypt/sha256.c
outside/scrypt/sha256.h
outside/scrypt/sysendian.h
urb/zod/base/arvo/hoon.hoon

Reverts urbit/urbit#276.  Clearly not teh problem.

Revert "Revert "Jetted scrypt""

---

extras/hoon-mode.el/hoon-mode.el

This fixes some problems with the copyright notice for `hoon-mode.el`.

Fix copyright notice

---

Makefile

Don't hesitate to ask me to rewrite the prose explaining the scenario to fit whatever tone you desire--I won't be offended.

Enable parallel builds (292)

---

urb/zod/arvo/hoon.hoon

General guidance on using floating point would be better for external documentation (++equ is not useful for most cases and should use epsilon test instead, etc.)

comments, a couple fixes

---

outside/scrypt/Makefile
outside/scrypt/crypto_scrypt-nosse.c
outside/scrypt/crypto_scrypt.h

no sse required

---

debian/docs

For merging

---

urb/zod/pub/doc/hoon/tutorial/2-syntax.md

If this change isn't correct, then the table earlier in the file needs to be updated.

correct hoon names for `->` and `?:`

---

Spec/u3.md

Ref: https://github.com/urbit/urbit/issues/439
Patches for 1), 2) and 3).  Left 4) unchanged.

Clarifications to Spec/u3.md

---

Makefile

fix etags target

---

urb/zod/ape/talk.hoon
urb/zod/pub/docs/user/talk.mdy

No conflicts or type-fails when combined with Anton's `talk-commands` branch.

`;set noob` for cli talk

---

urb/zod/arvo/eyre.hoon
urb/zod/lib/base.css

Unfortunately, this requires an eyre change.

Add a note about the login code in your console.

---

urb/zod/pub/tree/src/js/components/KidsComponent.coffee
urb/zod/pub/tree/src/js/main.js

Sort of a weird sorting algorithm.

Fix for runes kids

---

urb/zod/pub/tree/src/js/components/BodyComponent.coffee
urb/zod/pub/tree/src/js/main.js

It's more of a newsletter than an invite...

Header copy change

---

urb/zod/pub/docs/dev/hoon/runes/br/brcn.md
urb/zod/pub/docs/dev/hoon/tutorial/1-twigs.mdy
urb/zod/pub/docs/dev/hoon/tutorial/2-syntax.mdy
urb/zod/pub/docs/dev/hoon/tutorial/3-program.mdy

Now it doesn't sound like it's a feature of Hoon that simple symbol
tables hard to build.

Rewrite double negation

---

urb/zod/pub/tree/src/css/main.css
urb/zod/pub/tree/src/css/main.styl

code white-space

---

urb/zod/arvo/hoon.hoon

nb:  no pill, since a new one will need to be created anyway after the next set of merges.
This should unblock #666.  I recommend this update go in along with #664, then maybe wait a bit for everyone to get those, then push #666.

make reload, reset crash resistant through mule

---

jets/e/lore.c
urb/zod/arvo/hoon.hoon

@chc4 pull request, wrongfully deleted by GH. Unfinished (sorry, will get to it asap!).

fix ++lore and ++role

---

urb/zod/ape/bit.hoon
urb/zod/gen/hood/merge.hoon
urb/zod/lib/kiln.hoon
urb/zod/pub/bit/fab/hymn.hook

also, get rid of extra ~& in kiln

default case correctly in |merge

---

urb/zod/arvo/ford.hoon
urb/zod/mar/hook.hoon
urb/zod/mar/hoon.hoon
urb/zod/mar/markdown.hoon
urb/zod/mar/md.hoon

fix marks for new lore/role

---

urb/zod/pub/docs/dev/hoon/principles/2-syntax.md
urb/zod/pub/docs/theory/whitepaper.md

Update the glyph lists in the hoon tutorials and in the whitepaper to include sig.

Add sig ~ to the glyph lists

---

urb/zod/pub/docs/dev/hoon/reference/odors.md

Just substituting ? for :type; in odors.md

Update odors.md to use newer dojo syntax

---

README.md

Breach instructions should go here.

continuity breach

---

include/vere/vere.h
vere/http.c

Associated http-parser with connection instead of request; fixed queuing bug
Haven't changed anything in cttp.c because there seems to be handling code in there already.
fixes #409

Fixed pipelining on incoming http requests

---

README.md

Changing docs to refer to HTTP instead of HTTPS.

---

.gitignore
Makefile

… as per [this bit of advice](https://twitter.com/urbit_/status/739273155512958976) from [@urbit_](https://www.twitter.com/urbit_):

Commented out zod in osxpackage and debbuild

---

jets/b/reap.c

For the epic saga, see https://www.reddit.com/r/urbit/comments/4pd7vk/im_very_confused_about_standardlibrary_lists/

fix misbehaving reap jet

---

CONTRIBUTING.md

 dozbud in CONTRIBUTING.md

---

Makefile

`glibc 2.24` deprecated `readdir_r` and patched `readdir` for threadsafeness.  This Makefile upgrades warnings to errors with `CWFLAGS=-Werror`, so compilation fails in the presence of `glibc >=2.24`.  This is a problem in Arch today (#771) and other distros in the near future.
The best solution may be to check the `glibc` version and replace `readdir_r` with `readdir` if `glibc >=2.24`.  In the meantime, using `CWFLAGS+=-Wno-error=deprecated-declarations` in the Makefile in the case of `glibc >=2.24` allows `glibc 2.24` users to compile Urbit.
Depends on `getconf` and `expr` shell built-ins, which should be available everywhere.

Workaround for `glibc >2.24` compilation failure (#771)

---

vere/pier.c

Add clarifying comment to precommit logic.

---

jets/e/fl.c

Dragon4 fix

---

noun/manage.c

Matches the pill format in the new [CI code](https://github.com/urbit/arvo/blob/master/.travis/get-or-build-pill.sh).
The new format is:
`https://bootstrap.urbit.org/git-<hash>.pill` where `<hash>` is the first 10 characters of the git hash of the most recent commit (from either the current commit or its ancestors) that changed the sys/ directory.
Once this lands, I should update that fora post about the pill formats.

New pill URL format and search through old commits

---

vere/term.c

maintains cursors position on %clr

---

vere/term.c

forwardports #813 (show prompt after ctrl-c)

---

jets/b/roll.c

adds a cell check for the sample of the +roll gate

---

include/c/portable.h
vere/main.c

a simple way to make sure #951 never happens again

requires unsigned char on startup

---

vere/cttp.c

*blames it on the jet lag*
fix for #966
/cc @cgyarvin @Fang-

fixes improper null-termination in cttp header buffers

---

vere/http.c

preventing what may be an infrequent use-after-free

http: ensures that response buffers aren't freed until the request is disposed

---

README.md
meson.build
meson_options.txt
scripts/build

This reverts commit 26996c2b1647c0017bea2ab8789768daf0208709, reversing
changes made to 38f9c546c435b4d82bb94280a772e45df5295dee.
Related discussion can be found here:
https://github.com/urbit/arvo/issues/709

Revert "Merge pull request #977 from urbit/meson-build-type"

---

include/vere/vere.h
vere/ames.c
vere/cttp.c
vere/http.c
vere/term.c

Just cleaning-up some minor issues I found in the I/O drivers.

minor i/o driver cleanup

---

vere/sist.c

This is #1026 ported to release-candidate.
cc @jglukasik

Disable terminal echo on passcode entry

---

noun/jets.c

Ports https://github.com/urbit/urbit/pull/1049 to the testnet-rc branch so we can profile the testnet.
Confirmed works with -P on my mac laptop.

Port profiling fixes to testnet-rc

---

jets/b/sort.c
jets/tree.c

The majority of time in `+gather-builds` in Ford was spent inside `+sort`.
Closes #387

Write a jet for +sort

---

include/noun/vortex.h
noun/vortex.c
vere/raft.c
vere/sist.c

... in both live event handling and replay. These were made unnecessary by urbit/arvo#931

removes unnecessary effect traversals

---

vere/dawn.c

Matches the changes in urbit/arvo#946. Here it's just a simple renaming.

Rename hull to point in Ethereum boot logic

---

vere/dawn.c

Update dawn comments

---

vere/sist.c

PLEASE DON'T LOOK AT THIS UNLESSS YOU'RE BORED / NOT BUSY.
This is a bunch of minor cleanup that went along with #1115. Basically I got rid of a bunch of un-hi/lo-jacked `perror`s and cleaned up some unneeded preprocessor gunk in `sist.c`. Also saved a call to `c3_rand`.
Pun totally intended.

Random cleanup

---

.travis.yml

If my claim (in urbit/docs#326) is correct, then we can get rid of a lot of this and the CI will still pass.

Try removing a bunch of dependencies

---

.gitmodules
meson.build

- host_machine seems to be what we want for the machine that the binary
will run on. Doesn't matter unless anyone's cross compiling.
- There's a magic cross-platform threads dep apparently.
- Sorted deps, so that new deps have a canonical place to go.
- Fixed the build on OSX with MacPorts.

meson cleanup

---

vere/sist.c

Also refactors `_sist_cask`, and adds support for an optional leading `~` when entering the `@p` passcode (so one can simply copy/paste the contents of the passcode file).
Closes #852

updates passcode entry to handle EOF

---

vere/sist.c

disables inconsistent event-log validation step on replay

---

include/vere/vere.h
vere/dawn.c
vere/sist.c

dual of https://github.com/urbit/arvo/pull/980
This also:
- fixes a bug where we bunted a dead zuse type
- refactors snapshot downloading to use a new `_dawn_get_jam()` helper
I've initialized the file at the hard-coded URL to include just `~marzod`.

Download star list to boot comet

---

vere/ames.c
vere/behn.c
vere/cttp.c
vere/dawn.c
vere/http.c
vere/loop.c
vere/main.c
vere/raft.c
vere/reck.c
vere/save.c
vere/sist.c
vere/term.c
vere/time.c
vere/unix.c
vere/walk.c

I removed anything that was in portable.h, specified proper path names,
and removed some now-wrong (?) public domain notices. Also did some
formatting/consistency stuff.

Minor file-head cleanup

---

README.md
vere/main.c

This just removes/replaces anything that's actively wrong. The help text is still incomplete, and could definitely be improved.

updates README and usage instructions

---

.gitmodules
include/c/portable.h
meson.build
vere/sist.c

XX make sure to fork [mrdomino/libent](https://github.com/mrdomino/libent) to the urbit org before merging this.

Use libent for getentropy

---

meson.build

I suppose the subproject commit may have to get updated after urbit/libent#3 gets merged.

Updates libent (fixes #1155)

---

include/noun/jets.h
include/noun/manage.h
noun/jets.c
noun/manage.c
noun/nock.c
vere/reck.c
vere/sist.c

reclaim memory from persistent caches on restart and kernel reset

---

noun/manage.c
noun/trace.c
noun/vortex.c

Advice welcome wrt clearer, more specific error messages.
closes #1162

print error messages on boot failure due to bad pill

---

vere/ames.c

no-op in ames.c if no galaxy domain

---

noun/trace.c
vere/sist.c

- Adds tracing during playback
- stop snprintf-ing from one string into itself, which is undefined behavior

tracing bugfixes

---

vere/fuse.c
vere/main.c
vere/newt.c
vere/pier.c
vere/serf.c

I pulled these commits out of #1197 -- they should require less review and go in much quicker. I'll rebase that once this is in.

cc-release: fixes CLI argument parsing, uint64_t format strings

---

pkg/urbit/vere/unix.c

cc-release: removes clay mount auto-sync on restart

---

pkg/urbit/include/vere/vere.h
pkg/urbit/vere/pier.c

... by means of a `uv_idle_t` handler that we turn on and off as appropriate.

cc-release: runs event state machine once per libuv turn

---

noun/manage.c

Minor link fix i noticed while looking into https://github.com/urbit/urbit/issues/1242

Update link to docs for swap space help

---

README.md

Starting to clean up contributor onboarding documentation. A first step.

Update Contributing in README and remove Landscape info

---

nix/deps-env.nix
nix/pkgs/urbit/shell.nix

I just cargo-cult'd this, but it works for me and fixes #1304

adds ge-additions package to urbit nix-shell config

---

pkg/arvo/sys/vane/rver.hoon
pkg/arvo/tests/sys/vane/rver.hoon

Added a styled login page to rver based on Gavin's mocks.

Styled login page within rver for modulo

---

pkg/urbit/vere/term.c

fixes #1276, at least for my window-resizing case.
I see now this is a thing, maybe it's better: https://www.gnu.org/software/libc/manual/html_node/Interrupted-Primitives.html#Interrupted-Primitives

retry tcsetattr on EINTR

---

pkg/urbit/vere/http.c

(Joe double checked that this worked though.)

Maybe this fixes the transfer encoding issue. ¯\_(ツ)_/¯

---

pkg/urbit/include/vere/vere.h
pkg/urbit/jets/f/ut.c
pkg/urbit/vere/daemon.c
pkg/urbit/vere/pier.c

fixes slog priority printfs, enables utf8 in tanks

---

bin/solid.pill
pkg/arvo/app/dns-bind.hoon
pkg/arvo/app/lens.hoon
pkg/arvo/sys/vane/gall.hoon

Introduced many long years ago: a0156a472ab66b377b00d1202b879d62daf4ce03
/cc @philipcmonk

 fixes a bug in %gall preventing cross-ship cross-app communication

---

.travis.yml
sh/cachix

By only updating cachix if credentials are available.

fix CI for PRs from forks

---

pkg/arvo/app/dns-bind.hoon
pkg/arvo/app/dns-collector.hoon
pkg/arvo/app/dns.hoon
pkg/arvo/lib/tapp.hoon

Also prevents `lib/tapp` from wiping app state on incompatible state upgrades.
/cc @philipcmonk

improved debug-ability the dns apps

---

pkg/arvo/app/weather.hoon

Fix timer logic in Weather app

---

nix/ops/solid/builder.sh
pkg/arvo/lib/pill.hoon

The PR fixes some insufficiencies in #1429, discovered in attempting to merge master and automatically restage pills in #1422

updates solid pill staging to handle :lens and +solid changes

---

pkg/urbit/include/noun/allocate.h
pkg/urbit/noun/allocate.c
pkg/urbit/noun/retrieve.c

In response to the stack overflows reported in #1600.
/cc @frodwith

rewrites u3a_take() to use the road stack

---

pkg/arvo/sys/vane/eyre.hoon
pkg/arvo/tests/sys/vane/eyre.hoon

Make authorization cookie live for one week instead of one day

---

pkg/arvo/app/claz.hoon

This was never converted to lighter-than-eyre, so I went ahead and did it in a simple way.

claz: convert to iris

---

bin/solid.pill
pkg/arvo/lib/hall-json.hoon
pkg/arvo/sys/zuse.hoon

I found myself copying these functions over and over into new JSON libs inside of the odyssey branch, so I'd love to get these included as standard library additions instead of having to do that!

Added tank and path json encoders, array to set, and string as @tas to zuse/hoon

---

pkg/king/test/HoonMapSetTests.hs

While doing our golden testing, we shouldn't write result files to
the filesystem. Result files are temporary and filesystem operations
can fail a surprising percentage of the time when you're using CI.
Use the in memory comparison function instead.

Don't write files to disk during testing.

---

pkg/urbit/daemon/main.c
pkg/urbit/noun/events.c
pkg/urbit/vere/unix.c

vere: checks permissions, handles (some more) filesystem errors

---

pkg/arvo/app/chat-cli.hoon
pkg/arvo/app/chat-hook.hoon
pkg/arvo/lib/hood/drum.hoon

As per @jtobin's feedback. See commit messages for changelog.

Chat: minor fixes re feedback

---

pkg/arvo/app/chat-cli.hoon

chat-cli: update prompt on ;join

---

pkg/arvo/gen/azimuth-tracker/watch.hoon

Fixes #1837 per https://github.com/urbit/urbit/issues/1837#issuecomment-543282516

azimuth-tracker: fix |watch generator

---

pkg/arvo/app/chat-cli.hoon

Nothing noteworthy, but also don't want to let these sit locally as todo patches forever.

chat-cli: minor code style fixes

---

nix/deps/ivory-header/builder.sh

nix: fix ivory-header error conditions (detecting lfs pointers)

---

pkg/arvo/gen/trouble.hoon

I'll PR this now so others can help work on it. 
We'll want to output the comments about what to compare on ethercan.io and how to do it.
ht: pcmonk, ohAitch, Fang

arvo: add +trouble generator (for troubleshooting)

---

pkg/arvo/app/language-server.hoon
pkg/arvo/lib/language-server/complete.hoon

Allows language-server to commit automatically upon changes. 
Additionally recalculates syntax issues upon save.
Add function signature on hover. Fixes bug around autocomplete
not working properly when the cursor was mid-word.

Language server autocommit and type on hover

---

bin/solid.pill
pkg/arvo/app/chat-cli.hoon
pkg/arvo/sys/zuse.hoon

Just a little something to make "working with moons" easier.

zuse: add +name:title for (moon) identity

---

bin/solid.pill
pkg/arvo/sys/hoon.hoon
pkg/arvo/tests/sys/hoon/list.hoon

Add some extra list operations. 
TODO:
----------

arms for inserting in and updating lists and tests

---

pkg/arvo/gen/hood/ames-verb.hoon
pkg/arvo/gen/hood/knob.hoon
pkg/arvo/lib/hood/helm.hoon
pkg/arvo/sys/vane/ames.hoon
pkg/arvo/sys/zuse.hoon

Also modifies Ames itself by adding a %spew task so the verbosity toggles can be set at runtime.

|ames-verb generator to set ames verbosity

---

pkg/arvo/app/chat-store.hoon

chat-store: fix scrollback issue due to malformatted peek

---

pkg/urbit/vere/dawn.c

updates to 'Urbit identity' language in comet boot message

---

pkg/king/lib/Noun/Atom.hs

I was able to reproduce this by building without optimizations and increasing the number of quickcheck tests on my jam/cue tests. With the fix, I cannot reproduce.

Fix a bug in atom<->bytestring conversion.

---

pkg/interface/chat/src/js/components/lib/message.js

chat: fix wrong font-size on certain pre-elements

---

pkg/arvo/sys/zuse.hoon
pkg/urbit/jets/e/lore.c

Fix +to-wain:format null byte handling

---

pkg/interface/chat/src/js/components/lib/message.js

Removing `bb` from images
@urcades @matildepark

removing black border

---

pkg/arvo/app/contact-hook.hoon
pkg/arvo/app/contact-store.hoon
pkg/arvo/app/contact-view.hoon
pkg/arvo/app/contacts/js/index.js
pkg/interface/contacts/src/js/components/lib/contact-card.js
pkg/interface/contacts/src/js/components/root.js
pkg/interface/contacts/src/js/subscription.js

Properly handle "remove from group" UI action

Contact delete os1

---

pkg/interface/publish/src/js/components/lib/join.js
pkg/interface/publish/src/js/components/lib/sidebar.js
pkg/interface/publish/src/js/components/root.js

LIke https://github.com/urbit/urbit/pull/2219 but without the cruft.

basic join screen

---

pkg/interface/contacts/src/js/components/lib/contact-card.js

Remove image upload affordance from contact card.

Contacts: remove image upload button

---

pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs
pkg/hs/urbit-king/lib/Urbit/Vere/Serf.hs

Fix counting bug in event log replay.

king: Fix log replay bug.

---

pkg/interface/publish/src/js/components/lib/sidebar.js

publish: hide overflow in sidebar

---

pkg/interface/link/src/js/components/lib/channel-sidebar.js
pkg/interface/link/src/js/components/lib/channels-item.js
pkg/interface/link/src/js/components/lib/comment-item.js
pkg/interface/link/src/js/components/lib/comments.js
pkg/interface/link/src/js/components/link.js
pkg/interface/link/src/js/components/links-list.js
pkg/interface/link/src/js/components/root.js
pkg/interface/link/src/js/components/skeleton.js
pkg/interface/link/src/js/lib/util.js
pkg/interface/link/src/js/reducers/link-update.js

Please see commit messages for full changelog. They should be reviewable individually.
Primarily fixes:
- No unread counts on non-private channel
- "NaN links" after first link submission
- Permanent "0 contributors"

link fe: various fixes causing improvements

---

pkg/arvo/sys/vane/eyre.hoon

Kudos to @ixv for the help.
cc @urcades

eyre: add new os1 login screen

---

pkg/arvo/app/ping.hoon
pkg/arvo/sys/vane/ames.hoon

Looks like this was accidentally rebased out of #2113.  It's on livenet already.

ames: make routing simpler

---

pkg/arvo/app/link-store.hoon
pkg/arvo/app/link-view.hoon
pkg/interface/link/tile/tile.js

Also sneaks some small link-store work in there, always instantly marking your own submissions as read.
As usual, pls see commit messages.

link: properly support the launch tile

---

pkg/arvo/app/hood.hoon
pkg/arvo/lib/hood/drum.hoon

Adds a new tag to the hood state tagged union, starts the relevant apps on transition.

OS1: automatically start contacts and links apps upon recieving ota

---

pkg/hs/default.nix

Running this build now, not yet sure if works.
First build on a new machine takes hours.

king: Use newer static-haskell-nix script for KH build.

---

pkg/hs/urbit-king/lib/Urbit/King/Main.hs
pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs
pkg/hs/urbit-king/lib/Urbit/Vere/Term.hs
pkg/hs/urbit-king/lib/Urbit/Vere/Term/Render.hs
pkg/hs/urbit-king/package.yaml

WIP: Uncursed King

---

pkg/interface/link/src/index.js

I keep skimming over 'index.js' files and failing to commit changes that otherwise crash the app, sorry @Fang- san.

link-fe: remove header-bar from index.js

---

bin/brass.pill
bin/ivory.pill
bin/solid.pill
pkg/arvo/sys/hoon.hoon

The long-awaited extra commit I owe. Also removes +mush.

"extra commit"

---

pkg/interface/contacts/src/js/components/root.js

contacts: add bg-gray0 to root page

---

pkg/interface/publish/src/js/components/lib/settings.js
pkg/interface/publish/src/js/reducers/primary.js

Adds the ability to edit name, description, and disable/enable comments. Also lets the owner copy a shortcode to join the notebook.

publish: edit notebook settings

---

pkg/arvo/app/publish.hoon
pkg/interface/publish/src/js/components/lib/edit-post.js
pkg/interface/publish/src/js/components/lib/note.js
pkg/interface/publish/src/js/reducers/primary.js

Fixes:
- notebook deletion bug
- note read notification bug
- note editing newline and snippet bugs

OS1: multiple publish fixes

---

pkg/interface/chat/src/js/components/settings.js
pkg/interface/link/src/js/components/settings.js

Uses the same logic as Groups' sigil colour picker for submission, too.

chat, link: preview for channel colour picker

---

pkg/interface/publish/src/js/components/lib/join.js

publish: fix join typo

---

pkg/interface/soto/src/js/components/input.js

soto: add 'capslock' to ignored keys

---

pkg/interface/groups/src/js/components/lib/contact-card.js

groups: add bottom padding to contact card

---

pkg/arvo/sys/vane/eyre.hoon

eyre: Remove leading sig from password placeholder

---

pkg/interface/publish/src/css/custom.css

publish: dark mode syntax css

---

pkg/hs/urbit-uruk/example/mandelbrot.moon
pkg/hs/urbit-uruk/lib/Urbit/Moon/MoonToUruk.hs
pkg/hs/urbit-uruk/lib/Urbit/Uruk/Class.hs
pkg/hs/urbit-uruk/lib/Urbit/Uruk/DashParser.hs
pkg/hs/urbit-uruk/lib/Urbit/Uruk/JetEval.hs
pkg/hs/urbit-uruk/lib/Urbit/Uruk/JetSpec.hs
pkg/hs/urbit-uruk/lib/Urbit/Uruk/Refr/Jetted.hs

This is a port of the hoon mandelbrot generator to moon and to uruk. I've been running this locally with `moon exec --new example/mandelbrot.moon`, but as you said, this is slow.
This adds a few jets and hooks up every jet needed by the generator into the global table.

Uruk mandelbrot

---

pkg/arvo/app/launch.hoon
pkg/arvo/gen/who.hoon

The /who endpoint responds with the name of the ship in JSON. Necessary to validate the success of DNS binding in Bridge to enable one-click login.
- I added the %serve card to `launch`, unsure if this is the best place for it or not.

/who JSON endpoint

---

pkg/interface/link/src/js/components/link.js
pkg/interface/publish/src/js/components/lib/comments.js

link, publish: submit comment on ctrl+enter

---

pkg/interface/groups/src/css/custom.css
pkg/interface/groups/src/js/components/lib/contact-card.js
pkg/interface/groups/src/js/components/lib/contact-sidebar.js
pkg/interface/groups/src/js/components/lib/group-sidebar.js
pkg/interface/link/src/js/components/lib/channel-sidebar.js

In #2642 I forgot two cases that led to the skeleton having inconsistent border colouring; I went through and checked in both light and dark modes and this should finally bring consistency.

groups, link: skeleton fixes

---

pkg/arvo/app/launch.hoon

Fixes the issue with the homepage breaking. I think this was cause by this PR: https://github.com/urbit/urbit/pull/2656

launch: handle change in url parsing

---

pkg/interface/link/src/js/components/settings.js

This wasn't bound, nor calling, correctly.

link fe: fix "mark all as read" button

---

pkg/interface/chat/src/js/components/lib/message.js

Copies patp to clipboard when user clicks on the nickname/patp of the author of a message.

chat-fe: copy patp to clipboard on author name click

---

bin/solid.pill
pkg/arvo/sys/hoon.hoon
pkg/arvo/tests/sys/hoon/map.hoon

Fixes https://github.com/urbit/urbit/issues/2413

hoon: +apt:by check for duplicate keys

---

pkg/arvo/mar/publish/comment.hoon

A fix for https://github.com/urbit/urbit/issues/2731
cc @liam-fitzgerald I would set you as the reviewer but thats not an option for some reason. Let me know if this works.

publish: fix bug in comment mark

---

pkg/interface/groups/src/js/components/lib/contact-sidebar.js

Separates the users on ship from other group members in the sidebar
cc: @urcades

groups-js: seperate user's ship from rest of contacts

---

pkg/interface/chat/src/js/components/root.js
pkg/interface/link/src/js/components/root.js
pkg/interface/link/src/js/reducers/link-update.js
pkg/interface/publish/src/js/components/root.js

various-fe: add unread counts to title

---

pkg/arvo/app/publish.hoon
pkg/arvo/mar/publish/action.hoon
pkg/arvo/sur/publish.hoon
pkg/interface/publish/src/js/components/lib/notebook.js
pkg/interface/publish/src/js/components/lib/settings.js
pkg/interface/publish/src/js/components/root.js
pkg/interface/publish/src/js/reducers/primary.js

This PR adds the ability to turn a notebook into a group, or attach it to an existing group.

publish: groupify notebooks

---

pkg/interface/groups/src/js/api.js
pkg/interface/groups/src/js/components/lib/contact-card.js

This could be a little prettier, but it's entirely functional and matches the style / uses the same elements as the rest of the contact card.

groups-js: added ability to set avatar images

---

bin/solid.pill
pkg/arvo/sys/vane/gall.hoon

See rationale here: https://github.com/urbit/urbit/issues/2872#issuecomment-625612830

gall: Clear outstanding ack queue to breaching ships

---

pkg/interface/src/lib/s3.js

Dupe of #2868 for SPA version
FIxes #2865

Add ContentType to uploaded s3 images (SPA)

---

bin/ivory.pill
bin/solid.pill
pkg/arvo/sys/hoon.hoon
pkg/urbit/include/jets/w.h
pkg/urbit/jets/e/mole.c
pkg/urbit/jets/e/mule.c
pkg/urbit/jets/tree.c
pkg/urbit/noun/nock.c

This PR includes my review feedback for #2285, modernizes the style of the remaining virtualization gates, and adds new unitary (trace-less) virtualization gates (`+mole` and friends).
/cc @frodwith

hoon: further virtualization improvements

---

pkg/urbit/vere/daemon.c

This is my first time touching vere -- hopefully I got it *mostly* right 😬

vere: handle failed cue of private key file

---

pkg/interface/src/apps/publish/components/lib/settings.js

this UI confused me because it always says "create group" even when you try to "add to group". this PR is for making the string update to "add to group" when a group is selected.
This also fixes the header UI to match others on this screen.
if the different header sizes were intentional, let me know and i can remove that change!

publish: update groupify UI

---

pkg/interface/src/api/chat.js
pkg/interface/src/api/groups.js
pkg/interface/src/apps/chat/app.js
pkg/interface/src/apps/chat/components/chat.js
pkg/interface/src/apps/chat/components/settings.js
pkg/interface/src/apps/groups/components/lib/contact-card.js
pkg/interface/src/apps/groups/components/lib/contact-sidebar.js
pkg/interface/src/reducers/metadata-update.js
pkg/interface/src/store/chat.js

All actions in the following have been tested:
- Chat has been tested to work
- Groups have been tested to work
Current State:
- Haven't tested Links
- Publish doesn't work
- Launch works but the weather / clock tile APIs are not hooked up properly
Note: This concludes my JS work on the SPA for a bit. Moving my attention towards fixing the HTTP redirect bug in Eyre and then `linear-store` and `graph-store` afterwards.

spa: fix bugs in chat and groups, fix metadata reducer

---

pkg/arvo/app/publish.hoon
pkg/interface/src/api/publish.js

publish: fix store reducers

---

pkg/urbit/include/noun/aliases.h
pkg/urbit/include/noun/imprison.h
pkg/urbit/include/vere/serf.h
pkg/urbit/include/vere/vere.h
pkg/urbit/noun/imprison.c
pkg/urbit/noun/retrieve.c
pkg/urbit/tests/mug_tests.c
pkg/urbit/tests/newt_tests.c
pkg/urbit/vere/daemon.c
pkg/urbit/vere/lord.c
pkg/urbit/vere/newt.c
pkg/urbit/vere/pier.c
pkg/urbit/vere/term.c
pkg/urbit/worker/main.c
pkg/urbit/worker/serf.c

I did this work recently on top of #2946 (which was probably a bad idea). PR'ing it now for posterity and legibility -- otherwise it'll be buried in merge commits.

u3/serf: ipc-redux: refactoring and bugfixes 

---

nix/deps-env.nix
nix/pkgs/urbit/default.nix
nix/pkgs/urbit/release.nix
nix/pkgs/urbit/release.sh
nix/release.nix
pkg/urbit/configure
pkg/urbit/daemon/main.c
pkg/urbit/vere/ames.c
pkg/urbit/vere/behn.c
pkg/urbit/vere/foil.c
pkg/urbit/vere/fore.c
pkg/urbit/vere/hind.c
pkg/urbit/vere/newt.c
pkg/urbit/vere/term.c
pkg/urbit/vere/time.c
pkg/urbit/vere/unix.c
pkg/urbit/vere/walk.c
pkg/urbit/worker/serf.c
sh/cross

Fixes #1369 and various related issues.

vere: remove ncurses/terminfo dependency

---

pkg/interface/src/apps/chat/components/chat.js
pkg/interface/src/apps/chat/components/lib/message.js
pkg/interface/src/apps/chat/css/custom.css

- Caps maximum unread backlog that chat will fetch at 1000 messages.
- Adds a scroll container if code is posted and the code will overflow the
width of the page.
- Sets a static height on inline images in chat to prevent loss of scroll
position.

chat: qol fixes

---

pkg/arvo/app/hood.hoon
pkg/arvo/app/launch.hoon
pkg/arvo/app/publish.hoon
pkg/arvo/lib/hood/drum.hoon

All paths bind and file-server starts properly upon going through the SPA OTA process now. We/re good to go now.

spa: fixes for ota

---

pkg/arvo/app/soto.hoon

runs state adapter precisely once.

soto: run +on-load migration once

---

pkg/interface/src/subscription/base.js

should fix event source reconnection issues

interface: correct order of arguments in resubscribe logic

---

.travis.yml
sh/combine-release-builds
sh/release

This adds a new build stage called combine which takes the results
of the previous compile builds and packages them up into one
release tarball per platform.

king: Build release tarballs with both king and vere.

---

pkg/interface/src/apps/chat/components/lib/message.js
pkg/interface/src/apps/links/app.js

fixes unread counts on links, and fixes some image scaling issues that were occuring. 
fixes #2906

links: fix unread counts

---

pkg/arvo/app/wallet.hoon
pkg/arvo/mar/bitcoin/action.hoon
pkg/interface/src/api/wallet.ts
pkg/interface/src/apps/wallet/app.js
pkg/interface/src/apps/wallet/components/lib/bitcoinTransaction.js
pkg/interface/src/reducers/bitcoin-initial.js
pkg/interface/src/store/store.ts
pkg/interface/src/store/wallet.js

@matildepark I tested a full flow here (sync node from seed, request address, derivation, payment, balance update) so it should have most of the necessary stuff for the initial UI work.

bitcoin: fix bug when deriving a new @uc for remote ships

---

pkg/arvo/lib/hood/kiln.hoon
pkg/arvo/sys/vane/eyre.hoon

eyre: give all args to generators

---

README.md

Updated nix install command

---

pkg/interface/src/apps/chat/app.tsx
pkg/interface/src/apps/links/app.js
pkg/interface/src/apps/publish/app.js

Moves the unread counts to the front. 
For @philipcmonk.

interface: reorder unread counts

---

pkg/interface/src/apps/chat/components/settings.js
pkg/interface/src/apps/groups/components/join.js

just a couple fixes i made while playing around with the groups refactor
@liam-fitzgerald

chat, groups: update module name, fix perms

---

pkg/interface/src/apps/links/components/lib/channels-item.js
pkg/interface/src/apps/links/components/lib/group-item.js
pkg/interface/src/apps/publish/components/lib/group-item.js
pkg/interface/src/apps/publish/components/lib/notebook-item.js

Hasty! Forgot to make my channel item changes to the other apps.

link, publish: channel item legibility update

---

pkg/arvo/app/group-store.hoon

Removes scries such that the OTA will succeed with a molting gall.
cc: @tacryt-socryp  can you try this on your ship as well?

group-store: remove scries from OTA logic

---

pkg/arvo/app/contact-hook.hoon
pkg/arvo/app/contact-store.hoon
pkg/arvo/app/metadata-hook.hoon
pkg/arvo/app/metadata-store.hoon

Corrects some bugs introduced by the latest ota, including
- metadata for groups not syncing
- contacts not syncing
- default contacts accidentally getting mangled

ota hotfixes

---

pkg/arvo/app/chat-hook.hoon

About to test this, but putting out for review early. Should fix #3164.
Update: Tested, and confirmed that it is not destructive to working DMs.

chat-hook: recreate all foreign dms as local dms

---

pkg/arvo/app/chat-hook.hoon

Fixes the failed migration in the latest ota

chat-hook: correctly poke chat-view on fix case and fix path

---

pkg/interface/src/apps/chat/components/chat.tsx
pkg/interface/src/apps/chat/components/lib/chat-input.js

chat-js: store unsent message only on unmount

---

pkg/interface/src/apps/publish/components/lib/notebook.js
pkg/interface/src/apps/publish/components/lib/subscribers.js

Adds a 'Add all members as writers' to the subscribers list. Also allows group admins and not just the notebook owner into the subscribers page.

publish-js: add all members as writers button

---

pkg/interface/src/apps/chat/components/lib/content/code.js
pkg/interface/src/apps/chat/components/lib/content/text.js
pkg/interface/src/apps/chat/components/lib/content/url.js
pkg/interface/src/apps/chat/components/lib/message-content.js
pkg/interface/src/apps/chat/components/lib/message.js
pkg/interface/src/reducers/group-update.ts

Starting a process of tackling hairy parts of our interface code to bring them under control :)

interface: refactored chat message component into smaller pieces

---

pkg/arvo/app/chat-hook.hoon

Somehow in the big groups OTA, it became possible for the outgoing subscription map to get out of sync with the "synced" map. In normal operation, this is not allowed. This occurred via unsafe modification of the synced map. This is the root cause of the DM issue. I have made a fix that makes the outgoing subscriptions properly reflect the synced map.

chat-hook: fix synced map getting out of sync with outgoing subscriptions

---

pkg/interface/src/apps/chat/components/lib/chat-input.js

The basic problem was that messages were getting `join`ed with spaces regardless of how they had been split.
This approach is a bit more robust and explicit, plus it sends all messages at the end, instead of sending URLs as it finds them.

Interface: Fixed #3234: chat newline bug

---

pkg/arvo/app/contact-view.hoon

contact-view: poke %group-push-hook correctly

---

pkg/interface/src/App.js
pkg/interface/src/components/StatusBar.js
pkg/interface/src/lib/sigil.js

Interface: Set favicon to ship sigil

---

pkg/hs/urbit-king/TODO.md
pkg/hs/urbit-king/lib/Urbit/King/Config.hs
pkg/hs/urbit-king/lib/Urbit/King/Main.hs
pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs

king: use c vere's heuristics for finding the serf binary

---

pkg/hs/urbit-king/lib/Urbit/Vere/Dawn.hs

@Fang- As discussed in email.
Closes #3258.

king: fix dawn to use the wrapped ethereum server.

---

pkg/interface/src/apps/chat/components/lib/chat-input.js

Only preface the message with a newline if we're on subsequent lines

chat: fixes #3288

---

pkg/interface/src/components/Omnibox.js

This adds one new behavior: the first result is selected, unless a result that *still* matches the current input has previously been selected
It also fixes a minor bug concerning the order of results and tab-to-select behavior
Furthermore, it follows the new linting convention by breaking the rendering of results into a separate method

leap: set default select behavior

---

pkg/interface/src/lib/omnibox.js

A very dumb solution for #3274. Because we already did the work for our join routes to handle autojoining rooms you're already in, we just change the result links to join routes.
Works for
- joining a channel even when you have a fresh session (no data in state to check against)
- returning to a channel even when you have a fresh session (a momentary "joining..." prompt that we can eliminate with scries work)
Nonexistent rooms still produce nonstop loading states, and this needs to be addressed on both ends: we need to clear metadata from breached or deleted content; and we need to error catch bad join requests...but we can solve that separately.
I also linted the omnibox indexing library to separate them into functions. Subscriptions and groups are paired and I couldn't think of a very …

leap: results link to join routes

---

pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs
pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs

king: eyre: add missing printouts with ports

---

pkg/interface/src/App.js
pkg/interface/src/apps/dojo/app.js
pkg/interface/src/apps/launch/app.js
pkg/interface/src/components/Content.js
pkg/interface/src/components/TwoPaneApp.js

This will make it easier for us to move all of the apps in TwoPaneApp into a single layout component. No functionality changed.

interface: broke out routes from main App.js

---

pkg/arvo/app/landscape/index.html

interface: div is not a self-closing tag

---

pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/views/apps/chat/components/join.js

Chat: indigo join page

---

pkg/interface/src/logic/api/local.ts
pkg/interface/src/logic/reducers/local.ts
pkg/interface/src/logic/store/store.ts
pkg/interface/src/logic/store/type.ts
pkg/interface/src/views/App.js
pkg/interface/src/views/apps/dojo/components/input.js

See #3297 and #3323. Provides expected behavior on leap invocation and cancellation, especially within the dojo. Returns the user to previous input when cancelled.

leap: better handling of existing focus

---

pkg/interface/src/views/components/StatusBar.js

As per discussion in #3276, always shows home button in the status bar.

StatusBar: always show home button

---

pkg/interface/src/views/apps/chat/components/lib/chat-editor.js
pkg/interface/src/views/apps/chat/components/lib/chat-input.js

As requested by @urcades in the comments of #3033.

chat: bottom-align UI in input

---

pkg/hs/stack.yaml

v0.3.2 included an important bug fix that should be pulled in here.

urbit-king: update urbit-hob to v0.3.3

---

pkg/interface/src/views/apps/groups/components/new.tsx

groups: trim name on create

---

pkg/interface/src/logic/lib/sigil.js
pkg/interface/src/views/App.js

I was going to roll this into the virtualization PR but after @liam-fitzgerald's comments on #3356 I figured this would be a good fix all by itself. Basically this a) makes the sigil component a function instead of a class and b) memoizes it. I don't have any metrics but on paper it's better and it doesn't hurt

interface: Sigil speedup

---

pkg/interface/src/views/components/InviteSearch.tsx

interface: deduplicate InviteSearch results

---

pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/views/App.js
pkg/interface/src/views/apps/chat/app.tsx
pkg/interface/src/views/apps/dojo/app.js
pkg/interface/src/views/apps/groups/app.tsx
pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/links/app.js
pkg/interface/src/views/apps/publish/app.tsx

Made head reactive. Also took out the tracking of unseenTotal on each app because it didn't seem to do anything?

interface: made head reactive

---

pkg/arvo/sys/vane/clay.hoon

fixes #3317
Tested with both `|commit` and `|autocommit`

clay: if commit would be a no-op, don't commit it

---

pkg/arvo/app/chat-view.hoon
pkg/arvo/app/contact-view.hoon
pkg/arvo/app/file-server.hoon
pkg/arvo/app/launch.hoon
pkg/arvo/app/link-view.hoon
pkg/arvo/app/publish.hoon
pkg/arvo/app/soto.hoon
pkg/arvo/sur/file-server.hoon

file-server: fix %file-server by adding SPA flag and threading is-file through request

---

pkg/interface/src/views/apps/chat/components/chat.tsx
pkg/interface/src/views/apps/chat/components/lib/chat-input.js

chat: hideAvatars hides chat input avatar

---

pkg/interface/src/views/apps/chat/components/new-dm.js

Shortens comets and moons in the DM title

chat: cite patps in DM title

---

pkg/interface/src/views/apps/chat/app.tsx
pkg/interface/src/views/apps/links/app.js
pkg/interface/src/views/apps/publish/app.tsx

By the decree of @galenwp 
Updates title whilst tab is in the background
cc: @tylershuster this look ok to you?

interface: update title eagerly

---

pkg/arvo/app/graph-store.hoon
pkg/arvo/lib/graph-store.hoon
pkg/interface/src/logic/api/global.ts
pkg/interface/src/logic/api/graph.ts
pkg/interface/src/logic/reducers/graph-update.js
pkg/interface/src/logic/store/store.ts
pkg/interface/src/logic/store/type.ts
pkg/interface/src/logic/subscription/global.ts
pkg/interface/src/views/apps/links/app.js

Works fine and has no functionality changes. Will append and test scrying functionality to this PR, then we can get it merged with no functionality changes. Will make it easier to review the Links migration as its own thing.

interface: added graph reducer, store state, and subscription

---

pkg/interface/src/views/apps/chat/css/custom.css

Fixes issue introduced in https://github.com/urbit/urbit/commit/f2eeb7a14f5846d70ba7d298fe86817a36dca6ad

chat: break up inline code while maintaining multiline codeblocks

---

pkg/interface/src/logic/lib/tokenizeMessage.js
pkg/interface/src/views/apps/chat/components/lib/chat-input.js
pkg/interface/src/views/apps/links/components/lib/comment-item.js
pkg/interface/src/views/apps/links/components/lib/comments.js
pkg/interface/src/views/apps/links/components/link.js
pkg/interface/src/views/apps/publish/app.tsx
pkg/interface/src/views/apps/publish/components/lib/CommentItem.tsx
pkg/interface/src/views/apps/publish/components/lib/Comments.tsx
pkg/interface/src/views/apps/publish/components/lib/Note.tsx
pkg/interface/src/views/apps/publish/components/lib/NotebookRoutes.tsx
pkg/interface/src/views/components/RemoteContent.tsx
pkg/interface/src/views/components/RichText.js

Fixes https://github.com/urbit/landscape/issues/77
Deduplicates some of the message parsing logic.
Does not fix some of the fragmentation/non-indigoness between apps, but should be just as easy to fix later

links, publish: display rich text comments

---

pkg/arvo/lib/pull-hook.hoon
pkg/arvo/lib/push-hook.hoon

documents both the helper libraries for building hooks.

lib-hooks: document with comments

---

pkg/interface/src/views/apps/chat/components/lib/chat-editor.js

Addresses https://github.com/urbit/landscape/issues/82

chat: added ability to blur chat editor

---

pkg/interface/src/logic/api/publish.ts
pkg/interface/src/logic/lib/useWaitForProps.ts
pkg/interface/src/logic/reducers/group-update.ts
pkg/interface/src/views/apps/publish/app.tsx
pkg/interface/src/views/apps/publish/components/lib/GroupifyForm.tsx
pkg/interface/src/views/apps/publish/components/lib/Join.tsx
pkg/interface/src/views/apps/publish/components/lib/MetadataForm.tsx
pkg/interface/src/views/apps/publish/components/lib/Notebook.tsx
pkg/interface/src/views/apps/publish/components/lib/NotebookRoutes.tsx
pkg/interface/src/views/apps/publish/components/lib/Settings.tsx
pkg/interface/src/views/components/GroupSearch.tsx

- Does not timeout publish join flow
- Exposes groupify in settings UI

publish: don't timeout, show groupify

---

pkg/interface/src/views/apps/chat/components/lib/group-item.js

chat: check for cited participants in sidebar

---

pkg/interface/src/views/apps/chat/components/lib/chat-window.tsx

Fixes issue created in scroll PR

chat: added placeholder for empty room

---

pkg/interface/src/views/components/leap/Omnibox.js

Logging out currently doesn't work via Leap because we only use
react-router. This adds selection and navigation logic that passes
both app name and link href and compares app name against the default
app lib. This makes leap extensible for third party apps, too.

leap: use a instead of Link, if not default app

---

pkg/interface/src/logic/store/store.ts

By @vvisigoth request.
cc @tylershuster: this isn't set anywhere else, is it?

interface: embeds on by default

---

pkg/interface/src/views/components/StatusBar.js

This was to go out with the last feature OTA, but regressed in #3236, so it's reinstated here.

interface: always show home button

---

pkg/interface/src/views/apps/publish/components/lib/Subscribers.tsx
pkg/interface/src/views/components/Group.tsx

publish: check roles correctly for tags

---

pkg/interface/src/views/apps/chat/components/chat.tsx
pkg/interface/src/views/apps/chat/components/lib/ChatHeader.js
pkg/interface/src/views/apps/chat/components/lib/ChatInput.tsx
pkg/interface/src/views/apps/chat/components/lib/ChatMessage.tsx
pkg/interface/src/views/apps/chat/components/lib/ChatWindow.tsx
pkg/interface/src/views/apps/chat/components/lib/group-item.js
pkg/interface/src/views/apps/chat/components/settings.js
pkg/interface/src/views/components/VirtualScroller.tsx

@matildepark 
Well...check it out.

chat: fixes

---

pkg/arvo/app/graph-store.hoon
pkg/arvo/lib/signatures.hoon
pkg/arvo/mar/graph/update.hoon

Fix signing nodes with graph-store

graph-store: fix signatures & marks

---

pkg/interface/src/views/components/VirtualScroller.tsx

fixes #3493
@Fang- can you confirm? I only saw it in Safari but this fixes it there

chat: fixes dancing timestamps

---

pkg/interface/src/logic/api/chat.ts
pkg/interface/src/logic/api/graph.ts
pkg/interface/src/logic/api/launch.ts
pkg/interface/src/logic/api/links.ts
pkg/interface/src/logic/api/publish.ts
pkg/interface/src/logic/api/s3.ts

ensures that all API methods return promises, for chaining
~incidentally fixes #3505~

all: standardize API response types

---

pkg/interface/src/views/components/RemoteContent.tsx

all: noop on unmounted fetch embed error

---

pkg/interface/src/views/components/VirtualScroller.tsx

chat: fixes scroll keys

---

pkg/interface/src/views/apps/chat/components/chat.tsx
pkg/interface/src/views/apps/chat/components/lib/ChatInput.tsx

Fixes #3482 and an unfiled bug where files would post twice on safari

chat: fixes drag-and-drop bugs

---

pkg/interface/src/views/components/InviteSearch.tsx

all: exclude ships from invite search when shipResults is false

---

pkg/interface/src/views/apps/publish/components/lib/Join.tsx
pkg/interface/src/views/apps/publish/components/lib/Notebook.tsx

publish: allow unsubscribing from notebooks

---

pkg/interface/src/views/components/Error.tsx

all: fixes error stack trace in dark mode

---

pkg/interface/src/views/apps/chat/components/lib/ChatWindow.tsx

chat: fixes misses pending messages

---

pkg/interface/src/views/App.js

fixes urbit/landscape#87
Also fixes reversed scroll dragging in Chrome...?

all: sets scrollbar colors

---

pkg/interface/src/views/apps/chat/components/lib/ChatMessage.tsx
pkg/interface/src/views/apps/chat/components/lib/ChatWindow.tsx

fixes #3495, ~introduces new "collapse-on-read" behavior to prevent jumping~

chat: fixes unread marker behavior

---

pkg/arvo/lib/push-hook.hoon
pkg/arvo/ted/graph/join.hoon
pkg/interface/src/logic/api/graph.ts

- Fixes the kick path
- Proxy local pokes to the correct push-hook/store
- Fixes join thread by pathifying the resource

lib/push-hook: Fix kick path and proxy local pokes

---

pkg/interface/src/views/apps/links/components/lib/link-submit.tsx

links: prevents title from being overwritten

---

pkg/arvo/README.md

This wasn't updated to match "recent" changes to how testing works.

readme: update arvo test command

---

pkg/interface/src/views/components/leap/OmniboxResult.js

leap: thin the dojo caret

---

pkg/arvo/app/chat-hook.hoon

chat-hook: fix dumb mistake

---

pkg/urbit/vere/io/term.c

As per https://github.com/urbit/urbit/pull/3480#discussion_r487219868.

term: don't print styles in non-interactive mode

---

bin/solid.pill
pkg/arvo/mar/atom.hoon
pkg/arvo/mar/eth/txs.hoon
pkg/arvo/mar/md.hoon
pkg/arvo/mar/pem.hoon
pkg/arvo/mar/pill.hoon
pkg/arvo/mar/publish/comment.hoon
pkg/arvo/mar/publish/info.hoon
pkg/arvo/mar/txt.hoon
pkg/arvo/mar/udon.hoon
pkg/arvo/mar/umd.hoon
pkg/arvo/sys/zuse.hoon

And update all references. Follows up #3554

zuse: remove duplicate $octs definition

---

pkg/urbit/include/jets/q.h
pkg/urbit/include/jets/w.h
pkg/urbit/include/noun/retrieve.h
pkg/urbit/include/noun/xtract.h
pkg/urbit/jets/e/base.c
pkg/urbit/jets/tree.c
pkg/urbit/noun/retrieve.c
pkg/urbit/tests/jet_tests.c

Jets for the new implementations in #3576.

vere: adds jets for en/decoding base16

---

pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/launch/components/Groups.tsx
pkg/interface/src/views/apps/launch/components/tiles/basic.js
pkg/interface/src/views/apps/launch/components/tiles/clock.js
pkg/interface/src/views/apps/launch/components/tiles/tile.js
pkg/interface/src/views/apps/launch/components/tiles/weather.js
pkg/interface/src/views/apps/launch/components/welcome.js

Big changes to how tiles are rendered. Still needs more work but this is better than it was.
~Also incidentally starts to fix some of the weird text-sizing in chat, awaiting further indigoification~

launch: fixing layout

---

pkg/interface/src/views/apps/chat/components/profile-overlay.js
pkg/interface/src/views/apps/profile/components/lib/BucketList.tsx
pkg/interface/src/views/apps/profile/components/lib/DisplayForm.tsx
pkg/interface/src/views/apps/profile/components/lib/RemoteContent.tsx
pkg/interface/src/views/apps/profile/components/lib/S3Form.tsx
pkg/interface/src/views/apps/profile/components/lib/Security.tsx
pkg/interface/src/views/apps/publish/components/Notebook.tsx
pkg/interface/src/views/apps/publish/components/Settings.tsx
pkg/interface/src/views/apps/publish/components/Subscribers.tsx
pkg/interface/src/views/components/AsyncButton.tsx
pkg/interface/src/views/components/RemoteContent.tsx
pkg/interface/src/views/components/StatelessAsyncButton.tsx
pkg/interface/src/views/components/UnjoinedResource.tsx
pkg/interface/src/views/landscape/components/GroupSettings.tsx
pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
pkg/interface/src/views/landscape/components/PopoverRoutes.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarListHeader.tsx

Just pushing this because I can see you're working on the same tasks. -_-

interface: more design nits

---

pkg/interface/src/views/apps/launch/components/Groups.tsx

I only wrote this to accept the invite, not to join the group via the contacts API, so the invite would disappear but do nothing.

launch: accept group invites correctly

---

pkg/interface/src/views/apps/launch/components/tiles/clock.js
pkg/interface/src/views/apps/launch/components/tiles/tile.js
pkg/interface/src/views/apps/launch/components/tiles/weather.js

Made color value edits to a few launch elements, that's all.

launch: edited colors+values for clock, weather, and tile borders

---

pkg/arvo/sys/vane/eyre.hoon

Instead of always providing a wildcard for the allowed methods and headers, now echoes back the method and headers that the client said it's going to use, if any.
@tylershuster can you give this a try and confirm it fixes #3676?

eyre: explicitly permit proposed request in cors

---

pkg/hs/urbit-king/lib/Urbit/King/App.hs

Add the following to `pier` in Vere/Pier.hs:
```
void $ acquireWorker "crazy log tester" $ forever $ do
logError "wow amazing wow"
threadDelay 200_000
```
and run the king with --stderr. Before this change, the output will look something like
```
~zod:chat-cli: wow amazing wow
wow amazing wow
wow amazing wow
wow amazing wow
```
and after it looks like
```
~zod:chat-cli: wow amazing wow
wow amazing wow
wow amazing wow
wow amazing wow
```
This should make the more verbose logging modes substantially more usable and less scary.
Note: It's still an open question in my mind whether this is the thing we should be doing, or if we should instead be sending "stderr" logs to the terminal multiplexing system. Even if the latter, this is such a win in the short term that I think it should be …

Fix zigzag in --stderr logging

---

pkg/urbit/vere/io/ames.c

This resolves an irritating issue wherein the ames i/o driver spams error messages if the network goes down, the machine goes to sleep, &c.

vere: updates ames to only print network send failures once

---

pkg/interface/src/views/landscape/components/JoinGroup.tsx
pkg/interface/src/views/landscape/index.tsx

Restore automatic joining route

JoinGroup: restore autojoin

---

pkg/interface/src/views/landscape/components/NewChannel.tsx

interface: fix DM creation to give group permissions properly

---

pkg/hs/urbit-king/lib/Urbit/King/App.hs

This reverts commit e9ed97f8a82fb43992f8d1a16503e4565ea1b040.
This breaks slogs; we are constantly overwriting the last line in our boot output. I suspect that you really will have to send the --stderr messages to the terminal system.

Revert "king: fix zig-zag in stderr logging"

---

pkg/interface/src/views/components/ColorInput.tsx

Fixes https://github.com/urbit/landscape/issues/118

profile: add html color picker

---

pkg/interface/src/views/landscape/components/Participants.tsx

- Adds 'kick' action for admins, because sometimes you need to just give a ship a kick (if breached, etc.)

groups: add 'kick from' action

---

pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/launch/components/tiles/tile.js
pkg/interface/src/views/apps/launch/components/tiles/weather.js
pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx

Addresses urbit/landscape#114.
cc @urcades

interface: enforce border radius

---

pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/launch/components/tiles/basic.js
pkg/interface/src/views/apps/launch/components/tiles/custom.js
pkg/interface/src/views/apps/launch/components/tiles/weather.js

launch: migrate remainders to indigo-react

---

pkg/interface/src/views/apps/launch/components/tiles/clock.js

clock: render in SVG, show moon phase

---

pkg/urbit/daemon/main.c

Make the help text deserve your trust.

vere: fix -j help text

---

pkg/interface/src/views/apps/launch/components/tiles/clock.js

Revert "clock: render in SVG, show moon phase"

---

pkg/interface/src/views/apps/launch/components/tiles/clock.js

clock: svg with mask

---

pkg/interface/src/views/apps/launch/components/tiles/weather.js

Keeping my one line fix streak alive.

weather: fix api call

---

pkg/interface/src/views/components/DropdownSearch.tsx
pkg/interface/src/views/components/ShipSearch.tsx
pkg/interface/src/views/landscape/components/InvitePopover.tsx

landscape: allow autofocusing ship select

---

pkg/interface/src/views/apps/publish/components/EditPost.tsx

Fixes #3596
Not sure if this needs to be done in `<Note />` as well, just assumed that it does because it draws from the same thing.

publish: don't insert newline

---

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx

fixes https://github.com/urbit/landscape/issues/125

chat: fixes relative datestamps

---

pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/launch/components/Groups.tsx
pkg/interface/src/views/apps/launch/components/tiles/tile.js

Depends on https://github.com/urbit/urbit/pull/3767, which is included here for an accurate rendering of the clock
@urcades this was pretty easy to implement. Would appreciate any feedback.

Home tiles

---

pkg/interface/src/logic/reducers/group-update.ts

Brings behaviour in line with group-store agent.

groups-js: add ourselves to admin in group-update reducer

---

package-lock.json
pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/components/StatusBar.js
pkg/interface/src/views/components/StatusBarItem.tsx

- update to indigo-react 1.2.12
- home tile color fix
- header buttons now square
- foxed padding on header bar
- Update 'home button' icon and 'home tile' icon

UI tweaks + QA Fixes

---

pkg/interface/src/views/landscape/components/Participants.tsx

landscape: give private groups kicking ability

---

pkg/hs/urbit-king/lib/Urbit/Vere/Ames/Packet.hs

When I merged on top of bren's pr, I failed to notice this.

king: Fix MonadFail issue in Packet.hs

---

pkg/interface/src/logic/lib/util.js
pkg/interface/src/views/apps/publish/components/MarkdownEditor.tsx
pkg/interface/src/views/landscape/components/GroupSettings.tsx

don't do it @galenwp 
(two commits preventing accidental deletion of data — feel free to suggest more)

Antiautodefenestration

---

pkg/interface/src/views/apps/launch/app.js

fixes https://github.com/urbit/landscape/issues/129

launch: fixes tile padding

---

pkg/interface/src/views/apps/publish/components/NotePreview.tsx

fixes https://github.com/urbit/urbit/issues/3841

publish: fixes single revision plurality

---

pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx

fixes https://github.com/urbit/landscape/issues/132

---

ci.nix

@joemfb ain't got time for that.

build: remove from-scratch ropsten pill builds on ci

---

pkg/interface/src/views/apps/launch/components/tiles/clock.js

clock: add background to moon

---

pkg/interface/src/views/apps/chat/components/chat-editor.js

fixes https://github.com/urbit/landscape/issues/140

chat: unify line-height

---

pkg/arvo/lib/pull-hook.hoon

The crashing of the %fact handling in the #3895 fix caused the subscriptions to be removed. Adds a migration case to readd any missing subscriptions

pull-hook: rewatch missing subscriptions

---

ci.nix
default.nix
nix/default.nix
nix/lib/default.nix
nix/lib/push-storage-object.nix
nix/overlays/native.nix
nix/pkgs/hs/default.nix
nix/pkgs/urbit/default.nix

Anything from `pkgs.pkgsStatic` will have the [static adapter](https://github.com/NixOS/nixpkgs/blob/af7f9e5fa098e339d64ddfc1ea00bcd430210d0e/pkgs/top-level/static.nix#L22-L35) for Darwin applied, which includes running `install_name_tool` in the derivation's `fixupPhase`. 
Haskell packages are not pulled from `pkgs.pkgsStatic` when `enableStatic = true` as we don't want to build GHC statically, so this means our Darwin `mkDerivation` for Haskell packages doesn't get the `install_name_tool` fixup like other non-Haskell packages. I've added it as a `haskell.nix` module option for the KH binary under `nix/pkgs/hs/default.nix`.
(There was a bit of movement in `default.nix` and `nix/default.nix` related to the latter - but the primary change is in `nix/pkgs/hs/default.nix`.)
Result:
``` …
```

build: ensure urbit-king release binary links against /usr/lib not /nix/store

---

pkg/arvo/app/glob.hoon
pkg/arvo/app/landscape/index.html
pkg/interface/src/views/App.js
pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/launch/components/Groups.tsx
pkg/interface/src/views/apps/notifications/header.tsx
pkg/interface/src/views/apps/notifications/inbox.tsx
pkg/interface/src/views/apps/notifications/notification.tsx
pkg/interface/src/views/apps/notifications/notifications.tsx
pkg/interface/src/views/apps/notifications/preferences.tsx
pkg/interface/src/views/components/StatusBar.js
pkg/interface/src/views/components/StatusBarItem.tsx
pkg/interface/src/views/components/leap/Omnibox.js
pkg/interface/src/views/components/leap/OmniboxResult.js
pkg/interface/src/views/landscape/components/GroupSwitcher.tsx

Handful of FE tweaks for obvious QA fixes. Still need to amend some behaviours; see if we can show invites in the notifications menu (as per @vvisigoth), etc.

hark: first QA pass

---

pkg/interface/src/views/apps/launch/app.js

Fixes https://github.com/urbit/landscape/issues/162

launch: click to copy base hash

---

bin/solid.pill
pkg/arvo/sys/hoon.hoon

Fixes #3600.
cc @pilfer-pandex @joemfb

hoon: preserve callsite type on wet core in ++felt

---

pkg/interface/src/views/apps/publish/components/Writers.js
pkg/interface/src/views/landscape/components/ChannelSettings.tsx
pkg/interface/src/views/landscape/components/Resource.tsx

publish: Restore basic 'add writers' form

---

pkg/interface/src/views/apps/launch/components/Groups.tsx
pkg/interface/src/views/apps/notifications/inbox.tsx
pkg/interface/src/views/apps/notifications/notifications.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarList.tsx

- Scroll on load
- Hide empty timeboxes
- Loosen property access in various places to fix crashes

hotfix: OTA bugs

---

pkg/interface/src/views/apps/term/app.js
pkg/interface/src/views/apps/term/components/history.js
pkg/interface/src/views/apps/term/components/input.js
pkg/interface/src/views/apps/term/components/line.js
pkg/interface/src/views/apps/term/css/custom.css

I thought this was already done in the Term work, but it wasn't, so I just do it here. Tested on desktop and on iOS, works normally. Matches code styling in chat.
cc @urcades

webterm: migrate to indigo-react

---

pkg/interface/src/views/landscape/components/GroupSettings/Personal.tsx

groups: only prompt to delete on ownership

---

pkg/arvo/app/weather.hoon
pkg/interface/src/logic/api/launch.ts
pkg/interface/src/views/apps/launch/components/tiles/weather.js

weather: change API

---

pkg/interface/src/views/apps/publish/components/NotebookRoutes.tsx

publish: add loading spinner for notebooks

---

pkg/interface/src/views/components/DropdownSearch.tsx
pkg/interface/src/views/components/ShipSearch.tsx
pkg/interface/src/views/landscape/components/InvitePopover.tsx

Fixes #3824
...or nearly does. There's a problem where when you've entered a ship, then you go to type in another one, it clears the current value (preventing you from selecting multiple). @liam-fitzgerald you know react hooks & formik better than I. Can you point out what I'm doing wrong in `ShipSearch.tsx`?
A hint: in `onChange`, `value` is set to a blank array when it fires for the first time after selecting a ship, although the component later on knows that there is something in `value`.

groups: better ship search validation

---

bin/solid.pill
pkg/arvo/gen/hood/doze.hoon
pkg/arvo/gen/hood/fade.hoon
pkg/arvo/gen/hood/pass.hoon
pkg/arvo/lib/hood/drum.hoon
pkg/arvo/lib/hood/helm.hoon
pkg/arvo/sys/vane/clay.hoon
pkg/arvo/sys/vane/gall.hoon
pkg/arvo/sys/zuse.hoon

NB: this has breaking changes without state adapters!  It also changes Gall's wire format with no adapters.  Hopefully this can go into the breach, else I can write those later.
Uninstalling or suspending apps is useful when trying out unstable builds or 3rd party apps.  There's a few ways we can implement this:
- `%gone`:
- unsubscribe from all incoming and outgoing subscriptions
- delete state
- risks
- outstanding pokes don't get acknowledged
- outstanding kernel requests don't get canceled
- `%doze`:
- don't unsubscribe
- resolve to state (i.e. call +on-save)
- queue deals and agent signs to be run once agent resumes
- makes app no longer block updates
- allows resuming later
- risks
- app becomes nonresponsive without notifying subscription clients
- might miss responses from kernel …

gall: Allow deleting or suspending an app

---

pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/views/apps/launch/components/tiles/tile.js

bumps indigo to to new version and adjusts breakage. Will modify to point at npm when the associated PR is merged

interface: bump indigo

---

pkg/arvo/sys/vane/eyre.hoon
pkg/arvo/tests/sys/vane/eyre.hoon

fixes https://github.com/urbit/landscape/issues/154
!
@Fang- @matildepark

login: translate to indigo

---

pkg/interface/src/views/App.js

landscape: remove ~2020.12 breach banner

---

pkg/interface/src/views/apps/launch/components/tiles.js
pkg/interface/src/views/apps/launch/components/tiles/clock.js

clock: use new weather data

---

pkg/interface/src/views/apps/launch/components/tiles/weather.js

Fixes https://github.com/urbit/landscape/issues/190

clock: ignore cached date for sunrise

---

pkg/arvo/app/observe-hook.hoon
pkg/arvo/app/spider.hoon
pkg/arvo/ted/group/on-leave.hoon

Fixes #2992 for good. Depends on #4119.

group-on-leave: soften de-path to fix thread and add thread back to observe-hook state

---

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/components/CommentItem.tsx
pkg/interface/src/views/components/MentionText.tsx

- Passes the correct timestamp to Daybreak (#4127)
- Passes CalmEngine props to Mention components (#4130)

chat: fixes two regressions

---

pkg/interface/src/views/apps/chat/ChatResource.tsx
pkg/interface/src/views/apps/chat/components/ChatWindow.tsx

Load smaller amounts of backlog when displaying a chat

chat: lazier chat loading

---

pkg/urbit/vere/pier.c

Previously, we would crash on attempting to `+scot` cells, or parse
invalid paths. Now we catch those cases, and print legible error
messages instead.

vere: report, not crash, on unreasonable -Y and -Z

---

.github/workflows/merge.yml

Adds a workflow that, on any push to master, merges master to release/next-js.

Add a GitHub workflow that auto-merges master to release/next-js on push

---

pkg/arvo/app/landscape/index.html
pkg/interface/package-lock.json
pkg/interface/public/index.html
pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/profile/profile.tsx
pkg/interface/src/views/apps/term/app.js
pkg/interface/src/views/landscape/components/GroupsPane.tsx
pkg/interface/src/views/landscape/components/Resource.tsx
pkg/interface/src/views/landscape/index.tsx

This changes the name of the app across the board from "OS1" to "Landscape."
It also changes the document title as you navigate around the app, including surfacing notification counts.

interface: document title

---

pkg/arvo/ted/graph/delete.hoon

graph-delete-thread: remove entry from metadata-store, then remove entry from metadata-hook

---

pkg/arvo/sur/file-server.hoon

People like serving files, so questions about these come up a lot. Having brief descriptions of the exposed functionality here would probably go a long way.

file-server: inline docs for actions

---

pkg/interface/src/views/landscape/components/ChannelMenu.tsx

fixes #4199
saving glass panes since 2020

groups: confirm channel deletion

---

pkg/interface/src/views/apps/publish/components/Note.tsx

publish: fixes two behaviors on navigation

---

pkg/interface/src/views/apps/notifications/notifications.tsx

fixes https://github.com/urbit/landscape/issues/222

interface: put dynamic title on inbox

---

pkg/interface/src/views/apps/launch/app.js

fixes https://github.com/urbit/landscape/issues/166
I also made the color a bit better.
Tested in Firefox, Chrome, and Safari in both light and dark mode.

launch: fix hash color and mobile position

---

pkg/interface/src/views/apps/chat/components/chat-editor.js

fixes https://github.com/urbit/landscape/issues/230
uses code shamelessly swiped from https://codepen.io/shshaw/pen/c72208b279d750f1ab46b6a45bbd04d7 via https://css-tricks.com/auto-growing-inputs-textareas/

chat: fix sizing on mobile

---

pkg/interface/package-lock.json
pkg/interface/package.json

interface: bump sigil-js

---

pkg/arvo/app/hark-store.hoon

Hark, when calculating unread totals was ignoring notifications that
were under the same stats-index, but a different index. Reworks the
cache to calculate unread totals correctly.
Fixes urbit/landscape#236

hark-store: rework caching to correctly calculate unread totals

---

pkg/interface/src/logic/lib/util.ts
pkg/interface/src/logic/state/local.tsx
pkg/interface/src/views/apps/notifications/graph.tsx
pkg/interface/src/views/apps/notifications/header.tsx
pkg/interface/src/views/apps/notifications/inbox.tsx
pkg/interface/src/views/apps/notifications/notification.tsx
pkg/interface/src/views/components/MentionText.tsx
pkg/interface/src/views/components/RichText.js

fixes https://github.com/urbit/landscape/issues/218
fixes https://github.com/urbit/landscape/issues/237
before:
after:
also fixes an unfiled bug where leap crashes if state.suspendedfocus is invalid
I don't understand a lot of how the inbox is set up, but I think this is sane, so ping @liam-fitzgerald

notifications: fix layout

---

pkg/arvo/ted/graph/join.hoon
pkg/interface/src/logic/api/graph.ts

Pushes the pathological case back a bit, but doesn't make it stop trying.
This compiles, but I haven't been able to actually run the specific code I changed. @liam-fitzgerald, @tacryt-socryp, please advise.
This is a _partial_ fix for #4211. The full fix is making this also stop trying at some point, but I'm not sure what the right behavior for that case would be.

graph: make the join thread back off

---

package-lock.json
pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/views/components/AsyncButton.tsx
pkg/interface/src/views/components/StatelessAsyncAction.tsx
pkg/interface/src/views/components/StatelessAsyncButton.tsx

Supersedes #4070, #3877, don't merge until the changes are in indigo-react. Re-opened after #4070 auto-closed.

AsyncButton: protect against double submit

---

pkg/interface/src/views/apps/notifications/inbox.tsx

fixes urbit/landscape#252

---

pkg/interface/src/views/apps/links/LinkWindow.tsx

Fixes unfiled bug where creating a new collection returned a blank
screen.

links: return submit if no 'first item'

---

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/components/OverlaySigil.tsx

Fixes https://github.com/urbit/landscape/issues/317

chat: fixes wobble

---

pkg/interface/package-lock.json
pkg/interface/src/logic/api/hark.ts
pkg/interface/src/logic/lib/useLazyScroll.ts
pkg/interface/src/types/invite-update.ts
pkg/interface/src/views/apps/notifications/inbox.tsx
pkg/interface/src/views/apps/notifications/invites.tsx
pkg/interface/src/views/apps/notifications/notification.tsx

- Lazy loads notifications correctly
- Acknowledges the end of notifications (i.e. when they've all been loaded)
Fixes urbit/landscape#266

notifications: lazy load correctly

---

pkg/arvo/app/settings-store.hoon
pkg/arvo/app/settings.hoon
pkg/arvo/lib/settings.hoon
pkg/arvo/mar/settings/data.hoon
pkg/arvo/mar/settings/event.hoon
pkg/arvo/sur/settings.hoon
pkg/interface/src/logic/api/global.ts
pkg/interface/src/logic/api/settings.ts
pkg/interface/src/logic/reducers/settings-update.ts
pkg/interface/src/logic/store/store.ts
pkg/interface/src/logic/subscription/global.ts
pkg/interface/src/types/cage.ts
pkg/interface/src/types/settings.ts
pkg/interface/src/views/App.js

Draft PR for the settings store. Still need to do frontend stuff.
Can someone tell me if I have the pattern right for scrying? I wasn't sure if I should return `~` or `[~ ~]` when scrying for a thing that doesn't exist, but might exist in the future.

settings store

---

pkg/interface/src/views/apps/chat/components/unread-notice.js

Fixes https://github.com/urbit/landscape/issues/322

chat: fixes banner pluralization

---

pkg/interface/src/views/apps/chat/components/ChatWindow.tsx

Eliminates the friction quite a bit! See urbit/landscape#332.
cc @tylershuster

chat: set initialisation time to 100ms

---

pkg/interface/src/views/apps/profile/components/lib/BackgroundPicker.tsx
pkg/interface/src/views/apps/profile/components/settings.tsx
pkg/interface/src/views/components/ImageInput.tsx

Fixes https://github.com/urbit/landscape/issues/325
Slightly different behavior — sometimes wraps on small screens.

interface: changes wrapping behavior

---

pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/launch/components/tiles/tile.js

fixes https://github.com/urbit/landscape/issues/262

launch: changes tile border color

---

pkg/interface/src/views/apps/chat/ChatResource.tsx
pkg/interface/src/views/apps/chat/components/ShareProfile.js

Needs conditional render logic ("have we already shared?") and hooking into API call to share.

chat: add stubbed share banner

---

pkg/arvo/lib/contact-store.hoon
pkg/interface/src/logic/reducers/contact-update.ts
pkg/interface/src/views/apps/profile/components/EditProfile.tsx
pkg/interface/src/views/components/GroupSearch.tsx

- Cleanups GroupSearch to prevent funky behaviour cause by formik and its field comparisons
- Allows for add/remove of pinned profiles from groups

Contacts: cleanup GroupSearch, allow add/remove of pinned groups from profile

---

pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/Notifications.tsx
pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/index.tsx
pkg/interface/src/views/landscape/components/Participants.tsx

Fixed flex things bunching up into each other and added "View profile" option to Participants component.

interface: popover settings style fixes

---

pkg/interface/src/logic/lib/omnibox.js
pkg/interface/src/views/apps/chat/components/ShareProfile.js
pkg/interface/src/views/components/ProfileOverlay.tsx
pkg/interface/src/views/components/SetStatusBarModal.js
pkg/interface/src/views/components/StatusBar.js

Throwing fixes in here:
- https://github.com/urbit/landscape/issues/339
- https://github.com/urbit/landscape/issues/340
- https://github.com/urbit/landscape/issues/343
- https://github.com/urbit/landscape/issues/341

interface: fix visual bugs found in QA

---

pkg/interface/src/logic/lib/useModal.tsx
pkg/interface/src/logic/reducers/contact-update.ts
pkg/interface/src/views/apps/chat/ChatResource.tsx
pkg/interface/src/views/landscape/components/DeleteGroup.tsx
pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
pkg/interface/src/views/landscape/components/JoinGroup.tsx
pkg/interface/src/views/landscape/components/NewChannel.tsx
pkg/interface/src/views/landscape/components/Skeleton.tsx

interface: add lodash import to prevent crash in NewChannel
interface: normalize joinGroup modal
interface: stop propagation reshowing modal
interface: truncate group title

interface: all assigned QA bugs

---

pkg/interface/src/views/apps/links/LinkWindow.tsx
pkg/interface/src/views/apps/links/components/LinkItem.tsx
pkg/interface/src/views/components/RemoteContent.tsx

- Fixes a latent key issue in LinkWindow
- Some godawful hack to approximate a click event handler on an iframe (same-origin strikes again)
cc: @tylershuster 
Fixes urbit/landscape#288

links: set read on iframe interaction

---

pkg/interface/src/views/apps/notifications/graph.tsx
pkg/interface/src/views/components/ProfileOverlay.tsx
pkg/interface/src/views/landscape/components/GroupSwitcher.tsx

- Fixes https://github.com/urbit/landscape/issues/352
- Fixes https://github.com/urbit/landscape/issues/350
- FIxes https://github.com/urbit/landscape/issues/349

qa: mp fixes, feb 4

---

pkg/interface/src/views/landscape/components/JoinGroup.tsx

Skip preview on accepting an unmanaged invite (i.e. a DM invite), and skip straight to joining.

JoinGroup: skip preview if unmanaged group

---

pkg/interface/src/views/components/ShipSearch.tsx

Fixes incomplete ship entry case

ShipSearch: fix incomplete ship entry case

---

pkg/interface/src/logic/lib/sigil.js
pkg/interface/src/views/apps/chat/components/ChatInput.tsx
pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/apps/notifications/graph.tsx
pkg/interface/src/views/apps/profile/components/Profile.tsx
pkg/interface/src/views/components/Author.tsx
pkg/interface/src/views/components/leap/OmniboxResult.js
pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx

Profile: tweak sigil size

---

pkg/arvo/app/contact-pull-hook.hoon
pkg/arvo/lib/agentio.hoon
pkg/interface/src/logic/api/metadata.ts
pkg/interface/src/views/apps/profile/components/ViewProfile.tsx

Also cleans up error handling, to account for the case that someone's pinned a group that are banned from / can't join.

ViewProfile: fix incorrect loading conditional

---

pkg/interface/src/views/components/ShipSearch.tsx
pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/ChannelPermissions.tsx

Addresses crashes on setting channel permissions

ChannelPermissions: fix sig/nosig mismatch

---

pkg/arvo/app/sane.hoon

https://github.com/urbit/landscape/issues/380

sane: fix contact desyncs

---

pkg/arvo/lib/pull-hook.hoon
pkg/arvo/lib/push-hook.hoon
pkg/arvo/ted/graph/delete.hoon

- Fixes a syntax error in the graph delete thread
- Makes the +dbug output of the hooks prettier

landscape: miscellaneous fixes

---

pkg/interface/src/views/apps/publish/components/Note.tsx
pkg/interface/src/views/landscape/components/NewChannel.tsx

- Correct icon in NewChannel
- Fix shipsearch sig mismatch
- Correctly checks permissions on publish notes

interface: FE fixes

---

pkg/arvo/lib/metadata-store.hoon

Fixes crash in JSON conversion of +vip

metadata: use +perk in vip dejs

---

pkg/arvo/mar/tape.hoon
pkg/arvo/ted/code.hoon

@narner callable by POSTing `{}` to `/spider/json/code/tape.json` (requires that you're already authenticated)

ted: add -code thread

---

pkg/interface/src/views/apps/links/LinkResource.tsx
pkg/interface/src/views/apps/links/LinkWindow.tsx

Fixes https://github.com/urbit/landscape/issues/375

interface: don't show link submit when empty collection and we don't have permission

---

pkg/arvo/app/hark-store.hoon
pkg/arvo/lib/hark/store.hoon
pkg/interface/src/logic/api/hark.ts
pkg/interface/src/views/apps/notifications/notifications.tsx

Zeros out the unread count, runs seen, and empties out all the unread indices in `unreads-each`.

hark-store: add %read-all support

---

pkg/interface/src/logic/lib/omnibox.js
pkg/interface/src/logic/lib/util.ts
pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/apps/chat/components/content/text.js
pkg/interface/src/views/apps/profile/components/Profile.tsx
pkg/interface/src/views/apps/profile/components/ViewProfile.tsx
pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/Sidebar.tsx
pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/index.tsx

Fixes urbit/landscape#386
Fixes urbit/landscape#395
Fixes urbit/landscape#392
Fixes urbit/landscape#394
Fixes urbit/landscape#388

interface: QA fixes

---

pkg/interface/config/webpack.dev.js
pkg/interface/src/logic/api/settings.ts
pkg/interface/src/logic/lib/omnibox.js
pkg/interface/src/logic/lib/tutorialModal.ts
pkg/interface/src/logic/lib/useModal.tsx
pkg/interface/src/logic/lib/useOutsideClick.ts
pkg/interface/src/logic/reducers/group-update.ts
pkg/interface/src/types/local-update.ts
pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/notifications/notifications.tsx
pkg/interface/src/views/apps/profile/components/Profile.tsx
pkg/interface/src/views/components/GroupSearch.tsx
pkg/interface/src/views/components/ModalOverlay.tsx
pkg/interface/src/views/components/StatusBar.js
pkg/interface/src/views/components/StatusBarItem.tsx
pkg/interface/src/views/components/Triangle.tsx
pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/Notifications.tsx
pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/index.tsx
pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
pkg/interface/src/views/landscape/components/PopoverRoutes.tsx
pkg/interface/src/views/landscape/components/TutorialModal.tsx

Cleans up the tutorial to match designs
cc: @jyng

Tutorial: bugfixes

---

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/components/ProfileStatus.js

Fixes https://github.com/urbit/landscape/issues/389
Fixes https://github.com/urbit/landscape/issues/390

interface: mini profile does not dismiss improperly on click, and shows success indicator when status is set

---

pkg/arvo/app/settings-store.hoon
pkg/interface/src/logic/lib/omnibox.js

Not ready for this release. 
Will revive later

Tutorial: disable

---

pkg/interface/src/views/apps/chat/components/ChatWindow.tsx

Fixes the unread banner overlapping the share banner.

chat: wrap chatWindow in position='relative'

---

pkg/arvo/app/contact-store.hoon
pkg/arvo/lib/contact-store.hoon
pkg/arvo/sur/contact-store.hoon
pkg/interface/src/logic/api/contacts.ts

Hotfix to prevent forwarding loop

contact-store: add timestamp to %edit

---

pkg/interface/src/views/components/Dropdown.tsx
pkg/interface/src/views/components/SetStatusBarModal.js
pkg/interface/src/views/components/StatusBar.js

For those of us on BigYellowButton.

StatusBar: prevent sigil flexing offscreen

---

pkg/interface/src/logic/reducers/contact-update.ts
pkg/interface/src/views/apps/chat/ChatResource.tsx

Perhaps we can release to BYB first so Anthony can test if it fixes his case?

interface: profiles would intermittently show contact information when they should not, fixes this

---

pkg/arvo/app/group-view.hoon
pkg/interface/src/views/components/Dropdown.tsx

group-view: handle unmanaged group case
Dropdown: fix event propagation causing strange behaviour
Fixes urbit/landscape#427

group-view: fix dangling join requests

---

pkg/arvo/app/settings-store.hoon

cc @mrdomino I know the resolution we came to for your use case was to just use subscriptions, but I figured this is a simple enough change and it will probably be helpful to have anyway.

settings-store: add existence scry

---

pkg/interface/src/views/apps/chat/ChatResource.tsx
pkg/interface/src/views/apps/chat/components/ChatMessage.tsx

Fixes https://github.com/urbit/landscape/issues/434

interface: ensure that we display the correct ship name and do not retain stale state

---

pkg/interface/src/views/apps/chat/components/unread-notice.js

Fixes that thing @tylershuster did. 
Fixes urbit/landscape#462

chat: set timestamp size to 1 in unread-notice

---

pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/launch/components/Groups.tsx
pkg/interface/src/views/apps/launch/components/ModalButton.tsx

Graphical tweaks to match what's currently in mocks a little more. Mainly needs design review — @urcades ?

launch: update for 1.7

---

pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx

ResourceSkeleton: render group DM members

---

.github/workflows/merge.yml
.github/workflows/ops-group-timer.yml

- Auto globs and deploys to ~difmex-passed
- Automerges master into ops/group-timer
- Need to verify that CI has access to ~difmex-passed

meta: automatically deploy group-timer

---

pkg/interface/src/views/apps/settings/components/lib/S3Form.tsx

settings: restore back button on s3

---

pkg/arvo/app/language-server.hoon
pkg/arvo/lib/language-server/complete.hoon
pkg/arvo/lib/shoe.hoon

- Fixes parsing of identifiers for hover, autocomplete etc. 
- Improves formatting of hover items
- Ignores /sys files due to their length and nonstandard nature
- Prevent %play-open on %zpgl
- Retains state on reload

language-server: fixes & improvements

---

pkg/interface/src/logic/lib/idling.ts
pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
pkg/interface/src/views/components/VirtualScroller.tsx

- VirtualScroller: acknowledge end of load
Fixes urbit/landscape#507
- VirtualScroller: fix iOS jumpiness case
- UnreadMarker: fix dismiss on idle

VirtualScroller: fixes grabbag

---

pkg/interface/src/views/components/VirtualScroller.tsx

VirtualScroller: prevent crash on iOS

---

pkg/interface/src/views/landscape/components/Participants.tsx

running into https://bugs.chromium.org/p/chromium/issues/detail?id=688640
on large groups
Fixes urbit/landscape#513

Participants: remove grid

---

pkg/interface/src/views/components/DropdownSearch.tsx
pkg/interface/src/views/components/ShipSearch.tsx

ShipSearch: prevent dupes

---

pkg/arvo/app/hark-store.hoon

Stops futureposting pinning channels to the top

hark-store: remove visions of future

---

pkg/arvo/app/group-view.hoon
pkg/arvo/lib/group-view.hoon
pkg/arvo/sur/group-view.hoon
pkg/interface/src/logic/api/groups.ts
pkg/interface/src/logic/lib/useLazyScroll.ts
pkg/interface/src/logic/reducers/group-view.ts
pkg/interface/src/views/apps/notifications/inbox.tsx
pkg/interface/src/views/apps/notifications/invites.tsx
pkg/interface/src/views/apps/notifications/joining.tsx
pkg/interface/src/views/components/Invite/Group.tsx
pkg/interface/src/views/components/Invite/InviteSkeleton.tsx
pkg/interface/src/views/components/Invite/JoinSkeleton.tsx
pkg/interface/src/views/components/Invite/index.tsx
pkg/npm/api/groups/view.ts

- Removes pinning of invites to top
- Adds ability to hide join requests

invites: don't pin to top

---

pkg/interface/src/views/landscape/components/MetadataIcon.tsx

Did this wrong the first time, doesn't produce the border on colours as @g-a-v-i-n asked.

MetadataIcon: 1, not -1 inset

---

pkg/interface/src/views/apps/profile/components/EditProfile.tsx
pkg/interface/src/views/apps/profile/components/Profile.tsx
pkg/interface/src/views/apps/profile/components/ViewProfile.tsx

Prevents showing our sigil on everyone's profile.

profile: pass ship to image

---

pkg/interface/src/views/apps/links/LinkWindow.tsx
pkg/interface/src/views/components/VirtualScroller.tsx

- Fixes weird flicker in the virtualisation of flicker, due to the `renderer` not being referentially stable
- Documents the invariants that VirtualScroller needs from its parent components

collections: virtualisation flicker fix

---

pkg/interface/src/views/App.js

Regressed after new contacts released, unfiled.

landscape: fix favicons for flattened contacts

---

pkg/interface/src/views/components/Invite/index.tsx

Invites: accept already joined group

---

pkg/interface/src/logic/reducers/settings-update.ts
pkg/interface/src/views/apps/profile/components/ViewProfile.tsx
pkg/interface/src/views/components/CommentInput.tsx
pkg/interface/src/views/components/Dropdown.tsx
pkg/interface/src/views/components/StatusBar.js
pkg/interface/src/views/components/VirtualScroller.tsx
pkg/interface/src/views/landscape/components/Participants.tsx

Leap: fix double section
Fixes urbit/landscape#504
Participants: kick pending contacts
Fixes urbit/landscape#269
Profile: fix stale headers
Fixes urbit/landscape#419
StatusBar: fix dismiss
Fixes urbit/landscape#476
VirtualScroller: correct lazy loading with small chats
Fixes urbit/landscape#523
Comments: validate on submit only
Fixes urbit/landscape#530

interface: grabbag of fixes

---

pkg/interface/src/logic/lib/tutorialModal.ts
pkg/interface/src/views/apps/profile/components/Profile.tsx
pkg/interface/src/views/landscape/components/TutorialModal.tsx

- Fixes broken profile step
- Hide caret on mobile

Tutorial: polish for release

---

pkg/interface/src/logic/state/hark.ts
pkg/interface/src/views/apps/profile/components/Profile.tsx

Notifications: fix refresh

---

pkg/interface/src/logic/store/store.ts
pkg/interface/src/views/apps/profile/components/EditProfile.tsx
pkg/interface/src/views/components/Invite/index.tsx

should fix https://github.com/urbit/landscape/issues/554
...might help to actually reduce the message

interface: reduce group-view messages

---

pkg/interface/src/logic/lib/util.ts
pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
pkg/interface/src/views/landscape/components/Skeleton.tsx

A couple things at work here. Not positive which one caused the problem, but a few of them could and the others would definitely cause problems later. Toggling "hide unsubscribed channels" was my consistent repro and this fixes that.

interface: removed conditional hooks

---

pkg/interface/src/views/apps/settings/settings.tsx
pkg/interface/src/views/landscape/components/SidebarItem.tsx

settings: fix sidebar spacing

---

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/apps/chat/components/content/text.js
pkg/interface/src/views/components/VirtualScroller.tsx
pkg/interface/src/views/css/fonts.css

Cleans up the various warnings we get by correcting our code, with 404s on fonts we don't have in pkg/arvo, unkeyed components, a bad style name.

landscape: clean up console crashes, key mapped components

---

pkg/interface/src/logic/reducers/graph-update.js

Correctly sorts indices (smallest to largest)

graph-update: sort indices correctly

---

pkg/interface/src/views/apps/launch/app.js

tutorial: update for zustand

---

pkg/interface/src/views/apps/notifications/header.tsx

hark-fe: use calmengine for nickname render

---

pkg/interface/src/views/components/ShipSearch.tsx

ShipSearch: prevent dupes in exact matches

---

pkg/interface/src/views/apps/chat/ChatResource.tsx
pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/apps/chat/components/ChatWindow.tsx

Fix https://github.com/urbit/landscape/issues/572

interface: only display our contact when appropriate

---

pkg/urbit/daemon/main.c
pkg/urbit/include/vere/db/lmdb.h
pkg/urbit/vere/db/lmdb.c
pkg/urbit/vere/pier.c

To help chase down corruption/truncation bugs like #4605.

vere: adds lmdb debug stats

---

pkg/interface/src/views/apps/launch/components/Groups.tsx

launch: depluralise 'days' when necessary

---

pkg/interface/src/views/landscape/components/Participants.tsx

Participants: fix display of nonmembers

---

pkg/arvo/lib/push-hook.hoon

Fixes https://github.com/urbit/landscape/issues/270 for good, by ensuring that *all messages* passed through the hooks are transformed and applied in the order they're received.

push-hook: transform all messages, even the host's

---

pkg/interface/src/views/apps/settings/components/lib/NotificationPref.tsx

notifications: add submit button for preferences

---

pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx

sidebar: two styling fixes

---

pkg/interface/src/views/apps/publish/components/Notebook.tsx

publish: call all hooks before returning early

---

pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/views/components/Error.tsx
pkg/interface/src/views/components/ErrorBoundary.tsx

This should provide slightly better stack traces, plus it updates the "submit an issue" link to link to Landscape with the stack trace and title already filled in.

interface: better error boundary reporting tools and formatting

---

pkg/interface/src/views/components/ProfileOverlay.tsx

Adjusts sigil size and box to spec.
Existing (bad, undesired):
Proposed (good, desired):
Fixes urbit/landscape#588

chat: resize sigils to 32px, container to 60px

---

pkg/arvo/app/hark-graph-hook.hoon
pkg/arvo/mar/graph/validator/link.hoon
pkg/arvo/mar/graph/validator/post.hoon
pkg/arvo/mar/graph/validator/publish.hoon
pkg/arvo/ted/graph/create-group-feed.hoon
pkg/interface/package-lock.json
pkg/interface/src/logic/api/graph.ts
pkg/interface/src/logic/lib/useToggleState.ts
pkg/interface/src/logic/state/contact.ts
pkg/interface/src/logic/state/group.ts
pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/apps/notifications/graph.tsx
pkg/interface/src/views/components/Author.tsx
pkg/interface/src/views/components/OverlaySigil.tsx
pkg/interface/src/views/components/ProfileOverlay.tsx
pkg/interface/src/views/landscape/components/Home/AddFeedBanner.js
pkg/interface/src/views/landscape/components/Home/EnableGroupFeed.tsx
pkg/interface/src/views/landscape/components/Home/GroupFeed.js
pkg/interface/src/views/landscape/components/Home/GroupHome.js
pkg/interface/src/views/landscape/components/Home/Post/GroupFeedPerms.tsx
pkg/interface/src/views/landscape/components/Home/Post/PostInput.js
pkg/interface/src/views/landscape/components/Home/Post/PostTimeline.js

- Refactors profileoverlay to have fixed position, so it can escape it's bounding container
- Adds code, links input to adding posts (code is stubbed, given we cannot render them now)
- Notifications for post, no unreads, only notify if it's a reply
- VirtualScroller style fixes

group feed: interface improvements

---

pkg/interface/config/webpack.dev.js
pkg/interface/package-lock.json
pkg/interface/src/views/apps/chat/ChatResource.tsx
pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
pkg/interface/src/views/components/VirtualScroller.tsx

- Fixes unread line setting
- Fixes loading indicator not disappearing

chat: fix unread line setting

---

pkg/interface/src/views/apps/permalinks/embed.tsx
pkg/interface/src/views/apps/profile/components/Profile.tsx
pkg/interface/src/views/apps/profile/components/ViewProfile.tsx
pkg/interface/src/views/apps/profile/profile.tsx
pkg/interface/src/views/apps/settings/settings.tsx
pkg/interface/src/views/apps/term/app.js

Finalizing washedGray to lightGray change, realized I had missed reflecting the change across the profile and settings pages and the terminal / permalink embed.

interface: profile and settings light gray

---

pkg/interface/src/logic/reducers/hark-update.ts

This was in the reducer before the zustand rewrite. Is this chesterton's fence @tylershuster ?
Fixes urbit/landscape#646

notifications: clear before applying unreads

---

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/apps/notifications/invites.tsx
pkg/interface/src/views/apps/permalinks/TranscludedNode.tsx
pkg/interface/src/views/apps/permalinks/embed.tsx
pkg/interface/src/views/components/ProfileOverlay.tsx
pkg/interface/src/views/components/RemoteContent.tsx
pkg/interface/src/views/landscape/components/Home/GroupFeedHeader.js
pkg/interface/src/views/landscape/components/Home/Post/PostFeed.js
pkg/interface/src/views/landscape/components/Home/Post/PostReplies.js

Post: fix virtscroller position on replies
Fixes urbit/landscape#649
Post: fix various crashes
chat: update links to match spec
invites: render correctly
Fixes urbit/landscape#628
chat: fix showing contact in transclusion
Fixes urbit/landscape#629
ProfileOverlay: fix contact render
Fixes urbit/landscape#630
chat: cap block content at 500px
Fixes urbit/landscape#641

interface: next-userspace grabbag

---

pkg/arvo/app/group-view.hoon
pkg/arvo/lib/group-view.hoon
pkg/arvo/mar/graph/validator/post.hoon
pkg/arvo/sur/group-view.hoon
pkg/interface/src/logic/api/graph.ts
pkg/interface/src/logic/reducers/group-view.ts
pkg/interface/src/views/apps/chat/components/chat-editor.js
pkg/interface/src/views/apps/links/components/LinkItem.tsx
pkg/interface/src/views/apps/notifications/invites.tsx
pkg/interface/src/views/apps/notifications/notifications.tsx
pkg/interface/src/views/apps/permalinks/TranscludedNode.tsx
pkg/interface/src/views/apps/permalinks/app.tsx
pkg/interface/src/views/components/Invite/index.tsx
pkg/interface/src/views/landscape/components/Home/Post/PostContent.js
pkg/interface/src/views/landscape/components/JoinGroup.tsx

post: do not notify on top level content
interface: support %started update
group-view: add %started update
Invites: fix prop passing
Fixes urbit/landscape#654
interface: version serialized state
collections: update link copy
Fixes urbit/landscape#615

next-userspace grabbag vol. 2

---

pkg/arvo/mar/graph/validator/link.hoon
pkg/interface/src/views/apps/links/components/LinkItem.tsx
pkg/interface/src/views/apps/links/components/LinkSubmit.tsx
pkg/interface/src/views/apps/notifications/graph.tsx
pkg/interface/src/views/apps/permalinks/TranscludedNode.tsx
pkg/interface/src/views/apps/permalinks/embed.tsx

Allows permalinks to be added to collections.
Fixes urbit/landscape#661

collections: allow %reference as link

---

pkg/interface/src/logic/api/metadata.ts

interface: update md version

---

.github/workflows/build.yml

Fixes #4682 though unsure how to confirm this.

build: match on path subdirectories

---

pkg/interface/config/webpack.dev.js
pkg/interface/src/logic/state/base.ts

interface: version local state by commit hash

---

pkg/interface/src/views/landscape/components/Home/Post/PostInput.js

Post: allow submission with ctrl+enter

---

pkg/interface/src/logic/subscription/global.ts
pkg/interface/src/views/components/Author.tsx
pkg/interface/src/views/components/Timestamp.tsx
pkg/interface/src/views/landscape/components/Home/Post/PostFeed.js
pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostContent.js
pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostFooter.js
pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostHeader.js
pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostItem.js
pkg/interface/src/views/landscape/index.tsx

group-feed: tons of post item touch-ups

---

pkg/interface/src/logic/reducers/gcp-reducer.ts
pkg/interface/src/logic/reducers/hark-update.ts
pkg/interface/src/logic/reducers/metadata-update.ts
pkg/interface/src/logic/state/base.ts
pkg/interface/src/logic/state/group.ts
pkg/interface/src/logic/store/base.ts

- Adjusts reducers to be compatible with immer.js
- Removes redundant unconditional this.setState everytime we get a subscription update 
- Makes interface go fast
cc: @tylershuster

interface: performance enhancement

---

pkg/interface/src/logic/api/graph.ts
pkg/interface/src/views/apps/permalinks/app.tsx
pkg/interface/src/views/components/FormSubmit.tsx
pkg/interface/src/views/landscape/components/GroupSettings/GroupFeed.tsx
pkg/interface/src/views/landscape/components/GroupSettings/GroupSettings.tsx
pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
pkg/interface/src/views/landscape/components/Home/AddFeedBanner.js
pkg/interface/src/views/landscape/components/Home/EnableGroupFeed.tsx
pkg/interface/src/views/landscape/components/Home/GroupHome.js
pkg/interface/src/views/landscape/components/Home/Post/GroupFeedPerms.tsx
pkg/interface/src/views/landscape/components/Home/Post/PostInput.js
pkg/interface/src/views/landscape/components/PopoverRoutes.tsx
pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarListHeader.tsx

interface: normalize headers to 600 font weight
Fixes urbit/landscape#622
PostInput: adjust resize behaviour
Mitigates urbit/landscape#617 but does not fix it.
AddFeedBanner: update design to match spec
Fixes urbit/landscape#664
interface: fix protocol handler
Fixes urbit/landscape#680
GroupHome: description by default
Fixes urbit/landscape#668
GroupFeed: add settings page
Fixes urbit/landscape#665
Post: enable feed modal fixes
Fixes urbit/landscape#667

interface: assorted grabbag for next-userspace

---

pkg/arvo/lib/graph-view.hoon
pkg/arvo/mar/graph/validator/post.hoon
pkg/arvo/sur/graph-view.hoon
pkg/arvo/ted/graph/create-group-feed.hoon
pkg/interface/src/logic/api/graph.ts
pkg/interface/src/views/landscape/components/Home/EnableGroupFeed.tsx
pkg/interface/src/views/landscape/components/Home/GroupFeed.js
pkg/interface/src/views/landscape/components/Home/GroupFeedHeader.js
pkg/interface/src/views/landscape/components/Home/GroupHome.js
pkg/interface/src/views/landscape/components/Home/Post/PostFeed.js
pkg/interface/src/views/landscape/components/Home/Post/PostInput.js
pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostFooter.js
pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostItem.js
pkg/interface/src/views/landscape/components/Home/Post/PostReplies.js
pkg/interface/src/views/landscape/components/Home/Post/PostTimeline.js

Have done API and API actions. Also did prop-drilling. Now to implement the different render states.
EDIT: Ready to go.

group-feed: implement permissions properly

---

pkg/arvo/lib/metadata-store.hoon
pkg/interface/src/views/App.js
pkg/interface/src/views/apps/chat/components/chat-editor.js
pkg/interface/src/views/apps/launch/app.js
pkg/interface/src/views/apps/notifications/graph.tsx
pkg/interface/src/views/apps/notifications/joining.tsx
pkg/interface/src/views/apps/permalinks/embed.tsx
pkg/interface/src/views/components/GroupLink.tsx
pkg/interface/src/views/landscape/components/Home/Post/PostInput.js
pkg/interface/src/views/landscape/css/custom.css

notifications: fix post url
Launch: remove dev cruft
metadata: fix JSON conversions
Embed: prevent 404 on graph links
GroupLink: cap at 500px

hotfixes: various

---

pkg/interface/src/views/components/ProfileOverlay.tsx

miniprofile: rectify sigil corners

---

pkg/interface/src/views/apps/notifications/invites.tsx
pkg/interface/src/views/components/CommentItem.tsx

fix comment action backgrounds, prevent invites shrinking closed

---

pkg/interface/src/logic/reducers/gcp-reducer.ts

interface: type annotations, imports

---

pkg/interface/src/logic/subscription/global.ts

Fixes subscriptions not restarting properly

subscription: clear opened subs before restart

---

pkg/interface/src/logic/lib/BigIntOrderedMap.ts
pkg/npm/api/lib/BigIntOrderedMap.ts
pkg/npm/api/package.json

cc: @tylershuster
Fixes urbit/landscape#707
Fixes urbit/landscape#740

interface: mark BigIntOrderedMap compat with immer

---

pkg/interface/src/views/apps/permalinks/TranscludedNode.tsx

publish: fix color in darkmode

---

pkg/interface/src/views/apps/profile/components/EditProfile.tsx

EditProfile: do not mutate contact

---

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx

ChatMessage: prevent link overflow

---

pkg/interface/src/logic/lib/useLazyScroll.ts
pkg/interface/src/views/apps/notifications/inbox.tsx

notifications: prevent race condition causing empty notifications

---

pkg/interface/src/logic/lib/hark.ts
pkg/interface/src/views/apps/publish/PublishResource.tsx
pkg/interface/src/views/apps/publish/components/Note.tsx
pkg/interface/src/views/components/RemoteContent.tsx
pkg/interface/src/views/components/ShipSearch.tsx

launch: fix group notification display
Fixes urbit/landscape#720
Fixes urbit/landscape#656
RemoteContent: fix video, audio overflow
Fixes urbit/landscape#756
ShipSearch: fix error reporting
Fixes urbit/landscape#753
Publish: reset scroll on nav change
Fixes urbit/landscape#758

landscape: grabbag

---

pkg/arvo/app/group-store.hoon

group-store: remove empty tags

---

pkg/arvo/app/group-push-hook.hoon
pkg/arvo/ted/sane.hoon

sane: don't kick unsubscribed

---

pkg/arvo/app/metadata-store.hoon

Group Pull Hook `%add` is idempotent. This is a very calm upgrade TM.

metadata-store: subscribe to all feeds that got missed in the upgrade

---

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx

https://github.com/urbit/landscape/issues/591

interface: fix #591 message display by time-sent in chat

---

pkg/arvo/app/acme.hoon

acme: don't no-op for moons and comets

---

pkg/arvo/app/contact-store.hoon

Fix https://github.com/urbit/landscape/issues/675 for all new data, no migration needed.

contact-store: disallow data: urls from being added

---

nix/pkgs/docker-image/default.nix
pkg/docker-image/README.md

Also updates documentation and adds some examples.

Docker: add curl, implement scripts for obtaining +code from loopback

---

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/apps/publish/components/NoteForm.tsx
pkg/interface/src/views/components/ChipInput.tsx
pkg/interface/src/views/components/Dropdown.tsx
pkg/interface/src/views/landscape/components/GroupSummary.tsx
pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
pkg/interface/src/views/landscape/components/GroupifyForm.tsx
pkg/interface/src/views/landscape/components/JoinGroup.tsx
pkg/interface/src/views/landscape/components/NewChannel.tsx
pkg/interface/src/views/landscape/components/Participants.tsx
pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarListHeader.tsx

e.z. typescript win, down to 284 now.

interface: fix flex-shrink typings

---

pkg/interface/src/views/components/Dropdown.tsx

Dropdown: check ref exists

---

pkg/interface/src/logic/lib/omnibox.js

Fixes https://github.com/urbit/landscape/issues/721

interface: group feed no longer shows in omnibox

---

pkg/interface/src/views/apps/permalinks/TranscludedNode.tsx
pkg/interface/src/views/components/Comments.tsx

Fixes urbit/landscape#814
Fixes urbit/landscape#813

landscape: move transcluded comments to graphcontentwide

---

pkg/interface/src/views/apps/chat/components/ShareProfile.js

- Makes @philipcmonk marginally happier

chat: prevent shrinking of share banner

---

pkg/arvo/tests/sys/vane/clay.hoon
pkg/arvo/tests/sys/zuse/format.hoon

idk why we don't get CI on next-sys anymore, but it let these slip by. Could've been worse!

tests: update to reflect recent changes

---

pkg/arvo/app/file-server.hoon
pkg/arvo/lib/server.hoon

https://github.com/urbit/landscape/issues/561

server: stop caching session.js, add more flexible caching, stop using tape interpolation

---

pkg/interface/src/logic/lib/platform.ts
pkg/interface/src/logic/reducers/hark-update.ts
pkg/interface/src/views/components/VirtualScroller.tsx

VirtualScroller: fix pendings and scroll after jump
hark: fix notification archival
interface: include iPad in UA check

interface: fix omnibus

---

pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/views/components/StatusBar.js

Changes the submit an issue button to a lil bug icon.

interface: bump to indigo-react 1.2.22

---

pkg/npm/api/lib/BigIntOrderedMap.ts

BigIntOrderedMap: fix caching

---

pkg/npm/api/lib/BigIntOrderedMap.ts

BigIntOrderedMap: fix caching, again

---

pkg/interface/src/logic/lib/publish.ts

publish: fix snippet generation

---

pkg/interface/src/logic/lib/permalinks.ts
pkg/interface/src/views/apps/permalinks/embed.tsx

permalinks: navigate on-click

---

pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx
pkg/interface/src/views/landscape/components/Graph/parse.ts

- Preserve newlines
- Fix lineheight
- Disable nested blockquotes
- Disable inline html

GraphContent: rendering fixes 

---

pkg/interface/src/views/components/StatusBar.tsx

StatusBar: remove avatar fringe

---

pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/logic/api/contacts.ts
pkg/interface/src/logic/api/hark.ts
pkg/interface/src/logic/reducers/contact-update.ts
pkg/interface/src/logic/reducers/hark-update.ts
pkg/interface/src/logic/state/base.ts
pkg/interface/src/logic/state/hark.ts
pkg/interface/src/views/apps/profile/components/EditProfile.tsx
pkg/interface/src/views/apps/settings/components/lib/BackgroundPicker.tsx
pkg/interface/src/views/apps/settings/components/lib/CalmPref.tsx
pkg/interface/src/views/apps/settings/components/lib/DisplayForm.tsx
pkg/interface/src/views/apps/settings/components/lib/GroupChannelPicker.tsx
pkg/interface/src/views/apps/settings/components/lib/LeapSettings.tsx
pkg/interface/src/views/apps/settings/components/lib/NotificationPref.tsx
pkg/interface/src/views/components/FormikOnBlur.tsx

- Optimistic contacts and notifications updates
- Scrap submit buttons in preferences, save on change

interface: optimistic updating

---

pkg/interface/src/logic/lib/shortcutContext.tsx
pkg/interface/src/views/components/StatusBar.tsx

- Small yellow bug now centered in his golden cage.
- No longer logs every keystroke in service to the shortcut handler.

interface: fixes lopsided SMB, eliminates shortcut chord console logging

---

.github/workflows/typescript-check.yml

Adds a Typescript compiler check for pkg/interface PRs.
(I will mark as ready for review once we have a clean tsc pass.)

build: add typescript-check.yml

---

pkg/interface/src/logic/reducers/hark-update.ts
pkg/interface/src/views/apps/settings/components/lib/NotificationPref.tsx

fixes https://github.com/urbit/landscape/issues/878

interface: check notification availability

---

.github/workflows/typescript-check.yml

build: check subdirs on tsc

---

pkg/interface/src/logic/api/hark.ts

- Reads chats and comments optimistically, to avoid unnecessary lag

hark: optimistic read

---

pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx

Fixes mentions being on their own line when they start the line; fixes multiple blockquotes merging into one line.

GraphContent: amend text, blockquote boxing, color

---

pkg/interface/.storybook/main.js
pkg/interface/.storybook/preview.js
pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/stories/GraphContentTall.stories.tsx
pkg/interface/src/stories/GraphContentWide.stories.tsx
pkg/interface/src/views/components/RemoteContent.tsx
pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx
pkg/interface/src/views/landscape/css/custom.css

This PR adds storybook to the landscape SPA, and includes two stories for our most heavily reused and buggy component `GraphContent`, in an effort to slow the pace of accidental breakages to the rendering, and cover all edge cases. This should probably be paired with [Chromatic](https://www.chromatic.com/) or something similar, to allow for comparisons and to integrate it through CI. Additionally, the fixtures for this being static will help bisect whether rendering breakage is coming from `tokenizeMessage` or the renderer. Includes bugfixes for most of the outstanding issues against `GraphContent` rendering, however list indicators are broken on darkmode and an indigo patch is out to fix it. https://github.com/urbit/indigo-react/pull/109
Simply `npm run storybook` in the pkg/interface …

interface: another markdown pass

---

pkg/arvo/app/dm-hook.hoon
pkg/arvo/gen/dm-hook/dm.hoon
pkg/interface/src/logic/api/graph.ts
pkg/interface/src/logic/reducers/graph-update.ts
pkg/interface/src/views/apps/chat/DmResource.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarList.tsx

- Fixes sending a DM to yourself
- Fixes comet DMs crashing the sidebar
- Fixes mark as read and backlog fetching
- Adds pending, unread states

DMs: bugfixes

---

pkg/interface/src/views/components/CommentItem.tsx

Fixes deletion of updated comments
Fixes urbit/landscape#902

Comments: fix deletion

---

pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostItem.tsx

Most probable fix for urbit/landscape#912.

PostItem: only render byline if author in state

---

pkg/arvo/app/dojo.hoon
pkg/arvo/app/lens.hoon
pkg/arvo/mar/lens/command.hoon
pkg/arvo/sur/lens.hoon
pkg/herb/herb

Lets you run `herb --cancel` to cancel any ongoing command. Addresses this issue https://github.com/urbit/urbit/issues/4959

herb: add cancel command

---

pkg/interface/src/logic/reducers/hark-update.ts

Broke during merge conflict resolution i think.

hark-update: fix archival

---

pkg/btc-wallet/src/index.js
pkg/interface/src/views/apps/chat/DmResource.tsx
pkg/interface/src/views/apps/settings/components/lib/DmSettings.tsx
pkg/interface/src/views/landscape/components/Home/GroupHome.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx

interface: deploy omnibus

---

pkg/interface/src/logic/lib/hark.ts
pkg/interface/src/logic/reducers/hark-update.ts
pkg/interface/src/stories/GraphContentWide.stories.tsx
pkg/interface/src/stories/PendingDm.stories.tsx
pkg/interface/src/views/apps/chat/DmResource.tsx
pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
pkg/interface/src/views/apps/notifications/PendingDm.tsx
pkg/interface/src/views/apps/notifications/graph.tsx
pkg/interface/src/views/components/ProfileOverlay.tsx
pkg/interface/src/views/components/leap/Omnibox.tsx
pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx
pkg/interface/src/views/landscape/components/Graph/blockquote.js
pkg/interface/src/views/landscape/components/Graph/remark-break.ts

notifications: fix notification keying
Fixes urbit/landscape#947
notifications: fix note click through
Fixes urbit/landscape#937
notifications: fix group num calculations
PendingDm: fix mobile layout
Fixes urbit/landscape#935
ProfileOverlay: fix DM route
Fixes urbit/landscape#933
leap: navigate to DMs
Fixes urbit/landscape#948
GraphContent: fix inline content immediately following blockquote
DMs: reply functionality with blockquotes
Fixes urbit/landscape#932

interface: post-deploy fix omnibus

---

pkg/interface/src/views/components/ImageInput.tsx

Default:
Click into field:
Click "upload" blue text:
(will vary from OS to OS)
Successful upload:
Failed upload:
fixes urbit/landscape#893

imageinput: disable placeholder selection, hide placeholder on focus

---

pkg/btc-wallet/src/js/components/lib/balance.js
pkg/btc-wallet/src/js/components/lib/bridgeInvoice.js
pkg/btc-wallet/src/js/components/lib/invoice.js
pkg/btc-wallet/src/js/components/lib/send.js
pkg/btc-wallet/src/js/components/themes/light.js

Updates the invoice screen, including adding the total fee
Fixes a bug where the fee picker showed the options with the wrong labels and time estimates.

btc: bug and style fixes related to fees

---

pkg/arvo/app/dm-hook.hoon

Fixes missing DMs, no data should be lost

dm-hook: fix on-init, rerun in on-load

---

pkg/interface/src/logic/lib/omnibox.js
pkg/interface/src/views/components/leap/Omnibox.tsx
pkg/interface/src/views/components/leap/OmniboxResult.tsx

leap: display chording options

---

pkg/arvo/app/contact-store.hoon
pkg/arvo/app/graph-store.hoon
pkg/arvo/app/metadata-store.hoon
pkg/arvo/app/settings-store.hoon
pkg/arvo/lib/contact.hoon

Adding them so we can't have any random 10ms nest checks anywhere that we aren't expecting!

userspace: adding a variety of casts to avoid nest checks

---

pkg/interface/src/views/landscape/components/Sidebar/SidebarList.tsx

Fixes https://github.com/urbit/landscape/issues/965

interface: fix dm alphabetical sort issue

---

pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx

fixes https://github.com/urbit/landscape/issues/955

interface: pass api object to Mention component

---

pkg/interface/src/views/landscape/components/Sidebar/SidebarList.tsx

SidebarList: fix sorting

---

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/components/Author.tsx

chat: never wrap timestamps

---

pkg/arvo/app/spider.hoon

Perhaps someone will be able to adequately speed up spider down the line, but I can't seem to. Maybe these hints will help when the time comes.

spider: add profiling hints so we can see how slow it is

---

pkg/interface/src/logic/api/index.ts
pkg/interface/src/logic/lib/useDrag.ts
pkg/interface/src/logic/lib/useLocalStorageState.ts
pkg/interface/src/logic/lib/util.tsx
pkg/interface/src/logic/state/graph.ts
pkg/interface/src/logic/state/join.ts
pkg/interface/src/logic/state/local.tsx
pkg/interface/src/logic/state/metadata.ts
pkg/interface/src/logic/state/settings.ts
pkg/interface/src/views/App.js
pkg/interface/src/views/apps/chat/ChatResource.tsx
pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
pkg/interface/src/views/apps/chat/components/ChatPane.tsx
pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
pkg/interface/src/views/components/GroupLink.tsx
pkg/interface/src/views/components/ProfileOverlay.tsx
pkg/interface/src/views/components/RemoteContent.tsx
pkg/interface/src/views/landscape/components/Content.tsx
pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx
pkg/interface/src/views/landscape/components/GroupsPane.tsx
pkg/interface/src/views/landscape/components/Resource.tsx
pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarList.tsx
pkg/interface/src/views/landscape/components/Skeleton.tsx
pkg/interface/src/views/landscape/index.tsx
pkg/npm/api/lib/BigIntOrderedMap.ts

metadata-fe: fix preview fetch
interface: refactor sidebar, improve routing
chat-fe: improve render performance
interface: improve memoization and event listening of components
interface: improve memoization of hooks, state
@urbit/api: faster BigIntOrderedMap size accessor
Difficult to get solid numbers on performance improvements, but feels faster.

interface: general performance sweep

---

pkg/interface/src/views/apps/links/components/LinkBlocks.tsx
pkg/interface/src/views/components/VirtualScroller.tsx

Virtualises Grid view of collections

Collections: virtualise grid view

---

pkg/interface/src/logic/lib/graph.ts
pkg/interface/src/logic/state/contact.ts
pkg/interface/src/logic/state/graph.ts
pkg/interface/src/views/components/Author.tsx
pkg/interface/src/views/landscape/components/Home/GroupFeed.tsx
pkg/interface/src/views/landscape/components/Home/GroupFlatFeed.tsx
pkg/interface/src/views/landscape/components/Home/Post/PostInput.tsx
pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostItem.tsx
pkg/interface/src/views/landscape/components/Home/Post/PostReplies.tsx
pkg/interface/src/views/landscape/components/Home/Post/PostThread.tsx

- GroupFeed now uses proper recursive routes
- Improves performance of Author and PostItem components

Post: refactor routing, performance sweep

---

pkg/interface/src/logic/reducers/hark-update.ts
pkg/interface/src/logic/state/settings.ts
pkg/interface/src/views/apps/launch/App.tsx
pkg/interface/src/views/apps/settings/components/lib/DisplayForm.tsx
pkg/interface/src/views/components/FormikOnBlur.tsx

- Stops base hash from obscuring a group tile
- Fixes breakage in customising display settings
- Fixes unread notifications not being cleared on a resubscribe

interface: some bug fixes

---

pkg/interface/src/logic/api/bootstrap.ts
pkg/interface/src/logic/state/metadata.ts
pkg/interface/src/views/landscape/components/Sidebar/SidebarList.tsx
pkg/npm/http-api/src/Urbit.ts

- Fixes a recurrent memory leak on reconnect where we weren't cleaning up the eventsource properly
- Fixes a crash in the DM sidebar
- Reintroduces a timeout for fetching metadata previews

interface: omnibus

---

pkg/npm/http-api/src/Urbit.ts

@urbit/http-api: fix abort signal

---

pkg/npm/api/graph/lib.ts

See #5050 for original notes on issue.

api: update firstborn for correct scry path

---

pkg/arvo/app/btc-provider.hoon
pkg/arvo/app/btc-wallet.hoon
pkg/arvo/lib/bip/b158.hoon
pkg/btc-wallet/src/index.js

Used to take 28s to apply the blockfilter, now takes 8s. 70% improvement.

btc-wallet: refactor and improve performance

---

pkg/arvo/app/btc-provider.hoon
pkg/arvo/app/btc-wallet.hoon
pkg/arvo/lib/bip/b158.hoon
pkg/arvo/lib/bitcoin-utils.hoon
pkg/arvo/lib/bitcoin.hoon
pkg/arvo/lib/btc-provider.hoon
pkg/arvo/lib/btc.hoon
pkg/arvo/ted/btc-rpc.hoon
pkg/arvo/tests/lib/bitcoin.hoon
pkg/btc-wallet/src/index.js

Big props to @ixv for helping track through all of this. Used to take 40s, now takes 0.5s to process a `%block-info` request.

btc-provider: refactor and improve performance

---

pkg/interface/src/logic/lib/util.tsx
pkg/interface/src/logic/reducers/graph-update.ts
pkg/interface/src/logic/state/graph.ts

Fixes strange behaviour in sending messages.

graph-fe: clone requests, to ensure identical timestamps

---

pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx

ResourceSkeleton: shrink title bar on safari

---

pkg/interface/src/logic/api/bootstrap.ts
pkg/interface/src/logic/lib/useLazyScroll.ts
pkg/interface/src/logic/state/local.tsx
pkg/interface/src/views/components/ReconnectButton.tsx
pkg/npm/http-api/src/Urbit.ts

Fixes ghost subscriptions.
interface: fix reconnect backoff
interface: fix simultaneous requests in loading
@urbit/http-api: fix ack debouncing

interface: fix ghost subscriptions

---

pkg/interface/src/logic/lib/omnibox.ts
pkg/interface/src/logic/lib/tokenizeMessage.js
pkg/interface/src/logic/lib/tokenizeMessage.test.js
pkg/interface/src/logic/state/embed.tsx
pkg/interface/src/logic/state/local.tsx
pkg/interface/src/stories/LinkBlockItem.stories.tsx
pkg/interface/src/stories/LinkDetail.stories.tsx
pkg/interface/src/views/App.js
pkg/interface/src/views/apps/chat/DmResource.tsx
pkg/interface/src/views/apps/links/components/LinkBlocks.tsx
pkg/interface/src/views/apps/links/components/LinkDetail.tsx
pkg/interface/src/views/components/RemoteContent/embed.tsx
pkg/interface/src/views/components/leap/Omnibox.tsx

interface: handle malformed group links, fix mixed content errors on embeds

---

pkg/interface/src/views/App.js
pkg/interface/src/views/apps/term/app.tsx
pkg/interface/src/views/apps/term/components/input.tsx
pkg/interface/src/views/components/ImageInput.tsx

interface: fix crash in imageinput
interface: fix auto colorscheme
term: fix babel & tsc issues

interface: patch omnibus

---

pkg/npm/api/graph/lib.ts
pkg/npm/eslint-config/index.js
pkg/npm/http-api/src/Urbit.ts

- Fixes removing posts
- Logs errors from airlock
- Disable JSDoc validation for typescript, because TS uses TSDoc

interface: fix removing posts

---

pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/index.tsx

interface: fix graph deletion

---

pkg/interface/src/views/components/CommentInput.tsx

CommentInput: stop recreating input

---

pkg/arvo/sys/vane/gall.hoon

Should resolve this issue: https://github.com/urbit/bitcoin-wallet/issues/25
cc @finned-palmer

gall: no-op instead of sending %huck in +mo-clear-queue

---

pkg/interface/.eslintrc.js
pkg/interface/src/logic/lib/useFileUpload.ts
pkg/interface/src/logic/lib/useLocalStorageState.ts
pkg/interface/src/views/apps/chat/components/ChatAvatar.tsx
pkg/interface/src/views/apps/chat/components/ChatEditor.tsx
pkg/interface/src/views/apps/chat/components/ChatInput.tsx
pkg/interface/src/views/apps/chat/components/ChatPane.tsx
pkg/interface/src/views/apps/links/components/LinkBlockInput.tsx
pkg/interface/src/views/apps/links/components/LinkSubmit.tsx
pkg/interface/src/views/apps/publish/components/MarkdownEditor.tsx
pkg/interface/src/views/apps/settings/components/lib/BucketList.tsx

Fixes https://github.com/urbit/landscape/issues/1002, also includes moving message state higher and a good bit of refactoring the Chat components involved.

interface: fixing chat reply only firing once

---

pkg/arvo/gen/group-view/join.hoon
pkg/interface/src/logic/reducers/graph-update.ts
pkg/interface/src/views/apps/chat/DmResource.tsx
pkg/interface/src/views/apps/chat/components/ChatEditor.tsx
pkg/interface/src/views/apps/chat/components/ShareProfile.tsx
pkg/interface/src/views/apps/links/components/LinkBlocks.tsx
pkg/interface/src/views/apps/publish/components/NoteForm.tsx
pkg/interface/src/views/apps/publish/components/NoteNavigation.tsx
pkg/interface/src/views/apps/publish/components/NotebookPosts.tsx
pkg/npm/api/graph/lib.ts
pkg/npm/http-api/babel.config.js
pkg/npm/http-api/jest.config.js
pkg/npm/http-api/package-lock.json
pkg/npm/http-api/package.json
pkg/npm/http-api/setupEnv.js
pkg/npm/http-api/src/Urbit.ts
pkg/npm/http-api/test/default.test.ts

ChatEditor: fix mobile input reset
interface: use buttons on banners
Fixes urbit/landscape#705
links, publish: do not visualize deleted nodes
Fixes urbit/landscape#979
interface: fix deleting DM messages
Fixes urbit/landscape#1050
group-view: add +join
Fixes urbit/landscape#287
NoteForm: do not validate on blur
Fixes urbit/landscape#90
interface: skip deleted posts in NoteNavigation
Fixes urbit/landscape#857
@urbit/http-api: add tests, fix uncovered bugs
@urbit/http-api: setup testing

interface: assorted fixes

---

pkg/interface/src/views/apps/chat/components/ChatEditor.tsx

Fixing chat editing

---

pkg/interface/src/views/apps/chat/components/ChatWindow.tsx

ChatWindow: only dismiss if tab has focus

---

pkg/interface/src/views/components/CommentItem.tsx

Fixes urbit/landscape#754 by preventing edit/delete/copy until comment is confirmed

CommentItem: prevent actions until confirmed

---

pkg/interface/src/views/apps/chat/components/ChatEditor.tsx

Fixes urbit/landscape#1059, @liam-fitzgerald not sure what that code was used for do you remember?

ChatEditor: removing unused code preventing slashes

---

pkg/interface/src/views/apps/permalinks/app.tsx
pkg/interface/src/views/apps/permalinks/embed.tsx
pkg/interface/src/views/components/GroupLink.tsx
pkg/interface/src/views/components/StatusBar.tsx

Fixes urbit/landscape#987 and adds same functionality to graph embeds.

embeds: convert embed links for better usability

---

pkg/urbit/daemon/main.c

This reverts commit 6fe8165f1dbcbe4c9c9e3b46d74f431251956be3, reversing
changes made to 991a2310007aebd3d47b708bba1b9d11c804e04e.

Revert "Merge pull request #5107 from urbit/jo/chdir/next-vere"

---

pkg/npm/http-api/src/Urbit.ts
pkg/npm/http-api/test/default.test.ts

Strips the debounce mechanic, instead preferring to send acks when 20 or
more events have not been acked. This is because `setTimeout` in a JS context that is inactive is very unreliable.

@urbit/http-api: ensure acks are sent if timers are throttled

---

pkg/arvo/app/graph-store.hoon
pkg/arvo/mar/metadata/update-2.hoon
pkg/npm/api/graph/lib.ts
pkg/npm/api/metadata/lib.ts

- Fixes scries in graph-store
- FIxes incorrect version number in @urbit/api metadata bindings
- Fixes JSON conversions for metadata-update

landscape: fixes for dated release

---

pkg/interface/src/views/apps/chat/components/ChatEditor.tsx

Fixes urbit/landscape#1062, plz forgive my mess
*edited

ChatEditor: fix ref reference

---

pkg/btc-wallet/src/js/components/lib/balance.js
pkg/btc-wallet/src/js/components/lib/walletModal.js
pkg/btc-wallet/src/js/components/root.js
pkg/btc-wallet/src/js/hooks/useSettings.js

Fixes https://github.com/urbit/bitcoin-wallet/issues/17
@urcades this matches your design here:

btc-wallet: Show wallet scan progress

---

pkg/btc-wallet/src/js/components/lib/send.js

Fixes: https://github.com/urbit/bitcoin-wallet/issues/11

btc-wallet: Add sig to valid patp in send component

---

pkg/arvo/lib/graph.hoon

Should fix weird notification bug.

graph lib: make subset interface work the same as old one did

---

pkg/arvo/app/notify.hoon
pkg/arvo/lib/agentio.hoon

Should resolve this issue: https://github.com/urbit/urbit/issues/5138
May also require running `|fade %notify` followed `|start %notify`, maybe worth doing that automatically in hood if that's an option.

agentio: fix bug with fact-all

---

pkg/arvo/lib/pull-hook.hoon
pkg/arvo/ted/group/leave.hoon

Fixes https://github.com/urbit/urbit/issues/5143

pull-hook: leave quietly, do not crash if we have already left

---

pkg/arvo/app/dm-hook.hoon

This fixes the %notify bug that prevented dms from coming through.

dm-hook: reload agents on dm-hook state change

---

pkg/btc-wallet/src/components/Balance.tsx
pkg/btc-wallet/src/components/Send/BridgeInvoice.tsx
pkg/btc-wallet/src/components/Send/ExternalInvoice.tsx
pkg/btc-wallet/src/components/Send/FeePicker.tsx
pkg/btc-wallet/src/components/Send/Invoice.tsx
pkg/btc-wallet/src/components/Send/Send.tsx
pkg/btc-wallet/src/components/Settings.tsx

@ixv there were a few issues in the bitcoin wallet release branch that got merged into master, all fixed here. Can we get this into master out as an OTA today?
@timlucmiptev

btc-wallet: Fix various issues in prod release last night

---

pkg/grid/src/components/Button.tsx
pkg/grid/src/nav/Nav.tsx
pkg/grid/src/nav/search/AppInfo.tsx
pkg/grid/src/pages/Grid.tsx
pkg/grid/src/state/docket.ts
pkg/grid/src/state/mock-data.ts
pkg/grid/src/tiles/RemoveApp.tsx
pkg/grid/src/tiles/SuspendApp.tsx
pkg/grid/src/tiles/Tile.tsx

Adds missing install dialog, along with updating dialogs to match current mocks. I threw in the bottom mobile nav as a little treat haha.

dialogs: updates to design and mobile tweaks

---

pkg/arvo/app/spider.hoon

Fixes spider to scry the mark conversion from the correct desk

spider: store desk for http response

---

pkg/grid/src/components/AppInfo.tsx
pkg/grid/src/nav/Leap.tsx
pkg/grid/src/nav/Notifications.tsx
pkg/grid/src/nav/Search.tsx
pkg/grid/src/nav/SystemMenu.tsx
pkg/grid/src/nav/notifications/BasicNotification.tsx
pkg/grid/src/nav/notifications/OnboardingNotification.tsx
pkg/grid/src/nav/notifications/SystemNotification.tsx
pkg/grid/src/nav/search/Home.tsx
pkg/grid/src/nav/search/TreatyInfo.tsx
pkg/grid/src/state/base.ts
pkg/grid/src/state/kiln.ts
pkg/grid/src/state/util.ts
pkg/grid/src/styles/base.css
pkg/grid/src/styles/components.css
pkg/grid/src/tiles/RemoveApp.tsx
pkg/grid/src/tiles/SuspendApp.tsx
pkg/grid/src/tiles/useTileColor.tsx
pkg/grid/vite.config.ts

You can see what was done here:
web+urbitgraph://group/~fabled-faster/landscape-grid-qa/graph/~fabled-faster/grid-qa-feedback-3184/170141184505260310429332571857887428608

grid: qa fixes round 1

---

pkg/arvo/lib/hood/kiln.hoon

Not sure why we were doing this, looks and feel like it unintentionally slipped in.
<details><summary>For reference, old output</summary>
```
kiln: installing %gsh locally
gall: installing %graph-stream-hook
error in %hood
%arvo-response
! /sys/vane/gall/hoon:<[1.495 15].[1.495 36]>
! /app/graph-stream-hook/hoon:<[65 5].[79 7]>
! /app/graph-stream-hook/hoon:<[66 5].[79 7]>
! /app/graph-stream-hook/hoon:<[66 9].[72 11]>
! /app/graph-stream-hook/hoon:<[66 13].[66 45]>
! /app/graph-stream-hook/hoon:<[76 7].[78 8]>
! [%missing-dependency %app %fakeid-store]
! /app/graph-stream-hook/hoon:<[77 7].[78 8]>
!
~[
[ %rose
p=[p=":" q="" r=""]
q
[   i
[ %rose
p=[p="/" q="/" r=""]
q
[i=[%leaf p="app"] t=[i=[%leaf p="graph-stream-hook"] t=[i=[%leaf p="hoon"] t=~]]]
]
t=[i=[%leaf p="<[77 7].[78 8]>"] …
```

kiln: don't +mean the tang noun alongside the tang

---

pkg/grid/src/nav/preferences/AppPrefs.tsx

app-prefs: fixing logic around enabled

---

pkg/arvo/mar/kiln/bump.hoon
pkg/grid/src/app.tsx
pkg/grid/src/nav/Leap.tsx
pkg/grid/src/nav/Nav.tsx
pkg/grid/src/nav/notifications/Inbox.tsx
pkg/grid/src/nav/notifications/SystemNotification.tsx
pkg/grid/src/pages/Grid.tsx
pkg/grid/src/state/mock-data.ts
pkg/grid/src/tiles/Tile.tsx

- Fixes `|bump` json conversion
- Correctly identifies blocked desks, includes them in `except=`
- Fixes detection of a blocked %base update

arvo, landscape: fix upgrade flow

---

pkg/arvo/lib/hood/kiln.hoon
pkg/arvo/mar/kiln/bump.hoon
pkg/garden/desk.docket-0
pkg/grid/src/app.tsx
pkg/grid/src/nav/Leap.tsx
pkg/grid/src/nav/Nav.tsx
pkg/grid/src/nav/notifications/Inbox.tsx
pkg/grid/src/nav/notifications/SystemNotification.tsx
pkg/grid/src/pages/Grid.tsx
pkg/grid/src/state/mock-data.ts
pkg/grid/src/tiles/Tile.tsx

This includes several fixes to kiln's handling of kelvin version updates.  These need to be released *before* the actual kelvin change.
For releasing the %garden changes, we need to downgrade ~mister-dister-dozzod-dozzod's %base +zuse and sys.kelvin, then commit these changes to %garden.

kiln: Fix for kelvin updates

---

pkg/arvo/app/azimuth.hoon

Also reprocess state in +on-load for ships which currently have unprocessed state.

azimuth: stop processing state in %watch

---

pkg/urbit/noun/events.c

This PR makes vere automatically backup it's checkpoint on save, if no backup already exists. If any error occurs while attempting to create a backup, the `bhk` directory and its contents are entirely removed, so a subsequent save will reattempt to create a backup. For now, there is no automatic backup restoration; this functionality is being added to help prevent the most onerous event log replay situations.

u3: backup checkpoint on save (if no backup exists)

---

pkg/arvo/lib/azimuth.hoon

To account for the recent upgrade.

azimuth: update ecliptic address

---

pkg/landscape/app/invite-store.hoon

Makes this scry available over JSON, as per @narner request.

invite-store: change /all scry to return %invite-update

---

pkg/interface/src/views/apps/launch/App.tsx
pkg/interface/src/views/apps/launch/components/Groups.tsx
pkg/interface/src/views/landscape/components/Join/Join.tsx
pkg/interface/src/views/landscape/components/Join/Skeleton.tsx
pkg/npm/api/groups/lib.ts

- Removes automatic redirect
- Fixes dismissal of the modal popover
- Fixes background color of Join Group button

interface: address design nits for group joining

---

pkg/interface/src/views/apps/launch/components/Groups.tsx
pkg/interface/src/views/landscape/components/Sidebar/SidebarList.tsx

interface: hide invite if joined

---

nix/sources-pmnsh.json

Add configure flags from most recent secp256k1 nixpkgs.

pmnsh: update secp256k1

---

pkg/urbit/jets/e/hmac.c

As suggested by @joemfb. Probably not _that_ big a deal here, but figured it's worth doing anyway.

jets: cache hmac hashing gate

---

pkg/hs/urbit-king/lib/Urbit/Vere/Term.hs

king: don't kill on C-d

---

pkg/interface/src/logic/lib/omnibox.ts
pkg/interface/src/logic/reducers/hark-update.ts
pkg/interface/src/logic/state/settings.ts
pkg/interface/src/views/App.js
pkg/interface/src/views/apps/chat/components/ChatEditor.tsx
pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
pkg/interface/src/views/apps/publish/components/Note.tsx
pkg/interface/src/views/apps/settings/components/lib/CalmPref.tsx
pkg/interface/src/views/components/CommentInput.tsx
pkg/interface/src/views/components/VirtualScroller.tsx
pkg/interface/src/views/components/leap/Omnibox.tsx
pkg/interface/src/views/landscape/components/GroupSwitcher.tsx

interface: fix unreads not clearing chats
Fixes urbit/landscape#761
interface: inset by safe-area on iOS
Fixes urbit/landscape#242
interface: add disable spellcheck setting
Fixes urbit/landscape#79
interface: strip apps from landscape omnibox
Fixes urbit/landscape#1295
landscape: do not show cross-desk notifications
interface: prevent hook crash in publish notes
Fixes urbit/landscape#1299
Fixes urbit/landscape#1343
interface: remove My Channels link from GroupSwitcher
Fixes urbit/landscape#1331

groups: misc frontend fixes

---

nix/pkgs/urbit/default.nix
pkg/urbit/configure

This branch includes support for building on M1 Mac with stock nix.

build: arm64 architecture

---

pkg/urbit/Makefile
pkg/urbit/c/queue.c
pkg/urbit/include/c/queue.h
pkg/urbit/tests/queue_tests.c

A simple queue abstraction will likely come in handy in multiple places.

c3: implement generic queue backed by doubly linked list

---

pkg/interface/src/logic/api/index.ts
pkg/interface/src/logic/lib/notificationRedirects.ts
pkg/interface/src/logic/lib/omnibox.ts
pkg/interface/src/views/apps/launch/App.tsx
pkg/interface/src/views/apps/launch/components/Groups.tsx
pkg/interface/src/views/apps/permalinks/embed.tsx
pkg/interface/src/views/components/GroupLink.tsx
pkg/interface/src/views/landscape/components/Join/Join.tsx
pkg/landscape/desk.docket-0

- Handles join kind more safely
- Handles web+urbitgraph in join prompt

hotfix/groups: fix join links

---

pkg/landscape/app/observe-hook.hoon

landscape: cache marks again

---

pkg/urbit/jets/e/slaw.c

As uncovered by #5595, see #5161 for context.

jets: plug leak in (slaw %p ...)

---

pkg/landscape/app/graph-store.hoon

Also adds a /keys equivalent for the archive.

graph-store: fix scrying into archive

---

pkg/arvo/app/language-server.hoon

Looks in all desks when attempting to build a file and picks the first match.

arvo: language-server desk support

---

pkg/urbit/daemon/main.c
pkg/urbit/include/vere/vere.h
pkg/urbit/vere/io/http.c
pkg/urbit/vere/pier.c

Based off of `jo/khan-c3`, which already added `per_s` / `pes_s` to `u3_pier` (though on the write end.)

vere: add http/s port flags

---

pkg/grid/src/nav/notifications/BasicNotification.tsx

Fixes https://github.com/urbit/landscape/issues/1417 (for grid/landscape).

grid: Fix notification order in inbox

---

pkg/garden-dev/lib/hark-store.hoon
pkg/npm/api/hark/lib.ts

Allows notifications to be created from the frontend, and adds api bindings for the same 
cc: @patosullivan

hark: add %add-note JSON decoder

---

pkg/interface/src/logic/lib/useStorage.ts
pkg/interface/src/views/apps/chat/components/ChatInput.tsx
pkg/interface/src/views/apps/chat/components/ChatPane.tsx
pkg/interface/src/views/apps/links/components/LinkBlockInput.tsx
pkg/interface/src/views/apps/links/components/LinkSubmit.tsx
pkg/interface/src/views/components/StatelessUrlInput.tsx

This fixes https://github.com/urbit/landscape/issues/1411
To test: provide a bad s3 config.
Shows an exclamation point icon (and some helpful copy) when s3 failures occur in collections and chat:
Tooltip in chat on mobile:

groups: fix silent s3 failures

---

pkg/urbit/vere/io/http.c

does what it says on the can ...

vere: adds runtime status endpoint (reflecting current spinner state)

---

pkg/npm/api/groups/lib.ts
pkg/npm/api/package.json

Fixes: https://github.com/urbit/landscape/issues/1440

npm: fix issue caused by set var in groups/lib.ts

---

pkg/interface/src/views/landscape/components/Participants.tsx

fixes: https://github.com/urbit/landscape/issues/1447

groups: fix dm from participant list

---

pkg/interface/src/views/apps/publish/components/MarkdownEditor.tsx
pkg/interface/src/views/apps/publish/components/MarkdownField.tsx
pkg/interface/src/views/apps/publish/components/NoteForm.tsx

fixes: https://github.com/urbit/landscape/issues/1446

groups: fix add submitted state for notebook form

---

pkg/grid/src/nav/Leap.tsx

fixes https://github.com/urbit/landscape/issues/1445

landscape/grid: Prevent cen from breaking react router in grid's leap

---

pkg/arvo/gen/show-vat.hoon
pkg/arvo/gen/vat.hoon

```
> +vat %base
%base
/sys/kelvin:      [%zuse 419]
base hash:        ~
%cz hash:         0vp.akf4t.1b75q.fvff5.2rfi8.ua7sg.o94fv.4hvpg.cc2b7.acv12.m70bh
app status:       running
force on:         ~
force off:        ~
publishing ship:  ~
updates:          local
source ship:      ~
source desk:      ~
source aeon:      ~
pending updates:  ~
::
```
```
> +vat %kids
%kids %cz hash:     0ve.81ebi.6r6mi.9460t.jkk2v.h1giq.ga5gn.7t234.g9d4p.j579a.dpmb5
```
@belisarius222

vat: add +vat, a single-desk version of +vats

---

bin/solid.pill
pkg/arvo/sys/zuse.hoon
pkg/arvo/tests/sys/zuse/format.hoon

Adds a signed integer JSON parser, i.e. a gate of type $-(json @s)

zuse: add ++ns:dejs:format

---

Makefile
pkg/urbit/daemon/main.c
shell.nix

Opening this PR to test #5824 (and clean up odds and ends along the way)

vere: cleanup (remote pr test)

---

.github/workflows/vere.yml
Makefile
pkg/urbit/daemon/main.c
shell.nix

Broken in the last release, will target further changes to this branch to test.

vere: fix ci for remote PRs

---

pkg/interface/.eslintrc.js
pkg/interface/package-lock.json
pkg/interface/package.json
pkg/interface/src/views/apps/publish/components/MarkdownEditor.tsx
pkg/interface/src/views/components/RichText.tsx
pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx

This resolves a few issues:
- following paragraphs erroneously being included in blockquotes
- channel descriptions being rendered incorrectly because of latest react-markdown version
- incorrect background in notebook editor on dark mode

groups: pre-ota fixes omnibus

---

pkg/urbit/.gitignore
pkg/urbit/Makefile

Running "make compile_commands.json" after configuring does the
needful.

vere: build: add ability to create compdb (for Clangd etc.)

---

pkg/grid/src/components/Checkbox.tsx
pkg/grid/src/preferences/SecurityPrefs.tsx
pkg/grid/src/preferences/SystemPreferences.tsx

Closes https://github.com/tloncorp/homestead/issues/354

landscape: Add new logout modal, update Checkbox style

---

pkg/grid/src/nav/Help.tsx
pkg/grid/tailwind.config.js

Closes: https://github.com/tloncorp/homestead/issues/353
TODO:

landscape: Update help to match new designs

---

pkg/grid/src/components/icons/MagnifyingGlassIcon.tsx
pkg/grid/src/preferences/SearchSystemPrefences.tsx
pkg/grid/src/preferences/SystemPreferences.tsx

Closes https://github.com/tloncorp/homestead/issues/376

landscape: new system preferences search

---

pkg/grid/package-lock.json
pkg/grid/package.json
pkg/grid/src/preferences/ApperancePrefs.tsx
pkg/grid/src/preferences/SystemPreferences.tsx
pkg/grid/src/state/settings.ts

Closes: https://github.com/tloncorp/homestead/issues/352

landscape: new appearance prefs

---

pkg/grid/src/preferences/ShortcutPrefs.tsx
pkg/grid/src/preferences/SystemPreferences.tsx

Closes https://github.com/tloncorp/homestead/issues/349
Edit: this should be good to go now outside of the missing keybindings themselves.
Still need:

landscape: new shortcut prefs

---

pkg/grid/src/preferences/AttentionAndPrivacy.tsx
pkg/grid/src/preferences/SystemPreferences.tsx
pkg/grid/src/state/settings.ts

Closes: https://github.com/tloncorp/homestead/issues/350

Landscape: Add new calm engine prefs

---

pkg/arvo/sys/vane/ames.hoon

This should fix the issue with @zalberico's ship DOSing @arthyn's ship.

ames: don't start pump timers on recork

---

README.md

README: /using/install -> /install

---

pkg/landscape/app/s3-store.hoon
pkg/landscape/gen/s3-store/set-region.hoon
pkg/landscape/lib/s3-json.hoon
pkg/landscape/sur/s3-0.hoon

Allows us to use this field in the new garden/grid: https://github.com/urbit/garden/pull/13
We also need to talk about pulling this out of the %landscape desk at some point.

Groups/Garden: Add s3 region to s3 settings

---

pkg/urbit/noun/allocate.c

I ran into this and paired with @joemfb on it for a while today.  It appears to work when you remove this line, but it's very slow -- this is important information that we should document in the code.

u3: add comment explaining willoc logic

---

pkg/urbit/daemon/whereami.c
pkg/urbit/daemon/whereami.h

Thanks to [nartesfasrum](https://github.com/nartesfasrum) for the solution.
fixes urbit/urbit#6100

vere: updates whereami dep to support OpenBSD

---

pkg/garden/app/docket.hoon

Improves %docket's cleanup behaviour

docket: remove charge if docket file no longer exists

---

pkg/landscape/app/group-store.hoon

migration: adding crash fix

---

MAINTAINERS.md

Fixes: #6213
Markdown formatting fixes.

Fix broken formatting

---

.github/workflows/ota.yml

ci: autodeploy from develop instead of next/arvo

---

bin/solid.pill

Rebuilds the solid pill, this one works without issue.
Closes #6222.

pill: rebuild the solid pill

---

bin/multi-brass.pill
bin/multi.pill

bin: update multi.pill, delete multi-brass.pill

---

MAINTAINERS.md

MAINTAINERS.md: improve tagging instructions

---

pkg/arvo/gen/hood/install.hoon
pkg/arvo/lib/hood/kiln.hoon

This reverts commit 427e219b5be9881832618dcfd6046acd8839b131, reversing changes made to 86cf63986b87cd9bcaeb4bc449c24ae0091a18c9.

Revert "Merge pull request #6199 from urbit/philip/install-once"

---

pkg/arvo/gen/show-vat.hoon

show-vat: fix +show-vat to work with wafts

---

.github/ISSUE_TEMPLATE/config.yml

fixes tloncorp/landscape-apps#1799

meta: fix landscape reporting link

---

tests/run/hints.hoon

This is the development branch for the %meme hint.
The meme hint will have two verbosity modes:
0: slog the arena graph
1: slog all memory info and the graph

Dane.bettis/meme hint next

---

pkg/arvo/ted/eval.hoon
pkg/arvo/ted/khan-eval.hoon
pkg/base-dev/lib/strandio.hoon

Related to [#197 in urbit/vere](https://github.com/urbit/vere/issues/197).
This PR introduces threads which will be useful to any `conn.c` client. More specifically, these threads will be specifically targeted by the thin and thick clients I plan to produce for the issue linked above.

Add threads to run arbitrary hoon

---

pkg/arvo/lib/hood/kiln.hoon
pkg/arvo/sys/lull.hoon
pkg/arvo/sys/vane/ames.hoon
pkg/arvo/sys/vane/clay.hoon

Merging this release candidate back to develop https://github.com/urbit/urbit/releases/tag/urbit-os-v2.136-rc2

Merge urbit-os-v2.136-rc2 back to develop

---

pkg/arvo/sys/vane/ames.hoon

Fixes #6451
(testing on ~norsyr-torryn, will open for review after is done)
(Update: I have not seen an instance of the issue this PR is solving on my ship, so I haven't been able to find a repro to test it yet)
(Update 2: [repro found](https://gist.github.com/yosoyubik/ca58b34f0781c22a7d27c562f056d3b1), opening for review)

ames: reset timer for naxplanations on corked bones

---

pkg/arvo/sys/vane/ames.hoon

Hotfix broken old %ames loads

---

pkg/base-dev/lib/sss.hoon

i/6501 `+live` logic in `+give`

---

pkg/arvo/sys/vane/ames.hoon

ames: fix impure state update in inner cores

---

MAINTAINERS.md

..and make a real markdown table

meta: don't codeblock table in MAINTAINERS.md

---

pkg/arvo/sys/vane/ames.hoon

Fixes https://github.com/urbit/urbit/issues/6579

ames: on-take-wake no-op if not path for keen

---

pkg/arvo/gen/ames-keys.hoon

Fixes https://github.com/urbit/urbit/issues/6584

gen: add +ames-keys generator

---

pkg/arvo/sys/vane/clay.hoon

clay: shortcircuit identity casts

---

pkg/base-dev/mar/noun.hoon

Addresses #6514.
I tried to add grow to jam in noun, and to mime in jam, but this solution seems to be simpler.

feat: noun to mime

---

pkg/arvo/sys/vane/ames.hoon

Extracted from https://github.com/urbit/urbit/pull/6518/commits/7d153ba99ae4839ec386308dd358ac7e331d7a7f

ames: don't no-op if getting %ack on nack bone

---

pkg/arvo/sys/vane/clay.hoon

clay: add requests permission checks

---

pkg/arvo/app/dojo.hoon

`+complete-naked-poke` now works for all agents.
`:do<tab>`
```
:docket
:dojo
```

dojo: complete-naked-poke for all agents

---

pkg/arvo/sys/hoon.hoon
tests/sys/hoon/map.hoon

Has a corresponding [jet PR in Vere](https://github.com/urbit/vere/pull/439)

hoon: refactor unnecessary parameter to bif:by

---

pkg/arvo/sys/vane/ames.hoon

building on #6669, per https://github.com/urbit/urbit/issues/6596#issuecomment-1601548234.

ames: reinitialize rift for all ranks, not just moons

---

pkg/arvo/sys/arvo.hoon

arvo: fix scry permission check

---

pkg/arvo/app/ping.hoon

ping: add dbug lib

---

pkg/arvo/sys/lull.hoon
pkg/arvo/sys/vane/ames.hoon
pkg/arvo/sys/vane/gall.hoon

As described by https://github.com/urbit/UIPs/blob/main/UIPS/UIP-0105.md.

lull, gall, hoon: drop pokes for non-running agents

---

pkg/arvo/app/dojo.hoon

dojo: fix bad gall scries with | on non-null =dir 

---

pkg/arvo/app/roller.hoon

Fixes a type check that becomes evident with the fix introduced in https://github.com/urbit/urbit/pull/6751#issuecomment-1678965707

roller: fix state migration

---

pkg/arvo/sys/vane/ames.hoon

Same as https://github.com/urbit/urbit/pull/6761 for develop

ames: reinitialize congestion control values (bis)

---

pkg/arvo/app/roller.hoon
pkg/arvo/sys/vane/ames.hoon

See https://github.com/urbit/urbit/pull/6761#issue-1854981029 for context

ames:  fix state migration in 412 after merging #6762

---

pkg/arvo/app/hood.hoon
pkg/arvo/gen/hood/approve-merge.hoon
pkg/arvo/gen/hood/global-automerge.hoon
pkg/arvo/gen/hood/jump/approve.hoon
pkg/arvo/gen/hood/jump/propose.hoon
pkg/arvo/gen/hood/jump/reject.hoon
pkg/arvo/gen/hood/sync-automerge.hoon
pkg/arvo/gen/jumps.hoon
pkg/arvo/gen/updates.hoon
pkg/arvo/lib/hood/kiln.hoon
pkg/arvo/mar/kiln/approve-merge.hoon
pkg/arvo/mar/kiln/jump-ask.hoon
pkg/arvo/mar/kiln/jump-opt.hoon
pkg/arvo/mar/kiln/jump.hoon
pkg/arvo/mar/kiln/sync-update.hoon
pkg/base-dev/mar/kiln/approve-merge.hoon
pkg/base-dev/mar/kiln/jump-ask.hoon
pkg/base-dev/mar/kiln/jump-opt.hoon
pkg/base-dev/mar/kiln/jump.hoon
pkg/base-dev/mar/kiln/sync-update.hoon
pkg/base-dev/sur/hood.hoon

Reverts urbit/urbit#6800
Looks like this wasn't needed after all.

Revert "Revert "kiln: OTA merge approval (UIP 114)""

---

pkg/arvo/sys/lull.hoon
pkg/arvo/sys/vane/gall.hoon

As suggested by @joemfb in https://github.com/urbit/urbit/pull/6785#issuecomment-1753142434

lull: add egg-any tagged union for gall scry

---

pkg/arvo/app/dojo.hoon

dojo: fix incorrect beak desk on non-base generator

---

pkg/arvo/sys/vane/eyre.hoon

If the cache entry for any given url was cleared, eyre would recognize that an entry was bound at some point in the past, and serve a 404, instead of falling back to the normal, cacheless, dynamic response.
Here, we make eyre serve from the cache only if there is a full cache entry for the url, and have it proceed into normal request handling logic otherwise.
This way, setting a cached response for some url no longer means giving up dynamic responses on that url for the rest of time.
Recent versions of vere exhibit the same behavior. As such, in practice, this code won't get hit without a similarly-patched version of the runtime. For that, see the sister PR, urbit/vere#603.
Resolves #6702.

eyre: dynamic responses for empty cache entries

---

pkg/arvo/ted/test.hoon

It appears that bb8ba24 merged changes to /ted/test from #6790 and #6896 incorrectly, as the thread no longer compiled.
Because the former PR essentially included the change made to the latter (printing with slog priority 3 in case of failure), the minimum viable fix is taking the contents of /ted/test from #6790 and using those as-is.
However, that had hidden success prints behind a "quiet" flag, and provided no way of configuring that from outside the thread. So additionally, we expand the ""vase parsing"" performed on the thread's argument, such that an optional _first_ parameter of a quiet=? may be passed.
(Should the merge commit have had green CI checkmark in light of this? Presumably not, but I'll consider that out of scope for this PR.)
(I also have opinions about the output style …

tests: make /ted/test compile again

---

flake.nix
nix/test-fake-ship.nix
pkg/arvo/app/test.hoon
pkg/arvo/ted/test.hoon

This one contains #6917 and #6918 but for next/kelvin/411.

ci: fix ci on next/kelvin/411

---

pkg/arvo/sys/vane/ames.hoon

ames: remove spurious print

---

pkg/base-dev/lib/test.hoon

Just noticed what looks like a typo in the comment :)

Fixing comment in test.hoon

---

pkg/arvo/sys/hoon.hoon

I haven't actually tested whether this is faster than what we have, but it should be since it's nonrecursive.  I have tested that the algorithms match what was there, including for zero.

hoon: faster implementation of tuple indexing

---

pkg/arvo/mar/egg-any.hoon
pkg/base-dev/mar/egg-any.hoon

add `mar/egg-any/hoon` to `%base` for ease of poking agents from `%dojo`. 
`:my-agent &egg-any the-egg`

base: add egg-any mark

---

bin/jumbo-pair.pill
bin/mesa-groups.pill
pkg/arvo/gen/hood/hi.hoon
pkg/arvo/lib/hood/helm.hoon
pkg/arvo/sys/lull.hoon
pkg/arvo/sys/vane/ames.hoon
pkg/arvo/ted/hi.hoon

mesa: misc. bugfixes

---

pkg/arvo/sys/zuse.hoon
tests/sys/zuse/crypto/chacha.hoon

By @lukechampine, extracted from #6932 (initially committed on `jb/dire`).

zuse: add chacha

---

pkg/arvo/sys/vane/ames.hoon
pkg/arvo/sys/vane/clay.hoon
pkg/arvo/sys/vane/eyre.hoon
pkg/arvo/sys/vane/gall.hoon
pkg/arvo/ted/meta.hoon
pkg/arvo/ted/peek.hoon
pkg/base-dev/lib/strandio.hoon
tests/app/tend.hoon
tests/sys/fine.hoon
tests/sys/vane/eyre.hoon
tests/tend.hoon

same as https://github.com/urbit/urbit/pull/7163 but giving `%tune`(s) to agents instead of `%sage` so we don't break the API in 410K

mesa: client handling of %sage in 410K

---

pkg/arvo/sys/lull.hoon
pkg/arvo/sys/vane/gall.hoon

gall: fix clear queue when reviving agents

---

pkg/arvo/sys/vane/ames.hoon

this fixes a problem where we would no op if hearing a new sponsor %diff from %jael

ames: refetch public-keys
