urbit/urbit

- urb/zod/arvo/ames.hoon
- urb/zod/arvo/eyre.hoon
- urb/zod/arvo/ford.hoon
- urb/zod/arvo/gall.hoon
- urb/zod/arvo/hoon.hoon
- urb/zod/arvo/zuse.hoon
Handy summary of what's removed, with roughly the commits where they were last used, and also any that I ignored, with reasons.
At some point the docs will need to be cleaned accordingly.
Tested with :reset and :reload
Removed
========
%ames
----
* ++trox
* 5c894854ff770b663b5cae2588496478555d367c:jupiter/sys/192/arvo/ames.hoon:            ^+  ..trox
%eyre
----
* ++loco
* 1eb32f5ee46f3b910da0bf701cde814c12129d60:urb/zod/arvo/eyre.hoon:      ^-  (list ,[p=path q=path r=loco])
%ford
----
* ++colt
* a1c776ada1e1b65917c39ffcbab763efddb820ae:urb/zod/arvo/ford.hoon:  `vase`!>((colt `axle`+>-.$))
%gall
----
* ++colt
* a1c776ada1e1b65917c39ffcbab763efddb820ae:urb/zod/arvo/gall.hoon:    ++  stay  `vase`!>((colt `axle`+>-.$))
* ++rapt
* a1c776ada1e1b65917c39ffcbab763efddb820ae:urb/zod/arvo/gall.hoon …
> ruthlessly amputate extraneous arms

- Makefile
Turns out I didn't remove that just to break the Linux build.
> Conditionally disable unused-result on OpenBSD

- Makefile
So, sometimes PWD isn't exported. Like if you're in some kind of
weird sudo login session or something.
I don't know. It was broken for me. This fixed it.
> Use pwd command, not PWD env var

- extras/hoon-mode.el/hoon-mode.el
If you're editing two files in emacs, e.g. 5/hymn.hook and 6/hymn.hook, emacs will describe each on their modeline bars as "hymn.hook".  This is opaque.
This patch makes them display as "5/hymn.hook" and "6/hymn.hook".
> modeline bar improvements

- n/a.c
This implementation assumes that u3a_calloc is always called with
safe sizes and just asserts that.
> Overflow detection in u3a_calloc

- extras/hoon-mode.el/hoon-mode.el
- urb/zod/docs/pub/doc/guide/a-ford.md
Smarter approach to emacs mode.
Fix obsolete ford docs; ":cd" does not exist.
> emacs tweak, ford doc tweak

- Makefile
Guys. We already did this. Just not for *BSD.
This reverts commit e6becced960b6a35cfcd75f123a3d63152430318.
> Revert "fixed linux build"

- README.markdown
Notable issues:
- The +cat example doesn't work. At all. You can't even try to type the path without breaking :dojo.
- The "Control Characters" example for ^X is a lot more lack-luster now. Instead of being able to spawn arbitrarily many console apps that wait for input, being able to kill and swap between them at will, you can only have one console app running under a :dojo instance and arbitrary other ^V app. This is bad, since if a reader is going through the file sequentially they may not have a program other than :dojo running, making it looks broken. I moved the ^V section to the top so they can hopefully put the pieces together...
- Someone should really proofread this. Make sure I updated all the hostnames and shipnames, since I had to do that manually, and that everything read …
> Readme update!

- README.markdown
Doing a `;join /urbit-meta` from the initial :talk prompt only works if you are running a destroyer. Since this is the readme and it claims they aren't giving out destroyers (;D), there is a good chance the reader is running a sub, which need the full path for the room to join.
> Proper :talk instructions

- urb/zod/base/lib/react/core.hook
This adds a React processing rule, making any \<pre urb:exec=""\> tags have their contents evaluated and added below the tag. It includes handling crashing code.
I'm not that sure how safe this is, however - should the `++slap` have a different context without access to the vanes? Although right now this should only be used for `:tree` library examples, if `:talk` gets a markdown message type it would also be able to use it. That would be a problem, and so it needs to be reasonably secure, both with no `%clay` access and no infinite-runtime code.
> runnable <pre urb:exec=""> examples

- README.markdown
This adds a dependency missing in the command to install the dependencies on Fedora and changes the command to use DNF instead of Yum since the latter is no longer part of the base system in the stable version of Fedora.
> Fixes to the command to install dependencies on Fedora

- debian/control
cmake is a build-time dependency and has been for some time
> debian build deps

- vere/main.c
Makes the `~` part of `./bin/urbit -F -I ~zod -c fake_zod` optional. Should be able to cleanup the CONTRIBUTING.md file a little bit to remove the disclaimer, and not require a \ under zsh.
> optional sig

- vere/http.c
Always ignore EPIPE (broken pipe) errors, and only show the rest of them if running urbit -V
> Hide libuv socket errors

- noun/nock.c
Rather than use a switch statement in what looked to be the main loop of the nock interpreter, use computed gotos instead.  This should speed things up and is a typical pattern for interpreters.
> Thread the nock interpreter using computed gotos.

- vere/main.c
28 is the length of a ticket plus a leading sig, should anyone enter it.
If you enter an invalid ticket, it will panic later while setting up the pier, but with a nice "ticket: invalid secret '~foobar'" error message instead of the current bail.
I fired up a fakezod, +ticket'd ~doznec, and was able to run ./bin/urbit -F -c fake_doznec -w doznec and enter the ticket, so I assume it's all working fine.
> Ask for ticket, close #366

- vere/main.c
We've had an ugly unexplained segfault when you try to -c a pier that already exists. This adds a quick existence check.
> Check if directory already exists when using -c

- urb/zod/ape/talk.hoon
Barebones nicknaming functionality in console talk.
Further extension required:
- completion (per talk spec)
- removing nickname entries
- displaying nicknames if available
- webtalk support
> Talk nicknames

- vere/main.c
Reference: https://github.com/urbit/urbit/commit/fbfd7987f0ef48146902ab9b1850765c58e26645
// jfranklin9000 fork, test branch
https://github.com/jfranklin9000/urbit/blob/test/vere/main.c
https://github.com/jfranklin9000/urbit/commit/165cfc8ac265e6fedbd5b0bced1be91a07c37836
Check my git-fu before pulling.
The patch is intended to be one line in one file.
> Generalize the message if trying to use -c or -w on an existing pier.

- include/vere/vere.h
Two edits in a single file (include/vere/vere.h).  No change to the compiled code.
> Fix some comments in vere.h.  No changes to the compiled code.

- urb/zod/ape/talk.hoon
There was a suggestion by ~matfeb-sablud to change the rendering of moon names on talk. This change now renders moons (say, ~sampel-sipnym-matwyc-sablud) as ~matwyc^sablud in the console talk.
Discussion?
Obviously this would make it difficult to discern different moons from the same planet in chat, but if moons are meant to be closely bound to planets, is that such a problem?
> Change moon name rendering in talk

- noun/events.c
Ref: https://github.com/urbit/urbit/issues/441
> print loom and fix a range calculation in u3e_fault()

- .gitignore
- Makefile
I renamed target `tags` (and generated file `.tags`) to `ctags` (`.ctags`) and use the `tags` target to build all of the targets `ctags`, `etags`, `gtags` and `cscope`.  I can take that part out if it's a problem.
> Add gtags (gnu global) and cscope tag generation targets.

- urb/zod/pub/talk/src/css/main.css
- urb/zod/pub/talk/src/css/main.styl
This just keeps the writing box in `:talk` from causing crazy things to happen when you put a lot of text in it.
> #writing fix

- include/vere/vere.h
- vere/main.c
This patch adds a command line option to report urbit build info.
bin/urbit -R
---------
Libraries
---------
gmp: 6.0.0
sigsegv: 2.10
openssl: OpenSSL 1.0.2d 9 Jul 2015
curses: ncurses 6.0.20150808
I can make changes (rename/move stuff, change the flag option/processing, etc) if needed.
> Add command line option to report urbit build info.

- CONTRIBUTING.md
As discussed on talk and in various email chains, it's basically a confusion-inducing relic right now. Changes that we are unsure about putting in can stay in the issue tracker as open pull requests.
> Put 'test' on ice for outside contributors

- vere/http.c
Currently, things that cause %eyre to lose connection (mark recompiling, kernel recompiling, dropped connections) have these printf messages. It's a bit scary to see "server not found" followed by a pointer in the middle of a kernel update.
Not sure how useful it is for ~fyr, so just put it behind the verbose flag.
> ignore dropped requests printf

- urb/zod/ape/dojo.hoon
barring any consensus on whether paths are a useful thing ~in general~ hoon code, they still should work in dojo, with the unified syntax if nobody's finalized a split one
> Reintroduce special path parser for =% to fix #565

- urb/zod/pub/docs/dev/hoon/runes/cn/cndt.md
- urb/zod/pub/docs/dev/hoon/runes/cn/cnkt.md
- urb/zod/pub/docs/dev/hoon/runes/cn/cnls.md
- urb/zod/pub/docs/dev/hoon/runes/kt/kthp.md
- urb/zod/pub/docs/dev/hoon/runes/kt/ktls.md
- urb/zod/pub/docs/dev/hoon/runes/ts/tsbr.md
- urb/zod/pub/docs/dev/hoon/runes/wt/wtdt.md
- urb/zod/pub/docs/dev/hoon/runes/wt/wtgl.md
- urb/zod/pub/docs/dev/hoon/runes/wt/wtgr.md
- urb/zod/pub/docs/dev/hoon/runes/wt/wthp.md
- urb/zod/pub/docs/dev/hoon/runes/wt/wtkt.md
- urb/zod/pub/docs/dev/hoon/runes/wt/wtls.md
- urb/zod/pub/docs/dev/hoon/runes/wt/wtpt.md
- urb/zod/pub/docs/dev/hoon/runes/wt/wtsg.md
For runes with straightforward translations to semantically equivalent forms (like `^-(p q)` / `^+(*p q)`), this makes the equivalent form explicit in the reference docs.
It probably doesn't cover all the runes it should, just the ones that I knew of obvious translations for.
> Add "Equivalent to" sections to selected rune docs.

- vere/term.c
This keeps printfs from blowing away the line state (M-m M-m won't erase your prompt).
> Restore terminal line length and cursor position on refresh.

- noun/events.c
Seems to work. I haven't worked with libsigsegv before, but according to [this](http://git.savannah.gnu.org/cgit/libsigsegv.git/tree/src/sigsegv.h.in#n64), `u3e_fault` should return 0 when `ser_i` is 0 in order to give the stack overflow handler a chance to run.
> Fix stack overflow handling in Linux?

- urb/zod/lib/kiln.hoon
The second part of the solution to #666's upgrade problem.  Specifically, kiln now keeps track of what's being autoreloaded when, so that if, e.g. hoon.hoon and a vane are updated at the same time, a single reset is executed.
NB:  Do not merge without a breach.  hood's state-upgrade path was confusing, and it has been deemed an insufficiently valuable use of my time to create the necessary `++prep`.  This is not a particularly critical fix, and Hoon 151 is coming along "any day now", which should bring an intentional breach.
> autoreload sanely

- urb/zod/pub/docs/user/intro.md
Changed `Avro ships it ships with` to `Avro ships with`.
Removed whitespace from end of lines.
> Fix typo in user doc, intro.md

- urb/zod/pub/docs/theory/whitepaper.md
The ones on [this tutorial](http://urbit.org/docs/dev/hoon/principles/2-syntax) seem to be newer. If that's backwards, my bad.
> Update the whitepaper digraphs to match tutorial.

- README.md
Fixing broken links, the fact that the docs aren't on your ship, and that homebrew doesn't work.
> un-break readme

- README.md
Current link is dead, new link appears to have same content
> Updating link to docs

- include/c/motes.h
- vere/term.c
and a new mote: `c3__dot`
this supports the implementations in urbit/arvo#192
> adds term support for meta-. and meta-backspace

- jets/a/add.c
- jets/a/lth.c
- jets/a/mul.c
- jets/a/sub.c
- jets/b/scag.c
- jets/b/slag.c
- jets/c/met.c
- jets/c/peg.c
Some of the core jets observably break Nock semantics by soft-failing on ill-typed samples that the compiled Nock lets through untouched. Because the discrepancies involve soft failures, they're observable via ++mink:
```
> =jet-fails  =/  kick  [9 2 0 1]
=/  bad-jet
|=  {gat/* sam/*}
=.  +6.gat  sam
=/  gut   gat(+2 [7 [0 1] +2.gat])
!=((mack gat kick) (mack gut kick))
=+  [a b]=[[[0 0] 0] [0 [0 0]]]
|.
=-  [(levy tests bad-jet) (lien tests bad-jet)]
^=  tests
%-  ly
:~  [add b]
[sub a]
[mul b]
[lth a]
[lth b]
[peg a(+ 1)]
[scag a]
[slag a]
[met a]
==
> (jet-fails)
[%.y %.y]
```
With this patch:
```
> (jet-fails)
[%.n %.n]
```
> Fix jet discrepancies on ill-typed identity cases.

- jets/f/ut_burn.c
- jets/f/ut_mint.c
Fixes #663. Jet for urbit/arvo#238.
> Prevent ++burn:ut jet from zeroing non-constants.

- include/noun/allocate.h
The size and starting position of Urbit's reserved memory block is set by `U3_OS_LoomBits` and `U3_OS_LoomBase` in `include/c/portable.h`.
`U3_OS_LoomBase` is referenced in `include/noun/allocate.h` and sets the position in memory of u3_Loom.  This is good.
However, `U3_OS_LoomBits` is not actually used to set the size of the reserved memory block.  Instead:
in `include/noun/allocate.h`,
- `u3a_bits` is defined
- `u3a_bits` → `u3a_bytes`
in `noun/manage.c`, 
- `u3a_bytes` → `len_w` in `_cm_init()`
- `len_w` sets the reserved memory block size
This proposal puts `U3_OS_LoomBits` back to work by defining `u3a_bits` with it.
> Use `U3_OS_LoomBits` To Set Reserved Memory Size

- vere/term.c
I'm not sure of the exact details of the bug this code was fixing, but the buffer adjustments in `drum` (`++se-just`) definitely make it unnecessary. It's also the cause of the current issue blocking urbit/arvo#216.
Just thought I should throw it up here for clarity and easy testing. I don't know how or when you'd like to merge/release this.
> removes obsolete history-eating bug-fix from _term_it_show_clear()

- jets/f/ut_mull.c
arvo's sys/hoon.hoon defines the $tune case as:
{$tune *}
[(face p.gen sut) (face p.gen dox)]
Fix the C jet so that it doesn't use sut on both spans.
> Fix ++mull:ut's handling of $tune.

- vere/term.c
This is kind of a hack for getting the terminal (`_term_ef_get(1)`), but at least it's the same pattern used in `u3_term_ef_winc()` via `u3_term_ef_winc()` ...
> refreshes prompt after ^c interrupt

- noun/retrieve.c
Senior nouns were being wrongly unified and freed, breaking
untracked junior references.
This change should also be applied to the maintenance branch.
> Fix a memory corruption issue in u3_sung().

- noun/retrieve.c
This cures the 6+-minute duplicate-triggered boot times
we've seen since the previous fix in unification.
> Temporarily leak duplicates on intermediate roads.

- vere/unix.c
When running in docker for example, urbit always runs as pid 1. If it crashes / is killed too hard, it will try to kill itself on the next start, not cleaning up after itself again, resulting in a bricked pier / restart loop.
Since normal behavior would be to kill the old process, and there cannot be another process if the process' own pid is in the lockfile (even though it's a faulty/unexpected occurence), this should be safe to do.
> Don't kill self with corrupt Lockfile

- include/jets/k.h
- include/jets/q.h
- jets/d/in_tap.c
- jets/f/ut_burn.c
- jets/f/ut_crop.c
- jets/f/ut_find.c
- jets/f/ut_fish.c
- jets/f/ut_fuse.c
- jets/f/ut_nest.c
- jets/f/ut_peek.c
- jets/f/ut_rest.c
- jets/f/ut_wrap.c
- vere/fuse.c
... and indirects through a "rap" jet.
pairs with urbit/arvo#352
I have no problem with the first three commits here. I can add the new "rap" jet, replace all calls to `*_tap()` with `*_rap()`, and everything works without issue. Adding printfs confirms that the correct jet is being called at the right time. The problem comes with the last commit, when I try to remove the tap gate jet and replace it with a renamed rap loop jet. When I do that, I get an immediate core dump. Here's the backtrace:
```
(lldb) bt
* thread #1: tid = 0x0000, 0x00007fff9399ff06 libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGSTOP
* frame #0: 0x00007fff9399ff06 libsystem_kernel.dylib`__pthread_kill + 10
frame #1: 0x00007fff8da7a4ec libsystem_pthread.dylib`pthread_kill + 90
frame #2: …
```
> removes the argument from the tap jet

- .travis.yml
Build server image too old to have it in the repositories
> Require libuv for travis

- Makefile
Added build support for the Nix package manager: https://nixos.org/nix
supersedes #757, forward-ported and ifdef change applied
> Add build support for the Nix package manager

- vere/cttp.c
This is a solution to urbit/arvo#442, thanks to @joemfb for doing the digging. Just a single line deleted.
This should be safe because HTTP requests require only `Host` according to [this source](https://serverfault.com/questions/163511/what-is-the-mandatory-information-a-http-request-header-must-contain) and [HTTP 1.1 - RFC 2616](http://tools.ietf.org/html/rfc2616). Additionally: 
> Content-Length or Transfer-Encoding are only mandatory if an entity is delivered with the request or response, and in many cases a request or response will lack an entity (like a GET request, or a 302 response).
Thus, we are in the clear for removing a default `Accept` header. @belisarius222 suggested that we might want to add one at the Hoon level.
> Remove hard-coded default HTTP request 'Accept: */*' header from cttp.c

- noun/hashtable.c
Previously, trimming the penultimate value from a hash bucket would
leave arm_u in an inconsistent state: mug_w would be pointing at
a key-value pair in a node, but arm_u.buc_o and arm_u.inx_w were
not updated to reflect this. Correspondingly, a rare edge case could
occur where said key-value pair would not be marked cold (due to
buc_o), which is a semantic error.
> Update arm_u state correctly in _ch_buck_trim

- noun/manage.c
re #895, errors on response code >= 300.
ex:
```
$ bin/urbit -FI ~zod -A ./arvo/ -s -c tzqzod
~
urbit 0.5.0
urbit: home is tzqzod
loom: mapped 2048MB
boot: installed 242 jets
fetching https://bootstrap.urbit.org/260c9a4479a15ea0f7b3073eb556f5019da678b0-HEAD.pill to tzqzod/.urb/urbit.pill
error fetching https://bootstrap.urbit.org/260c9a4479a15ea0f7b3073eb556f5019da678b0-HEAD.pill: HTTP 403
please fetch it manually and specify the location with -B
```
> checks HTTP response code when fetching pill

- include/vere/vere.h
- vere/ames.c
- vere/main.c
Defaults to urbit.org
This is a prerequisite for running automated urbit/fleet tests on a separate network.
> added -H ames bootstrap domain

- include/noun/allocate.h
- jets/e/jam.c
- noun/allocate.c
- noun/retrieve.c
Fix stack overflows in jam and unifying equals, and use memoize-by-offset cache when doing equality checks for large nouns.
> Runtime overflows

- Spec/nock/4.txt
Ted's correction somehow didn't make it in!
Just to reiterate, however, on typo version of the spec, `#[2 b c]` reduces to b, which clearly isn't right.  I noticed this, complained in urbit-meta, and Ted pointed me to the github discussion.
> Typo in 4k Nock spec

- vere/ames.c
Prevent Ames from sending and receiving remote packets if networking is disabled.
> Enforce -F / -N network options in Ames

- vere/http.c
libuv 1.19.2 caused all references to `UV__*` codes to break. I think they want us to refer to `UV_*` instead.
> Fix uv error code reference

- include/noun/allocate.h
- jets/e/jam.c
- noun/allocate.c
- noun/retrieve.c
This reverts commit 2e5e8371311a9ba9a4e056cf8d626c8b55e20e4e, reversing
changes made to 5c5374c1fd3dea87d63cb601582027fd74002901.
This fixes #936.
> Revert "Merge pull request #920 from frodwith/runtime-overflows"

- vere/sist.c
Old message incorrectly said a 2048 bit RSA pair was being generated, when in reality it was a curve25519 key pair, as made apparent in issue #876.
I have updated the shown message.
> Updated key generation message. Fixes #876

- include/noun/allocate.h
- jets/e/jam.c
- noun/allocate.c
- noun/retrieve.c
- noun/trace.c
This reverts commit 67d3460a910678fbb7b0e265774f5989ee767573, reversing
changes made to 8d0f6cf3a6407fd6ba17569385cd802e83eb6bf8.
Fixes #936.
> Revert "Merge pull request #941 from frodwith/runtime-overflows"

- README.md
`ninja -C` was made specifically for this case, so users don't have to cd into and out of their build output directory all the time.
> README should recommend `ninja -C`

- include/vere/vere.h
- vere/term.c
- vere/walk.c
... for console `%sav` and `%sag` blits.
closes #427
> recursively mkdir in u3_walk_save

- noun/trace.c
process sampling already takes care to turn off cpu profiling during its
sampling. this "fix" for mid-equality sampling was masking another bug
at an earlier point in the debugging process for the unifying equality
changes. I realized upon reflection that it was incorrect.
> remove well-intentioned equality profile breakage

- vere/ames.c
I think I should be able to reason through the conjunction and/or negation of two boolean conditions, but apparently I cannot. I honestly don't understand how this is different from #959, and yet this works and that doesn't. (And by *works*, I mean that fake-key ships started without -N can communicate over localhost.)
Does anyone have a test-case that will confirm that the issue underlying #919 is still fixed?
/cc @belisarius222
> allows imperial addresses in the absence of -N (fix -F)

- include/vere/vere.h
- vere/http.c
... by adding a state enum to u3_hreq and ignores attempts to send duplicate responses.
This is a workaround for the fact (a bug?) that effects can be applied multiple times. Syncing several files into a %clay mount was the observed trigger.
closes #974
> makes http response %thou effectively idempotent

- noun/allocate.c
This bug caused very slow allocations for certain size boxes.
> bug in _box_slot

- debian/changelog
- meson.build
The breaking change here is urbit/urbit#987, commit 762638ac, changing
the memory allocation size of _box_slot. This introduced urbit/urbit
issue #990 and has required a continuity breach. The version bump here
is mostly to signal to users that they need to update to the new Vere
version to prevent a future ship crash. Though, we can't enforce this,
and if this happens, we have a couple imperfect fixes that may or may
not revive the crashed ship.
> Bump Vere version to version 0.6.0

- vere/main.c
This way, between continuity breaches, we can update the old pills,
adding printf's to them that will trigger upon `~zod is not responding`
messages such as urbit/arvo@c83fb6e23e903a7239187478612dff06c22a3c16,
telling people to pull the latest Vere. And upon breaches, we
can update these bootstrap links. This is a simple/hacky yet reasonably
effective way to help get more people on the same page as it relates to
handling users running different Veres with breaking changes.
> Version the bootstrap.urbit.org boot pill URL

- .gitignore
We're no longer putting the binary into `/bin` (now into `/build` instead),
so we don't need to ignore it anymore.
> Remove unused paths from gitignore

- noun/imprison.c
- noun/jets.c
- noun/retrieve.c
AddressSanitizer doesn't like the iterator/terminator pattern in `tree.c` and `jets.c`, and claims that it constitutes a global buffer overflow. I'm not qualified to adjudicate that claim, so I'm just excluding the relevant functions from AddressSanitizer.
This PR supersedes #915. The build changes are no longer necessary (`meson -Db_sanitize=address $BUILD_DIR`), and the CI integration should be discussed separately (ubuntu on travis is really old).
> ignores AddressSanitizer errors in jets.c

- include/vere/vere.h
- vere/http.c
H2O stops listening on a socket after it parses a complete request, since the client could pipeline multiple requests. It doesn't notice that a client has prematurely closed the connection until it tries to write a response. When we're proxying requests over %ames, it's not unusual for responses to be greatly delayed (if a ship is offline, for instance), so sockets pile up in CLOSE_WAIT. This PR adds a request timeout, which resolves the resource leak.
Thanks to @ramrunner for identifying the issue!
/cc @keatondunsford
> adds an http request timer to ensure connections are always closed

- noun/jets.c
Special thanks to @frodwith for figuring this out after I hit this.
While working on jets and doing memory testing, I was getting a leak that persisted even if I reduced my jet code to `return 0;`. Turns out the fact that I was using jet names longer than four character was giving trouble, only in the specific case of doing memory testing.
As explained by @frodwith:
> so what's happening is
> u3a_lush expects to get a c3_w (referred to elsewhere as cod_w)
> it's the code that prints during leak push
> which, if you're running a jet, is set to the name of the jet
> now, the thing that trims up the cos_c (the name from tree.c) very helpfully trims to a 5-character name
> ....VERY HELPFULLY, since it needs to be a 4-character name to fit in a c3_w
> so we get an indirect atom for cod_w, and …
> Fix issue with trimming >4 character jet names

- noun/trace.c
u3t_samp and u3t_damp were crashing in a call to u3v_do for some reason, which made it impossible to run a ship in profiling mode on release-candidate.
This doesn't fix that crash but just bypasses it by building the noun that was supposed to be returned by the call to u3v_do, manually.
> bypassed profiling bug

- include/config.h.in
- include/noun/allocate.h
- include/noun/trace.h
- meson.build
- meson_options.txt
- vere/http.c
This PR fixes two memory leaks on the release-candidate (introduced by yours truly).
Additionally, it moves the optional definitions of `U3_MEMORY_DEBUG` and `U3_CPU_DEBUG` into the generated `config.h` header, to be set by the custom meson options `-Dgc=true|false` and `-Dprof=true|false` (in the `meson` build generation, not the `ninja` compilation).
These options should be enabled in CI, probably as separate entries in a build matrix. And I think that should happen here, not on the Arvo build that's already heavily burdened. But that means we need a URL for a suitable pill stored in this repo. I'm happy to wire that up if it's deemed worthwhile.
Thoughts?
/cc @eglaysher @belisarius222 @frodwith
> fix memory leaks, add gc and profile build options

- vere/sist.c
Hiya martians :alien: :v:
In my experimentation with moving my planet to a different machine, I decided to follow the advice of the `for real security, write it down and delete the file...` line and remove the `*.code` file before copying dirs around. When I remove the file, urbit prompts me to type in the code instead.
But when entering the code, its printed onto the screen. This might be a small security issue if I'm showing urbit to someone IRL or in a livestream and they can see my planet's code as I type it in, or if i accidentally pastebin the boot output without retracting the code.
This PR makes it so your passcode is not displayed on the screen while you type it in, similar to how the password entry for many other unix programs works.
The logic for this comes from the [getpass …
> Disable terminal echo on passcode entry

- jets/f/ut_wrap.c
In the current release candidate, this happens:
```
> ^?(^|(add))
wrap-gold
ford: %slim failed: 
ford: %ride failed to compute type:
```
This is a jet mismatch from `+wrap`, I believe:
https://github.com/urbit/arvo/blob/release-candidate/sys/hoon.hoon#L11139
You should be able to convert iron and zinc cores to lead.
> converting iron and zinc cores to lead bug

- jets/f/ut_mint.c
A bug causes this cast to go through:
```
^+(|=(@ 15) ^&(|=(@ 15)))
```
It should nest-fail.  This change makes the cast work correctly with the metal wrapping runes `^&`, `^|`, and `^?`.
> Bug fix for metal-wrapping runes

- jets/f/ut_play.c
Casting with a `^&` rune example fails because of a minor jet typo:
```
> ^+(^&(|=(@ 15)) |=(@ 15))
-gene.[%ktpd %brts [%base %atom 0] %sand %ud 15]
play-open-z
ford: %slim failed: 
ford: %ride failed to compute type:
```
The above cast should go through.  This fix makes that happen.
> zinc gate casting bug

- include/vere/vere.h
- vere/main.c
- vere/sist.c
Pairs with urbit/arvo#872.
How can I run the vere changes with garbage collection on?  Is there any additional testing I should do?
This introduces two command line options (open to suggestions on which letters to claim):
- `-E ./ropsten.snap` specifies an Ethereum snapshot to load on boot.
- `-t` says to trust that snapshot for the boot checks as well.  This is useful because it allows you to boot a real ship without connecting to a node at all.  However, if e.g. your key was added to the chain after the snapshot, then this will fail.
To create a snapshot, just run `.ropsten/snap .^(noun %j /=snap=)` after you've synced.
> Allow booting from ethereum snapshot

- noun/jets.c
There were two issues in hashboard preventing the profiling of hinted-but-unjetted arms:
- `_cj_site_kick_hot()` was being called much less than it should have been.
- `_cj_site_kick_hot()` needed to be specialized to accommodate the `u3j_site` usage pattern in `u3j_gate_slam`.
Thanks to @frodwith!
> Fix un-jetted arm profiles

- .travis.yml
- .travis/.gitattributes
- .travis/.gitignore
- .travis/package-lock.json
- .travis/package.json
- .travis/pin-arvo-commit.txt
- .travis/test.js
This PR re-uses @ohAitch's urbit runner and test scripts from Arvo, now in their own repository at urbit/runner-js. We know specify an Arvo commit (or branch, or tag) in `.travis/pin-arvo-commit.txt`, build with GC and profiling enabled, boot a fake-zod, and run `+test`. If urbit bails, we try to print a core dump.
closes urbit/arvo#835
> updates CI to boot and run tests with GC

- vere/sist.c
> make implicit -S persist across fake-keyed restarts

- include/vere/vere.h
- vere/main.c
- vere/sist.c
The pre-boot validation process constructs a priority-order list of domains by reading from the Ships contract, which is a part of the %dawn boot event. This PR re-enables specifying a custom %ames domain with `-H`, by prepending the specified domain to that list (if it's not already in the list).
> restores -H for overriding ames galaxy domain

- .travis.yml
- .travis/print-core-backtrace.sh
We're not currently using the CI deploy phase, but we may someday. My changes in #1051 broke it, as I learned in urbit/arvo#884. Applying the same fix here.
> [CI] fix deploy phase, move coredump backtrace to a script

- vere/http.c
If the ship-specific proxy listener (`u3_ward`) is closed by a timer, the proxy-connection (`u3_pcon`) to which it is linked is closed at the same time. The unlinking of these structs cannot be asynchronous, or there will be a race ...
Note: the memory lifecycle of these proxy structs is overly complicated and should be generally cleaned up. It was written this way to allow the proxy implementation to be polymorphic, but I'm starting to suspect it's just not worth it. I'm not tackling this at the moment, as there are other proxy improvements that should be queued up too.
/cc @vvisigoth
> fixes race in tcp proxy resource cleanup

- noun/retrieve.c
Fixes urbit/arvo#703.
Verified manually that the `bail_fail` happens without this change and that this change fixes it.
> Fix bail_fail on `&33:~`

- vere/http.c
... fixing a platform-dependent crash when we traverse the list to dispose it
> properly zero-initialize u3_wcon linked-list pointer

- jets/e/ed_sign.c
> Use `u3a_malloc` in the ed25519 jet.

- noun/jets.c
- noun/manage.c
if the warm dashboard is reaped before call sites, the activation
(and thus the label inside the activation) can be freed (during u3h_put)
while a call site in the junior still points to the label (but doesn't hold
a reference to it, since it is on a senior road). trying to take that label
during call site reap then results in a bail: foul.
the solution is to always reap call sites before reaping the warm dashboard.
> reap call sites before reaping the warm dashboard

- README.md
supersedes #1039, removing subproject changes. (and `-S` is already on by default for fake ships)
> Fix README build instructions

- include/jets/w.h
- jets/d/by_jab.c
- jets/tree.c
- meson.build
+jab:by showed up in profiling traces when running ford, which makes sense since it is used extensively. 
This is my first de-novo jet that I've worked on. I am unsure about the reference counting here. What's the process for checking that it's all correct?
> Jet +jab:by, which is used extensively in ford.

- jets/f/ut_nest.c
There is a variance bug such that the following cast is allowed to go through:
```
> =a 12
> =core1 ^?  |=(b=@ a)
> =a "hello"
> =core2 ^?  |=(b=@ a)
> ^+(core1 core2)
```
This should not be!  The code in `hoon.hoon` is correct -- it turns out that the jet is wrong however.  It falsely returns "yes" for a nest in which two cores have identical code.  Obviously that's not enough to guarantee sameness of type.  So I've removed the offending lines.
> fix core nest jet mismatch

- include/vere/vere.h
There used to be both u2 and u3 behn declarations in vere.h. I de-duplicated them, but accidentally left some of the u2 declarations in place of u3.
> update old %behn declarations in vere.h

- vere/reck.c
The terminal id is always a simple unsigned integer (and in practice, is always '1'). Instead of calling into hoon code to handle this, just use strtol().
> Remove 30ms per dill-blit.

- include/noun/allocate.h
- include/noun/options.h
- include/noun/trace.h
- include/vere/vere.h
- noun/jets.c
- noun/manage.c
- noun/trace.c
- noun/vortex.c
- vere/loop.c
- vere/main.c
- vere/raft.c
- vere/reck.c
This adds a -j parameter which writes traces of your Urbit's function call
stack to a json file, readable by Chrome's about://tracing or the standalone
trace-viewer webapp.
---
An example of the output (both screenshotted and raw JSON) is in urbit/arvo#905, where I used this tracer to figure out a problem in the kernel.
Right now, this is more a request for comments instead of a real patch since I'm unsure about how I added this to vere. I put in a parallel `trace` to `don`, because I want this to be runnable in normal builds when the user hasn't compiled in `-Dprof=true`. This lets us tell users who are having performance issues to simply restart their urbits for a few moments with another command line flag instead of telling them to recompile their Urbit binary.
manually cc @frodwith …
> Add support for trace_event files.

- vere/reck.c
By using +slaw instead of +slay, we now can use the fast path using the case added in urbit/arvo#910. This removes 10s of milliseconds off each HTTP response.
> Use +slaw instead of +slay.

- include/c/defs.h
Currently, `c3_assert()` calls `c3_cooked` calls `u3m_bail(c3__oops)` calls `assert(0)`. This has the unfortunate side effect of throwing away the context of the original assertion; all assertion failures look like #990 (which is why it became a catch-all). The bail protocol in vere needs polish and enforcement. 
In the meantime, this PR adds a typical assertion printf to `c3_assert()` prior to the call to `c3_cooked()`, so that context is not lost. It still includes `assert()` in the macro to avoid compiler warnings.
> updates c3_assert() to print assertion/file/line before bail

- vere/unix.c
In #1092, I was a little too aggressive in fixing a memory-leak in unix.c and introduced a use-after-free.  I thought I had specifically tested that this was not the case. Mea maxima culpa.
(My fix is to copy paths that are hung onto, hopefully making the allocations easier to track.)
closes #1096
/cc @rmariani
> fix (my own) use-after-free in unix dir/file watch

- vere/ames.c
- vere/term.c
Upon reading from a stream, libuv *always* asks for 64K bytes. We've been helpfully complying, in ames, the terminal, and raft (follower mode). This adjusts the first two, giving constant buffer sizes that seem appropriate (I don't think anyone is using that raft implementation).
Running locally with these changes, I don't see noticeable performance improvements. But I owe to you all to measure more carefully, and will return with details.
> Use smaller heap allocations on libuv i/o reads

- include/vere/vere.h
- vere/loop.c
- vere/raft.c
- vere/sist.c
Augmented the code that processed all the outstanding Urbit events at once with new logic that processes a single event at a time, then schedules the next Urbit event to be processed in a later libuv event.
During normal runtime the events are processed asynchronously one at a time. On boot and shutdown, all events are processed synchronously.
I had originally written this using libuv's "idler" pattern, but that caused pathological changes to the control flow in libuv's event loop and 100% CPU usage, so I abandoned that approach. Instead, I repurposed the timer in the u3Z raft struct to trigger the processing of the next event.
Initial unscientific testing suggests this might feel slightly more responsive in the dojo; certainly pasted text starts appearing much faster. We should test the …
> Process one event at a time

- vere/raft.c
- vere/sist.c
This is a trivial change -- I'm opening this PR so we can discuss whether we want to do so. On the one hand, this subsystem will change dramatically in the near future. On the other hand, it might be worth it for the profiling and opportunity to polish the parts that will persist (particularly the encryption gates in %zuse).
If we decide not to enable this, I think we should remove the passcode and related printfs.
> re-enable event-log encryption

- noun/manage.c
This PR changes u3m_bail to a) not try to print the bail payload (which might be a massive stack trace) with `u3m_p` and b) allows `%fail` bails to continue through the crash handling protocol. I've tested with `(bex (bex 128))` and the compiler crash in urbit/arvo#69; both now turn into `%crud` replacement events.
`%fail` was made to abort instead of follow in 68c6adf3e1cf16317207abc664b836b648f2b4a6, and `%meme` was similarly changed. Both previously fell through to the `%exit` case. @cgyarvin, do you remember why this was changed?
> don't abort on bail:fail, but continue with crash handling

- include/c/portable.h
- meson.build
- vere/main.c
- vere/sist.c
Tested with stock clang on an OpenBSD 6.4 amd64 VM. Unfortunately
clang (and also gcc from ports) was not pleased about c3_rand,
whereas this was fine before. I have no idea what changed, but it
works now.
cc @joemfb
> Fixes the build on OpenBSD

- vere/raft.c
Return a u3_none rather than a u3_nul so that we don't crash.
I think this is the thing you were referring to right @joemfb ? It seems to have fixed my problem.
> fix _raft_lame bug

- include/c/defs.h
- vere/raft.c
- vere/sist.c
- vere/term.c
- Condense the allocator section in defs.h and make it match the
surrounding style.
- Use real calloc in c3_calloc. Some guy on the internet says
calloc can be faster than malloc since the OS may not actually
need to call memset.
- Replace calloc calls in vere code with c3_calloc.
Note that I left the c3_calloc definition as-is (i.e., not taking
a count argument). I was going to change it, but it seems like
count is 1 at all call sites. If it's ever used with count != 1,
I'd be in support of changing it, fwiw.
> Clean up allocator defs

- vere/term.c
or, term.c hack 2: electric boogaloo (re #1125)
Rather than do nothing when we get the mysterious EOF on paste, this PR calls the misnamed `u3_lo_bail()` to shutdown gracefully. If we don't do this, event-log corruption is likely.
> updates terminal read callback to shutdown gracefully on EOF

- vere/term.c
We encountered a problem where pasting a string of exactly 64 characters (but no more or less) crashes a ship.
This just changes the number of bytes that gets allocated so that our 64 char keys can be pasted into the dojo. This is a terrible hack and should probably be flagged for an actual fix.
> term.c hack

- vere/main.c
Opening this as a fallback option, in case we are able to add battery hashes to `tree.c` in sufficient time. Note that this change makes the `-S` argument a no-op.
> globally disable hashboard (pending actual hashes)

- noun/retrieve.c
- tests/hash_tests.c
They were changed in #1123 to calculate block aligned hashes, but we require them all to be exactly equivalent.
This partially fixes #1128, but ctrl-z is still fragile and inconsistent. Still looking for more ...
> corrects u3r_mug_chub and u3r_mug_words

- include/noun/retrieve.h
- include/vere/vere.h
- noun/retrieve.c
- vere/http.c
This PR includes a new hardcoded domain for the TCP proxy, fixes a couple small, known issues, and some minor refactoring.
The hardcoding is unfortunate -- it would be better for the domain to be given in an %eyre effect (along with the http configuration, perhaps). At the same time, it would just be hardcoded in %eyre then. I haven't added a CLI argument for the domain either (there's been a massive proliferation of arguments lately), but I can do that if there are strong feelings.
> tcp proxy cleanup

- .travis.yml
- include/c/defs.h
- include/c/portable.h
- include/vere/vere.h
- vere/sist.c
N.B. this broke the travis build since it uses a super old kernel. I bumped it to xenial, i.e. 16.04.
This should work on Linux since kernel 3.17, OS X since 10.12, OpenBSD
since 5.6, and FreeBSD since 12.0. It also introduces no external
dependencies. Note that getentropy should only be called with at most
256 bytes or it will return EIO. The getrandom variant on Linux doesn't
check for this. If called with len > 256, it's allowed to produce a
short read if it gets interrupted. This should show up as an error, so
everything's fine.
> c3_rand cleanup

- tests/hash_tests.c
> fix heap allocation in hash_tests

- vere/ames.c
Calling `exit()` here trashes the terminal.
> exit cleanly if $galaxy is already running (fake or real)

- vere/raft.c
This changes a few things about event replacement
- a failed %hold card (itself representing a failed %hear card) now becomes a %crud
- %warn is ifdef'd out, since nothing in arvo supports it
- we print the head of the card if we get to "all delivery failed"
If we agree that %warn should go, I'll remove it completely. All the vanes that take cards from unix currently accept %crud.
> cleans up event error handling in _raft_lame

- vere/sist.c
This traverses the event log in reverse order, for each event writes it out as is, plus the 4 byte header indicated the size
> added _sist_rest_nuu for g -> h log format conversion

- include/vere/vere.h
- vere/sist.c
To replay an event log, instead of loading the entire event log into memory, don't.
In order to do this, we changed the event log format to store a header before each event containing the size of that event, so that we can traverse backward and forward.
> replay one event at a time

- .travis/test.js
- include/config.h.in
- include/noun/allocate.h
- include/noun/jets.h
- include/noun/manage.h
- include/noun/nock.h
- include/noun/vortex.h
- meson.build
- meson_options.txt
- noun/allocate.c
- noun/events.c
- noun/jets.c
- noun/manage.c
- noun/nock.c
- noun/vortex.c
- vere/raft.c
refactors and unifies memory marking implementation for GC and `|mass`
> fixes |mass

- vere/sist.c
I haven't yet figured out how to get this assertion to pass, which would require modifying `cur_d`, probably by moving it to the next event. My first attempts at that failed, however, so at least this seems to behave properly.
I'm not sure we need the assertion anymore, since we started at the end of the event log and worked backward to get to this point. This assertion was copied from the old logic, which made the assertion if we didn't read any events from the event log.
> replay most recent event too

- noun/manage.c
A comment in manage.c links to now-nonexistent docs. I will soon be making a PR to the docs that will add the referenced section in getting-started.udon.
Related issue: https://github.com/urbit/urbit/issues/1164
> fixes dead link to swap instructions

- include/c/portable.h
- vere/unix.c
Above feature macro is needed on glibc 2.17 era, in order to activate ftw* related functions/macros.
> vere/unix.c: set _XOPEN_SOURCE

- vere/loop.c
- vere/raft.c
Note that libnoun still runs GC after exiting an inner road. The old GC calling convention in `loop.c` was not consistently handling effects. Specifically, it considered incoming HTTP requests to have been leaked. Moving the call to `_raft_grab()` ensures we always treat the event and its effects as roots when we mark the loom.
> cleans up vere GC call sites, runs once after event

- jets/tree.c
This PR does not enable hashboard, or mess with related CLI arguments (yet). To actually use hashboard, one still needs to tinker with `main.c` (commenting out `u3C.wag_w |= u3o_hashless;`, for instance).
In addition to adding the hashes, this PR corrects parent and hook axes in many declarations. Some of these have probably been incorrect since hashboard was merged, some were probably always incorrect (the crypto additions, for instance). Both cases were my fault, as I handled the relevant merges.
I've opened this PR now because the standard-library batteries should be relatively stable going forward. I expect we will only want to add hashes to `tree.c`, not replace them as batteries change, but that remains to be seen.
This PR can go in as, since it doesn't change any behavior. Or we …
> adds sha-256 battery hashes to the jet dashboard, corrects axes

- include/noun/trace.h
- include/vere/vere.h
- noun/trace.c
- noun/vortex.c
- vere/main.c
- vere/raft.c
The output of -j tracer is now split every 100,000 lines so that chrome doesn't choke on large traces (is this a reasonable number?) Also stuck the output of these in the put directory under a subdirectory called trace, and named them by unix date.
Stuck |mass outputs in their own subdirectory of put, called mass, for better organization.
> QOL improvements for -j trace and |mass outputs

- include/noun/manage.h
- noun/events.c
- noun/manage.c
- tests/hash_tests.c
- tests/hashtable_tests.c
- tests/test.c
- vere/sist.c
These changes to loom initialization and checkpoint restoration are just a backport from cc-release.
The changes to replay are to just to make it simpler to investigate replay failures. On failure, we print some more event metadata, jam and write the failing event to disk, take a checkpoint at the previous event, and then exit. Every 100K successful events, we also take a checkpoint.
> simplifies loom init/restore, checkpoints during replay

- vere/dawn.c
As brought up in #1130. Turns out the printf had completely disappeared from `dawn.c`. Seems this happened during refactoring in b13f444.
I'm using "boot:" as the printf prefix here, since the majority of the printfs in `dawn.c` seem to use that. There's two existing printfs that say "dawn:" instead. That latter seems to be a bit clearer about where the printf and related logic lives, should I go ahead and change those while I'm at it?
> Re-add dawn snapshot printf

- include/vere/vere.h
- vere/pier.c
- vere/save.c
- vere/serf.c
This PR forward-ports our solution to space leaks in the bytecode cache (by clearing caches on kernel resets and every 1k events), and wires up the checkpoint timer.
> cc-release: reclaim memory regularly, automate checkpoints

- include/vere/vere.h
- noun/vortex.c
- vere/king.c
- vere/pier.c
- vere/reck.c
- vere/serf.c
This PR fixes a leak in `u3v_lite()`, so the GC that runs when booting an ivory pill now passes.
This PR implements also `|mass` in the I/O process, but leaves it def'd out -- there are either leaks in `pier.c` and the I/O drivers, this GC pass is missing roots, or both. In any case, I'd like to get the implementation in early, rather than waiting to find and fix all leaks.
> cc-release: enables gc and implements |mass in the i/o process

- noun/allocate.c
- "leak" means actual uses are 0, but reference count is > 0
- "dank" means actual uses are > 0, but reference count is 0 (ie "reverse-leak":  we're still using freed memory; corruption is likely to occur).
- "weak" means actual uses are > 0, but actual uses are != reference count (i.e. this will be a leak or a dank at some point).
This was recorded correctly in `leq_w`, just printed wrong.
> if sweep gives 0 and reference count != 0, leak

- pkg/urbit/include/noun/manage.h
- pkg/urbit/include/vere/vere.h
- pkg/urbit/king/main.c
- pkg/urbit/noun/manage.c
- pkg/urbit/noun/trace.c
- pkg/urbit/serf/main.c
- pkg/urbit/vere/king.c
- pkg/urbit/vere/reck.c
This PR adds tracing functionality to cc-release.
The serf process is responsible for tracing nock computation and writing the output to a file. In the future we'll want to trace i/o as well, which needs to happen on the king.
> cc-release tracing

- pkg/urbit/include/vere/vere.h
- pkg/urbit/king/main.c
- pkg/urbit/serf/main.c
- pkg/urbit/vere/ames.c
- pkg/urbit/vere/king.c
- pkg/urbit/vere/pier.c
- pkg/urbit/vere/reck.c
- pkg/urbit/vere/save.c
- pkg/urbit/vere/term.c
- pkg/urbit/vere/unix.c
- removes precommits
- sequences compute, commit, and effect application
- ensures that snapshots are correlated with the most recently committed event (ie, never run ahead of the event log)
- adds explicit initialization and operation states to the pier, assertions to ensure valid state transitions
and fixes various other minor issues
> cc-release event state machine corrections

- pkg/urbit/include/vere/vere.h
- pkg/urbit/king/main.c
- pkg/urbit/vere/pier.c
Some further enhancements to and cleanup of the work done in #1232:
- batch event reads during replay
- remove a superfluous state flag in the pier
- use more specific conditions and assertions for some pier state transitions
- reorder pier initialization, disabling absurdly inefficient explicit log header read
> cc-release pier boot state-machine corrections

- sh/mk-bootbus
- sh/mk-bootzod
- sh/mk-fakezod
The scripts don't work on OSX because of the `-L` option. I talked to Ben and he said to just remove it.
> Remove the -L from the cp statements, since it is erroring on OSX.

- bin/brass.pill
- pkg/urbit/include/noun/jets.h
- pkg/urbit/include/noun/options.h
- pkg/urbit/include/noun/trace.h
- pkg/urbit/include/vere/vere.h
- pkg/urbit/king/main.c
- pkg/urbit/noun/jets.c
- pkg/urbit/noun/manage.c
- pkg/urbit/noun/nock.c
- pkg/urbit/noun/trace.c
- pkg/urbit/noun/vortex.c
- pkg/urbit/serf/main.c
- pkg/urbit/vere/king.c
- pkg/urbit/vere/pier.c
- pkg/urbit/vere/term.c
This PR sends `%slog` hints over the pipe from the king to the serf, restores the terminal spinner, removes special handling for ames initialization during the boot sequence, and refactors all of `pier.c`, grouping functions by the subsystem with which they are concerned.
Here's a much more readable diff, excluding the refactoring of pier.c: https://github.com/urbit/urbit/compare/e1c3e2b...ccr-slog-clean
In the long run, `%slog` hint output should probably be sent straight to syslog, or some similar system. In the short term, much to much of the system depends on that output making it directly to the terminal in predictable fashion, so I've taken the shortest available path to making it so.
Once urbit/arvo#1138 is merged, I'll update the arvo submodule and brass pill here as well.
/cc …
> cc-release: reliable output handling and refactoring

- pkg/urbit/noun/trace.c
- pkg/urbit/worker/main.c
This PR takes the shortest path to re-enabling -P sample profiling. Since we print the output upon shutdown, we print directly to stderr -- we can't reliably send the output over the pipe back to the daemon.
In the longer term, we may want to explicitly request the profiling output be sent over the pipe, write it to a file, etc. But we may also just want to remove it in favor of the trace profiling. I think it should remain enabled in some form until such a time as a final decision can be made (and the relevant work scheduled).
/cc @benjamin-tlon
> cc-release: restores -P sample-based profiling

- pkg/urbit/daemon/main.c
- pkg/urbit/include/noun/vortex.h
- pkg/urbit/noun/events.c
- pkg/urbit/noun/manage.c
- pkg/urbit/noun/trace.c
- pkg/urbit/noun/vortex.c
- pkg/urbit/vere/pier.c
- pkg/urbit/vere/term.c
- pkg/urbit/worker/main.c
This PR merges master into cc-release, further replaces `perror()` and similar functions with `u3l_log()`, cleans up some recent additions to the worker, and removes obsolete code/members for `vortex.c` and `u3A`. The latter two deserve further notes:
- we move the mug-chain checking/enforcement/error printing exclusively into the worker (previously split across worker and daemon), and require it at all times, not only during replay
- we fix a bug where the kernel mug was not being appropriately captured on process restart
- we separately track event-numbers in the worker for latest request and latest completed, so log/slog messages during event evaluation have the correct event number
- we make sure that `u3A->now` is always set to the time of the last successful event evaluation when …
> cc-release general cleanup

- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/lmdb.c
- pkg/urbit/vere/pier.c
When we have lots of small events, Urbit's throughput is hampered by `fsync()` costs on a per-event basis. This patch lets us batch up multiple events so they're committed to lmdb as a single transaction.
> Batch event log commits

- vere/sist.c
I took a shot at this.  I hope I didn't step on any toes.
There are some questions in the comments so it's not ready for merging.
It only looks for `'\n'`, not for `'\r'`, `"\n\r"` or `"\r\n"`.
I tested by booting moons using keyfiles with and without a trailing newline.
Both cases succeeded.
Requesting review by @joemfb
> Handle trailing newline in keyfile.

- default.nix
Running `./scripts/nixbuild` on a NixOS machine, i get the following error:
```
jgl@n3: ~/repos/urbit $ ./scripts/nixbuild
these paths will be fetched (0.16 MiB download, 1.00 MiB unpacked):
/nix/store/4vgpb5yb350mvw7czvnn9hha3p8spgvn-cmark-0.28.3
copying path '/nix/store/4vgpb5yb350mvw7czvnn9hha3p8spgvn-cmark-0.28.3' from 'https://cache.nixos.org'...
The Meson build system
Version: 0.46.1
Source dir: /home/jgl/repos/urbit
Build dir: /home/jgl/repos/urbit/build
Build type: native build
Project name: urbit
Native C compiler: gcc (gcc 7.3.0 "gcc (GCC) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Found pkg-config: /nix/store/sbg7j9ghnhl3kiw5gck9khhr2wwd5y8f-pkg-config-0.29.2/bin/pkg-config (0.29.2)
Native dependency ncurses found: YES …
```
> Add `git` to default.nix dependencies

- pkg/urbit/vere/lmdb.c
With lmdb, you have to have a maximum file size. I set this to a gigabyte during development, but I suspect ~zod would blow past this limit.
I've gone with 40gb here as a (hopefully) safe guess for now.
> Use a 40 gigabyte log size

- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/daemon.c
- pkg/urbit/vere/dawn.c
- pkg/urbit/vere/pier.c
This PR includes a variety of small fixes and tweaks:
- fixes a use-after-free in pier.c
- adds (disabled) helper code to print the keypair for a comet
- separates process limit handling in the daemon and the worker
- disables core dumps in the daemon
- updates the daemon (only) to print a backtrace on SIGABRT.
Core dumps are still enabled in the worker, but disabled in the daemon due to their now unwieldy size (as the entire event-log is mmap'd). Example output from a SIGABRT on the daemon:
```
Assertion '0' failed in vere/pier.c:1510
bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file noun/manage.c, line 663.
backtrace:
1   libsystem_platform.dylib            0x00007fff6b0e2b3d _sigtramp + 29
2   urbit                               0x000000010babecc8 …
```
> cc-release: fix memory bug, tweak limits and core dumps

- Makefile
- bin/brass.pill
- bin/solid.pill
- pkg/urbit/Makefile
- pkg/urbit/jets/e/cue.c
- pkg/urbit/tests/jam_tests.c
- pkg/urbit/tests/mug_tests.c
- pkg/urbit/vere/http.c
The PR gets `lighter-than-eyre` back to a working state on top of `cc-release`.
There's a new, pre-authorized `%request-local` task for `%rver` sent by the "lens" server, which is bound to localhost (thanks @ixv!). The cc-release daemon-mode "boot-complete" callback is restored to the `%form` effect handler (a inelegant but effective heuristic). And HTTP2 is disabled (for now). This also includes a merge of the latest cc-release to pick up the improvements to the +cue jet.
> lte: restore lens control plane

- nix/ops/default.nix
- nix/ops/fakeship/builder.sh
- nix/ops/solid/builder.sh
This fixes the incorrect pill-staging behavior discussed in urbit/arvo#1171.
I've only made this change to the use of `+solid` and not that of `+brass`. This implies that changes should be staged in the solid.pill, and that the brass.pill should be updated afterwards. This strikes me as the desired developer experience, and the correct approach more generally, but I'm open to dissent. (Long story short, if you're going to do both, run `./sh/update-solid-pill` *before* `./sh/update-brass-pill`.
> cc-release: uses a separate desk and manual commit for +solid staging (avoids -A)

- pkg/urbit/daemon/main.c
Fix for #1279, which I appear to have introduced when reconciling cc-release and master CLI argument parsing (by reordering the conditions to support new functionality). This code remains horrible and incredibly difficult to follow, but this fixes the most pressing problem.
> removes incorrect early return in cli argument-parsing

- pkg/urbit/jets/e/cue.c
- pkg/urbit/noun/retrieve.c
NB, this PR is not urgent.
I've rewritten the mug implementation to maintain the stack discipline developed in #1275, and tweaked the conventions for both. We have a few of these potentially-massive recursive noun traversals, and I think it would be very helpful for them to follow the same conventions to the degree that's possible. I also think this refactoring makes for a clearer and simpler implementation on its own merits.
This is the right place to bikeshed this style, naming conventions, stack usage, etc. If approved, I'm inclined to implement the same style in the +jam jet, as will as u3r_sing/u3r_sung (noun equality, unifying). This kind of code is intrinsically complicated, but it would be much easier to work with if it were consistent.
> cc-release: revise explicit-stack conventions in mug

- pkg/urbit/include/c/defs.h
- pkg/urbit/noun/allocate.c
- pkg/urbit/noun/events.c
- pkg/urbit/noun/manage.c
- pkg/urbit/vere/daemon.c
Namely, enabling slog hint printfs during ethereum pre-boot validation (in the daemon) and disabling cross-process (worker to daemon) printfs when handling errors (segmentation faults and OOM).
> cleans up some printf edge-cases on cc-release

- CONTRIBUTING.md
- README.md
(Resolves #1235.)
The main changes to `README` have simply been to remove the detailed build information, which is now subsumed by Nix.  I've added the simple `curl` one-liner instruction for downloading Nix, as well as pointed at the Makefile for performing most desirable dev tasks.
Note that the `README` also points at the "Getting Started" section of the docs proper.  I'm updating that in turn and will PR my changes when we release 0.8.0.  You can see the changes I've made [here](https://github.com/urbit/docs/commit/9b2b34e6ca2ac15e4e12e800fdb4d00b22679637) -- again, I've simplified the installation instructions and have primarily pointed at the static binaries we produce for macOS and Linux.
`CONTRIBUTING` hasn't changed much, but was missing from the cc-release branch.
> Update README, CONTRIBUTING for 0.8.0 release.

- sh/ci-tests
This PR fixes the monorepo merge builds in CI by removing the pill staging (which was causing request timeouts to be hit due to resource contention due to being run in parallel with testing under GC). If we decide it's useful and want to bring it back, we should use the TravisCI build-matrix functionality to run it in a separate job.
> fix monorepo merge builds in CI

- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/tests/sys/vane/ames.hoon
I've been trying to track down the %ames retry failures (leading to states where ships need to be `|bonk`'ed), using the included packet-sending test to inspect the state transitions. Along the way, I discovered that pings to a ship's sponsorship chain are sent very rarely, as their gated by the "network era" timestamp set on restart by the `%kick` event. What's more, they'll never be sent with the current runtime, as it doesn't send the `%kick` event (which is unquestionably my fault).
This could be handled one of two ways: adding `%kick` to the runtime, or disabling the condition. I chose the latter, as that will have the side effect of sending a lot more pings. I expect that in turn to keep routes from being timed out, to result in less packet forwarding, and generally keep the network …
> disables (kind of) spurious condition in %ames ping flow

- nix/ops/test/builder.sh
- pkg/urbit/configure
- pkg/urbit/include/vere/vere.h
- pkg/urbit/noun/allocate.c
- pkg/urbit/vere/daemon.c
- pkg/urbit/vere/pier.c
- pkg/urbit/worker/main.c
plugging memory leaks and refactoring the implementation along the way.
This work is on response to #1322, but nothing I've found explains or fixes the issue(s) reported therein. This PR enables us to measure usage in the daemon, which should help track down that meme.
> enables |mass in the daemon

- pkg/arvo/app/acme.hoon
- pkg/arvo/gen/acme/domain-validation.hoon
- pkg/arvo/gen/hood/serve.hoon
- pkg/arvo/tests/app/acme.hoon
Specifically, this turns inbound domain-validation HTTP requests into stateless reads (via a generator), and tracks order attempts correctly in order to backoff in case of errors.
This also fixes the old `|serve` generator to create the new `%eyre` generator bindings.
> minor robustness fixes for :acme

- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/ames.c
This is effectively a very heavy-handed "autobonk" to work around our occasional, as-of-yet undiagnosed loss of ames/behn timer rectitude.
/cc @vvisigoth
> adds ~m5 wakeup timer to vere for ames

- nix/pkgs/urbit/default.nix
- nix/pkgs/urbit/release.nix
- nix/release.nix
- pkg/urbit/.gitignore
- pkg/urbit/Makefile
- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/daemon.c
This writes the SSL certs to a temporary file on startup and then
uses environment variables to control OpenSSL and curl so that
they use them. We have to do this because OSX no longer ships the
normal ca pems, and we statically link with these libraries.
Half of #1299
> Embed the nix SSL certificate file into the resulting binary.

- nix/pkgs/urbit/builder.sh
- nix/pkgs/urbit/release.sh
- pkg/urbit/Makefile
To prevent the `./urbit` vs `urbit` problem from happening again, as discussed in person.
> Move urbit output binary to a build directory.

- pkg/urbit/vere/pier.c
As reported in #1322 
@eglaysher, do you recall why the daemon/worker protocol passes `[mug ovum]` as a jammed pair instead just passing them in the tuple? Is it to save on (re-)serialization cost for persistence?
> plugs leak in daemon replacement-event handling

- bin/solid.pill
- pkg/arvo/sys/vane/ames.hoon
The turf was, in fact, bogus. As noted in #1262 and many other places.
> fixes jet-registration hint in %ames +turf-scry (for profiling)

- pkg/urbit/vere/unix.c
This moves the process exclusion enforcement on a pier (via `.vere.lock`) earlier in the startup process. If you try to run the same pier in two different processes, the newer process will kill the older. This worked before, but works better now -- the earlier we do it the less can go wrong in the intervening period.
> acquires pier lockfile on io_init instead of io_talk

- pkg/urbit/daemon/main.c
I wrote report() with the Libraries header a while ago but removed it as un-urbit-like on the master branch at some point.  This PR does that in this branch.
> Remove cheesy Libraries header in main.c:report()

- bin/ivory.pill
- bin/solid.pill
- pkg/arvo/sys/hoon.hoon
(moved from https://github.com/urbit/arvo/pull/1215)
There are several differences between the hoon for play and the jet:
- The jet handles a bunch of additional cases which no longer exist (%fail, "%zpmc"); I have disregarded these.
- The hoon simply fails to implement %tscm (fixed here).
- The jet and the hoon disagree about how %sand should be interpreted. I've changed the hoon to match the jet, but am unsure this is the right thing to do.
More on the last: There's a distinction between rock constants and sand constants. A rock constant is one whose value (e.g. 1) the type system tracks. A sand constant only has its aura and cellular shape tracked (with a special case for flag and null auras). Or rather, that's what the old hoon said. The new hoon, modified to match the jet, maintains …
> Fix jet mismatch in play

- bin/solid.pill
- pkg/arvo/app/dns-collector.hoon
- pkg/arvo/app/hall.hoon
- pkg/arvo/app/talk.hoon
- pkg/arvo/sys/hoon.hoon
- pkg/arvo/sys/vane/alef.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/vane/eyre.hoon
This PR fixes a longstanding issue; `+get:by` was untyped. This also fixes a couple of minor bugs (that would have been prevented had `+get:by` already been typed), and adds some now-necessary casts.
This is logged in #323, with further explanation in urbit/arvo#688. As @ohAitch notes in the latter, adding types here compromises on the notion of a gate -- in particular, the type system is now not able to synthesize a valid sample bunt for `+get:by`. Notably, this breaks gate composition (see the changes in `clay.hoon`. I acknowledge this is a problem, but I think it's less of a problem than having such a fundamental map operation be untyped. I'm curious to hear if anyone feels otherwise.
> adds sample type to +get:by, fixes call-sites

- pkg/arvo/gen/reload-event.hoon
- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/pier.c
Try:
```
> .event/ovo +reload-event %c
$ urbit -I pier/.urb/put/event.ovo pier
```
This will inject any arbitrary event into a pier.  The intended use-case is to rescue ships that are in gridlock due to eg clay issues.
> add -I to inject event

- bin/solid.pill
- pkg/arvo/sys/vane/behn.hoon
- Fix |reload %b by no longer clamming in +load, which can hang or eat up all the memory because the Behn state has vases in it.
- Fix loud, annoying crashes by no-op'ing when Behn receives an unsolicited %wake event from Unix.
> Behn fixes

- pkg/arvo/app/talk.hoon
Hmm I thought I already opened this PR, but must have neglected to hit submit.
Simple, backwards-compatible change that allows you to optionally append a glyph to the end of `;join` and `;create` commands, to prevent talk from auto-binding for you, if you already know what glyph you want to use.
> Allow glyph binding during ;join and ;create

- pkg/arvo/app/talk.hoon
Fixes #1381.
Not sure why we ever rendered `$read` updates in the first place, but it _certainly_ shouldn't be an empty string. This just remove sit altogether.
> Don't sh-note updates to a circle's read counter

- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/ames.c
and, as a result, print less (see #1383).
Also, adds explicit packet drop condition if we attempt to send a packet before we're live.
>  updates ames i/o driver to track galaxy state transitions

- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
When we ask an app to run a %handle-http-cancel event, we don't
actually care about the return value or even if it errors. The
cancel event is purely informative. Likewise, because we cause
cancels on restart of urbit, they cannot expose crashes to the
system. Otherwise, an app with an open connection but a broken
or non-existent cancel handler can prevent your ship from
coming back up.
> Fix ~zod crash by fixing how %eyre handles app cancels.

- pkg/urbit/daemon/main.c
- pkg/urbit/vere/daemon.c
- pkg/urbit/vere/pier.c
- pkg/urbit/worker/main.c
This PR ignores SIGPIPE in both daemon and worker processes (which is correct, since we handle socket errors directly). It also handles turns SIGQUIT into SIGABRT in the daemon (to avoid dumping ~45 GB of core. Finally, it cleans up the handling of worker process exits.
> exit cleanly where appropriate; don't, where not

- nix/crossdeps.nix
- nix/deps-env.nix
- nix/deps/ca-header/builder.sh
- nix/deps/ca-header/cross.nix
- nix/deps/ca-header/default.nix
- nix/deps/default.nix
- nix/deps/ivory-header/builder.sh
- nix/deps/ivory-header/cross.nix
- nix/deps/ivory-header/default.nix
- nix/pkgs/default.nix
- nix/pkgs/urbit/default.nix
- nix/pkgs/urbit/release.nix
- nix/pkgs/urbit/shell.nix
- nix/release.nix
- pkg/urbit/Makefile
- pkg/urbit/configure
We embed the ivory pill into the daemon process, so we can eval hoon without IPC. As of #1374, that embedding is automated. Currently, the ivory pill is checked in via git-lfs, and if git-lfs has not been properly initialized, the contents of the ivory pill are just an LFS pointer (some descriptive text and hashes). If that's the case, the codegen and build complete successfully, but the resulting binary just prints `lite: boot failed` if you try to boot or restart a ship with it. That's obviously unacceptable. 
This PR adds some conditions to fail the build if the ivory pill appears to be an LFS pointer. But, in it's current state, it's still pretty unsatisfactory. It does not print a useful error message when it fails the build, and I don't know how to fix that. The current state of …
> updates ivory codegen to fail if ivory.pill is an lfs pointer

- pkg/urbit/jets/e/cue.c
- pkg/urbit/jets/e/jam.c
- pkg/urbit/noun/allocate.c
- pkg/urbit/noun/nock.c
- pkg/urbit/noun/retrieve.c
This PR replaces road stack sanity assertions (`bail:oops` on error) with explicit `bail:meme` error conditions. It also adds such error conditions to the `+jam` jet and the nock bytecode interpreter, where previously there were none.
/cc @frodwith
> uses bail:meme for all road stack-overflow error conditions

- pkg/arvo/app/talk.hoon
Fixes urbit/arvo#743.
The problem is that `~(pfix cen (stag self urs:ab)` catches the bare `%` character before we get to parsing glyphs instead of circles.
This basically replaces urs:ab in circle parsing with an exact copy implemented in terms of `plus` instead of `star`. I find this re-implementing somewhat unaesthetic, let me know if there's a smarter way to do this.
Another option that I discussed with @Fang- is to just parse glyphs before circles instead. Glyph parsing is however implemented in terms of `mask` which would never allow `%foo` to fall through to circle parsing as it should.
> Fix % not working as talk glyph

- pkg/arvo/sys/vane/eyre.hoon
See screenshot.
@g-a-v-i-n Do we have a specific font weight for ship names or is this adequate?
> Change ship name CSS in eyre to monospace

- pkg/arvo/tests/sys/vane/eyre.hoon
by dynamically generating the content-length headers for the expected results, based on their actual content.
Permanently fixes the test failure mentioned in #1441 (but not that issue itself).
> Ensure expected eyre test results always up-to-date

- pkg/arvo/sys/vane/clay.hoon
Looks like somehow the write queue in Clay on ~zod got stuck in a state where the cue has contents, but no write is active.  This make `|cancel` start the next write in the queue.
> Kick write queue on |cancel

- pkg/arvo/lib/stdio.hoon
- pkg/arvo/lib/tapp.hoon
- pkg/arvo/sur/tapp.hoon
Usage:
```
;<  =life  bind:m  ((scry ,life) %j /(scot %p our)/life/(scot %da now)/~zod)
~&  zod-life=life
...
```
Scry is currently disabled in async apps because we run them within `+mule`, and it's not immediately clear how to supply a scry function to `+mule` without introducing a type hole.  A `+scry` in lib/stdio is just about as good.  To implement this, we thought about sending a `%scry` schematic to ford, but ford currently only supports clay scrys.  We also thought about creating a special-purpose app to scry results, but this seemed like overkill, and it wasn't clear what ordering guarantees we would be relying on.
Since `lib/tapp` is the one that introduces the `+mule` calls, it seems that's the right place to complete the virtualization.  This adds special handling in …
> add +scry to lib/stdio

- pkg/interface/chat/src/js/components/lib/header-bar.js
- pkg/interface/publish/src/js/components/lib/header-bar.js
Upon @galenwp's request.
This PR distinctly does *not* include the compiled pkg/arvo code, in the hopes of establishing a brighter future. It can easily be added as a separate commit if need be.
> Loading spinner moved to left alignment

- pkg/arvo/app/publish.hoon
- pkg/arvo/sur/publish.hoon
This PR is to make it easier to migrate data between continuity eras with herb.
Export just bundles all relevant clay state into a single data structure and sends it to the subscriber,
import takes this bundle, saves all the files, and makes the relevant ford builds.
> Adds import and export arms to publish

- pkg/arvo/sys/hoon.hoon
Fixes #1405.
On master, if you run 
`=y |=  x=(list *)  |-  ?~  x  "derp"  i.x`
`(y ~[1 2])`
repeatedly in the dojo you'll get `[%dojo-lame %made]` approximately 50 % of the time. Unlike the issue I haven't encountered any difference with respect to printing out the function or not. The problem is that sometimes we try to print out a `cape` containing `[%bswt p=~[%yarn %noun]]` instead of the expected `[%bswt p=~[%noun %yarn]]`.
This is basically just commit 676aa77afdba87001c689717e3ffdce97e1017df, which was dropped from master at some point, git bisect doesn't return anything useful though.
> Sort clauses of $fork type pretty-printing

- pkg/urbit/configure
Simply bumps vere to v0.8.2.
This commit was made directly on the v0.8.2 release branch, but it *should* have been made on master and then been cherry-picked over.  Here we're just performing the reverse action to fix that up.
> vere: version bump (0.8.2)

- pkg/urbit/vere/pier.c
In debugging it's useful to use "priority" printfs, which just prepend `>` to the result to make them visually distinct.  This is especially useful when there is a large amount of output, as in complicated aqua tests.  This isn't used in production, I think the only place they're checked in is in tests.
This gives colors to priority printfs:
```
~&  >  'green'
~&  >>  'yellow'
~&  >>>  'red'
```
> Add colors for priority printfs

- bin/ivory.pill
- bin/solid.pill
- pkg/arvo/lib/ph/azimuth.hoon
- pkg/arvo/lib/ph/tests.hoon
- pkg/arvo/lib/ph/util.hoon
- pkg/arvo/lib/pill.hoon
- pkg/arvo/sur/aquarium.hoon
- pkg/arvo/sys/vane/jael.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/tests/sys/zuse/dawn.hoon
- pkg/urbit/vere/dawn.c
Fixes a bug in Jael that @belisarius222 uncovered while testing new Ames.  We supported the idea of "subscribe to updates about all ships" on the client side but not the server side.
> Store subscribers to all ships in Jael

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
You know how writing large files to Clay seems to take forever?  It's not your imagination, hoon.hoon takes 19 seconds on my machine. This PR reduces that by 93% to 1.3 seconds.
Turns out `+of-wain:format` used quadratic space.  It converts a list of lines into one big atom.  Its algorithm was more or less:
- set result = 0
- if no more lines, return result
- else, concatenate result and the next line, then recurse
Of course, each time it hits step 3 (once per line), it allocates a new big atom.  For hoon.hoon, that's 17000 allocations and writes, averaging 250KB each, for a total allocation/write of 3.4 GB.
Memory-wise, the solution is to do a single allocation and paste in all the lines at once.  Hoon doesn't let us access memory directly, but vere has a jet for `+can` which does this. …
> zuse: make of-wain:format use linear space (or "Make commits fast")

- bin/solid.pill
- pkg/arvo/app/aqua.hoon
- pkg/arvo/app/hood.hoon
- pkg/arvo/app/ph.hoon
- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/lib/pill.hoon
- pkg/arvo/sys/vane/dill.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/pier.c
A large portion of the boot process is just compiling apps.  In development, this is usually wasted time unless you're working on those specific apps.  This adds a `-l` flag, which starts the ship with just two apps: dojo and azimuth-tracker (the two you need to have a real ship).
On bare metal, this reduces boot time from 79 to 49 seconds (about a third faster).  The effect is even more pronounced on aqua, because you don't need to set up the C stuff.
Another possible improvement would be to whitelist a small set of files to be loaded into clay on boot.  Quite a bit of time is spent in clay on boot.
I was hoping this would be a small change, but it's a bit messier than I would have liked.  It's not clear to me whether the benefit is worth the complexity.  What do you guys think?
> dill, helm: add fast boot option with -l

- pkg/interface/chat/gulpfile.js
- pkg/interface/chat/package-lock.json
- pkg/interface/chat/package.json
- pkg/interface/clock/gulpfile.js
- pkg/interface/clock/package-lock.json
- pkg/interface/clock/package.json
- pkg/interface/launch/gulpfile.js
- pkg/interface/launch/package-lock.json
- pkg/interface/launch/package.json
- pkg/interface/publish/gulpfile.js
- pkg/interface/publish/package-lock.json
- pkg/interface/publish/package.json
- pkg/interface/weather/gulpfile.js
- pkg/interface/weather/package-lock.json
- pkg/interface/weather/package.json
Fixes #1659. `gulp.rename` copies files, leaving the original. For our minified files, this was navigated by not tracking the -min.js files in git. 
However, when deploying OTA, the -min.js files are still deployed to all ships. This PR adds the 'del' package, and a gulp task to clean up the -min files after renaming, for all current Landscape applications.
(Yes, I've tested it, and it works as specified. Adds 11ms to build time, though.)
> Interface: Add "clean 'renamed' files" gulp task

- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/pier.c
- pkg/urbit/vere/term.c
The terminal spinner, introduced in #651, was rendered on a separate thread and protected by a mutex. This was necessary before `v0.8.0`, as nock evaluation would block the main loop. With the new multiprocess architecture, that separate thread is unnecessary.
I suspect that my original re-integration of the spinner in the multi-process architecture was not quite right. There have been reports of process hangs, and deadlock on that mutex seems like a likely cause. To cancel the spinner, the main thread would need to acquire a lock on the mutex -- put another way, the spinner could block the main event loop. That's obviously not desirable. I think this implementation (a libuv timer reoccurring at some interval) is much simpler to reason about.
> rewrites the terminal spinner on the main loop

- bin/solid.pill
- pkg/arvo/sys/hoon.hoon
This check required the new type of +type to nest within the old type of
+type, which is wrong.  Specifically, this disallowed adding new runes
wihtout a staging procedure (which we didn't successfully complete).
Usually, you can add a rune to +hoon without going through the staging procedure that's required for changing the type of +type.  +hoon is referenced with +type, so technically you are changeing the type of +type, but since the old type nests within the new type it doesn't cause a problem.  This doesn't work anymore -- anything with a `~&` crashes with a `nest-fail`.
- In #1422, we "decapitated" all compiler jets -- all that remains in those jets is some aching logic.
- `!;` is a natural rune in the expansion of several runes, including `~&` and `!>`.  Specifically, `!;(*type 5)` …
> hoon: don't nest check in zpmc

- pkg/arvo/app/weather.hoon
We've had a very hot summer in Europe so when I saw 68º I thought it was completely normal. Then I looked at Darksky's API docs.
This adds automatic units based on location. At first I used string interpolation to create the URL but I think that concatenating the base url with the parameters using an n-ary weld looks more readable.
> weather: automatic units based of geo location

- pkg/arvo/app/publish.hoon
In Publish, users could get in a bad state if they made a post with valid udon, and subsequently edited to contain invalid udon. Furthermore, users subscribed to them would get in the same bad state.
This PR fixes the original bug, and users who are already in the broken state will be able to run a recovery command: `:publish %state-surgery`
which will also fix the downstream broken state of their subscribers.
> Publish broken post bugfix

- pkg/arvo/app/publish.hoon
When migrating notebooks to a new ship, Publish's `%serve` command currently makes builds for notes even if the publish-info file is missing. It now crashes the build if the file is missing, with a one-line `?>` asserting that the file is found in the list of paths associated with the collection, before continuing to import.
1. Make a notebook.
2. Copy its files from `/web/publish/[notebook-name]` (and `notebook-name.publish-info`) into another folder.
3. Make a new ship. Copy those files into `/web/publish` but delete the `publish-info` file.
4. `:publish &publish-action [%serve %notebook-name]`
> Publish: Add a check for publish-info when importing a notebook

- pkg/king/lib/Vere/Clay.hs
- pkg/king/lib/Vere/Http/Client.hs
- pkg/king/lib/Vere/Pier.hs
- pkg/king/lib/Vere/Serf.hs
- pkg/king/lib/Vere/Term.hs
- pkg/king/package.yaml
- This goes through everything I've previously done and makes sure it's all <80 cols and stylish. Sorry!
- Attaches serf stderr output to the terminal driver so that we get boot messages on startup.
- Actually implemented the UTF-8 handling in the terminal driver. You can now paste a ☃ or other emoji into the console.
- The atom putfile command should actually do something.
- Further haskell golfing.
> Further terminal fixes and cleanups

- pkg/king/app/Main.hs
- pkg/king/lib/Vere/Pier.hs
- pkg/king/lib/Vere/Serf.hs
- pkg/king/package.yaml
- stack.yaml
Also prints the name of the ship you're trying to boot, along with
whether its a fake or not. Also fixes a regression where we were
trying to acquire a lockfile before the pier directory was created.
> Makes a progress bar on booting a new ship.

- pkg/king/lib/Arvo/Event.hs
- pkg/king/lib/Vere/Pier.hs
- pkg/king/lib/Vere/Term.hs
This gets a terminal spinner to spin after a short delay like in
vere. This also fixes a bug in termRefreshLine which was screwing
up redisplay of the terminal spinner; it hadn't been translated
from C properly.
> Terminal spinner implementation in King Haskell.

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/tests/sys/zuse/html.hoon
de-xml:html now parses CDATA sections correctly, instead of failing to parse
> zuse: added CDATA support to de-xml:html

- pkg/king/app/CLI.hs
- pkg/king/app/Main.hs
- pkg/king/lib/Arvo/Event.hs
- pkg/king/lib/Vere/NounServ.hs
- pkg/king/lib/Vere/Pier.hs
- pkg/king/lib/Vere/Term.hs
- pkg/king/lib/Vere/Term/API.hs
- pkg/king/lib/Vere/Term/Demux.hs
- pkg/king/package.yaml
This branch implements external terminals in a very hacky way:
- Record all terminal events since start of KH process.
- When external terminals connect, dump all recorded events to external terminal.
In effect, this allows multiple client connections to *the same* terminal.
This is not ideal, obviously. I think this is a good idea as a short-term hack because:
- I need external terminal support in order to make the king a daemon.
- I need the king to be a daemon in order to support the client flow.
- Implementing external terminal support is hard.
- This approach bites off half the work needed to properly implement external terminals.
> Hacky External Terminals

- pkg/king/lib/Vere/Pier.hs
- pkg/king/lib/Vere/Term.hs
This makes canceling the persistance thread not rethrow an exception
which kills the process, and makes the terminal driver write one
final newline before giving control back to the terminal so the
bash prompt writes to its own line.
> Make king shutdown cleanly on a new line.

- pkg/urbit/include/noun/allocate.h
- pkg/urbit/include/noun/hashtable.h
- pkg/urbit/include/noun/jets.h
- pkg/urbit/include/noun/nock.h
- pkg/urbit/noun/hashtable.c
- pkg/urbit/noun/jets.c
- pkg/urbit/noun/manage.c
- pkg/urbit/noun/nock.c
This PR was motivated by problems encountered in #1741. In short: promoting values out of inner roads is complicated, and was made much more complicated by our use of hashtables. (This manifested in #1741 as an existential dependence on leaking references while unifying nouns.)
This PR phases transitions from inner to outer roads; first we promote them (and don't do anything else with them), then we do whatever we need to do with them. Specifically, there are no hashtable lookups or equality comparisons during the promotion phase (`u3a_take()` and friends). To do this, I added hashtable promotion (`u3h_take()` and parameterized `u3h_take_with()`) and merge (`u3h_uni()`). I also refactored the internals of the bytecode interpreter and jet dashboard program/registration/cache promotion, …
> u3: hashtable improvements, road promotion refactor

- bin/solid.pill
- pkg/arvo/app/ph.hoon
- pkg/arvo/lib/ph/util.hoon
- pkg/arvo/sys/vane/gall.hoon
fixes #1431
When we start talking to another ship, we subscribe to jael for breach notifications.  If they breach, then we:
- cancel outgoing subscriptions to that ship
- cancel incoming subscriptions from that ship
- cancel the jael subscription for that ship
- erase any memory of that ship
This is patterned after Clay's handling of breaches.  In particular, I cargo culted the pattern of saving the current rift of the foreign ship when we start the subscription to Jael to avoid reacting to spurious breach notifications from the past.  It's not cargo culting if I wrote the original, right?
The ph test reproduces the error, and with these changes it's fixed.  It's not obvious how to check for this lack of error, so for now I've just noted in a comment that the test is not expected to …
> gall: unsubscribe after breach

- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/lib/hood/helm.hoon
- pkg/arvo/lib/hood/kiln.hoon
I had previously removed Hall and Talk from the apps that are started up upon the ship starting. I have now updated this branch to remove Hall dependencies from Hood but Hall and Talk are still started up upon boot. This should be an acceptable change since Hood shouldn't depend on Hall anyway.
> hood: remove hall dependency.

- pkg/interface/weather/tile/tile.js
The `precipProbability` value ranges from 0 to 1, so to display percentages we need to scale it up.
Currently, it's just displaying 0-1%:
> Display actual precipitation probability percentages

- bin/solid.pill
- pkg/arvo/sys/arvo.hoon
- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/sys/vane/behn.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/vane/dill.hoon
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/vane/ford.hoon
- pkg/arvo/sys/vane/gall.hoon
- pkg/arvo/sys/vane/iris.hoon
- pkg/arvo/sys/vane/jael.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/urbit/include/c/motes.h
- pkg/urbit/include/noun/allocate.h
- pkg/urbit/noun/allocate.c
- pkg/urbit/noun/manage.c
- pkg/urbit/noun/vortex.c
- pkg/urbit/vere/reck.c
- pkg/urbit/worker/main.c
... and handling in both vere and arvo.
In vere, we simply clear all persistent caches, at either threshold. More precise cache management remains a goal. The current thresholds are roughly `75%` and `90%` of linear home-road use -- they do not take free-lists into account. Threshold detection is stateless, so it's possible that some resource usage patterns could result in frequent crossing/recrossing of a threshold.
In Arvo, we "spam" a `%trim` notification to every vane. That notification includes a *priority* `@ud` -- `0` is maximally urgent, `1` is less so. This scheme will let us simply add lower priority levels in the future as needed.
The vane `%trim` task handlers are currently all stubs. Top reclamation targets include the build cache in `%ford`, the compiler caches in `%gall` …
> u3: adds memory-pressure threshold detection

- pkg/urbit/include/noun/zave.h
- pkg/urbit/jets/f/ut_crop.c
- pkg/urbit/jets/f/ut_fish.c
- pkg/urbit/jets/f/ut_fond.c
- pkg/urbit/jets/f/ut_fuse.c
- pkg/urbit/jets/f/ut_mint.c
- pkg/urbit/jets/f/ut_mull.c
- pkg/urbit/jets/f/ut_nest.c
- pkg/urbit/jets/f/ut_peek.c
- pkg/urbit/jets/f/ut_play.c
- pkg/urbit/jets/f/ut_rest.c
- pkg/urbit/noun/nock.c
- pkg/urbit/noun/zave.c
Specifically, this change avoids uncounted references in the "decapitated" memoizing compiler jet stubs.
These issues have been latent in the code for a long time, but they were "activated" by the unifying-equality changes in #1741, and surfaced in #1757.
> u3: refactors memoization patterns for safer reference-counting

- bin/solid.pill
- pkg/arvo/sys/vane/gall.hoon
%gall currently prints
```
[%gall-booting <app> p=<ship> q=<desk>]
```
whenever it receives a %conf (i.e., when it boots an app).  This turns up in many of the places the old, less-informative `%mo-not-running` printf did, but it's of similarly little use, and mainly serves to create redundant line noise.  This (trivial) PR just removes it.
> gall: remove %gall-booting printf

- pkg/arvo/app/group-hook.hoon
- pkg/arvo/app/group-store.hoon
- pkg/arvo/app/permission-group-hook.hoon
- pkg/arvo/app/permission-store.hoon
- pkg/arvo/lib/group-json.hoon
- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/lib/permission-json.hoon
- pkg/arvo/mar/group-hook-action.hoon
- pkg/arvo/mar/group/action.hoon
- pkg/arvo/mar/group/initial.hoon
- pkg/arvo/mar/group/update.hoon
- pkg/arvo/mar/permission-group-hook-action.hoon
- pkg/arvo/mar/permission/action.hoon
- pkg/arvo/mar/permission/initial.hoon
- pkg/arvo/mar/permission/update.hoon
- pkg/arvo/sur/group-hook.hoon
- pkg/arvo/sur/group-store.hoon
- pkg/arvo/sur/permission-group-hook.hoon
- pkg/arvo/sur/permission-store.hoon
Added working and tested stores, hooks, and JSON marks. These have TODOs in them to no-op in a few cases where they don't currently (they send an update even though they did nothing), but apart from that, these are done.
Also, once some version of #1757 goes in, the group-json and permission-json can be refactored to use the functions in standard lib instead of using their own implementations. In the meantime, putting this out for review.
> Added store, hook, and JSON marks for both Groups and Permissions

- bin/solid.pill
- pkg/arvo/sys/arvo.hoon
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/vane/ford.hoon
- pkg/arvo/sys/vane/gall.hoon
Following on #1773, this PR fills out (some of) the `%trim` memory-pressure notification handlers.
- in arvo proper, we clear compiler caches at high priority
- in %eyre, we close all inactive channels
- in %ford, we clear half of the cache(s) at low priority, all at high
- in %gall, we clear compiler caches
Some potential improvements are noted in comments; for instance, we may want to cancel active %ford builds or close active %eyre channels at high priority.
%clay remains a good candidate for further improvements, as it could discard or tombstone foreign desks. But I think reclaiming from its blob store would require a GC-style pass over the entire state.
/cc @philipcmonk, @eglaysher
> arvo: trim vane in response to memory pressure

- nix/pkgs/default.nix
- nix/pkgs/urbit/image.nix
- sh/image
Adds `urbit-image` and `urbit-image-debug` to the top-level attributes exposed via `default.nix`. These respectively cook urbit and the debug variant into Docker-compatible images which can be loaded into the Docker daemon or alternative runtime. The images are tagged using the Nix store hash and time-stamped with the Unix epoch (1970-01-01) for reproducibility.
The additional script `sh/image` encodes the build and Docker-related load steps for convenience.
Following a successful build/load, you can boot the urbit image using the Nix store hash as the image tag and passing any urbit-related flags:
```
docker run --tty urbit:xd5q0b2d4cyq2h7mh6q3f01arfai37i9 -F zod zod   
```
Future work will include baking the correct pill into the image and pushing images to hub.docker.com in conjunction …
> Add Nix Attributes to Build Container Images

- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/ames.c
Removes the `-f` (Fuzz testing) flag. My assumption is that this behavior is neither used nor implemented in a sufficiently useful manner, please correct me + add context if that is not the case.
> Remove Fuzz Testing Option

- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
Snapshots were removed in #1436, but these arguments were left in.
/cc @philipcmonk
> removes obsolete cli args for eth snapshots (-C and -E)

- nix/pkgs/default.nix
- nix/pkgs/urbit/default.nix
- nix/pkgs/urbit/image.nix
- sh/image
Bakes the `bin/solid.pill` into `urbit` and `urbit-debug` container images. This ensures that any image built within the current tree is (or should be) in a working state when pushed to a remote repository.
Additionally the `urbit-debug` image now logs the coredump which is useful primarly for our hosting environment. Locally the `/tmp` mount can be inspected to extract the coredump if desired.
> Bake Solid Pill Into Container Images

- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/term.c
Currently `-d` (daemon mode) disables terminal/tty assumptions and calls `fork()` to background the daemon process. In the hosting environment the former is required/desirable as no terminal is attached/present for containerized ships - but the parent process is required to stay in the foreground, as PID 1 within the container.
This PR toggles the terminal guards under `term.c` using the new `-t` option, and keeps the existing `-d` option to enable the call to `fork()`, with the latter implying the former. That is:
*  `-d` calls `fork()` and disables terminal assumptions.
*  `-t` only disables terminal assumptions.
An additional guard on `-t` has been placed around the terminal column/row calculation in `term.c:u3_term_get_blew`, which is in response to a `SIGABRT` that occurs when no …
> Add Option to Disable Terminal/TTY Assumptions

- bin/solid.pill
- pkg/arvo/sys/vane/behn.hoon
Per @philipcmonk's suggestion in #1481, as discussed in #1790. This change *does not* handle the error of a failing %drip, as there's no way to route that error notification right now. But printing it will at least let us debug...
> behn: print error message if %drip event fails

- sh/image
Due to various vere-related terminal fixes and improvements - there's a lot of branch noise involved in producing test and debug-enabled images for the hosting environment. This PR adds simple git metadata to the image tag so that the provenance of these images can be traced.
> build: Git Tagged Container Images

- pkg/urbit/vere/pier.c
The emission of escape codes when printing colored priorities in `u3_pier_tank` causes log noise when no terminal is attached. This PR adds a naive terminal check around the printf's that set color start/reset escape codes.
> vere: Add Terminal Check to Tank Dump Colored Priorities

- sh/image
Changes the image name to match the binary name.
```
$ sh/image
Building urbit-image...
Loading /nix/store/p4mfv2f0ab7vzq5ijyhijsix5071iq45-docker-image-urbit.tar.gz into Docker...
Re-tagging with current git branch:container-image-tags and SHA:55e6533e
urbit:container-image-tags-55e6533e
```
With the image names being `urbit` and `urbit-debug` respectively, rather than the name of the invoked Nix attribute, which was `urbit-image` or `urbit-image-debug` prior to this change.
> build: Trim Container Image Tags

- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/noun/events.c
- pkg/urbit/noun/manage.c
Specifically, this PR
- removes `-b` ("batch create") and `-V` ("replay without kernel resets")
- implements `-x` ("exit after boot")
- and adds some comments (hopefully) clarifying unimplemented-but-desirable `-a` ("abort aggressively") and incomplete `-d` ("dry-run")
> vere: adds some minor cleanup of cli args

- bin/solid.pill
- pkg/arvo/sys/hoon.hoon
- pkg/arvo/tests/sys/hoon/differ.hoon
- pkg/arvo/tests/sys/hoon/map.hoon
- pkg/arvo/tests/sys/hoon/qeu.hoon
- pkg/arvo/tests/sys/hoon/set.hoon
This submits the work for the following bounty: https://grants.urbit.org/bounties/1322185260-unit-tests-for-pure-algorithms
TL;DR: It provides four test files `qeu.hoon`, `map.hoon`, `set.hoon` and `differ.hoon` with unit tests for all arms under `+to`, `+by`, `+in` and `+differ`.
@jtobin I hope I haven't messed up the commit history too much but following the "Contribution hygiene" guidelines, but I thought that it would make sense to see what files were added, following the definition of "atomic" commits.
There are some things with this PR (the fact that some tests fail) that I would like to explain here (there are comments in the testing files with longer explanations). 
The gist of it is that I believe that I found some issues with some of the arms. I made the mistake in the past of …
> tests: unit tests for pure algorithms

- pkg/arvo/app/claz.hoon
- pkg/arvo/gen/hood/claz-invites.hoon
- pkg/arvo/lib/keygen.hoon
For ship distribution purposes, we want to be able to send out large amounts of planet invites (using Delegated Sending). This PR implements logic in Claz for generating those transactions.
It takes a `.txt` file as input, with every line being `~ship,~ticket,0xaddress`. To generate these for some planets under some star, a generator is provided.  
`|claz-invites ~marzod 1 10 %/invites/txt` does this for ~marzod's first through tenth child.
That file can be taken out of the Urbit and used to, for example, print out invite wallets.
Those wallets won't be useful until you've sent the matching invite transactions.  
`:claz [%generate %/out/eth-txs %ropsten 0xsender %invites ~palfun-foslup %/invites/txt]` generates transactions for sending those using ~palfun-foslup as the invite-sender. …
> Claz: batch invites

- pkg/arvo/app/claz.hoon
- pkg/arvo/gen/hood/claz-invites.hoon
Missed in #1809, but bad enough to be confusing. This fixes incorrect comments, and adds what was still missing.
> Claz: Correct & complete comments

- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
Addresses #1811.
I can reproduce the issue by shutting down a pier before disconnecting from landscape and then restarting it. This results in `%invalid-outstanding-connection` every 20 seconds since the heartbeat move is never cancelled.
This is due to me being sloppy and only canceling heartbeat moves on `%disconnect`. Now we cancel heartbeats in `on-cancel-request` (fixing the above case, this is called on %born) and in `on-channel-timeout`. Let me know if there are other cases that I have missed.
This might fix #1812 as well, not sure of how to reproduce that one, though.
I'm still having trouble with nix (as mentioned [here](https://github.com/urbit/urbit/pull/1687#issuecomment-538802626))  so I can't run tests nor create pills locally. I suspect some tests will fail here, so I'll …
> eyre: fix missing cancel-heartbeat-move cases

- pkg/arvo/app/chat-cli.hoon
This cleans up a number of `TODO`s and issues around glyph handling that had been weighing on me. See commit messages.
I'd love to print the glyph translations (if any) on-`%target`, but doing that cleanly is non-trivial right now and outside of scope here. For what it's worth, the "I _need_ to double-bind glyphs case should be much less common in chat-cli, due to more available glyphs.
> Chat-cli: glyph fixes

- pkg/arvo/sys/vane/ames.hoon
This fixes a bug whereby %behn timers were being set on an empty duct, and the subsequent %wake was being routed to unix as an effect. These are safe to drop, as any subsequent messages sent or packets received will reset the timer, which will pick up all "pending" packets. (There's also a fallback %ames timer in vere, but it's presence doesn't change this analysis.)
> ames: skip timers if unix duct is unset

- pkg/arvo/app/claz.hoon
09cb5f2 added a %send-point call, which is meant to target the delegated sending
contract. For %invites batches, this was the case. Handling of %single, however,
still sent all calls to the ecliptic contract.
This looks at the call tag to determine the target contract.
Thanks @philipcmonk for catching this!
> claz: %single %send-point to correct contract

- nix/ops/brass/default.nix
- nix/ops/default.nix
- nix/ops/fakeship/default.nix
- nix/ops/image/default.nix
- nix/ops/ivory/default.nix
- nix/ops/solid/default.nix
- nix/ops/test/default.nix
- nix/pkgs/default.nix
- nix/pkgs/urbit/default.nix
- sh/image
Rather than reconstructing the `urbitExe` path/argument string using a debug conditional in every ops expression, attaches the following information to the `urbit` derivation's `.meta` attribute:
* `urbit.meta.debug` - whether this derivation is a debug build.
* `urbit.meta.bin` - the binary path/name, such as `/nix/store/urbit/bin/urbit` or `/nix/store/urbit/bin/urbit-debug`.
* `urbit.meta.flags` - any flags this particular build should be invoked with, such as `-g`.
* `urbit.meta.exe` - the combination of `urbit.meta.bin` and `urbit.meta.flags`.
The `nix/pkgs/image` expression has also been moved into `nix/ops` to take advantage of these changes as it also makes use of this debug metadata, as well as an update to the `sh/image` build script.
> build: urbit derivation debug metadata

- pkg/arvo/app/chat-store.hoon
Messages were not being stored properly in the chat-store. I did not realize that all subject modifications in =: were all in parallel. Changed to =. so that the subject modifications happen correctly (in sequence) to store messages.
> chat: changed a =: to a =. to fix message storage bug

- bin/solid.pill
- pkg/arvo/sys/vane/jael.hoon
New ships on the network are coming up synced to their galaxy instead of their star because I was grabbing their furthest sponsor instead of their most immediate.  This fixes that.
Consider this another vote in favor of updating the released pill instead of relying on all future updates to be OTA.
> jael: retrieve first sponsor instead of last

- pkg/arvo/app/claz.hoon
Expands on #1809 by implementing checks that ensure the requested transactions are actually usable. This includes making sure the given planets are usable, and that the inviter has enough in their pools.
Also makes claz print helpful information on-fail.
With this, adding new sanity checks should be fairly straightforward. (Though maybe claz needs a more aggressive refactoring first...)
> Claz: automated invite sanity checks

- bin/solid.pill
- pkg/arvo/sys/arvo.hoon
fixes #1835 (confirmed through local testing).
> arvo: improves move type specialization (by spec'ing incrementally)

- pkg/arvo/app/publish.hoon
Trying to mimic it misled me for a quick second, until I realized you really want `[%disconnect wire binding:eyre]` here. Since publish isn't using it anyway, might as well take it out.
> publish: remove unused %disconnect card

- nix/pkgs/urbit/default.nix
We've been stymied by there absence a few times, no reason not to always include them at this stage.
> build: always include debug symbols

- pkg/arvo/sys/vane/ames.hoon
Sometimes Jael sends an update about a ship that has no keys, eg if you try to talk to a ship we don't believe exists yet.  In this ames, was crashing, which was killing the azimuth-tracker http receive event, so ~zod wasn't getting up to date.
This just turns that into a no-op.
> ames: don't crash on jael update

- pkg/urbit/worker/main.c
This PR restores the old heuristic of purging vere caches every 1k events. We don't make sufficiently efficient use of free space to just depend on the memory pressure thresholds.
Additionally, this updates the `|mass` handler to also print the size of the free lists, and adds static memory measurement on startup, for cases where we can't evaluate `|mass` (currently run on every startup where < 1/2 of the loom is contiguously free).
> updates vere memory management heuristics and debug info

- nix/ops/image/default.nix
- nix/pkgs/urbit/default.nix
- sh/image
* Removes the baked in coredump inspection and wrapper scripts in favour of using `FROM <image>` downstream.
* Symlinks the binary wrapper to `/bin/urbit` ands it to the `PATH` - discoverable by downstream configuration.
* Symlinks the baked in pill to `/share/urbit.pill` - discoverable by downstream configuration.
* Changes the urbit expressions metadata to retain flags (such as `-g`) as a list.
* Removes the git tagging of images and relies on intentional re-tagging by the user, to avoid constant overlap when repeatedly building images for a specific SHA.
> build: simplify image build interface

- pkg/urbit/vere/term.c
The condition, added in #1793 (as part of `-t`, which disables features that require a tty), was precisely backwards. I missed it on review.
> vere: restore terminal dimensions measurement

- bin/solid.pill
- pkg/arvo/sys/vane/gall.hoon
fc7901d2 refactored much of +ap-peek, but introduced a bug in the process.  The relevant diff from that commit is as follows:
```
=/  slammed
-        =/  =path  [ren tyl]
-        =/  =vase  !>((slag p.u.cug path))
-        (ap-slam q.u.cug p.arm vase)
+        =/  index  p.u.maybe-arm
+        =/  term  q.u.maybe-arm
+        =/  =vase
+          =/  =path  [term tyl]
+          =/  raw  (slag index path)
+          !>  raw
+        (ap-slam term p.arm vase)
```
Note that [ren tyl] was replaced with [term tyl], where 'term' and 'ren' are not equal.  This commit merely rights that wrong.
(/cc @philipcmonk as this is probably still relevant on your static gall branch)
> gall: fix bug in +ap-peek

- pkg/urbit/noun/allocate.c
- pkg/urbit/noun/events.c
And ensures that they're printed, especially when the errors in question are fatal (`u3l_log()` is especially unsuitable for these, as it may send over a pipe, and the message may never be delivered).
> u3: cleans up error messages

- pkg/arvo/app/publish.hoon
Fix one is for https://github.com/urbit/urbit/issues/1834
There previously was no logic set the permissions correctly in the %serve and +import cases, resulting in people not being able to subscribe to blogs that have been imported in this manner.
Fix two is for https://github.com/urbit/urbit/issues/1863
The old gall 20 limit ~~bug~~ feature. We now automatically resubscribe when we receive a quit. And in the cases of the app intentionally sending a quit, we have converted that action to a poke, asking the other end nicely to unsubscribe from us.
> Publish: 2 seperate fixes

- pkg/arvo/app/claz.hoon
Does what it says on the can. Useful so it doesn't trip over trailing newlines, which many editors automagically add.
> claz: ignore empty lines in invites file

- bin/solid.pill
- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/vane/gall.hoon
- pkg/arvo/sys/vane/jael.hoon
- pkg/arvo/sys/zuse.hoon
Until now, clients of Jael have had to store the first-seen rift if they
want to reliably detect breaches.  Otherwise, they would get a false
positive if they heard an old message about a breach (eg if you kick
azimuth-tracker).  Clay and Gall did this correctly, but Ames did not.
Jael already maintains this state, so I added a notification to the
existing subscription that happens whenever it notices a breach (a diff
or full where the new rift is greater than the old one).
Because this is an issue on the live network, I wrote state adapters
for Gall and Clay.  The Gall one just removes the rift from our state,
but the Clay one is much more involved because we have to upgrade
instances of the clad monad that are possibly in progress.
Specifically, since more input is possible than before, …
> jael: provide edge-triggered breach notification

- Makefile
- nix/ops/default.nix
- nix/pkgs/arvo-ropsten/builder.sh
- nix/pkgs/arvo-ropsten/default.nix
- nix/pkgs/default.nix
- pkg/urbit/daemon/main.c
- sh/create-ropsten-pills
This PR makes a number of changes around pill management.  See the individual commit descriptions for more details, but the TLDR is:
* has `/sh/release` spit out a brass pill artifact as `urbit-vx.y.z.pill`
* changes the pill format in the vere bootstrap URI from `urbit-$URBIT_VERSION.pill` to `urbit-v$URBIT_VERSION.pill`
* adds a Nix derivation for Arvo specialised to Ropsten (i.e. a testnet), as well as derivations for brass & ivory testnet pills
* has `sh/release` spit out testnet pills as well
This automates a lot of mundane tasks that are currently required when one sets up a testnet.
> Dr. Tobin is prescribing you more pills

- pkg/arvo/app/chat-hook.hoon
No longer overwrite messages' timestamp on-receive, instead keeping whatever
timestamp was set by the sender.
This behavior matches that of the late Hall.
> chat-hook: use sender's timestamp

- pkg/arvo/app/acme.hoon
- pkg/arvo/app/dns.hoon
- pkg/arvo/gen/dns/auto.hoon
- pkg/arvo/lib/stdio.hoon
- pkg/arvo/sur/tapp.hoon
- pkg/arvo/tests/app/acme.hoon
These apps used `:hall` as their notification channel, but `:hall` is deprecated and no longer running by default. This PR updates the apps (and lib/tapp components) to support and use `%flog` output cards for all notifications.
> fixes :acme and :dns notifications

- pkg/arvo/app/chat-cli.hoon
The link currently used in chat-cli resolves with a 301 to the proper page on urbit.org for messaging usage instructions, but not actually the 'messaging' section of that page. 
This commit provides a more direct link to the exact instructions.
> chat-cli: Update ;help link

- nix/pkgs/arvo/default.nix
0bdced981e4 introduced the 'arvo-ropsten' derivation.  Attempting to install both 'arvo' and 'arvo-ropsten' via nix-env will result in a priority error; this assigns a higher priority to 'arvo' to resolve the
conflict.
Fixes #1912.
> build: give arvo a high priority

- pkg/arvo/sys/vane/gall.hoon
This fixes the %gall crashes plaguing the network (reported in #1911), but fixing the virtualization of agent compilation. Instead of un-virtualized crashes in %gall, agent compilation failure will now (again) be caught (and reported as negative acknowledgements, where appropriate).
/cc @philipcmonk
> gall: fix virtualization of agent compilation

- bin/solid.pill
- pkg/arvo/app/pool-group-hook.hoon
- pkg/arvo/lib/ethio.hoon
- pkg/arvo/sys/zuse.hoon
Depends/builds on #1895. Targets that branch since that hasn't been merged into master yet.
Implements `/app/pool-group-hook` which, if you were invited by someone, creates and maintains an `/invite-peers` group that contains all ships invited by the same person as you. In other words, your siblings in the invite tree.
(CI failure because muh pills I think. cc @jtobin)
> Pool group hook

- bin/solid.pill
- pkg/arvo/app/goad.hoon
- pkg/arvo/app/hood.hoon
- pkg/arvo/gen/hood/goad-gall.hoon
- pkg/arvo/lib/hood/kiln.hoon
- pkg/arvo/sys/vane/dill.hoon
- pkg/arvo/sys/vane/gall.hoon
- pkg/arvo/sys/zuse.hoon
This PR follows #1914 in our efforts to fix the livenet. Specifically, it's a way to work around broken live builds in %ford, as reported in #1898.
%ford builds can get stuck if %ford crashes when processing the response from %clay -- the response is intermediated through %behn via a %drip task, which provides isolation but not (yet) error reporting. When this happens, %ford thinks it's waiting for %clay, and %clay thinks it's already responded. Both are technically correct.
To work around this state for %gall agents, we add a `%goad` task to %gall, which can cause it to goad %ford into restarting the build. The task can apply to one specific agent, or all that are running. %gall will cancel the current live build (as it may be stuck) and start a new one. Alternately, we can set `force` …
> gall: adds %goad to force agent rebuilds

- pkg/urbit/vere/pier.c
Without the flush, the style bleeds onto the spinning cursor prompt line, if present.
> vere: flushes slog output to ensure style isolation

- bin/solid.pill
- pkg/arvo/sys/vane/jael.hoon
We were updating our state and then using that when checking if the rift
had incremented.  This would never be true, since we'd already set the
new state.
Fixes #1852 again.
This should be sent out OTA.
> jael: don't update state until you've tested for breach

- sh/create-ropsten-pills
If we're not on a branch, e.g. if we've checked out an arbitrary revision, then 'git branch --show-current' sensibly won't give us any output, and thus the pills produced by sh/create-ropsten-pills will be misnamed.
Consuming HEAD with git-rev-parse has the same effect here, and should work in all cases of interest.
> build: use HEAD in sh/create-ropsten-pills

- bin/solid.pill
- pkg/arvo/sys/hoon.hoon
This extends `gol` "backward-inference" typechecking to thread through cores.  Recall that `gol` is used exclusively for receiving more specific error messages; these changes should have no effect on programs which already compile successfully.
Before, this would type-fail on the second `|%`.
```
!:
^+  ^?
|%
++  foo  *@ud
--
|%
++  foo
?:  =(1 1)
2
%foo
--
```
With these changes, it gives a mint-nice at `%foo`.  It will also give you explicit errors if you have the wrong number/names of arms, including which arms it expects.
This is becoming much more important with static gall, since it's the first time we've used core subtyping so extensively and in userspace.
> hoon: Extend gol check through cores

- pkg/urbit/noun/manage.c
When running urbit on a machine without enough swap space, the message was
see urbit.org/docs/getting-started/installing-urbit/#swapfor adding swap space
So I fixed the URL and added a space before "for"
This PR supercedes #1926 and hopefully fits the conventions better.
> vere: fix url explaining how to add swap space

- bin/solid.pill
- pkg/arvo/sys/vane/jael.hoon
For some reason Jael subscriptions aren't starting properly for many
people.  Until we can get to the bottom of it, this sets everyone to
start listening directly to the chain.
> jael: only listen to azimuth-tracker on boot

- pkg/arvo/app/chat-cli.hoon
This augments permission management with invite sending, when setting "positive"
permissions. This matches talk's behavior.
Also implements `+full:tr`, which renders as `~ship/path`, even for local targets.
@loganallenc This does more or less what the chat-js does, please confirm this is all sane. We generate the UID from chat-in-question and target, to avoid duplicate invites piling up if they're re-sent but neither accepted nor deleted.
> chat-cli: send invites on-;invite

- nix/ops/image/default.nix
Seems there was an unused `entrypoint` binding lying around from the days when `debug` switched between invoking the binary directly and using a custom `entrypoint.sh`.
> build: remove unused let binding from image expression

- bin/solid.pill
- pkg/arvo/sys/vane/jael.hoon
I have no idea why this sort of error seems to show up in Jael and never anywhere else.
There may be other bugs, but this one on its own could explain 90% of the key-related issues we've been seeing.  This explains why people have been booting into having nobody's key state except their sponsorship chain (I moved the state update to the base case of a recursion that didn't recurse).  It also explains why updates from other ships don't work well (same, plus it only propogated the first thing in the list).  The bug has been there since new jael was released, but it was made worse by #1925.
This is a lesson to me to build more pH tests and run them when I fix bugs like this.  I discovered this only by trying to get existing pH tests to work in static gall, but I think it would have been …
> jael: process all ships in %full update

- .gitattributes
(I just happened to come across this technique while investigating the mechanics of smudge/clean for LFS-tracked files; it's worth adding.)
The 'index.js', 'tile.js', and 'index.css' files included in several Arvo apps are compiled, minified JS or CSS.  While they are technically text, they are not usefully diffable.  This PR designates such files as 'binary' in .gitattributes, which prevents git from attempting to create diffs for them in 'git log' and 'git show'.
Before:
```
$ git log -p -- pkg/arvo/app/chat
commit e06acb87bec18c8a7fafb4d96d13bfa533d06e2e
Author: Logan Allen <loganallc@gmail.com>
Date:   Thu Oct 24 14:31:40 2019 -0700
chat-ui: fix image previews from url types
diff --git a/pkg/arvo/app/chat/js/index.js b/pkg/arvo/app/chat/js/index.js
index c06d0732f..faf75ad00 100644 …
```
> apps: designate compiled js/css files as binary

- bin/solid.pill
- nix/ops/default.nix
- nix/pkgs/arvo-ropsten/builder.sh
- pkg/arvo/sys/zuse.hoon
Returns the target %zuse contract configuration to mainnet, and also tweaks the 'arvo-ropsten' build to use %alef instead of %ames.
@belisarius222 I have some existing scripting for handling testnets such that one doesn't need to hard-code any testnet config in git.  It's desirable to patch things here so I can simply reuse that stuff.
> zuse, build: remove default testnet config

- pkg/arvo/gen/publish/subscribe.hoon
As per @joemfb's suggestion: `:publish|subscribe ~palfun-foslup %urbit-only-exclusive-tweets`.
> publish: add subscribe generator

- bin/solid.pill
- pkg/arvo/sys/hoon.hoon
Immediately useful for implemeting json `@rd` parsing, which is basically
`++royl-rd` minus pfix sig. The increased separation also allows for running
stuff like `(rash '3.22e-47' royl-rn:so)` from the dojo.
Not sure who should look at this, ping @jtobin.
> hoon: refactor royl float parsers to separate arms

- pkg/arvo/app/chat-cli.hoon
- pkg/arvo/app/chat-hook.hoon
- pkg/arvo/app/chat-store.hoon
- pkg/arvo/app/chat-view.hoon
- pkg/arvo/app/invite-view.hoon
- pkg/arvo/app/permission-hook.hoon
- pkg/arvo/app/permission-store.hoon
- pkg/arvo/lib/chat-json.hoon
- pkg/arvo/sur/chat-store.hoon
Chat applications have been converted to static gall style and have been integration tested.
Notably, chat-hook now has a %backlog path for subscribing to messages from the backlog and a %mailbox path for subscribing to ongoing updates.
I may have uncovered a bug with removing wires after negative %watch-acks. Everything else works great and has been integration tested with the chat front-end.
> Chat functionality: integration tests complete

- pkg/arvo/app/azimuth-tracker.hoon
- pkg/arvo/app/eth-watcher.hoon
- pkg/arvo/lib/ethio.hoon
- pkg/arvo/sur/eth-watcher.hoon
- pkg/arvo/ted/eth-watcher.hoon
Put these in while working on porting userspace Ethereum tools to static gall. Figured it might be nice to get these into the release candidate if possible.
- Add support for batch requests to `/lib/ethio`. If any request in the batch fails, the entire batch is considered a lost cause.
- Add support for custom refresh rates to `/app/eth-watcher`. Useful for low-priority watchdogs, or cases where you need a long timeout time to deal with big requests/responses.
> eth: two enhancements

- pkg/urbit/vere/behn.c
I've observed two cases of ~marzod on the testnet hanging by not processing its timers.  In each case, running `-time ~s1` gets it going again, which suggests that for some reason the timer isn't getting reset correctly.
I've eliminated every deterministic case that I can tell where ames could be causing this, but it's always possible for this to happen if the error case of `%wake` crashes non-deterministically.  Since nondeterministic errors could happen at any time, we must handle this case.
This resets our timer to 10 minutes every time a timer fires, instead of clearing it.  This means if we don't hear a `%doze` that explicitly tells us to set or cancel our timer, we'll send a `%wake` after 10 minutes of timer inactivity.  Behn.hoon is already required to no-op on spurious timer …
> behn.c: backstop timer

- pkg/arvo/app/chat-cli.hoon
We were calling it directly, rather than through the (initialized) tc core,
causing the bowl in its context to be the *bowl, resulting in [~zod /] audience.
As briefly discussed with @philipcmonk.
> chat-cli: our-self with bowl set

- pkg/arvo/sys/vane/ames.hoon
Don't crash on a %public-keys response from Jael that includes a sponsor change but no keys. Instead, ignore that update. When we need the sponsor later, scry the up-to-date sponsor from Jael.
> ames: scry for sponsor and don't crash on jael response

- bin/solid.pill
- pkg/arvo/sys/vane/ames.hoon
This is why basically all packets are going through the galaxies right now.  Most of the time, the flow right now is:
- talking to ~dopzod but don't know where it is, so ask ~zod to forward, which it does
- ~dopzod responds both directly (on the origin lane) and through ~zod
- (if NAT, the direct response doesn't get back, but the one through  ~zod does.  Then you respond directly to ~dopzod because their lane piggybacked on the response.  ~dopzod responds both directly and through ~zod, and the story picks up the same as if you weren't behind a NAT)
- now you have a direct lane to ~dopzod, so all is well.
- now the duplicate response from ~dopzod through ~zod comes in (takes a little longer because it's bouncing off ~zod), resetting your lane to "provisional"
- since your lane is …
> ames: don't overwrite lane if already direct

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
Like #1982 but better.
This parser is not cached with `~+`, if that matters let me know.
@jtobin
> zuse: implement json number to @rd parsing

- pkg/arvo/lib/hood/drum.hoon
In some circumstances, we seem to boot to chat-cli instead of dojo, since we were sorting them alphabetically (cf talk came after dojo).  This sorts with `%dojo` always in front.
We also want to start acme on startup.  This won't apply to ships that have already booted, but they can just `|start %acme` if they need it.
> drum: boot to dojo and start acme

- nix/deps/ivory-header/builder.sh
- pkg/urbit/include/c/portable.h
- pkg/urbit/noun/manage.c
And removes an unnecessary use of `cat` in the ivory-header build. Fixes #2026
/cc @dpc
> u3: cross-platform fix for setting max open files

- nix/pkgs/urbit/release.nix
I meant to do this in #1848. We periodically need these.
> nix: enables debug symbols in release builds

- pkg/arvo/app/chat-store.hoon
Sending a `%code` letter without output would cause its code to be evaluated on
the recipients' ships. While that shouldn't naturally occur post-#2009, and
evaluation of `%code` letters remains virtualized, it's still remote code
execution, and worth fixing as such.
> chat-store: only evaluate our own %code

- pkg/arvo/app/group-hook.hoon
- pkg/arvo/app/permission-group-hook.hoon
Permission group hook wasn't properly mirroring group contents to permission sets in cases where a group was being reused across multiple permission sets. We found a couple of underlying issues associated with this, some that were present before the breach, and some that were introduced by the breach. We fixed them. Thanks!
> permission-group-hook: fixed permission associate flow

- nix/pkgs/urbit/release.nix
Well, this is embarrassing -- the third time's the charm ... I've tested this on MacOs; function names are present in the static binaries, line numbers are not. 
See #2029 and #1848
> nix: actually enables debug symbols in release builds

- pkg/arvo/ted/dns/address.hoon
!! crashes the thread, so dojo prints a stack trace.  An explicit
failure lets you give a custom error message.
Pairs well with #2022 and #2035 to give clean error messages.  OTA-able.
> dns: give quieter errors

- pkg/arvo/lib/hood/drum.hoon
Tangs were being printed in reverse order because they weren't updated after I removed the double-reversing action of hood to bring it in conformance with accepted standards.
OTA-able
> drum: print tangs in order

- pkg/arvo/app/azimuth-tracker.hoon
- pkg/arvo/app/spider.hoon
- pkg/arvo/lib/ethio.hoon
This is a fix for those transient loud errors where the node is giving `~` in the response to the block number request.  This parses without crashing, retrying if the parse fails.
This also silences spider's crash printing.  That's the responsibility of whoever started the thread -- maybe you expected it to crash.  This is why that stack trace was printing twice.
This is fine to OTA
> eth-watcher: be quieter about parse errors

- pkg/urbit/vere/newt.c
We've periodically seen malloc failures (ie, returning a null pointer) in `newt.c`, our IPC implementation ("memory lost" assertion failures). I've suspected that they were caused by attempts to allocate zero bytes. We were not properly following libuv's read callback conventions for EAGAIN/EWOULDBLOCK, which would've had that result.
The message parsing and assembly was in one large function that I found it hard to follow, so I've refactored into smaller pieces, so it should be more maintainable going forward.
> vere: refactors ipc message parsing and assembly

- nix/release.nix
`sh/cross` can now be invoked as follows:
```
sh/cross urbit linux64
sh/cross urbit darwin
sh/cross urbit-debug linux64
sh/cross urbit-debug darwin
```
Note: this seems orthogonal to #2029, as it to builds a _separate_ `urbit-debug` binary.
> build: support for releasing cross-compiled debug binaries

- pkg/arvo/app/chat-cli.hoon
Fixes a bug introduced in #1995.
Also rings the terminal bell on tab in an empty buffer. That seems right to me, but I'm open to counterarguments.
/cc @liam-fitzgerald
> chat: don't crash on tab in an empty buffer

- pkg/arvo/lib/ethio.hoon
These show up occasionally but don't constitute an error unless the caller determines they're an error.  This silences the over-eager printfs.
fixes #2048
> eth-watcher: silence printfs

- pkg/urbit/vere/http.c
Fixes #2003.
`curl -I -X GET http://localhost:80/~/login`
```
HTTP/1.1 200 ok
Date: Wed, 04 Dec 2019 15:13:56 GMT
Connection: keep-alive
Content-Length: 1817
Server: urbit/vere-0.10.0
content-type: text/html
```
`curl -I -X GET http://localhost:80/~/i-dont-exist`
```
HTTP/1.1 307 moved
Date: Wed, 04 Dec 2019 15:26:36 GMT
Connection: close
Server: urbit/vere-0.10.0
location: /~/login?redirect=/~/i-dont-exist
```
> vere: filter out content-length header from eyre

- pkg/arvo/lib/chat/eval.hoon
Previous implementation was doing double virtualization, which gave issues
around scries. By reimplementing with mint and mock, we get to catch all
possible failure cases and produce an appropriate output for each.
Previously, as seen through chat-cli:
```
~zod# (need ~)
_/~zod/home/~2019.12.2..22.51.57..1c0e/app/chat-cli/hoo
bail: 4
~zod# (sein:title our now our)
```
Now:
```
~zod# (need ~)
crash!
~zod# (sein:title our now our)
.^ unsupported in chat eval
```
(Note that the stack trace for the "crash" case is still included with the message. We just prepend something guaranteed-readable now.)
Special thanks to @frodwith for writing & helping me understand the core logic here.
> chat: improve eval implementation

- pkg/arvo/app/chat-hook.hoon
This matches the behavior that's used for +kick on /mailbox, among other flows.
> chat-hook: no-op on /backlog kick if not synced

- pkg/urbit/include/c/defs.h
This should help debug the mysterious "memory lost" printfs we've been seeing on our infrastructure nodes.
> vere: print arg to c3_malloc() et. al. on failure

- pkg/arvo/app/dojo.hoon
- pkg/arvo/lib/hood/drum.hoon
Turns out this wasn't a regression, it was intended behavior.  I
continue to believe it's the wrong behavior, but that will require a
longer discussion.
See #2035.
> drum: revert tang ordering change

- bin/solid.pill
- pkg/arvo/sys/vane/gall.hoon
%leave over the network didn't work because we included the message type
in the wire from gall, so the duct for the initial %watch and the %leave
were different.  We need to know the message type so we can route the
acknowledgment as %poke-ack, %watch-ack, or no-op.
This moves this piece of information to a piece of state, where we queue
up the message types per [duct wire].  Ames guarantees that
acknowledgments will come in order.
This also includes an easy state adapter.  The more interesting part of
the upgrade is that we likely have outstanding subscriptions with the
old wire format.  The disadvantage of storing information in wires is
that it can't be upgraded in +load.  So, here we listen for updates on
the old wire format, and when we get them we kill the old subscription,
so that …
> gall: remove message type from wire

- pkg/urbit/Makefile
- pkg/urbit/include/vere/vere.h
- pkg/urbit/tests/newt_tests.c
- pkg/urbit/vere/newt.c
This PR builds on #2042 (and really should've been included there). It includes further refactoring of `newt.c` to enable testing of the serialization and parsing routines, said tests, and a fix for an infinite loop in the parser.
> vere: adds tests for newt ipc framing, fixes infinite loop

- pkg/arvo/sys/vane/ames.hoon
This is *actually* why the galaxies are under so much load.  They're in
a forwarding loop with their stars, and this breaks the loop.
> ames: don't forward up the sponsorship chain

- bin/solid.pill
- pkg/arvo/app/claz.hoon
- pkg/arvo/app/gaze.hoon
- pkg/arvo/lib/claz.hoon
- pkg/arvo/lib/ethio.hoon
- pkg/arvo/sur/claz.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/ted/claz/prep-command.hoon
- pkg/arvo/ted/eth/get-timestamps.hoon
Ports two of our Ethereum tools to static gall.
Gaze does Azimuth statistics tracking. It now makes sure to do reasonably-sized batch requests, and keeps track of invite events.
Claz does Azimuth transaction generation. It gets support for document voting functions, but otherwise maintains feature parity with the original. Did split it up into /sur, /lib, and /ted files as appropriate. Perhaps in the future some of that will be consolidates into a /lib/azimuth.
eth-txs sender app and/or strand still pending, but I believe we have the old one still available to us where needed. Figured I should get this PR in while I do a quick side-quest.
> Eth apps: gaze and claz

- bin/brass.pill
- bin/solid.pill
- pkg/arvo/gen/hood/ames-sift.hoon
- pkg/arvo/lib/hood/helm.hoon
- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/sys/zuse.hoon
Adds |ames-sift generator that passes a %sift $task to ames with a list of ships to track.  If null, Ames prints for all ships (still subject to the submodule filtering of |ames-verb); otherwise, Ames prints just for those ships selected in the arguments to the generator.
Includes a state adapter, which I've run locally without issue.  Should be OTA'able.
> Ames trace by ship

- pkg/urbit/vere/newt.c
This builds further on #2069 et all. As far as I can tell, this leak has always been present on `cc-release` and related branches. Pretty obvious in retrospect ...
> vere: plug a memory leak in IPC message parsing

- pkg/urbit/Makefile
- pkg/urbit/tests/ames_tests.c
The duplication in the Makefile was irritating, this instead builds based on the naming conventions in `./tests/`, and runs the tests via same naming conventions in `./build/`.
/cc @benjamin-tlon, do you see any issues with this approach?
> vere: updates the test build targets to be generic

- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/sys/vane/gall.hoon
See #2070 for rationale.  Fixes #2070.
Also send a %leave if we receive a watch-ack we didn't expect so we clean up the subscription on the other side.
OTA-able
> gall: no-op on duplicate watch-ack

- pkg/urbit/vere/ames.c
- pkg/urbit/vere/pier.c
This was never properly wired up in cc-release. Also adds port printfs for all ships.
> ames: honor -p for non-galaxies

- pkg/arvo/sys/vane/ames.hoon
We've seen issues where the message-num of the head of live.state is
less than current.state.  When this happens, we continually try to
resend message n-1, but we throw away any acknowledgment for n-1 because
current.state is already n.  This halts progress on that flow.
We don't know what causes us to get in this bad state, so this adds an
assert to the packet pump that we're in a good state, run every time
the packet pump is run.  When this crashes, we can turn on |ames-verb
and hopefully identify the cause.
This also adds logic to +on-wake in the packet pump to not try to resend
any messages that have already been acknowledged.  This is just to
rescue ships that currently have these stuck flows.
(Incidentally, I'd love to have a rr-style debugger for stuff like this.
Just run a command …
> ames: recover from mismatched message nums

- pkg/arvo/sys/vane/eyre.hoon
A common issue is not knowing where to get your login passcode.  This puts those instructions on the login page.
Not sure who to tag on this one, maybe @jyng or @g-a-v-i-n?  Feel free to improve text or styling.
Fixes #1965
> eyre: add instructions to login page

- pkg/arvo/app/clock.hoon
- pkg/arvo/app/goad.hoon
- pkg/arvo/app/hood.hoon
- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/sys/vane/gall.hoon
OTAs commonly end up in an inconsistent state if apps depend on changes
to /sys.  For example, the %sift changes break on OTA because %spider
needs to be reloaded so that it's aware of the new thread type.  This
adds a %goad app, which reloads all apps after every change to /sys.
Getting this to start OTA is nontrivial, but this pattern should work
for apps in the future.  The changes to clock shouldn't generally be
necessary; they are only necessary here because we can't rely on hood to
start goad, since hood fails to compile if it's run before zuse is
reloaded.  Once goad is active, this will cease to be a problem.
> goad: recompile apps after changes to /sys

- pkg/arvo/app/clock.hoon
- pkg/arvo/app/goad.hoon
- pkg/arvo/gen/hood/reboot.hoon
By not running the risky %goad card in on-init.  Also includes some qol fixes.
For some reason the zuse didn't get properly updated.  This seems to have fixed the issue.
Already deployed, but cc @joemfb
> goad: make startup resilient to errors

- pkg/urbit/vere/http.c
As discovered with clang's ASan. This supersedes #2090.
The thing I had missed, causing #2032, is that `h2o_send()` with `H2O_SEND_STATE_FINAL` *synchronously* finalizes/disposes the request and all associated resources.
There's a second use-after-free fixed in this PR. The response generator is disposed before the request, but I trying to inspect it on request-dispose in order to cancel the request in %eyre. That is now handled through the response generator as it should be.
> vere: fix use-after-free in http responses

- pkg/urbit/daemon/main.c
- pkg/urbit/noun/allocate.c
- pkg/urbit/noun/events.c
- pkg/urbit/noun/imprison.c
- pkg/urbit/noun/jets.c
- pkg/urbit/noun/manage.c
- pkg/urbit/noun/trace.c
- pkg/urbit/noun/vortex.c
- pkg/urbit/tests/mug_tests.c
- pkg/urbit/tests/noun_tests.c
- pkg/urbit/vere/ames.c
- pkg/urbit/vere/cttp.c
- pkg/urbit/vere/daemon.c
- pkg/urbit/vere/dawn.c
- pkg/urbit/vere/http.c
- pkg/urbit/vere/lmdb.c
- pkg/urbit/vere/newt.c
- pkg/urbit/vere/pier.c
- pkg/urbit/vere/reck.c
- pkg/urbit/vere/term.c
- pkg/urbit/vere/unix.c
- pkg/urbit/vere/walk.c
- pkg/urbit/worker/main.c
This PR includes fixes for some minor memory leaks, a bunch of cleanup. The leaks were discovered by running the daemon under valgrind, which is made possible the change to loom base pointer.
There are many other issues flagged by valgrind, predominantly due to a) insufficient cleanup on exit (especially in http.c and pier.c), b) openssl's use of uninitialized memory (well established), and c) valgrind's view that the loom is uninitialized memory.
I intend to produce a suppression file to make it practical to run the daemon periodically. Doing so with the worker is not currently viable, as it segfaults immediately under valgrind. I assume this has to do with snapshot initialization or restoration, but I haven't been able to track it down yet. Valgrind supports custom allocators, but it'll …
> vere: dynamic allocation cleanup

- pkg/arvo/sys/vane/eyre.hoon
This error is mostly harmless, but it does indicate we aren't cleaning
up our subscriptions properly.  This lets you silence with |knob.
fixes #2088
> eyre: turn sigpam into flog

- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/tests/sys/vane/ames.hoon
Two bugs fixed here: first, if the %done reentrancy triggered another
%boon, that wasn't getting translated to a %lost, even though it could
have been the reason the event crashed in the first place.
Second, the %done reentrancy needs to happen after we emit our move, so
that we don't invert the order of the %boon's we produce.
> ames: handle misordered crashing boons

- nix/ops/image/default.nix
Removes the `/bin` creation + symlink and related dockerfile `ENV` setting in favour of using the `nix.dockerTools.contents` attriubute to ensure `urbit` + `urbit-worker` or the debug variants are locatable via `PATH`.
> build: trimming unnecessary image configuration

- nix/ops/default.nix
- nix/ops/image/default.nix
By baking (potentially) multiple pills into an image, we can provide mainnet vs ropsten images. It is still up to the operator to pass along the pill path(s) to the entrypoint.
For example, using Docker:
```
docker run --tty urbit -B /share/brass.pill -J /share/ivory.pill ...
```
The main `image` attribute still uses only the solid pill and `image-ropsten` has been provided with brass and ivory pills.
Additionally, herb has been added to the image for convenience.
> build: allow baking multiple pills into docker images

- bin/solid.pill
- pkg/arvo/sys/vane/clay.hoon
Previously, it would always produce ~, regardless of the path asked
about.
Now, it produces a loobean, based on whether or not a file exists at the
specified path.
This largely mimics the surrounding code. It takes care to specify the actual output type (with a fake `%loob` mark) in the `^-` of `+read-u`.
Specifying just `cage` there allows us to do a simple `!>` on the actual result. However, with the `hypo` construction, this doesn't nest. I'm not sure why, so we just do as the surrounding code does: get the type using the type spear, and put in the result noun as-is. This can probably be simplified, happy to take suggestions.
> clay: implement %u care

- bin/brass.pill
- bin/solid.pill
- pkg/arvo/sys/vane/ford.hoon
Fixes https://github.com/urbit/urbit/issues/2109 by clearing the cache whenever Ford reloads.  Note that this also assumes Ford will be reloaded every time Zuse reloads.  That's an assumption we might want to relax eventually, but for now this, in combination with the recent :goad call from :dill, should fix OTAs.
I've confirmed that this reloads Ford properly on a fakezod.  Testing the bug repro on a comet locally at the moment.
> ford: clear build results on +load

- pkg/arvo/app/chat-cli.hoon
Crashes such as #2125 cause chat-cli to get its chat-store subscription kicked (as per gall's "you crash on it, you lose it" behavior). Chat-cli doesn't handle the `%kick` case in on-agent however, causing it to stop receiving messages until the user manually reconnects it.
That manual reconnecting, however, got broken during static gall conversion. Were were passing `[%noun the-noun]` into `+poke-noun`, instead of just `the-noun` like it expects. Of course, since it takes a noun as argument, this doesn't type fail, and so managed to sneak in undetected.
This PR fixes both of those, and also adds a `~|` to the path that hit #2125, so that we can look further into that when it next occurs.
This is intended to go OTA as a hotfix. I will go ahead and self-merge as such. I applied this update …
> chat-cli hotfix: reconnect to chat-store when appropriate

- bin/solid.pill
- pkg/arvo/app/azimuth-tracker.hoon
- pkg/arvo/app/chat-cli.hoon
- pkg/arvo/app/dojo.hoon
- pkg/arvo/app/gaze.hoon
- pkg/arvo/app/link-server-hook.hoon
- pkg/arvo/gen/reload-event.hoon
- pkg/arvo/lib/base64.hoon
- pkg/arvo/lib/bip32.hoon
- pkg/arvo/lib/der.hoon
- pkg/arvo/lib/hood/helm.hoon
- pkg/arvo/lib/hood/kiln.hoon
- pkg/arvo/mar/snip.hoon
- pkg/arvo/mar/txt.hoon
- pkg/arvo/sys/hoon.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/ted/azimuth-tracker.hoon
- pkg/arvo/ted/claz/prep-command.hoon
This has been getting on my nerves for the longest time, and today I finally snapped. Turns out it really isn't that hard!
This updates the `+wise` parser, used for `=;` and `=^` (and everything that compiles down to them, which is just `=/` I think) to accept molds (`+wyde`) without a specified face.
This allows for constructions such as:
```hoon
=/  [x=@ y=@]
[5 6]
-  ::  [x=5 y=6]
```
Note that if you want to use "`some-type`" this way, you need to prefix with the `,` to avoid having it parsed as a face instead.
```hoon
=/  ,octs
[2 'hi']
-  ::  [p=2 q='hi']
```
I've gone ahead and replaced all instances of `=+  ^-` with `=/`, and similarly cleaned up my own todo's for doing the same with `=-  ...  ^-` and `=;`.
> hoon: support =/ (and friends) without face

- pkg/arvo/sys/vane/ames.hoon
Updates and fills in missing pieces of documentation comments in /sys/vane/ames/hoon.
Does not change functionality.
> Ames: renovate doc comments

- bin/solid.pill
- pkg/arvo/app/aqua.hoon
- pkg/arvo/app/azimuth-tracker.hoon
- pkg/arvo/app/chat-cli.hoon
- pkg/arvo/app/chat-hook.hoon
- pkg/arvo/app/chat-store.hoon
- pkg/arvo/app/chat-view.hoon
- pkg/arvo/app/dns-collector.hoon
- pkg/arvo/app/dojo.hoon
- pkg/arvo/app/eth-watcher.hoon
- pkg/arvo/app/group-hook.hoon
- pkg/arvo/app/group-store.hoon
- pkg/arvo/app/invite-store.hoon
- pkg/arvo/app/invite-view.hoon
- pkg/arvo/app/launch.hoon
- pkg/arvo/app/link-proxy-hook.hoon
- pkg/arvo/app/link-store.hoon
- pkg/arvo/app/permission-hook.hoon
- pkg/arvo/app/permission-store.hoon
- pkg/arvo/app/publish.hoon
- pkg/arvo/app/spider.hoon
- pkg/arvo/app/weather.hoon
- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/lib/server.hoon
- pkg/arvo/sys/vane/gall.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/ted/azimuth-tracker.hoon
As discussed with @philipcmonk.
Instead of providing a `(unit path)`, allows for `(list path)`, which better supports the "update to path and subpath" cases.
For example, if `/things` wants updates about everything, and `/things/specific` wants updates about the specific thing, they'll both need to receive a `%fact` when the specific thing changes.
Previously, these would have been two separate moves. Now, gall handles the multi-targeting for you.
This seems to apply fine on top of ships with the previous gall version. Lots of userspace files give compile errors prior to `goad: recompiling all apps`, but that itself completes silently. Pretty sure this is known and harmless.
> gall: (list path) in %fact and %kick

- pkg/arvo/app/chat-cli.hoon
This, uh, fell into the same old case of using an arm from a `|_` without initializing that core with a sample first. In this case, that resulted in the `bowl` in `connect` being the default bowl here. This is fine for `~zod`, since it's the default ship, but gives incorrect behavior for anyone else.
(This is what I get for self-merging #2128 without review.)
> chat-cli: reconnect with actual bowl

- pkg/arvo/app/invite-hook.hoon
Discovered this while tracking down bugs in the invite flow of the new publish app. Looks like this codepath is not actually hit in chat because the frontend pokes json directly, without passing it through the invite-action mark.
> invite-hook: fixed incorrect assertion about outgoing invites

- pkg/arvo/app/lens.hoon
Flushing the state in the +take-export arm causes the assertion to fail on line 98. So flush it after instead.
> lens: don't prematurely flush state

- pkg/urbit/noun/imprison.c
This PR fixes a bug wherein cached mugs were wrongfully retained on editing cells, producing a jet mismatch in `+mug`. @eglaysher found the mismatched values while tracking down a potentially related bug in jaque.
The extent of the impact of fixing this bug is not yet clear; many things depend on mugs, and it's possible that something was depending on a (deterministically) wrong mug. More testing will be required before these changes can be released.
/cc @frodwith
> u3: clear cached mugs on cell edit

- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/pier.c
- pkg/urbit/vere/term.c
... by removing dynamic allocations from that codepath.
> vere: plugs memory leak in the terminal spinner

- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/ames.c
- pkg/urbit/vere/behn.c
- pkg/urbit/vere/cttp.c
- pkg/urbit/vere/daemon.c
- pkg/urbit/vere/http.c
- pkg/urbit/vere/pier.c
- pkg/urbit/vere/save.c
- pkg/urbit/worker/main.c
These changes properly un/initialize openssl and curl. And fill out the i/o driver exit handlers, removing unnecessary dynamic allocations along the way. I made these changes to remove noise from valgrind. More to come on the tooling/testing front ...
> vere: cleanup resources on exit

- pkg/urbit/Makefile
This continues to run all vere tests, as before, but now sets a non-zero exit code on test failure.
> vere: fixes Makefile test-runner, exiting on failed test

- pkg/urbit/include/c/defs.h
- pkg/urbit/include/c/portable.h
- pkg/urbit/noun/imprison.c
- pkg/urbit/noun/manage.c
- pkg/urbit/noun/retrieve.c
- moves the loom base pointer on linux-64 (thereby also supporting valgrind)
- fixes a compilation issue in c3_assert (something about inlining and fprintf)
- skips core dump ulimit increase (ASan uses tons of memory)
- removes obsolete `no_sanitize_address` attributes
This PR is just the bare minimum to be able to use ASan and Valgrind. I intend to enable ASan in CI, the only remaining obstacles are threading the build and test config through nix. In the meantime, these tools can now be used locally.
------
To use this, build vere directly from within nix-shell:
```
cd pkg/urbit
nix-shell
CFLAGS="-g -fsanitize=address -fno-omit-frame-pointer -Wno-macro-redefined" LDFLAGS="-fsanitize=address -fno-omit-frame-pointer -Wno-macro-redefined" ./configure 
make -j 8
export …
```
> vere: adds support for ASan

- bin/solid.pill
- pkg/arvo/sys/vane/ames.hoon
There was a typo in the routing logic that was comparing equality against a value where it should have been doing a pattern match.  The value compared against contained the literal `*` gate, which would never match `route.peer-state`, so this condition was always true, meaning the fix that had added this  extra condition (https://github.com/urbit/urbit/commit/5406f0609273fa4db1bd84bf600a401d1c114ae2#) did not actually change the behavior from what it been previously.
If only this had caused a type error ...
> ames: actually maintain direct routes

- pkg/arvo/sys/vane/clay.hoon
Previously undocumented, but properly supported. Largely copies the text from +read-t.
> clay: document %t care

- bin/solid.pill
- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/sys/vane/behn.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/vane/dill.hoon
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/vane/ford.hoon
- pkg/arvo/sys/vane/gall.hoon
- pkg/arvo/sys/vane/iris.hoon
- pkg/arvo/sys/vane/jael.hoon
Uses Zuse's previously unused +harden helper function to streamline +task unwrapping in vanes.
Arguably, in landlocked vanes like Ford, we should crash if we get a %soft task, since no events should be coming in directly from the outside.  I decided not to change any functionality in this PR, though.
> /sys: use +harden on vane tasks

- pkg/arvo/app/chat-cli.hoon
- pkg/arvo/app/chat-hook.hoon
- pkg/arvo/app/chat-store.hoon
- pkg/arvo/app/chat-view.hoon
- pkg/arvo/app/group-hook.hoon
- pkg/arvo/app/group-store.hoon
- pkg/arvo/app/permission-hook.hoon
- pkg/arvo/app/permission-store.hoon
- pkg/arvo/gen/dbug.hoon
- pkg/arvo/lib/dbug.hoon
This implements `/lib/dbug`, an agent wrapper in the style of `/lib/verb`, that gives you some generic ways of looking at application state. More concretely, you can look at the entire bowl, or see if there are any subscriptions matching your specified conditions.
Example:
```hoon
> :chat-store +dbug %incoming ship+our
[ i=[duct=[i=/g/use/chat-view/~zod/out/~zod/chat-store/updates t=~[/d //term/1]] ship=~zod path=/updates]
t=[i=[duct=[i=/g/use/chat-cli/~zod/out/~zod/chat-store/chat-store t=~[/d //term/1]] ship=~zod path=/updates] t=~]
]
```
The lists don't always print very prettily (ie above, they explicitly include list faces), but trying to cast those always kills the pretty-printer in a weird way. In any case, this should suffice for now.
I went ahead and included this in a couple …
> /lib/dbug agent wrapper

- bin/solid.pill
- pkg/arvo/sys/vane/ford.hoon
@ixv recently uncovered a bug (https://github.com/urbit/urbit/issues/2180) in Ford that caused certain rebuilds to crash.  @Fang- and I believe this change should fix the bug, and we have confirmed that the reproduction that used to fail about two thirds of the time now has not failed at all in the ten or so times we've run it since then.  @Fang- is still running more tests to confirm the fix with more certainty.
It turned out the cause was that (depending on the rebuild order, which is unspecified and should not need to be specified), Ford could enqueue a provisional sub-build to be run but then, later in the same +gather call, discover that the sub-build was in fact an orphan and delete it from `builds.state` accordingly.  Then when Ford tried to run the sub-build, it would have already …
> ford: dequeue orphans

- bin/solid.pill
- pkg/arvo/sys/vane/ford.hoon
Replaced manual calls to `(~(got by builds.state) build)` with a new `+got-build` helper function that prints a helpful error message on failure.
Depends on https://github.com/urbit/urbit/pull/2192
> Ford +got-build helper

- LICENSE.txt
Urbit is MIT licensed, but the LICENSE.txt file appears to have
disappeared from the toplevel directory in c86879e833.
> Restore toplevel LICENSE.txt file.

- pkg/arvo/app/link-listen-hook.hoon
- pkg/arvo/app/link-proxy-hook.hoon
- pkg/arvo/app/link-store.hoon
- pkg/arvo/gen/dbug.hoon
- pkg/arvo/gen/link-store/note.hoon
- pkg/arvo/gen/link-store/save.hoon
- pkg/arvo/lib/dbug.hoon
Broadly, the commits herein address two issues.
- Comments weren't being synced by link-listen-hook at all.  
2e8fb88 makes that so, but depends on 69c86d7, which is an ugly hack that would not have been needed had the link-store API rewrite from the `m/uplink-broad` branch been in use. That work requires a partial rewrite of the frontend logic, however, so that will have to wait for a bit longer. The hack is "good enough for now" and I fully intend to see its removal through.
- Link-listen-hook would not retry if rejected due to out-of-date group definition.  
8723dc6 implements retry logic with exponential backoff, so that we attempt to recover from rejected subscriptions.
Commits not directly addressed above are largely administrative in nature. This includes a couple cherry-picked …
> link: listening & comments

- sh/release
Fixes #1400.
Release tarballs previously didn't include a release directory, so the files would be unceremoniously dumped into the user's current directory when extracted.  No longer!
Before:
```
$ tar xzf urbit-linux64-v0.10.3.tgz
$ ls
urbit    urbit-linux64-v0.10.3.tgz    urbit-terminfo    urbit-worker
```
After:
```
$ tar xzf urbit-linux64-v0.10.3.tgz
$ ls
urbit-linux64-v0.10.3    urbit-linux64-v0.10.3.tgz
$ ls urbit-linux64-v0.10.3
urbit    urbit-terminfo    urbit-worker
```
> Make release tarballs extract to a release directory

- pkg/arvo/app/publish.hoon
- pkg/arvo/mar/publish/action.hoon
- pkg/arvo/sur/publish.hoon
- pkg/interface/publish/src/js/components/lib/new-post.js
- pkg/interface/publish/src/js/components/root.js
Changed the publish api so that group paths are passed through from the frontend rather than generated on the backend (except in cases where they must be generated on the backend).
also included a minor bugfix in this PR.
> publish group paths

- pkg/interface/chat/src/js/components/lib/invite-search.js
In invite-search.js, empty groups being mapped into a set (in order deduplicate known peers) return as `undefined`, which doesn't have an `includes` method ... which led to errors. This additional check doesn't map those empty groups.
> chat: filter empty groups from peer search

- pkg/arvo/app/link/js/index.js
- pkg/interface/link/src/js/api.js
- pkg/interface/link/src/js/components/lib/comments-pagination.js
- pkg/interface/link/src/js/components/lib/comments.js
- pkg/interface/link/src/js/components/lib/link-item.js
- pkg/interface/link/src/js/components/lib/links-tabbar.js
- pkg/interface/link/src/js/components/lib/pagination.js
- pkg/interface/link/src/js/components/link.js
- pkg/interface/link/src/js/components/links-list.js
- pkg/interface/link/src/js/components/root.js
- pkg/interface/link/src/js/lib/util.js
Base64 isn't actually URL-safe, so we now do base64url before chucking arbitrary strings into the route path.
A similar problem is going to come and bite us if someone ever tries making a `/group/with/depth`...
> link fe: use base64url

- pkg/arvo/app/link-store.hoon
- pkg/arvo/app/link-view.hoon
- pkg/arvo/lib/link.hoon
- pkg/arvo/sur/link.hoon
- pkg/interface/link/src/js/api.js
- pkg/interface/link/src/js/components/lib/link-item.js
- pkg/interface/link/src/js/components/links-list.js
- pkg/interface/link/src/js/components/root.js
- pkg/interface/link/src/js/reducers/link-update.js
- pkg/interface/link/src/js/store.js
- pkg/interface/link/src/js/subscription.js
Colors the relative time on items in the link list green if we haven't interacted with them yet. Allows you to clear this on everything at once with a simple button.
I want to do more work on this to get unread counts in the sidebar (and hide the "mark all as seen" button if there's nothing new), but want to get this merged in so that @vvisigoth has a stable backend state type to test against.
> link: minimum viable un/seen status

- pkg/arvo/app/publish.hoon
- pkg/interface/publish/src/js/components/lib/comments.js
- pkg/interface/publish/src/js/components/lib/new.js
- pkg/interface/publish/src/js/components/lib/notebook.js
- pkg/interface/publish/src/js/components/root.js
This PR contains the following changes. They're all fairly distinct and divided by commit, so it might be easiest to review one commit at at time.
- invite/kick user from a notebook when they're added/removed from related group
- added the "New Post" button for all writers of a notebook, not just the host
- added "create group" toggle on notebook creation page
- made comment box clear on submit
> OS1: publish, multiple fixes

- pkg/arvo/app/chat-hook.hoon
Prior to sending them out to the messaging target.
Fixes #2257.
> chat-hook: evaluate result-less %code messages

- pkg/arvo/app/link-store.hoon
- pkg/arvo/app/link-view.hoon
- pkg/interface/link/src/js/components/lib/channel-sidebar.js
- pkg/interface/link/src/js/components/lib/channels-item.js
- pkg/interface/link/src/js/reducers/link-update.js
Adds little unread counters to the link counts in the sidebar. (Disappear if there's nothing new.)
> link: unread counters in sidebar

- pkg/arvo/app/chat-cli.hoon
Also adds in some casts to ensure sane action data. The chat-view-action
changed in this commit should've been nest-failing.
@loganallenc this (still?) doesn't automagically do the host prefixing on these paths. Should I be doing that during construction of the `%create` action here?
> chat-cli: no longer allow %mailbox and %journal chats

- pkg/interface/link/src/js/components/lib/link-detail-preview.js
We no longer downscale to 500px wide, but rather however wide fits
within the container, and doesn't exceed 500px in height.
> link fe: properly downscale wide images to fit screen

- pkg/interface/contacts/src/css/custom.css
- pkg/interface/contacts/src/js/components/lib/share-sheet.js
Just lining it up with the group sidebar's header padding; consistent font size and color.
> contacts: design tweaks for share sheet

- pkg/interface/publish/src/js/components/lib/comment-item.js
- pkg/interface/publish/src/js/components/lib/comments.js
- pkg/interface/publish/src/js/components/lib/icons/sigil.js
- pkg/interface/publish/src/js/components/lib/note.js
- pkg/interface/publish/src/js/components/lib/notebook-item.js
- pkg/interface/publish/src/js/components/lib/notebook-posts.js
- pkg/interface/publish/src/js/components/lib/notebook.js
- pkg/interface/publish/src/js/components/lib/sidebar.js
- pkg/interface/publish/src/js/components/root.js
- pkg/interface/publish/src/js/components/skeleton.js
- pkg/interface/publish/src/js/lib/util.js
- Following the conventions set up in Chat, routes Contact metadata through the Publish interface (notebook view, note view, comments and sidebar).
- Adds sigils to comments.
- Replaces ship names with nicknames and Source Code Pro with Inter if a nickname exists wherever names appear.
> publish: add nicknames and sigils to interface

- pkg/interface/link/src/js/lib/util.js
Matching implementation from contacts' [lib/util.js](https://github.com/urbit/urbit/blob/33f7d62186a852b449bb160a82bf056ae6abdd3c/pkg/interface/contacts/src/js/lib/util.js#L65).
As [requested](https://github.com/urbit/urbit/pull/2272#discussion_r378074128) in #2272.
> link fe: make uxToHex more safe

- pkg/arvo/app/chat-cli.hoon
No longer supported. As such, we also don't include that in the
permission path anymore.
This is a follow-up to answers to questions in #2275.
> chat-cli: remove r/w specifiers for invite and banish

- pkg/arvo/sys/hoon.hoon
This has bitten me often enough that it's actually _really_ annoying now. I'm pretty sure this comment is at least _equally_ correct, and hopefully _more_.
"Replace" suggests this function either produces an updated set/map when done,
like `+snap`, or changes all values in-place, like `+turn`. In truth, it's more
similar to `+roll`, which does reduction/accumulation.
("Reduce" specifically was chosen because it maintains the mnemonic relation to
the arm name.)
> hoon: clarify comments for +rep:in and +rep:by

- pkg/interface/chat/src/js/components/chat.js
- pkg/interface/chat/src/js/components/root.js
- pkg/interface/chat/src/js/reducers/initial.js
- pkg/interface/chat/src/js/store.js
Fixes #2212.
Also kicks you back to the main screen if the current station is not in your inbox, instead of just doing it if there are no stations in the inbox.
> chat: fix double message bug

- pkg/arvo/app/metadata-store.hoon
- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/sur/metadata-store.hoon
Added first pass of metadata-store, a data store for application metadata and mappings 
between groups and application data (chatrooms, publish notebooks, etc).
I will add documentation to this before merging it, but I wanted to put out this version for review. The hook will be started next and will be in a separate PR, then integration work will be merged in as its own PR.
> metadata-store: associate groups with resources within apps, and allow various types of queries

- pkg/interface/link/src/js/components/lib/link-item.js
`seenState` was supplying `grey2` instead of `gray2`, making the read state black in both color schemes. This commit corrects that.
> link: correct unread color class

- pkg/interface/chat/src/js/components/chat.js
The station format changed from `/~zod/lmao` to `/~/~zod/lmao` at some point. This breaks my stuff from #2221, and possibly other things in `chat.js` as well. Here's a fix.
> chat: fix station string format

- pkg/arvo/app/link-store.hoon
- pkg/interface/link/src/js/reducers/link-update.js
When pulling in submissions and comments from other ships, we want to make sure we integrate them properly into our latest-first data structures, on both the back- and frontend.
> link: ensure content remains sorted by timestamp

- pkg/arvo/app/link-listen-hook.hoon
- pkg/arvo/app/link-proxy-hook.hoon
- pkg/arvo/mar/link/listen-poke.hoon
Broadly:
- Fixes incorrectly implemented subscription response in link-proxy-hook.
- Makes link-listen-hook instances kick each other into listening on-group-join. Retry mechanic already accounted for out-of-sync group definitions, this just expedites the process.
> link: peer subscription fixes

- pkg/interface/chat/src/js/components/lib/invite-search.js
- pkg/interface/publish/src/js/components/lib/invite-search.js
If we don't have any ship peers in the search results, and the search term is a valid ship name, show it as a result.
> chat, publish: invite-search surfaces valid ship name as result

- pkg/arvo/app/publish/index.hoon
- pkg/interface/publish/src/css/custom.css
- pkg/interface/publish/src/index.js
- pkg/interface/publish/src/js/api.js
- pkg/interface/publish/src/js/components/lib/comments.js
- pkg/interface/publish/src/js/components/lib/dropdown.js
- pkg/interface/publish/src/js/components/lib/header-bar.js
- pkg/interface/publish/src/js/components/lib/icons/icon-home.js
- pkg/interface/publish/src/js/components/lib/new-post.js
- pkg/interface/publish/src/js/components/lib/new.js
- pkg/interface/publish/src/js/components/lib/note.js
- pkg/interface/publish/src/js/components/lib/sidebar.js
- pkg/interface/publish/src/js/components/lib/subscribers.js
- pkg/interface/publish/src/js/components/root.js
- pkg/interface/publish/src/js/components/skeleton.js
- pkg/interface/publish/src/js/reducers/response.js
Polish batch:
- new-post.js had `mw7` and the other views use `mw6`, so the views weren't consistent in use. Amended to all use `mw6`.
- Sidebar sorter uses the custom dropdown component. Dropdown component gets an `align` prop to flush itself left or right against its parent.
- Sidebar was too long to see all notebooks if you have a lot of notebooks. This is calc'd against the UI height now.
- header-bar moved back into skeleton a la Chat. Spinner added as an animation on the Home button.
- header-bar sigil is now lined up properly with the ship name, and blends into its background regardless of theme.
- New posts, new notebooks, new comments all have proper button disabling transitions and spinner functionality.
- Adding some fixes for `-m` and `-l` viewports for sidebar and note.js …
> publish: add spinner, transition behaviours

- pkg/interface/chat/src/js/components/chat.js
- pkg/interface/chat/src/js/components/lib/chat-input.js
- pkg/interface/chat/src/js/components/lib/message.js
If the sigil has not been given a colour by its owner, blend it into the background for both themes.
(I also caught a case where we don't sig planet names if a member is in a chat but not a contact, so I added a sig in that case.)
> chat: blend uncustomised sigils

- pkg/interface/contacts/src/js/components/lib/contact-card.js
- pkg/interface/contacts/src/js/components/lib/contact-item.js
- pkg/interface/contacts/src/js/components/root.js
- Clicking "share with group" would create the same double redirect silent crash that creating a new group would — just keeping the user in an unedited share view, but toggled, and having none of their changes propagate to the interface. This redirects the user to the "view card" view with a `.then()` after the api call, and adds spinner behaviour on top, which works as expected.
- I also added a similar `.then()` call for deleting a group and _then_ redirecting the history, and spinners there as well. It also now pushes you to `~contacts` and not to the (now vacant) group if you're deleting yourself.
- I think this might've been a regression I introduced by pasting in the sigil.js changes I've made from other applications (sorry). But sigils weren't updating to reflect their colours …
> contacts: redirecting share view, sigil color fix

- pkg/arvo/app/chat-store.hoon
Fixes #2182.
Same functionality as #2304, but as Logan pointed out this is better done in the store instead of the frontend.
> chat-store: immediate handle-read on our %message

- pkg/arvo/app/publish.hoon
- pkg/arvo/sys/vane/ford.hoon
This PR fixes the issue described here: https://github.com/urbit/urbit/issues/2321
Of crucial importance: This needs to go on the network at the same time as the rest of the OS1 stuff. If this goes on the network as a separate step, it will not work.
cc-ing @jtobin to make sure you see this. With the recent talk about how parts of feature branches can go in at different times, I want to make sure this one does not go in at a different time.
> OS1: fix publish ford OTA issues

- pkg/interface/chat/src/index.css
Three for three on missing the check-in for index files resulting in breakage. I'll be more careful.
> chat: remove spinner.css from index.css

- pkg/interface/link/src/js/components/lib/link-detail-preview.js
- pkg/interface/link/src/js/components/lib/link-item.js
- pkg/interface/link/src/js/components/skeleton.js
Link items in the detail view and in the list view now properly truncate link titles to the maximum width of the page container.
The issue has to do with the implicit `min-width: auto` of flex items that allow them to overflow their parents. Since we have nested flexboxes, if one overflows *its* parent, then all its children will obey the overflow in turn. In this case, I had to attribute a `min-width` to both the link item to restrict it to the page container, and then add another `min-width` to the skeleton, which was overflowing its parent in turn.
> link-fe: truncate titles properly

- pkg/interface/chat/src/js/components/join.js
- pkg/interface/chat/src/js/components/new.js
- pkg/interface/contacts/src/css/custom.css
- pkg/interface/contacts/src/js/components/lib/contact-card.js
- pkg/interface/contacts/src/js/components/lib/edit-element.js
- pkg/interface/contacts/src/js/components/new.js
- pkg/interface/link/src/css/custom.css
- pkg/interface/link/src/js/components/lib/link-submit.js
- pkg/interface/link/src/js/components/link.js
- pkg/interface/publish/src/css/custom.css
- pkg/interface/publish/src/js/components/lib/comments.js
- pkg/interface/publish/src/js/components/lib/join.js
- pkg/interface/publish/src/js/components/lib/new.js
Part of the Indigo spec. Text boxes, when focused, get a black border.
I threw it into Links' multi-line input too, but that one's more blurry as to whether it matches the specification (cc @urcades):
> chat, contacts, link-fe, publish: black borders on focused input

- pkg/arvo/sys/vane/eyre.hoon
- pkg/interface/chat/tile/tile.js
- pkg/interface/clock/tile/tile.js
- pkg/interface/contacts/tile/tile.js
- pkg/interface/launch/src/css/custom.css
- pkg/interface/launch/src/js/components/home.js
- pkg/interface/launch/src/js/components/tile.js
- pkg/interface/link/tile/tile.js
- pkg/interface/publish/tile/tile.js
- pkg/interface/soto/tile/tile.js
- pkg/interface/weather/tile/tile.js
- Add dark mode class declarations to launch 
- Add dark mode classes to all tiles.
- Add a dark mode event listener to clock, swapping out a few hex colors for background and text. @g-a-v-i-n 
- Add dark mode styles to sign in screen.
> launch: dark mode

- pkg/arvo/app/metadata-hook.hoon
- pkg/arvo/app/metadata-store.hoon
- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/sur/metadata-hook.hoon
Added metadata-hook. This hook networks the metadata-store by making all resources related to a particular group-path accessible.
One can subscribe to the metadata-hook upon a group-path and receive updates any time a resource changes associated with that group-path.
I'll add better documentation before merging this, but am mostly interested in a quick review / sanity check of the functionality / logic itself.
I'll be moving into testing and integration with `chat` with my next set of PRs.
> metadata-hook: a hook for sending metadata over the network

- pkg/arvo/app/permission-hook.hoon
If we `%add-owned`, then we add an entry to the `access-control` jug matching the
data we put into the `synced` map. When a permission gets deleted, we remove it
from `synced`, but previously neglected to clean up the matching access-control
entry.
This ensures that if a permission was deleted, and we had it registered as
owned, that the relevant `access-control` entry is removed from state.
OS1 chat OTA depends on this change. In my testing so far, I haven't encountered any race conditions of this not being in by the time chat-hook gets to its upgrade logic, but don't feel comfortable guaranteeing it to be fine to go in _with_ OS1. Ideally, we can push this out to livenet beforehand. (It _is_ just a bugfix, after all.)
> permission-hook: clean up access-control on %delete

- pkg/arvo/gen/dbug.hoon
I find myself asking for `%state` way more often than `%bowl`, so seems fair to make that the default when no arguments are supplied to `+dbug`.
> dbug: default to %state

- pkg/interface/publish/src/js/components/lib/note-navigation.js
- pkg/interface/publish/src/js/components/lib/note.js
- pkg/interface/publish/src/js/components/lib/notebook-posts.js
Wraps titles and snippets in Note headers and "All Posts" view, in addition to long, single-element blocks like `<a>` elements inside posts, so that nothing overflows the X-axis. 
Note navigation gets `flex-auto` to restrict itself to its parent and its titles get truncated.
> publish: wrap or truncate title / snippet overflow

- pkg/arvo/app/chat-hook.hoon
- pkg/arvo/app/metadata-store.hoon
- pkg/arvo/app/permission-group-hook.hoon
- pkg/arvo/lib/hood/drum.hoon
As usual, see commit messages for deets. Primarily, this PR does two things:
- Make chat-hook depend on metadata-store for permission checks (specifically, to find the group(s) associated with the chat it wants to check permissions on).
- Add on-upgrade logic to chat-hook that will migrate "legacy" `/chat/~host/name` group (& permission) paths to the new `/~/~host/name` format. (We use the `/~` prefix here, signifying an "unmanaged" group, because these groups were created hidden from the user, and thus should remain as such.)
I've done some light testing on this, and nothing obvious breaks. That said, I want to put some more stress on this and see if it still holds up. Hence the draft status. Still, a preliminary review seems good to have here, given the nature of all this.
Thanks …
> OS1 OTA: chat groups & permissions

- pkg/interface/publish/src/js/components/lib/new-post.js
Before, if you wrote a note with a duplicate title, the promise would be rejected, but the front end would silently fail, hung on the spinner.
This commit adds a catch: if we get "note already exists" back from the promise, we revise the `new-note` object to append a timestamp to the `@tas` and send it back to the API.
(Why a timestamp? Because we don't have the full list of notes in state, just the most recent 50, so we can't reliably, proactively, see in front-end if we're about to duplicate a title.)
I also re-order the `awaiting` state change to happen *after* the API call, because otherwise it would:
- set the `awaiting` state, 
- see that it had the duplicate note already as the original note's title before the promise returned,
- push the route to the original note while we're …
> publish: catch, amend, resubmit when creating notes with duplicate titles

- pkg/arvo/app/publish.hoon
- pkg/interface/publish/src/js/components/lib/join.js
- pkg/interface/publish/src/js/components/root.js
- Disabling the join button entirely if we don't have anything to send, so it doesn't have to handle that catch in `onClickJoin`
- Text input scrolls horizontally if the input is too long instead of the awkward multi-line thing it had
- Adding UI transitions to properly forward us to the notebook once we've joined it, and catching it when we join a notebook that doesn't exist (and the spinner behaviour, which I forgot to add earlier)
- If we tried to join our own, pre-existing notebook it would spin `<<http>>` forever, I think even persisting on reboots and requiring a fresh fakezod? I added a `return` before the auto-redirect transition so we don't make the API request and it has, seemingly, fixed it. It wasn't ... joining itself forever, was it?
- I also added the ability to …
> publish: join notebook polish, join from URL

- pkg/arvo/app/publish.hoon
In the OS1 OTA transition for publish it recreates notebooks, and sends invites to people that were previously subscribed. However since old publish did not have its publish invite store path initialized, people who receive that invite before they get the update will just crash and never see it even when they upgrade.
So this PR just adds that invite store path, just to avoid this messiness in this particular case. This change should go on the network ASAP.
> publish: add publish invite path

- pkg/interface/link/src/js/components/lib/comment-item.js
- pkg/interface/link/src/js/components/lib/comments.js
- pkg/interface/link/src/js/components/lib/link-detail-preview.js
- pkg/interface/link/src/js/components/lib/link-item.js
- pkg/interface/link/src/js/components/links-list.js
- pkg/interface/link/src/js/lib/util.js
- pkg/interface/publish/src/js/components/lib/comment-item.js
- If a user is a member, but not a contact (no metadata shared), their sigil is unstyled and blended as in Chat and Contacts. This is now incorporated into Publish and Links.
- Links had one too many `flex-auto`s and thus while long titles were truncated properly, short titles pushed their hostname too far to the edge. This is amended and it all seems to work properly now for both cases.
> links, publish: blend member sigils

- pkg/arvo/app/publish.hoon
- pkg/interface/publish/src/js/api.js
- pkg/interface/publish/src/js/components/lib/edit-post.js
- pkg/interface/publish/src/js/components/lib/new-post.js
- pkg/interface/publish/src/js/components/lib/note.js
- pkg/interface/publish/src/js/components/root.js
- Add a wildcard to the endpoint mount for notes so we can handle params
- Removes an errant console.log
- Create an "Edit Post" component with a similar presentation as New Post
- Routes it into Note view and conditionally checks if the user is in the write group before presenting the 'edit' link
There were some inline styles that duplicated indigo-static classes in new-post, I believe, so I swapped in those classes too.
Editing a note and then viewing the note returns the note but with a new line appended to the start and end. I can't see why this would originate in front-end: the state and value changes don't have this new line. 
I can only think this happens as part of the processing of the note after the API submission. Do you know why this does this?
> publish: add 'edit note' functionality

- pkg/interface/chat/src/js/components/lib/invite-search.js
- pkg/interface/chat/src/js/components/new.js
- pkg/interface/chat/src/js/components/root.js
- pkg/interface/contacts/src/js/components/lib/add-contact.js
- pkg/interface/contacts/src/js/components/lib/invite-search.js
- pkg/interface/contacts/src/js/components/new.js
- pkg/interface/contacts/src/js/components/root.js
- pkg/interface/publish/src/js/components/lib/invite-search.js
- pkg/interface/publish/src/js/components/lib/new.js
- pkg/interface/publish/src/js/components/root.js
Submitting this PR for feedback and then I'll port the changes to all apps, so don't merge immediately.
This is an implementation that creates a map of all our contacts and every nickname we have for them; on search, we filter the array of nicknames and if we have any partial match, throw their ship into the search results.
Separately, in the render side we append all nicknames we know of. Both nicknames and long ship names get truncated.
In this implementation the performance will worsen the more contacts we have. At that point, we will probably want to debounce the search input.
> invite search: fuzzy search ships by nicknames, show ship nicknames

- pkg/arvo/app/publish.hoon
This PR fixes various issues encountered in the process of upgrading publish from the old version.
In order:
- fixes a problem where it was making a %sing clay request rather than a %next, which required a second change to the file state before it detected the initial change
- set the tile num for invites and unread notes properly upon upgrading
- No longer leave notebooks on upgrade, since the other side will %kick you anyway and send invites for you to resubscribe. Gettting the update first and leaving too soon would mean you don't get the invite.
- Ignore subscription updates on the old /collection/* subscription path, just prevents uneccesary stack traces in some cases, functionally its the same.
- Stop reading in the date-created field at file change time, rather than just reading it …
> OS1: publish ota-ability fixes

- sh/cachix
This has been an issue in recent PRs from forked repos.
> ci: skip cachix push if env is not set and in a pr build

- pkg/arvo/app/metadata-store.hoon
In order to track & respond to all app-related metadata, hooks may want to
subscribe to the metadata-store as the first thing they do on-init. In that case
it is exceedingly likely that there are no entries for the `app-name` in
`app-indices` yet.
This makes us fall back to the empty set in case `app-indices` has no entry for
the `app-name` yet.
> metadata-store: never crash fetching app metadata

- pkg/arvo/app/metadata-store.hoon
- pkg/interface/contacts/src/js/components/lib/contact-card.js
- pkg/interface/contacts/src/js/components/lib/contact-sidebar.js
- pkg/interface/contacts/src/js/components/lib/group-detail.js
- pkg/interface/contacts/src/js/components/root.js
- pkg/interface/contacts/src/js/reducers/metadata-update.js
- pkg/interface/contacts/src/js/store.js
- pkg/interface/contacts/src/js/subscription.js
To re-target `master` once #2365 is merged. Until then, this is just for review!
- Quick display fix on the 'delete' button which was too close to the edge.
- Quick typo fix in metadata-store that led to `/all` subscriptions failing.
- Wrote a metadata reducer for the initial load and for `add` events; there are likely delete and change events but I cannot produce one!
The metadata data structure I wrote for the front-end is a map, keyed by group path, whose value is an object with keys of the channel name and a value of the full object. Like so:
This makes it simple to display and programmatically link to.
We pass all these "Open" links to the `/join` path of the respective application, because each application has a handler that redirects to a channel if we're already subscribed, or …
> contacts: add group details page, metadata-store reducer

- pkg/interface/chat/src/js/components/lib/sidebar-item.js
- pkg/interface/chat/src/js/components/root.js
- pkg/interface/chat/src/js/components/sidebar.js
- pkg/interface/chat/src/js/reducers/metadata-update.js
- pkg/interface/chat/src/js/store.js
- Adds a basic metadata-update reducer that is keyed by `app-path`
- Displays the title of the chat in sidebar
- Integrates contact metadata in the sidebar while we're at it
- Fixes a bug where unmanaged chats weren't showing 'selected' CSS by propping the `station` call from router to the sidebar
- Fixes a bug where 'me' messages showed as blank in the sidebar
> chat: display chat titles in sidebar

- pkg/interface/contacts/src/js/components/lib/contact-sidebar.js
- pkg/interface/contacts/src/js/components/lib/share-sheet.js
I changed the copy and appearance (color only) of the "Invite" button previously located in Contacts, as it looked like a non-interactive label.
I actually have a related Asana task to this issue regarding copy-checking in general throughout OS1, so the copy of this button edit may change in the near term, depending on how this other task goes.
> contacts: changed color + copy of "add to group" button

- pkg/arvo/lib/metadata-json.hoon
- pkg/arvo/mar/metadata/action.hoon
- pkg/interface/chat/src/js/api.js
- pkg/interface/chat/src/js/components/lib/message.js
- pkg/interface/chat/src/js/components/root.js
- pkg/interface/chat/src/js/components/settings.js
- pkg/interface/chat/src/js/reducers/metadata-update.js
- Adds sig-prepended, unmanaged chats to the regex that linkifies channels when mentioned in chat
- Adds a "copy shortcode" section to settings with the channel name for easy copying
- Dark mode linkified chats had a black border underneath them instead of white. No longer.
- Took a detour in ~hell~ lib/metadata-json.hoon and wrote JSON to metadata action parsers for add and remove actions, because I can do that now
- Constructed the API calls in the front-end for revising metadata
- Added 'update-metadata' responses to the metadata reducer (it just overwrites the entry in the map)
- Added edit fields for title, description, and color; the color field is regex validated for 6 hexadecimal characters; all fields pre-fill with current metadata and are disabled and faded if you aren't the …
> chat: settings — edit channel metadata, shortcode copying

- bin/solid.pill
- pkg/arvo/lib/test/ford.hoon
- pkg/arvo/sys/vane/ford.hoon
This PR is a rethink of #2322 -- slightly less principled, but much more performant. It restores %ford's "pit" short-circuit for kernel builds, but only during the boot process. Bugs caused by faulty "pit" short-circuit during normal operation will still be fixed as they were in #2322, but boot and `+test` are both much faster. These changes are necessary to restore well-functioning CI, and keep our kernel cycle-times somewhat reasonable.
These changes were made on #2366, but should go in separately (and maybe first). I'll update that PR once this is complete and merged.
> ford: restores pit-shortcircuit, but only during boot

- pkg/arvo/app/chat-view.hoon
- pkg/arvo/app/metadata-hook.hoon
- pkg/arvo/mar/metadata/action.hoon
Pretty small change, but nice quality of life improvement.
NOTE: this is good to keep in mind for links and publish, because the preference is now to send all metadata actions through %metadata-hook so that we have automatic support for foreign chatrooms / publish blogs / links collections being shown in the group's available channels. (not just the host's channels)
> metadata-hook: support group members other than host creating/editing shared resources

- pkg/interface/chat/src/js/components/settings.js
Before this gets put into all the other apps, I wanted to polish it — adding some padding below the 'edit color' input and black borders on focus to match every other input area.
> chat: settings inputs add borders on focus

- pkg/interface/chat/src/js/components/root.js
Because you can make multiple chats based on the same group, we check for the current station in our associations Map and if it's there, check for the associated group in contacts to push that metadata to the chat view.
(Simpler than I thought — since the other conversions to metadata-store are in progress, I really do recommend using an app-path keyed Map for their metadata...)
> chat: pull room contacts from associated group

- pkg/urbit/vere/reck.c
... due to periodic minor leaks. This was enabled in #1323. It'd be nice for it to run in CI, but running it on user ships is not worth the risk of crashing on (ephemeral) leaks.
#2177 may be a good place to re-enable in CI.
> vere: disables gc on |mass in the daemon process

- sh/release
Historically Vere has used a simple 'vx.y.z' versioning scheme that predates the monorepo structure introduced in 7ce50ad.  Going forward it's expected that our blessed runtime king/serf binaries will follow the scheme 'urbit-vx.y.z', i.e. with an `urbit-` prefix, to disambiguate them from other repository subprojects.
This renames Vere release tarballs as their version followed by their target platform.  So with the updated tag scheme, instead of e.g. 'urbit-linux64-vx.y.z.tgz' these will appear along the lines of 'urbit-vx.y.z-linux64.tgz'.
(**Note**: currently these release binaries are generated for every commit, but it seems it would be sufficient to just generate them for tags starting with `urbit-v`.  This would catch all releases and release candidates.  Does anyone feel strongly …
> Rename Vere release tarballs

- pkg/interface/chat/src/js/reducers/metadata-update.js
- pkg/interface/groups/src/js/reducers/metadata-update.js
- Chat handles metadata `remove` updates
- Groups handles metadata `update-metadata`, `remove` updates
Creating a chat that creates a group and deleting the chat removes the chat from the channel list, but the group persists ... I wonder if there's something we should handle there or just leave it be. 
I suppose I understand the case where you would want to make a new channel for a group that started in Chat and then have no channels — you could pick up elsewhere.
> chat, groups: metadata reducer additions

- pkg/interface/groups/src/js/api.js
- pkg/interface/groups/src/js/components/lib/group-detail.js
- pkg/interface/groups/src/js/components/lib/group-sidebar.js
- pkg/interface/groups/src/js/components/new.js
- pkg/interface/groups/src/js/components/root.js
- pkg/interface/groups/src/js/components/skeleton.js
- Set ASCII safe path as well as group metadata when creating a group
- Removing an invite error check in state — invite-search handles those now
- Surface group titles in the sidebar
- Filter the group's metadata entry out from the channels list
> groups: set + show group name; exclude group metadata from channel list

- pkg/interface/chat/src/js/components/lib/invite-search.js
- pkg/interface/groups/src/js/components/lib/invite-search.js
- pkg/interface/publish/src/js/components/lib/invite-search.js
Was starting work on incorporating the group names into the search and started with this — the blending of results was padded inconsistently and all black on dark mode. This should be solid now.
Outside this PR, I wanted to inquire about two issues with incorporating group names and slate it for later work:
1. We don't get group metadata from our subscriptions and we would have to add another subscription and reducer set to get them
2. Reducers are done a bit inconsistently at the moment anyway (Chat + Notebooks + hopefully the others using a Map, Contacts using an object), and throwing associations to the invite search component would basically expect a Map. Hopefully since Contacts' invite search usage disables group searching it wouldn't even come up (we could just throw a `new Map` in …
> invite search: proper padding, blending of group name

- pkg/interface/publish/src/js/components/lib/join.js
Prevents multiple clicks while we wait for a response for joining a notebook in Publish by disabling the button until we hear back.
> publish: disable button after joining book

- pkg/interface/groups/src/js/components/lib/contact-card.js
Contact card header had some weird behaviours.
- "Share with Group" got overlapped by the other buttons in different viewports.
- The "me" view had a different header height size than the contact card view — I think because one of the buttons had a different margin setting than the other, and when absent, it created an askew look to the header.
- `<— Channels` shouldn't link back to `/~/default` on the "me" view. Now it does not.
> groups: tweak contact card navigation

- pkg/interface/groups/src/js/components/lib/group-sidebar.js
When accepting an invite, the sidebar would crash the application
because we were accessing 'metadata' of undefined -- accessing
too many nested property levels without enough safety.
This commit just adds a check for the intermediate property.
> groups: sidebar, additional check for safety

- pkg/interface/chat/src/js/components/lib/invite-search.js
- pkg/interface/chat/src/js/components/new.js
- pkg/interface/chat/src/js/components/root.js
- pkg/interface/groups/src/js/components/lib/invite-search.js
- pkg/interface/groups/src/js/components/lib/sidebar-invite.js
- pkg/interface/groups/src/js/components/new.js
- pkg/interface/link/src/js/components/lib/invite-search.js
- pkg/interface/link/src/js/components/new.js
- pkg/interface/publish/src/js/components/lib/invite-search.js
- pkg/interface/publish/src/js/components/lib/new.js
- pkg/interface/publish/src/js/components/root.js
- If we have group metadata, organise our initialised index of groups as an array of `["endpoint", "title"]`
- When searching, filter against both indexes of the array with `||` so partial matches against either return the group as a result
- Show the title if we have it, otherwise show the endpoint
- If group results are disabled then group metadata can be exempted as a prop without a resulting crash. 
If I can flex for a second: I wrote this entire thing in one go, cold, and it just worked. I felt really powerful.
I don't know if calling `.includes()` on a string that isn't allocated in an array causes a crash (see L101 of invite-search.js in these commits) — but thus far we don't pass groups without the associated group metadata so ... 
I think maybe if we skip the dedupe we do by …
> invite search: surface group metadata in results

- pkg/interface/groups/src/js/components/lib/group-detail.js
- Really long group titles can overlap with "settings" on smaller viewports, so this is a a bandaid fix to shrink its max-width based on the viewport size.
> groups: add max-width for group titles

- pkg/arvo/sys/vane/eyre.hoon
Resolves a long-standing issue where going to the naked /~/login path after already being logged in would return a blank page and not properly redirect.
> eyre: upon login redirect parameter being empty, redirect to /

- pkg/interface/groups/src/js/components/new.js
- pkg/interface/groups/tile/tile.js
- pkg/interface/launch/src/js/components/header.js
- pkg/interface/launch/src/js/components/home.js
- pkg/interface/launch/src/js/reducers/invite.js
- pkg/interface/launch/src/js/store.js
- pkg/interface/launch/src/js/subscription.js
- Open a subscription to invite-view in launch
- Append the initial object to the data we pass to child tiles
- Add the invite count to the groups tile
This doesn't account for invite-updates — we would need to write some proper reducers for launch. Do we want to do that now? Later?
> launch: subscribe to invite-view, show group invite count in tile

- pkg/interface/publish/src/js/components/lib/edit-post.js
Previously, the button was filled in white — looking icky in dark mode.
> publish: make 'edit post' button transparent

- pkg/interface/publish/src/js/components/lib/edit-post.js
On smaller screens the "Save post" button would overlap with the sidebar switch — this just does the same thing as [45af92c](https://github.com/urbit/urbit/pull/2317/commits/45af92c173e3de0de443a121d24e3b44eee87c24#diff-937cf0ac21da74e0283462b4bf02930bR161) to get it out of the way...
> publish: add -m, -l widths for edit post button

- pkg/interface/chat/src/js/components/chat.js
Closes #2421. Reopens #2024, #2331. With apologies to @litpub.
The tradeoff costs of the implementation in #2295 were judged too high for being used in production right now — as we head into OS1 launch we decided as a team that the best solution for the moment is to go back to the previous experience, working on everything but FF's scroll; rather than having scrollback jumping to the bottom on new messages.
Additionally, @loganallenc said he already investigated the intersectionObserver API discussed in #2421 about a year or so ago and this implementation was the best tradeoff he had. Thus, we are in the position to have to just revert this for now.
This weird flexbox issue is at least making a bit of progress at Mozilla — they've marked it [on their shortlist of bugs to fix this …
> chat: revert #2295, #2371 — restores previous scroll implementation

- pkg/interface/chat/src/js/components/lib/chat-input.js
- pkg/interface/chat/src/js/components/lib/message.js
Cuts up a message by gaps in the message, removes the URLs and reattaches the message content with the gaps intact; sends the URLs as separate messages after it.
> chat: splice, URL test and send mixed content messages

- pkg/interface/launch/src/js/components/header.js
The notification could overlap long @ps. This amends the notification
to be relative to the @p block, pushed to the left of it. Fine in all browsers as far as I can tell.
> launch: notification in header is relative to @p

- pkg/interface/chat/src/js/components/lib/message.js
- pkg/interface/chat/src/js/components/settings.js
- pkg/interface/chat/src/js/lib/util.js
- pkg/interface/clock/tile/tile.js
- pkg/interface/link/src/js/components/root.js
- pkg/interface/link/src/js/components/settings.js
- pkg/interface/publish/src/js/components/lib/comments.js
- pkg/interface/publish/src/js/components/lib/new-post.js
- pkg/interface/publish/src/js/components/lib/new.js
- pkg/interface/publish/src/js/components/lib/note.js
- pkg/interface/publish/src/js/components/lib/settings.js
- pkg/interface/publish/src/js/components/lib/sidebar-invite.js
- pkg/interface/publish/src/js/components/lib/subscribers.js
- pkg/interface/publish/src/js/lib/util.js
- Fix the OS1 clock in Safari by using `addListener` not `addEventListener`
- Fix clock smearing as it redraws itself
- Fix an issue in Links where going to popout from Settings rendered without OS1 chrome
- Add some dark mode styles to buttons in Chat and Links
- Line up the header across the link list and settings views in Links
- Add dark styles for dropdown options in unmanaged notebooks' subscriber settings
- Add a darker bottom border to invite items in Publish
- Safety check by giving fallback values to the Note view in Publish
- Prevent duplicate note submissions in Publish
- Line up the top matter of notes in Firefox
- Fix the padding of the comments area in Firefox
- Change the clipboard API we use for copying shortcodes with a polyfill for Safari support
- Remove the linked …
> os1: bug bashing, volume 1

- pkg/arvo/app/chat-cli.hoon
From 22cc6ae:
Re-enables chat creation, touches up invite logic, and makes everything work with the new "un/managed" attribute of chats.
Changes the +target type, so requires state transition. We use that opportunity to clean up our messages mirror (memory reclamation).
"Unmanaged" chats should work the same as they did before.
Group-based chats are secondary citizens (seriously, just use the group web-ui), but supported by prepending "group " to whatever target you want to use. ie:
```
;join group ~marzod/secret-club  ::  join a group-based chat
;group ~marzod/secret-club       ::  target a group-based chat
```
The latter case should be rarely needed, as glyphs remember this attribute of their bound target.
Creating a group alongside a chat is supported through:
`;create …
> chat-cli: support group-based chats

- pkg/arvo/app/chat-hook.hoon
Have tested this with ~bus and with ~zod. The issue was that my previous testing was on ~zod, where the bunted our.bol value of 0 was actually working with no issue. For the recreate-chat pokes to be going through, I needed to be calling the arms within the cc core.
> chat-hook: ota fix and improvement on backlog fetching

- pkg/interface/chat/src/js/components/member.js
- pkg/interface/chat/src/js/components/new.js
- pkg/interface/chat/src/js/components/settings.js
- pkg/interface/chat/src/js/components/skeleton.js
- pkg/interface/groups/src/js/components/lib/contact-card.js
- pkg/interface/groups/src/js/components/lib/group-detail.js
- pkg/interface/link/src/js/components/links-list.js
- pkg/interface/link/src/js/components/member.js
- pkg/interface/link/src/js/components/new.js
- pkg/interface/link/src/js/components/root.js
- pkg/interface/link/src/js/components/settings.js
- pkg/interface/publish/src/js/components/lib/edit-post.js
- pkg/interface/publish/src/js/components/lib/new-post.js
- pkg/interface/publish/src/js/components/lib/note.js
- pkg/interface/publish/src/js/components/lib/notebook.js
- pkg/interface/publish/src/js/components/lib/settings.js
- pkg/interface/publish/src/js/components/skeleton.js
Walked through the flows in browser, some stuff on my phone, reviewed @urcades footage from Android. Closes #2431.
- All apps submit settings changes on blurring focus off the input, not on clicking 'save'
- Rearranging the invite search above the members list for Chat and Links
- Links had two display declarations leading to its 'root' page showing on mobile when it shouldn't
- Rearranging publish overflow to use the parent container, not the views.
- Adding mobile '<— Back' navigation when making a new post in Publish
- Some padding changes in Links
- Changes its approach for `/me` back navigation in Groups: a conditional '<- Back' link on the contact-card that changes its href depending on whether it's root identity, because otherwise mobile users had no navigation back.
- Chat …
> os1: mobile pass

- pkg/arvo/app/link-proxy-hook.hoon
Was using "manual" scries, and incorrect ones at that. Would crash, causing
subscriptions to not go through. Now uses the helper function and correct paths.
> link-proxy-hook: correctly scry initial response

- pkg/arvo/app/contact-hook.hoon
- pkg/arvo/app/contact-store.hoon
- pkg/arvo/app/contact-view.hoon
- pkg/arvo/app/eth-watcher.hoon
- pkg/arvo/app/invite-hook.hoon
- pkg/arvo/app/invite-store.hoon
- pkg/arvo/app/invite-view.hoon
- pkg/arvo/app/launch.hoon
- pkg/arvo/app/publish.hoon
- pkg/arvo/app/weather.hoon
This has proven very valuable for surface-level debugging so far. Looking at state, subscriptions etc. With OS1 support rush in mind, adds /lib/dbug to a handful of apps that didn't have it yet.
> apps: augment with /lib/dbug

- pkg/arvo/ted/eth-watcher.hoon
To 30 blocks + 30 blocks + 0-5 minutes == about 15 minutes total.
Further reduction should be possible, but requires changing the
algorithm a bit.  We don't want to reduce the number of confirmations
below about 30, though, since we don't handle reorganizations well.
See #2414.
> eth-watcher: reduce required number of confirmations

- pkg/arvo/sys/arvo.hoon
Does what it says ... This printf is unnecessary, and repeats unpleasantly in stack traces. It was an ill-advised last-minute addition in #2366. Mea culpa.
@jtobin, I'm happy to push one or more pills into this PR if that'd be useful.
> arvo: removes looping crash printf

- pkg/arvo/sys/vane/behn.hoon
Restores previous behavior.  This is wrong, but without it we fail when
vanes (specifically Ford) crash on goof.
Confirmed this works on a localhost version of ~pem.  To access +repn from the dojo, I then had to run `|wipe-ford 100`.  I assume os1 does this kind of thing programmatically.  Regardless, os1 should be tested as an OTA directly on top of this.
> behn: drop drip failures

- pkg/arvo/gen/dbug.hoon
- pkg/arvo/lib/dbug.hoon
`+dbug [%state 'some-hoon']` now allows you to run `some-hoon` against the
application's state. That hoon has access to the bowl and stdlib for
more dbugging convenience.
Behold:
```hoon
> :chat-store +dbug [%state '~(key by inbox)']
{[i=~.~ t=/~dev/hello]}
```
Some applications, like chat-store, accrue enormous amounts of state. Being able to poke at that more granularly will likely prove useful in debugging issues with those applications.
> dbug: allow complex, hoon-based state queries

- pkg/interface/chat/src/js/components/lib/chat-input.js
Hot and cold in that order. This amends the behaviour of messages
with text and URLs to submit them in order of found URL,
instead of batching the URLs at the end.
Same message, before and after:
> chat: split and send mixed messages sequentially

- pkg/interface/launch/src/js/components/home.js
Closes #2472.
If you set the weather it currently crashes the launch screen because it tries to set an invites property on a string. 
Since the invite append behaviour was intended for the groups tile, I'm just commenting it out here to prevent the crash, and to go later at integrating invite numbers across all tiles at once (if we even want to do that — we've been discussing the flows a lot lately).
> launch: stop passing 'invite' prop to tiles

- pkg/interface/weather/tile/tile.js
Closes #2473.
Autodetect doesn't redirect after it's done. 
It submits fine, but people can be confused. (The clock doesn't update to be colourful either but that's patched in #2471 — it's also possible that 2471 fixes some wonky weather behaviours too.) 
With both of these patches, though, weather should be restored to normal.
> weather: redirect after autodetect submission

- pkg/arvo/app/chat-cli.hoon
During upgrade, we gassed _in_ a map, instead of _by_, causing it to use
set-style sorting, leading to incorrect lookups.
This fixes that upgrade logic, and re-builds the map for existing instances.
(idk what the width configuration was doing there for the previous upgrade-to-same case.)
Fixes #2478.
> chat-cli: ensure bound map is sorted

- pkg/interface/chat/src/js/components/lib/chat-input.js
See some chatter in #2454.
Current URL regex is getting too many false positives, cutting up debug conversations. Replacing with one that only matches positive if there's a schema in front:
- www.google.com doesn't match. img.jpg doesn't match. a base hash won't match.
- https://google.com will match.
- dat://wogjerpgorejgiuohg3oigh3g03ihtq3.onion will match.
cc @ixv
> chat: use more precise regex for splitting messages

- pkg/interface/chat/src/js/components/lib/chat-input.js
Closes #2499.
In the chat input we fall back to `#000000` and blend it; but we also
prefix any colour we send to the sigil component with a `#` for
`uxToHex` values, so we end up passing `##000000`. This results
in simplified sigils -- when in doubt, ensure the hex formatting
is correct...
> chat: remove "#" from fallback sigil color in chat input

- pkg/interface/launch/src/js/components/home.js
You see this gap in the top left?
It's a blank tile for invites, now that we subscribe to them. I thought I was filtering it out — since it's kind of infrequent that you see this gap — but now it specifically doesn't return a tile for it.
> launch: don't render blank invites tile

- pkg/interface/soto/src/js/components/input.js
When we make a Dojo session, we use Sole to communicate between Dojo and whatever interface we have, transmitting each keystroke as you type and dynamically correcting as you go. This makes things a bit difficult for pasting, because you need to input each keystroke in series without losing track of the state on either side.
This commit sequentially resolves keystroke transmission promises, waiting for each to be confirmed before continuing. Seems to work in all browsers, had a hiccup that only happened one time in Firefox where later ones came first? But then it worked fine the time after that.
This is right click only for now, but I can figure out how to programmatically grab ctrl+v / cmd+v later...
> soto: allow paste functionality on right-click

- pkg/arvo/app/chat-view.hoon
- pkg/arvo/lib/chat-json.hoon
- pkg/arvo/sur/chat-view.hoon
- pkg/interface/chat/src/js/api.js
- pkg/interface/chat/src/js/components/root.js
- pkg/interface/chat/src/js/components/settings.js
Allows users to upgrade invite-only chats into full-fledged groups (with an associated chat). Relies on largely on existing chat-view logic to move things around (delete the old chat, create the new one, copy messages & metadata over).
Frontend copy might need another pass, but shouldn't be awful as-is.
> chat: groupify

- pkg/arvo/app/chat-cli.hoon
Downgrades unmanaged chat paths to their uglified versions, as used by
web chat. Removes "group-based" indicators and makes them implicit in
shorter paths instead. Fixes #2503.
Includes a just-in-case addition of fixing configured `width` if it's not sane. Observed it being 0 on development ships a small amount of times. Couldn't reproduce, but want to add this as a precaution: should patch up anyone left in insane state.
> chat-cli: absolute parity wrt "shortcodes"

- pkg/arvo/app/publish.hoon
This fixes https://github.com/urbit/urbit/issues/2511
The problem was in the +make-groups arm, in the case that we're using a foreign hosted group, we didn't mirror that group in our permission store. Now we do, and there's an upgrade flow in +on-load to create those permissions for already created notebooks that have this problem.
> publish: fix permissions issue

- pkg/interface/link/src/js/components/lib/link-detail-preview.js
- Gets the embed HTML from the Soundcloud [oembed API](https://developers.soundcloud.com/docs/oembed). 
- Sets the HTML in our state once we get it since we're waiting on a promise; passes it into the DOM as HTML directly as a fallback from the local `embed` variable (theoretically unsafe if we assume Soundcloud's oembed API gets attacked?).
In general I think what we really want is to stop manually regexing for these embeds and to get the Links back-end to get the metadata for us — so we can support anything and everything that returns an embed as part of OpenGraph.
For now this is ok. I think @vvisigoth just wants it in.
> links: add soundcloud embeds

- pkg/arvo/app/chat-cli.hoon
This way we don't just crash on the scry that follows.
Seen this occur on first boot occasionally. The resulting crash seems harmless, but this should clean it up regardless.
> chat-cli: skip catch-up if chat-store not booted

- pkg/arvo/app/chat-store.hoon
It was filling the number.envelope prior to adding the envelope to the
mailbox, but wasn't actually including that change in the %message(s)
update that was getting sent out.
This makes +append-envelope return both the updated mailbox _and_ the
modified envelope, which we then use in our outgoing update.
Tested, live, on ~paldev. Works fine.
> chat-store: include msg sequence nrs in update

- pkg/interface/publish/src/js/components/lib/note.js
- pkg/interface/publish/src/js/components/lib/notebook.js
- pkg/interface/publish/src/js/components/skeleton.js
Fixes this issue (https://github.com/urbit/urbit/issues/2479) which was introduced by this commit (https://github.com/urbit/urbit/pull/2446/commits/1b4b3274893c50e0038a2555b4e65808e456ebc8) which moved the scrolling behavior to the skeleton component, causing the onScroll event to fail to fire.
I was told this was to fix a visual bug, which I think was primarily about the scrollbar showing up on the inner div, rather than at the right side of the screen. This PR doesn't re-introduce the scrollbar visual bug, the only visual difference between this and whats on the network now is the sidebar toggle and popout buttons now stay in place as you scroll.
> publish: fix onScroll fetching bug

- pkg/interface/soto/src/js/components/input.js
- Allows pasting from the keyboard to pass through the keypress handler and use `onPaste`'s sequential promises
- On @ohAitch's suggestion invert the `ignoredKeys` approach and use the four longer keys as a whitelist
> soto: cmd/ctrl+v pasting, whitelist keys

- pkg/arvo/sys/vane/ames.hoon
Gives you a poor man's progress bar.  For example, to determine how much
of an OTA you've downloaded from your sponsor, run:
|ames-sift (sein:title our now our)
|ames-verb %rcv
and then to turn it off:
|ames-verb
> ames: print num-fragments in packet verbage

- bin/solid.pill
- pkg/arvo/sys/arvo.hoon
We have three stacks: the hoon stack, bar stack, and duct stack.  This
turns the bar stack to a list of ducts and adds it to the hoon stack.
This tells you the ducts of the moves that caused the move where you
crashed.
See:
```
recover: dig: intr
crud: %belt event failed
bail: intr
bar-stack
~[
~[/g/use/spider/~zod/find/~.dojo_0v5ogno.5anji.vn3f6.4gs7t.6r2ft /d //term/1]
~[/g/use/dojo/~zod/out/~zod/spider/drum/wool /d //term/1]
~[/d //term/1]
~[/g/use/dojo/~zod/drum/hand /d //term/1]
~[/g/use/hood/~zod/out/~zod/dojo/drum/phat/~zod/dojo /d //term/1]
~[/d //term/1]
~[//term/1]
]
call: failed
/~zod/home/~2020.3.17..23.14.11..50e0/sys/vane/ford:<[6.128 3].[6.220 5]>
/~zod/home/~2020.3.17..23.14.11..50e0/sys/vane/ford:<[6.129 3].[6.220 5]> …
```
> arvo: Multi-stack drifting

- pkg/interface/publish/src/js/components/lib/new-post.js
- Some classes as a shim for making a new post on `-l` and `-m` viewports breaking into the other buttons
- Adding a conditional check to the `postSubmit` function since the onclick seemingly fires regardless of the disabled check? This would allow blank notes to be submitted.
> publish: responsive new post button classes, prevent blank note submission

- pkg/interface/publish/src/css/custom.css
- pkg/interface/publish/src/js/components/lib/edit-post.js
Fixes https://github.com/urbit/urbit/issues/2542
For some reason calc behaves differently on firefox, so I stopped using it. Tested on Firefox, Chrome, Safari and Brave.
> publish: stop post input area from overflowing parent container in firefox

- pkg/arvo/app/chat-view.hoon
- pkg/arvo/lib/chat-json.hoon
- pkg/arvo/sur/chat-view.hoon
- pkg/interface/chat/src/js/api.js
- pkg/interface/chat/src/js/components/lib/invite-element.js
- pkg/interface/chat/src/js/components/lib/invite-search.js
- pkg/interface/chat/src/js/components/new.js
- pkg/interface/chat/src/js/components/root.js
- pkg/interface/chat/src/js/components/settings.js
- pkg/interface/groups/src/js/components/lib/add-contact.js
- pkg/interface/groups/src/js/components/lib/invite-search.js
- pkg/interface/groups/src/js/components/new.js
- pkg/interface/link/src/js/components/lib/invite-element.js
- pkg/interface/link/src/js/components/lib/invite-search.js
- pkg/interface/link/src/js/components/new.js
- pkg/interface/publish/src/js/components/lib/invite-search.js
- pkg/interface/publish/src/js/components/lib/new.js
Expands on the "groupify" functionality added in #2480 by allowing you to merge invite-only chats into an existing group.
UI/copy here might need some light touching up. Currently just display the group search, lets you continue without selecting a group (old behavior, creates a new group based on the chat), or shows you the "inclusive" toggle if you do select a target group (new behavior, merges chat into existing group).
> Chat: move chat to existing group

- pkg/arvo/app/goad.hoon
In many cases running without %force is insufficient because ford
crashes while unsubscribing.  This should fix some cases of OTAs being
received but not processed.
> goad: run with %force on kernel change

- pkg/interface/link/src/js/components/lib/channel-sidebar.js
Closes #2502.
During the metadata restructure I didn't adjust this property pass, and it passed through an empty "group" prop and processed it as 0. This commit fixes that.
> link: restore contributor counts in sidebar

- pkg/arvo/app/chat-hook.hoon
We would remove the entry from state, but not clean up its subscriptions.
Found this trying to join a chat I was in that got deleted, then re-created. It yelled `subscribe wire not unique` at me for `/mailbox/~/~host/chat`.
@loganallenc Perhaps this change should also be made for the `%store` case? But that doesn't do any subscription cleaning rn so I'm less sure. Please confirm sanity on this in general.
> chat-hook: clear all subscriptions on watch-nack

- pkg/interface/chat/src/js/components/sidebar.js
In the chat sidebar, we were looking for the box in our contacts object, 
not the associated group, so if you had a group and chat of the same name,
you'd see nicknames, but in no other situations. This commit rectifies
that by safely polling for the associated group of the chat.
> chat: sidebar pulls nickname from associated group

- pkg/interface/publish/src/js/components/lib/sidebar.js
Closes #2558. 
Alphabetical and reverse alphabetical sort in the sidebar
now uses localeCompare instead of Unicode point comparison.
> publish: sort inclusive of accented characters

- pkg/interface/groups/src/js/api.js
- pkg/interface/groups/src/js/components/lib/contact-sidebar.js
- pkg/interface/groups/src/js/components/lib/group-detail.js
- pkg/interface/groups/src/js/components/root.js
Closes #2483.
What it says on the tin ... the behaviour when you create a group in another app and then delete it in groups is neat — it seems to just seamlessly keep working, but retains its non-sig-prepended path.
> groups: delete group members without shared metadata; delete groups

- pkg/interface/chat/src/js/components/settings.js
Introduced in #2546, the new functionality seems able to induce weird
behavior causing messages to be processed twice. Disabling this
functionality on the frontend until that has been fixed.
> chat fe: disable advanced groupify

- pkg/interface/groups/src/js/components/lib/contact-sidebar.js
Adds 'adminOpt' to the remove button for group members
who have not yet shared metadata.
(Otherwise "Remove" shows all the time beside those members, for all members' UIs, in every group.)
> groups: permission remove button for group members

- pkg/interface/chat/src/js/components/settings.js
Reverts urbit/urbit#2566. The issue observed doesn't have anything to do with this logic in particular. See also #2579.
> Revert "chat fe: disable advanced groupify"

- pkg/interface/publish/src/js/components/lib/comment-item.js
- pkg/interface/publish/src/js/components/lib/comments.js
- Much like the chat variant, shows your last pending comment in faded opacity below; and still allows you to type another one while waiting for it. Posting that second comment, however, will still be disabled while you're waiting.
Performance question: To get it to be a seamless update (not popping in and out), I handle it in `componentDidUpdate`, but I can't get it to only do this when the latest comment has changed; if I add another `[0]` to that `Object.keys()`, it never processes — even though the strings ostensibly are different between the previous latest comment and our current; if I just compare `Object.keys()`, it always processes, on every keystroke, because it's comparing arrays, and of course the arrays are different assignments.
Likewise, handling pending comments in our …
> publish: add pending state for comments

- pkg/interface/groups/src/js/components/lib/contact-card.js
- Before we saw if window.ship was in the path of the group. If you're a star or higher, you'll match many group paths that you don't own. This strengthens the check.
- When you were looking at your own card in another group, it would say "Remove from" group. This is from an arbitrarily strict ternary check that adminOpt catches for us, so we just check if the ship is us.
> groups: two contact card changes

- pkg/arvo/app/chat-view.hoon
Provided "load backlog on-scroll" actually works, you don't really need
all that much on initial load.
> chat-view: limit initial scrollback to 25 msgs

- pkg/arvo/sys/zuse.hoon
Trying to use some http api, with a url of the following shape, and was getting a cttp error upon sending out the request.
```
https://example.com/?what=this,that
```
```
cttp: url parsing failed
cttp: strange request (unparsable url)
```
Looked it up, `cttp.c` just calls `de-purl:html`. Turns out that doesn't like commas in the query. Both [RFC 2396](https://tools.ietf.org/html/rfc2396#section-3.4) and [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.4) allow this though.
This makes the minimum viable change to get `,` to parse as part of a url's query.
I would've changed `+fque` and `+fquu` to use `+pque` instead, which seems to match RFC 3986, but that's a more drastic change: query parsing would no longer uses `+pold`.
`+pold`'s behavior (replace `+` with ` `  (ace)) seems …
> zuse: allow com in de-purl query parsing

- pkg/arvo/lib/dbug.hoon
This proved a little rough around the edges during recent investigation. Printing accounted for TMI type information, and didn't let you select all subscriptions.
Previously (truncated example):
```hoon
> :chat-hook +dbug [%outgoing %ship our]
[ i=[[wire=/store/~/~dev/bbb ship=~dev term=%chat-store] acked=%.y path=/mailbox/~/~dev/bbb]
t
[   i
[[wire=/store/~/~dev/rrr ship=~dev term=%chat-store] acked=%.y path=/mailbox/~/~dev/rrr]
t
[   i
[[wire=/store/~/~dev/cc ship=~dev term=%chat-store] acked=%.y path=/mailbox/~/~dev/cc]
t
...
]
]
]
```
This PR prints subscription details in a cleaner way, and sorts them by wire or path for outgoing and incoming subscriptions respectively.
Now (also truncated, but to the same linecount as above):
```hoon
> :chat-hook +dbug [%outgoing ~]
[wire=/invites …
```
> dbug: subscription searching & printing improvements

- pkg/arvo/lib/dbug.hoon
I oopsied this in #2587. Made it pretty-print the vase of the state, instead of just the state. Tiny fix!
> dbug: print %state's value, not whole vase

- pkg/interface/link/src/js/components/lib/link-item.js
In links, the `pt1` used to separate the `LinkItem` matter — title and author/date/comments — stretches the sigil, being sized at 36, to 36x38. It results in this:
I decided to just size it up to 38px instead of futzing with the line-heights of the matter.
> links: adjust sigil size to 38

- pkg/arvo/sys/zuse.hoon
Considering some of the options here were atoms, not cells, `$%` wasn't
appropriate, and led to `*etyp:abi:ethereum` resulting in ford %ride execution
failure. Simply using `$?` instead would result in a `fish-loop`, so here we split
the atom cases from the tagged union ones with a `$@`.
Previously:
```hoon
> *etyp:abi:ethereum
ford: %ride failed to execute:
```
Now:
```hoon
> *etyp:abi:ethereum
%string
```
> zuse: better ethereum abi data type

- pkg/interface/soto/src/js/components/input.js
Closes #2590.
If you entered the web dojo and hit Backspace immediately,
it would still process it as a valid key but pass the whole key forward.
This adds a conditional to ignore the key in those cases.
> soto: ignore backspace at cursor position 0

- bin/solid.pill
- pkg/arvo/gen/hood/cancel.hoon
- pkg/arvo/lib/hood/kiln.hoon
- pkg/arvo/sys/vane/clay.hoon
Makes it so that |cancel %force skips the next thing in the queue if
you're not in the middle of something.  If you are in the middle of
something, it skips the thing you're in the middle of (just like naked
|cancel).
This should resolve issues where |cancel doesn't drain the queue.
> clay: add option to skip queue

- pkg/interface/publish/src/js/components/lib/note.js
- pkg/interface/publish/src/js/components/skeleton.js
I noticed the skeleton leads to overflow out of the parent container on very small sizes.
I add `flex-auto` so that it stays within the container with horizontal scroll if it is indeed that small.
I also pass a prop to the react-markdown renderer so links in Publish'd notes target `_blank`, opening in new tabs, instead of leaving the app.
> publish: flexbox sizing in skeleton, links open in _blank

- pkg/interface/link/src/js/components/lib/link-submit.js
Adds a disabled check during link submission to prevent duplicates.
Also fixes an unmarked bug where 'linkValid' was not being reset to
false on submission, allowing for submitting blank links after one
correct link has been submitted.
> links: prevent duplicate link submissions

- pkg/interface/publish/src/js/components/lib/comments.js
Noticed this when commenting in ~dopzod's notebooks — it shows ~dopzod as the author of the pending comment because we pass `this.props.ship` not `~${window.ship}`, so this commit fixes that.
> publish: pending comments use our ship, not owner

- pkg/interface/publish/src/js/components/lib/note.js
- pkg/interface/publish/src/js/components/lib/notebook.js
- Adds the ability to delete notes for note authors, within the note, beside the 'edit' button.
- Adds a slight tweak to line up mobile navigation between the notebook view and the all notebooks view — it was affected by inner component padding, so it's pulled out of that padding.
(Also rearranged `componentWillMount` in note.js since it was in a weird position in the code.)
> publish: delete notes

- pkg/arvo/lib/server.hoon
We weren't doing basic server-side caching of our assets, which was significantly slowing down our pageload speed. Added a simple policy where assets we frequently change have a 1 day timeout and assets that don't frequently change have a 1 week timeout.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
> server: add basic cache-control for faster load speeds

- pkg/arvo/app/link-listen-hook.hoon
- pkg/arvo/app/link-store.hoon
- pkg/arvo/mar/link/listen-action.hoon
- pkg/arvo/mar/link/listen-update.hoon
- pkg/arvo/sur/link-listen-hook.hoon
- pkg/interface/link/src/js/api.js
- pkg/interface/link/src/js/components/lib/channel-sidebar.js
- pkg/interface/link/src/js/components/root.js
- pkg/interface/link/src/js/components/settings.js
- pkg/interface/link/src/js/components/skeleton.js
- pkg/interface/link/src/js/reducers/listen-update.js
- pkg/interface/link/src/js/store.js
- pkg/interface/link/src/js/subscription.js
Previously, we were mangling the group associations when "removing" link collections. But precisely because we were removing the collection's metadata, there was no way to rejoin them. 
This PR updates link-listen-hook to explicitly track the resources we're listening to in state, and provides actions for removing from (and adding back to) that list.
To match that, on the frontend, we fill the sidebar based on this list from link-listen-hook, instead of looking at all the associations stored in metadata. We also always show the "remove" action to everyone, but still only show "delete" to group owners.
Fixes #2576. Also fixes a bug where link-store was sending out updates for content it had already heard before.
> link: leave collections, retain metadata

- pkg/arvo/app/launch.hoon
- pkg/arvo/app/launch/index.hoon
- pkg/interface/chat/src/css/custom.css
- pkg/interface/chat/src/js/components/lib/welcome.js
- pkg/interface/chat/src/js/components/sidebar.js
- pkg/interface/groups/src/css/custom.css
- pkg/interface/groups/src/js/components/lib/group-sidebar.js
- pkg/interface/groups/src/js/components/lib/welcome.js
- pkg/interface/launch/src/js/components/home.js
- pkg/interface/launch/src/js/components/welcome.js
- pkg/interface/link/src/css/custom.css
- pkg/interface/link/src/js/components/lib/channel-sidebar.js
- pkg/interface/link/src/js/components/lib/welcome.js
- pkg/interface/publish/src/css/custom.css
- pkg/interface/publish/src/js/components/lib/sidebar.js
- pkg/interface/publish/src/js/components/lib/welcome.js
- Add startup content with instructions and tips for new users. Does not proc on OTA, only for new ships. Dismisses each message with `localStorage`, and in each app auto-dismisses the message if you have any data anyway.
- The link in launch for the 'lobby' is presently a URL join for `~/~dopzod/urbit-help`, lmk if this is changing.
> os1: add startup content

- pkg/arvo/sys/arvo.hoon
This must have been removed on accident recently.
> arvo: add wire to %give verb message

- pkg/arvo/app/metadata-hook.hoon
Not sure why this was still missing, I thought I got all of 'em in #2448. Apparently I missed a spot!
> metadata-hook: use dbug agent wrapper

- pkg/arvo/lib/dbug.hoon
- pkg/arvo/lib/verb.hoon
Events always pass through these, adding to the stack trace on-crash.
This information is practically never useful, however. Adding !. leaves
these cores out of the traces.
Before:
```
> :link-store %something-dumb
/~dev/home/~2020.3.26..19.03.58..29bd/sys/vane/gall:<[1.191 9].[1.191 37]>
/~dev/home/0/lib/dbug/hoon:<[30 5].[84 7]>
/~dev/home/0/lib/dbug/hoon:<[31 5].[84 7]>
/~dev/home/0/lib/dbug/hoon:<[32 7].[33 19]>
/~dev/home/0/lib/dbug/hoon:<[32 25].[32 47]>
/~dev/home/0/lib/verb/hoon:<[31 3].[39 15]>
/~dev/home/0/lib/verb/hoon:<[32 3].[39 15]>
/~dev/home/0/lib/verb/hoon:<[33 3].[39 15]>
/~dev/home/0/lib/verb/hoon:<[38 3].[39 15]>
/~dev/home/0/lib/verb/hoon:<[38 21].[38 43]>
/~dev/home/0/app/link-store/hoon:<[99 5].[107 17]>
/~dev/home/0/app/link-store/hoon:<[100 5].[107 17]> …
```
> lib: !. on dbug and verb wrapper agent cores

- pkg/arvo/app/chat/index.html
- pkg/arvo/app/contacts/index.html
- pkg/arvo/app/launch.hoon
- pkg/arvo/app/launch/index.hoon
- pkg/arvo/app/launch/js/channel.js
- pkg/arvo/app/link/index.html
- pkg/arvo/app/publish/index.hoon
Transition to serving Channel.js from an app rather than from Eyre directly. Given that we've already merged cache-control into index.html, we can't remove the channel-js from Eyre yet, so this commit serves a duplicate channel.js from an app with max-1-day caching in the meantime.
I think this is the right decision, as caching this file removes 2s from time of pageload to receiving data.
In a week or two, we could remove channel-js from Eyre for good.
What say you?
> apps: added a duplicate channel.js for caching, updated script tags to point to it

- pkg/arvo/app/contact-hook.hoon
- pkg/arvo/app/group-hook.hoon
This fixes a bug where group-hook wouldn't resubscribe correctly upon getting kicked. Now uses the correct group path for that resubscribe, instead of the whole wire.
Also adds on-load logic that checks to see if we have a subscription in place for every `synced` entry, and starts a new subscription if we don't.
Couldn't help myself and touched up the kick and watch-nack logic a bit to be more clear and correct. `=*` for pointing to specific parts of the wire that we care about, and the watch-nack case now makes sure it's actually relevant to the current configuration before we delete the entry. (The `=/  =ship` was sitting unused, pretty sure this is what it was intended for.)
I would test this on ~palfun but it's still spinning behn from today's OTA. Happy to wait that out and give it a …
> group-hook: fix resubscribe bug

- pkg/arvo/app/link-listen-hook.hoon
During the #2607 upgrade, strictly local collections got left out of the
listening set. (Because they did not have any outgoing subscriptions.)
This led to personal collections not being available on the frontend.
Here, we add upgrade logic for adding those back to our listening set again.
If a user had explicitly left a personal collection (instead of deleted it, for
whatever reason), they will have to leave it again. This case seems much more
rare than the "my collection is gone" one.
> link-listen-hook: recover neglected collections

- bin/solid.pill
- pkg/arvo/sys/vane/clay.hoon
Fixes #2602
I haven't been able to reproduce this bug, but I can see how it could
happen in theory.  This should resolve the issue.
> clay: don't underflow when patch produces empty file

- pkg/interface/chat/package-lock.json
- pkg/interface/chat/package.json
- pkg/interface/groups/package-lock.json
- pkg/interface/groups/package.json
- pkg/interface/link/package-lock.json
- pkg/interface/link/package.json
- pkg/interface/publish/package-lock.json
- pkg/interface/publish/package.json
The new version of urbit-ob includes stricter isValidPatp checks. Bumping to close issues around correct patp validation.
Fixes #2556
> various: bump urbit-ob version

- pkg/interface/chat/src/js/components/settings.js
Fixes #2629. When invite search in #2616 was patched in review to not break parity with the other applications, a 'groups' prop needed to be created and passed to it from our permissions; in settings this wasn't created and passed, thus the page crashes for unmanaged group owners. This PR remedies that.
> chat: settings pass 'groups' prop from permissions

- pkg/interface/link/src/js/components/lib/channel-sidebar.js
- pkg/interface/publish/src/js/components/lib/sidebar.js
A syntax typo led the array for grouped notebooks to not have paths
pushed into it. Only the last item in the group would be pushed into the
array. This commit fixes that typo.
-_-;;
Untested, but pretty, pretty sure this is the issue in question. Fixes #2638.
> link, publish: fix sidebar for multi-item groups

- pkg/arvo/app/clock.hoon
- pkg/arvo/app/weather.hoon
In the wild, ships that were live pre-OS1 still had launch subscriptions
open to the clock on the `/tile` path, instead of the currently-used
`/clocktile` path. Additionally, launch state for the clock tile seemed
incomplete.
Here, we simply re-`%add` the clock to launch, during `+on-load`.
Note that launch [currently](https://github.com/urbit/urbit/blob/069ec72f8ad4c834ea5a04aa2749f3d787b87632/pkg/arvo/app/launch.hoon#L110) does not clean up old subscriptions on
path change. For the pre-OS1 case, the old path is no longer in use,
rendering the subscription harmless. For cases where the correct
subscription was already in place, it'll print a %watch-wire-not-unique,
but doesn't do any harm besides that.
I thought I'd just go and fix that launch logic real quick, but it's a bit more …
> clock: ensure launch is listening correctly

- pkg/arvo/app/dojo.hoon
- pkg/arvo/lib/language-server/complete.hoon
Adds autocomplete for
- :app poke syntax
- :app|gen poke generator syntax
- +gen naked generator syntax
- =var variable syntax
Mines generators for their `+help` strings
Demo:
> dojo: add autocomplete for various dojo syntaxes

- pkg/interface/chat/src/js/components/skeleton.js
- pkg/interface/groups/src/js/components/skeleton.js
- pkg/interface/link/src/js/components/skeleton.js
- pkg/interface/publish/src/css/custom.css
- pkg/interface/publish/src/js/components/lib/sidebar-invite.js
- pkg/interface/publish/src/js/components/lib/sidebar.js
- pkg/interface/publish/src/js/components/skeleton.js
The outer borders of OS1 applications were all using `gray2`, a step up from the internal borders of `gray4`, which was distracting and inconsistent. This brings them to a light gray (and `gray1` in dark mode) to match the internal borders.
> os1: skeleton uses b--gray4, not b--gray2

- pkg/interface/chat/src/js/components/lib/header-bar.js
- pkg/interface/groups/src/js/components/lib/header-bar.js
- pkg/interface/link/src/js/components/lib/header-bar.js
- pkg/interface/publish/src/js/components/lib/header-bar.js
- pkg/interface/soto/src/js/components/lib/header-bar.js
Style tweaking in #2615 lacked `white-d` for text in the header, so text in the header shows as black in dark mode. This PR remedies that.
> os1: add dark mode style for app name in headers

- pkg/interface/chat/src/js/components/lib/group-item.js
- pkg/interface/chat/src/js/components/sidebar.js
I'm in so many direct messages that my grouped chats are buried, regardless of filtering down to seeing just them. Realising the error of my ways, this PR repositions the DMs *below* our (potentially filtered down) set of grouped chats.
cc @urcades
> chat: DMs repositioned below grouped chats

- pkg/interface/chat/src/js/components/lib/invite-search.js
- pkg/interface/groups/src/js/components/lib/invite-search.js
- pkg/interface/link/src/js/components/lib/invite-search.js
- pkg/interface/publish/src/js/components/lib/invite-search.js
Fixes #2657. 
By using an array, not a set, we stop deduplicating our group index,
pushing redundant information instead. When searching, this prevents a
component fail state where it cannot search a non-existent index for
matches.
> invite search: avoid crashing with no associations

- bin/solid.pill
- pkg/arvo/gen/hood/gall-sear.hoon
- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/lib/hood/kiln.hoon
- pkg/arvo/sys/vane/gall.hoon
- pkg/arvo/sys/zuse.hoon
See #2485 for context.
When a ship breaches, we remove all messages that have yet to be
delivered to an app (eg if it's not yet started).  We also add
|gall-sear to do this manually, but this shouldn't be needed in normal
operation.
Finally, to unblock ~zod and ~bus on mainnet, we sear one particular
ship automatically on loading hood.  It cannot be done manually because
no userpace changes can be made until it's unblocked.
Tested on a localhost copy of ~bus.
> gall: remove pending messages from breached ship

- pkg/arvo/app/azimuth-tracker.hoon
- pkg/arvo/app/eth-watcher.hoon
- pkg/arvo/app/gaze.hoon
- pkg/arvo/sur/eth-watcher.hoon
Previously, when the refresh-rate timer activated, and the thread from
the previous activation was still running, we would kill it and start
a new one. For low refresh rates, on slower machines, nodes, or network
connections, this could cause the update to never conclude.
Here we add a timeout-time to eth-watcher's `config`. If the refresh-rate
timer activates, and a thread exists, but hasn't been running for at
least the specified timeout-time yet, we simply take no action, and wait
for the next refresh timer.
Note that we opted for "at least timeout-time", instead of killing &
restarting directly after the specified timeout-time has passed, to
avoid having to handle an extra timer flow.
In the `+on-load` logic, we configure the timeout-time for existing
watchdogs as six times the …
> eth-watcher: separate timeout from refresh-rate

- pkg/interface/publish/gulpfile.js
Adds a missing `var` preventing Publish builds from completing when using `gulp bundle-prod`.
> publish: add rollupReplace to gulpfile

- pkg/interface/chat/src/js/components/join.js
- pkg/interface/chat/src/js/components/root.js
Small change, improves perceived performance of join and new chat screen moving to chatroom as soon as chatSynced (%chat-hook property) changes.
> chat-js: transition to new chat upon chatSynced changing in join or new chat screen

- pkg/arvo/app/chat-hook.hoon
- pkg/arvo/app/chat-store.hoon
- pkg/arvo/app/chat-view.hoon
- pkg/arvo/app/contact-hook.hoon
- pkg/arvo/app/group-hook.hoon
- pkg/arvo/app/link-listen-hook.hoon
- pkg/arvo/app/link-proxy-hook.hoon
- pkg/arvo/app/metadata-hook.hoon
- pkg/arvo/app/permission-hook.hoon
- pkg/arvo/app/publish.hoon
For the purposes of more detailed flame graphs when doing Chrome tracing, we added jet hints to most of the networked apps, and to the chat apps. More to come in the next few days.
> apps: added hints to the top of many networked apps

- pkg/arvo/gen/dbug.hoon
This should've been added in #2587.
> dbug: document "all subscriptions" option in gen

- pkg/interface/link/src/js/components/lib/link-detail-preview.js
- pkg/interface/link/src/js/components/lib/link-item.js
Juggling `display: inline-block` and `vertical-align` classes to get the Link info to line up correctly.
Compare before / after:
> link: line up link info on same line height

- pkg/interface/chat/src/js/components/lib/invite-search.js
- pkg/interface/groups/src/js/components/lib/invite-search.js
- pkg/interface/link/src/js/components/lib/invite-search.js
- pkg/interface/publish/src/js/components/lib/invite-search.js
After #2616, an edge case was introduced: 
- After migrating from subscribing to group-store, and passing its groups to invite search, we instead passed the permissions;
- by default, permission-store doesn't retain permissions for groups unless already associated with a channel and subscribed to a channel;
- Occasionally, circumstances require that ships that aren't in any managed channels, create a channel and associate it with a group;
Thus, if you were on a ship that was predominantly infrastructural — that is, not in any channels, but used to just host chats, notebooks, or collections, that belong to a group — the group wouldn't be passed to invite search; thus you couldn't see the groups in invite search; thus could never create those channels.
By instead iterating through …
> invite search: populate group index from contacts

- pkg/arvo/sys/vane/gall.hoon
After a discussion with Ted, I decided to try to remove Ford entirely from the hot-path of chat message sending / receiving to improve performance. Received about a 50% speed improvement for receiving a chat poke, and about a 15% improvement to receiving a chat subscription update from my tests.
Here for review!
Note: This is a hack meant to improve performance until the point at which Ford pinto is ready.
> gall: added hack to reduce processing time for chat messages by 30%

- pkg/interface/chat/src/js/lib/util.js
- pkg/interface/link/src/js/lib/util.js
- pkg/interface/publish/src/js/lib/util.js
Previously we were checking for a title for the association by accessing
a non-existent property of the key we were using to iterate through
the object. What we want to do is access the iterated object to find
that title, and so this commit does that.
Because of this issue, group titles weren't being used to sort groups in all sidebars except Groups (which has a bespoke sort) — it was silently defaulting to the paths, sorting by `@p`.
Fixes #2672.
> various: alphabetise associations accesses the object

- pkg/interface/chat/src/js/components/lib/invite-search.js
- pkg/interface/groups/src/js/components/lib/invite-search.js
- pkg/interface/link/src/js/components/lib/invite-search.js
- pkg/interface/publish/src/js/components/lib/invite-search.js
Allows the user to navigate potential invitees with the arrow keys and
with shift+tab and tab. Enter adds the currently selected invitee. 
Looks like unminified tile js was committed for publish, which would explain the massive diff there. Should I not be minifying? 
> invite-search: allow keyboard nav + selection

- pkg/interface/publish/src/js/components/lib/notebook-posts.js
Runs the snippet through ReactMarkdown instead of rendering it as text.
We restrict the allowed nodes in the render to pure text, so the snippet is not
overly visually heavy. At the moment, any links will be rendered as pure text instead of excluding them. Demo:
> publish: sanitise markdown snippets in preview

- pkg/interface/chat/src/js/components/chat.js
- pkg/interface/chat/src/js/components/join.js
Shows the spinner whilst joining a channel, both manually and from a
url. Also fixes an issue where a newly joined channel may be navigated
away from automatically.
> chat-fe: show spinner on join

- pkg/interface/chat/src/js/components/sidebar.js
Empty groups caused the padding on the first group to be too large.
Filter the groups before we map over them so that we can set padding
properly.
Fixes #2674
> chat-fe: filter empty groups in sidebar

- pkg/interface/publish/src/js/components/lib/new-post.js
Improve the UX of the loading spinner that shows when you have a new
note, by displaying it until we receive the new note in the
subscription, instead of until the poke succeeds.
> publish-fe: improve UX of loading spinner on new note

- pkg/arvo/app/link-listen-hook.hoon
- pkg/arvo/app/link-view.hoon
Instead of auto-watching a new collection when it gets added to group
associations, require that the user explicitly choose to view it.
Of course, creation counts as opting in, so watch the collections we
create by default.
This makes it consistent with chat and publish behavior.
> link: require explicit opt-in for new collections

- pkg/interface/chat/src/js/components/new.js
Fixes #2706. Fixes #2697.
Namespace issues! A common case in our post-groups chat world is the same name for Chats in several groups, eg. "general"; because that gets converted to the same, ASCII-safe path and then redirected if it exists, users couldn't make chats with the same name.
Additionally this meant that if a group owner breached and remade the chat, the two chats with the same path would clobber each other in the sidebar's filter, showing only one.
This PR follows Links' lead for managed chats, adding a few random digits to the path/shortcode for those cases. Because the join flow for managed chats is different from unmanaged chats, we don't really rely on the path to join the group — it's relatively invisible to the user. I may put a PR in to hide the "copy shortcode" prompt …
> chat: add unique ID to grouped chat paths

- pkg/interface/.eslintrc.json
- pkg/interface/CONTRIBUTING.md
- pkg/interface/package-lock.json
- pkg/interface/package.json
Adds `eslint`, `eslint-plugin-react` and `babel-eslint` to the root of `pkg/interface`.
You can find the eslint rules in `pkg/interface/.eslintrc.json`.
As of now, only `interface/launch` has been linted.
If this looks good, I can continue on the other urbit-apps modules.
Resolves #2555.
*Update:*
The .eslintrc.json files is partially inspired by this file https://github.com/handshake-org/hsd/blob/master/.eslintrc.json and airbnb's react eslint settings.
Only linted the `chat` and the `launch` apps. Other apps are untouched for now to prevent an even bigger PR. Have tested building the PR and commiting it to a fake planet, and does seem to work correctly.
No logic should have been touched, only code style should have been changed. All linting has been done manually by using Atom and some …
> interface: add eslint to interface and lint `launch` and `chat`

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/tests/sys/zuse/format.hoon
- pkg/arvo/tests/sys/zuse/html.hoon
This tests enjs:format, dejs:format, dejs-soft:format,
en-json:html, and de-json:html.
These tests currently have some failures because of 3 issues:
1. `at:dejs-soft:format` differs from `at:dejs:format`. `at` is for processing an array into a tuple. The original dejs would crash if the passed in json array wasn't the exact length as your list of item handlers. The one in `dejs-soft` returns nil for a too-short array, but will happily ignore the rest of a too-long array. Should we change it to fail for that case?
2. `de-json:html` is accepting a bunch of invalid number formats that it should be rejecting
3. `de-json:html` doesn't seem to be handling unicode escape sequences properly (`\u12ab`)
> Add unit tests for json de/serialization.

- pkg/arvo/app/publish.hoon
- pkg/arvo/lib/publish.hoon
- pkg/arvo/mar/publish/comment.hoon
- pkg/arvo/sur/publish.hoon
- pkg/interface/publish/src/js/reducers/primary.js
This PR changes publish so that when we make changes, whether its adding, editing, or deleting a post or comment, it will immediately store that upon receiving the poke, even if we are not the host of the notebook, and immediately send that update to the frontend.
If we aren't the host, and our poke to the host crashes, we handle that by either deleting the post/comment in the case of an add, or restoring the old one, in the case of an edit or delete. We also then send the opposite update to the frontend, eg: a delete if it was a failed add, etc.
The frontend reducers for adding notes and comments have been updated to be able to deduplicate updates, since in the normal case the frontend will now receive 2 updates, one pre- and one post-confirmation.
Additionally, this PR contains some …
> publish: eagerly store your own changes

- pkg/interface/chat/src/js/components/lib/invite-search.js
- pkg/interface/groups/src/js/components/lib/invite-search.js
- pkg/interface/link/src/js/components/lib/invite-search.js
- pkg/interface/publish/src/js/components/lib/invite-search.js
Triggers invitee suggestions after one character of input. To
compensate for the potential explosion of suggestions, we
tighten our group searching criteria and truncate the
ship suggestions on short searches. Also addresses a bug where names of
groups were not being downcased before search.
Fixes #2635
> invite-search: handle suggestions for short searches

- pkg/arvo/sys/vane/ford.hoon
Thanks to @belisarius222 for walking me through this. :)
Previous behavior:
```
> +hello 'world'
ford: %hood: syntax error at [12 13] in /~zod/home/0/gen/hello/hoon
ford: %core on /~zod/home/0/gen/hello/hoon failed:
~zod:dojo>
```
New behavior:
```
> +hello 'world'
ford: %hood: syntax error at [12 13] in /~zod/home/0/gen/hello/hoon
(crip (weld \ "hello, " (trip txt)))
------------^
ford: %core on /~zod/home/0/gen/hello/hoon failed:
~zod:dojo> 
```
The last line still reads "backwards" to me; I think it would make more sense at the top. But it wasn't obvious to me how to achieve that, since that line is produced in a separate build step.
> ford: print source line on syntax error

- pkg/arvo/app/launch/js/channel.js
- pkg/interface/chat/src/js/store.js
- pkg/interface/chat/src/js/subscription.js
Figured out that there was an unhandled error condition in Channel.js. Handled it. Tested an implementation within chat where chat can reset itself and re-establish subscriptions in no-connectivity scenarios. It works.
> channel.js: added way to handle event source errors more smoothly, and implemented in chat

- pkg/interface/chat/src/js/components/chat.js
- pkg/interface/chat/src/js/store.js
Previously, if a room was navigated to directly, the resubscribe message
would show before the chatSynced state was loaded. Initialises
chatSynced as null and checks it is not null before showing the
resubscribe message.
> chat-fe: resubscribe message iff chatSynced is populated

- pkg/interface/chat/src/js/components/lib/chat-input.js
Set the line height of the input to be the same as a sent message.
Additionally fixes an issue that would cause unnecessary scrollbars to
be shown.
cc: @matildepark 
demo:
> chat-js: adjust line height in chat input

- pkg/interface/publish/src/css/custom.css
Makes the rules that set both a background and foreground color come
last in the CSS, increasing their specificity. Changes the highlight to a
lighter grey, to better stand out. Correctly aligns highlights with code
block backgrounds.
Demo:
alignment on light mode:
light mode after:
cc: @matildepark 
Fixes #2684
> publish: increase legibility for code in dark mode

- pkg/arvo/lib/dbug.hoon
Previously, if filtering subscriptions turned up no results, nothing was
printed. With this change, we explicitly print "no matching subscriptions"
instead.
Wondering if we should do something to make the result stand out more, too. Since it gets printed _above_ the command in dojo scrollback, people seem to sometimes just miss it.
> dbug: avoid printing nothing at all

- pkg/arvo/app/link-listen-hook.hoon
Automatically leaves a collection when the user is removed from a group.
> link: leave collection on leaving associated group

- pkg/interface/link/src/js/components/root.js
The rightPanelHide prop was being improperly set on the home, settings
and members screens, causing them to be blank on small screen sizes
Fixes #2727
> link-js: fix pages disappearing on small screens

- pkg/arvo/app/chat-hook.hoon
Previously, we were removing the relevant entry from the `synced` map
before calling `+pull-wire`, which requires an entry to still be there.
This lead to subscriptions not actually being pulled, commonly leading
to "subscribe wire not unique" errors on re-join.
In addition to fixing that, `%remove` actions now try to pull the
subscription regardless of whether they have an entry in the `synced`
map or not. `%leave` is always safe, and we might want to clean up
subscriptions that shouldn't be there anymore in the first place.
> chat-hook: on %remove, try our best to pull subs

- pkg/arvo/app/chat-cli.hoon
#2618 changed the way chat-store orders messages. We need to account for that
when processing/printing. This is the minimum viable fix.
@loganallenc I'm 100% sure the inbox _scry_ has the reverse ordering, but the `%messages` update one I'm only 80% sure of. /sur file comments for ordering on these would be a nice aid.
> chat-cli: account for reverse message ordering

- pkg/arvo/app/link-listen-hook.hoon
- pkg/arvo/app/link-view.hoon
- pkg/interface/link/src/js/components/lib/message-screen.js
- pkg/interface/link/src/js/components/links-list.js
- pkg/interface/link/src/js/components/loading.js
- pkg/interface/link/src/js/components/root.js
- pkg/interface/link/src/js/reducers/link-update.js
By doing more or less the same thing that chat does, where it doesn't load in big backlog on page-load, but instead only does so when you actually go to view the resource.
Also does some smaller refactoring things. Cleans up the pagination logic in link-view a little bit, and refactors "message display" as used for the link fe landing page and "loading" messages into its own component.
> link: improve page load performance

- MAINTAINERS.md
Resolves #2735.
/cc @philipcmonk @ixv @joemfb @Fang- 
(A note: in general I don't think that we should change the pill corresponding to a Vere release after making it available, but this does happen from time to time.  In such cases we should just post the appropriate update to urbit-dev.)
> meta: add note re: announcing default pill

- pkg/interface/chat/src/css/custom.css
- pkg/interface/chat/src/js/api.js
- pkg/interface/chat/src/js/components/chat.js
- pkg/interface/chat/src/js/components/lib/unread-notice.js
Adds unread and day indicators. Also changes sending of read receipts to occur when the unread indicator passes the halfway mark of the screen.
cc: @urcades 
Demo:
> chat-fe: add unread and day indicators

- pkg/hs/urbit-king/lib/Urbit/Vere/Ames.hs
- pkg/hs/urbit-king/package.yaml
This is an attempt at fixing #2190 . Since the socket can change between threads, stuff it in a TVar.
I'm not 100% sure that I've thought of everything here, so I'm asking for your advice. Do you think this approach works? Is there a better way to set up the types?
> Make king handle socket exceptions in ames

- pkg/interface/chat/src/js/components/chat.js
- pkg/interface/chat/src/js/components/lib/backlog-element.js
Adds a backlog loading indicator that displays when we have not yet
received the backlog from the host.
Demo:
> chat-fe: add backlog loading indicator

- pkg/interface/publish/src/css/custom.css
Fixes #2773, makes Galen happy.
We set line-height for `ul > li`, but not `ol > li`, so ordered lists had inconsistent line-height.
> publish: change line-height on numbered lists

- pkg/interface/chat/src/js/components/lib/chat-input.js
- After #2756 was merged, if you typed `#`, it would toggle into code mode no matter where you were in your input. We shouldn't eliminate the possibility of using that key in conversation, so we check if there's no input in the editor before toggling modes.
- After that, I auto-linted with our current linter settings (and removed some vars and functions no longer in use that I think were put in during the first go at chat input suggestions).
> chat: toggle 'code' mode only at start of input

- pkg/arvo/app/contact-hook.hoon
- pkg/arvo/app/contact-store.hoon
- pkg/arvo/app/contact-view.hoon
- pkg/arvo/app/group-hook.hoon
- pkg/arvo/lib/contact-json.hoon
- pkg/arvo/mar/contact/hook-update.hoon
- pkg/arvo/sur/contact-hook.hoon
- pkg/interface/groups/src/js/api.js
- pkg/interface/groups/src/js/components/lib/contact-card.js
- pkg/interface/groups/src/js/store.js
- pkg/interface/groups/src/js/subscription.js
- Fixes #2488, Fixes #2696
- Updates subscription.js to do subscriptions in two rounds for performance
- Updates subscription.js to initiate new channel upon event source error.
- Adds a synced path to contact-hook so that we can make a "you lost connection, resubscribe UI element" as a preliminary "workaround" for rejoining a group from a breached ship (need to discuss with @urcades for next steps?)
- Suppresses printing of an error printf that isn't useful but that should happen
> Contacts quality of life fixes

- pkg/arvo/app/chat-hook.hoon
When a group is left, the permissions no longer exist and the mailbox
subscription is kicked. Before attempting to resubscribe, we simply
check if we still have permissions and if not, leave the chat.
> chat: leave chats associated with group on group leave

- pkg/arvo/sys/hoon.hoon
`+sloe`, which lists the arms of a core type, was broken for core types wrapped in a `%hint` tag, producing `~` as though the core had no arms.  This fix unwraps the `%hint` using `+repo:ut`, like everything else.
I think this bug arose because `%hint` was added later, and there was no type error because it was wildcard-matched with a `?+`.  I hope this is the only such case!
> fix +sloe for %hint'ed cores

- pkg/arvo/app/chat-hook.hoon
Fixes variable name mixup causing crash in master. Sorry about this one, I've learnt my lesson with rebasing
> chat-hook: fix variable name

- pkg/interface/chat/src/js/components/lib/chat-input.js
- pkg/interface/chat/src/js/components/lib/member-element.js
- pkg/interface/chat/src/js/components/lib/overlay-sigil.js
- pkg/interface/chat/src/js/components/lib/profile-overlay.js
- pkg/interface/groups/src/js/api.js
- pkg/interface/groups/src/js/components/lib/contact-card.js
- pkg/interface/groups/src/js/components/lib/contact-item.js
- pkg/interface/groups/src/js/components/lib/contact-sidebar.js
- pkg/interface/link/src/js/components/lib/comment-item.js
- pkg/interface/link/src/js/components/lib/comments.js
- pkg/interface/link/src/js/components/lib/link-item.js
- pkg/interface/link/src/js/components/lib/member-element.js
- pkg/interface/link/src/js/components/link.js
- pkg/interface/link/src/js/components/links-list.js
- pkg/interface/link/src/js/lib/util.js
- pkg/interface/publish/src/js/components/lib/comment-item.js
Supersedes #2787.
Adds the display for set avatars in all apps on top of the FE setting of avatars. Tested in unmanaged and managed channels, each with set or unset avatars as applicable, for all apps, and it looks fine.
Lints the files we touch, so sorry for the diff.
> os1: set and show avatars in all apps

- pkg/interface/groups/src/js/components/lib/contact-sidebar.js
- pkg/interface/groups/src/js/components/lib/share-sheet.js
I dropped one case: a lack of avatar prop in the share sheet, which passes to `ContactItem`, resulting in a blank share sheet icon.
> groups: add avatar prop to share sheet

- pkg/interface/chat/src/js/components/lib/chat-input.js
Closes #2795. Replays #2774.
Liam, there seems to have been a regression in chat-input. Compare the extraKeys when I [made this the first time](https://github.com/urbit/urbit/blob/de077ffb4759d31a9eab33d50bba97b046a6ad78/pkg/interface/chat/src/js/components/lib/chat-input.js#L432-L461); somewhere in here there was a patpautocomplete migration out of these extrakeys and into a shipsearch component, and I assume resolving a merge conflict regressed these changes.
> chat: toggle code at start of input

- pkg/interface/chat/src/css/custom.css
- pkg/interface/chat/src/js/components/lib/message.js
Uses overflow: auto on the code attachments so that scrollbars only
appear if the content overflows the container. Adds borders on sent Hoon
code to improve visual separation. 
Demo:
cc: @urcades
> chat-js: only show scrollbars if overflow

- pkg/interface/chat/src/js/components/lib/chat-input.js
Our regex processes true, and sends a message as a URL, if any part of
the string is a URL starting with a URI schema.
We pass this function strings cut up by spaces. If a link was enclosed
in quotes, or in brackets, this would still process as true.
This adds ^ to the regex to only process strings that START with
a schema.
What's the difference? Before, all these have a match somewhere in them, so they get send as URL letters:
After, only the first matches:
Now it gets positives only when it's quite clearly a pasted link.
> chat: strictly match URLs in outgoing strings

- pkg/interface/chat/src/js/components/lib/chat-input.js
Closes #2821.
With our new chat input, we faced a regression in that we don't autofocus the input; this reinstates the old logic, so that mobile devices don't constantly jump to the bottom of the screen, while desktop devices get autofocus.
> chat: autofocus input on desktop

- pkg/interface/chat/src/js/api.js
Closes #2802.
After 1b90328f3950a07882de4141fd274c87cd8b6d58, we fixed the graphic quirk with pending messages rearranging owners of chat messages, by concatenating the message array to the pending array and letting flexbox flop the whole thing. However, since we still `push` pending messages, not `unshift` them, this would reverse them as new ones were added.
This just replaces that one method and restores pending messages being displayed in the right order.
> chat: prepend new pending messages, not append

- pkg/arvo/app/chat-cli.hoon
- pkg/arvo/app/link-proxy-hook.hoon
- pkg/arvo/lib/hood/drum.hoon
Fixes issues related to drum boot ordering
- Changes drum's boot order to be deterministic regardless of the ship
you're on.
- Sorts cli connections so that the user always boots into %dojo
regardless of their @p
Fixes: #2248 #2681
> drum: sane boot order

- pkg/interface/chat/src/js/components/new-dm.js
Creating a new DM might redirect the user to the chat before it is
actually created. Fixed by waiting for confirmation before redirecting.
Fixes #2792
> chat-js: fix race condition in new-dm flow

- pkg/arvo/app/publish.hoon
When we remove metadata for a notebook, if the metadata does not exists, we previously crashed. Now we just no-op. This isn't directly related to any issues seen on the network, but prevented certain recovery tactics I tried to use when fixing ~bitpyx.
In general the publish %warp loop is fragile to these crashes, if you receive an update from clay and crash before you can set the next read, publish will not recover from that. This should be fixed more rigorously at some point. I'm unsure if the answer is to remove all such possible crashes, or to stop using clay entirely, which is why I have only fixed this one case for now.
> publish: allow crash case to no-op instead

- pkg/arvo/app/group-hook.hoon
- pkg/interface/groups/src/js/api.js
- pkg/interface/groups/src/js/components/lib/contact-card.js
Fixes a bug where kicking a member with contact info set would delete the group. Also fixes a bug where a group member leaving would not be propagated to the rest of the group
fixes #2816
> groups: fix self destruct on kick

- pkg/arvo/lib/hood/drum.hoon
If we find an agent that has already been launched then we continue
iterating through the list of apps instead of stopping
Fixes: #2858
> drum: fix broken app start

- pkg/arvo/app/claz.hoon
We were confusing "rate" and "rateUnit". These are "stars per tick" and
"duration of a tick" respectively, not the other way around.
The naming on those, in the contracts, is... not optimal.
(Looking at the logic for `rateUnit` calculation for `+register-conditonal`, maybe that isn't quite right either? Doubt we'll ever use it, but...)
> claz: correct lockup registration arg order

- MAINTAINERS.md
We shouldn't release all changes to the network at the same pace, at least for now.  This is a branching scheme which gives developers more control over when their changes will be released.
> Branching scheme

- pkg/arvo/lib/chat-json.hoon
Bad `@t` text might crash and fully halt the json conversion, preventing any
data from being delivered to the frontend.
Straight-up virtualizing the entire thing feels a bit aggressive, but seems like the safest bet here. Maybe the issue is just in the `%code` `%output` rendering, which calls `+wash`, but this way we don't need to know anything about how _any_ of the `enjs` functions convert to strings.
Targeting master directly, as a proposal to push this out with some priority. The estimated amount of people affected by #2878 (which this fixes) is 20-50, but that number could grow at any time, and the issue's pretty big-impact.
> chat: virtualize message-to-json conversion

- pkg/arvo/sys/vane/gall.hoon
Instead of printing all outgoing subscriptions for the app, only print the
subscription whose wire we're trying to re-use.
In the case of wire re-use, I usually don't care about all those other subscriptions...
(Given this is a kernel PR, and our current OTA strategy around those, this might need to be retargeted at something other than master...)
> gall: smaller %watch-not-unique print

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
Allow zero or one whitespace character before and/or after the equals sign in name attribute pairs, such as `<hello a = "yo" />` or `<hello a= "yo" />`. Following the spec at https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-Eq.
Needed this for my hackathon thing.
> zuse: allow whitespace around = in attr:de-xml:html

- pkg/urbit/include/jets/w.h
- pkg/urbit/jets/tree.c
The C code for +repn was written, but never hooked up.
> jets: hook up preexisting +repn jet.

- pkg/urbit/noun/imprison.c
Restores #2169, targeted appropriately per #2871. Closes #2396.
> Revert "Revert "u3: clear cached mugs on cell edit""

- pkg/arvo/app/publish.hoon
- pkg/arvo/mar/publish/comment.hoon
Introduced by a stupid mistake I made in this PR: https://github.com/urbit/urbit/pull/2707 where I forgot that changes to a mark type definition need to include the old mark type. This should fix this issue: https://github.com/urbit/urbit/issues/2731
I've tested this fix by booting a ship from before #2707, making a notebook with comments, adding the code from #2707 and confirming the reproduction, then copying these changes in.
Apologies to everyone this issue has plagued.
> publish: fix bug in publish comment mark

- pkg/arvo/app/chat-cli.hoon
Allows chat-cli to be `|link`ed to between moons and planets.
The multi-soling here is pretty minimal in that they all share the same configuration (mention `%bel`s, display width, timezone config etc), but that shouldn't make it any less usable. Supporting those properly would be more invasive work that's probably not worth the time right now.
Sorta-but-not-really fixes #2870, by making moons' chat-cli inherit exactly nothing from their planets, making for parity with the web ui.  
Also indirectly closes #1870 and closes #2154 and closes #2167 I guess.
Also makes some smaller improvements:
- No longer hard-crashes on `%bad-text` errors, instead printing a failure message. (fixes #2125)
- Now prints newlines in messages properly.
- Remove entropy from state.
- Allow sending the `•` …
> chat-cli: multi-sole, un-special-case moons

- pkg/arvo/app/publish.hoon
- pkg/arvo/lib/publish.hoon
- pkg/arvo/mar/publish/primary-delta.hoon
- pkg/arvo/sur/publish.hoon
Makes publish abide by namespacing conventions. Some liberties were taken with the structure because publish is not split into the typical triumvirate.
> publish: abide by namespacing conventions

- pkg/urbit/vere/cttp.c
this is more of an issue (and a seemingly failed attempt at patching it)
cttp seems to be incorrectly adding an ampersand to the first url query variable
ex:
```
http://127.0.0.1:23000/rates?currencyPairs=BTC_USD&storeID=examplestore
```
turns into:
```
http://127.0.0.1:23000/rates?&currencyPairs=BTC_USD&storeID=examplestore
```
> cttp: no '&' before first url query var

- pkg/urbit/jets/e/rub.c
This is a very long-standing bug (introduced in ae2f94b01848dd760bb5c912e3010689f4a86d61, which github hilariously attributes to @vvisigoth)  in the jet for `+rub`, which is length-based atom decoding for `+cue` and the inverse of `+mat`.
The implicit coercion from `c3_w` (uint32_t) to `u3_noun` (uint32_t, but ... different) would result in reading random data from the loom, but only when decoding atoms at a position greater than 128MB into a jam buffer. We only recently started jam-ing/cue-ing buffers that big (with the introduction of `|pack`), so this bug was latent until now.
> u3: fixes bug in +rub jet (unsafe coercion from c3_w to noun)

- pkg/urbit/jets/d/by_apt.c
- pkg/urbit/jets/d/in_apt.c
- pkg/urbit/jets/e/scow.c
- pkg/urbit/jets/tree.c
This fixes an off by one error in ship name printing, and disables
the +apt:{by,in} jets. I've tried debugging the +apt jets and am
making no progress other than finding a bug in the recursion; this
isn't enough to get ~marzod to boot, though.
> jets: fix broken jets so ~marzod can boot.

- pkg/arvo/app/publish.hoon
- pkg/arvo/ted/migrate-channels.hoon
- pkg/arvo/ted/migrate-group.hoon
Adds a thread for doing all the pokes necessary to migrate chats/link collections/notebooks to a new group.
> os1: migrate app data to new group

- pkg/arvo/sys/vane/ames.hoon
Ames used to report everything as an alien, even if it was actually known.  This fixes that.
> ames: fix %alien |mass over-reporting

- pkg/urbit/vere/lmdb.c
- pkg/urbit/vere/term.c
This PR fixes two deadlock scenarios having to do with the terminal: pathological `tcsettr()` retry loops, and thread contention over logging to the terminal. These should further ameliorate #1981 (but I can't be sure they'll completely resolve it).
> vere: fix terminal deadlock conditions

- pkg/arvo/mar/publish/info.hoon
If you made a notebook with a `'` in the title or description, the mark wouldn't parse it properly, when converting from `%mime` to `%publish-info`. This fixes that.
> publish: fix publish-info mark quote escaping

- pkg/urbit/noun/manage.c
- pkg/urbit/noun/retrieve.c
Much like #2919, these are some small fixes I had on a long-running branch. PR'ing them now as their individually useful, and I'd like to cut a patch release soon.
> vere: improves jammed state reloading in |pack

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
Allow the exponent token to be 'e' or 'E', allow the explicit sign of '+'.
Following the spec at https://json.org.
Fixes the bug Jose discovered in https://github.com/urbit/urbit/pull/1892#issuecomment-633428939.
Closes #2935.
> zuse: improve json to rn parsing

- pkg/arvo/app/chat-cli.hoon
- pkg/arvo/app/shoe.hoon
- pkg/arvo/lib/shoe.hoon
- pkg/arvo/lib/sole.hoon
In which we invent footwear that's actually comfortable to walk in.
Sole expects applications to do non-trivial logic, but applications often just want to implement some text commands. `/lib/shoe` can take care of that lower-level work.
Wrap as `((shoe command-type) your-agent)`, where `command-type` is the type of CLI commands for your app, and `your-agent` is a standard gall agent, with five extra arms: `+command-parser`, `+tab-list`, `+on-command`, `+on-connect`, and `+on-disconnect`. The extra arms will be called by `/lib/shoe` whenever it needs to deal with sole events.
Further documentation is in the lib itself, and the example `/app/shoe`.
This PR includes a commit for making chat-cli use sole. Modifies existing version upgrade logic instead of creating a new version, since `%2` …
> shoe: console application library

- pkg/arvo/sys/vane/ames.hoon
Otherwise if we end up having multple outstanding timers, they never
coalesce to a single timer.
> ames: don't set new timer if we woke up too early

- bin/solid.pill
- pkg/arvo/sys/vane/behn.hoon
Changes Behn's `.timers` data structure to maintain a queue for each date at which we have timers, preserving insertion order.
> behn: fix bug with timers at same date

- pkg/arvo/app/hood.hoon
Whoops, all updates are relinking dojo/chat-cli.  Not an urgent problem.
> hoon: update on-save

- pkg/arvo/app/publish.hoon
Now when you get kicked, check your local data to find the date of the last update you received and send that with the wire. The other ship, when receiving a watch, if it has a date, will only send back data from after that date.
> publish: send less data on kick/resubscribe

- pkg/arvo/app/hood.hoon
- pkg/arvo/gen/hood/ames-wake.hoon
- pkg/arvo/lib/hood/helm.hoon
- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/sys/zuse.hoon
Somehow we ended up with flows which expected to awaken but did not wake
up.  This was likely caused by the error in r920j OTA, urbit-os-v1.0.18,
insufficiently mitigated in somam, urbit-os-v1.0.19.
This adds a command which ensures that every flow has an active timer.
I expect this to be needed only once, but it's a pretty general tool, so
it's worth keeping.
I've included an unused @t parameter to more easily add simple debug
commands to ames without having to add a new task
Includes #2948 because we don't want to keep reloading hood.  Officially this is considered a "backport" cherry-pick since that has already been merged into a release branch.
> ames: add |ames-wake

- pkg/arvo/sys/vane/behn.hoon
It was throwing away timers sometimes if you cancelled a timer at the
same date as other timers.
> behn: fix +unset-timer

- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/sys/vane/jael.hoon
Still testing, but seems correct so far.  See #2952 for details.  Also copying the description of the first commit:
We inspect the wire of our subscriber to see if we need to produce the
result as a %public-keys or a %boon.  This is bad -- we should proxy the
subscription to avoid this need, but this doesn't make that change yet.
%pubs is an old name that doesn't exist anymore (last existed around
September 2019).  The new version is /public-keys, but it's worked so
far because /public-keys has only one item in the path, so it missed the
conditional.  This commit makes the intent more clear.
The [%a @ @ *] could be just [%a @ *], but I leave it to reduce the
chance of breaking stuff.
> jael: Breach-related fixes

- pkg/interface/dbug/src/js/components/searchable-list.js
includes() only works on strings, but we might pass in other types as keys.
Ames.js hits this, apparently:
https://github.com/urbit/urbit/blob/53b919965f50741cae6d51ccb283f8c9b38e6df3/pkg/interface/dbug/src/js/views/ames.js#L153
causes a `t.key.includes is not a function` error in the SearchableList component.
Observed this when trying to debug someone else's ship, haven't been able to whip up a repro locally. This should do the trick regardless.
> dbug fe: coax searchable list key into string

- pkg/urbit/worker/main.c
`|pack` (added in #1984) only works up to some threshold of memory usage (as currently implemented), so it's unsafe to run automatically. Restoring this kind of automatic memory compaction remains a goal, but it'll require more significant development efforts.
Examples of this problem abound -- #2677 is representative.
> serf: disable automatic |pack

- bin/solid.pill
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/zuse.hoon
See also #2723, which this fixes, for prior commentary.
It's not uncommon for people to run their ships behind a reverse proxy. In that situation, requests to Eyre will always appear to be coming from localhost.
[RFC7239](https://tools.ietf.org/html/rfc7239) describes the Forwarded header, which proxy servers can use to send along the original IP address, among other details.
This PR makes Eyre respect that header if the request came from localhost, updating the `address` associated with the request before further processing.
> eyre: respect "forwarded" header from localhost

- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
Primarily:
- make sure we actually clear expired cookies from state, instead of letting them accrue indefinitely
- extend cookie/session duration on-use in regular HTTP requests; fixes #1617 by virtue of channel acks being PUT requests
See commit messages for more commentary.
Note that this doesn't _explicitly_ fix the symptom mentioned in #1617 where channels stay open even after a session expires. But considering the "extend on ack" nature of the implementation here though, I don't think there's any need to track a `(map session-id channel-id)` for explicit cleanup or anything. RFC though, maybe there's security implications there we want to take care of.
> eyre: augmented cookie handling

- bin/solid.pill
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/interface/dbug/src/js/views/eyre.js
Set up, by default, on /~/logout.
Sending a POST request to this expires the current session and redirects to the login page. If the "all" key is set in the request body, expires all open sessions.
This provides the backend for #2649. @urcades might want to think about integrating these actions into the frontend. For now, I just added a pair of buttons to the debug dashboard.
> eyre: provide logout endpoint

- nix/pkgs/default.nix
- nix/pkgs/libaes_siv/builder.sh
- nix/pkgs/libaes_siv/cross.nix
- nix/pkgs/libaes_siv/default.nix
- nix/pkgs/libaes_siv/release.sh
- nix/pkgs/urbit/default.nix
- nix/pkgs/urbit/release.nix
- nix/pkgs/urbit/shell.nix
- nix/release.nix
- pkg/libaes_siv/COPYING
- pkg/libaes_siv/Makefile
- pkg/libaes_siv/README.md
- pkg/libaes_siv/README.urbit.md
- pkg/libaes_siv/aes_siv.c
- pkg/libaes_siv/aes_siv.h
- pkg/libaes_siv/config.h
- pkg/libaes_siv/shell.nix
- pkg/urbit/configure
- pkg/urbit/include/jets/w.h
- pkg/urbit/include/noun/allocate.h
- pkg/urbit/include/noun/xtract.h
- pkg/urbit/jets/e/aes_ecb.c
- pkg/urbit/jets/e/aes_siv.c
- pkg/urbit/jets/e/ripe.c
- pkg/urbit/jets/tree.c
- pkg/urbit/noun/allocate.c
- pkg/urbit/noun/manage.c
@belisarius222 mentioned that he saw that `+{en,de}:sivc:aes:crypto` were taking a millisecond each and appeared to be unjetted. This vendors libaes_siv and jets the `+{en,de}:siv?:aes:crypto` gates against it.
> Jet AES-SIV mode

- bin/solid.pill
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
Changes the HTTP status code of the redirect that occurs upon a
successful login from 307 to 303. 307 preserves the method of the
original request, so the redirected request is a POST. With the new SPA,
this causes a 404 as app/file-server validates the method of the
request, something that did not happen in earlier versions of landscape.
303 instead changes the method to always produce a GET request.
> eyre: 303 redirect on successful login

- pkg/interface/config/urbitrc-sample
- pkg/interface/config/webpack.dev.js
Fixes an issue where only the first ship would receive the updated files
from webpack. Enables watch mode. If herb is set to true in the urbitrc,
then webpack will commit the desk for each change on every ship.
> interface: improve webpack dev config

- pkg/arvo/app/chat-cli.hoon
- pkg/arvo/app/shoe.hoon
- pkg/arvo/lib/shoe.hoon
Seems generally useful for cli apps wanting to do single-keystroke commands or other "fast cli input" ux. I want this for something I'm working on, and ~litter-wolfur expressed wanting this for their srs app's cli.
The `+command-parser` must now produce both a flag and a command noun.
If the flag is true, instantly runs the command from the noun.
If false, maintains standard behavior and only runs it on-return.
> shoe: optionally auto-run commands on entry

- pkg/arvo/sys/vane/eyre.hoon
If we failed the password check, the login page served to us would never
include any redirect details, even if they were there in the original request.
Now we simply (attempt to) parse out the redirect field a little earlier.
> eyre: don't lose redirect upon failing login

- pkg/urbit/vere/lmdb.c
Many ships have been observed bumping up against the existing mapsize limits.  This results in a Vere crash via LMDB, which necessitates compiling a new binary with a higher mapsize if one wants to relaunch.
There doesn't seem to be any serious penalty to setting this somewhere in the terabyte range, though. In cases where the mapsize exceeds the size of the disk, I infer from the LMDB docs that the database may simply be permitted to grow until it runs up against the
disk limitations, which feels acceptable.
I've tested this on macOS and Linux and the binary runs without issue, despite the mapsize being set far in excess of the disks I'm running on.
Reference: https://lmdb.readthedocs.io/en/release/
> vere: increase LMDB mapsize to 1TB on macOS, linux
