- pkg/arvo/lib/language-server/complete.hoon
As discussed out of band with @liam-fitzgerald. It would search through the current input as a symbol, even if valid completions didn't strictly fit `@tas`.
Here we parse _any_ printable input, and produce `@t` in place of `term` accordingly.
> language-server: parse commands permissively

- pkg/urbit/noun/manage.c
These were useful in #3011, so I figured I'd PR them.  `unused free` is the most important one, maybe should be the only one.  Possibly I'm missing somewhere else where these printfs exist.
> noun: road-size printfs on u3m_fall

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/tests/sys/zuse/crypto/aes.hoon
- pkg/urbit/jets/tree.c
This PR fixes a jet mismatch in our AES-SIV implementations. The mismatch was created by #2902, which added the jets. But the fault was with the pre-existing hoon implementation. The fundamental issue was a mishandling of leading zeros on incremental values in the SIV calculation (`+s2vc:aes:crypto`). I've fixed it, and the 128 and 192 bit varieties in the same manner.
---------------------------------------------------------------------------
The following is a walkthrough of the mismatch itself. @philipcmonk tracked down this test case, and I was able use it find and fix the mismatch.
Here's our inputs, and the correct output, as generated by the jet:
```
> =key 0xfdef.6253.d284.a940.1b5d.d1b7.fbcd.4489.
3071.bf93.ace9.37da.7c5d.77d2.1f3e.cda4.
83be.1c51.a88b.c9ba.8741.e1ee.935b.c0ef. …
```
> zuse: fix jet mismatch in aes-siv

- pkg/arvo/sys/arvo.hoon
- pkg/arvo/sys/hoon.hoon
Adds +mure to run a trap in a separate road.  This should eventually be
just a hint.
Vega was running inside a mule, but since +load was called within vega,
the new kernel was all run within the same mule, so it didn't actually
get to reclaim the space after hoon compiled.
We verified this with printfs in u3m_fall.  On the test ship (from
mainnet) which had 800MB used, vega was taking interior free space from
950MB to 450 over the course of compiling hoon, then each vane would go
from about 450 to 350 and then back to 450 once it finished (which
proves they were correctly isolated).  With this change, after hoon
compiles the free space goes back up to 950MB.  This gives us a lot more
space to compile OTAs.
We had to slightly refactor the logic for doubly-recompiling hoon, since
+mure as …
> arvo: compile hoon/arvo in separate roads

- pkg/arvo/app/chat-hook.hoon
Not sure which branch I should be targeting. Arguably its a hotfix, but @philipcmonk if you're doing a release soon, maybe I should target your branch?
> chat-hook: pull on store path when removing

- pkg/arvo/lib/shoe.hoon
Turns out that having these pop up on every tab-press is really annoying,
and you usually only want them when it didn't manage to autocomplete anything.
> shoe: print tab options less eagerly

- pkg/interface/config/webpack.dev.js
- pkg/interface/src/App.js
- pkg/interface/src/apps/chat/app.js
- pkg/interface/src/apps/chat/components/chat.js
- pkg/interface/src/apps/chat/components/skeleton.js
- pkg/interface/src/apps/chat/css/custom.css
- pkg/interface/src/apps/groups/app.js
- pkg/interface/src/apps/groups/components/lib/group-sidebar.js
- pkg/interface/src/apps/groups/components/skeleton.js
- pkg/interface/src/apps/links/components/skeleton.js
- pkg/interface/src/apps/publish/app.js
- pkg/interface/src/apps/publish/components/skeleton.js
Removes use of vh units, as they don't play well with safari
(https://bugs.webkit.org/show_bug.cgi?id=141832). Adjusts layouts
accordingly. Fixes the bug causing scrolling jank in iOS safari
> various-js: improve scrolling experience on iOS

- pkg/interface/src/apps/groups/components/lib/s3-upload.js
- pkg/interface/src/apps/publish/components/lib/edit-post.js
The component for editing a post was tied up in checking for API
instantiation -- we want the check for a blank body to be independent
of that.
Addresses #3040.
> publish: edit post content no longer tied to api

- pkg/arvo/app/debug/index.html
- pkg/interface/dbug/src/index.js
Landscape rearchitecture removes `window.urb` from userspace. This initiates it as a fresh channel at dbug start.
Partially addresses #3035.
> dbug: init new channel on start

- pkg/arvo/app/dbug.hoon
- pkg/arvo/gen/timers.hoon
- pkg/arvo/sys/arvo.hoon
- pkg/arvo/sys/vane/behn.hoon
- pkg/urbit/vere/io/behn.c
Primarily:
- Rewrites behn.hoon's scry interface to use cares, not misuse the desk, provide more endpoints, and expose ducts only on an explicitly debug-oriented endpoint.
- Rewrites behn.c's "backstop" logic to scry into behn for the next timer instead of setting one for ten minutes into the future. (But still falls back to doing so if the scry doesn't succeed.)
Note that f714d90 touches arvo to make `%$` be considered a valid value for the desk. `+slaw` doesn't parse the empty string as a `%tas`. Arguably that's a bug in `+slaw`, but it's parsing behavior for `%tas` is a bit funky already and I'd rather not make the broader-scope change right now.
@joemfb I made some notes during our call yesterday about some oddities in behn.hoon's implementation, but chose not to do the fixes for …
> behn, vere: some improvements

- nix/pkgs/urbit/default.nix
- nix/pkgs/urbit/libsigsegv_fix.patch
This is a draft PR pending testing stack overflow handling and nix hygiene.  Can someone who knows nix take a look at this?  @brendanhay @eglaysher 
This patches libsigsegv to not check the stack vma on Linux, since that
involves reading procfs, and we make very heavy use of sigsegv.  This
eliminates most of urbit's performance discrepancy between Linux and
MacOS.  These are the benchmarks used; note this is a local MBP vs a
cloud Linux server, and the MBP is almost certainly faster hardware.
We take two benchmarks, one of which decrements 10 million times and the
other simply allocates 125MB of memory.  These are the results:
cpu-heavy ==  =/ n 10.000.000 |-(?~(n n $(n (dec n))))
mem-heavy == =a (bex 1.000.000.008)
macos, cpu-heavy: 6 seconds
macos, mem-heavy: 1 second
linux-before, …
> libsigsegv: disable stack vma check (or: Make Linux Fast)

- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/pier.c
Tries to get a scry result from a /vanecare/desk/path formatted path,
and jams the result to disk (.urb/put/) if it succeeds.
Optionally use -Y to specify a name for the resulting file.
Wrote this as an exercise, but seems potentially useful for getting data out of piers without booting them.
> vere: add -X flag for running a scry

- bin/solid.pill
- pkg/arvo/sys/vane/jael.hoon
Something I noticed recently is that in some cases we don't correctly restart the Jael-to-Jael subscription when the other ship breaches.  For example, if another planet breaches while we were asking for their moon's keys, that subscription will be broken.
This is particularly a problem when you boot a new moon to test software hosted on another moon -- often you don't wait for keys to download, so you hear about any historical breaches by that planet after you started asking for its moon's keys, so you never get to talk to that moon.
> jael: always restart subscription to breached ship

- pkg/interface/config/webpack.prod.js
- `npm run build:prod` outputs in `pkg/arvo/landscape/js` instead of urbitrc
- production builds were failing due to some missing typescript configs, brought the prod config to parity with dev
> interface: update production build for typescript

- pkg/interface/src/apps/chat/components/lib/message.js
> chat fe: don't embed webms as images

- pkg/arvo/app/hood.hoon
- pkg/arvo/gen/trouble.hoon
- pkg/arvo/lib/hood/kiln.hoon
- pkg/arvo/sys/vane/clay.hoon
Produces conflict list on mate-conflict, and also makes +trouble look at where we're actually getting OTAs from instead of guessing that it's our parent.  This still crashes if you haven't received any clay updates from them.
> kiln: Small fixes

- pkg/interface/src/apps/chat/components/lib/overlay-sigil.js
Changes the sigil overlay to only start checking for its position when it
becomes visible.
Fixes: #3055
> chat: fix sigil overlay perf issue

- bin/solid.pill
- pkg/arvo/app/chat-store.hoon
#3083 removed auto-trimming when receiving individual messages, but didn't touch the `%messages` case.
It's... not nice that there's duplicate logic for `%message` and `%messages`, but that's probably out of scope here.
(Targetting master, maybe we want to push this out as a hotfix.)
> chat-store: don't trim on %messages, either

- pkg/urbit/vere/http.c
Not touching the proxy message because that seems gone on ipc-redux.
Fixes #1332 in the dumbest way.
```
http: web interface live on http://localhost:8081
http: loopback live on http://localhost:12322
```
> vere: more readable http server status

- pkg/interface/src/components/GroupFilter.js
See #3096 for details on the issue. 
During the migration to global store (#3038), the API became
structured such that you must specify the local (app-specific) API.
Some cases were missed. This includes them.
> group-filter: specify local api for all cases

- pkg/arvo/app/dojo.hoon
Particularly useful in cases where there is no trace, for example if you
simply execute `!!` or `_!! 5`.
> dojo: add tags to identify errors

- pkg/arvo/app/file-server.hoon
We probably shouldn't be eating these without telling the user/developer.
Ideally you want to just nack the poke that configures this, but that's less trivial. You could scry into eyre to find out if the binding will succeed or not, I guess?
> file-server: print a warning when binding fails

- pkg/arvo/sys/zuse.hoon
Both +drop-list and +drop-map produce units instead of crashing. This makes
+drop-pole match that behavior, producing a unit of the resulting tuple.
`+drop-pole` isn't currently used anywhere, but I happened to need this version of it. If anything does still want to use the crashing version for some reason, they can `need-pole:drop-pole` or just, you know, `(need (drop-pole x))`.
> zuse: make +drop-pole produce a unit

- pkg/arvo/app/chat-cli.hoon
Describe the bug
In chat-cli, seem like the command tab completion triggers without the necessary prefix char (; in chat-cli) but not with it.
To Reproduce
Hit tab at a clear prompt in chat-cli, see completions for ; commands. Enter ; and hit tab, no more completions.
Expected behaviour
Should see completions after ;
Notify maintainers
@Fang-
> tab completion in chat-cli completes without prefix char

- pkg/arvo/sys/vane/eyre.hoon
In replicating a mockup, the residual 'version' for OS1 has overstayed its welcome as a stub on the login screen. This commit removes it.
Part 1 of some work toward #2699. @Fang- advised that the base hash should really be on the Landscape homepage instead in some way, and I agree.
cc @urcades
> eyre: remove stubbed version text

- pkg/interface/src/apps/chat/components/chat.tsx
- pkg/interface/src/apps/chat/components/lib/profile-overlay.js
See the request in #2623.
Also discovered and fixed a bug where we were passing `props.association` as `props.group` to the Message component, which passes that all the way down through `OverlaySigil` and `ProfileOverlay`, so the conditional check for hidden group was just silently producing `undefined` while there was no association prop to check, causing crashes on `ProfileOverlay` render.
> chat: profile overlay links to group profile

- pkg/arvo/app/weather.hoon
Because we nest data in a weather key and save that
in app state, we don't need to nest the data in weather twice over when
giving initial data to new subscribers.
(Thanks to @Fang- who basically wrote this within 10 seconds once I pointed out what I suspected the problem was ... tested it on fakezod in both subscribe / on-poke cases and it indeed corrects the issue.)
> weather: don't double-nest json on-watch

- pkg/interface/src/apps/chat/app.tsx
- pkg/interface/src/apps/chat/components/chat.tsx
- Fixes key issues which may be the cause of certain double renders
- Checks for an association before reporting unread in titlebar
> chat-js: unread counts sweep

- pkg/arvo/ted/build-cast.hoon
- pkg/arvo/ted/build-file.hoon
- pkg/arvo/ted/build-mark.hoon
Take a full beam in `-build-file`, `-build-cast`, and `-build-mark` threads so that they can run Ford builds from any desk.
They're now callable from dojo like this:
```
=f -build-file %/lib/sole/hoon
=c -build-cast /=work=/mime/txt
=m -build-mark %/mime
```
> -build-{cast,file,mark}: accept full beams; load from any desk

- pkg/interface/CONTRIBUTING.md
- pkg/interface/config/urbitrc-sample
- pkg/interface/config/webpack.dev.js
- pkg/interface/package-lock.json
- pkg/interface/package.json
- pkg/interface/src/App.js
Adds HMR to the hot reloading config. JS changes no longer require a refresh and appear instantly after the compilation has finished.
Bonus round: you can point `URL` at your own planet to test JS changes there.
> interface: add HMR to hot reloading config

- pkg/arvo/app/file-server.hoon
- pkg/arvo/app/hood.hoon
- pkg/arvo/mar/hash.hoon
- pkg/interface/src/App.js
- pkg/interface/src/api/base.ts
- pkg/interface/src/api/local.ts
- pkg/interface/src/apps/launch/app.js
- pkg/interface/src/components/StatusBar.js
- pkg/interface/src/reducers/local.ts
- pkg/interface/src/store/store.ts
- pkg/interface/src/store/type.ts
- pkg/interface/src/types/local-update.ts
Makes the base desk hash accessible through scry and then shows it in the status bar. Unfortunately, we can't scry this in the login page because we don't yet have a session to do scries with. 
Preview (see dhk61 in top right):
> interface: show base hash

- pkg/interface/CONTRIBUTING.md
- pkg/interface/config/urbitrc-sample
- pkg/interface/config/webpack.dev.js
- pkg/interface/package-lock.json
- pkg/interface/package.json
- pkg/interface/src/App.js
Currently our Landscape build process relies on autocommitting with herb, or committing to your ship manually each time you make a change:
- You run `npm run build:dev`
- It compiles and copies the JS binary into your ship's pier
- You commit the new JS blob
- You shift-refresh the page so it isn't cached.
This PR amends this flow; you now run `npm run start` to start a webpack-dev-server. 
When you make changes to your source code, the index.js binary has hot reload enabled, and thus, refreshes the page for you. No further work necessary.
When you're actually shipping code, `npm run build:prod` continues to output the binary in `pkg/arvo`.
> interface: add hot reload, dev server

- pkg/interface/src/App.js
- pkg/interface/src/apps/chat/components/lib/channel-item.js
- pkg/interface/src/apps/chat/components/lib/chat-tabbar.js
- pkg/interface/src/apps/chat/components/sidebar.js
- pkg/interface/src/apps/launch/app.js
- pkg/interface/src/apps/publish/components/lib/notebook.js
- pkg/interface/src/components/SidebarSwitch.js
Setting a line-height across the board of 1.5 was patched during SPA development with a few padding tweaks here and there; but in general we decided to just restore the inconsistent line-height we had before and set a consistent line-height during the Indigo refactor work in progress in FE.
> spa: restore previous line-height, padding

- pkg/interface/src/apps/chat/app.tsx
- pkg/interface/src/apps/chat/components/join.js
- pkg/interface/src/apps/chat/components/lib/channel-item.js
- pkg/interface/src/apps/chat/components/lib/group-item.js
- pkg/interface/src/apps/chat/components/lib/message.js
- pkg/interface/src/apps/chat/components/new-dm.js
- pkg/interface/src/apps/chat/components/new.js
- pkg/interface/src/apps/chat/components/settings.js
- pkg/interface/src/apps/chat/components/sidebar.js
- pkg/interface/src/apps/groups/app.tsx
- pkg/interface/src/apps/groups/components/join.js
- pkg/interface/src/apps/groups/components/lib/group-detail.js
- pkg/interface/src/apps/launch/components/welcome.js
- pkg/interface/src/apps/links/components/new.js
- pkg/interface/src/apps/publish/components/lib/new.js
- pkg/interface/src/apps/publish/components/lib/settings.js
- pkg/interface/src/apps/publish/components/lib/sidebar.js
- pkg/interface/src/components/InviteSearch.tsx
- Fixes a bug where invite search would return valid patps regardless of what `shipResults` was set to.
- Fixes a bug where Groups autojoin wasn't receiving props from the route and still had some cruft from its Publish scaffolding code.
- Drastically simplifies new Chat flows — 'New Chat' requires a group and links to Groups to create new ones; 'New DM' adds the ability to name and create group DMs and is graphically separated in the sidebar.
- Removes "Create group" toggle from all "New..." flows.
- Adds "Create group" link to Groups above the Invite Search input on New screens.
- Removes "Join [chat,notebook]" from sidebars.
- Removes shortcode references from Chat and Publish.
- Adds a link to join Urbit Community directly from the Launch welcome message.
- Restores shortcode links in …
> interface: UX renovations for new groups

- pkg/urbit/noun/retrieve.c
We were unconditionally adding equal items to the hashtable of
already-compared pointers.  This table exists so that if we've already
determined two non-pointer-equal nouns are value-equal, we don't have to
check them again.  However, atoms (especially direct) ended up in this
hashtable even though we don't look those up.  This makes sure we don't
add items to the hashtable if they're "pointer"-equal (which for direct
atoms is value-equal).
The impact of this inefficiency was greatly magnified by the issue with
+mug where (mug a a) = (mug b b) for all a, b.  For this reason, these
identical pairs added to the hashtable always had the same mug, so they
were added to the same bucket, which meant adding to that list required
linearly traversing the entire bucket.
This was the first barrier …
> noun: don't add identical values to _song_x_cape's hashtable

- pkg/arvo/sys/zuse.hoon
Trying to deal with http requests sent by an external application. Its requests weren't getting passed to the correct handler (an app), instead redirecting to login page.
Turns out the URL of the request contained a `)` in a query parameter, and this was tripping our parser up.
One class of characters allowed in URIs are "unreserved" characters. [RFC2396 defines](https://tools.ietf.org/html/rfc2396#appendix-A) unreserved characters as alphanumerics and nine "mark" characters. We were only parsing for four of those, missing `)` among others, leading to parsing failure for valid URLs.
Before:
```hoon
> (de-purl:html 'http://localhost/some?thing=or)&other=!')
~
```
After
```hoon
> (de-purl:html 'http://localhost/some?thing=or)&other=!')
[ ~
[ p=[p=%.n q=~ r=[%.y p=<|localhost|>]]
q=[p=~ …
```
> zuse: parse rfc2396 unreserved chars correctly

- pkg/urbit/configure
- pkg/urbit/noun/events.c
- pkg/urbit/noun/trace.c
- pkg/urbit/vere/io/cttp.c
- pkg/urbit/vere/io/unix.c
- pkg/urbit/vere/walk.c
- pkg/urbit/worker/serf.c
This ports #2991 to ipc-redux (minus the currently-impractical upgrade of nixpkgs), and fixes a couple additional warnings that showed up in CI.
@brendanhay, can you confirm this works in your environment?
> vere: fix warnings flagged by gcc 8

- pkg/arvo/app/landscape/js/channel.js
- pkg/interface/src/App.js
- pkg/interface/src/components/StatusBar.js
- pkg/interface/src/reducers/connection.ts
- pkg/interface/src/store/store.ts
- pkg/interface/src/store/type.ts
- pkg/interface/src/subscription/base.ts
- pkg/interface/src/subscription/global.ts
- pkg/interface/src/types/cage.ts
- pkg/interface/src/types/connection.ts
- Shows a connection status indicator in the status bar
- If the reconnection times out and enters the 'Disconnected' state, then the indicator can be clicked to manually reconnect
- Fixes a bug in the reconnect logic where app-specific subscriptions were not re-established.
cc: @urcades 
[demo](https://ewr1.vultrobjects.com/urbit/disconnect.mov)
> interface: show connection status indicator

- pkg/interface/src/apps/groups/components/lib/group-detail.js
- pkg/interface/src/apps/launch/app.js
If I can squeeze these in here I'd like to — 
- base hash uses `mono`
- group-detail has a correction for the line-height of its items
> interface: two design tweaks

- pkg/hs/urbit-king/lib/Urbit/Vere/Serf/IPC.hs
- pkg/urbit/include/c/motes.h
- pkg/urbit/include/vere/serf.h
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/lord.c
- pkg/urbit/vere/pier.c
- pkg/urbit/worker/main.c
- pkg/urbit/worker/serf.c
This PR further integrates #3099, using it as the implementation of `|pack`, addition it to the king/serf protocol, and restoring autopack due to memory pressure.
Additionally, these changes include explicit subcommands for the urbit-worker process, to further support manual inspection and pier recovery:
```
$ ./build/urbit-worker 
urbit-worker usage:
print pier info:
./build/urbit-worker info <pier>
gc persistent state:
./build/urbit-worker grab <pier>
compact persistent state:
./build/urbit-worker pack <pier>
jam persistent state:
./build/urbit-worker cram <pier>
cue persistent state:
./build/urbit-worker queu <pier> <at-event>
run as a 'serf':
./build/urbit-worker serf <pier> <key> <flags> <cache-size> <at-event>
```
This PR does not yet include changes to the new compaction …
> vere: integrate new memory compaction

- pkg/interface/config/webpack.dev.js
- pkg/interface/config/webpack.prod.js
- pkg/interface/package-lock.json
- pkg/interface/package.json
See #3132. Prior to this, we hit errors due to Babel not being able to transform async functions for browsers.
> interface: add babel-transform-runtime

- pkg/interface/src/apps/launch/components/tiles/clock.js
The clock renders the sun+moon before rendering the part of the image for the night section.
This ends up hiding the moon behind the night part of the image.
Layer the sun+moon after the night section to make the moon visible during night time.
> landscape clock: render sun+moon after night

- pkg/arvo/sys/vane/behn.hoon
- pkg/arvo/sys/vane/gall.hoon
- pkg/arvo/sys/zuse.hoon
This fixes https://github.com/urbit/urbit/issues/3102 by modifying Behn's `%huck` facility to accept and produce a `$sign-arvo` directly instead of using Arvo's meta-vase reduction.
This has the potential downside that Behn's `$task` now depends on `$sign-arvo`.  I'm not aware of any immediate problems from doing that, but maybe it could make future Zuse changes more difficult somehow, so I'm flagging it here.
I have tested `|reset` but not the other use of `%huck` in Gall.  I also confirmed that after applying this fix, changing Zuse still causes a successful `+molt`.
> zuse,behn,gall: fix %huck and |reset

- pkg/arvo/gen/hood/ota.hoon
- pkg/arvo/lib/hood/kiln.hoon
Instead of `|ota` cancel the OTA, make it show the current setting.
Make the cancel need a more explicit argument.
```
|ota                 shows the current setting
|ota disable         disable OTA
|ota ~sponsor %desk  reset to a different sponsor/desk
```
Because most of the time the expected desk is going to be %kids, use
that in the "help message".
> ota: show information instead of disable by default

- MAINTAINERS.md
Still mentions `%base` desks, and apparently we manually merge into `%kids` now?
> MAINTAINERS: amend for post-fusion

- pkg/urbit/include/noun/allocate.h
- pkg/urbit/include/noun/jets.h
- pkg/urbit/include/noun/manage.h
- pkg/urbit/include/noun/nock.h
- pkg/urbit/include/noun/vortex.h
- pkg/urbit/noun/allocate.c
- pkg/urbit/noun/jets.c
- pkg/urbit/noun/manage.c
- pkg/urbit/noun/nock.c
- pkg/urbit/noun/vortex.c
- pkg/urbit/worker/main.c
- pkg/urbit/worker/serf.c
This PR moves `u3a_compact()` to `u3m_pack()`, factors out its internal operations, and makes a fair bit of progress towards generalizing the implementation across north/south roads.
The missing generalized operations are the `u3a_rewrit*` functions used in the ad-hoc tracing step. I started new implementations, but there's still a ways to go. These changes aren't important enough to block #3099 and #3064, so I'm PR'ing what I have now -- further improvements will come later.
My main goal in this work was to better understand the implementation. To that end, I rewrote the two sweeping traversals to be more similar to each other, then generalized them across roads. In a north road, new locations are stored in the trailing size word as before; in a south road, they're stored in the leading …
> vere: refactors new memory compaction

- pkg/hs/urbit-king/lib/Urbit/Vere/Ames.hs
- pkg/hs/urbit-king/test/AmesTests.hs
The C king already provides this behavior, which is necessary to prevent OOMs on highly trafficked infra ships.
> king: drop ames packets when >1k are unprocessed

- nix/nixcrpkgs/pkgs.nix
- pkg/hs/urbit-king/lib/Urbit/Vere/Serf/IPC.hs
- pkg/urbit/include/c/motes.h
- pkg/urbit/include/noun/allocate.h
- pkg/urbit/include/noun/hashtable.h
- pkg/urbit/include/noun/jets.h
- pkg/urbit/include/noun/manage.h
- pkg/urbit/include/noun/nock.h
- pkg/urbit/include/noun/vortex.h
- pkg/urbit/include/vere/serf.h
- pkg/urbit/include/vere/vere.h
- pkg/urbit/noun/allocate.c
- pkg/urbit/noun/events.c
- pkg/urbit/noun/hashtable.c
- pkg/urbit/noun/jets.c
- pkg/urbit/noun/manage.c
- pkg/urbit/noun/nock.c
- pkg/urbit/noun/vortex.c
- pkg/urbit/vere/lord.c
- pkg/urbit/vere/pier.c
- pkg/urbit/worker/main.c
- pkg/urbit/worker/serf.c
This compacts memory on the home road, allowing you to reclaim contiguous free space.
Read [this](https://github.com/urbit/urbit/blob/69f8602e55c9467f6a8b714af5cd9ecd7224eb04/doc/spec/u3.md) if you're interested in the basics of how our memory allocator works.  Importantly, while you can free memory on the home road (permament memory, vs inner roads which exist and are freed during an event), it's unlikely to be at the edge of the heap, so you end up with framgented memory.  Processing events happen in inner roads, which only exist in the contigous free space between the home road's stack and heap.
Some ships end up with badly fragmented home road heaps, such that most of their loom is unusable.  |pack solves this by serializing, deduplicating, and deserializing, but it's quite slow, …
> Memory compaction

- pkg/arvo/app/file-server.hoon
See #3159. Maintains parity with +trouble, tested by booting a fake ~zod and a fake ~marzod.
> file-server: fix base-hash trimming

- pkg/interface/src/apps/groups/components/join.js
In #3133 I added a "fix" for groups autojoin to wait for first data load, in the case where you went *directly* to the join route without any data in state.
We want to avoid sending a join if we're already in UC.
Instead, that fix prohibited most of the use cases it was written for — because users, on first boot, *have* data instantiated and use the link in the welcome CTA to join UC. Because `prevProps.groups` and `props.groups` stay identical in the "I'm in no groups case" *and* in the "I'm using `<Link>` to come here" case, linkified joins to groups never work.
In this commit, we instead look for `props.contacts && Object.keys(props.contacts).length > 0` — contacts is the only data we have that is guaranteed to go from "empty" to "has an entry" from first boot; so, all in all, it's our …
> groups: fix autojoin on first boot case

- pkg/arvo/app/metadata-store.hoon
should resolve the failure to process the most recent OTA on ~bitbet-bolbel. The path is malformed on ~bitbet because of what i assume to be migration jank. However, ships other than ~bitbet have reported the OTA failing and so I'm drafting this PR until I can confirm that we can safely discard that metadata.
> metadata-store,hook: ignore bad paths in on-load

- pkg/interface/src/apps/chat/components/settings.js
- pkg/interface/src/apps/groups/components/lib/group-detail.js
- pkg/interface/src/apps/groups/components/new.tsx
- pkg/interface/src/apps/publish/components/lib/settings.js
- pkg/interface/src/components/toggle.js
- pkg/interface/src/reducers/group-update.ts
- Fixed a latent bug where only the group's owner could change group settings, regardless of roles. Now any admin can change settings (given this pokes *our* ship, does this propagate?)
- Makes the "toggler" checkbox type into a common component and dedupes its use in the codebase. cc @g-a-v-i-n 
- Adds UI for toggling the group's privacy policy, as well as some reducer behaviour for the new policy.
> groups: add private group toggle

- pkg/arvo/gen/hood/moon-cycle-keys.hoon
We were sending the correct life to Jael, but the ticket we printed had
the life hardcoded to 1.  This makes it use the correct life in both
places.
> moon: print key with correct life

- pkg/arvo/sys/vane/gall.hoon
In +mo-subscribe-to-agent-builds we subscribe to `%a` on all our apps to get updates when they change, but we also subscribe to `%z` on hoon/arvo/zuse/gall so that even if no built app changes, we'll still get a ping from clay, so we'll molt.
This change makes it so that if for some reason we get a `%z` response at another time, we ignore it.  ~dev ran into this bug, and this change fixed it.
Tagging @Fang- since Ted's out.
> clay: ignore extraneous /sys/lyv results

- pkg/arvo/lib/hood/kiln.hoon
This causes new ships to get a `%merge-no-merge-base` error after downloading the initial ota while merging into their own kids desk.  Not that big a deal since it merges correctly into their home desk.  For anyone who runs into this, you can workaround by manually running `|merge %kids (sein:title our now our) %kids, =gem %that`.
> kiln: get germ for actual desk

- pkg/arvo/gen/timers.hoon
+en-beam expects a spur, reversing it for the final path rendering.
> gen: use spur in +timers

- pkg/interface/src/apps/publish/app.js
Due to a change in a local variable named 'props' we overwrote the only
thing that used the props variable to pass itself to a child -- invites.
This commit deconstructs 'invites' alongside other properties from
the global store.
Fixes cases where you invite anyone to an unmanaged notebook and invites never show up.
Tested on ~dabben, works.
> publish: pass invites as prop correctly

- pkg/interface/src/apps/chat/components/chat.tsx
- pkg/interface/src/apps/chat/components/lib/chat-input.js
Previous behavior:
1. Type message in chat without submitting it
2. Navigate to other chat
3. Navigate back
4. Message has been cleared
New behavior: message is not cleared. This matches the behavior of Discord, Slack, etc.
> chat-js: save unsent message for each station

- pkg/arvo/app/chat-cli.hoon
Fixes chat creation through chat-cli, and allows users to associate new chats with groups
> chat-cli: revive chat creation and add group association

- pkg/arvo/sys/hoon.hoon
The tiki expansion for `?=` assumed that the case was in axis 3, but this is only true for "named wings," which are factored out into a `=+`. For "simple wings," `?=` can operate on the wing directly, so there's no need for an `%over` at all.
Previous behavior:
```
> =a ?(%foo)
> =b %foo
> ?=(a b)
-find.a
```
New behavior:
```
> =a ?(%foo)
> =b %foo
> ?=(a b)
%.y
```
(I'm kind of surprised this went unnoticed for so long...? This seems like it would break a lot of code.)
(EDIT: I'm no longer surprised. Even with this bug, `?=` will work fine as long as the wing can be found in `+3`, which is pretty much always the case.)
Initially reported here: https://groups.google.com/a/urbit.org/forum/#!topic/dev/IZJVJN7-PYY
> hoon: fix wtts axis for simple wings

- pkg/arvo/app/metadata-store.hoon
- pkg/arvo/app/publish.hoon
Fixes the following issues
- stops leaving/deleting a group associated with a notebook just because you left the notebook
- stops publish from telling your group-pull-hook to subscribe to your group-hook, which causes an infinite loop
- sets group tags for notebooks to allow multiple writers, which fixes the disappearance of the "new post" button
> publish: fix issues with new groups

- pkg/urbit/configure
- pkg/urbit/vere/disk.c
Adds aarch64 lines to `pkg/urbit/configure` and defines a new macro, `U3_CPU_aarch64`.
That macro is used in `pkg/urbit/vere/disk.c` to change the lmdb mapsize from 1TB to 60GB for aarch64 on linux, which was the previous (working) behavior #3014 
This fixes a problem with the mapsize on aarch64, tangentially discussed in #3173 
Uses #if defined instead of #ifdef in anticipation of macos on aarch64 being a thing before the end of the year.
@joemfb
> vere: change lmdb mapsize for aarch64

- pkg/urbit/vere/db/lmdb.c
- pkg/urbit/vere/disk.c
- pkg/urbit/vere/pier.c
The error printfs in the database weren't all properly formatted, and top-level initialization failure was not being handled (resulting in a segmentation fault, as opposed to an error message and `exit(1);`).
/cc @botter-nidnul
> vere: cleans up handling of fatal db errors

- pkg/interface/src/apps/groups/components/join.js
The vertical overflow on this box has always bugged me. I assume you didn't make it an `<input />` because you wanted the scrollability. If 'nowrap' is set, 'overflow-y-hidden' follows naturally...right?
> Hid vertical overflow on group join box

- nix/nixcrpkgs/pkgs/libsigsegv/builder.sh
- nix/pkgs/urbit/libsigsegv_fix.patch
Adds the equivalent arm patches to the i386 patches added in #3054
These result in a dramatic speedup in running  `=a (bex 1.000.000.000)` just as they do on x86_x64
This also sneaks in a hack to `/nix/nixcrpkgs/pkgs/libsigsegv/builder.sh` that allows libsigsegv to configure itself properly when cross compiling release binaries from x86_64 to aarch64.
It won’t trigger for you, since you’re not doing that (yet) but it will make it a little easier for me to maintain my aarch64 static release binaries if that `if [ $host = aarch64-linux-musleabi ]` section is upstreamed.
@philipcmonk
> libsigsegv: disable stack vma check on arm

- pkg/interface/src/apps/groups/components/lib/contact-sidebar.tsx
Check for our role in the group instead of checking the path, in order to check whether we should allow the user to attempt to invite members to the group.
> groups: admins and mods can invite users

- pkg/arvo/app/chat-hook.hoon
The previous fix assumed that unmanaged chats are prepending with sig, which is no longer the case. Unfortunately, this means we can no longer reliably disambiguate unmanaged chats from managed ones. Instead, we check for `dm--` prefix. This has the potential risk of returning false negatives.
> chat-hook: identify DMs correctly

- pkg/interface/src/components/Group.tsx
Fixes #3220 and an uncaught bug (`roleForShip` doesn't take `Patp`, it takes `PatpNoSig`)
This doesn't allow moderators to ban users but at the moment that is isomorphic with the back end
> Interface: Only allow admins to ban people

- pkg/interface/src/apps/chat/components/lib/chat-input.js
This works, but someone might want to check my math, so to speak.
There are two problems being fixed here:
One, the code split on spaces, which caused problems if a URL was followed by a newline
Two, the parser didn't check if we were in a codeblock. This is sort of a lame procedural method but it gets the job done
> Interface: Fixes #3195 URL message parsing

- pkg/arvo/sys/vane/ames.hoon
We used to not accept new indirect lanes if we already have a direct
lane.  This means that if Bob, with a publicly-accessible lane, changes
lanes (eg by restarting the process and getting a new port or changing
ip addresses), tries to talk to Alice, who is behind a NAT, then Bob
will try directly but fail (because Alice is behind a NAT), so he will
route the message through her galaxy.  This is good -- the message gets
to Alice.  However, Alice had a direct route to Bob's old lane, so she
will try to ack on that lane, which fails.  She will not time out this
lane because she doesn't know that Bob isn't getting the acks (acks
don't have their own acks).
The solution is that if Alice receives an indirect lane for Bob when she
already has a direct lane, she shouldn't ignore it.  If the lane …
> ames: fix lane discovery during some lane changes

- pkg/interface/src/apps/chat/components/lib/message.js
- pkg/interface/src/apps/chat/components/lib/profile-overlay.js
- Prevents overlay panel from expanding beyond 160px, truncates long nicknames
- Messages truncate nicknames beyond `mw5`, which still allows for moderately long names without creating too much overflow.
> chat: truncate long nicknames

- pkg/interface/src/apps/publish/components/lib/new.js
As of groups refactor you set writers separately instead of allowing everyone in a group to read and write to a notebook. The "new notebook" copy hasn't been amended, so this amends the copy to reflect that.
> publish: amend 'new' copy for new UX

- pkg/interface/package-lock.json
- pkg/interface/package.json
- pkg/interface/src/apps/groups/components/lib/contact-sidebar.tsx
- pkg/interface/src/components/Group.tsx
This uses `react-window`, which is a minimal rewrite of `react-virtualized` mentioned by @galenwp  in #2983.
Basically it combines the "members" and "contacts" into an array, and given an index, either returns members first or contacts if it's shown all the members.
It's not pretty but...it works?
> Interface: Add smart scrolling to group member list

- pkg/interface/src/apps/publish/components/lib/notebook.js
does what it says on the tin. the group is only missing because we haven't loaded it yet i.e. creating a new unmanaged notebook.
> publish-js: account for missing group

- .github/ISSUE_TEMPLATE/kernel-or-runtime-bug-report.md
- .github/ISSUE_TEMPLATE/os1-bug-report.md
Changes with Ford Fusion make `.^(@uv %cz /=base=)` no longer a good way to check the base hash. 
I changed the issue templates to ask users to use `+trouble` to find their base hashes instead.
> ISSUE_TEMPLATEs: use +trouble instead of .^(@uv %cz /=base=)

- pkg/interface/src/apps/chat/components/lib/message.js
#3226 caused the name line-height to be severely skewed due to `inline-block`ing and truncating the name (previously it was `inline`). Treating the span as a `block` not an `inline-block` standardises the line-height without any change to layout. Still preserves the truncation, too. I'm honestly not sure why the box model works that way.
Tested and works in Safari, Firefox, Brave.
> chat: names use db, not dib

- pkg/interface/src/apps/publish/components/lib/note.js
- pkg/interface/src/apps/publish/components/lib/notebook-posts.js
A bandaid for the @galenwp in the audience.
During the SPA refactor we did a rather large renovation of the Publish back-end / front-end interaction pattern. It worked via API calls on navigation instead of the PHP-style state injection. I wrote the logic to pre-empt sending read actions before we knew what we were looking at, by ensuring we had state instantiated first. Here I did so clumsily, so that reads would never send. My bad.
I also went ahead and decided to follow Links in how it marks "unread content": unread posts now have their dates written in green. No "mark all as read" button yet (we'll have to do [something like this](https://github.com/urbit/urbit/blob/master/pkg/interface/src/apps/dojo/components/input.js#L90-L99) where we reduce an array of notes with Promises, waiting …
> publish: send reads on nav, distinguish unreads

- pkg/interface/src/components/OmniboxResult.js
- pkg/interface/src/lib/omnibox.js
- If you had many results (eg. typing 'book' or 'chat' will generally show all notebooks and chats), scrolling with your arrow keys would ... scroll offscreen. We now push offscreen results into view as you scroll up or down, as you'd expect.
- Groups is not in Launch; thus it's not indexed as an app. This adds Groups to the index manually.
> omnibox: two UX tweaks

- pkg/hs/urbit-king/lib/Urbit/Vere/Ames.hs
This will help us investigate #3176. We have the hypothesis that this condition leads to delay in sending ames messages on kh start. But since I can't repro the issue, I can't test this hypoth. OTOH, if users run into this problem in the wild, they will be able to inform us whether they see these messages or not.
> king: ames: add stderr when sending before having turfs

- pkg/interface/src/apps/chat/components/chat.tsx
- pkg/interface/src/apps/chat/components/lib/chat-editor.js
- pkg/interface/src/apps/chat/components/lib/chat-input.js
- Fixes an issue where chat would autofocus on mobile devices, instead of on desktop.
- Fixes an issue where chat input would preserve a sent message during navigation due to retaining the message in state at the lowest component (editor), but not in any levels above (all props were empty strings).
> chat: prevent saving sent message on navigation

- pkg/arvo/app/landscape/index.html
- pkg/interface/src/components/Omnibox.js
- pkg/interface/src/components/OmniboxInput.js
(Everyone calls it "leap" and "leap" is four characters, I guess I'll start calling it "leap" after this.)
- Enter no longer propagates to inputs you navigate to.
- Search queries are now case insensitive.
- Results are sorted 'apps', 'commands', 'groups', 'subs'
- Background darkens in both light and dark mode (using `scales.black30` instead of `lightGray`, which swaps between white and black in each mode with some opacity)
Still pining after #3274, but it needs some investigation; I'm getting infinite loops trying to track down how to execute, and these are self contained.
@tylershuster wrote a duplicate PR of these as I was writing them. Sorry Tyler.
> leap: small fixes

- pkg/interface/src/apps/chat/components/lib/chat-editor.js
When I was hotfixing last night, I put in a patch at #3273 that reversed the boolean to autofocus the regex test for if we were on mobile or not. I did this because taking the boolean straight produced no autofocus on desktop; reversing it restored the autofocus.
Today, I noticed my iOS app still pops the input up every single time I navigate, which is what I was trying to avoid with that patch. 
I looked more at the regex and it appears we coax a string into a regex object while keeping the `!` from the previous iteration of the code as an accidental prefix before the `/`, which I believe causes the regex to treat `!/Android|webOS|iPhone|iPad|iPod|BlackBerry/i` to be treated as a single, long string to test against, not as regex syntax with a bunch of `or` clauses.
By removing the `!` …
> chat: fix syntax of regex check

- pkg/arvo/sys/hoon.hoon
For tacking some head or tail onto some noun, respectively.
I find myself doing things in the vein of `(turn my-list |=(=item [%constant item]))` often enough that I wanted a little function to just be there for me. Appropriately filed under the "functional hacks" section.
> hoon: add +lead and +late

- pkg/arvo/app/publish.hoon
See #3300. 
There's a critical fail state on hosted ships at the moment when using Leap to go to their own notebooks; this is because we attempt to join ourselves. This commit adds a check to see if our ship and the notebook host are the same; if so, we just return a no-op.
Works in basic testing on a fakezod — a `~&`d cord showed when I joined my own notebook; not when I tried to join a hypothetical outside ship. With this commit, could leap to it; without this commit, was spinning forever in FE (but not in Dojo?) trying to join it, and lost the notebook from Publish state, for some reason.
> publish: no-op when joining our own notebook

- pkg/interface/src/views/apps/chat/components/lib/content/url.js
**Problem**: a) The current "[embed]" next to Youtube URLs is not clearly a button and b) does not clearly describe its state
**Solution**: Make it a button using `indigo-react`'s styled component that reacts to state
**Caveat**: Due to active development on `indigo-react`, there is not a method that is both semantic and stylistically appropriate. This opts for semantics and documents where it is hacked
> interface: makes embed button a button

- pkg/interface/src/views/components/Omnibox.js
- pkg/interface/src/views/components/ReconnectButton.js
- pkg/interface/src/views/components/StatusBar.js
Migrated the rest of the status bar layout to flexbox, indigo-react components. Set line height to zero and attempted to center all elements properly.
(Also patches rounded corners into Leap's results, too.)
> statusBar: rewrite in indigo, line-height tweak

- pkg/interface/src/views/apps/chat/components/lib/content/text.js
**Problem**: When a group name has digits in it, it does not automatically link when sent on its own line in chat
**Solution**: Make the regex capture digits too
> chat: account for digits in group name links

- pkg/interface/src/views/apps/groups/components/lib/group-detail.js
See #3282. Also refactors shortcode render into a function.
> groups: pad shortcode prompt to avoid graphic bug

- pkg/interface/package.json
- pkg/interface/src/views/apps/chat/components/lib/chat-editor.js
- pkg/interface/src/views/apps/chat/components/lib/content/code.js
- pkg/interface/src/views/apps/chat/components/lib/content/text.js
- pkg/interface/src/views/apps/chat/css/custom.css
- Not the sidebar PR yet, sorry @galenwp.
- Adds blockquotes (#3338). @urcades?
- Code mode swaps placeholder and text with Source Code Pro.
- Add code messages now use Source Code Pro instead of being reset to Consolas.
- Updated codemirror to 5.55.0 to test my hypothesis from #2828.
> chat: several design tweaks

- pkg/hs/natpmp-static/cbits/natpmp.c
- pkg/hs/urbit-king/lib/Urbit/King/CLI.hs
- pkg/hs/urbit-king/lib/Urbit/King/Main.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ports.hs
Since startup hangs for seconds when you are not behind a router,
but still attempt to ask one to open ports for you, by default,
only try to contact the router if the local ip is `192.168.*.*` or
`10.*.*.*`.
Also make port forwarding force on/off.
> natpmp: By default, only try to talk to the router on private ips.

- pkg/arvo/app/contact-hook.hoon
- pkg/arvo/app/group-store.hoon
- pkg/arvo/lib/pull-hook.hoon
- contact-hook: no-op on accepted invite
The contact-hook was attempting to join a group upon it's invite being
accepted. However, the join poke is also sent from the frontend, causing
a potential race condition. Changes contact-hook to no-op on an
%invite-update.
- group-store: disallow joining a non-existent group
- pull-hook: no-op on pulling a resource we already have
Should address issues with joining groups
> groups: join fixes

- pkg/interface/src/views/App.js
- pkg/interface/src/views/apps/dojo/app.js
- pkg/interface/src/views/apps/dojo/components/input.js
DWISOTT. 
Does this by affecting the whole app, though. IMO not a bad solution as it prevents the need for `calc(100vh - $headerheight)` hacks in the future.
Also hides the ship name on mobile to save space.
Also learned how to serve on my local network for phone testing so that's cool.
> dojo: fixes whitescreen on mobile

- pkg/arvo/lib/chat-store.hoon
This was missing from the serialization, resulting in the value of keys being null in the JSON produced.
And an extra patch to use `?-` in the serialization instead of a sequence of `?:  ?=`.
> chat: serialize %keys to JSON for chat update

- pkg/interface/src/views/apps/chat/components/lib/chat-editor.js
- pkg/interface/src/views/apps/chat/components/lib/chat-input.js
This reverts commit a2af03fc7048ee94b09c1007cec1477b784925e8.
- Inconsistencies in how Safari and Chrome render the line-height and alignment.
- Chrome functions normally, but Safari has very janky behaviour in use:
> Revert "chat: bottom-align UI in input"

- pkg/hs/natpmp-static/cbits/binding.c
- pkg/hs/natpmp-static/cbits/natpmp.c
- pkg/hs/urbit-king/lib/Urbit/King/CLI.hs
- pkg/hs/urbit-king/lib/Urbit/King/Main.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ports.hs
- Only tries to perform port forwarding if we detect we're on a private network, with explicit always try
and never try command line flags.
- Fixes problems with the library we use where it could wait up to 4 minutes for a timeout. 
- Fixes a problem in the binding layer where if we failed to get a public address, we'd block Ames
from ever successfully sending a packet.
> natpmp: change nat-pmp startup behaviour.

- pkg/urbit/jets/b/reel.c
- pkg/urbit/jets/b/roll.c
The jet for +roll was tail recursive, but +reel for sure consumed stack space to iterate backwards over the input list. Both jets have been made into while loops, and +reel uses a vector to remember the list instead of the call stack.
> +roll and +reel stack space

- pkg/arvo/app/dojo.hoon
Unsure what happened here, we appears to have ended up at a `?` and a `?????` and nothing in between, documented as "val/type/hoon/xray".
Grabbed original implementations out of git history, there was an ominous warning about "filtering" but I don't have the context for what it means - these operations cannot have side effects, so worst case you can just not run them. (Possibly after rebooting a hung pier?)
Contains some questionable type hackery around the 79aa1cb redefinition of `$?` to disallow multiple "complex" types, if anyone can come up with a real solution here I'll be overjoyed if you push commits to that effect.
> dojo: restore `??` and `???` syntax

- pkg/interface/src/views/apps/chat/app.tsx
- pkg/interface/src/views/apps/chat/components/join.js
See #3371. 
New join behaviour in release/next-userspace had a few issues (no `station` prop passed; using `props` as if `const { props } = this` was there when it wasn't; and a double `/` in the route it redirected you to). All resolved. You can join chats again.
> chat: restore join functionality

- pkg/interface/src/views/apps/chat/components/lib/content/text.js
- pkg/interface/src/views/apps/chat/css/custom.css
See #3358. Sometimes you dump a base64 string and it makes the entire chat scroll horizontally. It happens.
Adds `overflow-wrap: break-word` to text messages. We also use indigo-react instead of adding another atomic CSS declaration; I also discovered the only thing using the old class declaration was a code overflow-wrap fix that ... isn't currently in use anyway, so it's unnecessarily in the CSS. Deleted.
> chat: break overflowing one-word messages

- pkg/arvo/app/chat-view.hoon
- pkg/arvo/app/dbug.hoon
- pkg/arvo/app/language-server.hoon
- pkg/arvo/app/lens.hoon
- pkg/arvo/app/publish.hoon
- pkg/arvo/lib/server.hoon
This has been bothering me since \**checks git log*\* a year and a half ago. No reason conversion to octs has to happen outside of this function.
> lib: take json as argument to /lib/server's +json-response

- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/vane/gall.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
This is a band-aid fix for #3196. The root cause for that still eludes me. All of the involved code "looks good to me".
Still, the symptoms of #3196 are annoying, so we address those directly. We detect the case that would lead to the error and, instead of trying to talk to the now-gone channel, we `%leave` the subscription that gave us the update. Since this requires new details from the wire, we cannot do this for existing cases, and instead rely on gall to forget all of eyre's subscriptions, "just this once".
Tested on a copy of @galenwp's ship, who was suffering from this issue.
idk what's up with the hercules failures, but it doesn't look like they're relevant here?
> eyre: prevent %eyre-no-channel errors

- pkg/arvo/ted/diff.hoon
Barebones 2-way diff thread.  Example:
```
> +cat /=home=/test/hoon
/~zod/home/~2020.8.28..04.23.09..8445/test/hoon
1
home-change
3
> +cat /=other=/test/hoon
/~zod/other/~2020.8.28..04.23.16..617e/test/hoon
1
other-change
3
> -diff /=home=/test/hoon /=other=/test/hoon
~[[%.y p=1] [%.n p=<|home-change|> q=<|other-change|>] [%.y p=1]]
```
Read this as "1 line of no change, then 'home-change' vs 'other-change', then 1 more line of no change".
Further development should include:
- recognize at least %txt and %hoon diff types as (urge:clay cord) and
print them prettily
- check if they're directories and recurse through them, noting files
that exist in one or the other and diffing ones that exist in both
- support 3-way diffs.  Since we know the desks they're on, we can find
a mergebase (see …
> clay: minimal -diff thread

- pkg/interface/src/views/apps/chat/css/custom.css
Importantly, doesn't affect the white-space of %code messages.
See #3358.
> chat: break up inline code

- pkg/interface/src/views/apps/publish/components/lib/NotebookItem.tsx
Re: #3283
The Publish refactor partially addressed the issue in question, but produced some flexbox squishing of the unread count instead. We give the title some padding on the right and disable flex-shrink to compensate.
> publish: fix unread counts for long titles

- pkg/interface/src/views/apps/profile/components/lib/Security.tsx
This was hidden in urbit-os-v1.0.44 until we could ensure it actually
logged you out of all sessions. It requires a hidden input to function,
so it's added here.
See #2649 for initial feature request. Sorry for the wait, @custom-jonathan!
> profile: log out of all sessions

- pkg/interface/src/views/apps/chat/components/lib/group-item.js
Pretty simple implementation: just tests to see if the title of the chat is going to be the ship name surrounded on either side with ` <-> `, and if so, replaces that same regex with nothing. Works for all my chats:
> chat: only show other participant in dms

- pkg/urbit/vere/io/ames.c
Fully fixes #3345:
- No longer fail to do bookkeeping on the scry queue in the "scry says we have no lane" case. This would lead to the queue "filling up" with non-existent entries, eventually resulting in all forward requests to be dropped on the floor.
- No longer give up on scrying at the first sight of failure. Instead, only do so if multiple lane scries fail in succession.
- Cache lane scry results for better performance. 
I had the pre-caching version running on ~nus for a while. On average, for every forward request it completed, it would drop three.  
Now, with caching, it seems to keep up with network traffic just fine. It's running at 100% cpu usage continuously to do so, but it's no longer dropping large amounts of packets (only dropping any briefly after booting, due to the …
> ames.c: better stateless forwarding

- pkg/arvo/app/chat-view.hoon
- pkg/arvo/lib/pull-hook.hoon
- pkg/interface/src/views/apps/chat/app.tsx
If a chat is leapt to before joined chats are loaded, then the frontend will attempt to join a chat that we already host.
Fixed in chat-view, lib/pull-hook and the frontend
> hotfix: prevent joining a host that we already host

- pkg/interface/src/views/apps/chat/components/lib/delete-button.js
- pkg/interface/src/views/apps/chat/components/settings.js
The current "Leave Group" copy says "You will need to request access again" which after the groups refactor is not accurate. Changing that is the primary purpose of this PR.
I'm also wondering about two things: one of which I changed, the other I didn't.
1. `React.PureComponent`: I don't have a lot of experience with these but it seems like it might be appropriate here. If here, than quite a few other places. I've been in the habit of using functional components but *they say* these have performance benefits.
2. The other is maybe an @urcades question: Why do we gray out the unusable buttons instead of just removing them? Seems like in especially this case you wouldn't want to have both "Leave Group" and "Delete Group" on the same screen, ever. I have used the settings page to reference a …
> chat: updated Leave Group copy

- pkg/arvo/gen/hood/merge.hoon
- pkg/arvo/gen/hood/merge/help.txt
- pkg/arvo/lib/hood/kiln.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/ted/ph/breach-sudden.hoon
- pkg/arvo/ted/ph/breach-sync.hoon
See gen/hood/merge/help.txt for an overview of all merge strategies.
- `|merge` with no arguments now prints out usage and a description of merge strategies
- Added `%take-this` and `%take-that` strategies, which are the same as the old `%this` and `%that` except they preserve files which only exist on one side or the other.  The primary use-case for `%take-that` is "forcing" updates without obliterating locally-added files, such as notebooks or 3rd party apps.
- Added `%meet-this` and `%meet-that` strategies, which are the same as `%meet`, except if both sides touched the same file (since their most recent common ancestor), prefer this or that desk.  Note this operates on the file level -- even if the changes inside the file don't conflict, we take the whole file from one side or the …
> clay: add safe merge strategies

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
Allows for parsing of an xml declaration. Throws it away, as the
datastructure doesn't have anywhere to put the result.
> zuse: allow xml declaration in +de-xml:html

- pkg/hs/urbit-king/lib/Urbit/Vere/Dawn.hs
- pkg/hs/urbit-king/package.yaml
This replaces the autogenerated bindings to the Azimuth contracts
which use Network.Web3 with hand rolled json messages. Booting a
ship involved 256 individual galaxy point lookups using web3, while
Vere batched all of that into one JSONRPC message.
With this patch, we also batch everything at each phase into one
JSONRPC batch.
Closes #3370
> king dawn: replace web3 usage with hand rolled jsonrpc messages.

- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Wai.hs
I noticed that the king's text log file kept filling up, and it's
mostly 'sending chunk "\n"' from eyre. This changes the log level
of every partial send over an active eyre channel to info, instead
of always.
> king: change logging from tracing to info in Wai.hs

- pkg/interface/src/views/apps/groups/components/lib/group-detail.js
Addresses https://github.com/urbit/landscape/issues/68
Doesn't use indigo yet. the `destructive` prop doesn't quite work as intended and figured it would be better to get a fix that worked fine out rather than have people accidentally delete groups in the meantime
> groups: add group deletion confirmation

- pkg/interface/src/views/apps/chat/components/lib/chat-message.tsx
This makes `ChatMessage`  a `PureComponent` so that it won't rerender if a shallow comparison of its props determines that they are equal. Previously a rerender of `ChatWindow` (if new messages came in) would force a rerender of all its children.
> chat: prevent message rerender

- pkg/interface/src/views/components/Error.tsx
If you've set an image background, it can make it hard to read 404s or
error messages. This adds the default bg color.
> error: add background style

- pkg/interface/src/views/apps/profile/profile.tsx
- The box for the nav was buried under some flexboxes. Adds z-index to fix behaviour on iOS Safari, profile orientation (it worked in landscape?). (#3383)
- Adds react-helmet to the routes since it appeared just before merge.
> profile: fix iOS safari behaviour, add react-helmet

- pkg/interface/src/views/apps/publish/components/lib/MarkdownField.tsx
- pkg/interface/src/views/apps/publish/components/lib/NoteForm.tsx
Partially addresses #3403 , punting on some of the stranger behaviours of CodeMirror as those will be fixed when landscape is bumped to indigo v1.2
> publish: make form expand to fill height of window

- pkg/interface/src/views/apps/chat/components/lib/chat-window.tsx
A side effect of #3357 was that pending messages didn't show up properly because, having no `number` attribute, the smarter system didn't know where to render them. This PR sorts the pending messages by timestamp and appends them to the list of messages to render
> chat: show pending messages again

- pkg/interface/src/views/components/leap/Omnibox.js
- Selected checks were crashing leap if no results were available. This just checks more safely.
> leap: safety check state.selected

- pkg/arvo/app/file-server.hoon
- pkg/arvo/gen/trouble.hoon
- pkg/arvo/lib/version.hoon
- pkg/arvo/sys/vane/clay.hoon
Change the definition of base-hash to be the mergebase of %home with the
OTA source.  This means it's the most recent successfully-applied
update, which is usually the most important information.
Add sour-hash, which is the hash of the most recently *downloaded*
update, regardless of whether it applied successfuly (ie the old
base-hash).
Add a summary of the various hashes at the top of gen/trouble.
I'll note this takes a few seconds now, since +find-merge-points isn't all that optimized (see #3029)
> clay: expose mergebase as base-hash

- pkg/interface/src/views/apps/chat/components/lib/chat-window.tsx
Doesn't show the "new message" indicators if the chat isn't idle. The sidebar still shows as unread briefly, but I don't know that this is a problem with the scroll implementation...
> chat: hotfix new message indicator

- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/sys/vane/dill.hoon
- pkg/arvo/sys/zuse.hoon
Depending on the additions to term.c made in #3467 allows dill to
forget about ansi escape codes, and pass styled text nouns straight on
to vere.
Also removes a bit of logic from drum, which assumed things about the
rendering of escape codes to adjust cursor positioning. Now it simply
states the semantic cursor position, letting the runtime deal with the
potential influence of styling.
Supersedes #3436, containing just the dill changes from there, unmodified.
Targeting `release/next-dill`, which shouldn't be pushed out OTA until #3467 (and the matching king haskell change) has been out in the wild for a while. Deploying this to older clients will make their command line prompts and some output lines fail to render.
> dill: send styled text to runtime as-is

- pkg/interface/src/views/components/leap/Omnibox.js
In #3451 I changed `selected` to use an array because I realised that Leap *wasn't* third-party application extensible; it would index third-party applications but use react-router, meaning all third-party applications would produce an inexplicable, front-end-based "404".
In Launch we handle this by checking if an application is in our default applications suite — an array of strings in `logic/lib/default-apps.js`. So Leap should do likewise; however, `selected` was using a string containing the link, the simplest solution. We needed it to also hold the 'app' to compare against our suite and see if it's ours or not.
#3451 missed a few cases; and in #3460 I caught most of the cases causing Landscape crashes but missed two:
- When you press Escape, we don't reset `selected` while we do …
> leap: ensure selected is always an array

- pkg/urbit/include/c/defs.h
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/io/hind.c
- pkg/urbit/vere/lord.c
- pkg/urbit/vere/newt.c
- pkg/urbit/vere/pier.c
- pkg/urbit/worker/main.c
- v0.10.8 introduced a bug, wherein the vere king would crash if the serf crashed. This was just a dumb mistake in the pier shutdown state machine (advancing the state before dispatching off of it).
- the error message printed on unexpected serf shutdown (manifesting as EOF on the ipc pipe) used to use the default libuv error strings, but this was unhelpful and confusing, so it's been replaced with more specific messages on each side of the pipe.
> vere: fix crash, cleanup error messages

- pkg/hs/urbit-king/lib/Urbit/King/Main.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ames/DNS.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ames/UDP.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Clay.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Multi.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Serv.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Service.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Wai.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Http/Client.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/LMDB.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/NounServ.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Serf.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Term.hs
The previously mostly unused "info" level sits between debug and warn. I've moved most things, especially startup trace messages, from debug to info. The idea is if you run with --stderr --log-info, you should get as chatty a ship as possible while still having it be usable. This means in particular that you don't get printouts on every event or http exchange. This would have made my debugging session with @ixv yesterday way better.
One problem remains, which is that on startup you get a bunch of zig-zag as multiple different threads log at the same time. This is a deep issue with RIO logging, which simply fails to guard the egress of logs in a manner appropriate for a concurrent environment.
> Use logInfo in place of logDebug in most situations

- pkg/arvo/sys/hoon.hoon
The promised hoon side of #3433, adapted somewhat from the initial comment at https://github.com/urbit/urbit/pull/1892#issuecomment-673680540.
I was unable to figure out how to both a) use a correctly-specific type for the parse-result list (`lef`) and b) use `+roll`, so I chose the latter.
The precise type of the parse-result list (which is only bunt-able because it is a list) is:
```
=|  lef=(list [p=hair q=[~ u=_(need q:(fel tub))]])
```
folding that manually is quite straightforward:
```
|-  ^-  (like _rud)
?~  lef  wag
=*  vex  i.lef
%=  $
lef  t.lef
wag  :-  (last p.vex p.wag)
[~ (raq p.u.q.vex p.u.q.wag) q.u.q.wag]
==
```
but the equivalent `+role`-call fails on empty inputs:
```
%+  roll  lef
|=  [vex=[p=hair q=[~ u=_(need q:(fel tub))]] wag=_wag]
^+  wag
:-  (last p.vex p.wag)
[~ …
```
> hoon: rewrites +stir using tail-recursion and +roll

- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/io/term.c
And, hopefully, for clarity...
This code could still use lots of improvement; in particular, the output state machine seems unnecessarily complex. But I've tried to remove layers of unnecessary indirection, reallocation, measurements of statically-sized outputs, &c. I think the biggest win is the direct utf-32 to utf-8 conversation, and the most questionable change is attempting synchronous writes.
These changes are not particularly high-priority -- I'm mostly just scratching at a longstanding itch. I'd be happy to make any changes you'd like.
> vere: refactors terminal output implementation for efficiency

- pkg/urbit/noun/imprison.c
- pkg/urbit/vere/king.c
... which I had broke somewhere in the lead up to `v0.10.8`, but adding "allocator" annotations to the `u3i_*()` atom allocation functions, but not accounting for their early returns.
This PR also unconditionally disables sample profiling in the king -- there's currently no way to capture the output, and it'll be easy to turn back on if we ever decide we want to and add such a mechanism.
> vere: fixes -P sample profiling

- pkg/hs/urbit-king/lib/Urbit/Arvo/Effect.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Term.hs
Adds support to `term.hs` for a `%klr` blit, containing a `+stub` describing styled text.
This is the king-haskell equivalent of #3467. For dill-side changes, see #3468.
Special thanks to @pilfer-pandex and @jtobin for holding my hand through this!
> kh: support rendering +stub as ansi escape codes

- pkg/interface/src/views/apps/dojo/app.js
It might address #3483 but too early to tell. Try a reproduction on livenet and in this branch by navigating quickly from apps to Dojo. On livenet, you can navigate between apps fine as fast as you want; but Dojo doesn't like it if you go to it quickly in sequence after another app and doesn't initiate.
I sequence the `resetControllers()` in the onMount and explicitly state what its `this` scope is to prevent any potential issue where `resetControllers()` was called too quickly or just not processing at all (since `this` might not be bound to the component?). It seems to be more reliable this way.
> soto: call resetControllers on mount

- pkg/interface/package.json
- pkg/interface/src/views/components/VirtualScroller.tsx
Fixes #3492
Most browser give deltaY as pixels on the wheel-event, Firefox gives it in lines (deltamode is 1, not 0: https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaMode). There are also major inconsistencies with what resolution various hardware and browser combinations fire the event, for example this bug only occurs for me on Firefox AND when using a mouse instead of a touchpad. The picture below logs a single mousescroll with that setup (with Chrome the values are the same).
Now I hate adding dependencies as much as the next guy, but this library is just https://gist.github.com/akella/11574989a9f3cc9e0ad47e401c12ccaf, and solves the problem quite nicely.
> webchat: fix slow scrolling

- bin/solid.pill
- pkg/arvo/gen/hood/meld.hoon
- pkg/arvo/gen/hood/trim.hoon
- pkg/arvo/lib/hood/helm.hoon
- pkg/arvo/sys/vane/dill.hoon
- pkg/arvo/sys/zuse.hoon
`%meld` is the name of the new global deduplicator, added in #3235). Support for the effect is also added in that PR, but there's no need to block this addition, or otherwise coordinate the release of these changes -- if the effect is unsupported, the user will merely see a `kick: lost` printf.
The `%trim` effect (triggering memory reclamation via a subsequent `%trim` event) has been long supported, but there was no way to manually trigger it. I've taken the liberty of adding that as well. The triggering task to %dill is named `%crop`, as `%trim` is already reserved for the global memory pressure event.
> arvo: adds new maintenance commands: |trim and |meld

- pkg/arvo/app/shoe.hoon
- pkg/arvo/lib/shoe.hoon
I needed this for a thing I'm working on. Figured tables would be a good first "complex screen-draw effect" for /lib/shoe.
Table data is a list of header names, a list of width restrictions, and a list of rows, defined as lists of `dime`s.  
Row contents are rendered as per the aura in the `dime`. This also determines their alignment (left/right), and how they break to fit smaller-width columns.
Note that the comment describes `%table` as "sortable, filterable data". This obviously isn't gonna fly in our current shoe/sole client, but it hints at a not-far-off future where we expose `shoe-effects` directly, letting capable clients render them in more dynamic, context-appropriate ways.
`%row` was added because `%table` necessitated implementing it. Whether it's a good fit for the shoe …
> shoe: tables

- pkg/arvo/lib/dbug.hoon
- pkg/arvo/lib/shoe.hoon
If the underlying app implements a `/x/dbug/state` endpoint in `+on-peek`,
dbug will now use that for `%state` evaluation. Falls back to the vase
provided by `+on-save` if the peek fails.
This allows apps and (perhaps more usefully) wrapper agents to provide
customized vases to `/lib/dbug`.
Updates `/lib/shoe` to make use of this, properly prepending the wrapped
app's vase to shoe's own, instead of including it as-is.
> dbug: attempt to scry for state

- pkg/interface/src/logic/api/chat.ts
- pkg/interface/src/views/apps/chat/components/join.js
- pkg/interface/src/views/apps/chat/components/lib/delete-button.js
- pkg/interface/src/views/apps/chat/components/settings.js
- pkg/interface/src/views/apps/groups/components/join.js
- pkg/interface/src/views/apps/publish/components/lib/Join.tsx
Uses the `replaceState` feature of the history API to change-in-place the page
location instead of pushing a new entry, which prevents backward navigation.
Also irons out some inconsistent behavior on joining.
Fixes #3504, fixes #3503, fixes some unfiled bugs
> all: Fixes joining navigation jank

- pkg/interface/src/views/apps/links/components/lib/link-submit.tsx
fixes #3481
It checks late to avoid the case where the link title isn't entered, the user enters one while the oembed is fetching, and then it gets overwritten
> links: prevents title from being overwritten

- pkg/interface/src/views/apps/chat/components/lib/ChatWindow.tsx
- pkg/interface/src/views/components/VirtualScroller.tsx
fixes #3496
Commented out to avoid merge collisions when #3511 merges.
Also only drafting because this should probably also show some loading indicator when loading more backlog
> chat: make backlog height only reflect loaded messages

- pkg/interface/src/views/apps/publish/components/lib/NoteNavigation.tsx
Addresses #3489.
Because we didn't access `date` through the function's `props` it was `undefined`; moment, too shy to say anything, just decided to use the timestamp for *right this second* instead.
> publish: correct timestamps on note navigation

- pkg/interface/src/views/apps/publish/components/lib/Notebook.tsx
fixed #3506
This isn't a very glamorous fix, but it seems to work. Is there a reason a notebook wouldn't have a group? Even if it's unmanaged, the proper path exists in the group object. If I do a check for group later on, then I get `this.props.notebook is undefined` in `Subscribers.tsx` — maybe this need someone more familiar with the architecture, but the problem is definitely there.
> publish: fixed error on notebook refresh

- pkg/interface/src/views/components/s3-upload.tsx
The dragger overlay doesn't have dark mode styles; this rewrites the component in indigo-react so that its colour scheme changes to match.
cc @urcades — anything we need to distinguish this further?
> various: s3 dragger uses indigo-react

- pkg/interface/src/views/apps/chat/components/lib/ChatWindow.tsx
fixes #3534
This is correct behavior.
May cause issues with some people who have messages stored out of order on their computer.
Leaving and rejoining the channel should fix it for them.
> chat: sort message by number instead of timestamp

- pkg/interface/src/views/apps/chat/components/lib/ChatWindow.tsx
@matildepark @vvisigoth 
This should fix the issue you noticed where posting an image would cause the chat to jump. It was caused by an old method that did more harm than good in the new implementation.
> chat: fixes message jump

- pkg/arvo/app/test/example.udon
This file dates back to the previous Eyre write; Arvo no longer has a
/web folder, so this seems fine to clean out.
(Reviewers aren't all mandatory, just people who would know if this is a bad thing to remove for whatever reason.)
> arvo: remove test/example.udon

- pkg/interface/src/views/apps/chat/components/lib/ChatWindow.tsx
Just some light refinements on how the unread markers behave. Now when you refocus the window, it will mark messages as read if you're at the bottom, thus clearing the banner and the tab icon, but the line will remain.
> chat: fixes unread marker on blur

- pkg/interface/src/views/components/leap/Omnibox.js
A very tiny PR while I'm debugging Leap in Safari 14 — just amending some of these repeated assignments into a single destructure makes the selection logic way easier to follow? — places emphasis on *where* in the array we assign in each case instead of just seeming like code.
> leap: destructure selection logic variables

- pkg/interface/src/views/components/leap/OmniboxInput.js
Safari 14 just came out; and while on Safari 13 Leap's autofocus works fine, in 14 Leap only autofocuses the first time and never again afterward. This is of course very annoying in everyday usage.
The origin appears to be [a change in behaviour in an unclear spec](https://bugs.webkit.org/show_bug.cgi?id=29241) for whether hiding an element automatically blurs it. What happens is that while in all other browsers, the `focus()` event fires every time, in Safari 14 the `focus()` even only fires the first time, because it technically *has never lost focus*? 
And thus it would only work properly if you were Leaping from Dojo or Chat, where there was another element to unfocus.
This commit forces the component to blur *itself* and refocus when it's mounted. This seems to retain the normal …
> leap: always blur and refocus input on mount

- pkg/arvo/app/graph-store.hoon
- pkg/arvo/gen/graph-store/export-graph.hoon
- pkg/arvo/gen/graph-store/import-graph.hoon
- pkg/arvo/mar/graph/update.hoon
To export a graph:
```
+graph-store/export-graph our %graph-name
```
The output can be routed to a jammed Unix noun by using :dojo's `.file/ext` syntax.  This file can then be copied into a Unix mount of an Urbit desk, where it should be given the `.graph-update` file extension so that the Clay file has the right mark.
To import a graph from a Clay file:
```
:graph-store|import-graph %new-graph-name %/full/path/to/graph-update
```
> graph import/export generators

- pkg/arvo/ted/graph/restore.hoon
- pkg/interface/src/views/apps/links/components/new.tsx
Adds a thread to restore an archived graph to full functioning, and fixes imports that broke in the indigo 1.2 upgrade
> Restore thread and Indigo import fix

- pkg/arvo/app/metadata-store.hoon
The OTA deployment of urbit-os-v1.0.50 unintentionally wiped the indices
during the state migration. This caused widespread permissions issues,
as agents were unable to tell which group is associated with what channel.
Fortunately, the indices are a simple transform of the associations noun,
which was kept intact. This commit introduces a state migration to rebuild
the indices, in order to restore connectivity on the network.
> metadata-store: rebuild indices

- pkg/hs/proto/lib/Untyped/Parser.hs
- pkg/hs/urbit-eventlog-lmdb/lib/Urbit/EventLog/LMDB.hs
- pkg/hs/urbit-king/lib/Urbit/King/Main.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/LMDB.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/NounServ.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Term.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Term/Render.hs
- pkg/hs/urbit-king/test/HoonMapSetTests.hs
- pkg/hs/urbit-noun-core/lib/Urbit/Noun/Jam.hs
- pkg/hs/urbit-noun/lib/Urbit/Noun.hs
- pkg/hs/urbit-noun/lib/Urbit/Noun/Tree.hs
I haven't done much (king) haskell work, but I did spot this crime against developers. Everyone I've spoken to about it was in favor of returning to ascii syntax, so I did a bunch of find-replace, and this is the result.
> kh: abolish unicode syntax in favor of ascii

- pkg/arvo/app/chat-hook.hoon
Send invites to all unsubscribed members of unmanaged chats to fix deleted DMs from metadata-store bug.
> chat-hook: send invites to all unsubscribed members of unmanaged chats

- pkg/arvo/sys/zuse.hoon
Because these things aren't always printable/valid `@t`.
There's maybe some argument to be made here around `@t` indicating a specific byte order, but `octs` gets used for both cords and arbitrary bytestreams, so...
> zuse: make octs value @ instead of @t

- pkg/arvo/app/dojo.hoon
Allows things like `+hello &helm-hi 'hi'`. Fixes #1476.
> dojo: parse %as in ++parse-value instead of ++parse-build

- bin/solid.pill
- pkg/arvo/sys/vane/eyre.hoon
This was originally introduced by me in #1814 to address #1811. Eyre was not canceling heartbeat timers on all relevant events making it easy to end up with an infinite behn loop. This check allowed ships that entered an infinite loop to recover, as per my comment at https://github.com/urbit/urbit/pull/1814#discussion_r333477482. Otherwise it's not necessary.
> eyre: remove superfluous connection-state check

- pkg/interface/src/views/components/DropdownSearch.tsx
fixes #3583
I figure this is safe because in general you want dropdowns to be above other things. LMK if there's a better pattern to use here.
> landscape: increase z-index of dropdown search

- pkg/interface/config/webpack.dev.js
This opens up the dev server to network connections, for instance on a mobile device on the same wifi network.
> interface: open dev server to network

- pkg/interface/src/logic/lib/omnibox.js
- pkg/interface/src/views/components/leap/OmniboxResult.js
- Removes all the image logic gunk and just uses indigo-react icons for Leap results. (One step closer to getting PNGs out of Landscape.)
- Trims up OmniboxResult of some unnecessary duplicate logic for essentially a single color ternary.
cc @urcades @g-a-v-i-n
> leap: use indigo-react icons

- pkg/arvo/lib/shoe.hoon
Previously, up-arrowing into (or otherwise retrieving) a command from history
that automatically runs on-input would directly run the command again,
preventing the user from up-arrowing past the auto-run command into further
history.
With this change, shoe detects discontinuous inputs (sole's `%set` edit), and
refuses to auto-run the parsed command in those cases.
Wrote an alternative fix here: 4267761, but ultimately decided against leaving auto-run commands out of history entirely. I imagine the behavior here fits user expectations better. Maybe this needs to be configurable, but I'm be hesitant to make that change without clear demand for it.
> shoe: don't auto-run discontinuous inputs

- CONTRIBUTING.md
- pkg/interface/CONTRIBUTING.md
- The interface dev environment is very simple to set up. This PR attempts to better exemplify that.
- Because there have been a few situations in which users get tripped up on fakezods using boot pills, I add instructions to use the solid pill and Arvo directory from the repository.
> meta: simplify contributing guides

- .github/ISSUE_TEMPLATE/config.yml
While Landscape source code is bundled with the Arvo repository, not all Landscape issues belong in the urbit repo. That is, urbit/urbit should concern itself with functionality and livenet issues, and QA or design-specific reports should be handled in its own forum. 
Commits can still close cross-repo issues using the repo format, eg. urbit/landscape#25.
cc @urcades
> meta: add link to file design issues

- pkg/interface/src/views/apps/chat/components/lib/ChatInput.tsx
- pkg/interface/src/views/components/s3-upload.tsx
fixes #3589
Due to inconsistencies in how browsers handle "change" events, it is necessary to make a brief delay on S3 uploader to prevent double-uploading
> landscape: delay uploading briefly to account for browser inconsistencies

- bin/solid.pill
- pkg/arvo/app/hood.hoon
- pkg/arvo/gen/cors-registry.hoon
- pkg/arvo/gen/hood/cors-approve.hoon
- pkg/arvo/gen/hood/cors-reject.hoon
- pkg/arvo/lib/hood/helm.hoon
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/zuse.hoon
Implement minimal CORS handling into Eyre, [as proposed on urbit-dev](https://groups.google.com/a/urbit.org/g/dev/c/bb82dwEJGzM/m/q2JjNSx5BwAJ).
Includes a `+cors-registry` generator for easily viewing the current CORS state, and `|cors-approve` and `|cors-reject` for allowing and denying origins access, respectively.
idk what's up with hood all of a sudden, but I needed b277b82 to get it to play nice and compile regardless of my other changes here.
> eyre: minimal CORS support

- pkg/interface/src/views/apps/publish/components/lib/MarkdownEditor.tsx
Addresses #3593.
Due to the refactor in #3540 we now use `useCallback`, and this prompts a rerender every single time we make a keystroke, pushing the cursor to the end. `autoCursor={false}` tells CodeMirror to not reset the cursor on a value change. We are going to want to prevent the rerender entirely, but I am thus far unsure how to finagle hooks — initial tips point to adding a [useRef](https://stackoverflow.com/questions/55045566/react-hooks-usecallback-causes-child-to-re-render).
(h/t to @tylershuster for pointing out the obvious fix)
> publish: disable cursor position reset on rerender

- pkg/interface/src/views/apps/chat/components/lib/groupify-button.js
- pkg/interface/src/views/apps/chat/components/new-dm.js
- pkg/interface/src/views/apps/chat/components/new.js
- pkg/interface/src/views/apps/chat/components/settings.js
- pkg/interface/src/views/apps/groups/components/new.tsx
- pkg/interface/src/views/components/metadata/settings.js
- "Module" and "colour" were in the wrong order for the poke that sets the name of a resource, causing a poke fail. (#3617)
- Replaces `~` and `.` in new group / resource paths with `-` to avoid weird behaviours. (#3605)
- We didn't pass `station` nor `changeLoading` to the groupify button causing groupifying chats to fail. (#3592)
> interface: metadata UI fixes

- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
Take 2!
Ok, full disclosure I didn't test this. But I know so little about this system I figured I should just run it all by you and tell you why.
I'm tired of seeing this in the console and it suggests an error:
```
XML Parsing Error: no root element found
Location: http://localhost:1701/~/channel/1601004556-791863
Line Number 1, Column 1:
```
So, in `eyre.hoon` wherever I saw `data=~` and `status-code=200` I changed it to 204, as per [the spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)
?
> eyre: send 'no content' headers with no content

- pkg/hs/urbit-king/lib/Urbit/King/API.hs
- pkg/hs/urbit-king/lib/Urbit/King/Main.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Term.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Term/API.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Term/Demux.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Term/Logic.hs
- pkg/hs/urbit-noun/lib/Urbit/Noun/Tank.hs
- pkg/hs/urbit-termsize/lib/Urbit/TermSize.hs
This fixes two, related problems with terminal handling in KH:
- slog (`~&`) and urbit-worker stderr output wouldn't display in mulitplexed terminals, because they were hardcoded to go to the stderr of the terminal that king haskell was attached to.
- Terminal sizing was wrong, in part because of multiplexed terminals.
These two commits can be reviewed individually.
> King Haskell terminal fixes

- pkg/arvo/sys/vane/eyre.hoon
Lets you check whether a specific `Cookie` header value string constitutes an authenticated request.
eg: `/ex/=//=/authenticated/cookie/(scot %t 'cookie-string')`
Intended for use in the runtime, for example with #3557.
> eyre: add authentication checker scry endpoint

- pkg/interface/src/views/apps/links/components/link-detail.js
- pkg/interface/src/views/apps/links/components/link-list.js
- pkg/interface/src/views/apps/links/components/settings.js
- We were passing an undeclared `ship`, always blank and defaulting to our ship's info. We safely access the graph node's author.
- Also wraps the tab bar in a `Box` component — the graph-store rewrite apparently deleted some spaces in the quotes that were spacing atomic CSS classes, that prevented the tab bar from shrinking closed. When in doubt: always write the solution in indigo-react.
> links: access contact metadata properly

- pkg/interface/src/logic/lib/omnibox.js
- pkg/interface/src/views/App.js
This fixes an unfiled bug where any leap results including a command in them would crash the whole app because the lowercase app name would fail to be recognized as an icon, and leap was not contained in an error boundary.
For future error trapping it also wraps the main components of the app in error boundaries.
> leap: error trapping, fixes icon bug

- pkg/urbit/include/noun/retrieve.h
- pkg/urbit/noun/allocate.c
- pkg/urbit/noun/retrieve.c
- pkg/urbit/noun/serial.c
Building on #3433, this PR refactors/rewrites our big, open-ended noun traversals (pre-order in `u3a_walk_fore/unsafe()` and `u3r_sing()`, post-order in `u3r_mug()`, `u3s_cue()`, `u3a_take()`).
Their manual stack fiddling (and road-direction abstraction) have been replaced with the new road-stack API, and the post-order traversals use two functions with (do) while loops instead of labeled goto. I've also generally cleaned up and commented the implementations, and split `u3a_take()` into north/south variants (it used to work this way, but the old explicit-stack version was so big that I couldn't bring myself to duplicate it).
> u3: use new road-stack api in noun traversals

- pkg/arvo/sys/vane/ames.hoon
This should help us debug failing scry requests related to stateless forwarding.  `|ames-verb %for` turns on printing in the `~` case.
> ames: print failed scrys

- pkg/arvo/sys/vane/eyre.hoon
Disallows registering bindings (through `%connect` and `%serve`) that would capture
traffic on paths starting with `/~` (Eyre's) or `/~_~` (runtime's, as of cc389c5).
Note that we don't touch `+insert-binding`, which is used by Eyre internally to
set up bindings in its own namespace.
> eyre: prevent binding in reserved namespaces

- pkg/interface/src/logic/api/publish.ts
- pkg/interface/src/views/apps/publish/PublishResource.tsx
- pkg/interface/src/views/apps/publish/components/lib/Author.tsx
- pkg/interface/src/views/apps/publish/components/lib/Note.tsx
- pkg/interface/src/views/apps/publish/components/lib/Notebook.tsx
- pkg/interface/src/views/apps/publish/components/lib/NotebookPosts.tsx
- pkg/interface/src/views/components/DropdownSearch.tsx
- pkg/interface/src/views/components/GroupSearch.tsx
- Fix unmanaged notebooks (or any notebook in a group with no contacts) crashing
- Fix a crash in the groupify menu for notebooks
- Prevent duplicate results from showing when searching an exact patp
- Send 'read' actions when loading a note
> publish: crashes and regressions

- pkg/interface/src/views/apps/publish/components/lib/NoteNavigation.tsx
`nextUrl` updated to the id of the next note rather than the previous note.
@matildepark @tylershuster
> publish: prevId -> nextId

- pkg/interface/src/views/components/RemoteContent.tsx
@matildepark Would you try to break this? I can't, but I don't see why this change would cover every use case.
> landscape: better embed checking

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/tests/sys/zuse/mimes.hoon
Motivated by #1892, jets incoming. This is just typical MSB-first hex; the only remotely interesting part is the careful handling of input length to account for leading zeros. (The input will be `$octs` once #3554 is in.)
The API is (mostly) taken from `lib/base64`, which I intend to clean up and move into %zuse (and jet) in a similar manner.
> zuse: adds |base16 en/decoding core

- pkg/urbit/include/c/motes.h
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/io/http.c
- pkg/urbit/vere/pier.c
This adds an http endpoint (`/~/slog`) to the existing http server in vere, on top of the bindings that eyre makes. It does SSE, sending pre-processed lines of output to all open connections whenever the runtime receives a `%slog` from the worker.
This can be useful for gathering debugging output from ships in hosting contexts, and can bring web dojo closer to the real terminal experience.
The matching web dojo PR is following Soon™, but this should be ready for initial review on its own.
~We... may or may not want to hold off on merging this until we put authentication on it. We don't have an http auth mechanism in the runtime yet, but there's probably something we can do along the lines of scrying into eyre with "is this a valid session cookie"?~  
Authentication is in as of d0d9437.
> vere: webslogs

- pkg/interface/src/views/apps/launch/app.js
- pkg/interface/src/views/apps/launch/components/Groups.tsx
The new layout has no way to do this, so we iterate them as tiles with 'accept' and 'reject' iconography.
> launch: display group invites on home screen

- bin/solid.pill
- pkg/arvo/sys/hoon.hoon
Fixes #1473.
<s>
Note that something is off with the type of (at least some of) the individual arms in the coin parser (`|so`). Invoking them directly works fine:
```
> (twid:so [1 1] "0sj1c9s1nmupjo1")
[p=[p=1 q=16] q=[~ u=[p=[%blob [7.303.014 7.496.034]] q=[p=[p=1 q=16] q=""]]]]
> (crub:so [1 1] "2012.1.1")
[p=[p=1 q=9] q=[~ u=[p=[p=~.da q=170.141.184.499.601.039.830.939.939.828.137.984.000] q=[p=[p=1 q=9] q=""]]]]
```
But we get a wet-gate type failure if we try to call them via `+scan`:
```
> (scan twid:so "0sj1c9s1nmupjo1")
mull-grow
-find.$.+2
> (scan crub:so "2012.1.1")
mull-grow
-find.$.+2
```
I discovered this behavior when testing the change in this PR, but it's a pre-existing issue, so I think it's out of scope here.
</s>
Update: I am an idiot, and had reversed the order of the …
> hoon: virtualize cue when parsing %blob coin literals

- pkg/arvo/sys/hoon.hoon
Here's a fun one. Follow-up to #3266.
Previously:
```hoon
> ((late 42) *(list))
mull-grow
-find.t
find-fork
```
By using tree instead of face addressing, we avoid stepping into faces from the
argument noun.
Updates `+lead` for visual symmetry, and the much rarer `-find.h` case.
> hoon: avoid potential shadow in +late

- pkg/hs/urbit-king/lib/Urbit/King/CLI.hs
- pkg/hs/urbit-king/lib/Urbit/King/Main.hs
Two fixes: one to make --serf apply to all multitenant piers started, and the other one line needle that I was able to track down: when the king gets a request to shutdown in multitenant mode, it doesn't rebroadcast that request to its serfs.
(This pull request will be easier to review on a per-commit basis.)
Fixes #3187
> King multitenant fixups

- pkg/urbit/jets/a/div.c
- pkg/urbit/jets/c/dvr.c
- pkg/urbit/jets/c/sqt.c
The `+dvr` and `+sqt` jets incorrectly double-counted references when copying GMP integers on the looom, and the `+div` and `+dvr` jets failed to push a `divide-by-zero` error message onto stack trace. (I found the former due to CI errors in #3636, and the latter in code review.)
Note that the `|fl` jets also appear to incorrectly double-count GMP integers. Those jets are much more complicated, and I'm much less familiar with them. I'll open a separate issue to track them.
> u3: fixes jet memory leaks, mismatches in +div/+dvr/+sqt

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
- pkg/interface/src/views/apps/chat/components/content/text.js
- pkg/interface/src/views/apps/chat/components/overlay-sigil.js
- pkg/interface/src/views/apps/chat/css/custom.css
- pkg/interface/src/views/components/RemoteContent.tsx
- pkg/interface/src/views/components/withPropsChecker.js
This PR standardizes chat font-size at Indigo 1, resulting in the same size as livenet (16px / `f9`).
To do this, it rewrites many chat components in Indigo, but there are still a few utility classes left.
It also catches an uncaught `next-userspace` bug where `ChatWindow` would retain its current scroll position and unread status when switching between stations, presumably due to some upstream memoization.
> chat: fix and standardize font size

- pkg/urbit/include/noun/imprison.h
- pkg/urbit/jets/b/flop.c
- pkg/urbit/jets/b/murn.c
- pkg/urbit/jets/b/scag.c
- pkg/urbit/jets/b/turn.c
- pkg/urbit/jets/b/weld.c
- pkg/urbit/noun/allocate.c
- pkg/urbit/noun/imprison.c
This PR adds `u3i_defcons()`, a deferred cell constructor, and uses it in the list jets. This replaces a pattern of constructing lists in reverse order, and flopping them when complete, and therefore avoids an unnecessary round cell allocations in each. This optimization is often called [tail-recursion modulo cons](https://en.wikipedia.org/wiki/Tail_call#Tail_recursion_modulo_cons). We may want to consider adding it to the bytecode interpeter at some point in the future.
> u3: improve efficiency of list jets by cons'ing in-order

- pkg/urbit/include/noun/allocate.h
- pkg/urbit/jets/b/lent.c
- pkg/urbit/jets/d/in_wyt.c
This PR removes what I argue is unnecessary arbitrary-precision in the `+lent` and `+wyt:in` jets.
First, it occurred to me that `+lent` need not unconditionally use arbitrary-precision increment (`u3i_vint()`); the counter starts at 0, so we know exactly when it no longer fits in a direct atom. I rewrote the `+lent` jet to iterate with a `c3_w` (uint32_t) counter until that overflows, then initialize an indirect atom and subsequently iterate with `u3i_vint()` (this is in 94a4dc5).
But then it occurred to me that we statically know the maximum number of cells we can represent on the loom, so use of arbitrary-precision in this jet is entirely unnecessary. Instead, we can simply increment a `c3_w` counter. The code is guarded by a compile-time assertion that the maximum number of cells …
> u3: replaces arbitrary-precision math in +lent and +wyt:in jets

- pkg/interface/src/views/landscape/components/GroupsPane.tsx
- pkg/interface/src/views/landscape/components/Participants.tsx
- pkg/interface/src/views/landscape/components/PopoverRoutes.tsx
- Re-establishes avatars in the participants list if they are set
- Passes the hide props for both nicknames and avatars to respect user settings and avoid a regression
> groups: pass hideAvatars / nicknames to participants list

- pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
- We get recent groups from localStorage, but this produces edge cases where we leave a group, but retain it in our recentGroups array
- We don't filter this array for what groups we're currently in before rendering it, so "empty" recents are rendered
- This just filters that array with a safety check'd call inside the `associations.contacts` object.
> groups: remove remnant groups from recent

- pkg/interface/src/logic/lib/omnibox.js
- pkg/interface/src/views/components/leap/Omnibox.js
- pkg/interface/src/views/components/leap/OmniboxResult.js
- Adds 'home' (our DM / personal space) to the leap index + default results when nothing is searched
cc @urcades @g-a-v-i-n — 
Design-wise I use "Circle" for the icon, not "Home", because we use "Circle" to denote the home space in the tile; and we use the "Home" icon to ...  bring us to the launch screen. I think this is gonna need smoothing at some point, but I just wanted to be consistent.
> leap: add 'home' to leap index, default results

- pkg/interface/src/logic/lib/omnibox.js
- pkg/interface/src/views/App.js
- pkg/interface/src/views/components/UnjoinedResource.tsx
- pkg/interface/src/views/components/leap/Omnibox.js
- Leap didn't use `/home`, but the `group-path`, if the resource was unmanaged, emptying the sidebar when leaping to unmanaged resources
- The groups pane listened for the wrong key for Links inside `graphKeys` — it doesn't use `/ship/patp/resource`, but `sigless-patp/resource`, so we listen correctly now.
> groups, leap: redirect unmanaged resources correctly

- pkg/interface/src/views/apps/publish/components/Note.tsx
- In `<Note>`, `baseUrl` is the Note's path; `rootUrl` is the notebook's path; thus the Notebook Index link was linking to itself. We just use `rootUrl` accordingly, instead of `baseUrl`.
> publish: fix 'notebook index' link

- pkg/interface/src/logic/reducers/local.ts
This should fix the following warning that I get whenever I reload my landscape page:
```
Failed to rehydrate localStorage state SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at e.value (local.ts:11)
at r.value (store.ts:39)
at r.value (App.js:88)
at as (react-dom.production.min.js:212)
at fl (react-dom.production.min.js:255)
at t.unstable_runWithPriority (scheduler.production.min.js:19)
at Bi (react-dom.production.min.js:122)
at hl (react-dom.production.min.js:248)
at Qs (react-dom.production.min.js:239)
```
I believe this happened whenever localStorage was empty, because it would try to run `JSON.parse('')`, which produces that error.
> LocalReducer: fix empty case of localStorage rehydration

- pkg/interface/src/views/apps/links/LinkResource.tsx
Fixes a regression on next-userspace branch where, because we weren't keying by the graph's keys (dates), submitted links append to the bottom of the list, not pop up at the top of the list.
> links: key linkItems by date

- pkg/interface/src/logic/lib/omnibox.js
- pkg/interface/src/views/components/leap/Omnibox.js
- pkg/interface/src/views/components/leap/OmniboxResult.js
Fixes a temporary regression where apps were no longer indexed in Leap; I believe it also fixes an unfiled bug where third party apps crash Landscape due to, what I can only assume, is new behaviour in indigo-react when no icon string is specified (it used to have a default?).
Doesn't list the apps in the default results list (we'll probably want "Recent Groups" here but requires some additional logic); also uses the new Dojo icon.
> leap: restore app index, remove from default

- pkg/urbit/include/jets/k.h
- pkg/urbit/jets/a/dec.c
- pkg/urbit/tests/ames_tests.c
- pkg/urbit/tests/hashtable_tests.c
- pkg/urbit/tests/jam_tests.c
- pkg/urbit/tests/mug_tests.c
- pkg/urbit/tests/newt_tests.c
This PR enables garbage-collection in all of our runtime unit suites (except for `noun_tests`, which would need a ton of cleanup). It also removes redundant tests, uses a more consistent testing protocol (continue testing after failure, return results), and generally cleans things up.
> u3: run gc after each unit test suite

- pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx
- pkg/interface/src/views/landscape/components/Sidebar/SidebarInvite.tsx
There's no way to actually accept a DM at the moment. This PR iterates through non-group invites in the home workspace (since it's the only case that still uses the invites-only system).
Design review since I rewrote the component in indigo-react @urcades @g-a-v-i-n —
> interface: show unmanaged invites in home workspace

- pkg/urbit/jets/b/murn.c
- pkg/urbit/jets/b/skid.c
- pkg/urbit/jets/b/skim.c
- pkg/urbit/jets/b/skip.c
- pkg/urbit/jets/b/turn.c
This PR builds on #3658, applying the same optimizations to the `+skim`, `+skip`, and `+skid` jets. Each of these were implemented with unbounded recursion, and would overflow the stack on large inputs. All three have been converted to loops, and unnecessary intermediate cell allocation and deconstruction in `+skid` has been removed.
> u3: improve efficiency of more list jets

- pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
- Mobile navigation out of a DM presents a blank sidebar at the moment
- We check for the home URL (probably a better workspace utility for this?) and pass workspace instead of selected group for constructing our back links to remedy this issue
> groups: properly direct mobile navigation in home

- pkg/interface/CONTRIBUTING.md
- pkg/interface/config/urbitrc-sample
- pkg/interface/config/webpack.dev.js
Allows to dynamically switch between ships depending on the localhost subdomain. e.g. 
```
module.exports = {
URL: 'https://hastuc-dibtux.arvo.network',
FLEET: {
'zod': 'http://localhost:80',
'bus': 'http://localhost:8080',
'nus': 'http://localhost:8081'
}
```
in one's urbitrc will proxy `zod.localhost:9000` to `http://localhost:80`,  `bus.localhost:9000` to `http://localhost:8080`  and  `nus.localhost:9000` to `http://localhost:8081`. It will fall back to `https://hastuc-dibtux.arvo.network` when no subdomain is found.
> interface: multi ship devserver

- pkg/arvo/sys/hoon.hoon
`+murn` was missing both a typecast of its product and list sample homogenization (compare with `+turn`). It also required the provided gate to cast to `(unit)` or manually add the relevant `u` face: ``(murn `(list @)`[1 2 3 ~] |=(a=@ `a))`` would nest-fail in `+mull`, but ``(murn `(list @)`[1 2 3 ~] |=(a=@ (some a)))`` would succeed.
> hoon: adds product cast to +murn

- pkg/arvo/sys/hoon.hoon
I think their time has come. While investigating #3664 and developing #3689, I found that I had to enable these to make progress. Even though I was printing absolutely massive types, performance was not an issue. There's still much to be done to improve our type printing, but I think it's worth enabling these regardless.
This PR also removes the "road:new" stack-trace message on crashes in `+road` -- I don't think that conveys anything useful to users or developers, as `+road` is a general-purpose virtualization tool with no specific semantics. (Furthermore, its entire purpose is to behave as if the computation were not virtualized, modulo the allocator properties of the runtime. So it really shouldn't be observable, and should probably just be a hint in the future.)
> hoon: enables need/have type printfs on nest-fail

- pkg/urbit/include/jets/w.h
- pkg/urbit/jets/tree.c
This just backports #2899 from `na-release/next-vere`.
> u3: re-re-enable +repn jet

- pkg/arvo/app/time.hoon
This PR restores the `:time` app, which is a simple, low-resolution tool for timing a computation in the dojo (estimated via the elapsed time between the beginning of the computation, and the arrival of a subsequent timer event schedule for `+(now)`).
It's usefulness had been greatly reduced by the integration of `cc-release` (in v0.8.0), due to issues with event-timestamp granularity. It was removed with the integration of static-gall and spider, replaced by the `-time` thread. But the latter is less useful, as it doesn't support arbitrary expressions. And the event-timestamp issues have been resolved in `v0.10.8`.
> arvo: restore :time app

- pkg/arvo/sys/hoon.hoon
This is the hoon changes from #2895, backported from `na-release/next-vere` (with the addition of `+stun`, which is a good candidate for jetting).
> hoon: adds hints for likely-to-be-jetted list/treap/parser arms

- pkg/interface/src/views/apps/chat/components/ChatInput.tsx
- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/apps/chat/components/chat-editor.js
- pkg/interface/src/views/apps/chat/components/content/code.js
- pkg/interface/src/views/apps/chat/components/content/text.js
- pkg/interface/src/views/apps/chat/components/profile-overlay.js
- pkg/interface/src/views/apps/chat/components/unread-notice.js
- pkg/interface/src/views/apps/chat/css/custom.css
- pkg/interface/src/views/apps/launch/components/Groups.tsx
- pkg/interface/src/views/apps/launch/components/tiles/tile.js
- pkg/interface/src/views/landscape/components/ChannelMenu.tsx
- pkg/interface/src/views/landscape/components/GroupsPane.tsx
- pkg/interface/src/views/landscape/components/InvitePopover.tsx
- pkg/interface/src/views/landscape/components/Participants.tsx
- Fixes the chat input top border being cut off on dark mode Safari; rewrites the containers in indigo-react.
- Properly pins the unread notice; truncates the text for small browsers (urbit/landscape#106).
- Because we don't have a new DM route to handle the logic, just removes 'send message' from Participants view for now. (We need a utility to redirect and/or create a DM.)
- Stubs out the email invite prompt as per @vvisigoth.
- Fixes the styling of the channel dropdown in dark mode (urbit/landscape#109).
- Removes the secondary, 'recent groups' sort from the launch screen (urbit/landscape#111).
- Fixes an unfiled bug where the box-shadow was set to `rgba(0,0,0,0.1)` producing a weird, dark border in dark mode. We just pass the theme colour and inherit it, as we do elsewhere.
cc …
> interface: design feedback tweaks

- pkg/arvo/sys/vane/clay.hoon
This PR fixes a long-standing miscompilation in %clay, introduced in 8f66b6ff5f2c864f3477e4b029bc7d0dc472a0a7, found by experimenting with #3664, first (obliquely) reported in https://github.com/urbit/arvo/pull/914#discussion_r239579011.
> clay: refactors +cancel-request, consistently accounting for TMI

- pkg/interface/src/views/apps/launch/components/tiles/tile.js
Dropped this in the last PR — because we get boxShadow colour from inheriting it, Weather passing 'color' as a prop overwrite both the text and shadow, making them bright white. Tile props should be passed to their children, not necessarily their wrapper, so this moves the spread a layer down.
> launch: pass tile props to child

- pkg/urbit/jets/e/secp.c
ecdsa-raw-recover had an erroneous jet. This commit fixes the critical
error so that the jet returns the right result according to the secp
secp256k1 spec, although it still does not match the hoon. The hoon is
subtly wrong, and will be addressed in a future commit.
> vere: fix typo in secp reco jet

- pkg/arvo/app/link-store.hoon
It's burdensome to upgrade cards and vases, and in practice they will be stale anyway, so we throw them away.
Per https://github.com/urbit/urbit/pull/3544#issuecomment-708880202
> link-store: throw away state if it's stale cards

- pkg/interface/src/views/apps/dojo/components/history.js
- pkg/interface/src/views/apps/dojo/subscription.js
Connects to the SSE stream on `/~/slog` to receive printf output from the
runtime, and pretends those are incoming `%txt` effects.
Depends on #3557, which introduces the endpoint used here. Probably shouldn't be merged until that has gone out in a vere release? But this fails gracefully, so maybe we can pass on juggling pending PRs.
> webdojo: slogs

- pkg/arvo/app/chat-hook.hoon
Fixes #3710. Really straightforward, moved logic from +on-load to +poke-noun so as not to be caught in %gall's molting phase. I have tested on a fakezod upgrading from state-7 to state-10 and can confirm that it runs successfully.
This hack is extremely ugly, but we plan on deprecating %chat-hook as soon as next week, so this seems acceptable.
> chat-hook: hack to move scry to a new event to fix +on-load

- pkg/arvo/sys/vane/jael.hoon
- pkg/hs/urbit-king/lib/Urbit/King/Main.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Dawn.hs
The derivation of `+code` in jael was more complicated than it had to be, I first simplified it, and then I implemented it in Haskell as part of the Dawn module so we could print the code on initial boot. (I want to say that vere used to do that.)
> Simplify +code and implement it in KH.

- pkg/interface/src/views/landscape/components/ChannelMenu.tsx
Fixes an unfiled bug via @galenwp where accessing channel settings (or deleting the channel) in the home workspace redirected back to the hidden group path instead of the home workspace, wiping the sidebar content.
> landscape: check workspace in channel menu

- pkg/arvo/sys/vane/clay.hoon
In certain cases +find-merge-points was very slow.  Specifically, the
`done` set was meant to avoid checking the same commit repeatedly, but
it didn't catch the case where a commit was added to the worklist that
was already in that worklist.
Secondly, the worklist was stored as a list but used as a queue, which
resulted in a lot of unnecessary welding.  We change it to a qeu.
Fixes #3735
> clay: speed up +find-merge-points

- pkg/arvo/app/glob.hoon
- pkg/arvo/mar/map.hoon
- pkg/interface/config/webpack.prod.js
- pkg/interface/package-lock.json
- pkg/interface/package.json
- pkg/interface/src/logic/lib/util.js
- pkg/interface/src/views/apps/chat/ChatResource.tsx
- pkg/interface/src/views/landscape/components/Participants.tsx
This PR makes some changes to landscape's build configuration in order to decrease bundle size. Total reduction is from 10MB to 2MB. Have no hard numbers, but this should improve landscape's responsiveness across the board. 
Source maps have never worked correctly on production builds, and the
way that they are bundled into the JS itself negatively impacts our time
to first paint. As such, we disable them for a significant bundle size
improvement
Landscape is not localised in any fashion and we never change the
default locale. As such, the locales that moment.js includes in the
bundle are redundant and can be removed
Due to lodash's packaging mechanism, it is unable to treeshake unless
you always import from it in a certain fashion. This commit adds a babel
plugin to rewrite these imports …
> interface: various bundle size optimisations

- pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx
- Checks if we're in the home workspace or if we're admin of the group when displaying the 'new channel' button.
This is, of course, a lie if we don't also prevent this on back-end, but it's a stopper for now. Part 1 of resolving #3704.
> landscape: only show 'new channel' if admin

- pkg/interface/src/views/landscape/components/GroupsPane.tsx
- pkg/interface/src/views/landscape/components/NewChannel.tsx
- The 'ship search' prompt in the new channel menu shows in all workspaces; but it's only really necessary in the home workspace.
- In this PR we just hide it away when we're inside a group workspace, so inviting participants only happens from one place (the invite button in the sidebar)
> groups: new channel only shows ship search at home

- pkg/interface/src/views/landscape/components/Participants.tsx
If you type `~haddef-sigwen` into the participant search, nothing shows up. If you type `haddef-sigwen`, I do indeed show up. 
In this PR we just trim off the query's sig if it starts with it.
(Also fixes an unfiled bug where the search was case sensitive by accident, because we were comparing the `nickname.toLowerCase()` against the raw, `search` query, not `s` which is `search` transformed to `lowercase` itself.)
> groups: allow search to have sigs

- bin/solid.pill
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
...by over 90%, in the observed case.
Eyre keeps channel events in state until they get acked by a connected client, so that the client can catch up and resume operating after unexpected disconnects. Currently, Eyre stores the fully serialized versions of those events, in the format in which they're sent over the wire.
This PR makes Eyre lazy about serializing events coming from gall agents, delaying both the noun -> json, and json -> event-stream conversions until they're actually needed. Instead of storing serialized event-stream data in state, we simply store the `sign`s. This generally takes up less memory, and potentially makes use of noun deduplication to reduce the footprint even further.
The cost we pay is needing to reserialize in the "reconnected to channel with unacked events" …
> eyre: reduce memory usage of unacked channel events

- bin/solid.pill
- pkg/arvo/app/dbug.hoon
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
- pkg/interface/dbug/src/js/views/eyre.js
Intends to supersede #3680. This is the fancier implementation proposed therein.
Eyre keeps channel events in state until they get acked by a connected client, so that the client can catch up and resume operating after unexpected disconnects. Currently, Eyre does not react to rapid growth of those queues that might result from clients not sending acks.
This PR implements a mechanism for detecting such "[clogging](https://public-media.si-cdn.com/filer/1c/25/1c25dff1-03f2-4a64-8ef3-70721c533ca0/istock-177415966.jpg)", and proactively kicking subscriptions that are adding too many events to the queue.
If the client hasn't sent an ack for `~s30`, any subscription that accrues more than 50 unacked events gets closed to prevent further buildup.  
Upon reconnecting, the client will see `%kick` …
> eyre: kick busy subscriptions if client not acking

- pkg/interface/src/views/apps/chat/ChatResource.tsx
Addresses #3748.
We destructure envelopes and config from the station inside our inbox unsafely; and if you navigate away mid-join, you can sidestep the join flow and see the view before the props are instantiated — causing a consistent crash when you navigate to the room, until the full backlog hits our ship and the messages load in on a subsequent refresh.
By safely instantiating (more elvis operators!) we can avoid the crash, which nicely enough shows the "Past messages are being restored" notice while we wait, which I haven't yet seen in nu-groups, so it seems to be functioning normally.
> chat: prevent crashes if join is interrupted

- pkg/interface/src/logic/lib/sigil.js
- pkg/interface/src/views/apps/chat/components/ChatInput.tsx
- pkg/interface/src/views/apps/chat/components/overlay-sigil.js
- pkg/interface/src/views/components/StatusBar.js
- pkg/interface/src/views/components/leap/OmniboxResult.js
As per mockups. Tagging designers since the changes are 'passing a prop', but when and where we should use the icons is the question here.
> interface: use icon sigils for <16px renders

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/apps/chat/components/content/code.js
1. Multi line hoon evaluations now have `white-space: pre` to preserve line breaks, etc.
2. Unread marker has a little bit more padding to even out its location in the log (was slightly too close to preceding messages). Still some weird cases when between authors but we may just have to equalise last message / next author padding amounts. (Also is rewritten in indigo-react.)
> chat: hoon eval whitespace, unread marker padding

- pkg/arvo/gen/metadata-store/remove.hoon
Adds a `|remove` generator, to allow group owners to remove channels that they do not control, but wish to remove from the group.
> metadata-store: add |remove generator

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
Before:
After:
cc @tylershuster is there some reason we were using `items-center` on all these besides this timestamp?
> chat: timestamps are lined at top of messages

- pkg/interface/src/views/apps/publish/components/MarkdownEditor.tsx
- pkg/interface/src/views/apps/publish/components/MarkdownField.tsx
- pkg/interface/src/views/apps/publish/components/NoteForm.tsx
See urbit/landscape#117.
Would appreciate a once-over on Firefox and the like, but seems to look fine on all sizes on Webkit.
> publish: prevent post input overflowing layout on safari

- pkg/interface/src/views/apps/chat/components/chat-editor.js
In order to get "normal" (expected) text input behavior on mobile, typing needs to occur in a proper input element. 
https://github.com/codemirror/CodeMirror/blob/2571b4ad08e007c246d73bdd973892bf5dd7b02e/src/edit/options.js#L78
As you can see above, codemirror (despite exposing the option) does not allow changing the input type to a textarea on mobile. Therefore, expected behavior is impossible.
This PR detects mobile browsers and falls back to regular HTML input — no code highlighting, no image pasting. Fortunately, those aren't really things we need on mobile.
It uses a JavaScript proxy object so that existing CodeMirror behavior doesn't have to be altered.
The experience is miles ahead. I have tested it on iOS and Android (simulated via Android Studio)
> chat: fall back to native input on mobile

- pkg/interface/src/logic/reducers/graph-update.js
- pkg/interface/src/views/apps/links/LinkResource.tsx
Pre-graph-store links that were brought over use @da as their index,
however new links use a unix timestamp as their index. Pending a proper
fix, we instead just normalize all the indexes to be unix timestamps
inside the reducer.
> graph-js: normalize keys in reducer

- pkg/interface/src/views/apps/publish/components/GroupifyForm.tsx
- pkg/interface/src/views/components/GroupSearch.tsx
Part of #3704 work — just only lists groups we admin in the groupify list if we pass `adminOnly` as a prop.
Side note: Currently only Publish has a groupify form at all, so might want to take a sec and add it to the other unmanaged settings pages again...
> landscape: add 'admin only' check to groupify form

- pkg/interface/src/views/apps/chat/ChatResource.tsx
- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
- pkg/interface/src/views/apps/chat/components/overlay-sigil.js
- pkg/interface/src/views/apps/chat/components/profile-overlay.js
- pkg/interface/src/views/components/DropdownSearch.tsx
- pkg/interface/src/views/components/ShipSearch.tsx
- pkg/interface/src/views/landscape/components/GroupsPane.tsx
- pkg/interface/src/views/landscape/components/InvitePopover.tsx
- pkg/interface/src/views/landscape/components/NewChannel.tsx
- pkg/interface/src/views/landscape/components/Participants.tsx
- pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx
- pkg/interface/src/views/landscape/components/Sidebar/SidebarListHeader.tsx
- pkg/interface/src/views/landscape/components/Skeleton.tsx
- pkg/interface/src/views/landscape/index.tsx
- Places DM creation / redirection logic at `/~landscape/dm/:ship`.
- Pulls 'allStations' prop plumbing out of all the chat components, remove DM creation logic from profile overlay, just redirects to the DM route.
- Restores "Send Message" option in Participants list.
**Still to be done**:
- A general 'DM creation' prompt — part of me wondered if it would be easier to just weave in "Direct Message" instead of "Chat" when in NewChannel.tsx in the home workspace, but I don't know how to make Formik less aggressive about required values (much as it is with Publish).
That is, we want it to only prompt us to name the chat if there's multiple members in the direct message; if there's only one participant, we want to just ship it over to the "new / redirect DM" route.
I also thought we could …
> chat: create dm route, restore participants option

- pkg/urbit/include/noun/vortex.h
- pkg/urbit/noun/manage.c
- pkg/urbit/noun/vortex.c
This PR is a substantial performance improvement for the vere king.
On every turn of the libuv event loop, we update a global `@da` timestamp, so that all i/o drivers can have a consistent view of time. The function that we use to do so (`u3v_time()`) was also formatting that same timestamp, through a nock call to hoon's atom (`$coin`) printer. That's an expensive call, with no relevant high level jets (at the moment, see #2853). But, even worse, that formatted timestamp was never read or used anywhere.
I discovered this issue while debugging the network forwarding loop reported in #3778. So I used the loop as a simple performance test. As the following flame graph makes clear, samples were dominated by `u3v_time()`.
Those samples were taken roughly every millisecond, for around 90 …
> u3: remove timestamp printing in u3v_time()

- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
I double-confused myself. The comment here made me think I was fine just storing the moves in reverse order, but of course I have to _produce_ them in the correct order. Also Arvo uses sane move order, so the test was wrong to begin with.
https://github.com/urbit/urbit/blob/235bfbbd2faf3184481558bad09108a8f69e91c3/pkg/arvo/sys/vane/eyre.hoon#L1050-L1052
> eyre: produce moves in correct order

- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
When an application would send multiple facts during a single event, it was possible for one fact to trigger a clog, removing the subscription and sending a quit, but then subsequent facts still getting sent out at normal.  
Getting facts after receiving a quit seems slightly weird, especially considering clients sending out resubscribes based on the point at which they lost the subscription.
Here, we drop any facts for subscriptions we don't have registered in state, which should only happen in the described case.
> eyre: ignore facts directly after clog

- pkg/arvo/sys/vane/ames.hoon
To help avoid routing loops (see #3778), this PR updates the %ames' `/peer/<ship>/forward-lane` scry handler to exclude ourselves from possible routing targets. To precisely match the forwarding semantics in `+send-blob:event-core`, it also produces both the peer's and peer's sponsoring galaxy's routes, when the route to the peer is indirect.
> ames: updates forward-lane scry-handling to prevent routing loops

- pkg/urbit/vere/io/ames.c
With a focus on packet-parsing, stateless forwarding, and galaxy address resolution.
The packet parsing (original in `_ames_recv_cb()`) did not sufficiently protect against strange lengths, and could underflow the buffer-length (which was signed). The parsing logic was also mixed together with the forwarding logic. These things have been factored out from each other.
The packet parsing and serialization involved a bunch of unnecessary allocations and representation changes, these have been mostly replaced with direct implementations (but there's still a bunch of unnecessary allocations in the higher-level packet flows).
The protocol-version checking/enforcement is incomplete in various ways, this PR includes comments documenting various scenarios we need to support to varying degrees.
I …
> vere: refactors ames i/o driver

- bin/solid.pill
- pkg/arvo/app/chat-cli.hoon
- pkg/arvo/app/dojo.hoon
- pkg/arvo/lib/bip32.hoon
- pkg/arvo/lib/language-server/build.hoon
- pkg/arvo/mar/lens/command.hoon
- pkg/arvo/mar/publish/info.hoon
- pkg/arvo/sys/hoon.hoon
- pkg/arvo/sys/zuse.hoon
Resolves conflicts in #2949, thanks to @jfranklin9000 for all the actual work.  This has languished since May since it was difficult to OTA correctly.  Since then, Ford Fusion made this sort of update easy and reliable, so I tested the OTA now and it works fine.
For the merge I did the dumbest possible thing, which leaves two notable areas using the old parser names: lib/language-server/parser and clay, since at that time the ford parsers were in ford.hoon.  The old parser names still exist, so maybe this is fine, else we could update those.
> hoon: update glyph names

- pkg/arvo/gen/configure-hosting.hoon
- pkg/hs/urbit-king/TODO.md
- pkg/hs/urbit-king/lib/Urbit/King/CLI.hs
- pkg/hs/urbit-king/lib/Urbit/King/Main.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs
This makes it so during `run`, you can inject a series of Events
into your Urbit. The `-I` injection was implemented in Vere, and
has been ported to KH, with the extended `--inject-event-list`
flag which handles a jammed list of events.
Also included is a sample generator which builds a list of events.
> king: implement -I and --inject-event-list

- pkg/interface/src/views/components/leap/Omnibox.js
- Return 'other' results first because "Home" was getting buried by channels when those types of results should be returned first (though exact results should also always be weighted, see #3705)
- Searching for group names was accidentally case sensitive; now it's not.
> leap: return 'other' first, lowercase groups

- pkg/interface/src/views/apps/chat/components/content/code.js
- pkg/interface/src/views/apps/chat/components/content/text.js
- pkg/interface/src/views/apps/chat/css/custom.css
Wraps inline / blocked code in indigo-react components to match our theme; rely less on custom CSS, etc. See urbit/landscape#124.
Kudos @tylershuster (and yes, I did test to avoid overflow regressions ...)
> chat: indigo-react inline code

- pkg/interface/src/views/apps/launch/components/tiles/clock.js
Fixes https://github.com/urbit/landscape/issues/110 (again)
SVG arc spec has a flag to draw "a large arc" which is what caused the bulbing out needing a mask. If we weren't masking, we'd want to be particular about when to draw a large arc and when not to. But if we don't draw a large arc, and we're supposed to, we get the emaciated behavior shown in the last comment on 110.
Normally you'd just get the distance of the arc and if it's greater than 180 you'd set the flag. But because we're dealing with angles that are greatly above 360 or below 0, instead of doing all the clamping and `Math.abs`ing, let's just always draw the large arc and mask out the overflow.
> For with much wisdom comes much sorrow; the more knowledge, the more grief.
> clock: always draw large arc

- pkg/arvo/app/chat-cli.hoon
- pkg/arvo/app/chat-hook.hoon
- pkg/arvo/app/chat-view.hoon
- pkg/arvo/app/contact-hook.hoon
- pkg/arvo/app/contact-view.hoon
- pkg/arvo/app/invite-hook.hoon
- pkg/arvo/app/invite-store.hoon
- pkg/arvo/app/publish.hoon
- pkg/arvo/lib/invite-json.hoon
- pkg/arvo/mar/invite/action.hoon
- pkg/arvo/mar/invite/update.hoon
- pkg/arvo/sur/invite-store.hoon
- pkg/arvo/ted/graph/create.hoon
- pkg/interface/src/logic/api/invite.ts
- pkg/interface/src/logic/reducers/invite-update.ts
- pkg/interface/src/views/apps/launch/components/Groups.tsx
- pkg/interface/src/views/landscape/components/Sidebar/SidebarInvite.tsx
No functionality or logic has been changed, just reorganized to be clearer and more in line with the modern style. We also no longer use the %json mark on the frontend to speak to %invite-store, instead relying on mark conversions.
Edit:
- The `%graph-create` thread should have been sending invites when it was handed an unmanaged resource with an invite policy, but it was not. It now is.
> invite-store/hook: modernize the code style to match other new apps

- pkg/interface/src/views/apps/launch/app.js
- pkg/interface/src/views/apps/launch/components/Groups.tsx
A front-end fix for #3800 until urbit/landscape#72 lands.
The launch screen iterates through `associations.contacts` to list group tiles; by using our metadata-store instead of the group-store, it inherits the "group metadata isn't deleted" bug in #2992. To the user, this is confusing — groups they're kicked out of and groups they delete alike will still persist on the launch screen (but groups they manually leave will correctly tell metadata-store to delete the data?), so it appears as though the group itself cannot be deleted.
This PR passes our groups into that logic and filters the metadata to verify we only list groups we currently actually have.
> launch: filter out metadata for deleted groups

- pkg/interface/src/views/apps/profile/components/lib/BackgroundPicker.tsx
- pkg/interface/src/views/apps/profile/components/lib/DisplayForm.tsx
- pkg/interface/src/views/components/ColorInput.tsx
Uses ColorInput instead of a regular text Input to bring background color selection inline with the rest of landscape
> Profile: use ColorInput for background

- pkg/interface/src/views/apps/links/LinkResource.tsx
- pkg/interface/src/views/apps/links/components/link-item.js
See #3045. If we're the submitted link's author, surfaces a 'delete' button to delete the node.
cc @tacryt-socryp Back-end wise, does the permission line up here?
> links: add link deletion

- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
Reverts urbit/urbit#3799. It was accidentally merged into master, but should've targetted next-sys instead. Reverting to regain parity between master and livenet.
> Revert "eyre: ignore facts directly after clog"

- pkg/interface/src/views/components/VirtualScroller.tsx
Fixes #3801
This just checks if the thing we're hovered over as we scroll has *its own* scrollbar, and doesn't apply the inversion and subsequent pseudoscroll if so
> chat: fixed embedded scroll item disability

- pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
See #3805.
The top item in the group switcher:
- If we're in the home workspace, links to "All Groups" as per livenet.
- Otherwise, links to the home workspace.
> landscape: 'home' workspace in switcher

- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Multi.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Serv.hs
This should fix the problem where shutting down urbit-king, and then immediately starting it up again changes the http port. I hit this all the time and it is super annoying.
Fixes #3822
> king: cancel http servers immediately on shutdown.

- pkg/hs/urbit-king/lib/Urbit/King/App.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ames.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ames/LaneCache.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ames/Packet.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Serf/IPC.hs
- pkg/hs/urbit-king/package.yaml
- pkg/hs/urbit-king/test/AmesTests.hs
- pkg/hs/urbit-noun/lib/Urbit/Noun/Conversions.hs
- pkg/hs/urbit-noun/package.yaml
Our version of #3174 and #3405.
When the king receives a packet, he parses it and determines if it is for a ship other than himself. If so, he forwards it without involving the serf, except that he from time to time scries the serf for information on the routes ("lanes"/"AmesDests") stored for ships he wishes to forward to. Additionally, he drops packets that are malformed, have the wrong version number, or which are bound for ships that we don't have a route to.
Test plan.
Change the logDebug to a logInfo on L258 and add the following code at L259 of Ames.hs:
```
if encode pkt == b
then logInfo $ displayShow ("ames: packet match")
else logInfo $ displayShow ("ames: packet mismatch", encode pkt, b)
```
Throughout, verify that we have only "packet match" messages.
1. Run your own ship with …
> Implement stateless forwarding in the king

- pkg/hs/urbit-eventlog-lmdb/lib/Urbit/EventLog/LMDB.hs
Previously, the mapsize was 10 GiB. This change increases it to 1 TiB, which should be the same that the c king uses.
When I tried to switch ~def over to kh for testing, I found that the ship would promptly crash because of this discrepancy.
> king: increase lmdb max mmap size for parity with vere

- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/zuse.hoon
Continuation of #2962. In addition to respecting the original address, we now also set the `secure` flag based on whether or not the request originally came in over HTTPS.
Not relevant to Eyre as it exists in next-sys right now, but there's incoming changes around cookie handling and such that want to know whether the "real" connection is secure or not.
cc @brendanhay, if Horizon doesn't already, it's going to want to tack on a `Forwarded` header to specify these details.
> eyre: respect protocol from Forwarded header

- pkg/hs/urbit-king/lib/Urbit/King/CLI.hs
- pkg/hs/urbit-king/lib/Urbit/King/Main.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Dawn.hs
@philipcmonk mentioned that we didn't have this option in KH a little while ago. This option is useful both for debugging Ethereum issues, and for sovereignty reasons, where you don't want to trust our Eth nodes.
> king: port the '-e' option to specify ethereum node endpoint.

- pkg/interface/src/views/App.js
This puts firefox at parity with chrome — it's only a problem on the launch screen, but it should be this way anyway
> landscape: fixes white background on scrollbars

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
Previously extensions ending with numbers such as `.woff2` were not recognized.
Observe:
```
(rash '/~landscape/fonts/inter.woff2' apat:de-purl:html)
[p=~ q=<|~landscape fonts inter.woff2|>]
```
Now: 
```
(rash '/~landscape/fonts/inter.woff2' apat:de-purl:html)
[p=[~ ~.woff2] q=<|~landscape fonts inter|>]
```
> zuse: improve url extension parsing

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx
- The new channel container had some padding leftover when its child was hidden, preventing users from clicking bottom channels; we hide the container itself now
- I was going to add `flex-shrink` to the daystamp in the unread marker, but it always provided useless data for its intended use case (eg. staggering the daybreak + unread marker instead of combining them, see below) so I just remove it.
> landscape: hide new channel container, daybreak in unread marker

- pkg/interface/src/logic/lib/publish.ts
This is the same fix as https://github.com/urbit/urbit/pull/3856
@liam-fitzgerald does this have something to do with the work you mentioned on bigints earlier? `===` checks are failing because of a JS variable type and I haven't looked deeply into it but my intuition tells me a) that's the issue and b) you might know something about a holistic pass to remedy the issue rather than adding `valueOf()` piecemeal
> publish: fixes #3859, fixes #3844

- pkg/arvo/app/hark-graph-hook.hoon
- pkg/arvo/lib/graph-store.hoon
- pkg/arvo/mar/graph/validator/link.hoon
- pkg/arvo/sur/post.hoon
- pkg/interface/src/logic/api/graph.ts
- pkg/interface/src/logic/lib/graph.ts
- pkg/interface/src/types/graph-update.ts
- pkg/interface/src/views/apps/links/components/comment-item.js
- pkg/interface/src/views/apps/links/components/comment-submit.js
- pkg/interface/src/views/apps/links/components/comments.js
- pkg/interface/src/views/apps/publish/components/CommentItem.tsx
- pkg/interface/src/views/apps/publish/components/Comments.tsx
- pkg/interface/src/views/components/MentionText.tsx
- pkg/interface/src/views/components/RichText.js
- Adds a %mention type to +content:post
- hark-graph-hook scans for %mentions of our own ship instead of doing wacky text processing
- Links, publish now tokenise mentions before sending to backend
- Mentions in comments are highlighted and replaced with the nickname, if any.
Visual demo:
> hark, graph-store: mentions support.

- nix/lib/test-fake-ship.nix
with intervening |mass measurements (the before/after `~&` printfs ensure that `stderr` output is fully captured).
> test: cleans up output, adds |trim and |meld

- pkg/arvo/sys/vane/clay.hoon
Motivation for the change is performance improvements on the un-`^~`d uses of
`+ream`. Parsing turns out to be slow, making `+ream` slow in turn. So we construct
the hoon ast manually instead.
`!,` is arguably better style than ream, since it doesn't necessitate a `^~` for static
input, and lets syntax highlighting function properly.
For the investigated case, in `+get-cast`'s +grow flow, improves performance by
over 80%.
> clay: replace ream with nouns and !, zapcom

- pkg/urbit/vere/io/http.c
The default was 1 GiB, which seems high.
(This is not a pressing issue, but I had made a note to change it, and I want to test hercules-ci with a PR from a fork.)
> vere: set maximum http request to 512 MiB

- pkg/urbit/vere/disk.c
- pkg/urbit/vere/pier.c
The previous behavior was to simply wait for the next snapshot timer, but it's better to save eagerly.
> vere: save snapshot upon completed replay

- pkg/arvo/sys/vane/eyre.hoon
Pretty-printing is expensive, yet we do it whenever we construct the cookie string, at least once (but usually twice) per authenticated request.
Here we call out to the specific to-tape functions we need, instead of relying on the pretty-printer for converting... tapes to tapes, among other things.  
The primary gains come from the cookie-related instances, we update the others mostly for good style.
For the "receive request and immediately send response" case, that is processed synchronously within eyre and doesn't touch anything else (ie, client sends channel ack), speeds thing up by roughly 55%.
> eyre: forego <atom> in favor of (scow %aura atom)

- pkg/interface/src/views/apps/publish/components/Author.tsx
Fixes an accidental regression — we were looking for `ship.slice(1)` in our contacts, but the `ship` prop had no sig anyway, so it always came up `false` in notes and comments.
> publish: restore nicknames in note interface

- nix/pkgs/urbit/default.nix
Poached from @eglaysher's work in #3380.
> vere: remove dependency on nix-store path for static darwin binary

- ci.nix
- nix/lib/boot-fake-ship.nix
- nix/lib/test-fake-ship.nix
- nix/pkgs/urbit/default.nix
- pkg/arvo/lib/hood/drum.hoon
Contains the following debug-related changes:
* Exposes `urbit.meta.arguments` which will contain `[ "-g" ]` when `enableDebug = true`.
* `lib/{boot,test}-fake-ship.nix` will now exec the `urbit` binary with any of the derivation's `urbit.meta.arguments`.
* `dontStrip = true` is now set by default.
> vere: enable GC argument when running tests with debug binary

- ci.nix
- nix/lib/default.nix
- nix/lib/effect/default.nix
- nix/lib/effect/effects-setup-hook.sh
- nix/lib/make-release-tarball.nix
- nix/lib/push-storage-object.nix
- nix/pkgs/pill/builder.nix
This removes the need to calculate sha256/md5 hashes on the tarballs or pills which were used as part of the `gsutil` gymnastics to perform idempotent uploads.
The effects now run at the end of build, but unfortunately didn't have quite the positive performance impact I was hoping for - only a very small improvement. They do run inside a special sandbox though, so we get sandboxes inside sandboxes, life isn't all bad.
Depends on #3886
> build: replace push-storage-object fixed output derivation with hercules ci effect

- pkg/arvo/sys/vane/dill.hoon
People using older runtimes might not support the `%klr` blit. It's not
uncommon for prompts without style to get passed in as `%pom` though, so
here we catch that case and turn it into a `%pro`, which gets rendered as
a traditional `%lin`.
With this, dojo and chat-cli remain usable under `next-dill`, even on `v0.10.8`. This allows us to consider pushing `next-dill` out more quickly after the release of `next-vere`, if we want. Note that old runtimes will still silently swallow _actually styled_ text. cc @vvisigoth 
(Arguably drum/sole should be more nuanced about this, but the code here sticks more closely to the original change location, which seems appropriate for a temporary, compatibility-oriented patch.)
> dill: if styled prompt has no style, emit as plain

- pkg/arvo/app/graph-pull-hook.hoon
- pkg/arvo/lib/push-hook.hoon
- pkg/arvo/ted/ph/lib-hooks.hoon
- Fixes a bug where paths that had been kicked and rewatched would not receive new updates after receiving the backlog from the initial rewatch.
- Adds a ph test to validate that this rewatch-after-kick logic works correctly. 
- On migrate, kicks all rewatched paths so they can get the new updates
> lib-hooks: fix %kick bug

- pkg/arvo/lib/push-hook.hoon
%remove did not properly iterate over the paths and as such did not
return a complete list of paths to kick.
Fixes #3868
> lib-push-hook: fix behaviour of %remove

- pkg/arvo/app/graph-pull-hook.hoon
- pkg/arvo/lib/graph.hoon
Scries to see if we already have the graph, and only then do we archive it. 
Unrelated, but how the hell does lib/graph work here if we aren't passing it the bowl?
> graph-pull-hook: only archive if we have graph

- pkg/urbit/noun/manage.c
This PR refactors the nock runtime exception generator, `u3m_bail()`. A subset of bail motes (`%foul`, `%oops`, `%meme`) are always treated as fatal errors, but this was inconsistently handled: `abort()` in one case, `assert(0)` in another. (@brendanhay, I think this may have been the cause of the hanging-on-error behavior you observed, although I haven't been able to reproduce it.)
Additionally there was an assertion in the presence of a "namespace block" bail (`%need`), but that is obsolete (the interpreter bails with `[%1 (list path)]` in the case of a blocked namespace read).
>  u3: refactors fatal exception handling in u3m_bail()

- pkg/arvo/app/glob.hoon
- pkg/arvo/app/hark-chat-hook.hoon
- pkg/arvo/app/hark-store.hoon
- pkg/arvo/app/landscape/index.html
- pkg/arvo/lib/hark/chat-hook.hoon
- pkg/arvo/lib/hark/store.hoon
- pkg/arvo/mar/hark/chat-hook-action.hoon
- pkg/arvo/mar/hark/chat-hook-update.hoon
- pkg/arvo/sur/hark-chat-hook.hoon
- pkg/arvo/sur/hark-store.hoon
- pkg/interface/src/logic/api/hark.ts
- pkg/interface/src/logic/reducers/hark-update.ts
- pkg/interface/src/logic/store/store.ts
- pkg/interface/src/logic/store/type.ts
- pkg/interface/src/logic/subscription/global.ts
- pkg/interface/src/types/hark-update.ts
- pkg/interface/src/views/apps/chat/ChatResource.tsx
- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
- pkg/interface/src/views/apps/chat/css/custom.css
- pkg/interface/src/views/apps/notifications/chat.tsx
- pkg/interface/src/views/apps/notifications/header.tsx
- pkg/interface/src/views/apps/notifications/inbox.tsx
- pkg/interface/src/views/apps/notifications/notification.tsx
- pkg/interface/src/views/apps/notifications/notifications.tsx
- pkg/interface/src/views/components/FormikOnBlur.tsx
- pkg/interface/src/views/landscape/components/ChannelMenu.tsx
- pkg/interface/src/views/landscape/components/Resource.tsx
- pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
Drafting, pending frontend changes being finished, just wanted get a pass on the hoon real quick. 
EDIT: Now ready to go!
- No mentions? We could get this by scanning the text of the messages, and chat-cli apparently does this anyway, but not implemented here. 
- Chat can now teleport to arbitrary messages by passing `msg` query param of the message number. This produces a highlighting effect on the message being teleported to. This way, clicking on a message in the inbox takes you exactly  to the message. 
Demo frontend:
> hark-chat-hook: Notifications

- pkg/urbit/jets/e/fl.c
This PR includes fixes for the obvious, visually-identified double-counted references mentioned in #3657. It's a draft, as this code has no tests, I'm not very familiar with it. I'll revisit once I've sufficiently tested manually. (Unit tests for our floating point implementation would be very nice to have ...)
> u3: fixes incorrect double ref-counting in |ff jets

- pkg/urbit/vere/io/term.c
We should tell people about `-t` instead of calling `c3_assert(0)`.
> vere: print error and exit if stdin is not a tty

- pkg/arvo/lib/verb.hoon
Instead of passing in a tape to print in case we need in, pass in a trap that
can be called to generate the tape on-demand.
Eagerly rendering printouts was costing us a lot of time when we didn't actually
need them, because the pretty-printer is slow.
> verb: render printouts lazily

- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
Eyre's clog logic was a tad inconsistent about "only facts" vs "not poke-acks". This makes it consistently say "only facts" when it comes to clog-related logic.
Yes, in theory this means `%watch-ack`s and `%kick`s can build up endlessly, but those should take up negligible space compared to %facts.
Should fix any oddball cases of crashes here that #3835 didn't already catch.
> eyre: clog exclusively for %facts

- pkg/arvo/app/hark-graph-hook.hoon
- pkg/arvo/lib/graph-store.hoon
- pkg/arvo/lib/hark/graph-hook.hoon
- pkg/arvo/mar/graph/validator/link.hoon
- pkg/arvo/mar/graph/validator/publish.hoon
- pkg/arvo/sur/hark-graph-hook.hoon
- pkg/interface/src/logic/api/hark.ts
- pkg/interface/src/logic/lib/notification.ts
- pkg/interface/src/logic/reducers/hark-update.ts
- pkg/interface/src/types/hark-update.ts
- pkg/interface/src/views/apps/notifications/notification.tsx
- pkg/interface/src/views/landscape/components/ChannelMenu.tsx
Follow individual indices in graph-store, and notify when an immediate child is created. In order to bypass potentially empty indices the notification-kind type is now `(unit [@t @ud])` where the `@ud` describes the length of the parent index.
> hark: follow individual indices 

- pkg/arvo/app/graph-store.hoon
Runs all updates in one event, so as to not involve IO when it's unnecessary. 
Sidenote: The `update(resource.q resource)` pattern is suspicious to me, shouldn't we really be checking equality and crashing otherwise? Maybe useful for copying a graph I guess, but idk.
> graph-store: run-updates no longer pokes itself

- pkg/interface/src/views/apps/notifications/chat.tsx
- pkg/interface/src/views/apps/notifications/header.tsx
- pkg/interface/src/views/apps/notifications/inbox.tsx
- pkg/interface/src/views/apps/notifications/notification.tsx
Fixes an interface crash when receiving rich media in notifications.
> hark: pass remotecontentpolicy to chat notifications

- pkg/arvo/app/chat-cli.hoon
- pkg/arvo/app/dojo.hoon
- pkg/arvo/lib/graph-store.hoon
- pkg/arvo/lib/language-server/parser.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/zuse.hoon
See: https://github.com/urbit/urbit/pull/3787
I tested by deleting the deprecated parsers in `hoon.hoon`, although that's not part of the PR.
I made a fakezod with this PR and the deletions.
```
urbit -A pkg/arvo -B bin/solid.pill -F zod
```
Then I made a new pill and made a fakezod from that too.
```
.fixup/pill +solid
^d
urbit -B zod/.urb/put/fixup.pill -F bus
```
This all worked.
I will start the conversion of `%bscl` to `%bccl`, etc.
I didn't commit a pill.
Is this the correct branch for this PR?
> hoon: update glyph names (continued)

- pkg/interface/src/views/apps/notifications/graph.tsx
- pkg/interface/src/views/apps/notifications/notification.tsx
See #3931. If you get a comment on a Link collection or a note with an image or a video, `<RichText>` will process it for our remote content preferences, but that's not passed to it.
> hark: fix crash on comments with remote content

- pkg/arvo/app/graph-store.hoon
Correctly subset in scries, so we aren't sending updates that we already have from the log. This was the cause of urbit/landscape#157 .
> graph-store: correctly subset in scries

- package-lock.json
- pkg/arvo/app/hark-store.hoon
- pkg/arvo/lib/hark/store.hoon
- pkg/arvo/sur/hark-store.hoon
- pkg/interface/src/logic/api/hark.ts
- pkg/interface/src/logic/reducers/hark-update.ts
- pkg/interface/src/logic/store/store.ts
- pkg/interface/src/logic/store/type.ts
- pkg/interface/src/types/hark-update.ts
- pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
- pkg/interface/src/views/apps/launch/app.js
- pkg/interface/src/views/apps/launch/components/Groups.tsx
- pkg/interface/src/views/apps/notifications/graph.tsx
- pkg/interface/src/views/apps/notifications/header.tsx
- pkg/interface/src/views/apps/notifications/inbox.tsx
- pkg/interface/src/views/landscape/components/Skeleton.tsx
Reworks the caching so that we keep a `(jug index @da)` as a cache of what indices have unread notifications in what timeboxes. Uses this cache to unify the unread handling and add a `%read-index` poke, which allows us to automatically read notifications when we mark a chat as read. Additionally, adds unread counts to group tiles as seen below.
Also includes assorted bugfixes:
- Cleans up UX of accepting a group invite from the invite (#3924 )
- Does not mark notifications as unread when their content is navigated to (#3920 )
- Fixes ordering and loading of notifications (#3929 )
- Fixes an issue where the color of the transparency on publish note notifications would not adjust with theme
- Enables scrollback on archived notifications
> hark: rework caching to allow for better unread counts, read all by index

- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/sys/zuse.hoon
Only treat an address as a comet if it's bigger than 64 bits.  Otherwise, a comet could impersonate a different kind of ship, which posed security problems.  This PR changes comet generation in Zuse, and comet validation in Ames.  I'm not aware of other places where this validation would be necessary, but it's possible others exist.
> no more impostor comets

- pkg/arvo/sys/zuse.hoon
This PR includes the hoon changes from #3180, which has the context and previous discussion. The vere changes are in #3523.
For the best user experience (ie, performance), these changes should not be released OTA until the vere changes have been released, and users have had time to upgrade. As a result, ie, since its target is a moving target, this PR doesn't (yet) include pills.
> arvo: accept embedded nulls in to-wain:format

- pkg/interface/src/views/apps/notifications/chat.tsx
(Should) address urbit/landscape#161.
Chat notifications, unlike graph notifications, ask for metadata for render in a way that can lead to a crash if we don't have the metadata for whatever reason. This PR attempts to gracefully handle those errors:
- We look for the app path from the notification data itself, not from the association;
- We allow the groupPath to fall back to `undefined`;
- If our group path is `undefined` then the notification will redirect us to the chat inside of the home workspace (where the chat, if it has no group path, probably is anyway).
> hark: handle "no chat metadata" errors

- pkg/interface/src/logic/lib/util.ts
- pkg/interface/src/views/apps/profile/profile.tsx
- pkg/interface/src/views/components/ColorInput.tsx
- pkg/interface/src/views/landscape/components/ContactCard.tsx
- pkg/interface/src/views/landscape/components/GroupsPane.tsx
- pkg/interface/src/views/landscape/components/PopoverRoutes.tsx
I was wrong about the issue in #3875 — the issue was the rewrite of the `hexToUx` utility into TypeScript, which instead of returning a string dumped a JS blob into the field. Why it worked properly when the contact information existed, I don't know. So now you can set all your information before sharing your contact information, without having to share the empty contact first, as expected.
Also fixes an unfiled issue where the color input processing assumed all information began with `0x`, as it does in group colour metadata but not in contact card defaults (which just used `0`), so it would show a different colour than what you submitted because it would chop off the first two characters.
Instead of falling back to an empty contact card, it falls back to our root identity and says …
> landscape: fix broken sharing of contact information, prefill with root identity

- pkg/interface/src/views/apps/chat/components/content/text.js
- pkg/interface/src/views/components/VirtualScroller.tsx
This reverts commit 3b5d3c6ff6a288cbf0d659cdb84183baa3bd8d6e.
@tylershuster This doesn't seem to actually fix the issue with reversed scrolling in embeds and introduces additional bugs for users when scrolling down, any objections here?
> Revert "chat: fixed embedded scroll item disability"

- pkg/interface/src/logic/lib/useDropdown.ts
Fixes #3954
Looks like somewhere along the way the dropdown started adding exact matches without checking to see if the match was also in the candidates. This should be fine across the board — if a candidate is also an exact match, we only show one of them.
> landscape: preclude dropdown duplicates on exact match

- pkg/interface/src/views/apps/notifications/inbox.tsx
- pkg/interface/src/views/components/Invite.tsx
- pkg/interface/src/views/components/StatusBar.js
- pkg/interface/src/views/components/leap/OmniboxResult.js
- pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx
- Moves `SidebarInvite` to components and calls it `InviteItem`
- Removes invite logic from the sidebar, moves all invites for all apps to the inbox instead
- Changes the check for 'a dot' accordingly
See #3925.
It would be cool if we could display if it was a chat or the like — but invite-store provides us with `graph-push-hook`, not any metadata, ahead of time.
> landscape: show all invites in inbox

- bin/solid.pill
- pkg/arvo/app/dojo.hoon
- pkg/arvo/gen/ivory.hoon
- pkg/arvo/gen/solid.hoon
- pkg/arvo/lib/language-server/complete.hoon
- pkg/arvo/lib/language-server/easy-print.hoon
- pkg/arvo/lib/pprint.hoon
- pkg/arvo/lib/xray.hoon
- pkg/arvo/sys/hoon.hoon
- pkg/arvo/sys/vane/clay.hoon
- I'm not sure how to create a bootable pill with these changes.
- `pkg/arvo/lib/pprint.hoon` may have a bug.
See these lines (403 and 406):
`XX %tsld to %tsgl, but should be %tsgr? (to match =>)`
`XX %tsbn to %tsgr, but should be %tsgl? (to match =<)`
> hoon: bscl to bccl, etc

- pkg/arvo/app/dojo.hoon
- pkg/arvo/app/lens.hoon
- pkg/arvo/mar/lens/command.hoon
- pkg/arvo/sur/lens.hoon
- pkg/herb/herb
- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/io/fore.c
- pkg/urbit/vere/pier.c
Part of the [data migration](https://github.com/urbit/urbit/pull/3604) work. This PR adds -i and -o flags for import and export.
I moved the commit for the herb/lens changes from the linked PR to this one, because its a dependency for this work, and it looks like this work will land first. Even so, just using this naively in its current state will not work because the lens changes depend on changes to the apps in that PR. To test this, just change the `+on-peek` arm in lens to return a constant for `%export-all`.
The import flow, while gross, I believe does not break anything. Making an http request with no place to put the response appears to just cause the http server to reset.
The way to invoke this is 
to export: `urbit -o <pier>` (or to specify the output path: `urbit -o -Y …
> vere: add flags for import and export

- .github/workflows/build.yml
- pkg/hs/proto/lib/SimpleNoun.hs
- pkg/hs/proto/lib/Untyped/CST.hs
- pkg/hs/proto/lib/Untyped/Core.hs
- pkg/hs/proto/lib/Untyped/Parser.hs
- pkg/hs/proto/package.yaml
- pkg/hs/racquire/lib/Data/RAcquire.hs
- pkg/hs/racquire/package.yaml
- pkg/hs/urbit-atom/bench/Main.hs
- pkg/hs/urbit-atom/package.yaml
- pkg/hs/urbit-atom/test/Main.hs
- pkg/hs/urbit-eventlog-lmdb/package.yaml
- pkg/hs/urbit-king/lib/Urbit/Arvo/Common.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ames.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ames/DNS.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ames/UDP.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Behn.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Clay.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Dawn.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Multi.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Term.hs
- pkg/hs/urbit-king/package.yaml
- pkg/hs/urbit-noun-core/lib/Urbit/Noun/Core.hs
- pkg/hs/urbit-noun-core/package.yaml
- pkg/hs/urbit-noun/lib/Urbit/Noun/Tree.hs
- pkg/hs/urbit-noun/package.yaml
- pkg/hs/urbit-termsize/app/Main.hs
- pkg/hs/urbit-termsize/package.yaml
Following a complaint from @brendanhay, I've turned on -Wall in the package.yamls (except proto, and terminal-progress-bar, which doesn't even use stack) and fixed all the resulting failures and/or excluded certain warnings I found unproductive. Tested by rebuilding after `stack clean`.
Happy to receive feedback on what set of warnings is appropriate.
> king: fix warnings; establish a stricter and more consistent warning policy

- pkg/urbit/noun/manage.c
`+mook` processes stack frames into printable trace (`$tang`), but is currently unavailable to use during boot, which makes bootstrap debugging very painful. This adds very basic printing of stack frame values for `%spot` and  %mean (atomic only).
> u3: adds ghetto +mook replacement

- pkg/urbit/include/noun/zave.h
- pkg/urbit/jets/f/ut_crop.c
- pkg/urbit/jets/f/ut_fish.c
- pkg/urbit/jets/f/ut_fuse.c
- pkg/urbit/jets/f/ut_mint.c
- pkg/urbit/jets/f/ut_mull.c
- pkg/urbit/jets/f/ut_nest.c
- pkg/urbit/jets/f/ut_rest.c
- pkg/urbit/noun/zave.c
This resolves a basic safety issue with the partial memoization in the decapitated jets.
> u3: adds |ut battery to jet cache keys

- pkg/urbit/noun/nock.c
All currently supported hints have their own bytecode ops, which is good for performance, but not for extensibility. This PR adds a dynamic hint protocol to the bytecode interpreter, whereby additional hints can be whitelisted for compilation and implemented via before/after callbacks.
This PR is not compatible with any pre-existing pier, as it changes some existing bytecode ops (although calling `u3m_reclaim()` on boot is probably enough to work around for this for now). I'll be adding a version tag to the memory image  shortly, in order to support changes likes this in the future.
//cc @frodwith (and thanks for all the help!)
> u3: adds bytecode ops and protocol for dynamic hints

- pkg/interface/src/views/apps/links/LinkResource.tsx
When you're on a link page, hitting the settings popover will trigger an error since the LinkResource matches the path. This makes it so that it only matches numerical indexes.
> landscape: fix link route breaking popover

- pkg/interface/src/views/landscape/components/Content.js
- pkg/interface/src/views/landscape/components/GroupsPane.tsx
- pkg/interface/src/views/landscape/components/NewChannel.tsx
- During our OTA last week we needed to redirect graph resources without knowing what their module type was (only available in metadata-store, which we don't get until we accept). In constructing a join flow that awaited the metadata @liam-fitzgerald restored the `GraphApp` component but it clobbered the catch-all 404 routing. We make the graphapp routing specific to `/~graph`.
- Passes `props.chatSynced` to `NewChannel` and awaits its arrival before redirecting chat resources (which was giving a false positive `isChatMissing`, redirecting the user to a 404 page). (#3923)
- Adds a four digit identifier to grouped resource paths to prevent clobbering when making two resources of the same name across groups (eg. "General"). (#3996)
> landscape: fix new chat creation 404; fix new resource clobbering

- pkg/interface/src/views/apps/publish/components/NotePreview.tsx
- pkg/interface/src/views/apps/publish/components/Notebook.tsx
Fixes https://github.com/urbit/landscape/issues/182
I realize this changes some design (@jyng @urcades) but I think it's closer to the spec than before, and it basically just unifies it to use the same styling as on the inside, plus bolding the title...which I think is in spec? I mean it's all changing soon but this fixes it in the interim.
Before:
After:
> publish: styles preview

- pkg/interface/src/views/apps/publish/components/Notebook.tsx
- pkg/interface/src/views/apps/publish/components/Writers.js
- pkg/interface/src/views/landscape/components/NewChannel.tsx
- If we have no writers set for the notebook in our group, everyone can write.
- Allow users to set writers on channel creation if the new channel screen is in a managed context. All added writers are verified they're ingroup✔️ on FE to prevent back-end crashes (`addTag` requires the added ships are already members).
- Surfaces current writers on the channel settings page, decorated in mono and cited.
> publish: surface writers in new channel creation

- pkg/arvo/app/graph-store.hoon
Safely returns a null when either the update-log does not exist, or it
is empty
Fixes #3976
> graph-store: safely peek update-log

- pkg/arvo/app/hark-store.hoon
If a notification came in that merged with a notification that had
already been read, then it would not be added to the cache properly and
therefore would not correctly send %read updates when %read-index was
called.
cc: @vvisigoth 
Fixes #3977
> hark-store: fix caching of merged notifications

- bin/solid.pill
- pkg/arvo/app/dojo.hoon
- pkg/arvo/app/test.hoon
- pkg/arvo/gen/glass.hoon
- pkg/arvo/gen/hood/mount.hoon
- pkg/arvo/gen/metal.hoon
- pkg/arvo/gen/timers.hoon
- pkg/arvo/lib/strandio.hoon
- pkg/arvo/sys/arvo.hoon
- pkg/arvo/sys/hoon.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/vane/gall.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/ted/build-cast.hoon
- pkg/arvo/ted/build-mark.hoon
- pkg/arvo/ted/diff.hoon
- pkg/arvo/ted/test.hoon
- pkg/arvo/tests/sys/vane/eyre.hoon
- pkg/arvo/tests/sys/zuse/format.hoon
As requested, no longer use reversed paths in sley-style peek handling.
I think this is the last of the "reverse path" shenanigans.
> arvo: unflop the spur in scry

- pkg/arvo/mar/css.hoon
- pkg/arvo/mar/hoon.hoon
- pkg/arvo/mar/html.hoon
- pkg/arvo/mar/js.hoon
- pkg/arvo/mar/json.hoon
- pkg/arvo/mar/mime.hoon
- pkg/arvo/mar/png.hoon
- pkg/arvo/mar/snip.hoon
- pkg/arvo/mar/tang.hoon
- pkg/arvo/mar/txt.hoon
- pkg/arvo/mar/xml.hoon
Switch a bunch of .hoon files in /mar from using
the old `{}` syntax for specifying argument types, to the
newer `[argname=argtype]` syntax.
> Use new-style gate argument syntax in /mar

- pkg/arvo/gen/sponsor.hoon
Add a new generator `+sponsor` that encapsulates the logic of invoking `(sein:title our now our)` to get the sponsor of the current ship.
> gen: add +sponsor generator

- pkg/arvo/lib/bip32.hoon
- pkg/arvo/tests/lib/bip32.hoon
Fixes #2877.
It updates +decompress-point:secp256k1 to use elliptic curve cryptography over the finite field p, using modulo arithmetic.
The fact that p "[...] satisfy the equation, p mod 4 === 3", allows us to "skip the somewhat complex general purpose Tonelli-Shanks algorithm, and use a simple identity to find the square roots." [1]
It also allows key derivation for mainnet, testnet and regtest, both for extended keys and addresses.
@Fang- 
- [1] https://stackoverflow.com/a/30431547
> bip32: bitcoin address derivation from extended keys

- pkg/arvo/mar/graph/validator/link.hoon
- pkg/arvo/mar/graph/validator/publish.hoon
- pkg/interface/src/views/apps/notifications/graph.tsx
Updated mark conversion so that edits to comments are notified
separately to new comments.
UX note (cc: @urcades ):
This will notify users if they're subscribed to the parent node i.e. if they've unmuted the book or link that the comment was left on. Should we expose following a comment for updates instead? e.g. click 'notify me on update' -> get notified when comment changes.
> hark: update mark conversion for editable comments

- pkg/interface/src/logic/lib/publish.ts
- pkg/interface/src/views/apps/publish/components/NotePreview.tsx
- pkg/interface/src/views/apps/publish/components/Notebook.tsx
- pkg/interface/src/views/apps/publish/components/NotebookPosts.tsx
- pkg/interface/src/views/apps/publish/css/custom.css
- pkg/interface/src/views/components/Author.tsx
After #3989 I noticed our `md` class didn't have styling for non-`<p>` characters, which our body content used for stripping headers and the like, leading the layout to look quite uneven.
This PR makes `getSnippet` take up until the first `\n` character as of index `2` to get the first line; wraps the snippet in indigo-react, sidestepping the CSS styling with its "sometimes 14px margin-bottom, sometimes 2px" due to not every snippet having a paragraph element.
I also went ahead and rendered image previews if the first line is an image, containing it in a 300px block.
Before / after (note "On Odyssey" being smaller even though it's header copy, because we're escaping headers in the snippet):
> publish: amend snippets, add images to snippets

- pkg/interface/src/views/apps/launch/app.js
- pkg/interface/src/views/apps/launch/components/Groups.tsx
- pkg/interface/src/views/apps/launch/components/ModalButton.tsx
- pkg/interface/src/views/apps/launch/components/tiles/tile.js
- pkg/interface/src/views/components/leap/OmniboxResult.js
- pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
- pkg/interface/src/views/landscape/components/JoinGroup.tsx
- pkg/interface/src/views/landscape/components/NewGroup.tsx
- pkg/interface/src/views/landscape/index.tsx
Fixes #3768
This doesn't...quite look right. Can someone tell me what's off?
Also, should note that tiles now link if they start with `/~landscape/`, because those should all be `<Link />`able routes, right? We shouldn't need an exception for `/~landscape/ship`
> launch: adds new group button

- pkg/interface/src/views/App.js
> landscape: add breach notification

- pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
Automatically dismiss relevant mentions when a chat is marked as read
Fixes: #3977
> chat-fe: autodismiss mentions whilst in channel

- pkg/arvo/app/aqua.hoon
- pkg/arvo/gen/aqua/breach.hoon
- pkg/arvo/gen/aqua/init-azimuth.hoon
- pkg/arvo/gen/aqua/init.hoon
- pkg/arvo/gen/aqua/restore-fleet.hoon
- pkg/arvo/gen/aqua/snap-fleet.hoon
- pkg/arvo/gen/aqua/spawn.hoon
- pkg/arvo/lib/aqua-azimuth.hoon
- pkg/arvo/lib/ph/io.hoon
- pkg/arvo/lib/strandio.hoon
- pkg/arvo/sur/aquarium.hoon
- pkg/arvo/ted/aqua/behn.hoon
- pkg/arvo/ted/aqua/dill.hoon
- pkg/arvo/ted/aqua/eyre.hoon
- pkg/arvo/ted/ph/breach-hi-aqua.hoon
- pkg/arvo/ted/ph/start-drivers.hoon
In order to make it much easier to work with fleets of ships, aqua now stores azimuth state internally rather than relying on a thread.
> aqua: rework how it uses azimuth

- pkg/arvo/app/dojo.hoon
Fixes an instance that hadn't accounted for #3994 yet. This broke `&json &blit bel+~` and other conversion cases.
Went over the rest of dojo again, but I think this is the only one I missed. All other calls take arguments from contexts that should already have unflopped spurs.
> dojo: correct mark conversion scry path

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/apps/chat/components/chat-editor.js
- pkg/interface/src/views/apps/profile/profile.tsx
- pkg/interface/src/views/apps/publish/components/EditPost.tsx
- pkg/interface/src/views/apps/publish/components/NoteForm.tsx
- pkg/interface/src/views/landscape/components/ContactCard.tsx
- pkg/interface/src/views/landscape/components/InvitePopover.tsx
- pkg/interface/src/views/landscape/components/Participants.tsx
- pkg/interface/src/views/landscape/components/PopoverRoutes.tsx
- Adds 'cancel' button when editing a note. If the field is dirty, MarkdownField still prevents navigation.
- Adds a leading sig when copying patps from Chat (#4059)
- Mobile input for Chat overflows vertically by using textarea instead of input.
- Chat's Daybreak marker is padded evenly with other chat messages, removing `pt='3'` since `pt='3'` is already inherited by the renderSigil component.
- Admins can no longer ban themselves.
- Admins can no longer demote themselves if they are the only admin in the group.
- Invite popover now has some margin on mobile devices.
- Amends the 'Back' link size on mobile views of our root identity card to match current Indigo.
- Profile now has icons, and its sidebar matches the styling of other sidebars (gray background, not blue).
- Fixes an issue …
> landscape: QA grab-bag

- bin/ivory.pill
- bin/solid.pill
- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/ted/aqua/ames.hoon
- pkg/arvo/ted/ph/hi-comet-az.hoon
- pkg/arvo/tests/sys/vane/ames.hoon
- pkg/urbit/vere/io/ames.c
(Supersedes https://github.com/urbit/urbit/pull/4048.  Commits have been cleaned up and applied to the latest na-release/candidate.)
Revises the Ames packet format to be easier to parse and ideally save a few bits here and there.  Relays no longer need to understand `+jam` and `+cue`, raising the ceiling on relay speed.  Also, to save bandwidth, instead of including `[sndr rcvr sndr-life rcvr-life]` in the ciphertext for authentication purposes, that's now authenticated explicitly as an [AES-256 SIV](https://tools.ietf.org/html/rfc5297) "associated data vector" but not actually sent over the wire.
This packet format is called "flat" because it is less recursive than its predecessor.
```
32  bits:  header
48  bits:  (optional) 48-bit origin
4   bits:  sender life (mod 16)
4   bits: …
```
> Ames flat packet format

- MAINTAINERS.md
By adding this instruction to our release flow, we can easily link to the latest Vere programmatically.
(I have already done this with v.0.10.8.)
> MAINTAINERS.md: add instruction for latest vere

- pkg/urbit/jets/e/aes_siv.c
Along with https://github.com/urbit/urbit/pull/3894, closes a vulnerability when receiving Ames packets with a malicious `len` field.  I've tested this with single-packet and multi-packet messages.  I have not tested with malicious packets.
> vere/aes_siv: check claimed length

- pkg/arvo/app/observe-hook.hoon
- pkg/arvo/ted/group/on-remove-member.hoon
Fixes #3912 and #4040. Honestly think this is better if incorporated into `%group-store` directly, but this is a first pass.
> observe-hook: add %group-on-remove-member thread

- pkg/arvo/lib/pull-hook.hoon
- Virtualises the kick handler for the inner door in lib/pull-hook, so
that crashes in the handler do not cause a dangling resource with no
subscription. Additionally, failed kicks now cause the sync to be
dropped into a failed-kicks map in the state, where we attempt to
recover from the failure in the on-load. Unfortunately, we can't catch
blocking scries, so we sanity check the path (if it's a gall scry, ensure
that the ship and case are [our now]:bowl).
- If the %kick handler of the inner-core crashes, then we never get to
resubscribe, thus leaving a dangling entry in the state with no
corresponding subscription. Updates the pull-hook-action pokes to not
crash when given a dangling entry.
> lib/hooks: virtualise kick handler to ensure subscription integrity

- pkg/arvo/app/chat-cli.hoon
Makes chat-cli listen to graph-store rather than chat-store.
Along the way, cuts some features. No longer supports channel creation,
deletion, permission management or inviting. No longer lets you send
messages to multiple targets at once.
No longer displays messages from all joined chats, and no longer lets
you join or leave chats. Instead, chat-cli solely concerns itself with
viewing chat content you're already subscribed to (through use of
Landscape or other rich clients). `;view ~host/chat` to start printing
messages for that chat when they come in, `;flee` to toggle off. `;view` to
see what chats are enabled, `;chats` to see all available chats.
The removal of features acknowledges chat-cli's lack of real support for
the modern, group-centric state of userspace.
The intent of `;view` …
> chat-cli: mvp graph-store migration

- pkg/arvo/app/dojo.hoon
- pkg/arvo/app/glob.hoon
- pkg/arvo/app/observe-hook.hoon
- pkg/arvo/app/spider.hoon
- pkg/arvo/ted/build-cast.hoon
- pkg/arvo/ted/build-file.hoon
- pkg/arvo/ted/build-mark.hoon
- pkg/arvo/ted/diff.hoon
- pkg/arvo/ted/dns/address.hoon
- pkg/arvo/ted/glob.hoon
- pkg/arvo/ted/graph/create.hoon
- pkg/arvo/ted/graph/delete.hoon
- pkg/arvo/ted/graph/groupify.hoon
- pkg/arvo/ted/graph/join.hoon
- pkg/arvo/ted/graph/leave.hoon
- pkg/arvo/ted/graph/restore.hoon
- pkg/arvo/ted/hi.hoon
- pkg/arvo/ted/invite/accepted-graph.hoon
- pkg/arvo/ted/migrate-channels.hoon
- pkg/arvo/ted/read.hoon
- pkg/arvo/ted/test.hoon
- pkg/arvo/ted/time.hoon
- pkg/arvo/ted/tree.hoon
As suggested in https://github.com/urbit/urbit/pull/3738#issuecomment-713031839.
Instead of a list of arguments with trailing `~`, dojo now passes threads and generators a a tuple of the arguments. If no arguments are given, still passes `~`. We update the generaters/threads themselves, and all other callsites, to match.
Notable changes include:
- In the `path` argument case, we can no longer distinguish between no arguments and `/` (without adding additional clarification, like `unit` or explicit trailing `~`).  This currently affects the pill generators and `|init-oauth2`, but the `/` case wasn't reasonable for those anyway.
- Similarly, the atom argument case is affected, making it harder to distinguish between no arguments and `0`. For `:dns|request` and `|moon` this doesn't matter. …
> various: start threads with unit of tuple args

- .github/workflows/build.yml
- .github/workflows/release.yml
* Splits the tarball upload into a separate workflow that is only triggered when any kind of draft/create/update of a release occurs. Currently it just continues to upload an artefact named according to the pattern: `gs://bootstrap.urbit.org/ci/urbit-v${version}-${system}-${GITHUB_SHA:0:9}.tgz` - I assume you'll want this to match the release name?
* The (vere) tests potentially rerun for every push and when any pull request is initiated. I've disabled this behaviour so it'll only occur when a pull request is created/pushed to.
> build: disable ci release tarball upload on pull request

- pkg/arvo/ted/aqua/dill.hoon
- pkg/arvo/ted/group/on-leave.hoon
- pkg/arvo/ted/group/on-remove-member.hoon
As per https://github.com/urbit/urbit/pull/4036#issuecomment-738561605.
Also cleans up a duplicate case in a ?-.
> ted: update straggler threads for vase unit change

- pkg/urbit/jets/tree.c
Disabling these jets (from #2853) resolved memory corruption issues (in the king process) on the testnet. More debugging will be needed to find the root cause (test coverage remains wanting, yet highly desirable). Disabling for now ...
> u3: disable +scot and +scow jets

- pkg/arvo/lib/pull-hook.hoon
For some reason, on na-release/candidate, `lib/pull-hook` fails to compile. This addresses that issue.
> pull-hook: fix handle-kick printouts

- nix/lib/test-fake-ship.nix
- pkg/arvo/lib/aqua-azimuth.hoon
- pkg/arvo/sys/hoon.hoon
Fixes a terrible bug i introduced into `@da` coin printing in #3636, wherein timestamps with *either* zero seconds/minutes/hours were printed as if all of their seconds/minutes/hours were zero (and truncated). Flagged by @philipcmonk.
Also fixes some calls to `+end` and +rsh` (api changed in #4060) that weren't updated when merged (in #4074).
> hoon: fixes logic bug in date printer (truncation)

- pkg/arvo/sys/vane/ames.hoon
Ames crashed on this scry if it hadn't heard of the ship, so if you had five of them in a row it would give up on stateless forwarding.  This is possibly the reason for the occasional time we've seen forwarding revert on mainnet, but it's especially important in the new breach when the first ships will mostly be talking to ships that haven't migrated yet.
> ames: don't crash on forward-lane scry

- Makefile
The urbit and urbit-debug derivations both produce an urbit-worker
binary, and they conflict.
I've been running this locally for a while, if there's no better fix, this could go in as a workaround.
References #4089
> nix: don't install urbit-debug by default.

- pkg/arvo/lib/pull-hook.hoon
Prevent proliferation of wires by removing path-specific details from wires when `%watch`ing from pull-hook.
> pull-hook: make wires more stable identifiers based on resource

- pkg/interface/src/views/components/leap/OmniboxResult.js
After indigo-react 1.2.15, Box no longer has `position:relative` by default.
While we caught this elsewhere, we dropped this in Leap results, aligning the
notification dot to the top left of the browser window instead.
Targeting na-release/candidate as it'll inevitably get merged downstream into next-userspace and this is otherwise a regression.
> leap: position notification dot relatively

- pkg/arvo/sys/vane/jael.hoon
there's no correct way to deconstruct a duct, but we can at least do it accurately
> jael: deconstruct wires accurately

- pkg/urbit/vere/io/http.c
- pkg/urbit/vere/lord.c
As discussed out of band: fixes the webslog callback to handle cords correctly, fixes the flog callback, and sends flogs to the webslog callback.
> vere: webslog atom tanks, and webflogs

- pkg/arvo/app/observe-hook.hoon
Fixes #4114. We got a repro on Isaac's ship and resolved it by making this change. This issue may be representative of a deeper issue in `%spider` where spider may not be issuing `%thread-results` deterministically every time a thread is completed. Unsure. Regardless, no functionality was broken, and everything continues to work in this PR.
cc @philipcmonk
> observe-hook: spider wasn't always issuing thread-results, so we got %watch-not-unique. we now make unique wires, but spider's issue remains

- pkg/interface/src/views/apps/links/LinkResource.tsx
Leaving the 'c' uncapitalised here causes Landscape builds to fail on Linux.
> landscape: case sensitivity training

- pkg/interface/src/views/apps/notifications/graph.tsx
- pkg/interface/src/views/components/ShipSearch.tsx
- pkg/interface/src/views/landscape/components/NewChannel.tsx
- Adding writers and unmanaged channel creation has been silently broken after #3998 because the ship search returns sig'd patps. Because we compare unsig'd patps everywhere the ship search is used and the invite popover desigs them anyway, I just removed the sig.
- Snippet gradients would take up the full height of the screen in hark because `position='relative'` is no longer implicit in `<Box>` (indigo-react 1.2.15+). This passes the relative positioning for that instance.
> landscape: various regressions

- pkg/hs/urbit-king/lib/Urbit/King/App.hs
- pkg/hs/urbit-king/lib/Urbit/Prelude.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ames.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Ames/UDP.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/KingSubsite.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Stat.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Term.hs
To address the problem of alleged dropped packets in kh, we add a bunch of counters at each step of the ames driver pipeline. The intent was for these to be part of a system like the SIGINFO/SIGUSR2 handler in classic vere, but it turned out, surprisingly and disappointingly, to be much easier to surface these via the new runtime subsite that @Fang- and I developed. So visit `/~_~/stat` to get your stats.
We also append 32 bits of random to the end of the default log filename so you can keep your old logs. That way, when something goes wrong (e.g. oom), we have more insight into what it was even if the ship has been restarted.
> king: Create a new stats subsystem; count some stuff in Ames

- pkg/arvo/sys/vane/jael.hoon
This had regressed during ~~some breach-related merge~~ a sloppy merge I did. Multiple commits/branches had touched this codepath recently, eating the code step change introduced in #3217.
For reference, the code from the PR:
https://github.com/urbit/urbit/blob/4804cb78646b72dab036591ed74d490722ddb1cd/pkg/arvo/sys/vane/jael.hoon#L1085-L1090
Current jael had the simplification applied properly, but lost the step salting.
Fixes #4126.
> jael: account for step in deriving code

- pkg/arvo/app/graph-store.hoon
For some reason, we receive 8-10 facts for every individual update that is performed to graph-store. I believe the root cause stems from the `lib/push-hook` or `lib/pull-hook` libraries, given the behavior, though it could also stem from the frontend if we are repeatedly sending events to the host. My guess is that the issue is in `%pull-hook` somehow. However, we now no-op aggressively within `%graph-store`, which is righteous, and we no longer spam notifications on livenet, a very noticeable symptom.
Unfortunately, we now query graph-store twice as much in order to determine if we already have a node. I don't expect noticeable slow-down, but it will definitely affect the time complexity of the `%add-nodes` operation.
The root cause should be investigated as soon as possible next week. …
> graph-store: no-op if we already have *any* of the indexes in an %add-nodes event

- pkg/arvo/app/graph-pull-hook.hoon
Silence issues with nacked `%poke-ack`s occurring in `%graph-pull-hook` due to the mysterious duplicate message bug.
If anyone can stamp this, that would be nice.
> graph-pull-hook: silence issues temporarily

- pkg/arvo/app/graph-pull-hook.hoon
- pkg/arvo/app/graph-store.hoon
The previous hook silencing didn't work, so we'll temporarily silence this duplicate issue by not crashing. Upon solving the likely root cause that may stem from `%push-hook`, we will turn back on the assertion, as it is useful for checking whether our invariants hold. It is currently too noisy and we know that the issue is occurring, so we don't need it to be on.
> graph-store: silence duplicate message assertion temporarily

- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
Currently `mars.cachix.org` is used which is a free tier binary cache under my personal account. It is subject to an account-wide limit of 10GIB, resulting in garbage collection between my personal projects and this repository.
This PR updates CI to use our paid `ares.cachix.org` instance, which is under a Tlon account, and updates the `README.md` with an optional step to get people setup to use the binary cache.
The `CACHIX_AUTH_TOKEN` has already been updated to use `ares` instead of `mars` - CI failures will occur until this is merged.
> build: use ares.cachix.org for continuous integration

- pkg/interface/src/views/apps/notifications/inbox.tsx
- pkg/interface/src/views/components/Invite.tsx
- Set scrolling box as `relative`
- invite container is sticky, not the invites themselves
- fix spacing on border between invites
Fixes #4111
> notifications: fix invite squashing

- default.nix
should be `enableStatic` not `enableSatic`
Took me a couple of minutes to figure out why `nix-build -A urbit --argstr crossSystem x86_64-unknown-linux-musl --arg enableSatic true` was trying to build different things than `nix-build -A urbit --arg enableStatic true` even though they were supposed to be exactly equivalent commands.
> default.nix: fix typo in examples section

- pkg/arvo/app/graph-store.hoon
- pkg/arvo/lib/push-hook.hoon
The push-hook library was iterating through incoming subscriptions and was sending out the same fact to the same path multiple times. It now taps the list of paths it takes in so as to deduplicate them prior to issuing facts. Perhaps this could be pulled up into Gall?
Thanks for helping me find this, @philipcmonk. This PR also turns back on noisy printing of duplicates in `%graph-store`, because that will help us root out any future issues in the stack that cause duplicate messages to be sent. There won't be any duplicate facts anymore at present so the terminal will continue to be quiet.
Messages sent over the `%push-hook` will now cause 10x less network traffic than they did previously.
cc: @vvisigoth @matildepark The root cause has been found and resolved.
> push-hook: push out facts to each path only a single time

- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/mar/sole/effect.hoon
- pkg/arvo/sur/sole.hoon
This lets applications suggest to the client that they should gracefully
unsubscribe from the session.
Arguably this might be accomplished by `%kick`-ing the client and then
crashing on their subsequent resubscribe, but that requires tracking
their sole session id and has less semantic clarity on what's happening.
Of course this doesn't _guarantee_ that the client will actually close their session, but that's on them. This will give applications more control over their sole sessions, letting them create more explicitly short-lived experiences, instead of lingering in the user's drum ring until they manually `|unlink`.  
(Think along the lines of, chess session that closes once the game is over, `|link`ing into a remote feedback form, etc)
Depends on (and targets) #4167, because this would …
> sole: add %bye effect for closing the session

- pkg/arvo/lib/hood/drum.hoon
- pkg/arvo/mar/sole/effect.hoon
- pkg/arvo/sur/sole.hoon
This fixes an issue where ctrl-d-ing to unlink the current app would crash.
The added logic also happens in `+se-drop`, which will get called by
`+se-abet` if we did unlink an application. But `+se-agon` depends on the
index being sane, and may be called between `+se-klin` and `+se-abet`.
> drum: update app index early when unlinking

- pkg/urbit/jets/tree.c
- pkg/urbit/noun/jets.c
The PR brings hashboard up-to-date with hoon %140, adding and updating hooks and battery hashes. 
There's currently no command-line option to enable hashboard, the simplest way to run it is to just ensure that `u3_Host.ops_u.has` is set to `c3n` in `daemon/main.c`. I'll think about a better way to expose that control. I have also not tested switching to hashboard on a pier booted with only %fast-hint registration. Both are out of scope for this PR.
> u3: revive hashboard

- pkg/urbit/vere/io/fore.c
- pkg/urbit/vere/pier.c
... instead of simply toggling whatever state was previous set. Fixes #4107
> vere: set arvo verbosity based on presence of -v

- pkg/arvo/sys/zuse.hoon
This can be used to make #4166 run much more efficiently.
> zuse: add backward tap (+bap) to +ordered-map

- pkg/urbit/vere/io/unix.c
Instead of committing all mountpoints regardless of what was specified when running `|commit`.
This came up in discussion on #3240. Couldn't find an issue for it.
> vere: commit the specified mountpoint only

- pkg/arvo/sys/vane/ames.hoon
@belisarius222 and I identified an issue about a year ago that caused flows to occasionally stick, so we added the `%strange-current` assertion to try to catch the issue earlier.  This has showed up from time to time in the last year, and @ixv and I worked out a fix.
An example of the problem is when we're sending messages 288 and 289 and we've received a message-level ack for 289 but not 288, but there are also fragments of 289 which have not been acknowledged, so they remain in our packet pump.  The fragments of 289 *should* have been removed from packet pump when the whole message was acknowledged, but for some reason they weren't.
The first commit in this PR simply runs `on-done` in the packet pump (this is what clears straggler fragments from the packet pump) as we process messages, …
> ames: Fix stuck flows caused by %strange-current

- pkg/arvo/sys/vane/jael.hoon
When we changed wires from /a/foo to /ames/foo, our sorting function
started sorting by last character instead of first character, so breach
notifications were given to gall before ames.  This made gall try to
resubscribe before ames cleared its state, so the message would be lost.
Fixes #4177
> jael: fix breach notification ordering

- pkg/arvo/app/glob.hoon
- pkg/arvo/app/hark-graph-hook.hoon
- pkg/arvo/app/hark-store.hoon
- pkg/arvo/app/landscape/index.html
- pkg/arvo/lib/graph.hoon
- pkg/arvo/lib/hark/store.hoon
- pkg/arvo/mar/graph/validator/link.hoon
- pkg/arvo/mar/graph/validator/publish.hoon
- pkg/arvo/sur/hark-store.hoon
- pkg/interface/src/logic/api/hark.ts
- pkg/interface/src/logic/reducers/hark-update.ts
- pkg/interface/src/views/apps/links/components/LinkItem.tsx
- pkg/interface/src/views/apps/publish/components/Note.tsx
- pkg/interface/src/views/apps/publish/components/NotePreview.tsx
- Adds a `%seen-index` poke to update the last-seen timestamp independently of the unread count
- hark-graph-hook now produces a `%seen-index` on a self post
- hark-graph-hook refactored for clarity
> hark-graph-hook, hark-store: set last-updated on self posts

- pkg/interface/src/views/apps/launch/components/tiles/weather.js
"Clear" is a possible weather style that currently gets displayed as transparent. my bad.
> weather: add style for 'Clear'

- pkg/arvo/sys/hoon.hoon
Fixes #4169 (or, at least, that specific instance of it). We may still want to virtualize `$tank` printing in the king.
> hoon: crash with valid tank on %eror

- pkg/arvo/sys/hoon.hoon
A wise man once told me we probably want this to show up in profiling output.
> hoon: add jet hint for +redo

- pkg/interface/src/logic/api/hark.ts
- pkg/interface/src/logic/reducers/hark-update.ts
- pkg/interface/src/views/apps/notifications/inbox.tsx
- pkg/interface/src/views/apps/notifications/notification.tsx
- pkg/interface/src/views/apps/notifications/notifications.tsx
This fixes #4187 by removing the "archive" view in notifcations and the references to it in the reducers. The archive functionality had been partially removed from the frontend, but not all the way, which was causing JS errors when you tried to click the archive button on a notification. This resolves that issue and has been tested to work on `~tacryt-socryp`.
@philipcmonk I'd like to cut a release to hotfix this issue upon having this PR approved. Would you have time to chat? I'm new to doing these deploys and would like to get it right.
> interface: fix missing archiveBox by removing Archive view

- pkg/arvo/sys/vane/gall.hoon
We can't molt until clay has gotten its pork or else we'll build the old
app against the new kernel.  This ignores vegas, since we should get a
notification from clay on /sys/lyv.
> gall: don't molt on vega

- .github/actions/glob/Dockerfile
- .github/actions/glob/entrypoint.sh
Sets two environment variables, `LANDSCAPE_STREAM` and `LANDSCAPE_SHORTHASH`, to be employed by Landscape builds.  Also reverts the janeway version used to v0.13.1 as the --dev flag is unnecessary.
> meta: glob action tweaks

- pkg/interface/src/logic/lib/util.ts
- pkg/interface/src/views/components/ProfileOverlay.tsx
my bad.
this passes a second parameter to `useShowNickname` for manual override of `hideNicknames` state variable. lmk if there's a better way to do this.
> interface: fixes bug where profile overlay would crash due to hook use

- MAINTAINERS.md
As of #4198, we auto-deploy release/next-js to opted-in ships on network (I'm getting final word on the specific %desk before announcing this). 
Thus, merging into release/next-js is part of deploying to livenet (and really, merge conflicts should be pretty infrequent, since the `master <-> release/next-js -> release/next-userspace` flow is more or less unidirectional for cross-branch changes).
This includes an advisory to include a merge to next-js as part of deploy. We could sidestep this if GitHub Actions let us auto-merge master into next-js, but unsure about that yet.
> meta: add landscape development stream information

- pkg/interface/src/logic/lib/tokenizeMessage.js
cc @tylershuster 
When writing a message and tokenising its contents, we now use a regex to check patp validation against the substring *excluding all characters not lowercase alphabetical*; then if needed, appends a subsequent text node for the end punctuation.
This excludes sigs, though, eg. `oh ~radbur-sivmus~~ hello~` won't work; this should probably be discouraged anyway, since `~` is our mention character.
See #4183 for the reported issue.
> landscape: allow most patp punctation in tokenize

- pkg/interface/src/views/landscape/components/Sidebar/Apps.tsx
On @matildepark's ship, the "Jobs + Gigs" Publish channel has an unread state in `%hark-store` but no corresponding graph (because it was unsubscribed). This made the interface get into a state where the graph could not be joined because of the way the sidebar routing works. I fixed the sidebar routing to prioritize showing the "unsubscribed" state if we do not have the graph key for a particular graph, as `%graph-store` is the source of truth for whether we have a channel or not.
This fixes the presentation of the issue, but highlights an issue with `%hark-graph-hook` in which somehow the entry in `%hark-store` was not removed when the corresponding graph was removed.
cc: @liam-fitzgerald, something to look into when you get back.
Band-aids a fix for #4164.
> 4164: fixes display issue with jobs / gigs based on faulty hark state

- pkg/arvo/app/spider.hoon
For thread ids generated by spider itself, includes the name of the thread,
for convenient identification.
Prompted by debug struggles in #4211.
> spider: prefix thread ids with thread name

- pkg/interface/src/views/apps/term/app.js
cc @tylershuster 
#4197 checks for props.notificationsCount in the interface, but Term doesn't pull props out of `this`.
Fixes urbit/landscape#221
> term: use 'this' in notificationscount

- pkg/interface/src/logic/lib/useS3.ts
Submitting on behalf of @tylershuster, who figured this out last night but is having fork problems?
iOS requires the upload be within the DOM when using hooks; so we append it within the DOM during the upload. I also added `visibility: hidden` to remove it from being displayed.
Doesn't affect desktop upload in my testing. Fixes an unfiled bug.
> landscape/useS3: restore behaviour on iOS

- pkg/interface/src/views/components/Comments.tsx
See #4212 for original filed issue.
When we get the comment content for an initial value — so we can edit its contents — we reduce mentioned children without adding their leading sig, because graph-store doesn't use the leading sig on the back-end. We just append the leading sig for this purpose, so the resubmitted comment includes the mention.
> landscape: edit comments include leading sig

- pkg/interface/src/views/components/ShipSearch.tsx
See #4218 for filed issue.
The conditional validation logic in shipSearch tripped over cases where ship was `undefined`, like when you type a space and then backspace. We just `return` in such cases instead of setting the field to return an error.
cc @tylershuster
> shipSearch: skip validating 'undefined'

- pkg/interface/src/views/apps/notifications/graph.tsx
- pkg/interface/src/views/components/leap/OmniboxResult.js
- pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
Swaps out the Links icon for the Collections icon in the sidebar, Leap, and the Notifications inbox.
Fixes https://github.com/urbit/landscape/issues/224
> landscape: use 'collections' icon

- pkg/interface/src/views/components/MentionText.tsx
- pkg/interface/src/views/components/RichText.js
fixes #4245
This is a bit of a novel approach — it reduces the content in `<MentionText>` down to a single child `<RichText>` whose markdown-formatted content contains specially-formatted (but hopefully logical) links, which are then parsed by `<RichText>` into actual `<Mention>` objects.
**Before:**
**After:**
> publish: renders line breaks

- pkg/interface/src/views/apps/chat/components/chat-editor.js
If you typed, eg. `~bitbet-bolbel/urbit-community` on iOS it wouldn't render as a link because `Enter` would be submitted. We use `onKeyDown` to prevent this and stop propagation properly.
> chat: fix 'enter' behaviour on iOS

- pkg/interface/src/views/components/StatusBar.js
At present issues opened by the 'Submit an issue' button are opened in the urbit/landscape repo, but since the relevant commit doesn't exist in that repository, GitHub fails to auto-link it.  This prepends `urbit/urbit@` to the rendered Landscape shorthash, which I *think* should cause GitHub to auto-link the commit appropriately.
> Reference urbit/urbit repository when submitting issues

- pkg/arvo/app/hark-graph-hook.hoon
*_watching was bunting to watching (i.e. a no-op), causing watching to
be wiped everytimne a graph was removed
> hark-graph-hook: fix muting on %remove-graph

- pkg/arvo/app/hark-group-hook.hoon
> hark-group-hook: add type checking to vase sent to %hark-store, fix #4217

- pkg/arvo/gen/tally.hoon
Scrapes groups and graphs for member counts and recent activity respectively,
and uses that to print out a "tally" of activity for all local groups and their
channels. Since this output is intended to be shared with other parties,
anonymizes resource identifiers by default.
Example output, from a ship hosting a couple low-activity groups.
```
> +tally
tallied your activity score! find the results below.
to show non-anonymized resource identifiers, +tally |
counted from groups and channels that you are hosting.
groups are listed with their member count.
channels are listed with activity from the past week:
- amount of top-level content
- amount of unique authors
the date is ~2021.1.6..17.41.04..0daa
you are in 3 group(s).
you are hosting 3 group(s):
group, 2627f969, 103
chan, 574bcec1, …
```
> tally: add generator for measuring group activity

- pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
See #4219 for filed issue.
The unread message banner was getting its sourced unread message from the index of the last unread message; but this was itself called from a reversed `graph.keys()`, so if I have 9 unreads, it seems like it would get the 9th oldest loaded in, not the 9th newest?
If we call `graph.keys()` for this message without the reverse, the banner's timestamp functions as it should.
> chat: unreverse keys when getting unread msg

- pkg/arvo/app/graph-store.hoon
- pkg/arvo/app/hark-graph-hook.hoon
- pkg/arvo/app/hark-store.hoon
- pkg/arvo/lib/graph.hoon
Correctly remove unreads when nodes or graphs are removed. Additionally fix all current cases of hark-graph mismatch. 
When %remove-nodes is sent as an update, it may refer to a parent node,
in which case the deletion of all the parent's children is implied. If
we hold onto references to nodes outside of graph-store, we are unable
to tell which of our references were affected, other than iterating over
every reference to check if one of the deleted indices is a prefix of
the reference. This is obviously undesirable, so we emit all of the
nodes we deleted, including the nodes deleted implicitly.
Creates a noun poke %fix-dangling, which iterates through the unreads
and dismiss those which refer to nodes which no longer exist.
Additionally, adds a migration which runs this poke.
To …
> hark-store: fix dangling unreads

- pkg/arvo/app/hark-store.hoon
Fixes #4201 by checking if the notification was already read before attempting to mark it as read.
> hark-store: Fix channel marking as read crash

- pkg/arvo/lib/azimuth.hoon
Adds local contracts to azimuth.hoon to support local testnets. These addresses are static iff you use the same seed and deploy script from bridge.
> azimuth: add local contracts

- pkg/interface/src/logic/reducers/hark-update.ts
We simply did not update the notification count when a notification was archived. Fixed
Fixes https://github.com/urbit/landscape/issues/233
> hark: address phantom dot on archive

- .github/actions/glob/Dockerfile
- .github/actions/glob/entrypoint.sh
Uses janeway v0.13.3 in the glob action, which allows us to remove some of the hacky steps introduced to the entrypoint script in 17f3431b43.
> meta: bump janeway version in glob action

- pkg/interface/src/views/components/MentionText.tsx
See #4258 for filed issue.
After #4132, an edge case was introduced where pilots with avatars set, but not nicknames, would have a contact-less profile overlay card inside mentions. 
This is because that PR used the existence of a nickname property to check if we had a contact passed to the component (as some layouts elsewhere in the interface pass the entire contacts rolodex to parse through ourselves). We always have a color in a contact prop, so we use that instead to check for its existence.
> landscape: pass contact to profile overlay thoroughly

- pkg/interface/src/views/apps/publish/components/MarkdownEditor.tsx
See #3329 for filed issue.
Imports [continueList](https://codemirror.net/doc/manual.html#addons) CodeMirror addon and hooks into 'Enter' to prefix the next line with another list item if we're in a list.
> publish: automatically continue lists

- pkg/arvo/app/landscape/js/channel.js
Hotfix to channel.js that *should* (currently being tested) vastly reduce `%eyre` clogs. Fixes #4110.
> channel.js: ack every 30 events *even if this.outstandingJSON is empty*

- pkg/arvo/app/hark-graph-hook.hoon
Does what it says on the tin, to correct for an earlier bug that may have wiped the `watching` state
> hark-graph-hook: rewatch all DMs on upgrade

- .github/workflows/build.yml
- .github/workflows/release-docker.yml
- .github/workflows/release.yml
- default.nix
- nix/pkgs/docker-image/default.nix
- pkg/docker-image/README.md
This PR adds Nix and GitHub Actions builds for a docker image for Urbit, pushed to `tloncorp/urbit`
Builds are done alongside Urbit, Docker Hub pushes are done whenever a tag matching `urbit-v*` is pushed to GitHub/urbit/urbit
Once this is done the `build.yml` file will also build the docker image, and the `release-docker.yml` file will push the image to docker hub with a tag corresponding to the Urbit version, whenever a tag matching `urbit-v*` is pushed.
This PR tracks the progress on #1934 and my corresponding [proposal](https://grants.urbit.org/proposals/626138244-docker-image-for-cloud-container-orchestration)
+ [x] Boot from a .key file (tested on moons)
+ [x] Delete the container and make a new container, booting from the existing pier
+ [x] Touch a <name>.comet file and then make …
> Nix build for a 'smart' docker image that can load keyfiles or a pier and boot a ship

- .github/workflows/merge.yml
Per GitHub,
> When you use the repository's GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run.
The merge workflow previously used the default GITHUB_TOKEN, and so would fail to trigger the desired glob workflow when auto-merging 'master' to 'release/next-js'.  Now our handy new janeway bot does it for us.
> Use bot to execute merge workflow

- .github/workflows/release-docker.yml
When pushing the docker image, update the "latest" tag as well as
pushing a tag for the current Urbit version. This way users pulling
tloncorp/urbit:latest will always get an image with the latest point
release of Urbit.
@jtobin this is a convenience fix for the docker image release cc @jalehman
> build: tag docker image as "latest"

- nix/pkgs/docker-image/default.nix
Vere will not run a ship if STDIN is closed, unless passed the `-t`
flag. Hosted docker containers will not be interactive, but we would
like the docker image to be usable locally and interactively as well.
Thus, we check for STDIN being closed in the shell prior to launching
Vere, and if it is closed, pass the `-t` flag.
> docker-image: Pass `-t` flag to vere if not in an interactive container

- .github/workflows/release-docker.yml
Hosted container services such as Azure Container Images are broken
by the absence of metadata in images pushed by Skopeo. Using Docker we
can push and ensure all metadata is in place.
Tested on: GitHub Actions for black-river-software/urbit fork.
> build: docker-image: Use docker instead of Skopeo to push

- pkg/interface/src/views/apps/chat/components/chat-editor.js
- pkg/interface/src/views/apps/launch/app.js
- pkg/interface/src/views/apps/links/components/LinkItem.tsx
- pkg/interface/src/views/apps/links/components/LinkSubmit.tsx
- pkg/interface/src/views/apps/profile/profile.tsx
- pkg/interface/src/views/apps/publish/components/NotePreview.tsx
- pkg/interface/src/views/apps/publish/components/Notebook.tsx
- pkg/interface/src/views/components/Author.tsx
- pkg/interface/src/views/components/StatusBar.js
- pkg/interface/src/views/components/leap/OmniboxInput.js
- pkg/interface/src/views/landscape/components/ChannelMenu.tsx
- pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
- pkg/interface/src/views/landscape/components/PopoverRoutes.tsx
- pkg/interface/src/views/landscape/components/Resource.tsx
- pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
- pkg/interface/src/views/landscape/components/Sidebar/SidebarListHeader.tsx
cc @urcades 
- Prevent text clipping in group titles.
- Widen popover and profile menu size from 150px to 250px.
- Level the font size to 14px nearly everywhere.
- Chat editor padding is increased on mobile devices.
- Remove patp from status bar.
- Move 'new post' button to the header of resources, removes the metadata display in Publish resources.
> landscape: typography refresh sprint QA

- pkg/interface/package-lock.json
- pkg/interface/package.json
- pkg/interface/src/views/apps/chat/components/content/text.js
See #4202 for filed issue.
Uses RemarkBreaks plugin to render line breaks as `<br>` instead of rendering as child text nodes.
OK, one last time @tylershuster...
> chat: allow line breaks in markdown

- pkg/arvo/sys/vane/ames.hoon
Tested with @tacryt-socryp.  Reduces number of calls to `+jam` when publishing chat messages down to one total, as opposed to one per subscriber.  Since the `~+` cache does not persist across Arvo events, this doesn't catch all cases of message duplication, but it catches the common use case of Gall `%fact`s being delivered to many subscribers in a single Arvo event.
> ames: cache message +jam in +on-memo

- pkg/interface/src/views/landscape/components/Sidebar/SidebarListHeader.tsx
See urbit/landscape#257. Also uses `12px` for each sidebar header item to match the spacing of the two group header items.
> landscape: sidebar header item center, padded

- .github/workflows/build.yml
- .github/workflows/release-docker.yml
The use of the CACHIX_NAME secret introduces problems with external PRs, in particular, so this just repeats what was done in 10855b9ec517906de2734b8239185d5e37f6d40a.
cc @eamsden
> Remove use of CACHIX_NAME in build action

- pkg/interface/package-lock.json
- pkg/interface/package.json
- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/apps/chat/components/content/text.js
- Formik was upgraded to 2.2.6, which broke form behaviours across the interface; we downgrade to the dictated peer version of 2.1.5 to keep parity with indigo-react. This is the critical fix, because it prevents DM and channel creation full stop.
- We ended up leaking additional Markdown tokens as of the line breaks fix deployed last week on devnet. Using RemarkBreaks and RemarkDisableTokenizers together, for whatever reason, breaks the latter, so you have to choose one or the other plugin. I fall back to disallowing the tokens for now, which strips their nodes (eg. `# this is header` will show as `this is header`), but it's better than rendering headers.
> landscape: two hotfixes

- pkg/interface/src/logic/state/local.tsx
suspendedFocus may contain an HTMElement, which would throw an error
when it was serialized. Prevents this by adding suspendedFocus and omniboxShown to the
serialization blacklist.
> localState: prevent serialization of HTMLElement

- pkg/arvo/sys/vane/clay.hoon
Rewrites the `+pile-rule` parsing rule for compactness and legibility. This is a purely stylistic change.
As briefly discussed out of band, @belisarius222.
> clay: condense +pile-rule

- pkg/interface/src/logic/store/store.ts
adds window.debugStore() to show past actions based on the tag and the
current state of some slice of the store. Logs the past 15 actions for
each tag.
cc: @tylershuster how can we get something similar for the zustand based store?
> interface: add debug shim to store

- pkg/interface/src/logic/lib/util.ts
- pkg/interface/src/views/apps/notifications/notification.tsx
Changes the mouse event handler so the notification dismissal control persists between actions, regardless of browser. 
Fixes urbit/landscape#265
> interface: consistent hover events

- pkg/interface/src/views/apps/chat/ChatResource.tsx
- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/components/OverlaySigil.tsx
- pkg/interface/src/views/components/ProfileOverlay.tsx
- pkg/interface/src/views/components/StatusBar.js
- pkg/interface/src/views/components/leap/OmniboxResult.js
- Use mono for ship names in Leap
- Weaves the now-flattened contacts prop through Chat
- Adds the new look for the mini profile box with an editable status message and dropdown menu, just has a stub for the API action.
Questions for other JS wizards (@tylershuster @jamesacklin @liam-fitzgerald)
- I'm trying to be super clever with `contentEditable` so that if it's *our card* you can just click and change the status in the message, setting it on blur, but React seems unhappy about having a controlled component `contentEditable`.
- `history.push()` doesn't work in the dropdown inside the profile overlay. I do not know why. Other dropdowns don't have to do anything to the context.
> contacts: update profile overlay

- pkg/arvo/ted/graph/create.hoon
- pkg/arvo/ted/graph/delete.hoon
- pkg/interface/src/logic/api/contacts.ts
- pkg/interface/src/logic/lib/omnibox.js
- pkg/interface/src/logic/lib/workspace.ts
- pkg/interface/src/types/noun.ts
- pkg/interface/src/views/apps/launch/components/Groups.tsx
- pkg/interface/src/views/apps/notifications/header.tsx
- pkg/interface/src/views/apps/notifications/invites.tsx
- pkg/interface/src/views/apps/notifications/notifications.tsx
- pkg/interface/src/views/apps/profile/components/EditProfile.tsx
- pkg/interface/src/views/apps/profile/components/Profile.tsx
- pkg/interface/src/views/apps/profile/profile.tsx
- pkg/interface/src/views/components/GroupSearch.tsx
- pkg/interface/src/views/components/ShipSearch.tsx
- pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
- pkg/interface/src/views/landscape/components/GroupifyForm.tsx
- pkg/interface/src/views/landscape/components/GroupsPane.tsx
- pkg/interface/src/views/landscape/components/NewGroup.tsx
- pkg/interface/src/views/landscape/components/Resource.tsx
- pkg/interface/src/views/landscape/components/Sidebar/SidebarList.tsx
- We renamed contacts to groups in associations, so I just replaced that across the interface.
- An attempt at making GroupSearch multi-group select, adjusting its behaviour in Groupify to compensate.
- Incorporates GroupSearch on the profile page.
- Stubbed API calls for setting groups.
Can't test this much since we can't make groups and metadata-store crashes but it's 90% of the way.
> profile: more stubs

- pkg/interface/src/logic/lib/sigil.js
Comets need sigils with background colors too. Passes the color in to the Box used by comets (shipname > 14 chars).
Also a formatting change, but I noted the operative line with a comment.
Fixes urbit/landscape#316
> interface: sigil color for comets

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
Sets and clears the chat message author's name on click with hooks, rather than with a ref. Sets this message in Inter regardless if the author has set a nickname or not.
Fixes (urbit/landscape#331)[https://github.com/urbit/landscape/issues/331]
> interface: clears 'copied' message on shipname click

- pkg/interface/src/views/apps/publish/components/Note.tsx
- pkg/interface/src/views/apps/publish/css/custom.css
fixes https://github.com/urbit/landscape/issues/324
Seems fine to `overflow: hidden` `Note`s, right?
> publish: fixes codeblock wrapping behavior

- pkg/arvo/app/contact-pull-hook.hoon
- pkg/arvo/app/contact-push-hook.hoon
- pkg/arvo/app/graph-pull-hook.hoon
- pkg/arvo/app/graph-push-hook.hoon
- pkg/arvo/app/group-pull-hook.hoon
- pkg/arvo/app/group-push-hook.hoon
- pkg/arvo/app/metadata-pull-hook.hoon
- pkg/arvo/app/metadata-push-hook.hoon
- pkg/arvo/lib/contact.hoon
- pkg/arvo/lib/graph.hoon
- pkg/arvo/lib/group.hoon
- pkg/arvo/lib/metadata.hoon
- pkg/arvo/lib/pull-hook.hoon
- Adds %no-validate flag, to prevent checking the wire/src.bowl/resource all match-up to enable P2P connections. 
- Moves the resource-for-update back into the inner door, to match the push-hook.
- Fixes `+get-contact` and `+is-allowed`
This is about as much as I can do given what I know. Unsure how you intend to share contacts to the hosts, but contacts that are on the host are propagated fine to members of the group.
> contact-hooks: some improvments 

- pkg/arvo/app/invite-store.hoon
- pkg/arvo/lib/group-view.hoon
- pkg/arvo/sur/group-view.hoon
- pkg/arvo/ted/group/invite.hoon
- pkg/interface/src/logic/api/groups.ts
- pkg/interface/src/views/components/Invite.tsx
- pkg/interface/src/views/landscape/components/InvitePopover.tsx
- pkg/interface/src/views/landscape/components/JoinGroup.tsx
Adds a -group-invite thread to invite users to groups.
Updates the interface to call into the thread correctly
Fixes a bug preventing speedy joins from being redirected correctly
Correctly initialises the state of invite-store
Now prompts for an invite description and displays it, if set.
> Invites: update for new group-view

- pkg/interface/src/views/components/OverlaySigil.tsx
Restores the intended dynamic positioning of the profile overlay in chat messages. Calculates the space between a chat message and the vertical bounds of the chat window using client geometry, rather than scroll offset, which would sometimes throw a false positive and position the profile overlay contents below the chat window.
Fixes [urbit/landscape#303](https://github.com/urbit/landscape/issues/303)
> interface: fix profile overlay positioning in chat

- .github/actions/glob/Dockerfile
This should unbreak the glob action.  I recently pushed an image for the latest janeway version, but am not yet sure why the old one became unavailable..
> meta: update janeway dep in glob action

- pkg/arvo/app/hark-store.hoon
- pkg/arvo/app/metadata-hook.hoon
- pkg/arvo/app/metadata-store.hoon
- pkg/arvo/sur/hark-store.hoon
- Addresses metadata-hook crash
- Discards the unused `metadata-update` portion of `group-contents` in hark, to allow vases to nest properly.
This branch OTAs fine onto a `-L` copy of ~hastuc-dibtux
> hark, metadata-hook: fix OTAs

- pkg/arvo/app/hark-store.hoon
Two %read-note actions set on the same notification could cause the
cache to become invalid. Instead, crash if we read a note that is
already read.
Fixes https://github.com/urbit/landscape/issues/276
> hark-store: crash on invalid note read

- pkg/arvo/app/contact-store.hoon
This is a possible fix for the forwarding loop problem. I'm unsure what the best way to address this is. Maybe a `+validate-update` arm in the pull-hook? 
The forwarding loop occurs like so.
1 host subscribes to a members profile.
2 member subscribe to the groups contact information.
3 member updates their profile, causing a fact to be sent to their push-hook
4 this causes the host to receive the same fact, which they then forward onto the groups contact subscription.
5 the member then receives the fact on the groups subscription, which goes to the store and then the push hook
6 GOTO 4
> contact-store: prevent hook forwarding loop

- pkg/arvo/app/metadata-pull-hook.hoon
- pkg/arvo/app/metadata-push-hook.hoon
- pkg/arvo/app/metadata-store.hoon
- pkg/arvo/lib/metadata.hoon
Prevents channels automatically becoming pinned during migration
Also moves the preview generation logic into `lib/metadata.hoon` and generates it directly on the pull-hook side, if we already have it.
> metadata: prevent automatic pinning during migration

- pkg/arvo/app/contact-push-hook.hoon
- pkg/interface/src/views/apps/chat/components/ShareProfile.js
- Prevents infinite loop in proxy a %share action
- Does not send a %share if we are the recipient
> contact-hooks: prevent infinite hook loop

- pkg/arvo/app/contact-push-hook.hoon
- pkg/arvo/app/settings-store.hoon
- pkg/arvo/lib/group.hoon
settings-store didn’t compile, and contact-pull-hook scry would fail every time because it was written wrong.
> groups, settings, contacts: make them compile and run scries properly

- pkg/arvo/app/settings-store.hoon
We have yet to deploy the setting-store to livenet, so we should set the "tutorial seen" boolean to false in on-init, and not mess with it on-load.
> setting-store: show tutorial upon first load, don't show if dismissed

- pkg/arvo/app/metadata-pull-hook.hoon
Correctly initialise md-pull-hook
> metadata-pull-hook: move watches to +on-init

- pkg/arvo/app/contact-store.hoon
- pkg/arvo/app/metadata-pull-hook.hoon
Backstop the overflow of requests that is occurring on livenet right now because of the slow OTA processing time.
> metadata-pull-hook: keep track of pending requests

- pkg/interface/src/views/apps/chat/css/custom.css
- pkg/interface/src/views/apps/profile/components/Profile.tsx
- pkg/interface/src/views/components/Invite/index.tsx
- pkg/interface/src/views/components/ProfileOverlay.tsx
- pkg/interface/src/views/components/RichText.js
- pkg/interface/src/views/components/StatusBar.js
- pkg/interface/src/views/landscape/components/GroupsPane.tsx
- pkg/interface/src/views/landscape/components/NewChannel.tsx
- pkg/interface/src/views/landscape/components/Participants.tsx
- Redirects properly when DMs are started within DMs (urbit/landscape#421)
- Redirects to the right workspace when accepting a DM, passes the actual ship instead of hastuc-dibtux (urbit/landscape#406)
- Passes a filtered contacts object for rendering group participants; fixes a former bug for rendering all pending members (urbit/landscape#422, urbit/landscape#312)
- Status flushes right on viewing a profile, is padded (urbit/landscape#413)
- Statuses can be linked, also fixes an unfiled bug where disableRemoteContent was nonfunctional (urbit/landscape#418)
- Fixes flexbox on dev stream mobile actually this time
- Reverts the embed changes yesterday (urbit/landscape#407)
> landscape: front-end fixes post-1.6

- pkg/interface/src/views/components/Invite/index.tsx
We're accessing `invite.ship` when we don't have `invite`. This stubs that
out.
Currently accepting a DM crashes on interface, this fixes that.
> invite: prevent interface crash

- pkg/arvo/app/contact-store.hoon
Will stop flickering due to an excess of `%kick`s but does nothing for the network load causing the kicks in the first place.
> contact-store: enforce timestamp ordering on %initial

- pkg/interface/src/views/apps/chat/components/content/text.js
Handling linebreaks outside of the parser allows us to preserve
linebreaks, which goes against the markdown spec and is poorly
supported by the parser library.
> TextContent: handle linebreaks before feeding parsing

- pkg/interface/src/views/apps/chat/components/content/code.js
Fixes an unfiled bug where Landscape was only rendering the first line of code message output. This has likely been at large since the graph-store migration in December.
Code output is now an array of messages, not an array within an array's `[0]`:
We were looking for `code.output[0]`, thus we only rendered line 1 of the Dojo response.
> chat: render all code output, not just first line

- pkg/interface/src/views/apps/links/LinkWindow.tsx
We were missing the "Text" import in LinkWindow so collections that don't allow us to post would crash on render, unless we already had the graph, in which case it would function fine.
Fixes urbit/landscape#433
> LinkWindow: add missing 'text' import

- pkg/arvo/app/graph-push-hook.hoon
- pkg/arvo/app/group-push-hook.hoon
- pkg/arvo/app/group-store.hoon
- pkg/arvo/app/hark-store.hoon
- pkg/arvo/app/metadata-push-hook.hoon
- pkg/arvo/gen/metadata-store/remove.hoon
- pkg/arvo/ted/sane.hoon
- pkg/interface/src/logic/reducers/hark-update.ts
- pkg/interface/src/views/landscape/components/NewChannel.tsx
- pkg/interface/src/views/landscape/components/Sidebar/SidebarListHeader.tsx
- pkg/interface/src/views/landscape/index.tsx
hark-store: give %read-all fact
Fixes urbit/landscape#402
metadata-push-hook: correct association key
Fixes urbit/landscape#405
SidebarListHeader: look in %groups not %contacts assocs
Fixes urbit/landscape#405
AddGroup: fix activation from leap
Fixes urbit/landscape#439
metadata-store: update +remove
Fixes urbit/landscape#428
graph-push-hook: correctly call +get-roles-writers-variation
Fixes urbit/landscape#423
Fixes urbit/landscape#424
sane: fix accidental self kick
Does not remove ourselves from the group when run. Additionally adds
card preview support to the inside app pokes.
Fixes urbit/landscape#442
> landscape: various fixes for breakage from OTA

- pkg/arvo/app/contact-store.hoon
Resolves crash condition and sets the information using what we have.
Also fixes https://github.com/urbit/landscape/issues/408
> contact-store: upon %edit of a nonexistent contact, make an empty contact and set that field

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/components/leap/Omnibox.tsx
- pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
Also respects CalmEngine, as (unfiled) we weren't checking `hideAvatars` before rendering inside chat messages.
Fixes urbit/landscape#315
> chat: only show avatars if we have them

- bin/solid.pill
- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/vane/gall.hoon
When receiving a `%lost` from Ames, Gall was sending a `%u` message to leave the subscription.  However, Gall wasn't calling the normal routine for this, so it wasn't adding the leave request to its request queue -- this was causing the request queue to become desynchronized, which at least partially contributed to the repeating "2nd watch ack" printfs.
This fix does not recover from a broken queue (at least not on my ship), but it should prevent a working queue from desynchronizing.  I'm not yet sure how we should try to recover from this condition, but it might be good to get this onto the network ASAP to prevent more ships from entering the error condition.
EDIT:
The first commit only fixed one of a few problems going on simultaneously. …
> gall: fixes to %boon handling

- pkg/arvo/app/landscape/index.html
- pkg/interface/config/webpack.dev.js
- pkg/interface/config/webpack.prod.js
- pkg/interface/package-lock.json
- pkg/interface/package.json
- pkg/interface/src/serviceworker.js
This adds a serviceworker with the boilerplate from https://developers.google.com/web/tools/workbox/guides/get-started and starts to cache images. Seems...faster?
Preliminary work to out-of-tab browser notifications and other wondrous splendiferousnesses
@liam-fitzgerald RFC
> interface: adds serviceworker

- pkg/interface/src/views/components/RemoteContent.tsx
Some filehosts do not support CORS requests from third party domains. This breaks image loading from these hosts on current release branch. Fixes this by falling back to not enabling CORS on these requests if we catch an error from the image element. 
cc: @tylershuster
> RemoteContent: remove crossOrigin attribute if CORS unsupported

- pkg/arvo/app/test.hoon
- pkg/arvo/gen/tally.hoon
- pkg/arvo/lib/strandio.hoon
- pkg/arvo/ted/build-file.hoon
- pkg/arvo/ted/test.hoon
- pkg/arvo/tests/lib/pkcs.hoon
This fixes #3598 (or at least all known causes -- the whole herb/lens/test harness is still pretty fragile). It also fixes a couple current build/test failures. I'm targeting master to fix CI quickly and broadly.
> ci: fix test harness output, report build failures

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/components/MentionText.tsx
Horizontally aligns a mention in a chat message if it is the first thing in the message; adds a margin if it is inline with surrounding text.
Fixes urbit/landscape#468
> chat: correctly position mentions

- pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/index.tsx
Channel settings would flex smaller than the content requires on Safari; we prevent this here.
> landscape: prevent  settings collapse on safari

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/components/ProfileOverlay.tsx
- pkg/interface/src/views/components/ProfileStatus.js
Conforms the mini-profile layout to design spec. Also normalizes the cursor appearance within the mini-profile and restores the `history.push` actions (whoops).
Here are a few instances of mini-profiles in ascending order of complexity.
A mini-profile with nothing set:
A mini-profile with display name set:
A mini-profile with display name and avatar set:
A mini-profile with display name, avatar, and status set:
My own mini-profile:
Fixes urbit/landscape#461
> interface: fixes miniprofile layout, restores actions

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/apps/chat/components/content/text.js
- pkg/interface/src/views/apps/chat/css/custom.css
Addresses the `blockquote` spacing inconsistency as outlined in [urbit/landscape#473](https://github.com/urbit/landscape/issues/473) and adds an even unit of padding to the last chat message in the window.
Fixes urbit/landscape#473
> chat: blockquote spacing

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
Pads the message content itself, not the daybreak or unread dividers.
Fixes urbit/landscape#475.
> chat: correctly pad daybreak divider

- bin/solid.pill
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/tests/sys/zuse/format.hoon
State before: in `chrono:userlib`, there were second-resolution
`@da`-to-unix and unix-to-`@da` functions. In `en`/`dejs:format`, there were
millisecond-resolution `@da`-to-unix and unix-to-`@da` functions. The
`@da`-to-unix path in `time:enjs` confusingly rounded to the nearest
millisecond, meaning millisecond *n* was a label for [*n*-0.5, *n*+0.5) rather
than [*n*, *n*+1).
This adds a millisecond-resolution `@da`-to-unix and unix-to-`@da` to
`chrono:userlib`, and a second-resolution conversion to `en`/`dejs:format`.
It makes use of the `chrono:userlib` functions in `en`/`dejs`, and doesn't do
any rounding.
Backwards-incompatible changes:
- made `unt:chrono:userlib` take `@da` rather than `@`.
> zuse: time conversion fixes

- pkg/interface/src/views/components/GroupLink.tsx
- pkg/interface/src/views/landscape/components/MetadataIcon.tsx
cc @urcades 
Fixes urbit/landscape#478
> landscape: bring placeholder group joins to parity

- pkg/interface/src/views/components/GroupSearch.tsx
Loosely searches for group titles.
Fixes urbit/landscape#477
> GroupSearch: use includes, not startsWith

- pkg/interface/src/views/apps/links/LinkResource.tsx
- pkg/interface/src/views/apps/notifications/graph.tsx
- pkg/interface/src/views/apps/notifications/header.tsx
- pkg/interface/src/views/apps/publish/PublishResource.tsx
- pkg/interface/src/views/apps/publish/components/Notebook.tsx
- pkg/interface/src/views/apps/publish/components/NotebookPosts.tsx
- pkg/interface/src/views/apps/publish/components/NotebookRoutes.tsx
- pkg/interface/src/views/components/Author.tsx
Both Links and Publish were still accessing group paths in contacts; additionally some sig mismatching prevented the Author component from rendering, anyhow. We desig aggressively to resig for the contact in the component; we pass the whole contacts object now.
Fixes urbit/landscape#457, fixes urbit/landscape#458
> links, publish, notifications: work with flattened contacts

- pkg/interface/src/views/landscape/components/MetadataIcon.tsx
Prevents visible cutoff given we have border-radius.
> MetadataIcon: hide image overflow

- pkg/interface/src/views/components/ShipSearch.tsx
Fixes an unfiled bug where we didn't show nicknames in ShipSearch after the contact-store rewrite, since contacts aren't grouped anymore.
> ShipSearch: update for flattened contacts

- pkg/arvo/lib/metadata.hoon
Fixes an issues where groups that were originally hidden but got groupified will be unable to be joined. We no longer render previews for hidden groups anyway, so just discard. 
cc: @yosoyubik
> metadata: do not generate previews for hidden groups

- pkg/arvo/app/hark-store.hoon
- pkg/interface/src/logic/reducers/hark-update.ts
notifications: reduce group stats properly
hark-store: give stats facts for group notifications
Group notifications were being left out of the initial %unreads fact,
which was causing faulty calculation of notification counts  on the
frontend
Fixes urbit/landscape#276
> notifications: fix negative unread count

- pkg/interface/src/views/apps/launch/app.js
- pkg/interface/src/views/apps/launch/components/ModalButton.tsx
I used `washedGray` and forgot it was an opacity colour — falling back to the hex here.
> launch: fix modal backgrounds

- pkg/interface/src/logic/reducers/group-update.ts
Currently there's an edge case where if you have a private group, and someone joins it, and you in the same session look at your participants, you'll appear to have more "pending" than you actually have, because we don't reduce the member out of the pending set until next load.
This checks if we're invite-only; if so, an added member is removed from the set when we reduce.
Tested on both a private and public group, works without crash or incident, fixes issue.
Fixes urbit/landscape#490.
> groups: reduce added member from pending

- pkg/interface/src/views/components/Body.tsx
- pkg/interface/src/views/components/GroupSearch.tsx
- pkg/interface/src/views/components/Loading.tsx
- pkg/interface/src/views/components/ShipSearch.tsx
- pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/ChannelPermissions.tsx
- pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/index.tsx
- pkg/interface/src/views/landscape/components/GroupsPane.tsx
- Archiving a channel will crash right now instead of redirecting us properly — we return the redirect and skip waiting on the delete now
- Loading a channel has a border, which was annoying me, so I made a prop to remove it if we need to. We also space "Creating DM" apart from the spinner
- "Create or select a channel" was too small, now it is not
- ShipSearch and GroupSearch show a pointer now
> landscape: grabbag

- pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
It was driving me a little crazy.
Before:
After:
> ResourceSkeleton: flex and truncate description

- pkg/interface/src/logic/lib/tokenizeMessage.js
Reverts urbit/urbit#4224
This is more trouble than it's worth — needs another pass at tokenising.
Fixes https://github.com/urbit/landscape/issues/275, https://github.com/urbit/landscape/issues/277
> Revert "landscape: allow most patp punctation in tokenize"

- pkg/interface/src/views/components/leap/OmniboxResult.js
Fixes https://github.com/urbit/landscape/issues/487
We also cite patps now to render comets a bit more palatably.
> leap: truncate statuses

- pkg/interface/src/views/apps/links/components/LinkItem.tsx
We actually enforce URI validation *really aggressively* on submit from Landscape — we don't care what the type is (we take `gopher://`, `ipfs://`, just fine), we just want some prefix on that link.
But when we render a link, we trust the URL contents. If you manually poke a link into a collection without a URI prefix, the link won't work when clicking in Landscape. So now we look for a prefix; if there isn't any, we prefix `http://`.
Fixes urbit/landscape#280.
> links: enforce valid URI on render

- pkg/arvo/app/hark-store.hoon
Previously, rebuilding the cache in any scenario other than on-load would add
missing notifications but not remove read or dismissed notifications
Fixes urbit/landscape#479
> hark-store: bunt cache before rebuilding

- pkg/interface/src/logic/lib/tokenizeMessage.js
Tiny fix to the URL regex so that it doesn't store punctuation marks (e.g. ",") inside the urls, breaking the links.
> landscape: ignore punctuation tokenizing URLs

- .github/workflows/publish-npm-packages.yml
Adds a workflow that, on every push to master, will publish new versions of interface subpackages to the NPM registry if any are available (i.e., if version numbers have been incremented in any of the respective package.json files).
cc @tylershuster
> meta: publish interface packages when available

- pkg/interface/src/logic/state/local.tsx
- pkg/interface/src/logic/state/settings.tsx
- pkg/interface/src/views/apps/launch/app.js
- pkg/interface/src/views/apps/settings/components/lib/CalmPref.tsx
Adds a setting within the CalmEngine to hide the top-level tiles separately from group tiles (so you can choose both, neither, one or the other, with and without unread counts).
Requested by @urcades, presuming design stamp.
> settings: add 'hide utility tiles'

- pkg/interface/src/views/components/MentionText.tsx
Fixes an unfiled bug where mentions in comments had no contact information.
MentionText is written to work regardless of whether it's passed _one_ contact or _the whole object_; this was a performance change I wrote a few months ago, but in some cases where we couldn't avoid passing the whole object into the component we access the contact through the object. I presume state hooks will remedy this.
Anyway, _that_ assignment didn't have a sig prepended, as contact-store now has, so all contacts weren't matching in mentions within comments sections.
> MentionText: update for new contacts

- pkg/arvo/app/hark-graph-hook.hoon
- pkg/arvo/mar/graph/validator/chat.hoon
- pkg/arvo/mar/graph/validator/link.hoon
- pkg/arvo/mar/graph/validator/publish.hoon
- pkg/arvo/sur/hark-graph-hook.hoon
This is the new autowatching behaviour: 
- chat: none
- publish & links: posting a link will autowatch it for comments, commenting will autowatch for further comments
> hark-graph-hook: upgrade notification-kind to allow for sibling autowatches

- pkg/arvo/gen/tally.hoon
Previously, if metadata-store said a graph existed, we'd unconditionally scry
for it. Now, we make sure the graph _actually_ exists, to avoid risking a crash.
I think `/app/sane` can catch/fix such cases, but it's not guaranteed to have run on a user's ship, so we need to do a sanity-check here too.
> tally: be safer wrt mangled metadata

- pkg/interface/src/views/apps/chat/components/ChatInput.tsx
- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/components/Author.tsx
- pkg/interface/src/views/components/ProfileOverlay.tsx
- pkg/interface/src/views/landscape/components/Participants.tsx
**PLEASE NOTE** I was unable to test this PR locally as I had issues cloning the repository (something with `con.c`, notable that I initially attempted to clone via Windows, fool that I am!).
Anyway, shout out to @matildepark for telling me where to change the things that needed to change. You may also wish to squash these commits as they were made via GitHub web (due to aforesaid git clone issue).
> Add objectFit='cover' to various Landscape avatars to avoid aspect ratio squishing

- pkg/interface/src/logic/state/local.tsx
- pkg/interface/src/logic/state/settings.tsx
- pkg/interface/src/views/App.js
- pkg/interface/src/views/apps/chat/components/content/text.js
- pkg/interface/src/views/apps/chat/css/custom.css
- pkg/interface/src/views/apps/launch/components/tiles/custom.js
- pkg/interface/src/views/apps/launch/css/custom.css
- pkg/interface/src/views/apps/links/css/custom.css
- pkg/interface/src/views/apps/publish/components/NoteNavigation.tsx
- pkg/interface/src/views/apps/publish/css/custom.css
- pkg/interface/src/views/apps/settings/components/lib/DisplayForm.tsx
- pkg/interface/src/views/components/RichText.js
- pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
- pkg/interface/src/views/landscape/css/custom.css
Adds the option to pick "light", "dark" or "auto" themes. Also strips out a lot of older CSS and rewrites some small elements that themselves depended upon `prefers-color-scheme` to detach them from the rest of our theme logic.
When testing, please try some of those divergent cases (ie. picking light while your OS is in dark mode, or dark while your OS is in light mode). I think I caught them all, but there's a lot going on of course.
> settings: allow picking indigo theme

- pkg/arvo/sys/vane/ames.hoon
- pkg/arvo/sys/zuse.hoon
- pkg/arvo/tests/sys/zuse/ordered-map.hoon
The ordered map `+traverse` function failed to delete all items because it could skip a node under certain deletion conditions.  This fixes that, confirmed by a new test that failed with the old implementation.
This should fix the [ames: strange current issue](http://github.com/urbit/urbit/issues/4424).
> zuse: fix ordered-map delete many

- pkg/interface/src/views/apps/links/LinkResource.tsx
Forcibly destroys and recreates a linkwindow when the channel changes. This is necessary to prevent the virtualscroller from acting upon stale state.
Fixes urbit/landscape#508
> LinkResource: fix changing channels

- pkg/interface/src/views/App.js
- pkg/interface/src/views/apps/settings/components/lib/CalmPref.tsx
- pkg/interface/src/views/apps/settings/components/lib/DisplayForm.tsx
- pkg/interface/src/views/apps/settings/components/lib/LeapSettings.tsx
- pkg/interface/src/views/apps/settings/components/lib/NotificationPref.tsx
- pkg/interface/src/views/apps/settings/components/lib/S3Form.tsx
- pkg/interface/src/views/apps/settings/components/lib/Security.tsx
- pkg/interface/src/views/components/RichText.js
- pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/ChannelPermissions.tsx
- pkg/interface/src/views/landscape/components/GroupSettings/Admin.tsx
- pkg/interface/src/views/landscape/components/GroupSettings/Personal.tsx
- pkg/interface/src/views/landscape/css/custom.css
- Use Anchor instead of BaseAnchor to restyle rich text links (https://github.com/urbit/landscape/issues/516)
- Place anchor css reset inside custom CSS instead of the styled Root component so that objects in portals get the CSS applied (like group switcher, etc.)
> landscape: destyle anchors

- pkg/interface/src/views/landscape/components/GroupSummary.tsx
- pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
- pkg/interface/src/views/landscape/components/MetadataIcon.tsx
Group avatars use inset box shadows instead of borders. This sort of has the effect of not showing any border at all. Is this on purpose? I don't know. @g-a-v-i-n Please confirm!
Fixes urbit/landscape#492.
> MetadataIcon: use box-shadow

- pkg/interface/src/views/apps/publish/components/NotePreview.tsx
Chrome's `object-fit` scaling logic differs from its `background-image` logic. In some cases, [portrait images stretch](https://stackoverflow.com/questions/63019769/css-object-fit-cover-is-stretching-a-particular-image-in-chrome-on-mac) if the file is malformed in some way. 
This PR shims that by using the `background-image` scaling in a box that encloses an invisible copy of the image (otherwise, an empty box gets flexed closed and requires way more shims all the way up the tree).
Makes you love the web.
Fixes urbit/landscape#495
> publish: use backgroundImage for images

- pkg/interface/src/views/components/RichText.js
Indigo anchors use inline-block; this breaks the flexing of the channel description. We make them inline here.
> RichText: anchors display inline

- pkg/interface/src/views/apps/chat/components/ChatInput.tsx
- pkg/interface/src/views/components/Author.tsx
Both were using older logic that checked for `null` but if you remove an avatar, it becomes an empty string; we instead ask if it's truthy, matching the fix in #4460.
> ChatInput, Author: fix "removed avatar" case

- pkg/arvo/app/dbug.hoon
Lanes aren't strictly guaranteed to be jams, and we don't want to crash when
processing them.
> dbug: virtualize ames lane cueing

- pkg/interface/src/views/apps/chat/components/ChatInput.tsx
- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/components/Author.tsx
As per @urcades, we style avatars to match sigils' rounding.
> landscape: avatars use borderRadius '1'

- pkg/arvo/ted/graph/groupify.hoon
- pkg/arvo/ted/graph/restore.hoon
These threads had stopped compiling when we shipped the upgrade from `%metadata-hook` to `%metadata-push-hook`.
> graph-threads: make %groupify and %restore compile

- pkg/interface/src/views/apps/term/app.js
- pkg/interface/src/views/apps/term/components/history.js
Try running `.` in webterm at half your screen width — the history container overflows off screen. This is because you need `min-width: 0` to flex child containers when they try to overflow. We apply that here.
> term: flex history container width

- pkg/interface/src/views/apps/chat/css/custom.css
- pkg/interface/src/views/apps/publish/components/MarkdownField.tsx
- pkg/interface/src/views/apps/publish/components/Note.tsx
- pkg/interface/src/views/apps/publish/css/custom.css
- Fixes link colour on Publish render (urbit/landscape#521)
- Fixes chat / publish input and renderer theming on specific client + Indigo setting combinations
> landscape: two css regressions

- pkg/interface/src/views/apps/links/components/LinkItem.tsx
- pkg/interface/src/views/apps/settings/components/lib/RemoteContent.tsx
- pkg/interface/src/views/components/RemoteContent.tsx
LinkItem: safely access size
Fixes urbit/landscape#542
RemoteContent: use settings instead of local state
Fixes urbit/landscape#544
> interface: p1 hotfixes

- pkg/interface/config/webpack.dev.js
- pkg/interface/package-lock.json
- pkg/interface/package.json
- pkg/interface/src/index.js
- pkg/interface/src/logic/api/metadata.ts
- pkg/interface/src/views/apps/publish/components/Notebook.tsx
- pkg/interface/src/views/components/RemoteContent.tsx
- pkg/interface/src/views/components/useTutorialModal.tsx
- pkg/interface/src/wdyr.js
As per a discussion with @liam-fitzgerald a while back, adds `why-did-you-render` during development to check for unneeded renders. Seems to be pretty clean already, but it looks like it doesn't track functional components by default (only PureComponents), but might aid in future debugging.
Also removes some unnecessary `console.log`s
> interface: added tool to track unneeded renders

- pkg/interface/src/views/apps/settings/components/lib/BackButton.tsx
- pkg/interface/src/views/apps/settings/components/lib/S3Form.tsx
- pkg/interface/src/views/apps/settings/settings.tsx
Adjusts the System Preferences layout to be the same (CSS grid-based) as Groups and Messages.
The sidebar in both instances is flexible. The proportions match, therefore so do the pixel measurements at various window widths.
An easy way to test is to visit the System Preferences, Leap to a Group, then use browser keyboard shortcuts to quickly flip back and forth between pages.
Fixes urbit/landscape#541
> settings: sidebar same width as groups

- pkg/interface/src/views/apps/profile/components/EditProfile.tsx
- pkg/interface/src/views/components/StatusBar.js
- Correctly references `contacts` from the Zustand store in the header dropdown status-setter (the old one came from app root, which never refreshed and would result in out-of-sync statuses).
- Correctly aligns the "Save Profile" button to the text baseline of the other profile actions.
> interface: small grab-bag

- pkg/interface/src/views/apps/links/components/LinkItem.tsx
- pkg/interface/src/views/apps/publish/components/Note.tsx
- pkg/interface/src/views/apps/publish/components/NotePreview.tsx
- pkg/interface/src/views/apps/publish/components/Notebook.tsx
- pkg/interface/src/views/apps/publish/components/NotebookPosts.tsx
- pkg/interface/src/views/components/Author.tsx
- pkg/interface/src/views/components/CommentItem.tsx
- Checks for our role in notes and comments, allows admins to delete them.
- Changes the update colour to blue to match the rest of the interface, moves to flexbox to just center the line height properly
- Shows the author's sigil on notes now so you can DM them if you want
- Removes a bunch of unnecessary api prop weaving since the Author component doesn't use the api for anything
> publish: allow admins to delete posts, comments

- pkg/interface/src/views/components/UnjoinedResource.tsx
- pkg/interface/src/views/landscape/components/GroupsPane.tsx
- pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx
- pkg/interface/src/views/landscape/components/Skeleton.tsx
We were referencing `props.associations` where we no longer received associations from props.
> GroupsPane: restore channel counts on summaries

- pkg/interface/src/logic/lib/sigil.js
- pkg/interface/src/views/apps/chat/components/ChatInput.tsx
- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
Resizes chat sigils and avatars to 24px square and slightly respaces some elements to keep everything in line.
- Keeps sigils themselves to 16px square, but pads enough around them to appear as 24px boxes. This is to keep them aligned to the author's name.
- Message author name type size is now uniform to the message content.
- Sigil, author, and timestamp are padded over to line up with the channel title in the header.
- Subsequent (non-sigil'd) messages are padded to align with author name.
Keeping as a draft right now to iterate with design.
Fixes urbit/landscape#460
> chat: 24px sigils

- pkg/interface/src/views/apps/profile/components/Profile.tsx
- pkg/interface/src/views/apps/profile/components/ViewProfile.tsx
Made a few tweaks to the current interface, some closer to designs, some just "better":
List of Tweaks:
1. Increased Height of Header
2. Larger radii on header + avatar/sigil
3. UI-weight font weight for user-set name
4. Spacing between patp and bio matches space between username + avatar/sigil
Caveats:
I need to check out how these end up being applied to the mobile version of the interface. For example, I want to eliminate the border radii and border stroke on small viewports so the header is edge-to-edge.
> landscape profiles: tiny tweaks to visual elements

- pkg/arvo/sys/zuse.hoon
- pkg/arvo/tests/sys/zuse/format.hoon
Fixes #4598.
#4474 made the JSON time conversion no longer invertible, which caused
problems for chat, which uses message timestamp in milliseconds as a key
— so chat would send a message with ms timestamp x, it would get
encoded as @da x, but then when it went back through the conversion to
milliseconds, it would often (not always) get encoded as x-1.
I still do not fully understand why this is — and why it doesn't seem
to be a problem with seconds based on cursory testing — but integer
multiplication and division generally do not invert. And adding a half a
millisecond to the input date before converting it resolves the issue
and makes the functions invertible.
I added a regression test, so hopefully the next courageous adventurer
who winds up here after wondering why `+unm` looks funny …
> zuse: fix time fix regression

- pkg/interface/src/views/apps/chat/components/ChatInput.tsx
- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
Adds a light-gray background to chat messages on hover while preserving the existing chat message spacing.
Also adds commented-out dummy message actions that match the mockups and discussion found here: https://github.com/urbit/landscape/issues/460#issuecomment-797258413
Fixes urbit/landscape#460
> chat: row hover

- pkg/interface/src/views/landscape/components/MetadataIcon.tsx
This is a one character/variable change — editing the group avatar radius from `2` to `1`.
Whenever we have two radii'd elements near one another, in a nested manner, we want to always attempt to "drill down" from largest corner radius on the outside, with increasingly smaller radii applied to inner elements.
> ed: sidebar group avatar fix

- pkg/interface/src/views/apps/chat/components/ChatWindow.tsx
- pkg/interface/src/views/components/VirtualScroller.tsx
- Instead of marking graphs as loaded when we get a empty response from /node-siblings, mark them as read when the response is not as big as it should be
- Only calculate unread index when we've loaded all the way to the bottom edge
> ChatWindow: fix unread mark and gaps in scrollback

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/apps/profile/components/Profile.tsx
- pkg/interface/src/views/components/Author.tsx
- pkg/interface/src/views/components/ProfileOverlay.tsx
- pkg/interface/src/views/components/RemoteContent.tsx
- pkg/interface/src/views/components/RichText.js
- pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
In response to an unfiled bug on display in UC last weekend.
> interface: remove referrer headers from img tags

- nix/overlays/native.nix
- nix/pkgs/lmdb/darwin-fsync.patch
This is a (presumed) fix for the (presumed) event log corruption observed in #4605 (see the [fsync man page for MacOS](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html)).
@brendanhay, plz review for general nix sanity.
Also, do you have any idea how i would apply a platform-specific patch to  `pkg/hs/lmdb-static/cbits/`? (Alternately, we could just warn people off of `urbit-king` on MacOS until the log is moved.)
> build: patch lmdb to use F_FULLFSYNC on darwin

- pkg/arvo/lib/signatures.hoon
- pkg/arvo/ted/graph/add-nodes.hoon
As per @matildepark, waiting to put this in until closer to end of sprint. Can confirm that this works. I tested it on `~bolbex-fogdys` and `~tacryt-socryp` on livenet.
> graph-store signatures: turn them on and correctly validate them

- pkg/interface/package-lock.json
- pkg/interface/package.json
- pkg/interface/preinstall.sh
cc @tylershuster 
Instead of our awful hack in build:prod to grab npm/api and install its dependencies, we add a preinstall script that iterates through each folder in pkg/npm and installs all their dependencies, preventing any need for additional developer intervention before working on Landscape development.
> build: pkg/interface builds pkg/npm preinstall

- pkg/arvo/sys/vane/ames.hoon
It can still be enabled with `|ames-verb %msg`, but it's too loud to be on by default.
> ames: silence "fragment crashed" printf by default

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
On the tin. Applies to daybreak and unread markers.
Fixes urbit/landscape#589
> chat: prevent marker text from wrapping

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/apps/notifications/graph.tsx
Adds an optional `hoverMarker` prop to `ChatMessage`. When set, this hides the washedGray hover background. We then use this in the Notifications view, where we want to prevent the gray background from appearing until we get through the detailed refactor coming from @g-a-v-i-n.
Pointed out by @matildepark , no corresponding Landscape issue.
> hark: eliminate chatmessage hover backgrounds

- pkg/interface/src/views/apps/settings/components/lib/CalmPref.tsx
- pkg/interface/src/views/apps/settings/components/lib/Debug.tsx
- pkg/interface/src/views/apps/settings/settings.tsx
Watch this video:
https://user-images.githubusercontent.com/3999320/110891389-be128980-82a6-11eb-9cfa-ec361cb46c56.mp4
In the absence of an actual "Debug" menu item spec from design, this can be invoked by typing `~` on your keyboard while looking at the settings screen.
The state can be filtered using lodash's `_.get(object, path, default)` syntax, and the stores will update as data changes. Each time the filter correctly matches a part of the store, that result is logged in the console.
Useful for development and also for working through issues with Landscape with people experiencing issues. You could tell someone to go to this page and then enter `unreads.graph[/ship/some-long-string-here][/02384038438543]` to get a consistent track.
> interface: added debug menu

- pkg/urbit/noun/urth.c
This PR fixes a (possible) crash in `|meld` and `urbit-worker cram pier`. Both operations involve reallocating all persistent state off-loom, and then copying it back onto the loom (which btw, is unnecessary in the case of `cram`). Loom refcounts are fixed-up by a gc pass, but that includes a read of uninitialized memory (the hot jet state) due to the order of operations.
> u3: reallocate hot jet state before gc in meld and cram

- pkg/interface/src/views/components/Dot.tsx
- pkg/interface/src/views/landscape/components/Sidebar/Apps.tsx
- pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
- pkg/interface/src/views/landscape/components/Sidebar/types.ts
Fixes https://github.com/urbit/landscape/issues/122
Hashed the final bits out with @urcades in uc/design. Dots indicate *notifications* in a channel where bright indicates unread. 60% gray indicates read but subscribed and 30% gray indicates unsubscribed. Selected/hovered for both subscribed and unsubscribed channels shown. (There isn't a dot in the light version on accident, but you can verify it does show up)
> sidebar: updated channel state design

- pkg/hs/urbit-king/lib/Urbit/Vere/Http/Client.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Serf/IPC.hs
- pkg/hs/urbit-king/package.yaml
> king: fix two space leaks leading to oom on ~def.

- pkg/hs/urbit-king/lib/Urbit/Vere/Serf/IPC.hs
- pkg/hs/urbit-noun/lib/Urbit/Noun/Time.hs
Fix for #4562.
Although hardware does not have a femtosecond clock, it does have a nanosecond clock (or at least that's the precision that Haskell purports to give). The problem is that, while nanoseconds are by definition given as a decimal fraction of seconds, urbit's "fractoseconds" are given as a *binary* fraction, and decimal fractions do not divide evenly into binary fractions. The result is that one nanosecond after 1970 is
```
~1970.1.1..00.00.00..0000.0004.4b82.fa09
```
as a `@da`. Arguably, this is the most accurate way to represent the time data coming out of the king, so, in my view, that level of precision should be kept internally in the `Gap` type, and any transformation we do for compatibility should be done at the interface between Haskell and the serf (which is what I do …
> king: remove the "hardware femtosecond clock"

- pkg/arvo/app/metadata-push-hook.hoon
If we were creating a DM, for which no %groups metadata exists, the
+transform-proxy-update arm would crash, preventing the creation of new
DMs.
> metadata-push-hook: do not crash on new hidden metadata

- pkg/interface/src/logic/store/store.ts
It works, [is correct](https://github.com/pmndrs/zustand#calling-actions-outside-a-react-event-handler) — hard to reproduce https://github.com/urbit/landscape/issues/536 but fixes in in theory
ht @liam-fitzgerald
> interface: wraps zustand setter in batchUpdate

- pkg/interface/src/logic/lib/gcpManager.ts
We polled on -gcp-is-configured before, so that if the store got
configured, Landscape would get a token without needing a browser
refresh. But the resulting POSTs were bothersome, so now we only check
once and stop if GCP store doesn't seem to be configured.
We could check 0 times (and delete -gcp-is-configured), but this has
problems. Mainly:
- there would be no way to tell whether GCP store was unconfigured or
misconfigured
- if -gcp-get-token failed intermittently (e.g. the token-uri was down
for a moment), we would not get a token for that session.
We may want to make GCP store into a Gall app of its own, so we can get
updates from it for free. Or else perhaps key off of the presence of the
store config in settings-store or something. But for now, this
fixes urbit/landscape#583.
> interface/gcp: stop polling for gcp store config

- pkg/hs/urbit-king/lib/Urbit/King/Main.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Multi.hs
- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Serv.hs
Following joe's suggested response to #4530, we shut down the king when the http server is saturated with requests, as an alternative to getting the server permanently stuck in a state where it cannot accept new connections.
To make this condition far less likely, we increase the resource cap on file descriptors from 256 to 10240 (the value of OPEN_MAX, at least on darwin).
In the long run, we should probably try to restart the http server rather than shut down the king, or selectively go through and terminate specific requests.
> king: commit seppuku when server is out of fds, also setrlimit allowing for more fds

- pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/KingSubsite.hs
- pkg/hs/urbit-noun/lib/Urbit/Noun/Conversions.hs
`textAsTa` was not properly handling uppercase alphanumerics. This would
break subsite authentication when there are uppercase characters in your
cookies.
Should now be equivalent to `(cury scot %t)`.
dojo:
```
> (scot %t 'urbauth-zod=0v2.d0q3n.4jgsq.fl9jk.mp2nd.97uu6; lang=en-US')
~.~~urbauth-zod~3d.0v2~.d0q3n~.4jgsq~.fl9jk~.mp2nd~.97uu6~3b..lang~3d.en-~55.~53.
```
ghci:
```
λ> textAsTa "urbauth-zod=0v2.d0q3n.4jgsq.fl9jk.mp2nd.97uu6; lang=en-US"
"~~urbauth-zod~3d.0v2~.d0q3n~.4jgsq~.fl9jk~.mp2nd~.97uu6~3b..lang~3d.en-~55.~53."
```
> king: fix textAsTa

- pkg/interface/src/views/apps/chat/components/unread-notice.js
- pkg/interface/src/views/components/Timestamp.tsx
- Restyles `foo messages since bar` banner in Chat as per spec. Prevents chat contents from appearing behind our semi-transparent colors by mocking in a solid-color background. Respects dark mode.
- Replaces left-padded date in `Timestamp` with a non-breaking space to retain typographic purity.
Light mode:
Dark mode:
Light mode with a very wide viewport:
Fixes urbit/landscape#563
> chat: new unread message style

- pkg/arvo/app/hark-store.hoon
- pkg/arvo/lib/hark/store.hoon
- pkg/arvo/sur/hark-store.hoon
- pkg/interface/package-lock.json
- pkg/interface/src/logic/reducers/hark-update.ts
- pkg/npm/api/hark/types.ts
When we receive a notification, it might not affect our count because
it’ll get merged on the server side, but we unconditionally increment
our count on the client if the notification hasn’t been loaded yet.
Addresses this by storing a set of time, index so we can compute whether
or not the notification is merged or unloaded and change the count
accordingly. Calculates the notificationsCount as derived state, instead of independently updated state
Fixes urbit/landscape#276
> hark: kill incorrect count reporting

- .github/workflows/build.yml
Part 1 of a "CI specificity" series — 
In userspace we often have JS-specific changes that are just hanging on CI for a long period of time. They don't need to be in CI, and they clog up the queue. This only runs the build CI if we're changing files in pkg/arvo, pkg/hs or pkg/urbit in the push.
Could use a looksee because I am unsure how to test the change, though I noticed the first time I pushed this change there was a fail because of a typo, and I fixed the typo and it just didn't run on the force push, so presumably it worked.
> meta: only build ci if changing arvo, vere, king

- pkg/interface/src/views/apps/chat/components/ChatInput.tsx
- pkg/interface/src/views/apps/launch/app.js
- pkg/interface/src/views/apps/launch/components/tiles/custom.js
- pkg/interface/src/views/apps/launch/components/tiles/tile.js
- pkg/interface/src/views/apps/links/components/LinkItem.tsx
- pkg/interface/src/views/apps/links/components/LinkSubmit.tsx
- pkg/interface/src/views/apps/notifications/inbox.tsx
- pkg/interface/src/views/apps/notifications/notifications.tsx
- pkg/interface/src/views/apps/publish/components/NoteNavigation.tsx
- pkg/interface/src/views/apps/publish/components/NotePreview.tsx
- pkg/interface/src/views/apps/publish/components/Notebook.tsx
- pkg/interface/src/views/components/Body.tsx
- pkg/interface/src/views/components/StatusBar.js
- pkg/interface/src/views/components/StatusBarItem.tsx
- pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
- pkg/interface/src/views/landscape/components/Home/AddFeedBanner.js
- pkg/interface/src/views/landscape/components/Home/GroupFeedHeader.js
- pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
- pkg/interface/src/views/landscape/components/Sidebar/Sidebar.tsx
- pkg/interface/src/views/landscape/components/Sidebar/SidebarListHeader.tsx
I noticed an inconsistency between the Landscape JS and the Figma mocks. This may fix https://github.com/urbit/landscape/issues/633
> interface: borders changed from washedGray to lightGray to match Figma mocks

- pkg/arvo/README.md
In which I ~~do a blatant power-grab~~ formally shoulder some responsibility for the stuff I put out. Already discussed out of band, just looking for a quick a-ok here.
~littel-ponnys no longer maintains Eyre, so I will take over.
/lib/test goes without a dedicated maintainer for now.
Additionally, #4463 and follow-up work sees me taking charge of the terminal
stack, so I will take over formal ownership of that going forward.
> readme: update arvo maintainers list

- pkg/arvo/lib/push-hook.hoon
- pkg/arvo/mar/version.hoon
Allows airlock libraries and other local stores to negotiate versioning better
> push-hook: add version scries

- pkg/interface/src/views/App.js
- pkg/interface/src/views/apps/launch/app.js
The check for rendering the tutorial modal was relying on a passed prop that does not exist now.
(I also move all the hooks to the top of the function as per best practice.)
> launch: get tutorial state from zustand

- pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
Proposes a more dynamic way of handling layout of channel titles and descriptions while making room for additional actions.
For small viewports, don't show the description at all. Show a back button, and truncate the channel name to fit the available space, including any right-hand actions or icons in the header.
For larger viewports, remove the back button, and show the channel description while making room for any right-hand actions. 
- Truncate both the title and description if both exceed half the allotted space. 
- Truncate the title if the title is longer than the description.
- If the channel does not have a description, or if the title is shorter than the description, do not truncate the title, and truncate the description if it exists. 
Small viewport, short title:
Small …
> interface: truncate channel names & descriptions in header

- pkg/interface/src/views/apps/chat/components/unread-notice.js
Adjusts the border-radius of both elements to match and hides the overflow.
fixes urbit/landscape#657
> chat: adjust unread banner corners

- pkg/interface/config/webpack.dev.js
- pkg/interface/src/register-sw.js
This is tripping us up like the old days — serviceworker caches the JS so that changes stick across hot reloads, making it hard to tell whether changes are being reflected as we work. We just don't build the serviceworker for dev.
If you are developing on Safari, you will have to run the following after this is on next-userspace:
```
navigator.serviceWorker.getRegistrations().then(function(registrations) {
for(let registration of registrations) {
registration.unregister()
} })
```
cc @tylershuster
> landscape: don't build serviceworker in dev

- pkg/interface/src/views/apps/chat/css/custom.css
Overrides CodeMirror defaults in custom CSS to prevent its sizer from min-heighting offscreen and uses flexbox to keep the text input vertically centred.
Please please please try to break it with long long input. Tested on Firefox.
Fixes urbit/landscape#632
> chat: prevent input overflow offscreen

- pkg/arvo/mar/graph/validator/chat.hoon
- pkg/arvo/mar/graph/validator/link.hoon
- pkg/arvo/mar/graph/validator/post.hoon
- pkg/arvo/mar/graph/validator/publish.hoon
All validators (and uses of `!>` and `!<`) should have type-casts to avoid expensive nest-checking.
Please put into `prerelease` @matildepark
> graph-validators: speed up validators by adding type casts

- pkg/arvo/app/graph-push-hook.hoon
Documenting the work done with Phil to both fix the `read-at-aeon` error occurring in `%graph-push-hook` and prevent it in the future by more rigorous type-checking. This works as is and the pattern should be replicated across all apps that use `=<`
> graph-push-hook: add hc where appropriate and enforce type-checking to prevent issue in future

- .github/workflows/publish-npm-packages.yml
It's a little aggressive on the attempted publish, causing constant fails.
> build: only run publish-npm-packages on pkg/npm

- pkg/arvo/app/graph-store.hoon
In my test, the time to validate a graph went from 56 seconds to 1 second when joining UC General.
Perf Before:
Perf After:
> graph-store: speed up +validate-graph by using +turn and no longer virtualizing

- pkg/interface/src/views/apps/profile/components/ViewProfile.tsx
Fixes urbit/landscape#682.
For whatever reason we can't mutate these arrays in place when using immer. See [this StackOverflow thread](https://stackoverflow.com/questions/53420055/error-while-sorting-array-of-objects-cannot-assign-to-read-only-property-2-of/53420326), this fixes the crash by copying the array we're rendering.
> ViewProfile: clone contact groups array

- pkg/urbit/daemon/main.c
- pkg/urbit/include/vere/vere.h
- pkg/urbit/vere/io/http.c
Fixes #4638
Note that this prints `http: listen: address not available` when we get `UV_EADDRNOTAVAIL` and continues with no http server, should we crash instead?
> vere: add -b to specify http server bind ip

- pkg/urbit/jets/a/gte.c
- pkg/urbit/jets/a/gth.c
- pkg/urbit/jets/a/lte.c
- pkg/urbit/jets/a/lth.c
- pkg/urbit/noun/jets.c
Our atom comparison jets (`+gth`, `+lth`, &c) use GMP when either argument is an indirect atom. This is expensive, as we have to allocate to GMP integers. This PR updates the jets to only use GMP when the arguments have the same bitwidth.
This PR was inspired by the (very slow) exhaustive test I'm performing for #4692 (and seeing the jets in stack samples). I'll try to whip up a quick benchmark to measure the impact.
> u3: adds bitwidth short-circuit to atom comparison jets

- pkg/arvo/app/metadata-push-hook.hoon
There was an erroneous assertion that had been around for the past month or more that *should* have prevented all unmanaged channel creation, but mysteriously did not. I have talked through this with Isaac and Matilde and we all agree that this should have been broken for a long time, but was *not*.
This now works and has been tested on `~tacryt-socryp` on livenet.
@liam-fitzgerald Can you think of why this could have possibly worked prior?
> metadata-push-hook: fixes issue with adding unmanaged metadata

- pkg/urbit/vere/io/unix.c
Instead of first comparing to a previously committed version of the
file, which may or may not have been fully accepted by clay.
Fixes #3240, though some of the discussion therein remains relevant.
> vere: only compare to clay when committing files

- pkg/urbit/include/jets/q.h
- pkg/urbit/include/jets/w.h
- pkg/urbit/jets/e/fein_ob.c
- pkg/urbit/jets/e/fynd_ob.c
- pkg/urbit/jets/tree.c
- pkg/urbit/tests/jet_tests.c
I was inspired to add these after seeing @philipcmonk's performance measurements in #4677. I've added some sparse unit tests for both jets, and a (disabled) exhaustive 32-bit roundtrip test, all of which pass.
I intend to add some nock/jet result-comparison testing from the arvo side (something like `=((f i) =>(f(+6 i) .*(. -)))`), and the implementations could use a little cleanup (and comments where they appear to differ from the hoon). But I wanted to open this PR ASAP so anyone who was interested could play around or take measurements.
> u3: jets +fein:ob and +fynd:ob

- pkg/arvo/lib/metadata-store.hoon
- pkg/arvo/lib/push-hook.hoon
- pkg/arvo/mar/metadata/update-1.hoon
- pkg/interface/src/logic/lib/virtualContext.tsx
- pkg/interface/src/logic/subscription/global.ts
- pkg/interface/src/views/apps/chat/components/chat-editor.js
- pkg/interface/src/views/apps/permalinks/embed.tsx
- pkg/interface/src/views/components/RemoteContent.tsx
- pkg/interface/src/views/landscape/components/DeleteGroup.tsx
- pkg/interface/src/views/landscape/components/GroupSettings/GroupFeed.tsx
Mainnet is currently experiencing undue load due to a watch-kick loop.
If the watch is unsupported, it will be kicked due to a mark mismatch,
which will be interpreted by the unversioned hooks as a network pressure
kick, prompting a resub and continuing the loop. Instead, we now no-op
on unversioned, unsupported watches, waiting for the subscriber to
rewatch after it processes the versioning OTA. This will silently break
groups for the subscriber until the reach the latest OTA, but is
preferable to nacking, and kicking them permanently
> push-hook: nack unversioned subscriptions when unsupported

- pkg/interface/src/views/apps/chat/components/ChatMessage.tsx
- pkg/interface/src/views/components/MentionText.tsx
- pkg/interface/src/views/components/RichText.js
After https://github.com/urbit/urbit/commit/60b7b5df442496468b5fa3f2ed4a8abc11aa83d7 refactored the profile overlay everything that referenced it was updated, except MentionText. This fixes that and passes the api prop through each place where we use MentionText, so that your status can be sent, etc.
> landscape: restore profile overlays on mention clicks

- pkg/interface/src/views/landscape/components/Sidebar/SidebarList.tsx
When we changed metadata.module to metadata.config, we amended the logic for parsing through group paths in the DM workspace, but not in the My Channels workspace.
> landscape: fix 'my channels' sidebar logic

- pkg/arvo/lib/pull-hook.hoon
- pkg/arvo/mar/metadata/update-0.hoon
- pkg/arvo/mar/metadata/update.hoon
- pkg/arvo/sur/metadata-store.hoon
Pull-hook side of the previous change to push-hook
(479fbfd). Noop on unsupported
unversioned marks, waiting for the publisher to upgrade and kick. Same
tradeoffs as previous change apply. Restores the historical marks to their correct types so that clamming will no longer fail
> pull-hook: noop on unsupported, unversioned facts

- pkg/interface/src/logic/lib/useRunIO.ts
- pkg/interface/src/views/components/Invite/index.tsx
Now that the store is immutable, callbacks that close over props will
see stale props because the reference is captured at instantiation. This
was not an issue previously, because the references would be directly
mutated. To remedy this, useRunIO has been added, which takes an async
function to run for the actual network processing, and a second
callback, which is able to see fresh props because it is not
instantiated until the async callback has resolved successfully.
Importantly, useRunIO does not resolve until the second callback has
finished, preserving the semantics of the callback for Formik handlers
and the like.
Fixes urbit/landscape#691
> Invite: fix stale props in inviteAccept callback

- pkg/arvo/app/graph-store.hoon
- pkg/arvo/app/observe-hook.hoon
- pkg/arvo/sur/observe-hook.hoon
Keep all marks warm so as to never need to build a mark on demand. Can confirm that on a livenet comet, this stops all marks from rebuilding, whereas some marks (ex: `%hark-update`) would rebuild continually before this.
> observe-hook: upgrade to keep marks warm

- pkg/arvo/lib/language-server/parser.hoon
- pkg/arvo/sys/hoon.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/zuse.hoon
Got fed up with hand-writing this for the hundredth time, so just exposed it from the stdlib, and made existing re-implementations use that instead.
> hoon: add +stap, path parser

- pkg/interface/src/views/components/GroupLink.tsx
Forwards users directly to groups they have already joined when they click a GroupLink.
Video attached; I belong to the "Clack" group and not the "Areological Fermentation" group:
https://user-images.githubusercontent.com/748181/114098922-087c2b80-9890-11eb-8a5a-a0de17f8cc08.mp4
Fixes urbit/landscape#593
> groups: forward to already-joined group from GroupLink

- pkg/arvo/mar/graph/validator/post.hoon
- pkg/interface/src/views/landscape/components/Home/GroupFeed.js
- pkg/interface/src/views/landscape/components/Sidebar/SidebarListHeader.tsx
Keeps track of an unread count for group feeds, and displays the link as blue if the group feed has unreads. In lieu of better specified behaviour the unread count is reset upon navigation to the page.
> Group Feed: unread counts

- pkg/interface/src/views/components/MentionText.tsx
Mentions are wrapped in ProfileOverlay, which defaults to using a `Box`, which is a `block`, so we pass an inline prop which corrects the issue. Overlays still work.
Fixes urbit/landscape#763
> MentionText: inline mentions

- pkg/interface/src/views/components/ProfileOverlay.tsx
Dropped in a merge conflict resolution (https://github.com/urbit/urbit/commit/7fd4928d96fbac5e0ca680c11179c3737847a3d4).
Fixes urbit/landscape#757
> ProfileOverlay: restore DM button

- pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
> landscape: sidebar uses black100 for all synced

- pkg/arvo/app/file-server.hoon
Ported from the HTTP2 branch, to avoid strange release flows.
> file-server: lowercase headers for http2

- pkg/arvo/app/metadata-store.hoon
Fixes `got` crashing in +on-load
> metadata-store: fix OTA 2

- pkg/interface/src/views/apps/chat/css/custom.css
- pkg/interface/src/views/apps/profile/components/Profile.tsx
- pkg/interface/src/views/apps/publish/css/custom.css
- pkg/interface/src/views/apps/settings/components/lib/S3Form.tsx
- pkg/interface/src/views/components/Author.tsx
- pkg/interface/src/views/components/CommentItem.tsx
- pkg/interface/src/views/components/RemoteContent.tsx
- pkg/interface/src/views/landscape/components/Graph/content/text.js
- pkg/interface/src/views/landscape/components/JoinGroup.tsx
- pkg/interface/src/views/landscape/components/Participants.tsx
- Author component now allows you to click to copy like it does elsewhere (https://github.com/urbit/landscape/issues/578)
- Profiles are padded on mobile and remove the profile type on those viewports to prevent text breakage (https://github.com/urbit/landscape/issues/658)
- JoinGroup prompts redirect if we have the group in our state already  (https://github.com/urbit/landscape/issues/683)
- RemoteContent has been changed to reflect the new style of embedded content. Links embeds still work normally. (https://github.com/urbit/landscape/issues/693)
Examples follow:
On CalmEngine:
- Prevent promoting to admin if the participant is pending (https://github.com/urbit/landscape/issues/694)
- Correct the line height of comment item actions (https://github.com/urbit/landscape/issues/731)
- Fix …
> landscape: assigned omnibus

- pkg/interface/src/views/landscape/components/Sidebar/Apps.tsx
Fixes a bug where the "this channel has notifications" dot would not appear when it should have
> sidebar: typesafe notifications check

- pkg/interface/src/views/components/leap/Omnibox.tsx
- pkg/interface/src/views/components/leap/OmniboxInput.js
- pkg/interface/src/views/components/leap/OmniboxResult.js
This PR proposes we unify the selection in Leap between hovered (mouse) and keyboard selections by doing the following:
- Set the active selection, not just hover treatment, by mouse among leap results
- Determine an item's selection-eligibility by mouseMove event (not hover) to account for items scrolling into view under the cursor
- Hide the mouse cursor while navigating results by keyboard; restore the cursor on mouse move
Reformatting handled in a separate commit.
Video demonstrating behavior attached.
https://user-images.githubusercontent.com/748181/114450025-7d5aa880-9ba3-11eb-9cf8-5deb200cabb9.mp4
Fixes urbit/landscape#598
> leap: deduplicate selection with mouse+keys

- pkg/urbit/vere/io/cttp.c
The PR fixes a long-standing occasional crash in vere's http client i/o driver. The issue was my misuse of the `h2o_http1client_connect()` -- while usually asynchronous regardless of success, a failure to create a sock results in a synchronous invocation of the error callback, which causes a use-after-free.
Fixes #4601 and #2006
> vere: fix cttp crash by accounting for synchronous error callback

- pkg/urbit/vere/io/cttp.c
Reverts urbit/urbit#4766
(I accidentally merged it into `master` instead of `release/next-vere`. My apologies for the mistake.)
> Revert "vere: fix cttp crash by accounting for synchronous error callback"

- pkg/interface/src/views/components/ImageInput.tsx
Adds a clear affordance to zero out the ImageInput field.
Respects darkmode as well.
Clicking this button restores the uploading prompt.
Fixes urbit/landscape#785
> imageInput: adds clear button

- nix/pkgs/docker-image/default.nix
This lets docker's SIGTERM pass through to urbit so it stops cleanly.
Previously it was taking 7-8 seconds to stop and occasionally left a `.vere.lock` file behind when it did. After adding `exec` it stops in <1 sec and seems to clear the lock properly. I also think the lack of this might have been truncating the error messages during some crashes I was having in the past week.
> docker: add exec to final urbit invocation

- nix/pkgs/docker-image/default.nix
This allows the docker container Ames port to be optionally overridden by passing a `--port=xxx` argument along with the `docker run` command. If no port argument is passed the default 34343 is still used instead.
Example: 
```
docker run -p 80:80 -p 13436:13436/udp \
--mount type=volume,source=/home/user/urbit/galaxy,destination=/urbit \
tloncorp/urbit --port=13436
```
This is fairly edge case and probably not needed by many users but adds a little flexibility and it can suppress the warnings galaxies get:
```
ames: czar: overriding port 13436 with -p 34343
ames: czar: WARNING: 13436 required for discoverability
```
> docker: allow setting Ames port via docker run argument

- pkg/interface/src/logic/lib/useLazyScroll.ts
- pkg/interface/src/logic/lib/useRunIO.ts
- pkg/interface/src/logic/lib/util.ts
- pkg/interface/src/logic/state/group.ts
- pkg/interface/src/logic/state/metadata.ts
- pkg/interface/src/views/apps/notifications/graph.tsx
- pkg/interface/src/views/apps/notifications/group.tsx
- pkg/interface/src/views/apps/notifications/header.tsx
- pkg/interface/src/views/apps/notifications/inbox.tsx
- pkg/interface/src/views/apps/notifications/invites.tsx
- pkg/interface/src/views/apps/notifications/notification.tsx
- pkg/interface/src/views/components/Author.tsx
- pkg/interface/src/views/components/Invite/Group.tsx
- pkg/interface/src/views/components/Invite/index.tsx
- pkg/interface/src/views/components/Timestamp.tsx
This redesign is very visual, so have some pictures:
Included in this PR:
- Better rendering for chat messages and comments
- Comment links navigate directly to the comment, instead of the note/link containing the comment
- Clicking a finished join takes you to the joined group
- Better mobile layout 
Filing now, to save an even larger PR later. Still to come:
- Expanded notification settings screen
- Reworked behaviour around setting reads and binning
- Dismissal on mobile by swiping
cc: @g-a-v-i-n for design feedback.
> notifications: FE refactor/redesign

- pkg/interface/CONTRIBUTING.md
- pkg/interface/package.json
- pkg/interface/preinstall.sh
The original commit was reverted hot on next-js because the auto-deploy script was crashing on some uncompiled `../npm/api` files, in the wake of package-lock requiring it to actually grab the `../npm/api` folder. 
This is because the npm in the docker instance we use to auto-deploy can't leave its pwd in an automated mode, we will need to amend docker or the package.json to let npm do that for installing these local dependencies. [See here](https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd).
However with and without this preinstall script there's an ongoing issue in developing on Landscape where the npm cache across these four packages can get into some wild desynchronisation, requiring some [truly silly …
> meta/interface: re-integrate preinstall script with clean install

- pkg/interface/src/logic/state/contact.ts
- pkg/interface/src/views/components/MentionText.tsx
Mentions currently don't show nicknames ever right now; this is because the new hook introduced in #4738, `useContact`, is passed with whatever ship string we give it, which, in graph-store, doesn't include a sig, but in contact-store, is referenced with a sig. We just deSig and prepend a sig in all cases now.
> MentionText: pass all ships with sigs

- pkg/interface/src/views/components/Invite/Group.tsx
- pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
contained in this PR:
Purely visual fixes to two small issues:
1. Incorrect border radius in notification items (the little "reference elbow" that shows were an invite is coming from)
2. Sidebar coloration: After actually trying out `black80`, it's still too subtle. I think what we had before was good, in that no one was complaining about sidebar contrast. It looks a little dull/inactive at first, but you quickly get acclimated.
Reference Elbow Before:
Reference Elbow After:
~
Sidebar Before:
Sidebar After:
> ed: visual tweaks to notifications and sidebar 

- pkg/interface/src/views/App.js
Even if overflow is hidden, certain mobile browsers may interpret a
scroll event to be on the document root, leading to strange and
inconsistent scrolling behaviours. Addresses this by adding
touch-action: none, which explicitly instructs browers to ignore this
element in scroll calculations.
> interface: correctly scroll lock document

- pkg/interface/src/views/apps/launch/app.js
This was causing the tutorial to never be shown. This change should be
deployed with a new pill, to ensure comets show the tutorial.
> launch: fix reversed destructure

- pkg/interface/src/logic/state/settings.ts
Prevents a race condition where the tutorial prompt will always show
> settings: default tutorial to seen

- pkg/interface/src/views/landscape/components/Home/Post/PostReplies.js
If an item is top of view, and has a parent, we now render the parent author we are replying to.
Fixes an unfiled bug.
Before / after
> PostReplies: show parent author in parent postItem

- pkg/interface/src/logic/api/hark.ts
- pkg/interface/src/logic/lib/hark.ts
- pkg/interface/src/logic/lib/platform.ts
- pkg/interface/src/logic/state/hark.ts
- pkg/interface/src/logic/state/metadata.ts
- pkg/interface/src/views/apps/notifications/notification.tsx
- pkg/interface/src/views/apps/notifications/notifications.tsx
- pkg/interface/src/views/apps/settings/components/lib/GroupChannelPicker.tsx
- pkg/interface/src/views/apps/settings/components/lib/NotificationPref.tsx
notifications: bring preferences to spec
notifications: update dismiss action styling
Dismiss button is shown on hover, for everything except mobile, where it's shown all the time. Punting the actual slide-to-reveal delete button in favour of a broader conversation about animation libraries in the weekly meeting. 
notifications: fix broken pagination
Fixes urbit/landscape#788
> notifications: preferences screen, fix pagination 

- pkg/arvo/sys/vane/gall.hoon
Following @philipcmonk's recommendation in https://github.com/urbit/urbit/issues/4687.  Should help clarify problem with Gall request queueing.
> gall: print on missing request for ack

- pkg/arvo/sys/hoon.hoon
- pkg/arvo/sys/vane/clay.hoon
- pkg/arvo/sys/vane/eyre.hoon
- pkg/arvo/sys/zuse.hoon
Four separate changes aimed at improving landscape initial load time, with notes in the individual commit messages.  I also determined that we're compiling marks on every refresh.  In my opinion, we should keep all marks "warm", but in the meantime you can run `-test %/mar ~` to warm them up until they're invalidated by a dependency changing (for example zuse).
Combined, these changes take my initial landscape load from 28 seconds to 6.3 seconds (under profiling; a bit faster in real-world).  Still far too long!
With marks warmed up (by running `-test %/mar ~`) it takes 12 seconds even without any other changes, so that's the most important thing.  The changes in this PR cut that time in half again.
The majority of the remaining time (3.5 seconds) is spent in mark conversion to json …
> sys: Speed up things used in Landscape

- pkg/arvo/sys/vane/eyre.hoon
- pkg/interface/src/views/css/fonts.css
https://web.dev/font-display/?utm_source=lighthouse&utm_medium=unknown
Fixes https://github.com/urbit/landscape/issues/762
> eyre + interface: use font-display: swap; to reduce time to paint text

- pkg/arvo/app/metadata-store.hoon
I should have cast the action I passed into the !> in #4748. Apologies, I messed up.
> metadata-store: actually fix it, strongly type the action sent to %pull-hook to prevent moronic errors
