pkg/interface/src/views/apps/notifications/notifications.tsx, pkg/interface/src/views/apps/publish/components/Note.tsx
While indigo-react 1.2.20 passes background colors to actions for us, it doesn't yet, so these are still whited out unnecessarily. Patching for now.
Fixes urbit/landscape#802
=> landscape: pass background colors to actions

pkg/interface/package-lock.json, pkg/interface/package.json, pkg/interface/src/logic/lib/publish.ts, pkg/interface/src/logic/lib/tutorialModal.ts, pkg/interface/src/logic/lib/useLocalStorageState.ts, pkg/interface/src/logic/lib/useModal.tsx, pkg/interface/src/logic/lib/usePreviousValue.ts, pkg/interface/src/logic/lib/useRunIO.ts, pkg/interface/src/logic/lib/useStatelessAsyncClickable.ts, pkg/interface/src/logic/lib/useStorage.ts, pkg/interface/src/logic/lib/util.ts, pkg/interface/src/logic/lib/workspace.ts, pkg/interface/src/logic/reducers/connection.ts, pkg/interface/src/logic/reducers/group-update.ts, pkg/interface/src/logic/reducers/hark-update.ts, pkg/interface/src/logic/reducers/launch-update.ts, pkg/interface/src/logic/reducers/settings-update.ts, pkg/interface/src/logic/state/launch.ts, pkg/interface/src/logic/store/store.ts
I want to work on doing some interface CI, but first that means I need to actually make our TypeScript check not have 300+ errors. I started by adjusting the `pkg/interface/src/logic` folder, here, to fix all the errors when type checking by making them safer or otherwise reflect what we're actually doing.
I still have to figure out the Zustand types failing for some strange reason. I would rather just not use them at this rate.
I also upgrade TypeScript to 4.2 in this PR. I don't think the breaking changes in 4.0 affect us.
=> landscape/logic: type safety adjustments

pkg/interface/src/views/apps/notifications/graph.tsx
Fixes crash in notifications screen. Don't have repro, @matildepark can you confirm fix?
=> GraphNotification: safe property access

pkg/arvo/app/group-timer.hoon
Fixes an infinite loop of kick and resubscribes. Already deployed to ~difmex-passed
=> group-timer: fix mark assertion

pkg/interface/src/logic/lib/virtualContext.tsx, pkg/interface/src/views/apps/permalinks/embed.tsx, pkg/interface/src/views/components/VirtualScroller.tsx
VirtualScroller: fix race condition in ref deletion
A callback ref is called after the component is mounted, but before the
component is unmounted. However, we might still be adjusting scroll
position based on a component that is going to be remounted. Previously,
we delayed the deletion until the next tick with setTimeout. With the
faster ordered map implementation, the component may be remounted
before the next tick, leading to the deletion of a ref that is still
mounted. To work around this, we store a set of 'orphans' and clear the
map of orphans on an interval, and only clear the map if we are not
currently adjusting our scroll position. Also includes fixes for jumpy
scroll behaviour on initial mount.
virtualContext: fix useVirtualResizeProp
=> VirtualScroller: fix race conditions and excessive scroll adjusting

pkg/urbit/noun/manage.c
This PR updates the u3 exception mechanism (bail) to no longer treat `bail:meme` (OOM on the loom) as a fatal error.
I've been hesitant to make this change, as I'm not confident that I completely understand all scenarios. So I've additionally made all top-level bails fatal. This was already explicitly the case for `bail:exit` (deterministic nock reduction failure), and appeared to be implicitly the case for most other errors. There is still code that tries to recover from some top-level bails (see `recover: top`), but I don't see how it could maintain our invariants with regards to memory management. I'm leaving it for now until this implementation can be more thoroughly cleaned up.
Additionally, I've cherry-picked a cleanup commit from #4675, and removed assertions from the emergency …
=> u3: propagate bail:meme

pkg/urbit/include/noun/serial.h, pkg/urbit/jets/e/slaw.c, pkg/urbit/noun/imprison.c, pkg/urbit/noun/retrieve.c, pkg/urbit/noun/serial.c, pkg/urbit/tests/jet_tests.c
Fixes #4767, and improves performance.
There was a jet mismatch in `+slaw`; the `@ud` parser mistakenly allowed leading zeros, and less-than-3-digit blocks between `.` separators. Those bugs have been corrected in a new implementation.
To test the performance, I parsed a big `@ud` in a loop.
```
> =do |*([max=@ud arg=* fun=gate] =|(i=@ud |-(?:(=(max i) ~ =+((fun arg) $(i +(i)))))))
> |start %time
```
The raw parser combinator:
```
> :time (do 1.000 (rap 3 ['123.456.789' (reap 200 '.123.456.789')]) |=(a=@t (rush a dem:ag)))
[%took ~s21..438a]
```
The old, overly-lenient jet:
```
> :time (do 1.000 (rap 3 ['123.456.789' (reap 200 '.123.456.789')]) |=(a=@t (slaw %ud a)))
[%took ~s5..697e]
```
The new jet:
```
> :time (do 1.000 (rap 3 ['123.456.789' (reap 200 '.123.456.789')]) |=(a=@t (slaw …
```
=> u3: rewrites %ud parser

pkg/arvo/lib/graph-store.hoon, pkg/arvo/lib/metadata-store.hoon
Attempting to remove all uses of `+trip` and `+crip` from the hotpath that Landscape data moves through. These arms make quite a few allocations and can be replaced with `+rap` for better performance.
The change to the `%graph-store` lib is likely to have a larger effect.
=> graph-store, metadata-store lib: skip trip and crip, use rap

pkg/interface/src/views/apps/chat/ChatResource.tsx, pkg/interface/src/views/components/VirtualScroller.tsx
ChatResource: prevent unnecessary state update
VirtualScroller: only rerender on scroll lock if necessary
VirtualScroller: lock scroll less aggressively
Prevents incorrect scroll adjustment
VirtualScroller: aggressively cleanup refs
Prevents a memory leak, as it appears React holds onto the class
instance after unmounting
VirtualScroller: rework scroll initialisation
Calling restore if the scroll is locked simply resets the scroll,
instead of using the usual adjustment algorithm
=> VirtualScroller: performance, memory leaks

pkg/arvo/lib/language-server/parser.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/clay.hoon
Hoon files may want to import nouns from all files in a given directory.
`/~` lets you do so, importing as a noun structured like a `(map @ta *)`.
Note the description as "directories" here, instead of "path prefix".
The behavior, as implemented, will not include `/path/hoon` for `/~  /path`, instead only including `/path/more/hoon` and more deeply nested files.
This seems to be, generally, the behavior you want, for example when importing from `/app/myapp/*` for use in `/app/myapp/hoon`.
It's a bit out of line compared to general clay semantics though, so RFC.
Also, the map keying by `@ta` seems more ergonomic than `path` for most cases, but does run into the usual hyphenation-ambiguity problem, where `/path/a/b/hoon` and `/path/a-b/hoon` would conflict with each other. Again, RFC.
From …
=> clay: add /~ ford rune, as /= for directories

pkg/interface/src/views/apps/chat/components/ChatInput.tsx, pkg/interface/src/views/apps/chat/components/ChatMessage.tsx, pkg/interface/src/views/apps/chat/components/chat-editor.js, pkg/interface/src/views/components/ProfileOverlay.tsx, pkg/interface/src/views/components/RemoteContent.tsx, pkg/interface/src/views/components/StatusBar.js, pkg/interface/src/views/components/leap/OmniboxResult.js, pkg/interface/src/views/landscape/components/Graph/GraphContentWide.tsx
Some very fun visual updates to chat, courtesy of @jyng.
- Introduces click-to-copy a ship's name in the mini-profile overlay.
- Swaps to the new Messages icon in the status bar and in Leap.
- Switches the cursor to `pointer` for Attachments and Dojo in the Chat input field.
- Swaps the message loading placeholder background to `washedGray` and rounds the box corners by 4px.
- Presents external images in chat with no gray border or padding, and introduces a 4px border-radius.
- When hovering over an external image, surfaces a small visual cue in the upper-right of the image.
- When images are in a normal chat flow context, makes the entire image, but when an image is transcluded, limits interactivity to this small visual cue. (This is in anticipation of clicking the entire transuded block …
=> chat: jimmy's visualfix omnibus

pkg/interface/src/views/apps/chat/components/ChatInput.tsx, pkg/interface/src/views/apps/chat/components/chat-editor.js
Discovered some inconsistent and frustrating event behavior with #4801 where the act of clicking the disabled Send button in ChatInput would blur the field, thereby hiding the button you just tapped. This persists the Send button regardless of input focus, and turns the button blue if the user has entered some text.
Default experience otherwise:
=> chat: persist submit button

pkg/interface/src/views/components/ColorInput.tsx
ColorInput sets its value to `#{value}` but we skim off that prepended pound onChange and basically everywhere else. However, if you set a different value on the same page (like theme) and resubmit without actually typing into the ColorInput, the component will return `#{value}`, which gets duplicate prepended and submitted to the ship as `##{value}`, breaking the background color.
Fixes urbit/landscape#803
=> ColorInput: remove "#" from input value

pkg/interface/src/views/apps/links/components/LinkItem.tsx, pkg/interface/src/views/apps/publish/components/Note.tsx, pkg/interface/src/views/components/Author.tsx, pkg/interface/src/views/components/CommentItem.tsx, pkg/interface/src/views/components/Timestamp.tsx, pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostHeader.js
Somewhere in there we lost timestamps on comment items, notes, links, etc. etc. I use `props.date` as a fallback in `Timestamp` and also add a prop to set line-height to force Author and Timestamp to line up across all instances it's used (Links, Publish, Group Feed, etc etc) — the `tall` line-height breaks `align-items` otherwise.
=> landscape: restore timestamps across interface

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx, pkg/interface/src/views/components/CommentItem.tsx
Was using Landscape and was just thinking "we should probably have this"...
cc @urcades — how's this look (it's just using our already-defined highlight styles) and do you approve of the feature?
@liam-fitzgerald @tacryt-socryp I don't think this is that expensive, is it?
=> landscape: highlight content mentioning our ship

pkg/arvo/app/chat-cli.hoon
This feels more correct, and matches historic on-;join behavior.
Fixes #4758.
=> chat-cli: update audience on-;view

pkg/hs/urbit-king/lib/Urbit/Arvo/Common.hs, pkg/hs/urbit-king/lib/Urbit/Vere/Ames/Packet.hs, pkg/hs/urbit-king/lib/Urbit/Vere/Ames/UDP.hs
In king haskell, it seems, the "lane" is more of a poorly lit alley, an alley I hope I don't have to walk through ever again.
This time around, it seems I got the byte order of the ip address wrong. According to https://hackage.haskell.org/package/network-3.1.2.1/docs/Network-Socket.html#t:HostAddress, the ip address in haskell is represented as a Word32, of which it is said, confusingly, that "[t]he raw network byte order number is read using host byte order." On real computers, this means it's reversed, which, apparently, is not what the corresponding c function does. So we fix that here. Hopefully.
We also add code to guarantee that when your UDP port is closed and reopened due to a problem, it is opened at the same port. Previously, if you hadn't explicitly specified a port, we'd ask …
=> king: fix lanes yet again, also reuse udp port

pkg/hs/urbit-king/lib/Urbit/Vere/Clay.hs
Brings the haskell king inline with the C king (see: https://github.com/urbit/urbit/blob/268677e74412d80eb5ebc9eed4c3add20a274f91/pkg/urbit/vere/io/unix.c#L845)
This discrepancy in behaviour breaks janeway. 
(Also, is this against the right branch?)
=> king: do not commit files starting with a dot

nix/pkgs/hs/default.nix
By way of ensuring the lmdb package's cabal extra-libraries field is ignored and our lmdb overlay is used. 🤷🏽
=> king: ensure lmdb is statically linked on osx

pkg/urbit/vere/io/cttp.c
This PR fixes a crash introduced by #4766. That PR fixed a longstanding, rare crash in the http-client driver, caused by a surprising synchronous call to a normally async callback, which would result in a use-after-free. The fix introduced a new, deterministic crash for every TLS request, due to my misunderstanding of the code (which I had written).
`cttp.c` always connects by ip/port, to avoid synchronous `getaddrinfo()` calls in the library (we use libuv's threadpool at call sites). In order to correctly negotiate TLS sessions, we must also synchronously patch the SNI data, but only after successful `connect()` calls. This PR extends the client request state machine to correctly cover these edge cases.
=> vere: fix cttp tls crash from (bad) fix for synchronous error callback 

pkg/docker-image/README.md
Minor documentation update to fix the examples and clarify best practices for setting and mapping the Ames UDP port while running Urbit in docker.
=> docker: update documentation

pkg/interface/src/logic/api/contacts.ts, pkg/interface/src/logic/state/contact.ts, pkg/interface/src/logic/state/graph.ts, pkg/interface/src/logic/state/local.tsx, pkg/interface/src/views/apps/chat/ChatResource.tsx, pkg/interface/src/views/apps/chat/components/ChatInput.tsx, pkg/interface/src/views/apps/chat/components/ChatMessage.tsx, pkg/interface/src/views/apps/chat/components/ChatPane.tsx, pkg/interface/src/views/apps/chat/components/ChatWindow.tsx, pkg/interface/src/views/apps/chat/components/ShareProfile.js, pkg/interface/src/views/components/withStorage.tsx
Paves the way for DMs, by stripping the association prop everywhere and refactoring the Chat functionality into ChatPane, which makes no assumptions about the presence of an association or group by lifting that functionality into prop callbacks.
=> Chat: refactor to strip associations prop

pkg/arvo/lib/pull-hook.hoon, pkg/arvo/lib/push-hook.hoon
Prevents undue network pressure due to spurious kicking. Also prevents the looped pull-hook add issue at the source.
=> hooks: don't kick every reload

pkg/arvo/sys/vane/clay.hoon
Four changes:
- implement +validate-u to allow %u requests over the network
- make +validate-x use our local marks to make %x requests generally
work over the network
- in +start-request, if a foreign ship is making a request that we
shouldn't send over the network, ignore it.  This closes a DOS vector.
- in +duce, if we're about to make a request to a foreign ship which
they won't be able to answer, crash the event.
Combined, these fix many of the common cases of weirdness around foreign
clay requests.  Notably absent is a fix for reading `%a` across the
network, which I still maintain should happen against the foreign
hoon/zuse.
fixes #4834
see also #4307
Thanks to @tinnus-napbus for providing a repro for these
=> clay: fix requests for strange cares over ames

pkg/interface/src/views/apps/chat/components/ChatInput.tsx, pkg/interface/src/views/apps/chat/components/chat-editor.js
- Clears state on submit such that the button does not stay blue
- Refocuses field on submit such that the mobile keyboard doesn't disappear
- Removes submit on enter; retains enter for linebreak insertion
=> chat: input behavior quirks

pkg/arvo/app/graph-store.hoon, pkg/arvo/lib/graph-store.hoon, pkg/arvo/lib/graph.hoon
Hotfixes the lack of update log for graphs which causes frequent resetting of unreads and notifications.
The varying timestamp in the %add-graph fact from graph-push-hook was
preventing deduplication of the jammed noun in ames. Prevents
unnecessary bail: memes upon sending many %add-graph facts.
=> graph-store: update log hotfixes

pkg/urbit/vere/io/ames.c
In some situations it's useful to restrict the Ames packets that arrive
to be from a certain set of ships.  We've needed this a few times in the
last few years, so this creates an ifdef-ed out function for doing this.
It looks like `lan_u` does not get freed in the normal case, but I'm not really sure why not.
=> ames: add packet filter for rescue operations

pkg/urbit/vere/auto.c
%behn timers running ahead of %ames prevents us from draining ames queues as fast as possible.
=> vere: deprioritize %behn

pkg/arvo/app/launch.hoon, pkg/interface/src/logic/api/local.ts, pkg/interface/src/logic/reducers/launch-update.ts, pkg/interface/src/logic/state/launch.ts, pkg/interface/src/types/local-update.ts, pkg/interface/src/views/App.js, pkg/interface/src/views/apps/launch/app.js, pkg/interface/src/views/apps/notifications/inbox.tsx, pkg/interface/src/views/components/StatusBar.js, pkg/interface/src/views/components/leap/OmniboxResult.js
If arvo indicates it needs a newer runtime to apply an upgrade, we now
display a persistent notification on the notifications screen and
turn the base hash background yellow.
Took the liberty of adding a yellow notification dot for this case. If there are any other notifications, the blue dot gets drawn on top of it. Seemed better than displaying multiple dots.
Tagging @urcades for design review. Your mocks had a link, but I'm not sure what's a good place to point that to. We don't have a docs page for _upgrading_ the binary specifically...  
Not sure who's most appropriate to tag for a JS review in this area, so I just picked 
@liam-fitzgerald. Feel free to defer.
Closes urbit/landscape#188.
=> landscape: version negotiation notification

pkg/arvo/app/hark-graph-hook.hoon
Marginal performance gains that pave the way for larger ones. (Really tiny)
Should do two fewer scries when adding a graph, and one less per %add-nodes update.
Ideally, we'll move to using %watch-as for converting %add-nodes into $notif-kind
=> hark-graph-hook: remove unnecessary scries where possible for perf

pkg/interface/src/logic/lib/util.ts, pkg/npm/api/README.md, pkg/npm/api/contacts/lib.ts, pkg/npm/api/graph/lib.ts, pkg/npm/api/groups/lib.ts, pkg/npm/api/hark/lib.ts, pkg/npm/api/hark/types.ts, pkg/npm/api/index.ts, pkg/npm/api/metadata/lib.ts, pkg/npm/api/metadata/types.ts, pkg/npm/api/package-lock.json, pkg/npm/api/package.json, pkg/npm/api/s3/index.ts, pkg/npm/api/tsconfig.json, pkg/npm/eslint-config/package-lock.json, pkg/npm/http-api/.gitignore, pkg/npm/http-api/Urbit.ts, pkg/npm/http-api/example/browser.js, pkg/npm/http-api/example/node.js, pkg/npm/http-api/index.ts, pkg/npm/http-api/package-lock.json, pkg/npm/http-api/package.json, pkg/npm/http-api/tsconfig.json, pkg/npm/http-api/types.ts, pkg/npm/http-api/utils.ts
This brings the `@urbit/api` and `@urbit/http-api` code in the code base up to date with what is currently published on npm. 
Landscape does not rely on `http-api` so those changes shouldn't be a problem — most of these changes are bugifxes discovered while working on https://github.com/urbit/urbit/pull/4611 or by other contributors.
Landscape does rely on `api` but most of those changes should be to functions that have not been integrated back into Landscape yet.
=> npm: Updated http-api and api packages

pkg/arvo/lib/pull-hook.hoon, pkg/arvo/lib/push-hook.hoon, pkg/arvo/lib/versioning.hoon
hooks: add diplomacy flag
pull-hook: slog tank on versioned nack
Should hopefully provide more debugging info for ghost subscriptions
push-hook: hold subscription open after validating access
When we receive a watch-nack on a versioned subscription, we attempt to
resubscribe on an unversioned path. However, if we receive an unversioned
subscription request for which we are not compatible, we hold the
subscription open and never send any facts on unversioned subscriptions.
As the check for unversioned compatiblility occurs before retrieving the
initial-watch, subscriptions which are supposed to nack never do. Fixed
by moving the conditional.
Fixes urbit/landscape#795
versioning: convert gates return a cage
=> hooks: refactor, fix nacking, slog ghosts

pkg/arvo/gen/hood/code.hoon
Because `|code %reset` logs out all active web sessions (and does not produce or print the new code), it causes problems if run through web terminal, without access to the actual terminal. This feature should be redesigned for compatibility without hosting.
In the meantime, this PR adds a warning and requires for confirmation before reset. Wording improvements welcome.
/cc @brendanhay
=> gen: warn and prompt for confirmation in |code %reset

pkg/arvo/app/file-server.hoon, pkg/arvo/lib/server.hoon, pkg/arvo/mar/ico.hoon
Adding support for .ico files makes hosting prebuilt websites on urbit easier.
This commit utilizes the following changes to effectuate .ico support:
-/mar/ico/hoon
* Utilizes similar structure to /mar/png/hoon, w/ changed mimetype
-/lib/server
* Added ico-response, again similar to png w/ same caching
-/app/file-server
* Added reference to ico-response:gen
This will also rectify one complexity glossed over in [this docs addition](https://github.com/urbit/docs/pull/1067) and allow for minor simplification of the guide.
=> file-server: Added support for .ico files:

pkg/interface/src/views/apps/permalinks/TranscludedNode.tsx
Doesn't calculate the index of the transcluded node if the node prop is undefined because of a timing issue in the parent component or any other reason.
fixes urbit/landscape#841
=> permalinks: fix crashing slice error

pkg/interface/src/logic/lib/publish.ts, pkg/interface/src/views/apps/publish/components/Note.tsx, pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx
- Enables forestry features for all users now that the renderer is on livenet. Mentions, group links, transclusions, etc.
- Makes headers blocks.
- Fixes links with proper href now.
- Adds break elements to renderers.
- Passes `tall` to the renderer so it doesn't treat all notes as inline. Changes the container for tall content into a grid so that `row-gap` works and separates content.
=> publish: amazon

pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx
Fixes urbit/landscape#842
She said, "it's literally always better to flex truncate a title than to push UI out of the container. lol. lmao"
=> ResourceSkeleton: always flex-shrink

pkg/interface/src/views/apps/permalinks/embed.tsx
Presents a message when a reference is unavailable -- in this case, it's referring to a chat message in a channel in a private group I have not joined.
=> permalinks: present error for unavailable references

pkg/interface/src/views/apps/permalinks/TranscludedNode.tsx
Adds styling to deleted chat references.
Deleted chat reference from the same resource:
Deleted chat reference from another resource:
=> permalinks: style deleted chat reference

pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx
=> GraphContent: prevent grid blowout

pkg/interface/src/views/components/GroupLink.tsx
Although the bug was poetic, this makes the icon in GroupLink aware of the group's hidden status and surfaces a lock icon in those cases instead of the "public" globe icon.
=> groups: World Privacy icon fix

pkg/interface/src/views/apps/permalinks/embed.tsx, pkg/interface/src/views/components/GroupLink.tsx
- Uses "peer" for a single-member GroupLink; "peers" for >1... peer.
- Avoids the problem of an empty nested embed within the same resource (I quote you, you quote me quoting you, observe blank 12px-high box). Surfaces the permalink resource in this case.
=> permalinks: minor fixes

pkg/interface/src/views/components/GroupLink.tsx
Adds a space, which I forgot in a previous PR.
=> permalinks: add group peer space

.github/workflows/glob.yml, .github/workflows/merge-master.yml, MAINTAINERS.md
This PR retires next-js in favour of next-userspace, auto-deploying next-userspace to the dev stream. 
Going forward _all possible changes_ should target next-userspace for staging deployment; irrevocably breaking changes will target the next dated release branch (eg. 1.8's branch will be `release/2021-5-27`).
=> meta: auto-deploy release/next-userspace

pkg/interface/src/views/apps/links/LinkResource.tsx
Conforms the `baseUrl` prop we pass to `Comments` from within `LinkResource` to fit the new `/index/:index` route used as of permalinks.
Very confused where this broke, since all related code has been the same for two months. Has editing links comments been broken that long?
Fixes urbit/landscape#873
=> LinkResource: add index to baseUrl prop

pkg/interface/src/views/apps/launch/components/Groups.tsx, pkg/interface/src/views/components/StatelessAsyncAction.tsx, pkg/interface/src/views/components/StatusBar.tsx
Makes the SYB button and notification dismiss buttons square.
Also gets rid of the annoying "these iterable elements don't have unique keys" console error on the group grid view.
fixes urbit/landscape#836
fixes urbit/landscape#833
=> interface: square buttons; home: squash group key squawking

pkg/arvo/sys/vane/ames.hoon
Time out direct lanes much faster after inactivity.  Removes logic in +on-memo that reset the `last-contact` time to `now` after a period of inactivity; this caused the ship to restart the lane timeout logic from scratch on a new message after a period of inactivity.  The problem with this was that if the lane had been held open by the receiver's firewall as a pinhole that has since closed, the firewall would drop any new packets, and it would take on the order of minutes to resume connectivity between the two ships.
After this change, if the first packet times out on a direct lane that has been inactive for thirty seconds or more, the lane will be marked as indirect, causing retries to hit the peer's sponsor.  This puts marginally more relaying load on sponsors, but should improve …
=> Ames: time out direct lanes faster

pkg/arvo/sys/hoon.hoon
I.e, print `.10` as `.10` not `.1e1`. Only use `e+-N` when it would be shorter.
Before:
```
> (turn (gulf 1 10) |=(a=@u (turn (gulf 0 9) |=(b=@u (grd:rs d/[& -5 (mul (pow 10 a) +((pow 10 b)))])))))
~[
~[.2e-3 .1.1e-3 .1.01e-2 .1.001e-1 .1.0001 .1.00001e1 .1.000001e2 .1.0000001e3 .1e4 .1e5]
~[.2e-2 .1.1e-2 .1.01e-1 .1.001 .1.0001e1 .1.00001e2 .1.000001e3 .1.0000001e4 .1e5 .1e6]
~[.2e-1 .1.1e-1 .1.01 .1.001e1 .1.0001e2 .1.00001e3 .1.000001e4 .1.0000001e5 .1e6 .1e7]
~[.2 .1.1 .1.01e1 .1.001e2 .1.0001e3 .1.00001e4 .1.000001e5 .1.0000001e6 .1e7 .1e8]
~[.2e1 .1.1e1 .1.01e2 .1.001e3 .1.0001e4 .1.00001e5 .1.000001e6 .1.0000001e7 .1e8 .1e9]
~[.2e2 .1.1e2 .1.01e3 .1.001e4 .1.0001e5 .1.00001e6 .1.000001e7 .1.0000001e8 .1e9 .1e10]
~[.2e3 .1.1e3 .1.01e4 .1.001e5 .1.0001e6 .1.00001e7 .1.00000096e8 …
```
=> [hoon co] Fix float printer overuse of scientific notation

pkg/interface/src/logic/lib/util.tsx
~~before/after:~~ after/before:
Also changes the sidebar sort algorithm — doesn't seem to break anything but I don't think I'm in any groups with emoji channel names.
Fixes https://github.com/urbit/landscape/issues/875
=> interface: changed alphabeticalOrder to ignore non-word characters

pkg/arvo/app/dm-hook.hoon, pkg/arvo/app/hood.hoon, pkg/arvo/lib/hood/drum.hoon
- Autoboots dm-hook on upgrade and initialisation
- Fixes the +on-init logic scry
=> dm-hook: boot fixes

pkg/interface/src/logic/api/graph.ts, pkg/interface/src/logic/reducers/graph-update.ts, pkg/interface/src/views/apps/launch/components/Groups.tsx, pkg/interface/src/views/landscape/components/GroupSwitcher.tsx, pkg/interface/src/views/landscape/components/GroupsPane.tsx
Groups: fix keying
GroupSwitcher: update recent groups on unmount
Fixes an unfiled bug where switching to a non-group workspace would not
add the most recent group to the group switcher
graph-reducer: ignore superfluous updates
Reduces RAM usage drastically, especially in long-lived sessions
=> interface: misc grabbag

pkg/arvo/sys/hoon.hoon
The current default `seminoun` is wrong, given the pattern of bunting batteries in `+play:ut`.
=> hoon: update seminoun bunt to be fully blocked

pkg/urbit/jets/e/argon2.c
=> jets: fix malloc check

pkg/interface/src/views/apps/permalinks/TranscludedNode.tsx, pkg/interface/src/views/apps/permalinks/embed.tsx
Adds an sigil/author skeleton loader to transcluded blocks such that the chat view doesn't dramatically jump with unloaded content. Sets a 'pending' flag in state in the async call, as it turns out this was much simpler and reliable than checking for undefined props.
https://user-images.githubusercontent.com/748181/118661351-070e1f00-b7bd-11eb-85b5-32eb5bd922a6.mp4
Also brings the author/content lines into alignment with Chat references due to the new ChatMessage line-height.
=> permalinks: graph node placeholders

pkg/arvo/app/graph-store.hoon, pkg/arvo/mar/graph/validator/chat.hoon, pkg/arvo/mar/graph/validator/link.hoon, pkg/arvo/mar/graph/validator/post.hoon, pkg/arvo/mar/graph/validator/publish.hoon
Introduced by lack of full mark testing on: https://github.com/urbit/urbit/pull/4554
Fixes urbit/landscape#889
=> graph-validators: hotfix broken vale:dais caused by removal of +bunt from clay

pkg/interface/src/views/apps/permalinks/TranscludedNode.tsx, pkg/interface/src/views/apps/permalinks/embed.tsx
Unifies padding around placeholder rows and brings loaded permalink nodes back into alignment.
=> permalinks: final spacing pass for elements + placeholders

pkg/interface/src/views/apps/chat/components/ChatInput.tsx
Gets rid of a blank space in ChatInput if S3 isn't configured.
fixes urbit/landscape#892
=> chat: no s3, no blank space

pkg/interface/src/logic/lib/tokenizeMessage.js, pkg/interface/src/logic/lib/tokenizeMessage.test.js
- Patp regex is less flexible, only accepts one "any" character before a mention.
- Links regex parses _before_ group reference parser to prevent breaking references.
- Groups regex will only match on preceding spaces, there will never be a case where people are mingling it mid-word like `Here's a message~haddef-sigwen/mygroup`.
- All regex looks for `\s\S` now, not `.`, because `.` doesn't match on whitespace characters eg. line breaks, thus eating the remainder of a message that has line breaks after, well, any mention or URL.
You can give this a shot with a notebook's comment field, if you segregate links to groups, mentions, URLs with line breaks.
=> tokenizeMessage: revenge

pkg/btc-wallet/config/webpack.prod.js
Not needed for the build process, causes a crash.
=> btc: remove urbitrc import

pkg/arvo/sys/arvo.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/gall.hoon
This PR saves us an additional 15-20ms per event by reducing arvo scry overhead.
=> arvo: add %whiz option to  that allows one to prime the compiler cache

pkg/npm/http-api/package.json
Targeting master so it gets pushed to npm faster. LMK if there's a problem with that. Fixes https://github.com/urbit/urbit/issues/4941
=> npm/http-api: changed relative dependency

pkg/interface/src/logic/lib/tokenizeMessage.js, pkg/interface/src/logic/lib/tokenizeMessage.test.js
- Races the regexes and chooses the regex which produces the shortest prefix, i.e. the closest match. 
- Adds tests to cover cases
- No longer adds superfluous text nodes
=> tokenizer: please I beg no more

pkg/interface/src/logic/reducers/contact-update.ts, pkg/interface/src/views/apps/profile/components/ViewProfile.tsx
When applying add-group or remove-group updates optimistically (https://github.com/urbit/urbit/commit/a11a1e42ce402e0433a63ec45ee8b964867d38d5), we send
our ship resourceFromPath objects, and get back `/ship/~name/resource`
strings. When we apply the update optimistically, we use the former,
storing the object in state. This causes interface errors, as it expects
the string. Therefore, on both cases in the reducer we construct the string and 
dedupe if it comes in after application.
Fixes urbit/landscape#917
=> interface: catch contact-update type mismatch

pkg/arvo/app/graph-store.hoon, pkg/arvo/mar/graph/validator/chat.hoon, pkg/arvo/mar/graph/validator/link.hoon, pkg/arvo/mar/graph/validator/post.hoon, pkg/arvo/mar/graph/validator/publish.hoon, pkg/arvo/sys/vane/eyre.hoon
A draft of work to prime caches for any `%c` conversion that `%eyre` does to json.
Note: I don't know much about ducts or how to handle the response I get back from clay (or if I need to), but this compiles so I figured I'd push it up and get somebody to help me figure out the rest.
Edit: Can confirm that this works in practice on livenet and shaves 70ms off of a `%graph-update` event.
Given that I've tested this on my livenet ship, I'm marking this as ready, but I'd still like some comments on the duct stuff / ways to heat these caches more efficiently (getting rid of the time spent in nest checks would be ideal).
Edit: Latest version takes about 300ms per event, so this overall gives us a 40% speedup.
=> eyre: send warp to warm %f cache for any mark that gets used and switch to %f from %c

pkg/arvo/app/graph-store.hoon, pkg/arvo/mar/graph/validator/chat.hoon, pkg/arvo/mar/graph/validator/link.hoon, pkg/arvo/mar/graph/validator/post.hoon, pkg/arvo/mar/graph/validator/publish.hoon, pkg/arvo/sys/arvo.hoon, pkg/arvo/sys/hoon.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/gall.hoon
Made `+look` in arvo significantly faster. A trace that has the eyre performance improvements merged in already takes about 120ms less per chat message sent. Down from 300ms to 180ms.
=> arvo: add +de-case to speed up +de-beam, prime cache in +settle:va

pkg/arvo/app/btc-wallet.hoon, pkg/arvo/lib/btc.hoon, pkg/arvo/sur/btc-wallet.hoon
Instead just store the sample that gets passed into the core
=> btc: stop storing bip32 core in btc-wallet state

pkg/interface/src/logic/lib/omnibox.js, pkg/interface/src/views/components/leap/OmniboxResult.tsx
Fixes urbit/landscape#915
- Iterates through all apps regardless of tile type when indexing; instead just filters the two tiles we don't want in the index
- Provides appropriate fallback values for custom tile cases
Leap result logic is getting a little long in the tooth, but will probably amend its index behaviour quite soon anyhow. BTC Wallet's entry has no title; it feels weirder to special case it in FE, probably should add a title to it on back-end?
=> leap: render custom app tiles

pkg/arvo/lib/push-hook.hoon
Addresses a bug where if the publisher could not perform the fact
conversion, it would not be deferred to the subscriber, preventing the
subscriber from being ahead of the publisher
=> push-hook: fix version negotiation

pkg/arvo/app/graph-push-hook.hoon
Prevents messages from being dropped during the OTA, when there's a mismatch in deployed versions between host and subscriber.
=> graph-push-hook: disable proxying of DM updates

.github/actions/glob/Dockerfile, .github/actions/glob/entrypoint.sh
Despite the benign-looking patch version bump, the latest version of janeway drops support for the `--do-it-live` flag in favour of `--ci` (which also does some additional CI-specific stuff).
=> meta: update to janeway v0.15.2

pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
Fixes this confusing non-state:
Now reflective of unread/unsynced/hasNotification states (shown below with nicknames turned on and the DM at rest).
fixes urbit/landscape#623
=> messages: synced/unread treatments for group DMs in sidebar

pkg/arvo/app/graph-store.hoon, pkg/arvo/mar/graph/indexed-post.hoon, pkg/arvo/mar/graph/validator/chat.hoon, pkg/arvo/mar/graph/validator/dm.hoon, pkg/arvo/mar/graph/validator/link.hoon, pkg/arvo/mar/graph/validator/post.hoon, pkg/arvo/mar/graph/validator/publish.hoon
@belisarius222  recommended I do this recently, and I tested it and it is indeed significantly faster (by about ~20ms for a single chat / publish / link / feed message). Tested to work on Chat, Publish, Links, and Feed.
=> graph-store + validators: stop using +grab:noun and switch to using a static conversion to %graph-indexed-post

pkg/arvo/sys/zuse.hoon
We've had notes to move various parsing functions to zuse for literally years, so I figured I'd go ahead and do it.
=> zuse: comb through all notes in libraries, and move arms to zuse

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/dill.hoon
Quick and dirty forward-compatibility by pulling the new belts (from #4463) into the current dill. Intent is to send this out prior to the new dill/runtime combo as an appetizer OTA.
This, along with the new runtime doing best-effort handling of current dill's blits, will ensure that the new runtime is reasonably usable even with the old dill.
=> dill: support next runtime's inputs

pkg/interface/src/views/landscape/components/Sidebar/SidebarList.tsx
The SidebarList refactor that occurred to accomodate new-style DMs
inadvertently broke the keyboard shortcuts to switch between channels.
Revives this, and adds support for switching between DMs as well.
=> SidebarList: fix shortcuts

pkg/arvo/app/hark-graph-hook.hoon
Given that we know the types of the conversions used in `%hark-graph-hook` at compile time, there's no need to use dynamic conversions. Replaces all tubes with static conversions.
=> hark-graph-hook: speed it up with static conversions

pkg/interface/src/logic/lib/tokenizeMessage.js, pkg/interface/src/logic/lib/tokenizeMessage.test.js, pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx
- Also, respect calmengine settings in Messages sidebar (hideNicknames, hideAvatars)
=> tokenizeMessage: fix urls that end in punctuation

pkg/arvo/app/chat-cli.hoon
Noticed this misspelling in the output of the `;help` command.
=> Fix mispelling in chat-cli help message

nix/sources.json
Update from v2.2.4 to v2.2.6. Includes security fixes and some correctness fixes around HTTP2. Have tested that Landscape, HTTPS, etc still work on this version.
https://github.com/h2o/h2o/releases/tag/v2.2.5
https://github.com/h2o/h2o/releases/tag/v2.2.6
=> h2o: update to 2.2.6

pkg/interface/src/logic/lib/util.tsx, pkg/interface/src/views/landscape/components/PopoverRoutes.tsx
While this error only really happens if you have a severely malformed association, we shouldn't crash the FE in such cases. Possibly superseded by later work on data loading in Landscape, but for now, seems harmless to weave in here.
Fixes urbit/landscape#960
=> landscape: loosen owner check in popover

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx, pkg/interface/src/views/components/Author.tsx, pkg/interface/src/views/components/MentionText.tsx
My understanding of urbit/landscape#65 is that the tooltip over any sort of ship text (mention, author, chat byline) should display the inverse of whatever logic is showing it.
- If I have nicknames set to show, I should naturally see ships' nicknames (if set), and see their ~patps on hover
- If I have nicknames set to not show, I should naturally see ships' ~patps, and their nicknames on hover (if set)
- Regardless of my settings, if others have not set nicknames, they should not show and I should naturally see their ~patps with no hover text otherwise.
I may have misinterpreted the issue, since this seems inconsistent with our rule about never showing nicknames if the pilot truly does not want to see them. It's an easy enough fix to back out the second behavior above, but just need some …
=> interface: consistent  titles for mentions, authors with nicknames

pkg/interface/src/views/landscape/components/NewGroup.tsx
Implements some very simple form validation preventing group names that begin with digits. Emoji and symbols are still permitted.
fixes urbit/landscape#906
=> groups: prevents group names starting with digits

pkg/arvo/sys/vane/eyre.hoon
Surprisingly enough, this gets rid of a small nest check within spider. ~4-8ms speed-up to sending a message. I really can't seem to speed up spider any more at all, despite banging my head on it. Vases.
=> eyre: cast within zapgar to avoid nest check

pkg/arvo/ted/glob.hoon
The GCP bucket will occasionally fail requests for no good reason. Adds exponential retry to the glob thread to prevent this from affecting UX. 
Fixes urbit/urbit#4958
=> ted/glob: add exponential retry

pkg/interface/src/views/apps/settings/components/lib/CalmPref.tsx, pkg/interface/src/views/components/FormikOnBlur.tsx
- If the other toggle was clicked while we are waiting on a response for the other toggle, then would skip the submitting the second toggle click. Now no longer waits for a response
- If you refreshed right into the page, the settings would use the defaults and never be updated when the network response came in. Now updates the form whenever `initialValues` change
Fixes urbit/landscape#976
=> CalmEngine: Even calmer

pkg/interface/src/views/components/GroupLink.tsx
"fit-content" limits the clickable space for the group link, so we just
tell the row to expand to its parent.
Fixes urbit/landscape#978
=> interface/GroupLink: set full-width click area

pkg/arvo/app/dm-hook.hoon
We weren't emitting facts when pendings got updated, so new pending messages would only show on refresh
=> dm-hook: fix updating pendings

.github/actions/glob/Dockerfile, .github/workflows/glob.yml
Replaces ~lomlyx with ~hanruc due to the former's impending retirement.
(When this is merged, the glob workflow will use ~hanruc-nalfus-nidsut-tomdun as its ship target.)
=> meta: janeway version bump, new glob target

pkg/arvo/app/graph-push-hook.hoon, pkg/arvo/app/graph-store.hoon, pkg/arvo/app/hark-graph-hook.hoon, pkg/arvo/app/observe-hook.hoon, pkg/arvo/mar/graph/cache/hook.hoon, pkg/arvo/mar/transform-add-nodes.hoon, pkg/arvo/sur/observe-hook.hoon
Simplified our other apps' caching strategies and consolidated them into a general purpose utility in `%observe-hook`.  The previous caching strategy was fragile when marks were changed. Performance is approximately the same.
=> observe-hook: add ability to warm static mark conversions

pkg/interface/src/views/apps/chat/DmResource.tsx
Removes the 'delete message' action from direct messages by passing `isAdmin={false}`.
DmResource does not pass `onDelete` to its child ChatPane, but it does pass `isAdmin`, so the action is surfaced without any ability to delete, silently failing. I tried instantiating the same `removePosts` action, and it of course poked graph-push-hook, which failed during transform. dm-hook itself does not have any facility for deleting messages in its on-poke, so this seems unimplemented on back-end, and thus should not be surfaced on front-end.
As a feature it should be slated separately.
Fixes urbit/landscape#982.
=> DmResource: remove 'isAdmin' prop

pkg/npm/api/package.json, pkg/npm/api/tsconfig.json, pkg/npm/http-api/package.json
When publishing to npm, the `dist/*.js` files weren't being built, so the packages didn't work.
cc: @tylershuster
=> npm: build ts -> js files before publishing

pkg/arvo/app/btc-provider.hoon, pkg/arvo/app/btc-wallet.hoon, pkg/arvo/lib/bip/b158.hoon, pkg/arvo/lib/bitcoin.hoon, pkg/arvo/lib/btc.hoon, pkg/arvo/sur/btc-provider.hoon, pkg/arvo/tests/lib/bip/b158.hoon
Now when we get updated about a new block, only request address info for addresses that match that block's blockfilter. If there's a gap of multiple blocks, we need to go request blockfilter information for those blocks specificially. 
This depends on this PR on the urbit-bitcoin-rpc repo, which allows you to make those requests for specific block information: https://github.com/timlucmiptev/urbit-bitcoin-rpc/pull/26
=> btc: use blockfilter when requesting address info

.github/actions/glob/Dockerfile
(The new image has npm's `unsafe-perm` set to true, which should fix some globbing issues).
=> meta: update janeway to v0.15.3.1

pkg/interface/src/views/apps/settings/components/lib/LeapSettings.tsx
This matches the phrasing used in the omnibox and on the tile.
=> settings: my channel -> my channels

pkg/arvo/lib/bip/b158.hoon
change `swp` to `flim:sha` in +to-range of the bip158 lib to ensure leading 0's are preserved
=> bip158: change swp to rev in +to-range

pkg/npm/api/graph/lib.ts
`getNode` added a duplicate slash before the index, resulting in bad scry
paths. This removes that slash.
=> landscape: remove duplicate slash in scry path

pkg/arvo/app/file-server.hoon
Need the iphone app to get its own identity in a way that doesn't rely on the domain name.
I don't know if this is the best place to put this, but I don't know any better place. I figure since this is the place where`window.ship` is defined its somewhat related.
=> file-server: scry for identity

pkg/arvo/app/btc-provider.hoon, pkg/arvo/app/btc-wallet.hoon
We currently ping once every 30 seconds *and* every time a peer connects. This can lead to the provider hanging, particularly in cases when someone reconnects repeatedly. The solution is to ping only on our schedule of once every 30 seconds.
=> btc-provider: ping _only_ once every 30 seconds

pkg/arvo/app/file-server.hoon
Per the conversation in the landscape meeting, it makes more sense to do this https://github.com/urbit/urbit/pull/5056 in a way that doesn't require authentication. Now ships expose a `/who` path that returns their ship name.
=> file-server: restore who generator binding

pkg/arvo/app/btc-wallet.hoon, pkg/arvo/app/file-server.hoon
Addresses this issue: https://github.com/urbit/bitcoin-wallet/issues/25
This isn't really a sufficient solution though, fading the app should really just cause launch and file-server to remove the related stuff. Seems like if we're going to have fade, we also need an `on-fade` arm.
=> btc-wallet: check if tile and file server are already initialized

pkg/arvo/app/btc-wallet.hoon, pkg/arvo/lib/bitcoin-json.hoon, pkg/arvo/sur/btc-wallet.hoon
@ixv added the `%scan-progress` update type. It is sent in `+init-batches` and `+check-scan`.
`main` and `change` are the 2 sub-wallets. `~` means fully scanned; an `idx` value is the lowest index of the current scanning batch.
=> scan-progress added

pkg/arvo/ted/graph/leave.hoon
- Don't wait for an ack for pokes to `graph-pull-hook` and `graph-store`
- Return early, instead of crashing, if groups or metadata are missing
Fixes urbit/landscape#921
=> -graph-leave: don't crash on inconsistent state

pkg/arvo/lib/bitcoin.hoon
Fixed `to-cord:adr` in `bitcoin.hoon`: it was printing old-style addresses with their Urbit `0c` prefix for the `@uc` aura.
=> fixed address bug for legacy addresses

pkg/arvo/app/btc-provider.hoon, pkg/arvo/sur/btc-provider.hoon
Pinging the server every 30 seconds spikes the CPU too frequently for most providers. I made it ping every 60 seconds instead as that seems to be less load. I also made the interval for ping frequency configurable so that people can play with it based on their own machine's performance characteristics.
=> btc-provider: made interval ~m1, and allow provider to set interval

pkg/interface/src/logic/state/hark.ts, pkg/interface/src/logic/state/local.tsx, pkg/interface/src/views/App.js, pkg/interface/src/views/apps/chat/ChatResource.tsx, pkg/interface/src/views/apps/chat/DmResource.tsx, pkg/interface/src/views/apps/links/components/LinkBlockInput.tsx, pkg/interface/src/views/apps/links/components/LinkBlocks.tsx, pkg/interface/src/views/components/StatelessUrlInput.tsx, pkg/interface/src/views/components/VirtualScroller.tsx, pkg/interface/src/views/landscape/css/custom.css
interface: revive optimistic unread updating
Fixes urbit/landscape#1030
collections: style pass on smaller screen sizes
interface: add all breakpoints to state
VirtualScroller: fix scrollbar on safari
Moves to mousemove instead of pointermove events as a result of this
bug[1]. Adds a CSS rule to optionally globally disable selection of text,
to prevent this from occurring during scroll on safari, as
preventDefault() does nothing.
[1]: https://bugs.webkit.org/show_bug.cgi?id=220194
=> interface: fixes blocking release

pkg/arvo/app/file-server.hoon
If the %cu scries return false, then we fallback to requesting the
index.html from the mount point.
Fixes urbit/landscape#837
=> file-server: improve SPA 404 behaviour

pkg/arvo/app/group-view.hoon, pkg/interface/.storybook/preview.js, pkg/interface/src/stories/Invite.stories.tsx, pkg/interface/src/views/components/Invite/Group.tsx, pkg/interface/src/views/components/Invite/index.tsx
Reworks part of the invite flow to be clearer, and also to prevent brokeness
- Errored invites now have to be dismissed manually, to ensure that the user is actually notified of the join failure.
- Invites reflow better on mobile screensizes
- Fixes invites dismissal failure https://github.com/urbit/landscape/issues/949
=> Invites: fix dismissal, style pass

.github/actions/glob/Dockerfile
Bumps the janeway version to v0.15.4 and changes the image source to that kept in the 'tloncorp' repo instead.
Related: #5073.
cc @liam-fitzgerald
=> meta: bump janeway version, change repo

pkg/urbit/daemon/main.c
The original impetus for this was creating the `%khan` socket: Unix domain
socket paths are limited to 108 characters since they have to fit into a
`struct sockaddr`; we want the `%khan` socket to be relative to the pier;
hence it's most expedient if the socket is itself a relative path of
known length, and is created with cwd located at the pier directory.
There has also been talk about having the binary chroot itself to the
pier directory for ~security reasons. The code to do so existed, but was
`ifdef`'d out (and would require further work, e.g. patching in
`/dev/urandom`.)
This patch merely calls `chdir` in `main` and sets `u3_Host.dir_c` to `"."`. It
seems to work; however, `u3_Host.dir_c` (and `u3_Local`) is now largely
redundant, and is used in a lot of places to construct paths …
=> vere: have king chdir to pier directory on boot

pkg/arvo/app/metadata-store.hoon, pkg/arvo/ted/group/create.hoon
The `.hidden` flag was being incorrectly set upon new group creation, so any groups created since it's introduction would not show up in the omnibox.
Fixes urbit/landscape#1017
=> metadata-store: do not hide groups on creation, unhide all current groups

pkg/btc-wallet/src/js/components/lib/walletModal.js, pkg/btc-wallet/src/js/hooks/useSettings.js, pkg/btc-wallet/src/js/lib/util.js
Fixes https://github.com/urbit/bitcoin-wallet/issues/40.
Right now just mapping "USD" to "$" since the app can only toggle between USD and BTC, but we can add other currency symbols to the switch later.
Also fixed an issue I found with destructuring a param in checkTicket (event was always undefined).
=> btc-wallet: Show dollar sign instead of usd

pkg/urbit/daemon/main.c
This reverts commit efd123bfc7ef017d99ddade80040e20eb9de2e0a, reversing
changes made to f0e11a84562c84f290590b69cb1d970bec348f48.
This reverts #5086, which should have been applied to release/next-vere,
not release/next-sys.
=> Revert "Merge pull request #5086 from urbit/jo/chdir"

pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostContent.tsx
Addresses concerns from comments in urbit/landscape#887 by giving indication when truncation is happening and also truncating anything above 300px tall.
=> PostContent: height detect and fade for truncation

pkg/arvo/app/group-view.hoon, pkg/arvo/app/hark-group-hook.hoon, pkg/arvo/app/metadata-pull-hook.hoon, pkg/arvo/app/metadata-push-hook.hoon, pkg/arvo/app/metadata-store.hoon, pkg/arvo/lib/metadata-store.hoon, pkg/arvo/lib/metadata.hoon, pkg/arvo/mar/metadata/update-1.hoon, pkg/arvo/mar/metadata/update-2.hoon, pkg/arvo/sur/metadata-store.hoon, pkg/arvo/ted/graph/create-group-feed.hoon, pkg/arvo/ted/graph/create.hoon, pkg/arvo/ted/graph/delete.hoon, pkg/arvo/ted/graph/disable-group-feed.hoon, pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/ChannelPermissions.tsx, pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/Details.tsx, pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/index.tsx, pkg/interface/src/views/landscape/components/GroupSettings/Admin.tsx, pkg/interface/src/views/landscape/components/GroupSettings/Channels.tsx, pkg/interface/src/views/landscape/components/GroupSettings/GroupFeed.tsx, pkg/npm/api/metadata/lib.ts, pkg/npm/api/metadata/types.ts
- Refactors layout of metadata-store to remove TODOs about reorganisation
- Adds an `%edit` action to allow more granular updating of metadata
I strongly dislike the fact that this is a breaking change to metadata-store, but I don't see any way around in lieu of scries inside mark definitions.  
Requesting @ixv and @Fang- review because L is away
=> metadata-store: refactor, add %edit

pkg/interface/src/logic/reducers/group-update.ts
Fixes urbit/landscape#1044 by preventing a crash in the reducer that would kill the subscription. FWIW, i strongly dislike that we receive the cards backwards on the channel (which is the cause of this bug), i'd be interested in ways to make this more usable. Wondering whether we should catch exceptions from callbacks in @urbit/http-api ?
=> interface: prevent crash in reducers on new group DMs

pkg/arvo/app/lens.hoon
Necessary to revive ropsten testnet for now. It's not critical that we import contacts, as none of it has changed. The contact import logic needs a total rewrite anyway, given that it dates back to pre-contact unification.
=> lens: remove contact importing

pkg/arvo/lib/graph-store.hoon
Patches importing so that the ropsten testnet will work successfully. Does not restore the previous behaviour, which was to check that the graph existed and we had permissions, backing off exponentially and on success would begin to sync the graph. Such behaviour is not really useful for the ropsten usecase, and was designed for network-wide breaches. As we can coordinate ships coming off and online on the testnet, these timing problems are a nonissue.
=> graph-store: patch importing

pkg/interface/src/logic/lib/util.tsx, pkg/interface/src/logic/state/graph.ts, pkg/interface/src/logic/state/hark.ts, pkg/interface/src/logic/state/settings.ts, pkg/interface/src/stories/ColorInput.stories.tsx, pkg/interface/src/views/apps/settings/components/lib/CalmPref.tsx, pkg/interface/src/views/apps/settings/components/lib/DisplayForm.tsx, pkg/interface/src/views/apps/settings/components/lib/DmSettings.tsx, pkg/interface/src/views/apps/settings/components/lib/GroupChannelPicker.tsx, pkg/interface/src/views/apps/settings/components/lib/NotificationPref.tsx, pkg/interface/src/views/components/ColorInput.tsx, pkg/interface/src/views/components/FormikOnBlur.tsx, pkg/interface/src/views/components/ImageInput.tsx
- Fixes ColorInput text entry case
- Makes DM settings optimistic, removes submission button
- Changes ImageInput to not set the form error on upload failure, instead setting its own error variable
- Fixes CalmEngine pulling incorrect prop from form
- Unifies optimistic state handling for forms
The one true way ™ to do optimistic form inputs now is to do the following
- Ensure that you're hooking into optimistic state updates inside the onSubmit, and select the initialValues directly from state (i.e. the selector that you pass the hook should return initialValues directly
- use formikOnBlur
- done!
=> interface: form handling, optimism sweep

pkg/btc-wallet/src/js/components/lib/balance.js, pkg/btc-wallet/src/js/lib/util.js
Fixes: https://github.com/urbit/bitcoin-wallet/issues/36
We can't use `navigator.clipboard` from a non-secure context (i.e., must use localhost or https). Now using a function to determine if we're in a secure context and then using a workaround to make copying to the clipboard work if not.
=> btc-wallet: Fix copy from non-secure context issue

pkg/interface/src/views/landscape/components/Home/Post/PostItem/PostContent.tsx
Refactors post content height detection to use resize observer so we always get correct truncation and adds small margin when doing so.
=> PostContent: ensure group feed spacing correct

pkg/arvo/app/hood.hoon, pkg/arvo/app/metadata-store.hoon, pkg/arvo/app/notify.hoon, pkg/arvo/lib/agentio.hoon, pkg/arvo/lib/hood/drum.hoon, pkg/arvo/mar/notify/client-action.hoon, pkg/arvo/mar/notify/provider-action.hoon, pkg/arvo/mar/notify/update.hoon, pkg/arvo/sur/notify.hoon
We use a single app as both provider and client for push notifications. The provider can add or remove a service, and a client can connect or disconnect to a provider.
When a client connects to a provider, the provider sets up a binding for them, and then subscribes to the client. The client has a subscription to their own hark-store, which they filter for dms, turn into `notify` specific notifications, and forward to the provider. The provider then sends the push notification.
This is written in a somewhat general way, the idea being that many providers could provider many services, but we're somewhat constrained in specificity to dms for and the specific twilio api we're targeting, for the time being. It can be made more general in the future.
=> notify: push notifications for mobile app

pkg/arvo/sys/vane/dill.hoon
Otherwise, if you accidentally give on the system duct, you crash the
event, as in #5138
=> dill: no-op on strange fact

pkg/urbit/jets/c/rep.c, pkg/urbit/jets/c/rip.c
The jets for `+rip` and `+rep` are embarrassingly partial; see #4049 and #1210 for context. This PR updates them to defer to nock, rather than bail non-deterministically in unimplemented cases. Finishing their implementations remains a priority.
/cc @ohAitch
=> jets: updates +rip and +rep stub jets to defer to nock

pkg/arvo/gen/hood/crunch.hoon, pkg/arvo/lib/crunch.hoon, pkg/arvo/mar/csv.hoon, pkg/arvo/sur/crunch.hoon
The crunch library and generator are tools to export group graph data to a CSV-format file.
The purpose of crunch is to help quantify the growth of the Urbit network.
The code added here is work done under the grant [https://urbit.org/grants/bounties/analytics-script/](https://urbit.org/grants/bounties/analytics-script/)
Development of this code occurred at [https://github.com/hosted-fornet/crunch](https://github.com/hosted-fornet/crunch) where you can find a README that should make it easy to use this code.
FYI @timlucmiptev @jalehman
=> Add crunch library and generator

pkg/arvo/lib/azimuth.hoon
The static Ecliptic address in /lib/azimuth hadn't been updated to reflect the recent upgrade yet.
=> azimuth: update for latest ecliptic address

pkg/interface/src/views/components/RemoteContent/index.tsx
This prevents URLs ending in 'mov', 'ogg', etc. from rendering as empty video/audio, allowing people to learn about Isaac Asimov and William Rees-Mogg. Tested locally, seems to work.
Guessing @urcades is a reasonable maintainer to tag?
=> landscape: altered RemoteContent regexes for images, video, and audio to include period literal.

pkg/arvo/app/notify.hoon
Stops some noisy errors from printing, doesn't change any behavior beyond that
=> notify: cleanup %watch-not-unique cases

pkg/arvo/app/metadata-store.hoon, pkg/interface/src/logic/reducers/metadata-update.ts, pkg/interface/src/logic/state/metadata.ts, pkg/interface/src/views/landscape/components/GroupifyForm.tsx, pkg/interface/src/views/landscape/components/Resource.tsx, pkg/interface/src/views/landscape/components/ResourceSkeleton.tsx, pkg/interface/src/views/landscape/components/Sidebar/SidebarItem.tsx, pkg/npm/api/metadata/lib.ts, pkg/npm/api/metadata/types.ts
Previously, if an %initial-group fact had less associations than the agent did, we ignored those missing facts. This causes channels to not remove their metadata correctly. Addresses this issue both in %metadata-store and also in the associated reducer
=> metadata-store: Handle removes on kick correctly

default.nix, pkg/base-dev/lib/docket.hoon, pkg/base-dev/lib/strandio.hoon, pkg/base-dev/sur/docket.hoon, pkg/garden/app/docket.hoon, pkg/garden/desk.docket, pkg/garden/ted/glob.hoon
Kind of a pain to test, need a better way to insert a `charge` directly.
Either that or rework `chad`, since it will cause the currently stored glob to be deleted when the desk.docket file is updated.
Open to some suggestions here.
=> docket: download globs over ames

pkg/arvo/app/hood.hoon, pkg/arvo/lib/hood/kiln.hoon, pkg/arvo/mar/kiln/bump.hoon, pkg/base-dev/sur/hood.hoon, pkg/grid/src/nav/notifications/SystemNotification.tsx, pkg/npm/api/hood/lib.ts
When we receive the %mere gift from clay, the kernel has not yet been
reloaded. This means any attempts to bump desks will fail, as they will
be bumped against the old kernel. Rectifies this by continuing the %base
desk update flow in +on-load, instead of +take-merge-main. Also adds a
wef=(unit weft) to the state in order to discriminate whether or not the
kernel has just been reloaded
Also allows bumps to be triggered from the UI
=> dist: fix update ordering in kiln, wire to UI

pkg/urbit/include/c/portable.h
Building on the apple silicon `m1brew` build changes in #4675 and related discussion in https://github.com/urbit/urbit/issues/4257#issuecomment-891802105, this PR changes the loombase for all darwin builds, making our darwin static binaries run correctly under rosetta.
/cc @locpyl-tidnyd 
Closes #4257
=> u3: refactors address layout macros, combines darwin/aarch64

pkg/btc-wallet/src/components/Send/BridgeInvoice.tsx, pkg/btc-wallet/src/components/Send/ExternalInvoice.tsx, pkg/btc-wallet/src/components/Send/Invoice.tsx
Fix for: https://github.com/urbit/bitcoin-wallet/issues/42
Also fixes another issue I noticed while working on this: after sending a successful TX we were just sitting on the invoice screen rather than going back to the balance.
cc @timlucmiptev @ixv
=> btc-wallet: Fix issues with bridge and external invoices

pkg/btc-wallet/src/App.tsx, pkg/btc-wallet/src/components/Body.tsx, pkg/btc-wallet/src/components/Header.tsx, pkg/btc-wallet/src/components/Settings.tsx
Fixes: https://github.com/urbit/bitcoin-wallet/issues/43
Adds a home button (moves the header up to where it is in the new designs, too). Adds an "X" icon to close out of settings.
cc: @timlucmiptev @jalehman
=> btc-wallet: Add home button

bin/solid.pill, pkg/arvo/lib/hood/kiln.hoon, pkg/arvo/sys/vane/gall.hoon, pkg/base-dev/sur/hood.hoon
A two-parter, designed to cleanup the flow of removing an agent from a desk
notes:
- |commiting straight into an installed desk still breaks.
- L583 returned `mo-cor` instead of `cor`. My understanding is that this will throw away all the previously executed iterations of the `roll`, but continue the iteration regardless. I believe this constitutes a bug and so changed it to return `cor`
kiln: kill agents before merge
If a remote commit is downloaded that simultaneously removes an agent from
desk.bill but also removes the associated source files, then the commit
will fail as gall will not have received the card to kill the agent yet.
Instead, we read our foreign copy of the bill in +take-download, and
kill any necessary agents there, preventing a reload of the deleted
agent from …
=> kiln, gall: Fix removing agents from desk

pkg/urbit/compat/mingw/ptty.c, pkg/urbit/compat/mingw/uv.patch, pkg/urbit/compat/poor-mans-nix-shell.sh, pkg/urbit/compat/posix/ptty.c, pkg/urbit/include/vere/vere.h, pkg/urbit/vere/io/term.c
This PR fixes a crash on windows (under `-t`) by applying libuv/libuv#3302 (allowing null writes to `uv_pipe_t`). Additionally, it suppresses (most) null writes in `term.c`, and includes a little refactoring.
/cc @locpyl-tidnyd
=> vere: windows fixes, refactoring for new terminal

pkg/urbit/jets/c/rap.c, pkg/urbit/jets/c/rep.c
This PR fixes a couple jet mismatches in bloq-size invariant handling.
=> u3: replaces spurious bloq-size bail:exit's in +rap and +rep jets

pkg/urbit/include/ur/hashcons.h, pkg/urbit/ur/hashcons.c
the hashcons used for cueing input events grows large on initial boot due to the need to store the entire pill. This exposed the slowness of iterating over all buckets in the hashcons to reset fill counts to 0 and wipe (~ 5*10^6 buckets on a run which loads solid.pill).
By factoring out the `fill` field of the `pail` types into a `fills` array field parallel with the `buckets` array in the `dict` types, we can use `memset` to 0 all of the pail fill fields.
NB it is semantically valid to simply memset the `buckets` array but the need to 0 all of the ref and val entries outweights any performance gain from using `memset` in this case, per my benchmarking.
=> vere: use memset to wipe hashmaps

pkg/urbit/worker/serf.c
I had broken event labels in `-j` trace output in a previous refactoring.
=> serf: fix incorrect conditional (integer precision) in event tracing

pkg/base-dev/sur/hood.hoon
This feels inconsequential, but there are a surprising number of edge cases that require this,  for example, 
- scrying in `+on-init`
- Moving an agent from one desk to another where the moved agent is also poked by an agent on the freshly started desk. 
In general, it feels nice that we control the order of the agents starting
=> hood: respect ordering of agents in bill

pkg/grid/src/components/Setting.tsx, pkg/grid/src/nav/notifications/OnboardingNotification.tsx, pkg/grid/src/nav/preferences/InterfacePrefs.tsx, pkg/grid/src/nav/preferences/SystemUpdatePrefs.tsx, pkg/interface/config/webpack.dev.js, pkg/interface/src/logic/state/launch.ts, pkg/interface/src/register-sw.js, pkg/interface/src/views/App.js, pkg/interface/src/views/apps/launch/App.tsx, pkg/interface/src/views/apps/launch/components/tiles.tsx, pkg/interface/src/views/apps/notifications/inbox.tsx, pkg/interface/src/views/apps/permalinks/embed.tsx
-   X terminal tile still needs to be removed from groups/landscape    
-   X embedded app links need better sizing for mobile  
-   X handle urbit links toggle should be disabled if no HTTPS
-   X service worker path and scope is wrong for groups/landscape 
-   X groups/landscape hash needs to be removed  
-   X enable otas broken, because arak type changed
-   X pre-prompt for handling urbit links
-   decided on onboarding notification
-   handle the case when no protocol handler
todo:
-   rename to groups
-   add new favicon with full set of links, possibly use vite plugin
=> interface: dist fixes

pkg/arvo/mar/kiln/vats-diff.hoon, pkg/base-dev/mar/ship.hoon, pkg/garden/app/treaty.hoon, pkg/garden/mar/ship.hoon, pkg/grid/src/app.tsx, pkg/grid/src/nav/search/Home.tsx, pkg/grid/src/state/docket.ts, pkg/npm/api/docket/lib.ts
- Our handling of 'allies' (treaty's term for a provider that allows app discovery), was inconsistent and incomplete. We previously used the ship sponsor, however this presents usability issues if the user's sponsor is offline, or doesn't maintain a useful list of apps. Additionally, we previously prompted to view ~zod's desks in the UI, if we didn't have any other allies to look at, which was inconsistent, because it should prompt for the sponsor, as they're the only ship that's guaranteed to be allied.
- No longer defaults to the sponsor, instead using a hardcoded ship name.
- Adjusts frontend to respect this hardcoded ship name
cc: @urcades
=> treaty: default to hardcoded ship instead of sponsor

pkg/arvo/app/dojo.hoon
Syntax is `+desk#gen`. The `#` is just a placeholder (as is tradition), and I'd be happy to take suggestions/votes on the real thing. I was thinking `+desk>gen` maybe?
`:app|gen` de-sugars to `:app +desk#gen`, where the desk is the desk the app is running on.
`:app|desk#gen` is currently broken, in the sense that the above de-sugaring takes precedence, overwriting the manually specified desk with the desk where the app is running.
The `+on-load` here just aborts any running user action to avoid having a monstrously large state adapter.
=> dojo: support running other-desk generators

pkg/urcrypt/Makefile.am, pkg/urcrypt/configure.ac
fixes urcrypt's automake/autoconf files so that libargon2 will compile on architectures without SSE instructions, but x86_64 will still use the optimizations
=> urcrypt: argon2 only optimize for x86_64 on x86_64

pkg/arvo/lib/hood/kiln.hoon, pkg/garden-dev/sur/docket.hoon, pkg/garden/app/docket.hoon
I noticed docket wasn't getting notified when I ran `|install our %something`. Turns out kiln just wasn't sending the `%commit` diffs that docket relied on in the local case.
Patched kiln to send a `%commit` during local install. Not entirely sure if this is the semantically correct change, please lmk.
Once kiln was sending the notifications, docket was crashing when trying to add the new docket to state, so patched that as well.
=> kiln, docket: fix local installation

pkg/arvo/sys/vane/clay.hoon
Fixes https://github.com/urbit/landscape/issues/1207
=> clay: print stacktrace on build failure

pkg/arvo/gen/kick.hoon, pkg/landscape/app/graph-pull-hook.hoon, pkg/landscape/app/graph-store.hoon, pkg/landscape/lib/pull-hook.hoon
- The pull hook renegotiation poke may have crashed during the software distribution OTA. This PR fixes this by rerunning the poke.
- Additionally adds a flag to the kick poke to specify the aggressiveness of renegotiations.
=> graph-pull-hook: restore network connectivity

pkg/urbit/noun/retrieve.c
Large nearly-identical nouns were reported as equal due to a bug
introduced in e389220d1889e80a20c5cb2e8f9bd5cf279629c9.  This fixes that.
The bug was noticed when small changes were made to files and they
didn't register as changes to clay's %a subscribers.
Fixes #5285
=> u3: fix big noun equality

pkg/base-dev/sur/hood.hoon
`+vats` / `+trouble` are generators that simply print the output of the `+report-vats` arm of sur/hood/hoon.
@philipcmonk asked for the kids hash to be printed as well.
=> hood: report %kids desk hash in +report-vats

pkg/interface/src/logic/lib/util.tsx
Prevents `metadata is undefined` crashes upon joining a group. I suspect zombie children issues are underlying, but fixing that is a bit of a minefield.
=> interface: Handle undefined association in getFeedPath

pkg/arvo/app/hood.hoon, pkg/arvo/lib/hood/drum.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/dill.hoon, pkg/arvo/sys/vane/eyre.hoon, pkg/arvo/sys/vane/gall.hoon, pkg/arvo/sys/vane/jael.hoon, pkg/arvo/tests/sys/vane/gall.hoon
(draft because this is the product of a single long pair programming session with @belisarius222, and this needs to be evaluated next week with a clear mind.  It seems to work fine, though)
Start with `|start %desk %app-name`.  `|start %app` still defaults to `%home`.
Everywhere in the kernel that we deal with marks, we infer the app it's
connected to and use the marks from that desk.
Also some light renaming in gall, especially path->wire and
current-agent->yoke.
Subsequent tasks:
- Dojo needs a syntax to run generators and threads from other desks
- The home desk should be split into at least a minimal base desk and
big "userspace" desk.  Dill's initialization logic should be updated
to handle
- |show-package, |install, and |uninstall should to be written
- Clay should have smarter …
=> gall: allow apps to run from any desk

pkg/arvo/app/dojo.hoon
Similar to the recently added syntax for generators, you can now `-desk!thread` to run the thread from the specified desk.
=> dojo: support running threads from other desks

pkg/urbit/noun/events.c
And discard invalid checkpoint patches on restart. (That was needlessly treated as a fatal error, dropping the patch just means a short event log replay.)
=> vere: abort on checkpoint sync errors

pkg/grid/src/tiles/RemoveApp.tsx, pkg/grid/src/tiles/SuspendApp.tsx, pkg/grid/src/tiles/TileMenu.tsx
Changes up some copy in the app tile menus and the resulting pop ups for app removal and app suspension.
Addresses isssues https://github.com/urbit/landscape/issues/1237 and https://github.com/urbit/landscape/issues/1235
=> copyedits: apptile menu, remove/suspend interfaces

pkg/interface/src/views/apps/publish/components/Note.tsx, pkg/landscape/app/hark-graph-hook.hoon
- Correctly get ID from index, was incorrectly fetching version numbers from notes instead of the note ID
- Works around malformed unreads by dismissing them
=> hark-graph-hook: correctly get rear of index

pkg/interface/src/logic/state/hark.ts, pkg/interface/src/views/apps/publish/components/Notebook.tsx, pkg/interface/src/views/landscape/components/GroupsPane.tsx
Fixes the missing %read-graph and %read-group actions by reimplementing them in the interface.
=> interface: fix read-graph, readGroup actions

pkg/interface/src/logic/lib/useResize.ts
Interior mutability bites again. This was causing a memory leak, as the reference to the element was never let go
=> useResize: fix destructor

pkg/arvo/app/azimuth.hoon, pkg/arvo/sys/vane/jael.hoon
Jael needs to be reconfigured to listen to the new aagent for azimuth
events, and the old app needs to be shut down. We do this in
/app/azimuth's +on-init.
Additionally, we make sure that jael doesn't crash when it (as expected)
loses its subscription to the old agent.
Only tested on a fakenet ship so far, which might not hit the full/relevant case here.
=> jael, azimuth: reconfigure for L2

pkg/arvo/app/acme.hoon
Small patch for the ancient workaround.
Arguably this should be `q.byk.bowl` instead, but then if this ever goes onto a non-base desk, you risk pushing the cert out to all who installed from the desk.
=> acme: load custom cert from base desk, not home

pkg/arvo/gen/hood/label.hoon, pkg/arvo/lib/hood/kiln.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/clay.hoon
This PR finishes off the implementation for using labels in the clay filesystem. Labels are `@tas` which you can use in place of dates or revision numbers.
<details>
<summary>Examples to try</summary>
Make a change to `<ship>/base/gen/hood/label.hoon` after mounting, then run the following
```hoon
|label %base %v2
|label %base %origin, =aeon 1
.^(@t %cx /=base/v2/gen/hood/label/hoon)
.^(@t %cx /=base/origin/gen/hood/label/hoon)
```
</details>
Many thanks to @philipcmonk who worked through this with me.
=> clay: support labels

pkg/arvo/app/azimuth.hoon
Also kick the call to +mule out of the loop.  By uncommenting the
diagnostics in u3m_fall, I measured that running through the 290k events
the azimuth snapshot required this much memory:
Head recursive, +mule in:  1.1GB
Head recursive, +mule out: 780MB
Tail recursive, +mule in:  700MB
Tail recursive, +mule out: 70MB
So this commit chooses the last one.  The most delicate part is making
sure the effects are the right order; this uses the usual idiom.
Kicking +mule out of the loop is okay because lib/naive should never
fail, and if it does then azimuth shouldn't advance until an out-of-band
solution is decided.
Addresses #5431
=> azimuth: make +run-logs tail-recursive

pkg/urbit/daemon/main.c
Tested by building vere and trying it with `-B`, `-p`, and `-F`.
=> vere: alphabetize getopt short options

pkg/arvo/sys/zuse.hoon
de-xml parser fails when xml content node contains doublequotes (`doq` rule), this PR proposes to remove this restriction as high-level javascript APIs that operate on DOM don't entitize/encode doublequotes by default.
=> improve de-xml parser

pkg/interface/src/logic/lib/tokenizeMessage.js
There's a bug in the publish url preprocessing where if the link text is a url (like this `[http://example.com](http://example.com)`)
it will treat it like the graph `%url` content type instead of letting markdown handle it. The fix is just to detect that case in the same fashion that we detect urls in parens
Let me know if master is the wrong branch to target here, I'm out of the loop on the release process.
=> interface: fix publish url preprocessing

pkg/landscape/app/invite-hook.hoon
Fixes a bug that prevented moons from being invited
=> invite-hook: use equality instead of team:title

pkg/arvo/mar/atom.hoon, pkg/base-dev/mar/atom.hoon
Found out the hard way that the `%atom` mark was actually not included in base-dev. Proposing here that it should be in there, considering it's not too uncommon to produce data with that mark.
=> pkg: include atom mark in base-dev

pkg/landscape/gen/graph-store/export-graph.hoon
This was crashing before due to a `[%no-cast-from %graph-update-3 %graph-update]`. With this change it produces output.
=> landscape: correct mark

pkg/interface/src/logic/lib/notificationRedirects.ts, pkg/interface/src/logic/reducers/invite-update.ts, pkg/interface/src/logic/state/invite.ts, pkg/interface/src/views/apps/permalinks/embed.tsx, pkg/interface/src/views/landscape/components/Content.tsx, pkg/interface/src/views/landscape/components/GroupSummary.tsx, pkg/interface/src/views/landscape/components/Join/Join.tsx, pkg/interface/src/views/landscape/components/Join/Skeleton.tsx
- Fixes graph redirects of unjoined groups
- Stops the group summary from reflowing the modal when loaded
- Adds invite declination
- Fixes clicking on an invite notification
- Fixes group navigation
=> interface: minor group join fixes

pkg/arvo/app/claz.hoon, pkg/arvo/lib/claz.hoon, pkg/arvo/sur/claz.hoon
I keep making these changes locally, so probably good to just commit them instead. 0a5bcf7 is pretty ugly, but gets the job done. We're not doing spawn-based lockups anymore anyway.
Arguably this should go into its own `pkg/` folder too, but the easier access is nice for now.
=> claz: better linear lockup ops support

.gitattributes
This is a simple change which forces all hoon files to be checked in and checked out using LF newlines, regardless of the user's `core.autocrlf` setting. Without this, developers on Windows can inadvertently try to create a fakezod with illegal line endings, all while receiving unrelated error messages.
=> meta: enforce LF line endings for hoon files

pkg/arvo/app/dojo.hoon
Since ford fusion, `:dojo` crashes on failed mark conversion or bunting a non-existent mark. Such crashes unlink dojo from drum, which discards the session and its history. This PR appropriately protects and virtualizes those operations.
Also, has dojo's mark conversion always been a mold invocation? That seems unnecessarily expensive -- it'd be nice to just cast if the value already nests.
=> dojo: improve safety of mark conversion

pkg/urbit/include/noun/allocate.h
Add comments to the following commonly-used macros in `allocate.h`:
- `u3a_is_cat`
- `u3a_is_dog`
- `u3a_is_pug`
- `u3a_is_pom`
- `u3a_to_off`
- `u3a_to_ptr`
- `u3a_to_wtr`
- `u3a_to_pug`
- `u3a_to_pom`
- `u3a_is_atom`
- `u3a_is_cell`
- `u3a_h`
- `u3a_t`
- `u3a_into`
- `u3a_outa`
- `u3a_is_north`
- `u3a_is_south`
=> u3: comment u3a_* macros

pkg/urbit/vere/io/behn.c
@joemfb and I (really just Joe) noticed this bug in the Behn io driver when he was walking me through how IO drivers work. it wasn't checking that the tag on the kick was c3__doze, and now it does.
Yay! first PR!
=> Adding tag == c3_doze check to _behn_io_kick in Behn io driver

pkg/urbit/noun/nock.c
This PR fixes a miscompilation of dynamic hints in the bytecode interpreter. Calls (nock 9) in hinted formulas in tail position were being compiled into tail calls, but hinted formulas (in the dynamic hint protocol) are never in tail position, as there is a post-evaluation callback.
This bug caused a crash, which was first observed in #5477. Dynamic hints were added in #3979, and first used in #5261.
/cc @frodwith
=> u3: fix compilation of dynamic hints in tail position

pkg/arvo/sys/arvo.hoon
This PR is not urgent -- the changes have just been sitting in my git stash for awhile.
- adds detail to hoon/arvo/lull/zuse entries; this was helpful in tracking down the reset space leak
- makes vane participation optional (`/whey` namespace)
- groups vane entries and metadata (default, type, and compiler-cache)
- fixes a type typo
=> arvo: refactor |mass output

pkg/urbit/vere/io/fore.c
Event injection validation was never updated to support routing on a
full vane name. Upgrades the check, so that wires with a first element
longer than 4 characters fail validation, instead of the previous limit
of 1 character
=> vere: update event injection for four letter vanes

bin/multi-brass.pill, pkg/garden/lib/hark-store.hoon, pkg/landscape/mar/hark-note.hoon
Boot was broken, fixing the hark-note file mark and re-adding the
hark-store library fixed it.
This lets us push a new pill, which is necessary for the fix in #5434 to
actually work.
Fixes #5501
Fixes #5502
cc @liam-fitzgerald for sanity check, though I've already pushed a pill
=> landscape,garden: make build

CONTRIBUTING.md
This fixes some links and updates the git policy to reflect the use of
`next/` branches.
=> readme: update CONTRIBUTING.md

MAINTAINERS.md
- rename release/next-foo to next/foo
- specify standard branch names for releasing changes to each desk
- remove na-release/ -- it has seen little use and existed for an era
when we breached frequently
Any other changes we should make here?  Perhaps we should specify more about how releases are announced?
=> meta: update branch conventions

pkg/arvo/lib/hood/helm.hoon
Addresses #5516
The old |rekey expected a `seed:jael`, this rewrites |rekey to work with
`feed:jael` which has `seed:jael` as a case so it is backwards
compatible with old keyfiles.
I suspect there is room for improvement here:
https://github.com/urbit/urbit/pull/5522/commits/3651f6a7c653f6e72767a2a0f14a0759b6e6d931#diff-dcb56b92e2927b7d8184f5dd10c0bab7b18e7340bbdec1ffb5c4800d11075936R60-R66
namely the use of identical `?.` statements twice in a row. We can't look at `who.fed` until after the `?@` so that the compiler knows what its looking at, so it seems like we need this but I could be overlooking something about `$^` molds (which `feed:jael` is) that makes it so this can be a bit cleaner. The only idea I've had so far is to factor the `?.` statements into its own arm under a `|^`, but …
=> helm: update |rekey to work with multikey files

pkg/landscape/app/metadata-pull-hook.hoon, pkg/landscape/app/metadata-push-hook.hoon, pkg/landscape/lib/pull-hook.hoon, pkg/landscape/lib/push-hook.hoon, pkg/landscape/ted/group/leave.hoon
Aggressively refactors the permissioning flow for groups, so as to make more reliable
On leaving a group:
- Leaving a group is triggered through the `-group-leave` thread
- This pokes group-push-hook, to remove ourselves from the groups, group-store to remove our copy of the group, and group-pull-hook, to cancel syncing of group
- When hosts hear of a %remove-members fact in the metadata-push-hook, it revokes the ships included in that fact. This should trigger the usual nacking and cleanup flow, which has been thoroughly tested.
=> groups: fix permission handling

pkg/arvo/app/azimuth.hoon, pkg/arvo/app/roller-rpc.hoon, pkg/arvo/app/roller.hoon, pkg/arvo/gen/roller/assign.hoon, pkg/arvo/lib/azimuth-roll-rpc.hoon, pkg/arvo/lib/dice.hoon, pkg/arvo/sur/dice.hoon, pkg/arvo/ted/roller/send.hoon
Adds suport for [roller-api](https://github.com/urbit/urbit/tree/roller/typescript-client/pkg/npm/roller-api) client [0.1.14](https://github.com/urbit/urbit/commit/347593316f8868e24a4286adabdd59421da96f81) and [0.1.13](https://github.com/urbit/urbit/commit/816afe3fa44d353148fe8e477ecd0c6d65127a5e):
- `%spawns-remaining`
- `%get-remaining-quota`
- `%when-next-slice`
- `%get-allowance`
Also refactoring and cleanup of `/lib/dice.hoon` and `/app/roller.hoon` to support a future, WIP [`/app/roller-cli.hoon`](https://github.com/urbit/urbit/pull/5459)
=> roller: update roller and roller-rpc with quota related methods

pkg/arvo/sys/vane/ames.hoon
This adds a fix that crashed the [latest OTA](https://github.com/urbit/urbit/releases/tag/urbit-os-v2.119) due to a [`%freaky-alien`](https://github.com/urbit/urbit/blob/master/pkg/arvo/sys/vane/ames.hoon#L1835) error. The solution is to use `+get-peer-state` instead, and ignore the event.
=> ames: ignore missing peer-state on-publ-sponsor

pkg/interface/webterm/app.tsx
Specifies a selection highlight color to make sure it's legible within the active theme. Fixes the visual aspect of urbit/landscape#1270 and #5507, but the selection functionality itself is still hard to discover.
Also disables some xterm.js behavior that would cause alt-clicking to insert arrow keys, with the intent to move the cursor to that location. We (will fully) support clicks natively, so there's no need for this.
Selection highlight color is just whatever the current foreground color is, but notably still gets rendered at the usual 50(?)% opacity.
=> webterm: improve selection look & feel

pkg/arvo/app/azimuth.hoon, pkg/arvo/app/eth-watcher.hoon, pkg/arvo/ted/eth-watcher.hoon
The previous value—used for testing—didn't consider block reorgs, which meant that if we zoom to the latest block that has no transactions, but that gets later replaced by a 1-block reorg that does have a transaction, we'll miss it, making our Azimuth state incomplete.
To fix it, we rewind the Azimuth state to the contents of the snapshot, and then start retrieving logs from the latest one we have.
=> eth-watcher: fix zoom-margin to account for reorgs

pkg/urbit/include/noun/events.h, pkg/urbit/noun/events.c
Clean up [`events.c`](https://github.com/urbit/urbit/tree/peter/truncate-event-log/consolidate/pkg/urbit/noun/events.c) by;
- deleting functions that are not called from anywhere in the system (`u3e_dirty`, `u3e_check()`, `_ce_check_page()`, `_ce_maplloc()`, `_ce_mapfree()`);
- deleting short static functions in [`events.c`](https://github.com/urbit/urbit/tree/peter/consolidate-event-functions/pkg/urbit/noun/events.c) with only a single call site (`_ce_patch_write_page()`, `_ce_patch_create()`, `_ce_patch_read_control()`, `_ce_patch_write_control()`) and instead inling the functionality at the call site;
- and folding the functionality of `_ce_patch_free()` into `_ce_patch_delete()`.
=> u3: consolidate functions in events.c

pkg/landscape/app/dm-hook.hoon
Fixes an issue where the subscription update would contain stale data
=> dm-hook: mutate screened before giving fact

pkg/garden/desk.docket-0, pkg/interface/src/logic/lib/notificationRedirects.ts, pkg/interface/src/logic/reducers/hark-update.ts, pkg/interface/src/views/apps/chat/ChatResource.tsx, pkg/interface/src/views/apps/chat/DmResource.tsx, pkg/interface/src/views/apps/launch/App.tsx, pkg/interface/src/views/landscape/components/Join/Join.tsx, pkg/interface/src/views/landscape/components/Sidebar/SidebarListHeader.tsx, pkg/landscape/desk.docket-0
This fixes a few issues with the way `JoinRoute` was processing `kind` so we were never getting correct differentiation between groups and group chats which caused issues when clicking 'View Group'. 
- ensures that we retain join request state if the modal is open, and ensure that group is in state before allowing them to navigate to it
- notification link handling to redirect to the already joined chat, if already joined.
- fixes an issue causing notifications to not show at all because the check for desk was slightly off.
- stops DMs from trying to load if we haven't accepted it yet
- fixes potential undefined ref in `SidebarListHeader` urbit/landscape#1268
The original "joins" refactor addressed urbit/landscape#1308, urbit/landscape#1342, but this fixes the final part of the flow and a …
=> group-chat: fix joins

pkg/arvo/app/hood.hoon, pkg/arvo/lib/hood/helm.hoon, pkg/garden/app/docket.hoon
Before the software distribution era, file-server used to bind this. Ships that existed pre-dist still have that bound, pointing to the generator in `%home`. Ships that booted directly into the softdist world though, never got this endpoint bound.
Apparently some things still (want to) depend on this. This PR simply restores the endpoint and makes sure it's pointing to the generator on base. Some slightly odd coupling here, with the generator on base, and docket (who now sets up the binding) living in garden, but unless we want to have kiln set this up I'm not sure there's a better place to do this right now.
=> helm: bind /who.json

pkg/arvo/lib/hood/helm.hoon
This is identical to #5522, I was just asked to merge it into `next/arvo` instead of `release/next-userspace`
=> helm: fix |rekey to work with multikey files

pkg/urbit/compat/mingw/compat.c, pkg/urbit/compat/mingw/compat.h, pkg/urbit/noun/events.c
fixes #5565, which was introduced in #5477 (the optimizations introduce there depend on all pages being initially dirty).
=> u3: fix snapshot corruption by preemptively dirtying the loom

pkg/urbit/daemon/main.c
Fallback to the default happens in dawn.c, which correctly points to
roller.urbit.org, an endpoint that matches its request/response logic.
Continuing to use an Ethereum endpoint instead of an L2 one will just result
in 400s, since they don't speak the same language.
Arguably `ops_u.eth_c` should be renamed, but out of scope for here.
=> vere: do not use eth-mainnet for galaxy booting

pkg/urbit/Doxyfile, pkg/urbit/c/queue.c, pkg/urbit/include/c/defs.h, pkg/urbit/include/c/queue.h, pkg/urbit/include/vere/disk.h, pkg/urbit/vere/db/lmdb.c, pkg/urbit/vere/disk.c, pkg/urbit/worker/mars.c
This PR makes a bunch of small, functionality-independent changes, mostly to the `disk` module:
- Add `_disk_free()` to more easily free a `u3_disk` instance's resources.
- Change type of `put_u` field of `u3_disk` struct to `c3_queue *`. 
- Move `u3_feat` struct out of `disk.h` and into `disk.c`.
- Move the declaration of `u3_disk_etch()` out of `disk.h` and into `disk.c` as `_disk_serialize_fact()`.
- Move the declaration of `u3_disk_sift()` out of `disk.h` and into `disk.c` as `_disk_deserialize_fact()`.
- Remove `disk` module's dependency on `foil` module.
- Remove auto-commit functionality embedded in `u3_disk_plan()` and expose `u3_disk_commit()` in the public interface.
- Remove `u3_disk_plan_list()`  and implement looping logic at single call site in `mars.c`.
- Rewrite …
=> vere: tidy up disk module

pkg/arvo/sys/hoon.hoon
The macro expansion for `;<` (urbit/arvo#1150) introduces a gate, wrapping and deferring the execution of the final sub-expression `s`. Since that gate is visible to `s`, idiomatic hoon recursion cannot be straightforwardly used with `;<`:
```
> =/  a=(list (unit @))  ~[`1 `3 `4]
=|  b=(list @t)
|-  ^+  b
?~  a   b
;<  c=@  _biff  i.a
=?  b  =(1 (mod c 2))  [(scot %ub c) b]
$(a t.a)
-need.[i=u(@) t=it(u(@))]
-have.%~
nest-fail
```
`^$(a t.a)` would work, but is very fragile in this style of code -- the number of `^`s corresponds to the number of `;<` expressions between the site of the recursive call and the `|-` in question. Instead, the pattern has been to introduce loop aliases:
```
> =/  a=(list (unit @))  ~[`1 `3 `4]
=|  b=(list @t)
|-  ^+  b
=*  loop  $
?~  a   b
;<  c=@  _biff  i.a …
```
=> hoon: updates %mcgl with an hygienic expansion

pkg/grid/src/state/base.ts
Restores subscription reconnect issues by correctly throwing a
FatalError so that subscriptions are correctly restarted.
This was removed in a refactor, probably by accident
=> interface: fix subscription reconnect issues

pkg/interface/src/views/apps/notifications/notification.tsx, pkg/interface/src/views/components/ProfileOverlay.tsx
The `ProfileOverlay` component expects a `ship` arg as a patp without the sig. This deSigs the ship value used in `NotificationText`.
This closes urbit/landscape#1376
=> interface: use single sig in NotificationText

pkg/urbit/c/list.c, pkg/urbit/include/c/list.h, pkg/urbit/tests/list_tests.c
Reimplement the `c3_list_len()`, `c3_list_next()`, `c3_list_prev()`, and `c3_list_data()` macros as inline functions. There is no performance penalty for doing so, we get the added benefit of type safety and a generally more clear interface.
Tests:
All tests in [lists_tests.c](https://github.com/urbit/urbit/tree/peter/list/pkg/urbit/tests/list_tests.c) pass.
=> c3: reimplement c3_list_* macros as inline functions

pkg/interface/src/views/components/MentionText.tsx, pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx, pkg/npm/api/graph/types.ts
Fixes https://github.com/urbit/landscape/issues/1134
Note that this bypasses remark, which seems necessary for our purposes (and we can just style `<Mention />` directly), but I could be wrong.
To test: send messages like these in any chat:
```
yo *~zod*, what's up?
yo *~zod*
hey **~zod**
hey **~zod**, how've you been?
```
=> groups: Fix markdown styling around ship names in chat messages

pkg/interface/src/logic/lib/util.tsx, pkg/interface/src/views/landscape/components/Join/Join.tsx
Fixes: https://github.com/urbit/landscape/issues/1404
Adds a new func to utils, "preSig", which takes a string and checks for a sig, returning that string if the sig already exists, otherwise returning a sigged string.
=> groups: handle unsigged group links in join

pkg/landscape/app/hark-graph-hook.hoon
Fixes https://github.com/urbit/landscape/issues/1302
Note that the actual change is on line 474. For whatever reason, hoon.vim (I think?) decided to strip out trailing spaces on some lines on save.
=> groups: do not notify user if mentioned in DM

pkg/grid/src/nav/search/Apps.tsx, pkg/grid/src/state/docket.ts
Addresses urbit/landscape#1360 by making the state transitions more explicit, act across the multiple requests, and introduces a timeout so that people aren't waiting for more than 30s.
=> grid: better searching software progress

pkg/landscape/app/notify.hoon
Disables automatic dismissal of push notifications in an attempt to
tighten the debugging space. This should prevent unintentional 404s. To
prevent a space leak we clear notifications once a week on a timer.
=> notify: disable notifications dismissal

pkg/base-dev/lib/ring.hoon
Also I took the liberty of making `build-signing-participants` use a `%lyfe` scry and remove unknowns from the set rather than crashing. This is a choice - happy to change it back the other way.
=> Update /lib/ring/hoon for %jael scries.

pkg/grid/src/tiles/TileGrid.tsx
This cleans up the keys stored for ordering so that if an app is uninstalled it gets removed from the list and also puts preventative measures in.
=> tile-grid: prevent uninstalls from breaking view

pkg/grid/src/tiles/TileGrid.tsx
Fixes loop discovered while I was reviewing https://github.com/urbit/urbit/pull/5653
This bug is live in production.
To reproduce the bug: install an app (like %hodl from ~dister-datder-sonnet) and remove it.
=> grid: fix loop caused by useEffect in tilegrid

pkg/grid/src/app.tsx, pkg/grid/src/state/docket.ts, pkg/grid/src/state/settings.ts, pkg/grid/src/tiles/TileGrid.tsx
This PR addresses issues seen with persisting tile ordering. We were not actually using the settings store correctly so this addresses that which enables the ordering to persist. It also fixes issues where we were overriding previously set ordering due to not waiting for the settings to be loaded.
=> grid: actually use settings and improve ordering correction

.github/workflows/build.yml, pkg/ent/configure, pkg/urbit/compat/poor-mans-nix-shell.sh, pkg/urbit/configure
Apparently at some point `make` went away on the mingw system. `mingw32-make` still exists and does the trick though.
=> repo: fix build on mingw

pkg/arvo/sys/hoon.hoon
This PR plugs a long-standing type-quote leak in bootstrapping the compiler. Newly compiled copies of the compiler could end up holding a reference to the old compiler (transitively), and this would show up as a space leak when upgrading hoon+arvo, and ever-growing pills.
While it's not a new problem, it has not been consistently present. I had "plugged" the leak once before (in #1847), by moving an experimental pretty-printer out of `hoon.hoon` and into userspace. At the time, I suspected an interaction between vase literals (ie, "type-quoting") and an unusual pattern of pinning in that pretty-printer, but was unable to find a precise reproduction. Much later, around or after the final continuity breach, I noticed that the space-leak was back. I tracked it down to core compilations (vase …
=> hoon: plug type leak in compiler bootstrap

package-lock.json, pkg/interface/package-lock.json, pkg/interface/package.json, pkg/interface/src/logic/state/gardenSettings.ts, pkg/interface/src/logic/state/local.tsx, pkg/interface/src/views/App.tsx, pkg/interface/src/views/apps/permalinks/embed.tsx, pkg/interface/src/views/apps/settings/components/lib/NotificationPref.tsx, pkg/interface/src/views/landscape/components/Content.tsx
This builds on this PR: https://github.com/urbit/urbit/pull/5660
(Which requires this PR: https://github.com/urbit/urbit/pull/5656)
And addresses this issue: https://github.com/urbit/landscape/issues/1409
Now that we're storing browser preferences on the ship we can pull those preferences out of garden/grid's settings store into other apps. We could similarly extract out the notifications and theme preferences and then remove those settings toggles from the Groups UI.
Note that this is loading the gardenSettings outside of the bootstrap at the moment and in the AppPermalink component (the only place in the app where we use it, for now). Should we stick this in bootstrap or just load these settings as we need them (@arthyn, related to our discussion on app performance and state hydration)? …
=> Groups: respect garden's browser settings in groups.

pkg/npm/api/lib/lib.ts
Adds the preSig func originally added in https://github.com/urbit/urbit/pull/5632
=> npm: add preSig func to npm lib

pkg/interface/src/logic/api/bootstrap.ts, pkg/interface/src/logic/api/index.ts, pkg/interface/src/logic/state/local.tsx, pkg/npm/http-api/src/Urbit.ts
- Properly handles and restarts connection upon receiving kicks
- Restarted (not resumed) connection now works correctly, I suspect due to closing over stale state
=> interface: fix reconnect bugs

pkg/interface/src/views/components/TruncatedText.tsx
Fixes this: https://github.com/urbit/landscape/issues/1408
Now looks like this:
=> groups: fix issue with wrapping urls in notes

pkg/arvo/app/spider.hoon, pkg/arvo/mar/thread-done.hoon, pkg/arvo/mar/thread-fail.hoon, pkg/base-dev/lib/strandio.hoon, pkg/base-dev/mar/thread-done.hoon, pkg/base-dev/mar/thread-fail.hoon, pkg/garden/desk.docket-0
this is a band-aid for #5442.
adds `%thread-done` and `%thread-fail` marks so that child threads work.
also fixes `await-thread:strandio` and removes some blank lines from
`app/spider.hoon`
`%thread-done` loses the type of the result, so you'll need to use `;;` to
get it back. the right way to fix this is to have threads produce cages
instead of vases according to @philipcmonk
=> spider: fix child threads

.github/workflows/build.yml, .github/workflows/release-docker.yml, default.nix, nix/lib/boot-fake-ship.nix, nix/lib/test-fake-ship.nix, nix/pkgs/pill/brass.nix, nix/pkgs/pill/brass.sh, nix/pkgs/pill/builder.nix, nix/pkgs/pill/ivory.nix, nix/pkgs/pill/ivory.sh, nix/pkgs/pill/solid.nix, nix/pkgs/pill/solid.sh, nix/pkgs/urbit/default.nix, nix/sources-pmnsh.json, nix/sources.json, pkg/urcrypt/urcrypt/secp256k1.c
This PR upgrades nixpkgs to latest master, which results in the following dependency upgrades:
```
gmp:     6.2.0  -> 6.2.1
sigsegv: 2.12   -> 2.14
openssl: 1.1.1g -> 1.1.1n
libuv:   1.40.0 -> 1.43.0
lmdb:    0.9.25 -> 0.9.29
curl:    7.72.0 -> 7.81.0
```
Most notably, this change upgrades secp256k1 (which is unversioned), and includes breaking changes to its API for schnorr signatures, which necessitates changes to urcrypt. It also upgrades LLVM from version 7 to 11 (which took about 16 hours, since the darwin `stdenv` embeds it three (3) times).
#5561 showed up again, and is apparently not M1 specific; it occurs on macos x86_64 as well (and is probably just a clang bug).
I was unable to get `herb` to build inside nix (issues with `pytest-forked` and python2), so I removed `herb` from …
=> build: fix, upgrade dependencies

pkg/base-dev/lib/strandio.hoon
Due to the clunky hack to fix child threads in #5670, data validated by the `%thread-fail` mark is just a raw noun, so we need to use `;;` instead of `!<` on the `[term tang]` in the `cage`.
In response to: https://github.com/urbit/urbit/pull/5671#pullrequestreview-929497298
=> strandio: fix +await-thread %thread-fail handling

pkg/arvo/app/azimuth-tracker.hoon, pkg/arvo/app/azimuth.hoon, pkg/arvo/app/eth-watcher.hoon, pkg/arvo/app/gaze.hoon, pkg/arvo/sur/eth-watcher.hoon, pkg/arvo/ted/eth-watcher.hoon
As discussed out of band with @yosoyubik and @Fang-, I need this feature because my custom `/app/gaze` that produces events for the [network explorer](https://network.urbit.org/)  runs out of memory when processing a massive batch of logs.
=> eth-watcher: implement optional to-block parameter

pkg/landscape/app/graph-store.hoon
support a `%depth-first` scry constructed as follows `.^(* %gx /=graph-store=/graph/<ship of resource>/<name of resource>/depth-first/<count>/<start>/graph-update-3)`
see #5586
=> %depth-first has pattern-matching issue

pkg/interface/src/views/apps/links/components/LinkBlockItem.tsx, pkg/interface/src/views/apps/links/components/LinkDetail.tsx, pkg/interface/src/views/components/RemoteContent/embed.tsx
Adds an optional "stretch" prop to image thumbnails to correctly fill the grid items in Collections.
Also changes the object-fit in the Collections item detail view to show the whole image, uncropped.
fixes urbit/landscape#1313
=> links: image thumbnail fills entire grid item

pkg/interface/src/logic/lib/useMedia.ts, pkg/interface/src/views/landscape/components/GroupSwitcher.tsx
Fixes: https://github.com/urbit/landscape/issues/1426
Added the useMedia hook that we use in grid to groups, added an isMobile check to the GroupSwitcher in order to navigate to just the popover route on mobile so we can see the menu rather than going straight to the notifications section of the settings screen.
=> groups: show group settings menu when pressing settings cog on mobile

pkg/interface/src/views/apps/chat/components/ChatMessage.tsx, pkg/interface/src/views/apps/settings/components/lib/BackgroundPicker.tsx, pkg/interface/src/views/components/CommentItem.tsx, pkg/interface/src/views/components/ImageInput.tsx, pkg/interface/src/views/components/StatelessUrlInput.tsx, pkg/interface/src/views/landscape/components/GroupSettings/GroupFeed.tsx
A fun survey of tiny, annoying issues.
- Adjusts the size of the buttons in the chat message actions menu.
- Eliminates the white background in dark mode for editing a comment.
- Replaces "link" with "URL" or "image URL" in link and image inputs.
- Changes the Group Feed toggle help text to reflect reality.
fixes urbit/landscape#1377
fixes urbit/landscape#1328
fixes urbit/landscape#1161
fixes urbit/landscape#1045
=> groups: various copy and design fixes

pkg/interface/src/views/components/StatelessAsyncToggle.tsx, pkg/interface/src/views/landscape/components/GroupSettings/Personal.tsx
Adjusts the "Group Notifications" toggle copy to reflect reality.
Also makes some minor refinements to the StatelessAsyncToggle such that state changes don't cause layout jumps and/or rely on words like "Saved" or "Done," which may be confusing when used in non-matching contexts.
Off:
Loading:
Success (tooltip shown):
Error (tooltip shown):
On:
fixes urbit/landscape#1012
=> groups: fix join/leave notification toggle

pkg/arvo/app/eth-watcher.hoon
The zoom margin is handled in [`/ted/eth-watcher`](https://github.com/urbit/urbit/blob/132592e32eea16eafdcc275bbd4652421d51b53e/pkg/arvo/ted/eth-watcher.hoon#L86), so this code is unnecessary. My work on #5695 revealed this problem since if you specify a `to-block` when subscribing to `/app/eth-watcher` the last batch of logs never gets released.
=> eth-watcher: remove obsolete zoom-margin handling

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/clay.hoon, pkg/base-dev/sur/hood.hoon
This converts the blob store from having deltas, directs, and
tombstones, to just having direct pages.  This simplifies a lot of code,
since we don't have to constantly ensure that deltas always have their
parent available.
This removes the hardcoded text diff logic from clay, which was
previously required for bootstrapping.
Over the wire, we handle both old and new requests and responses
transparently, so communication is normal in both directions across
ships which do or do not have this change.
Built on top of #5408 to take advantage of the cleanup there.
=> clay: convert all blobs to pages

pkg/grid/src/components/ProviderLink.tsx, pkg/grid/src/nav/Leap.tsx
Fixes: https://github.com/urbit/landscape/issues/1421
also makes the display name visible separately, next to the shipname:
=> grid: fix leap ship autocomplete

pkg/interface/src/logic/lib/useStorage.ts
This PR adds the latest signature version used in most s3 providers, many of which only support v4. Notably this allows people to use [Filebase](https://filebase.com) which has a generous free tier.
=> s3: adding v4 signatures for updated compatibility

pkg/interface/src/views/apps/profile/components/EditProfile.tsx
Adds async/await to prevent pokes from being interrupted by a premature route change in the profile page.
The airlock pokes responsible for updating user profile values in `/~profile/[~zod]/edit` were not being awaited, and would therefore occasionally be interrupted by history.push(). I added async/await, switched to for loops for their simple async/await readability, and removed some redundant if/else logic for the `isPublic` key.
Fixes urbit/landscape#1199
=> groups: fix edit profile

pkg/interface/src/logic/lib/workspace.ts, pkg/interface/src/views/apps/chat/DmResource.tsx, pkg/interface/src/views/landscape/components/GroupsPane.tsx
Replaces the title "Groups" with "Messages" for Messages pane. When the
user selects a DM pane, displays the contact ship's name/nick along with
unread notifications in the title.
Fixes [urbit/landscape#1250](https://github.com/urbit/landscape/issues/1250)
=> groups: set the right title for messages

pkg/interface/src/views/components/RemoteContent/embed.tsx
(Replicated from #5712, minus the extraneous changes.) 
The gains from this unobtrusive change are fairly straightforward.
=> Images should use -webkit-optimize-contrast.

pkg/urbit/include/noun/allocate.h, pkg/urbit/noun/allocate.c, pkg/urbit/noun/nock.c
If we ever come up with a good `@dr` sub-second notation, we could consider using that instead. Until that time, this should be more readable than what we have now.
(Not very excited about how the interface here is subtly inconsistent with `u3a_print_memory`, but didn't want to make a bigger change. Maybe there's C magic I don't have that can bridge the gap, idk!)
=> u3: improve %bout time printing

pkg/npm/api/package.json, pkg/npm/api/rollup.config.ts, pkg/npm/http-api/package.json, pkg/npm/http-api/rollup.config.ts
This fixes an issue which causes the @urbit/api and @urbit/http-api modules to not be able to be used in CommonJS environments, because it treats the CJS builds as ESM.
=> npm: fix libraries module setup

pkg/interface/src/views/components/Author.tsx
The copy function copies ~~zod instead of ~zod to the clipboard. This
removes the extra sig from the copy routine via deSig() incase the ship
string has no leading sig.
Fixes
[urbit/landscape#1434](https://github.com/urbit/landscape/issues/1434).
=> groups: don't double sig the planet name on copy

pkg/garden/app/docket.hoon
Tested this is on a ship that had `%hodl` installed before applying https://github.com/urbit/urbit/pull/5732 and all worked fine.
=> docket: force a |rein %base prior to fixing #5667

pkg/landscape/app/group-view.hoon, pkg/landscape/ted/graph/create.hoon
Adds functionality in %group-view and -group-create to automatically
watch group chats when created. This appears to have gotten lost around
the time of the hark-graph-hook and group-view rewrite
=> landscape: fix automatically watching group chats

pkg/interface/src/views/landscape/components/ChannelPopoverRoutes/ChannelPermissions.tsx
A previous change updated group state to use arrays instead of sets, due
to the ease of (de)serialisation. This was not total, and resulted in a
bug in the ChannelPermissions component
=> interface: update ChannelPermissions to use arrays

pkg/interface/src/views/components/RemoteContent/index.tsx, pkg/interface/src/views/landscape/components/Graph/GraphContent.tsx, pkg/interface/src/views/landscape/components/Graph/blockquote.js
This is a follow up to https://github.com/urbit/urbit/pull/5715. The commits in the previous PR were based off of the wrong branch (`next/landscape` instead of `next/groups`). I re-applied them to this branch in order to avoid excessive diff.
To summarise, this PR:
- change links to be plain URLs
- add rich-embed URL below each plain URL link when appropriate (eg when the link is audio, video, oEmbed, etc)
- allow links to be part of a blockquote without breaking out from the syntax
Furthermore, it addresses a few more small details reported in the previous PR convo (https://github.com/urbit/urbit/pull/5715):
- set URLs in a list item to keep the same text size as the rest of the text
- avoid to display extra nodes below single URLs
This last point, while implemented "visually", is not …
=> Fix proposal for Groups: embeds break formatting context and more

pkg/arvo/app/roller.hoon, pkg/arvo/lib/azimuth-roll-rpc.hoon, pkg/arvo/lib/dice.hoon, pkg/arvo/sur/dice.hoon
This PR fixes the way the roller handled "forced" transactions (i.e. transactions that had a force flag indicating that they should be included in the next batch even if they fail to apply to the roller's predicted state), specially when it relates to the roller's transaction history. This PR also modifies the roller's state to keep track of this forced transactions when the are included in the sending map, so when they fail, they are still considered as part of the batch.
%roller-rpc and it's TS client [v0.1.15](https://www.npmjs.com/package/@urbit/roller-api/v/0.1.15) have been updated to support this.
The contents of the PR are currently deployed to ~roller-dozzod-dozzod and used with the latest version of Bridge.
(Note: this PR is built on top of the …
=> roller: fix handling of forced transactions

pkg/urbit/noun/nock.c
Use an X macro to unify the definition of opcodes, their names, and their indirect jumps in the bytecode interpreter into a single table. The likelihood of these bits of information changing is admittedly low, but I'm dipping my toes into the interpreter waters, and a simple hygiene task like this is a good first step. Plus, it eliminates 50 lines of code :)
Tested:
```console
$ urbit -F bus
<snip>
$ urbit bus
<snip>
```
=> u3: unify interpreter opcode information using X macro

pkg/urcrypt/urcrypt/urcrypt.h
Correct the parameter order in the declaration of `urcrypt_ed_veri()` in [`urcrypt.h`](https://github.com/urbit/urbit/tree/next/vere/pkg/urcrypt/urcrypt/urcrypt.h), which does not match the definition in [`ed25519.c`](https://github.com/urbit/urbit/tree/next/vere/pkg/urcrypt/urcrypt/ed25519.c) nor the call site in [`ed_veri.c`](https://github.com/urbit/urbit/tree/next/vere/pkg/urbit/jets/e/ed_veri.c) on [`next/vere`](https://github.com/urbit/urbit/tree/next/vere).
cc @frodwith
=> urcrypt: correct parameter ordering in urcrypt_ed_veri()

pkg/arvo/app/eth-watcher.hoon
If there were pending-logs in an existing watchdog that was not fully restarted, and the number of the starting block is newer than the first in pending, when starting a new thread, those logs will be carried over to the new thread, which will then be re-downloaded and will fail to be verified in /lib/naive.
Because of the changes here https://github.com/urbit/urbit/pull/5710 this PR might not be relevant since it seems that we release (and delete) the pending logs as soon as we receive them, but it still looks like a good practice to consider this case.
=> eth-watcher: discard future pending logs in watchdog

pkg/arvo/lib/hood/helm.hoon, pkg/arvo/mar/helm-moon-breach.hoon
Intended use is for transitory moons to be able to breach themselves on
startup.
If you run a moon without persistence, then every time the program is
restarted, it must be breached.  This lets the moon breach itself
instead of requiring direct interaction with the planet.  The moon
should reserve the first bone for this purpose, and then every time it
starts up, it should send [%helm-moon-breach ~moon-name] to hood on the
planet.
=> helm: add poke to helm to allow self-breaching moons

pkg/arvo/sys/vane/clay.hoon
The current Ford cache is per-desk, keyed on the name of the build (eg a file at a certain path).  It's impossible to share a cache like this between desks because that name may refer to different things on different desks or at different revisions.
Since these caches aren't shared, they commonly hold exactly the same data, just generated independently.  For example, the same library used on different desks is built repeatedly, and the memory is not shared unless the user manually runs `|meld`.  For users with many apps installed, this adds significant memory pressure.
@belisarius222 and I designed a new cache which is keyed on the name of the build plus its dependencies.  This is all the input to a build except the standard library, so we when we match a key we don't need to know which …
=> ford: rewrite cache to share more builds

pkg/arvo/gen/hood/ames-prod.hoon, pkg/arvo/lib/hood/helm.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon
Sometimes Ames waits for a couple minutes before re-sending a packet.  This is annoying, especially when debugging, so I added an `|ames-prod` generator that resets congestion control for all flows on the specified list of ships, or all ships if no argument.  This causes at least one packet to be re-sent on each open flow to each peer, and resets congestion control to initial values.
We should also fix Ames so it no longer has this problem, but sometimes you just want to tell the computer to send the packet already.
cc @philipcmonk, you might want to take quick lookover here too.
=> |ames-prod reset congestion control

bin/solid.pill, pkg/arvo/sys/vane/eyre.hoon
This change greatly improves the ergonomics of working with channel JSON
in statically typed languages, as the polymorphism is moved out of the
actual diff and into the event framing.
=> eyre: include mark of fact in channel json

pkg/arvo/app/dojo.hoon, pkg/arvo/sys/hoon.hoon
Too often when dealing with big types the compiler traces and other such outputs become hard to read. Wrapping a type as $+(shorthand big-type) will now print #shorthand in place of the type.
To be clear, the changes here are simply connecting the last few dots of a system that's already implemented. I've been using this for a little bit in development, and it behaves fine.
=> hoon: hook up $+ for shorthand type rendering

bin/solid.pill, pkg/arvo/sys/vane/clay.hoon
This fixes a space leak where the entire ford/clay core would be
included in the ford cache. Heavily reduces memory usage by clay,
reducing total usage from 100-200MB to around 10MB per-desk.
Also heavily reduces the size of clay results, they now jam to about 1MB instead of ~20MB
=> clay, ford: Reduce memory usage

pkg/arvo/app/azimuth.hoon, pkg/arvo/gen/azimuth/kick.hoon, pkg/arvo/gen/azimuth/watch.hoon, pkg/base-dev/lib/ethereum.hoon
Repurposes %kick to check for a possible missing subscription to /app/eth-watcher, notify %jael to resubscribe again to /app/azimuth and re-start downloading eth-logs from the last one we have previously downloaded, instead of going all the way back to the last processed block in the azimuth snapshot.
This replaces the previous flow of running this command: `:azimuth|watch 'INFURA_NODE' %default` to get up to date with the ethereum logs with `:azimuth|kick`
=> azimuth:  use %kick poke to restart subscriptions

pkg/urbit/vere/pier.c
This restores `-X`, which was broken in #5575.
=> vere: fixes -X scry/export (broken in previous refactoring)

pkg/base-dev/lib/ethereum.hoon
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md
I needed it because some api's i'm hitting fail if the address isn't checksummed.
Could maybe be written better, haven't done much byte munging in hoon. Feel free to improve.
=> lib/ethereum: +address-to-checksum gate to ethereum lib as per EIP-55

pkg/arvo/sys/vane/ames.hoon, pkg/arvo/tests/sys/vane/ames.hoon
This is a set of changes to ames that affect comet communication, loosely following @philipcmonk's design. Specifically:
- Self-attestation packets are now processed via `+on-publ-full`. This means that comets will respond to a self-attestation with their own self-attestation. It also fixes a bug where receiving a self-attestation would clobber existing peer state.
- Non-comets now send a special "sendkeys" packet to comets that they wish to communicate with. Technically, this is an empty `shut-packet`, encrypted with dummy key. The comet will drop this packet on the floor, but will still respond with a self-attestation.
- When a comet wants to talk to another comet, it sends its own self-attestation rather than a sendkeys packet. The effect is the same (the receiver replies with their …
=> ames: comet communication fixes

pkg/urbit/vere/io/ames.c
This was printing the components of IPv4 addresses in backwards order.
=> vere: print ip address in correct order

pkg/urbit/vere/disk.c
Sets the mapsize for AAarch64 Linux in `pkg/urbit/vere/disk.c` to the largest size I can get to work with musl, 500 GiB.
Leaves the Windows mapsize untouched at the old default of 60 GiB because I haven't done any testing to see what the limit is there.
=> vere: change mapsize to 500 GiB on AAarch64 Linux

pkg/arvo/app/dojo.hoon
It's too easy to get trapped in the Dojo %dy-edit-busy escape room. Just
type something like:
-build-file /=base/gen/ls/hoon
This modifies the dojo output to tell the user how to get out.
Fixes #1462.
=> dojo: say how to beat the %dy-edit-busy escape room

pkg/arvo/app/dojo.hoon
Scries clay for a list of files beneath the provided path - if the response
is nil then the dir must not exist (clay abhors a vacuum).
Fixes #1559
=> dojo: check =dir exists before switching

pkg/arvo/sys/vane/behn.hoon
This PR is built from my validation code for #5857. I still wasn't sure that %behn was handling all state transitions correctly, so I wrote a more explicit, declarative state machine to check its results. Once that I was done, I felt the result was clearer then the previous code.
#5857 has the necessary changes to fix #5747, this is additional cleanup that I think is worthwhile.
=> behn: refactor to use +abet pattern

pkg/arvo/app/dojo.hoon
Changes dojo to emit a usage message and ignore the request.
Fixes #1519
=> dojo: setting eny/now/our shouldn't crash dojo

pkg/base-dev/sur/hood.hoon
These changes address an issue in `%hood` that was causing the `|rein` (#5862) and `|start` (#5627) commands to suspend all unspecified, non-autostart agents on execution (i.e. agents not listed to start by the command and not in `%desk/desk.bill`). Now, `|rein` and `|start` properly only modify the agents specified.
The command sequence below demonstrates the new behavior:
```
~zod:dojo> +agents %base
status: running   %acme
status: running   %hood
status: running   %lens
status: archived  %skeleton-2
status: archived  %skeleton-1
status: running   %dbug
status: running   %azimuth
status: running   %ping
status: running   %dojo
status: running   %eth-watcher
status: running   %spider
status: running   %herm
~zod:dojo> |rein %base [& %skeleton-1] [& %skeleton-2]
gall: reviving %skeleton-1 …
```
=> hood: fix issue w/ rein diff application

pkg/arvo/mar/dns/complete.hoon, pkg/arvo/mar/dns/request.hoon, pkg/arvo/ted/dns/address.hoon
As discussed with @Fang- out of band, the Foundation will take ownership of `ship.arvo.network` domains. This PR points `/ted/dns/address` to the Foundation operated `~deg` instead of Tlon operated `~zod`. It also includes some marks for my DNS automation.
I'll coordinate with @Fang- to switch DNS over when the OTA with this commit hits the network.
=> dns: transfer ship.arvo.network domains from ~zod to ~deg

pkg/garden/app/docket.hoon, pkg/landscape/app/graph-store.hoon
#5706 describes an issue with using `!>` higher up in `graph-store` where multiple types are potentially included in the vase's construction, resulting in a type of `?((unit time) update-log:store)` when scrying the internals - no fun!
=> Solve #5706 - Create vase at each branch of `t.t.t.t.path`

pkg/arvo/sys/vane/behn.hoon, pkg/arvo/tests/sys/vane/behn.hoon
This PR fixes #5747 and adds regression tests for %behn.
The bug was caused by %behn failing to emit a `%doze` effect (to set the next timer in the runtime) in certain necessary situations (itself caused by failing to clear the runtime state mirror `next-wake`, and unnecessarily comparing pending timers to the current timestamp). It also removes some unnecessary behavior: `%doze` was emitted unnecessarily, and occasionally with intentionally-skewed timestamps.
=> behn: fix timers not firing

pkg/arvo/sys/vane/gall.hoon
Removes the `!:` at the top of gall, so that it no longer gets included in traces about agent builds or crashes.
We also refine intentional crashes with `~_`s, so that we still see a crash reason even if we don't get a full trace.  
Unintentional crashes obviously cannot get this treatment, and as such may not provide useful pointers for debugging when they get hit. RFC on this tradeoff. Perhaps there are some more-localized places we still want to put a `!:`?
Lastly, flops the trace for `+on-load` crashes, which were getting printed bottom-first.
Should alleviate #5854 at least partially.
=> gall: exclude from traces

pkg/urbit/vere/disk.c, pkg/urbit/vere/io/term.c, pkg/urbit/vere/king.c, pkg/urbit/vere/pier.c
This PR tweaks handling of fatal errors in vere (specifically the "king" process). We now track the presence of a fatal error in global state (`u3_Host.xit_i`, already present and fit for purpose), and make sure to fail any attempted prep-for/upgrade in the presence of errors. (The absence of this logic meant that a binary upgrade could succeed even if preparatory replay failed, which could leave the pilot with a binary that refuses to run linked into the pier.)
=> vere: exit correctly on fatal error

pkg/arvo/sys/vane/eyre.hoon
Problem:
by-channel has its own copy of server-state from line 2182. discard-channel returns an altered state, with one channel removed from the state of by-channel.
but the state of by-channel isn't changing with each iteration, so %trim is only removing one channel per invocation instead of all channels.
Solution:
update by-channel on each iteration.
=> eyre: fix for %trim bug

pkg/urbit/include/c/motes.h, pkg/urbit/jets/e/aes_siv.c, pkg/urbit/noun/manage.c, pkg/urbit/vere/io/ames.c, pkg/urbit/worker/serf.c
The "punt" logging pattern in the crypto jets was intended to surface unusual error conditions. But urcrypt and libaes-siv don't clearly distinguish between deterministic decryption failure and other errors (invalid calls, allocation failures, &c). to ensure determinism, so the relevant jets "punt" *all* errors back to the nock interpreter. And `+de:sivc` is used by ames, which means that receiving any invalid ciphertext or stale keys produces noisy, useless output: two lines of `sivc-de-punt` per packet.
The PR just removes the logging, but there are two non-trivial next steps which should be done:
- deterministic decryption failure should not punt
Accomplishing this will require review of libaes-siv and the openssl functions it depends on, and may require patches to distinguish error …
=> jets: remove +de:sivc punt logging

pkg/arvo/mar/aqua/effect.hoon
This is needed for successful test runs, and should've gone in with #5681 but slipped through somehow. My bad!
=> aqua: add %aqua-effect mark file

pkg/npm/http-api/src/Urbit.ts, pkg/npm/http-api/src/types.ts, pkg/npm/http-api/test/default.test.ts
Surfaces the mark of the subscription updates.
For this to not be `json` requires that the ship be running the upcoming kernelspace update. However this upgrade is backwards and forwards compatible, i.e. current `http-api` and these changes are compatible with both current kernel space and upcoming kernel space. How to proceed with versioning changes? Suspect a minor version bump, because type signatures have changed, albeit not very meaningfully.
=> @urbit/http-api: surface mark of updates

pkg/arvo/sys/hoon.hoon
Printing some vases is extremely slow without sharing this cache.
Previously, this was shared "accidentally" because all the compiler
calls were run in the same road; now we do it explicitly.
A pathological case is `!,  *hoon  a=1`.  This change reduces the time
required to run +sell on that (eg by entering it in the dojo) from 43
seconds to 320ms.
Also added a `!.` to `+mean` because without it adding a `!:` to the
top of hoon.hoon creates really bad stack traces in some cases.
We should be on the lookout for this kind of slowdown elsewhere.
=> hoon: thread compiler cache through +sell

pkg/npm/http-api/src/Urbit.ts
I had independently discovered and patched #5864, only to discover my branch was just too stale. Still, I think I can add additional value here.
In reconnect scenarios (or wonky network situations) we may receive events we had already heard. Here we make sure to drop those.  
(Not that this library currently does reconnects in that way, but it should probably be made to.)
Also simplifies the getEventId() logic, and clarifies the difference between the different `*EventId` values.
=> http-api: prevent double-processing of events

pkg/npm/api/index.ts, pkg/npm/api/package-lock.json, pkg/npm/api/term/lib.ts
Replaces https://github.com/urbit/urbit/pull/5904
(wasn't based on next/npm)
=> api: fix `@urbit/api` `term` exports

pkg/urbit/vere/king.c
Currently when creating a fake ship, if an invalid ship name is given,
then the program exits without ever cleaning up the terminal. This
results in  a bugged termianal that requires closing and repopening
or using the `reset` cmd.
This commits adds a call to `u3_term_log_exit()` and `fflush(stdout)`
before calling `exit(1)` to ensure proper cleanup.
Address issue #5914
=> vere: clean up terminal on invalid fake ship name

pkg/arvo/sys/vane/ames.hoon
The previous recork timer queued up %cork messages without sending them.
It also relied on making sure pump timers didn't get set for recork bones.
This was fragile.
The new design enqueues up to one new %cork message per ship during each
recork timer, based on the state of the flow.  If the flow is closing but
there are no outstanding messages in it, then it needs to be recorked.
Flows will be recorked in ascending numerical order by bone.
=> ames: recork better

pkg/urbit/daemon/main.c
This PR fixes a dumb oversight in the new binary upgrade system. Thanks to @midlyx-hatrys for the report.
Fixes #5924.
=> vere: make `prep` and `next` commands non-interactive (no tty required)

pkg/arvo/sys/vane/gall.hoon
Gall tells ames to %cork flows for subscriptions it has closed.
Receiving a kick also closes a subscription, but gall wasn't issuing a
%cork in that case. We correct that here.
Inlines +mo-handle-ames-response's logic at its only callsite.
=> gall: cork a subscription's ames flow on-kick

pkg/arvo/sys/vane/gall.hoon
Gall was not always including the subscription nonce in the wire, when it should have been. Most prominently, when `%leave`ing a subscription due to a crash.
Additionally, we were not initializing the sub-nonce correctly during the upgrade case. This affected ships who have been running pre-release until now, but the artifacts this issue has left behind will get cleaned up by new-and-improved `|doff`.
=> gall: handle nonces in wires correctly

pkg/arvo/sys/vane/ames.hoon
Stop crashing on benign acks on corked bones.
Also, +on-plea gets called in two very different ways:
1) handling request from local vane to send %plea to peer
2) handling %cork request from another ship, which our local ames has %pass'ed
to ourselves
In the second case, we shouldn't print misleadingly, or bind a duct in the ossuary.
=> ames: fix "ack crash"

pkg/arvo/sys/vane/gall.hoon
In response to clog notification from remote ames, we were sending a
%cork to clean up the flow. However, the wire we were using had the /sys
prefix already stripped off. Here, we put it back in.
=> gall: use a fully-formed wire when sending %cork

pkg/arvo/gen/hood/doff.hoon, pkg/arvo/lib/hood/helm.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon, pkg/arvo/sys/vane/gall.hoon
`%doff` now kills live subscriptions and any old subscriptions that might be lingering due to prerelease bugs.  We had to modify Ames to ignore `%leave` messages sent on closing or corked bones during a `%doff`.
=> gall: kill old subscriptions on %doff

pkg/arvo/tests/sys/vane/ames.hoon
The test turned out to be broken because we were injecting the wrong rift number in a mocked move.  Fixing that caused the test to pass.
=> ames: fix comet test

pkg/arvo/sys/vane/gall.hoon
Adds a `%f` scry to Gall to retrieve the sub-nonce for each agent.
=> gall: scry for nonces

pkg/arvo/gen/ames-timers.hoon
Per ship, for the top N (default `50`) ships .
=> base: adds generator for getting %ames timer counts

pkg/arvo/sys/vane/gall.hoon
We've seen some issues with `|doff`, so we're turning it off for now.  This leaves in the interface and hood generator, so we can enable it again easily.
=> gall: disable %doff for now

pkg/arvo/gen/gall-nonces.hoon
Shows the list of agent-nonce pairs in ascending-nonce order, so that the (supposedly) most interesting ones are always easily visible.
=> gen: add +gall-nonces for reading all next nonces

pkg/arvo/sys/vane/gall.hoon
This is sufficient to bring the normal (non-prerelease-bugged) cases
into the new world.
For the prerelease ships that ran a buggier version of the new gall
subscription logic, we note that the conditional may trigger for the
nonce=1 case where it had already triggered for their
(shouldn't-be-possible) nonce=0 case. This results in a %leave on a wire
that wasn't in use. This no-ops on the publisher side though, and the
flow gets corked right away, so this is considered harmless.
=> gall: re-enable doff, only for old-style subs

pkg/base-dev/lib/agentio.hoon
Original post:
> The current code in agentio.hoon has +rest as a copy-paste of +wait, and thus sending a %wait rather than a %rest to Behn.
It was easier to make a new PR to target next/arvo than to rebase (which had conflicts).
=> agentio: fix `+rest` typo, attempt 2

pkg/arvo/sys/vane/gall.hoon
When ames notifies us that our subscription has been kicked, we enqueue
a cork to clean up the flow. Unlike the %leave case, however, we were
not registering the cork in the queue of outstanding comms. We would
eventually get an ack, but not know what for, and erroneously inject
%poke-acks and %watch-acks.
Here we simply add a %cork entry to the queue before sending it.
=> gall: when kicked, register %cork as outstanding

pkg/arvo/sys/vane/gall.hoon
This is a band-aid to work around the upgrade bug where sometimes `%base` agents fail to restart.  Upon receiving a move whose target is `%base` or `%dojo`, instead of enqueueing or dropping the move, force-start `%dojo` and `%hood` and then retry the move.
I've tested this by running `|pass [%g %idle %hood]` and `|pass [%g %idle %dojo]`.  Both cases work fine as far as I can tell.  Earlier versions of this code that didn't roundtrip through Arvo had subscription problems after the revival.  Note that the `/nowhere` wire is important to use with `%jolt` to ensure resulting `%onto` agent restart notifications don't crash Gall.
I've targeted this PR at master, since that's what I based this code off of.  Happy to retarget if needed.
=> gall: revive %hood and %dojo on keypress

pkg/arvo/sys/vane/ames.hoon
Yes, there is a global timer for closing flows, but all that does is
enqueue a cork message. +on-stir needs to set _pump_ timers for all
flows that might still have messages to send, which includes closing
flows.
=> ames: don't skip closing flows in +on-stir

pkg/arvo/gen/ames-flows.hoon
This should help to diagnose issues with runaway resubscriptions or any Ames flows that have failed to close.
=> +ames-flows: diagnostic generator to count ames flows

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/gall.hoon
This sends a `%cork` on any old subscription ducts, which should have been corked already but might not have been if a ship had been running a prerelease version of the gall request queue fix.  h/t @joemfb 
The "all" flag should only be set if you want the ship to try to kill an old subscription at sub-nonce zero.  If your ship didn't run with a particularly old version of the gall request queue fix, then if you set `all=&`, gall will end up creating an extra Ames flow (and hopefully cleaning it up, but better not to find out).
=> gall: %rake task to clean up dead %leave's

pkg/arvo/sys/vane/gall.hoon
We shouldn't be hitting this case anymore. Injecting events into agents
which they might not expect, and might not even be real, is bad.
=> gall: don't inject potentially-fake acks

pkg/urbit/noun/manage.c
Following on #5826, wherein I failed to realize that this would also print 2x per bad packet ...
=> u3: suppress bail:evil printf

pkg/arvo/sys/vane/ames.hoon
Previously, when the larva got to processing enqueued events, it was
doing so without loading state into the adult beforehand, resulting in
incorrect processing of events.
Here, we make the larva call +molt more eagerly, ensuring that the adult
always has its state available when we use it.
=> ames: ensure larva initializes adult's state

pkg/arvo/sys/vane/ames.hoon
As a follow up to #5961. The previous implementation used the wrong duct, and didn't cancel stale or wrong pump timers, leading to their proliferation.
Per @belisarius222, this should also traverse %ames' state and recalculate `next-wake` for each flow (maybe under a `%hard` argument). I'll work to add that, but this is ready to go as is (tested on my ship, corrected timer issues introduced by the previous version).
=> ames: refactor %stir, %rest stale/wrong timers

pkg/arvo/sys/vane/ames.hoon
Fixes some issues with Ames's larval upgrade logic that were discovered when upgrading ~zod.
=> ames: fix upgrade bugs

pkg/interface/src/views/components/RemoteContent/index.tsx
Adds a prop (`stretch={tall}`) to allow images in notebook posts to fill the width of the post
Notes:
- Doesn't affect messages in Groups or DMs
=> interface: full width images for notebook posts

pkg/arvo/sys/vane/ames.hoon
Also fixes the error slog on failed attestation timers.
=> ames: handle failed recork timers

pkg/arvo/sys/vane/ames.hoon
Pre-release ships may have multiple recork timers. This ensures that, after stir, we always have exactly one.
=> ames: clean & re-set recork timer during %stir

pkg/arvo/sys/vane/ames.hoon, pkg/arvo/sys/vane/gall.hoon
Locally, `%cork` is guaranteed to succeed instantly. The requesting vane doesn't need an ack to safely consider the flow "closed". Ames will now no longer eventually give a `%done` in response to `%cork` tasks.
Subsequently, gall will consider any `%cork`s it sends completed immediately, and no longer sticks it in the outstanding requests queue. It also cleans up the queue's entry whenever it's empty.
Largely untested at the time of writing, but I think this is right. At some point, we'll want to rip out gall's request queue entirely.
=> ames, gall: no %done on corks

pkg/arvo/sys/vane/gall.hoon
This gets added in +ap-handle-peers already.  This caused outgoing subscriptions to not get cleaned up properly.
Issue introduced in c2d77a5d.
=> gall: don't add duplicate nonce in +ap-nuke

pkg/arvo/ted/dns/address.hoon
My newfangled automation of `ship.arvo.network` domains introduced in #5868 exposed a bug in `ted/dns/address`: the thread pokes before subscribing. This often leads to situations where the DNS request is completed before the client subscribes, leaving this thread running forever.
=> dns-address: subscribe before poke and fix wire mismatch

pkg/npm/http-api/src/Urbit.ts
Will allow us to handle rejections more gracefully.
=> http-api: If scry fails, return reject response

pkg/garden/lib/treaty.hoon
For some reason, a %uv case was added to the JSON serialiser for $case. $case has no such case in the union, and so this does not make sense.
=> garden: fix broken treaty JSON

pkg/arvo/sys/vane/clay.hoon
We shouldn't get a clay stack trace for read-at-aeon-fail because that gives us miles of clay stack trace whenever hoon compilation fails
=> Don't print a stack trace for `read-at-aeon-fail`

pkg/arvo/ted/test.hoon
Changes the test command to check if args contains a single path and
wraps it in a list. Now a test thread can be started without providing
a list:
-test %/tests/lib
And passing a list still works:
-test %/tests/lib ~
If no arg is given, `test` will run all tests under `/=base=/tests`.
=> pkg: -test shouldn't require a list of paths

pkg/arvo/sys/vane/eyre.hoon
Eyre always gets passed request headers in lowercase, so we should search for
the lowercased version of the header.
Arguably `+get-header` should lowercase keys before comparing them, but that's
a more serious behavioral change.
(Notably browser-native EventSource clients don't generally make use of this header, which explains why this has lasted as long as it has. Userland implementations might though!)
ht @joemfb for catching this.
=> eyre: look for lowercase last-event-id header

pkg/arvo/sys/vane/clay.hoon
seems that this structure has been unused since
[e75ab631a4de5061714af1905de4a1bf1a2a951d](https://github.com/urbit/urbit/commit/e75ab631a4) and confuses
newbies trying to figure out exactly what the commit
structure is (which is how I came across this)
=> clay: remove $dork

pkg/urbit/daemon/main.c, pkg/urbit/include/noun/options.h, pkg/urbit/include/vere/mars.h, pkg/urbit/include/vere/vere.h, pkg/urbit/worker/mars.c
We currently automatically pack the memory when we start running out of space. We have avoided automatically melding, because it may be slow and require a significant amount of memory on the host machine.
Here, we add an --auto-meld flag that enables automatic melding, so that it can be opted into in situations/setups where it makes sense.
Have had some trouble testing this properly, but did get the auto-meld to run at some point.
=> vere: meld on memory pressure, if --auto-meld

pkg/urbit/bench/ur_bench.c, pkg/urbit/include/noun/allocate.h, pkg/urbit/include/noun/events.h, pkg/urbit/include/noun/manage.h, pkg/urbit/include/noun/options.h, pkg/urbit/noun/allocate.c, pkg/urbit/noun/events.c, pkg/urbit/noun/manage.c, pkg/urbit/tests/ames_tests.c, pkg/urbit/tests/hashtable_tests.c, pkg/urbit/tests/jam_tests.c, pkg/urbit/tests/jet_tests.c, pkg/urbit/tests/mug_tests.c, pkg/urbit/tests/newt_tests.c, pkg/urbit/tests/nock_tests.c
The PR makes the loom memory-map size a runtime rather than compile-time configuration. The compile-time constants are still there (`u3a_bits`/bytes/words/cells/pages &c), but those are now representational upper-bounds instead of exact limits.
Next steps for this PR include adding commandline flags to set the loom size for both mars and urth processes, and bumping those compile-time upper bounds where possible (which would make #6001 more important).
These changes will need to be reconciled with #5701.
See #880
=> u3: allow the loom size to be set at runtime

pkg/arvo/sys/vane/ames.hoon
This PR addresses #6009 by setting a ship's sponsor in %ames to itself when azimuth sponsorship is lost.
Barring a state migration in %ames, the only other obvious option I see is to simply ignore sponsorship loss in %ames. This will likely impact networking more than that would, but it shouldn't entirely prevent it, and it seems better to respect the pki change. Thoughts?
=> ames: hotfix for pki sponsorship loss

pkg/garden/app/docket.hoon, pkg/garden/lib/multipart.hoon
Some files, like zip files, may have trailing zero bytes, which get eaten when stored in reverse in an atom. So instead, we say `content` is an `octs`, passing the true size along.
Fixes #6012.
Not immediately obvious to me if this should go into `next/landscape` or not, considering the only changes there right now are frontend changes.
=> garden: respect all zeroes in multipart content

pkg/urbit/daemon/main.c, pkg/urbit/include/c/motes.h
sample output:
```
$ build/urbit vile fake-zod
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/110.231.552
boot: installed 351 jets
0w50w.642KA.glYh8.RvaRp.6TA35.3XRYN.ULCI6.UmcsZ.5rGvG.3dvFt.E6rMF.mZnd~.3O6QB.7LZ1f.-ukYN.z2fcY.Ecviv.LiZEg.8w0sp
```
=> vere: adds %vile command for extracting keys

pkg/arvo/app/aqua.hoon
Previously, attempting to use aqua's `%swap-files` poke would crash, since the scry path was malformed. The desk was also hard-coded to `%work` -- now the user inputs a desk name. I've tested the new poke, and was able to successfully add a desk to aqua's pill and spin up a new fakeship with it, which then properly installed the agents in that desk.
=> aqua: make `%swap-files` poke take a desk and add it to pill

pkg/urbit/include/noun/retrieve.h, pkg/urbit/noun/retrieve.c
This PR adds overflow checks (compile time where possible, runtime where not) to the atom measurement function `u3r_met()`. To offset the cost, it also removes so unnecessary branches. These checks could elided if `u3r_met()` returned `c3_d` instead of `c3_w` -- that change should be made, but it'll be more invasive (and have implications for allocation interfaces, which are often driven with measured values).
=> u3: add overflow checks to u3r_met()

pkg/urbit/c/defs.c, pkg/urbit/include/c/defs.h, pkg/urbit/include/vere/vere.h, pkg/urbit/noun/events.c, pkg/urbit/noun/manage.c, pkg/urbit/noun/urth.c, pkg/urbit/vere/io/http.c, pkg/urbit/vere/io/term.c, pkg/urbit/vere/io/unix.c, pkg/urbit/vere/king.c, pkg/urbit/vere/lord.c
This PR replaces all instances of `read()` and `write()` (outside of the `compat` directory) with `c3_read()` and `c3_write()`. `c3_read()`/`c3_write()` are wrappers around `read()`/`write()` that correctly handle partial reads/writes. They also handle retries in the case where `read()`/`write()` returns `EINTR`, `EAGAIN`, or `EWOULDBLOCK` up to a specified maximum number of attempts. 
Incorrect handling of partial reads/writes in `events.c` is the suspected cause of our lingering snapshot corruption bug, which has tended to appear when disk space fills up. Additional work will be required to gracefully handle failed calls to `c3_read()` and `c3_write()` in `events.c`, but that work is beyond the scope of this PR.
The inclusion of `c3_read()` and `c3_write()` has the added benefit of …
=> c3,u3: read() and write() to completion

pkg/urbit/compat/mingw/compat.c, pkg/urbit/compat/mingw/compat.h, pkg/urbit/noun/events.c
This PR builds on #5889. It's a draft due to conflicts, and should wait to be reconciled with #6003.
The implementations are "partial" because `ReadFile()` and `WriteFile()` update the file position after i/o completion -- these are not spec-conformant implementations, but are fit for our single-threaded use-cases (so long as calls to their non-positioned counterparts aren't intermingled on the same file *description*).
=> mingw: adds (partial) implementations of pread/pwrite

pkg/urbit/daemon/main.c, pkg/urbit/include/noun/options.h, pkg/urbit/include/vere/vere.h, pkg/urbit/noun/events.c
This PR implements demand paging for the loom. Thanks to @ritfed-tabryg for the suggestion, @eamsden for many fruitful design discussions, and @mcevoypeter for the original implementation in #5940.
Demand paging is implemented on linux and macos, and turned on by default (disabled by `--no-demand`). It remains highly desirable on windows (where memory is not overcommitted), but will require changes to our "platform abstraction layer" (lol) to support CoW file-backed mappings, and further changes to the implementation to explicitly remove old mappings before establishing new ones.
The changes here differ from #5940 in key ways. The north segment of the loom (home-road heap, `north.bin`) is still in a CoW file-backed memory map, but that mapping is now reestablished after every snapshot …
=> vere: implements demand paging

pkg/urbit/vere/disk.c
If you run the urbit binary as root (common in `systemd` services and similar) and happen to run the urbit binary again as a less privileged user the lockfile handling of vere fails. This is a common cause of corruption in situations like #6024. To reproduce, start a fakezod with `sudo`, then run the same fakezod as a normal user.
This PR adds an explicit check for the `kill` permission error, making the protection against dual boot situations more robust.
=> vere: check for permission error on old process kill

pkg/urbit/compat/mingw/compat.c, pkg/urbit/compat/mingw/compat.h, pkg/urbit/daemon/main.c, pkg/urbit/include/noun/options.h, pkg/urbit/vere/disk.c
u3 ignores SIGTERM in certain circumstances. This behavior is non-operable in the urth process, since libuv is configured to intercept SIGTERM and deliver it asynchronously on the main loop. But it is operable in the mars process. So the mars PID is a bad fit for the lockfile, which is a pidfile, and used by external scripts to shutdown vere (in CI, for example). The lockfile is managed along with the event log, which has been moved to mars.
This PR adds mars/urth/sole process roles to u3, and uses `getppid()` to create the lockfile when the process role is mars. It may well be better to change the signal-handling, but this is less risky for now.
=> vere: use the urth PID in the lockfile

pkg/urbit/daemon/main.c, pkg/urbit/include/c/portable.h
This PR bumps the maximum loom size from 2GB (`2^31`) to 4GB (`2^32`). To avoid breaking any current deployments, the default loom size remains unchanged. Opt-in to the largest size with `--loom 32`. Thanks to cgy for leaving us an extra bit. More to come.
NB: this size bump is not currently opt-in across maintenance commands -- these will also need to be updated and support the `--loom` argument.
=> vere: bumps the loom max to 4GB (opt-in)

pkg/arvo/sys/hoon.hoon, pkg/arvo/tests/sys/hoon/set.hoon, pkg/urbit/jets/d/in_apt.c
FIX: #6037 
`apt:in` now checks for duplicates
```
> ~(apt in ^-((set) [1 [1 ~ ~] ~]))`
%.n
```
=> fix apt:in duplicate bug #6037

.github/workflows/build.yml, .github/workflows/vere.yml, default.nix, nix/default.nix, nix/overlays/arm.nix, pkg/urbit/include/c/portable.h
Opening this PR for posterity ...
This upstreams @botter-nidnul's nix patches to support static binaries for aarch64 (changes to the codebase itself had already been accepted in prior PRs). Thanks to @botter-nidnul for his years of work producing community-supported binaries!
The rest of this PR updates our github actions config to support aarch64 via buildjet.
=> vere: adds official arm builds

pkg/urbit/Makefile, pkg/urbit/include/noun/events.h, pkg/urbit/noun/events.c, pkg/urbit/noun/manage.c, pkg/urbit/tests/jam_tests.c, pkg/urbit/tests/meme_tests.c, pkg/urbit/tests/nock_tests.c
This PR fixes a latent memory-corruption bug introduced with the guard page in release v1.10, prs #5881 and #5882.
Those changes replaced inconsistent, ad-hoc road-stack overflow checks with an orthogonal approach: a guard page is protected in the center of the loom, moved on page faults, and used to systematically prevent the road heap and stack from running into each other (by producing a `bail:meme`). This is system is more rigorous and efficient than the prior approach, but it depends entirely on the assumption that our memory usage patterns are linear and contiguous, from either end of the loom towards the center. This assumption is violated during the creation of inner roads, since padding is added between the parent road heap and child road stack. If the guard page happens to fall …
=> u3: fixes memory corruption in inner roads

pkg/urbit/noun/events.c, pkg/urbit/noun/manage.c
This PR fixes another latent memory-corruption bug introduced in v1.10 (see #6072 for context, the bug was introduced in #5881 and #5882).
`|meld` modifies every page of the persistent state, so tracking the pages that it touches is not worthwhile. It's optimized to turn off page-tracking, in such a way that a subsequent snapshot update will restore it. But this optimization has the unfortunate side effect of removing the guard page (which it pre-dates), for the duration of the process (ie, restarting the ship would restore it, and running `meld` as a subcommand does not risk corruption).
This PR restores the guard page after turning off (all other) page tracking, and maintains or asserts other relevant invariants of the guard page system.
Fixes #6078.
=> u3: fix memory corruption after meld; enforce guard page invariants

pkg/urbit/daemon/main.c, pkg/urbit/include/noun/urth.h, pkg/urbit/noun/urth.c, pkg/urbit/worker/mars.c
This PR modifies the replay logic (in mars, unreleased) to explicitly enumerate errors during replay, print appropriate messages and/or stack traces, and retry `bail:meme` after `pack` (or `meld`, if run with `--auto-meld`). Targets #6079, as it was in the development of this feature that those issues were discovered.
=> vere: handle errors during replay

pkg/urbit/noun/events.c, pkg/urbit/noun/manage.c
This PR is a minimal back-port of the snapshot error handling fixes (and error message improvements) from #6062 and #6063 (without the overall feature set of either). Opened for visibility, as this is a bigger diff than the other hotfix changes (and newly written, whereas the other changes are mostly just cherry-picked from elsewhere).
=> u3: improve snapshot error handling (for hotfix release)

pkg/arvo/sys/vane/ames.hoon
The +on-cork handler asserts that the peer is known to us. This is the incorrect behaviour, because it will crash when corking a flow to a peer that is still an %alien. This can happen, for instance, when making a gall subscription for the first time and then corking it before the alien naturalises.
Questions:
- Is no-opping the correct move here? I suspect it is not
=> ames: prevent crashes when corking an alien flow

pkg/npm/api/README.md
Replacement for #6030 to get around issues with merge commits in a fork I don't have access to fix.
=> Fix npm README typo: setings -> settings

pkg/npm/http-api/src/Urbit.ts
Subset of #5918 that includes _just_ the `Urbit.ts` changes. This should be able to go out to frontends right now and retain their existing behavior, while preparing them for the full release of #5918 at some point in the future.
=> http-api: use /~/name endpoint if cookie not legible

pkg/urbit/daemon/main.c
Opening this PR for visibility ....
These (mechanical, highly duplicative) changes add support for the `--loom` argument (#6010) to many subcommands (`meld`, `next`, `pack`, &c). A shared arguments parser (maybe auto-generating `--help`) for these commands would be a welcome contribution...
=> vere: supports --loom for all relevant subcommands

pkg/arvo/sys/vane/gall.hoon, pkg/landscape/app/graph-store.hoon
This PR updates %gall to allow its agents to optionally integrate with `|mass`. %gall's `/whey` scry handler peeks into each agent , and incorporates their labels if successful/valid (with error output suppressed).
Additionally, this PR includes a basic integration with `:graph-store`. Only the resource name is displayed, which might not be sufficient. It may also be worth grouping graphs and logs instead of listing the separately. This new output should be coupled with simple instructions for listing graphs/archives, measuring their memory usage, and removing them if it becomes necessary. (All the graph-store stuff could easily be a separate PR, can easily be released piecemeal, &c.)
=> %gall: integrate agents with |mass

pkg/arvo/ted/test.hoon
Preserves the behavior of stripping "%tests" from test paths but keeps
tests under other directories so their test- arms are still evaluated.
Fixes [#5803](https://github.com/urbit/urbit/issues/5803)
=> pkg: don't silently skip non %tests/ test arms

pkg/arvo/sys/vane/ames.hoon
Stale lanes may cause forwarding loops. Imagine the following:
1) Planet A is live. Galaxy B, its indirect sponsor, learns of its route.
2) A goes offline. Another ship, C, is started in its place, at the same route.
3) B receives a packet for A, forwards it to the known route.
4) C received the packet, forwards it to B.
5) Repeat from 3.
Here, we update the forward lane(s) scry used by the runtime to not produce a
peer's lane if they haven't communicated with us in the last hour. Everyone's
supposed to ping their sponsorship chain every 30 seconds. If those aren't
going through, you shouldn't expect to be reachable anyway.
We may or may not want to update +send-blob to match.
=> ames: do not produce stale forward lanes

pkg/arvo/app/dojo.hoon
These changes re-add support for file imports via `%ford` runes (e.g. `/+`, `/-`) to `%dojo`, since their inadvertent absence [post-fusion](https://github.com/urbit/urbit/pull/3060). To minimize changes to `%dojo`'s app data, imports are currently limited to the `/+` and `/-` runes, which import into the `lib` and `sur` variables, respectively.
```
~zod:dojo> /-  *dns
~zod:dojo> (address.sur [%if *@if])
[%if if=.0.0.0.0]
~zod:dojo> /+  kg=keygen, csv
~zod:dojo> (ownership-wallet-from-ticket.kg.lib ~zod [4 ~.dozzod-dozzod-dozzod-dozzod] ~)
[ type="ownership" seed=...]
~zod:dojo> (print-rows.csv.lib `(list vase)`~[!>('a') !>('b')])
'a'
'b'
<1.tan [* <46.hgz 1.pnw %140>]>
~zod:dojo> /+
~zod:dojo> lib
-find.lib
dojo: hoon expression failed
~zod:dojo> /%  txt  %txt
~zod:dojo> =>(~(grab txt "") …
```
=> dojo: re-add support for ford runes

pkg/arvo/tests/lib/naive.hoon
I had commented out some of these tests because running the full `+test-rut` can take ~s15 to ~s30 or more depending on hardware. I did not realize that running these tests was actually part of the CI pipeline at the time, so I'm uncommenting them.
This should be uncontroversial, but since it adds a non-trivial amount of time to CI I could see an argument for not including them - but maybe that's just evading the point of CI and it takes however long it takes. Someone more experienced ought to have a better idea than me.
=> naive: uncomment some naive.hoon tests

pkg/arvo/sys/vane/jael.hoon
As discussed with @philipcmonk out of band, it's strange that the "general" `%public-keys` subscription excludes moons. Jael may not track all moons in existence, but it should certainly still tell you about the ones it knows about. In most cases, those are the only ones you care about anyway.
=> jael: send updates to all "general" pubkey subs

pkg/base-dev/lib/language-server/complete.hoon
See https://github.com/urbit/urbit/issues/6052.
This is the only use of the deprecated syntax of `+*` I was able to find in the repository.
I was going to make the changes to `+boog` to remove the `+*` parsing in the same PR, and that works fine on a ship with only `%base`. But Clay seems to run into issues with this on a regular solid pill fake ship with
```
> .^((set desk) %cd %)
{%bitcoin %base %landscape %webterm %garden %kids}
```
I haven't figured out why yet. Even though `+cat %/lib/language-server/complete/hoon` shows the change in the commit here, it still says its running into a syntax error as though it hadn't changed. I'll be adding the stack trace to https://github.com/urbit/urbit/issues/6052. In any case, it makes me pretty sure that we need to change the existing instance …
=> language server: change +* to |$

pkg/arvo/sys/vane/clay.hoon
This is an experiment in documenting invariants in Clay.  This was inspired by synchronously reviews of recent changes to Clay, where the most important parts were me constructing arguments that certain guarantees were upheld.
This comment describes the system:
https://github.com/urbit/urbit/blob/45b5257c04f2b3a7d44c50f68be758b5751cb5ea/pkg/arvo/sys/vane/clay.hoon#L34-L77
This also fixes two issues discovered by thinking through these issues in this methodical way:
- `|label` did not result in a `+wake` call, so if a subscriber was waiting on that label to exist, they would not get updated until something else happened on that desk.
- `+park` did not invoke `+tare` for suspended desks, so if a commit to a suspended desk added an item to its commit-in-waiting, then subscribers would not …
=> clay: document invariants

pkg/arvo/sys/vane/ames.hoon
- fix `fragment-num` and `num-fragments` having duplicate faces
- fix faces being wrapped around wrong things in various places
- fix `bone` not being printed in "hear last in-progess" message
- make pretty tape interpolation style more uniform
@joemfb
resolves #6058
=> ames: debug print msg formatting fixes

pkg/base-dev/lib/bitcoin-utils.hoon
When the first byte is greater or equal to 0xfd, (bex len) bytes are consumed to
form the csiz atom, but only one byte is dropped from the 'rest' of the input.
The parser should consume all bytes of the CompactSize.
=> bitcoin-utils: Fix parsing of of CompactSize integers

pkg/arvo/app/dbug.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon
Tested this on two different live moons and saw no communication issues: they can talk to each other, their sponsor, install apps, join/leave/rejoin groups.
Addresses decrement-underflow error seen in #6075 and https://github.com/urbit/urbit/issues/5979#issuecomment-1275723988
Note: this updates `%lull`
=> ames: remove num-live from pump-metrics

pkg/arvo/sys/vane/clay.hoon
These are hotfixes for a prerelease of 417.  Recompiling all apps (as necessary for upgrading Clay) took too much memory to complete on ~wicdev-wisryt (>600 MB), these address that issue.
First, we stop adding explicit road transitions in Clay.  These were added in d1b4af89fea7922deb7f7660a08f82e34a89ae66 to avoid the issue where the memoization cache would accumulate entries for all compilations within a road, becoming far too large.  Six days later the memoization cache was capped in #3041, rendering the road transitions unnecessary, but since performance was acceptable, we did not revisit that decision.
Since the memoization cache is capped, it actually requires less memory to do all compilations in the same road.  This way, internal fragmentation (free lists) gets reused, and we don't …
=> clay: 417 hotfixes

pkg/landscape/desk.bill
This is currently under contention for agent name with new groups, and unused in current groups.
=> groups: removing notify

pkg/arvo/sys/arvo.hoon
I'm not sure if `|de` has some connotation - it's mentioned that this core would be called `de` in prior commits but it doesn't seem to be named that here. Until it switches to `de`, putting it in parity with `+of`
=> Fix Comment: `arvo` comment for `|of` reads `|de`

pkg/urbit/noun/events.c
This PR fixes a regression introduced in #6072 (and released in v1.11) whereby it was possible to have "multiple simultaneous guard pages" (alternately, whereby old guard pages were not properly cleaned up). This condition would result in the `strange page` assertion being eventually hit, when we subsequently faulted on an already-dirty, non-guard page.
The guard page implementation should be refactored so that these ad-hoc implementation details aren't spread around too much, but this is the smallest change to fix the regression right now.
=> u3: ensure a single guard page

pkg/urbit/noun/events.c, pkg/urbit/tests/events_tests.c
This PR fixes an unreleased bug introduced in #6063, whereby snapshots could be corrupted when they were resized.
The bug was caused by a discrepancy between memory protections and page metadata (not unlike #6125), and was introduced while refactoring an earlier version that failed to maintain the invariant that only pages within the snapshot could be clean (harmlessly, because there was no discrepancy). So this PR also includes documentation of the key invariants of the snapshot system. Thanks to @belisarius222 for his assistance formulating and reviewing these invariants. Further localization of these comments (a la #6085) would be highly desirable.
Finally, this PR replaces `static const` page sizes with macros, to avoid the proliferation of VLAs introduced in #5881. Thanks to …
=> u3: document and enforce snapshot system invariants

pkg/urbit/noun/events.c
This PR forward-ports (the unreleased portion of) #6079 for release, extending it to account for the changes in #6126. PR'd here for posterity.
=> u3: re-enforce guard page invariants.

pkg/grid/src/nav/notifications/Inbox.tsx, pkg/grid/src/nav/notifications/SystemNotification.tsx, pkg/grid/src/tiles/Tile.tsx
This PR addresses a few straggler issues in the integration between Grid and new Clay / Kiln (aka [Agents in Clay](https://roadmap.urbit.org/project/agents-in-clay)).
=> grid: new clay + kiln integration  

pkg/garden/desk.docket-0, pkg/grid/src/nav/notifications/SystemNotification.tsx
The old predicate checked whether we have a commit-in-waiting for the next kelvin.  We add a check that the desk is even live -- we don't want to block on suspended apps.
=> grid: only block on live apps

pkg/arvo/gen/solid.hoon, pkg/arvo/sys/arvo.hoon, pkg/arvo/sys/hoon.hoon
This PR cleans up the boot formulas, pill generators, and various virtualization apis, making them avoid unnecessary variation in the nock formulas they use. This avoids pressure on the bytecode compiler and cache, and is just generally more correct. @frodwith has been after me to clean this sort of thing up for a long time. (The change to `+slot` is probably spurious, depending on the precise behavior of an interpreter.)
These changes may help @jtobin with some of his caching work.
I've applied to this to a running ship and tested the apis in question, built the relevant pill types and successfully booted from them all.
/cc @eamsden
=> hoon: use static nock formulas for boot and virtualization

pkg/arvo/gen/story-list.hoon, pkg/arvo/gen/story-read.hoon, pkg/base-dev/lib/story.hoon, pkg/base-dev/mar/story.hoon
`+story-list` produced janky indentation because the `$-(story wain)` functions encoded linefeeds in the cords of the wain and the printer doesn't like this.
Story printing functions have been changed to produce pure wains without linefeeds.
resolves #6017
=> story: fix story printing

pkg/urbit/bench/ur_bench.c, pkg/urbit/compat/mingw/seh_handler.c, pkg/urbit/daemon/main.c, pkg/urbit/include/all.h, pkg/urbit/include/noun/events.h, pkg/urbit/include/noun/manage.h, pkg/urbit/noun/events.c, pkg/urbit/noun/manage.c, pkg/urbit/noun/urth.c, pkg/urbit/tests/ames_tests.c, pkg/urbit/tests/events_tests.c, pkg/urbit/tests/hashtable_tests.c, pkg/urbit/tests/jam_tests.c, pkg/urbit/tests/jet_tests.c, pkg/urbit/tests/meme_tests.c, pkg/urbit/tests/mug_tests.c, pkg/urbit/tests/newt_tests.c, pkg/urbit/tests/noun_tests.c, pkg/urbit/worker/serf.c
This PR builds on #6126 and refactors the interface to the snapshot system (`events.c`), further isolating it from the rest of u3.
- `events.h` has been removed from `all.h` and should no longer to be directly called. Instead, use the wrapper functions in `manage.h` (`u3m_save()`, `u3m_ward()`, &c). The high/low watermarks used throughout the snapshot system have been normalized, and a number of small errors (off-by-one, &c) have been corrected.
- The `.urb/chk/` directories inside the pier are now created at a higher level, with paths passed in.
- The guard page system now operates by page index instead of "post" (word-offset into the loom). The rounding logic (my suggestion in #5881) was ill-considered and has been removed. It was intended to reduce faults by biasing the guard page …
=> u3: refactors snapshot system interface

pkg/arvo/app/azimuth.hoon
Fixes typo introduced in [36deb95411d0a94c3aa6e772adc2b4ae2f946764](https://github.com/urbit/urbit/commit/0e16d82a46ea569e04326ba497b99f93b7ddc751)
This is a copy of https://github.com/urbit/urbit/pull/6148 made to just clean up the commit message since I don't have access to the third party repo fork to do it there.
We should typically not commit directly to master to avoid this class of problem in the future, more details are in this comment: https://github.com/urbit/urbit/pull/6148#issuecomment-1353638486
=> Fix build break typo in azimuth

pkg/urbit/daemon/main.c, pkg/urbit/include/noun/manage.h, pkg/urbit/noun/manage.c
This PR makes the full replay command (`play -f`) work in the presence of arbitrary snapshot corruption (requiring special initialization). And it fixes the argument parsing of the `queu` command, which has been broken since the binary consolidation in v1.9.
=> vere: minor fixes for replay tools

pkg/arvo/.gitattributes
We no longer need to omit `pkg/arvo/tests` from this repo's export archives (@jtobin confirmed in chat a couple weeks ago), and I need the folder to be bundled in archives for CI in the [new repo](https://github.com/urbit/vere).
=> gitattributes: remove export-ignores

pkg/arvo/sys/zuse.hoon
in the past, `+team` meant "our / our moon", but it has been primarily used to represent "our".
Moons as having the full permissions of their parents doesn't make a lot of sense anymore.
I've combed through the uses of `+team` throughout urbit/urbit and I'm quite sure that each instance is better off as just "our".
This looks like the more elegant solution (instead of changing each instance of `+team`)
@philipcmonk
=> zuse: change team:title to return false for moons

pkg/arvo/sys/hoon.hoon
`|*  foo  bar` is sugar for `=+  foo  |@  ++  $  bar  --`, and newbies find
the old style confusing. this switches out the `|@` pattern for the `|*`
one, at least in layer <=4. the only ones remaining are `+toad`, `+rune`,
and `+runo`, which are already tweaked in #5873 so we omit them here.
some jets are harmed, so it probably needs to be part of a kelvin release:
```
fund: in in, parent 6a6f885b not found at 7
fund: in apt, parent 3b38f03b not found at 7
```
should probably be merged alongside #5873
=> hoon: swap =+  foo  |@  ++  $  bar  --  for |*  foo  bar

pkg/arvo/gen/hood/install.hoon, pkg/arvo/lib/hood/kiln.hoon
It's often useful to |merge a desk, but if you're still getting updates from your sync source, you may get overwritten in the future.  In this case, you want to merge and clear the sync source.  With this change, you can do this with:
```
|install ~ship %desk, =once &
```
=> kiln: add `once` flag to |install

pkg/base-dev/lib/agentio.hoon
Closes #5992.
Because of how wet gates handle types, the vase created by `+fact-curry` is unusable and there's no real way to fix it. Hence removal.
=> base-dev: remove `+fact-curry` from lib/agentio

pkg/arvo/lib/hood/kiln.hoon
Increments the commit number every time, is there a better way to do this?
=> kiln: recursive `|rm`

pkg/arvo/sys/vane/clay.hoon
This flow is not supported, and it was causing issues releasing 416.  This change just drops the responses to avoid crashing, but at some point we should either support this flow or reject the request in the first place.
=> clay: Drop foreign %wris responses

pkg/landscape/app/chat-hook.hoon, pkg/landscape/desk.bill
Old groups software, no longer supported. Don't want this to be re-linked and confuse people just trying to use their dojo.
Confirmed that this works cleanly even if chat-cli is in the forefront when this logic runs. Used the /app/chat-hook because it seems most appropriate, and I don't trust changing logic of graph-store or w/e. Repeated runs of this will just no-op.
Closes #6229.
=> chat-cli: put it to rest

pkg/arvo/app/acme.hoon, pkg/arvo/lib/dns.hoon
also: libdns handle 301 redirect during self-check
when https redirects were implemented in eyre, the initial cert configuration worked ok. However, when trying to renew, it couldn't handle the now-enabled 301 redirects. This changes it so it just directly makes https requests for the self-checks if https is enabled in eyre
resolves #6234
=> acme: handle https redirect in self-check

pkg/arvo/lib/hood/kiln.hoon
This is the fourth option described in #6244.
Fixes #6244
=> kiln: Keep %kids desk in sync after kelvin update

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon
Fixes #6245
Respects both `|ames-verb %kay` and `|ames-sift`
=> ames: put "is ok"/"not responding" behind |ames-verb

pkg/interface/webterm/lib/blit.ts
As it turns out, the exact behavior of the 'S' CSI command is not "move contents up into scrollback", but rather "delete the top line(s), move other contents up". This behavior leads webterm to eat into outputs whenever it renders slogs.
Xterm(.js), when given a newline character at the bottom of a scroll region, does produce the desired behavior of bumping the top line away into scrollback, instead of obliterating it.
This implementation now diverges from vere's, which is unfortunate, but the alternative is making webterm track the contents of the bottom-most line of the default session, which seems rather ridiculous by comparison.
Fixes #6257.
=> webterm: safer printf rendering

pkg/arvo/app/dojo.hoon
Hoon.hoon got the separating `+` added in 13d1c28 (part of #5641), but dojo was never updated to match. Here, we pass it on.
Super tiny change, so figured I should PR against the release candidate. Of course this logic really shouldn't live in two places, but here we are.
=> dojo: match hoon.hoon %know %hint printing style

pkg/webterm/desk.docket-0
For release with a new glob that includes #6258.
=> webterm: v1.1.1

bin/solid.pill, pkg/arvo/gen/hood/close-flows.hoon, pkg/arvo/gen/stale-flows.hoon, pkg/arvo/lib/hood/helm.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon, pkg/arvo/sys/vane/gall.hoon
Adds `|close-flows`, a %hood generator that sends a %cork to all ships that have nacked a %watch (e.g. we tried to subscribe, and the publisher crashed or rejected our subscription, but we didn't properly %cork the flow). This issue is fixed in https://github.com/urbit/urbit/pull/6102, and this PR depends on it in order to work properly.
The tool runs in dry mode by default, printing the number of flows that can be closed. To actually send the corks, run as:
`|close-flows, =dry |`
(possible fix for https://github.com/urbit/urbit/issues/6065, that will alleviate _some_ memory pressure in %ames)
PS: this updates %lull in its current form by adding a %kroc task to ames—the names is taken but we currently don't use the %kroc gift and the $krocs set so we should probably remove that.
=> ames: add |close-flows

pkg/arvo/lib/hood/kiln.hoon
=> clay: correctly restart syncs when source breaches

pkg/arvo/sys/vane/clay.hoon
Ensures no desk with an illegal name can be created by sanity checking in `%fuse`, `%park`, and `%merge`.
Prevents the cause of #6266 but doesn't fix ships with bad desk names already.
Replaces #6290.
=> clay: desk name sanity check

pkg/arvo/sys/vane/eyre.hoon, tests/sys/vane/eyre.hoon
#5918 got deployed prematurely to ~binnec, without giving app developers a change to update their version of `http-api`. This broke Groups and pretty much every frontend app. This PR removes the `HttpOnly` header from eyre for now, but keeps the new `/~/name` endpoint so people can use the old stuff and the new stuff for a while. We can add the header back later.
=> eyre: revert inclusion of HttpOnly header for now

pkg/arvo/lib/test/ames-gall.hoon, tests/sys/grq.hoon
Fixes #6333 
This is working fine in the branch prior to the removal of %/tests from the arvo folder, but running the test suite (after copying everything into a running ship) shows some tests failing (e.g. gall-test-jolt; others show a `bail: 3` message) and this one also failing (it looks like it doesn't run the %sub agent). Not sure what has changed since #6207?
=> ames: fix failing GRQ test

pkg/arvo/sys/vane/clay.hoon
Previously, if the pointer for a syntax error pointed to the end of the file (and the file ended in a newline) the code snippet rendering would try to display a line _beyond_ the end of the file, causing a crash.
Here, we detect that case, and display `<<end of file>>` instead.
(Originally merged through #5812, but got lost somewhere along the way. This is a cherry-pick of the commit from there.)
Fixes #6287. Supersedes #6288. Special thanks to @hosted-fornet for catching that this was missing again.
=> clay: render syntax errors at end of file

bin/solid.pill, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/eyre.hoon
The previous changes implementing the `/~/name` endpoint were breaking, since we changed the type of `$action:eyre`. This commit keeps the `/~/name` endpoint functional, but adds adapters to eyre scries that returns the old `$action:eyre` type. These adapters and their associated intermediate types can be removed the next time we burn a kelvin.
The associated issue is #6342, see also #5918 and #6324.
=> lull, eyre: add intermediate type for /~/name endpoint

pkg/autoprop/app/autoprop.hoon
Autoprop has a timer that checks whether we're on a new/different runtime periodically. When we detect we are, we re-build the props, so that they may be re-published under that new version identifier.
However, we weren't updating the cached runtime version we store in state, causing every firing of this timer to re-build the props.
Here, we correctly update state if we detect a difference, so that subsequent timers don't trigger redundant rebuilds.
=> autoprop: properly keep track of runtime version

pkg/arvo/sys/vane/ames.hoon
addresses #6340
this adds a variable at the top of ames, `packet-size`, set to `13`. This
1. is better style, letting people know what `13` means in the code
2. lets `%pyro` easily modify packet size for a large boost in performance
=> ames: store packet bloq size in subject

pkg/arvo/app/hood.hoon, pkg/arvo/gen/hood/knob.hoon, pkg/arvo/lib/hood/drum.hoon, pkg/arvo/lib/hood/helm.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/dill.hoon
Adds a `%logs` task to dill, which can be used to un/subscribe to system output.
All of `%crud`, `%talk` and `%text` are now considered "system output" for this purpose. Dill no longer renders those itself. This further uncouples it from drum, dill now makes no assumptions about the default session except the fact that it exists.
Drum has been updated to subscribe to these `%logs`, and will now render those in dill's stead. The visible behavior here should not have changed, they always get rendered into the default session.  
(That's a little bit of a lie. Cases where non-default sessions would experience poke-nacks or watch-nacks (in dill's interactions with the terminal handler agent) would previously get rendered in their associated sessions. I think considering those part of the …
=> dill: legible %logs

pkg/arvo/sys/hoon.hoon
Unify logic for `div` and `mod` in `dvr`, instead of splitting the logic and repeating the same calculation twice on a `dvr` call.
Also add default sample to `dvr`, mirroring `div` and `mod`.
Tested changes successfully against latest code from `develop` (both `urbit/urbit` and `urbit/vere`).
=> hoon: minor improvement to +mod and +dvr

pkg/arvo/mar/ted/eval.hoon, pkg/arvo/sur/ted/eval.hoon, pkg/arvo/ted/eval.hoon, pkg/arvo/ted/khan-eval.hoon
Partially resolves [#197](https://github.com/urbit/vere/issues/197)
Add a mark to make it easier to use the `eval` and `khan-eval` threads via `conn.c` + Khan.
=> ted: add mark to use eval thread via khan

pkg/arvo/sys/vane/ames.hoon
Fixes #6363
We have a reproduction betwen ~halbex-palbep and ~rontul-dantyr-norsyr-torryn, I'll put this fix in ~palbex-halbep to confirm that it work and will then open it for review.
=> ames: always ack recork pleas

.github/workflows/vere.yml
[This issue](https://github.com/cachix/cachix-action/issues/144) in the `cachix/install-nix-action` repository provides the solution to our problem: simply upgrade the action.
The successful CI jobs associated with this PR/branch (see below) demonstrate the effectiveness of this solution.
Resolves #6367.
=> ci: upgrade to `cachix/install-nix-action@v20`

pkg/base-dev/lib/ethereum.hoon
Resolves #6376.
Adds ethereum-types:render-hex-minimal and and ethereum-types:hex-bytes-minimal. Modifies RPC for get-block-by-number to render block number using these.
Fixes 16-bit alignment in ethereum block number serialisation which results in stuck eth-watcher on livenet.
I'm new to hoon so I'm sure there's a more elegant way to do this. However, this addressed the issue locally and on the test ships I have available. This is a minimal patch which should not impact other users of num-to-hex or render-hex-bytes until further discussion can be had.
Urbit ID: ~macpem-micsec
=> Fix stuck %eth-watcher due to get-block-by-number zero-padded number RPC failure.

bin/solid.pill, pkg/arvo/sys/hoon.hoon
Resolves #6380.
I updated the section of `sane` which checks for `%t` validity to iterate through bytes with an incrementing cursor. This greatly reduces memory load.
=> hoon: make sane memory-efficient for large atoms

pkg/arvo/sys/vane/ames.hoon
=> ames: no-op if bone has been corked on the sender

.github/workflows/develop.yml, .github/workflows/feature.yml, .github/workflows/master.yml, .github/workflows/release.yml, .github/workflows/vere.yml
Resolves #6370.
@jalehman Should we be using `next/*` for our "release branch" pattern? We could use `next/kelvin/*` or `next/release/*` as well. Thoughts appreciated. See `release.yml` for where we use it.
cc @philipcmonk @zalberico
=> ci: use branch for `vere` version

pkg/arvo/lib/hood/kiln.hoon
Resolves #6242 / #6154
Handles the `|uninstall` of local desks
=> kiln: fix uninstall

pkg/base-dev/lib/sss.hoon
Closes #6397
Forgot a step in my `;:` chain, and had the wrong "base case". Also cleaned up the logic, `?:` seems clearer than `?.`.
The logic here is: When trying to serve a wave `w'` that doesn't exist, we only assume that it was deleted (i.e. send a `%yore`)
- if the last known wave `w` exists, then only if `w' < w`
- if the last known rock `r` exists, then only if `w' ≤ r`.
In all other cases, including when neither `w` nor `r` exist, the requested wave is in the future and should result in a `%nigh`.
Shout out to @rabsef-bicrym who discovered the mistake. :)
Side note: using the irregular forms of tisgal and miccol together seems to break Github's syntax highlighting. Do we know who is responsible for this?
=> sss: Distinguish between an empty path and a wiped path

pkg/arvo/sys/vane/ames.hoon
Fixes #6391
(I tested this on ~norsyr-torryn that was constantly hearing boons on a corked bones and after acking them they have stopped)
=> ames: always ack %hear tasks on corked bones

pkg/arvo/lib/hood/kiln.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/clay.hoon
We were retrying failed kelvin upgrades as many times as we had apps that needed to be suspended, because suspending an app triggers an attempt to run the next kelvin upgrade.  This suspends all those apps in one batch move, and then tries the next kelvin upgrade only once at the end.
Fixes #6407
Partially addresses #6285
=> hotfix clay rebuild loop

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/eyre.hoon
This fulfills the first milestone of https://urbit.org/grants/eyre-scry. It adds a simple cache to eyre that maps URLs to scry paths, with the usual accessors for updating the cache. A gift is given to the runtime when a watched file changed, and the full cache is sent to the runtime on init.
=> eyre: Add cache

pkg/arvo/gen/vat.hoon, pkg/arvo/gen/vats.hoon, pkg/base-dev/sur/hood.hoon
With a hat tip to #6390, this pr also implements #6297.
Not quite ready to merge; in certain cases I don't understand, the formatting of the resulting tank gets messed up. Also I need to start getting my updates from ~binnec-dozzod-marzod. Will report back asap.
=> +vats options

pkg/base-dev/lib/sss.hoon, pkg/base-dev/sur/sss.hoon
Closes #6409 
Turned into a fairly large rewrite. Still some rough edges in terms of architecture, but the interface should be stable and it works as intended (as far as I can tell after testing), and I wanted to get it released quickly to unblock hodzod and focus on remote scry instead.
Permissions are either set by using `+public:du`, `+secret:du`, `+allow:du` and `+block:du`, or manually by passing a gate to the `+perm:du` arm. Permissions are encoded as `(unit (set ship))`, with `~` indicating public data and `[~ ships]` indicating that only `ships` are allowed. So for example, to only grant access to `~sampel`, call `+perm:du` with `_[~ (silt ~sampel ~)]`. 
It’s also possible to kill a path using `+kill:du`. This deletes the state from the publisher and informs anyone who tries to …
=> sss: Unsubscribing and permissions

pkg/arvo/gen/hood/new-desk.hoon
Resolves #6426.
Add an optional argument "minimal" to `|new-desk` which preserves current behavior; otherwise, by default, include an additional list of files in the new desk that will help jump-start development of a Gall agent.
=> arvo: add more files to |new-desk generator

pkg/arvo/sys/vane/ames.hoon
Resolves [#6442](https://github.com/urbit/urbit/issues/6442).
`.^((unit @da) %ax /=//=/peers/~zod/last-contact)` now returns a `(unit @da)` of the `last-contact`.
=> ames: add last-contact scry endpoint

pkg/arvo/sys/vane/dill.hoon
Instead of including wrapped-task as-is in most call traces, we now only include it in traces for crashing (harden task) calls. For everything else, we include only the tag of the resulting $task.
Closes #6444. That issue doesn't specify under what conditions this was observed. I imagine in the crashing `harden` case we'll still want to be able to inspect the noun. I still include the tag of the resulting task in the general trace, for clarity.
=> dill: exclude wrapped-task from most +call traces

pkg/arvo/app/ping.hoon, pkg/arvo/sys/vane/ames.hoon
Redo of https://github.com/urbit/urbit/pull/5828, which had bad merge conflicts.  This is cleaner because of @yosoyubik's Ames refactor.
=> ames: ping faster to sponsors

pkg/arvo/sys/arvo.hoon
This PR prints the time it takes to compile Hoon, Arvo, Lull, Zuse, and the vanes.  Compile times seem to have slowed down recently, so it would be good to know which modules are the bottlenecks.
Sample output (upgrading from an old Arvo that did not have these hints yet):
```
> |commit %base
>=
arvo: beginning upgrade
arvo: compiling next arvo
arvo: +load next
lull: ~hidtem-sardyn
took s/5.899.605
zuse: ~rindeg-bollyt
took s/8.318.232
vane: %ames: ~mormul-divnux
took s/3.766.802
vane: %behn: ~sogmut-tonmus
took ms/494.150
vane: %clay: ~fashus-ridwex
took s/16.344.822
vane: %dill: ~togmed-bondyl
took s/1.098.004
vane: %eyre: ~danfet-dosfyr
took s/3.579.556
vane: %gall: ~foddeb-nacsul
took s/2.876.367
vane: %iris: ~macryl-midnyl
took ms/404.828
vane: %jael: ~ravnex-fitref
took s/2.320.433 …
```
=> arvo: print module compilation times

pkg/arvo/sys/vane/behn.hoon, pkg/arvo/sys/vane/clay.hoon
... and handle them correctly in the only remaining %drip-sites in %clay.
This has been tested and validated in various upgrade scenarios between local fake ships. It was motivated by a case of `.^` in `+on-load` rendering a ship effectively inoperable (`behn: queue blocked`).
=> behn: propagate errors in deferred moves

pkg/arvo/sys/vane/eyre.hoon
Eyre keeps a queue of unacked events, resending them to a frontend through a SSE stream until they are acked. This behavior is violated in `+on-get-request` where the events are cleared from the queue without waiting to hear the acknowledgement. This is incorrect.
This PR has bearing on #6311, but there are other problems as well. More fixes coming up later.
=> eyre: do not clear unacked events in +on-get-request

pkg/arvo/sys/vane/ames.hoon
The `%snub` task was introduced in `urbit-os-v2.131`: https://github.com/urbit/urbit/blob/urbit-os-v2.131/pkg/arvo/sys/lull.hoon#L379
This corresponds to `%ames` state `%9`: https://github.com/urbit/urbit/blob/urbit-os-v2.131/pkg/arvo/sys/vane/ames.hoon#L863
It was later modified in in `urbit-os-v2.136`: https://github.com/urbit/urbit/blob/urbit-os-v2.136/pkg/arvo/sys/lull.hoon#L383
Corresponding `%ames` state is `%12`: https://github.com/urbit/urbit/blob/urbit-os-v2.136/pkg/arvo/sys/vane/ames.hoon#L884
The `+load` migration was correctly written from `%ames` state `%11` to `%12`, but given that the `queued-event` type is dependent on the type of `task:ames` in lull, versions `%9` and `%10` will miserably fail to migrate, printing out the type of ames state for hours.
TLDR it's currently …
=> ames: properly migrate old %snub tasks

pkg/base-dev/lib/sss.hoon
Closes #6469 
This is a trace from the previous version. It should've been a type error, but wet gates...
Thanks to @litlep-nibbyt for finding it!
=> sss: Fix memory leak on publisher

pkg/arvo/app/dbug.hoon, pkg/arvo/sys/vane/eyre.hoon, pkg/base-dev/sur/hood.hoon
This PR fixes some %gall meta-namespace reads that were missed in merging #6406 (revised there to account for #6388). Thanks to @arthyn for the bug reports.
It'd be great to trigger (more) of these codepaths in CI. Maybe loading parts of the debug dashboard over HTTP?
=> arvo: fix %gall meta-namespace reads (missed in merge)

pkg/base-dev/mar/json.hoon
On the tin, this uses the more standard `de:json:html` instead of the internal parsing arm.
=> json: used optimized arm for mime -> json

pkg/arvo/gen/vats.hoon, pkg/base-dev/sur/hood.hoon
_(plus trailing whitespace cleanups)_
Display `%base` first and `%kids` last if you don't specify a list of desks (`+vats` or `+vats, =filt %exists`).
before
```
> +vats
%bitcoin
<snip>
::
%base
<snip>
::
%kids %cz hash:     0v1f.ga4df.4tv9m.tbrep.209ub.kngeg.tlfqm.7ct9l.srvaf.6apg6.j43l7
%talk
<snip>
::
```
after
```
> +vats
%base
<snip>
::
%bitcoin
<snip>
::
%talk
<snip>
::
%kids %cz hash:     0v1f.ga4df.4tv9m.tbrep.209ub.kngeg.tlfqm.7ct9l.srvaf.6apg6.j43l7
```
The `+sort` moves `%kids` to the head of the list and `%base` to the rear.  A downstream `+flop` displays the desks in the desired order.
The `+sort` is in two places because `+vats` and `+vats, =filt %exists` are different code paths.
If you specify a list of desks no sorting occurs.
```
> +vats %bitcoin %kids %talk %base …
```
=> +vats: sort %base and %kids (sometimes)

CONTRIBUTING.md
re: `-c`
```
urbit -F zod -B path/to/urbit.pill my-fake-zod
too many arguments
Urbit: a personal server operating function
https://urbit.org
Version 2.1
Usage: ...
<snip>
```
```
urbit -F zod -B path/to/urbit.pill -c my-fake-zod
~
urbit 2.1
<snip>
```
=> meta: command corrections in CONTRIBUTING.md

pkg/arvo/app/spider.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/gall.hoon, pkg/arvo/ted/keen.hoon, pkg/base-dev/lib/strandio.hoon
=> fine: next steps

pkg/landscape/app/dm-hook.hoon
This fixes incorrect call to `scry:io` in dm-hook.
=> landscape: actual 413 compat

pkg/arvo/gen/vat.hoon
In #6532 I changed `+report-vat` to produce a `tang` instead of a `tank`, but I forgot that `+vat` still existed.
=> vats: fixes +vat

pkg/arvo/app/dojo.hoon, pkg/arvo/sys/hoon.hoon, pkg/arvo/sys/vane/clay.hoon, pkg/base-dev/lib/language-server/parser.hoon, pkg/landscape/app/chat-cli.hoon
.. with backwards-compatible `+vang` interface. This PR targets #6509. (The combined diff looks like https://github.com/urbit/urbit/compare/develop...jb/vang-compat.)
=> hoon: support configurable doccords parsing

pkg/arvo/sys/vane/clay.hoon
`=case` was added as an argument to read-s to support %cs subs. It was accidentally removed as an argument during a merge, breaking %cs subs by causing it to always crash in a comparison between `case` and `[%da now]`, because `case` resolved to the mold rather than a value. This commit restores intended functionality.
=> clay: fix read-s subs for 413

pkg/arvo/sys/vane/clay.hoon
This significantly reduces memory usage during userspace rebuilds. It's not exactly clear why; there's some kind of effective space leak in memoization while parsing. This is an easy, low-risk, stop-gap.
=> clay: virtualize parsing to workaround runaway memoization

pkg/arvo/sys/vane/eyre.hoon
... and responses more efficiently.
The `+got:by` in `+handle-gall-error` was not correct -- pokes to suspended agents can be deferred arbitrarily, and there's no guarantee that we still have the connection. (@finned-palmer encountered this with a suspended %garden).
The `+got:by` in `+handle-response` was redundant, the connection is already in scope. There also redundant connection-state updates, or patterns of update followed immediately by delete.
=> eyre: handle agent errors safely

pkg/arvo/sys/vane/eyre.hoon
Previously, if an incoming request caused a crash, we would just drop it on the floor. We should at least have the decency to serve the client a quick 500 and let them get on with their day.
We make sure not to touch state here. The connection is guaranteed-fresh because of the task's semantics, and we're handling it in-line in one go.
Notably we only give a simple "crud!" for the body, instead of the full error trace. We don't know whether the request is authenticated or not (and who knows if checking was the cause of the crash!), and the crud might leak sensitive details about the ship it occurred on. For the owner, the trace still gets printed into the terminal.
=> eyre: when a %request causes a crud, serve 500

pkg/arvo/sys/vane/gall.hoon
=> gall: always check that an agent isn't nuked before initializing `+ap`

pkg/arvo/sys/vane/clay.hoon
This PR relaxes a constraint introduced in #6568, which is too restrictive for existing use cases.
=> clay: allow reads at the null tako

pkg/arvo/sys/vane/clay.hoon, pkg/arvo/sys/vane/gall.hoon
Meta: this is hotpatched directly onto ~dem.  Nothing should be released before this, or if it is, then this should be re-hotpatched onto ~dem.
Galaxies process a lot of pings, and in 413K, the time required to process pings regressed by roughly 10x, to around 30-40ms each.  In the 413K refactoring around requests for remote scry, we started checking whether a requested hash was in the "reachable takos" of a desk before we could approve the request.  Unfortunately, for many live ships, this process takes more than 10ms.
There are several possible mitigations, two of which are implemented here.
- First, the ping requests use the `%noun` mark, and Gall dutifully tries to build the `%noun` mark in order to validate that the untyped noun it received is in fact an untyped noun.  There's no …
=> Clay/gall: make pings fast

pkg/arvo/gen/vat.hoon
**Describe the bug**
+vat has been deprecated. when you run it it gives the message "Notice: +vat is deprecated as +vats now takes lists of one or more desks"
this prompted me to try ```+vats ~[%base %garden]``` which fails. I assert that this is the correct interpretation of the message above.
I propose to change the message to: "Notice: +vat is deprecated as +vats now takes one or more desks as arguments. e.g. '+vats %base %garden'"
**Additional context**
This is a simple one-liner that may prevent frustration in others as well. Especially until the docs are updated.
**Notify maintainers**
@joemfb 
tested on local planet by copying over new vat.hoon and running ```|commit %base```.
output:
```
> +vat %base
%base
/sys/kelvin:      [%zuse 413]
base hash: …
```
=> clarify +vats usage in +vat deprecation msg

pkg/arvo/sys/vane/ames.hoon
First, I noticed that when we time out a route, we aren't immediately sending to the galaxy.  This turned out to be due to a state mismanagement bug, where we updated our local copy of `peer-state`, but `+send-blob` used the global copy of it.  I fix this by saving our local copy manually, and I confirmed this fixed the issue, but I wouldn't be surprised if we have similar bugs elsewhere.
Second, we have a rule that we don't update congestion control stats when a response is returned to a packet that we've been retrying.  This is because packets that we've had to retry are often outliers, so we don't want that to infect our stats.  However, I believe we should reset `rto` here, because `+on-timeout` may have inflated it a lot, and in some circumstances that can cause frustrating increases …
=> ames: packet retry tweaks

pkg/arvo/sys/vane/ames.hoon
Our rift in ames can be initialized incorrectly (not at all), leaving us out of sync with %jael and the rest of the network. This prevents *fine* requests from being handled. I'm not sure how/when to properly initialize the rift in ames. It's explicitly zero-initialized in %jael, not in the keyfile, and not part of the `%private-keys` local subscription. It seems like all of that should be changed.
For now, this PR allows our rift to be reset from %jael through the `%stir` debug command.
@pkova, it'd be great to get this into the release-candidate if possible.
=> ames: add %rift to %stir

pkg/arvo/sys/vane/ames.hoon
Continuation of https://github.com/urbit/urbit/pull/6593. I found another instance of the bug fixed in that PR, in the `|fine` core. 
I don't think that we should use the "early `+abet`" pattern in general—to me that points to doing something in two different contexts. Open to other suggestions but I think that it's best to, if we have updated a piece of state that code declared outside of the current core uses, pass that directly. In this case it means to extract the retrieval of the peer-state outside of `+send-blob`. I've done that for all the call sites where we use that arm. I'm opening this for review to get feedback (but will test this on a live ship to confirm that nothing is obviously wrong with the change)
=> ames: more bugfixes after #6593

pkg/arvo/sys/vane/ames.hoon
We were not properly handling acks for live packets in the packet pump, and were always instantiating the congestion control pump with the same number (the initial, with all packets) for every iteration.
=> ames: fix incorrect handling of acks in |pack

pkg/arvo/sys/hoon.hoon
This PR adds `?/` and `?\` as `?#`-based versions of `?-` and `?+`. It also fixes a bug in `+lose:ar` -- the combinatorial explosion turns out to be necessary. Opening as a draft for further discussion/exploration; I'm not sure how we'll want to stage `?#`-related changes, or if the performance implications here are too dire.
=> hoon: further explore ?#, fix bugs

pkg/arvo/mar/vere.hoon, pkg/base-dev/mar/vere.hoon
Useful for frontends that want to check whether vere is up to date.
Format is 
`{"zuse":413,"arvo":238,"non":"0ve.kp3qf","nock":4,"rev":"/vere/~.2.6","lull":324,"hoon":139}`
=> mar: add vere mark

pkg/arvo/lib/test/ames-gall.hoon, pkg/arvo/sys/vane/ames.hoon, tests/sys/fine.hoon
Unbelievably, *fine* has been implicitly depending on hearing response fragments in the correct order. This PR fixes that by sorting them before deserialization, with a test case to prove it. It also limits fine response error messages to the appropriate scope, and refactors the existing fine tests.
=> fine: handle misordered responses

pkg/arvo/sys/vane/ames.hoon
Fixes #6608 by implementing the solution proposed [here](https://github.com/urbit/urbit/issues/6608#issuecomment-1559498863): 
> to check if we, as a server ames (the one not sending the %cork), are waiting for acks on messages we have sent, don't process the %cork, and wait for the client to send another one.
Testing the error found in https://github.com/urbit/urbit/pull/6598, it removes the flow on both sides, but waiting to hear from @Fang- to confirm that there are no other issues.
=> ames: skip corks if pending acks for naxplanations

pkg/arvo/sys/vane/ames.hoon, tests/sys/vane/ames.hoon
Previously, if we noticed `%boon` handling had caused a crash, we would transform any existing `%boon`s into `%lost`s, but still emit a new `%boon` for the message we crashed on.
Now, we make sure to just directly send a `%lost` if sending the `%boon` caused a crash. We drop the existing-moves transformation entirely, assuming it to vestigial from a brief glance at the blame/history. Reviewers, please confirm whether this is correct or not. (It must be, the tests still pass after all. (; )
Fixes #6611 (see there for more deets) and adds a test to make sure it doesn't occur again.
=> ames: correctly %lose a %boon we crashed on

pkg/base-dev/lib/pill.hoon
This PR fixes a problem I introduced in #5989. Splitting the raw `arvo-formula` and pre-processed arvo kernel (`installed`) across separate events in the solid pill breaks structural sharing between them. If it's not recovered through some other means (such as IPC event batching), this can create massive performance problems matching jets. See urbit/vere#420 for how this came up and the current workaround -- this PR will fix solid pills going forward, but existing piers must (always) be accounted for regardless.
=> solid: preserve structural sharing in arvo

pkg/base-dev/lib/shoe.hoon
Resolves #6625
To fix, I changed the instance of `+roll` to a `+spin` which increments a counter each time a column contains empty tapes. Also, `+row`'s trap now stops at the point when the null count equals the number of columns, indicating there's nothing left to render.
=> shoe: renders blank tape rows

pkg/arvo/app/dojo.hoon
`+complete-gen-poke-to-app` now works for desks other than `%base`.
`:dojo|<tab>`
```
:dojo|allow-remote-login   ::  allow-remote-login: allow a ship to link to dojo
:dojo|wipe                 ::  wipe: poke dojo to wipe its state
:dojo|acl                  ::  acl: list the ships that are allowed to link to dojo
:dojo|revoke-remote-login  ::  revoke-remote-login: revoke a ship's right to link to dojo,
```
`:treaty|<tab>`
```
:treaty|remove-desk  ::  :treaty|remove-desk: Stop republishing remote desk
:treaty|unpublish    ::  :treaty|unpublish: Stop publishing local desk
:treaty|add-desk     ::  :treaty|add-desk: Republish remote desk
:treaty|unally       ::  :treaty|unally: Stop syncing treaty data from ship
:treaty|publish      ::  :treaty|publish: Publish local desk
:treaty|ally …
```
=> dojo: gen tab complete for non-base desks

pkg/arvo/app/spider.hoon
(1) In +thread-fail, +thread-clean is called before +thread-http-fail and +cancel-scry meaning neither of the latter two actually run in any meaningful way. `serving` has been replaced with `(~(del by serving.state) tid)` and `scrying` has been replaced with `(~(del by scrying.state) tid)` in the state and therefore we cannot `(~(get by serving.state) tid)` in +thread-http-fail or `(~(get by scrying.state) tid)` in +cancel-scry.
(2) In +thread-http-fail return an informative tang as json instead of an empty 500 http response when the failure results from an internal crash.
=> spider: provide a tang http response when a thread called via http crashes

pkg/arvo/app/dojo.hoon
dojo `+complete` options are now sorted alphabetically.
before:
`:a<tab>`
```
:aqua
:acme
:azimuth-tracker
:azimuth
:azimuth-rpc
```
after:
`:a<tab>`
```
:acme
:aqua
:azimuth
:azimuth-rpc
:azimuth-tracker
```
=> dojo: sort complete options aor

pkg/arvo/app/dojo.hoon
dojo thread completion now works for subdirectories. e.g. `/ted/azimuth/load/hoon`
`-az<tab>`
```
-azimuth-load
-azimuth-snap-logs
-azimuth-snap-state
```
=> dojo: complete teds in dirs

pkg/arvo/sys/vane/eyre.hoon
On most ships the mark conversion tube from json to mime is cold. To see if you're affected, open a talk DM with the dev tools network tab open and refresh the page. On most ships this will take 10-30 seconds to fully load.
This happens because we only scry for the tube, but never tell Clay to cache the tube like we do in `+channel-event-to-json`. This PR makes Eyre give Clay a similar `%warp` move after scrying to keep the tube warm.
=> eyre: keep json to mime tube warm in handle-scry

pkg/arvo/app/dojo.hoon
This should probably be tested thoroughly.
`%dojo` now preserves input history after crashing.
This is an implementation of `~sarpen-laplux`'s idea of having `%dojo` poke itself to avoid crashing in `%drum`.
https://github.com/urbit/urbit/pull/6068#issuecomment-1317261818
=> dojo: preserve input history after crash

pkg/arvo/app/dojo.hoon
To [avoid false positives](https://github.com/urbit/urbit/pull/6652#pullrequestreview-1473439945), `+complete-gen-poke-to-app` now works for live dudes only.
Also, switch `=.` to `=?` for clarity.
=> dojo: don't +complete-gen-poke-to-app for dead dudes

pkg/arvo/sys/vane/gall.hoon
this fixes a typo in +ap-peek causing %x scries to always run the mark conversion logic even if the mark you want is the same as what the endpoint produced
=> gall: fix typo in +ap-peek causing redundant mark conversion

pkg/arvo/sys/hoon.hoon, tests/sys/hoon/func.hoon
Resolves #6655.
Fixes the sample of the wet gate produced by `++curr`.
Prior to the fix, `++curr` used the same expression for the sample of the returned wet gate as in `++cury`, minus the different face. This is incorrect: `++curr` binds the tail of `a`'s sample, so `b` should use the head of `a`'s sample instead of its tail.
The fix was successfully tested on a fakezod, although I only tested it on the version %139.
=> hoon: fix gate currying

pkg/arvo/sys/vane/clay.hoon
The syntax error pointer now points to the correct location.
before:
```
[%error-building /app/acme/hoon]
-------------^
=/  (~foo)
syntax error at [349 14] in /app/acme/hoon
```
```
[%error-building /app/acme/hoon]
^
<<end of file>>
syntax error at [1.416 1] in /app/acme/hoon
```
after:
```
[%error-building /app/acme/hoon]
syntax error at [349 14] in /app/acme/hoon
=/  (~foo)
-------------^
```
```
[%error-building /app/acme/hoon]
syntax error at [1.416 1] in /app/acme/hoon
<<end of file>>
^
```
=> clay: fix syntax error pointer

pkg/arvo/app/ping.hoon, pkg/arvo/sys/vane/ames.hoon
Ping takes a lot of resources on sponsor ships, because each ship sends a ping every 25 seconds, which is handled within the event loop.  This especially affects Tlon and all hosting providers above a certain scale, because they may have hundreds or thousands of ships under a single galaxy.
One solution is to process pings much faster, probably by handling them in the runtime.  I think this would be a valuable line of work.
The other solution is to ping much less often, which is also good and correct.  Hosted ships generally have public ports, so they don't need to ping every 25 seconds to keep a pinhole open.  They only need to ping when their port or IP changes.
This PR introduces a mode to the `:ping` app which can be manually enabled to declare that you know that you're not behind a …
=> ping: Rewrite to support non-NAT mode

pkg/base-dev/lib/sss.hoon, pkg/base-dev/sur/sss.hoon
SSS had a problem where, because i had naively implemented the nigh/yore protocol using ames pokes, publishers experienced a very high load, with many pokes coming in per minute.
This instead relies on ames acks from the subscriber, in the following way:
1. Subscriber asks to subscribe.
2. Publisher sends its latest rock `n`.
3. *Only when* the subscriber acks receipt of a rock or a wave `n`, the publisher performs one of the following:
a. If the ack was a nack, no-op.
b. If the publisher has wave `n+1`, send it.
c. If publisher doesn't have wave `n+1`, but it does have a higher rock, send that.
d. If publisher doesn't have wave `n+1` and it doesn't have a higher rock, store subscriber `~sampel` in a map. Once the next wave is published, send that to all subscribers in the map, and empty …
=> sss: rely on ames acks instead of timers

pkg/arvo/ted/code.hoon, pkg/arvo/ted/hi.hoon, pkg/arvo/ted/read.hoon
Before:
```
> -hi ~zod
l
u
f
s
s
e
c
c
u
s
d
o
z
~
i
h
```
After:
```
> -hi ~zod
'hi ~zod successful'
```
Same problem for `-code` and `-read`.
=> base: fix /ted/hi, /ted/code and /ted/read output formatting

pkg/arvo/sys/zuse.hoon
As discovered by @joemfb https://github.com/urbit/vere/pull/480#issuecomment-1615162411
``` hoon
> `*`=+(to-wain:format .*(-(+6 '') -<))
[0 0]
> `*`(to-wain:format '')
0
```
Fixing the hoon instead of the jet unlike the vere PR above.
=> zuse: fix to-wain jet mismatch

pkg/arvo/sys/lull.hoon
As of [RFC 5789](https://www.rfc-editor.org/rfc/rfc5789), PATCH is a valid HTTP request method. The `$method:http` type, however, did not include it, preventing us from making requests with this method.
Here, we add it to the `$method:http` type, so that it now includes all nine standard HTTP methods.
It doesn't look like we `?-` over the request method anywhere in base, and vere simply treats the method as a cord. Still, since user code could be `?-`ing on this (or similar), this is a breaking change. Targeting the 412 branch as such.
=> lull: add %'PATCH' to $method:http

pkg/arvo/lib/hood/kiln.hoon
If `|uninstall` is run on a desk with a `zest` of `%dead` (e.g. a desk that has been `|suspend`ed), `+poke-uninstall` will no-op and fail to cancel the desk's syncs if it has any. This PR rewrites `+poke-uninstall` such that it will cancel a desk's syncs irrespective of its `zest`, which was the behavior of `|uninstall` prior to #6382 . I suspect that #6720 is related, but even if not I believe that this change reflects the desired behavior of `|uninstall`. Also fixes a deprecated `%cd` scry in `+poke-suspend`.
=> kiln: have +poke-uninstall unsync desks with %dead zest 

pkg/arvo/lib/hood/kiln.hoon
Resolves the `uninstall` case in #6720
Currently, if a foreign desk is uninstalled, the first update that the publisher commits will produce the following output in dojo (this happens because we asked the other ship to notify us when an update happens before uninstalling the desk, so the data will eventually come):
``` 
kiln: downloading update for %desk from ~publisher/%desk
```
However, the update eventually no-ops, and the desk remains unchanged.
This PR solves the problem by checking if the desk is still installed before downloading it.
=> kiln: avoid downloading updates for uninstalled desks

pkg/arvo/sys/vane/clay.hoon
Looks like the introduction of `+read-q` led to a bug where a `[~ ~]` from `+read-q` was not propagated correctly from `+read-x`, instead becoming `~`. This results in stuff like `-read %x our %base da+now /i-dont-exist/txt` blocking forever even though we know the file does not exist.
=> clay: propagate [~ ~] properly from read-x

bin/solid.pill, pkg/arvo/sys/vane/ames.hoon, tests/sys/grq.hoon
As discussed with @yosoyubik and @joemfb out of band.
I tested this with 50 000 dead flows. Without consolidation these flows resulted in a constant 30 % cpu usage. Consolidating the timers led to a CPU usage of almost 0 with a 100 % spike for a few seconds every two minutes.
The retry interval is the normal ~m2, we can make it configurable later.
=> ames: consolidate dead flows to a single behn timer

pkg/arvo/sys/vane/ames.hoon
When forwarding packets, we check that we've heard a message along that lane in the last hour, and if we haven't, then we don't use that lane.  This does not work if you enable `%no-nat`, because you'll only receive very occasional pings.  As a result, galaxies will stop forwarding for `%no-nat` ships after one hour.
Those checks were added because we knew that all our children would ping us every 25 seconds, so no messages for one hour was a sure-fire indicator that they weren't online.  This is no longer the case, and the short-circuit is only an optimization anyway.  This PR removes those checks.
If we wanted to re-enable this kind of behavior, we could add a once-a-day ping even when your lane hasn't changed in `%no-nat` mode, and then declare a lane stale if we haven't heard anything …
=> ames: Don't check for lane staleness

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon
I decided to make a new task instead of using `%stir` as suggested by @philipcmonk here: https://github.com/urbit/urbit/pull/6700#issuecomment-1648475369. We need to pass a ship argument (`%stir` takes just a `@tas`) and unbelievable nonsense can erupt in `+load` when you change a type of a task so I think this is better.
=> lull, ames: add %tame task to delete a route for a ship

pkg/arvo/sys/vane/eyre.hoon
The companion PR to #6717.
Makes cosmetic changes to the login page of eyre. This addresses an issue with insufficient contrast between text elements and their backgrounds in dark mode.
- Renames and reassigns color variables to be in line with the @tloncorp/landscape style without introducing the overhead of Tailwind.
- Bumps the root font size on sub-30em-wide viewports to 16px to avoid mobile devices zooming in to the focused form field. Matches the 14px root font size in the rest of Landscape + apps on wider viewports.
- Removes the circle from the "X" icon when the login fails to be consistent with Landscape's icon language.
- Restyles the local vs eauth login toggle.
<details>
<summary>Image previews</summary>
---
---
---
---
</details>
=> eyre: cosmetic updates to login form

pkg/arvo/sys/vane/ames.hoon
Ships that were booted after the state migration that introduced the congestion control values as part of the ames state were operating with bunted values (`[msg=0 mem=0]`) which meant that publisher would consistently kick on every fact they would send.
Here we initialize the values in the definition of ames-state for any new ships that are booted and reinitialize them in a state migration for any ships that have them bunted.
=> ames: reinitialize congestion control values

pkg/arvo/sys/vane/ames.hoon
built on top of https://github.com/urbit/urbit/pull/6763 to reuse the state migration.
=> ames: reinitialize recork timer

pkg/arvo/sys/vane/ames.hoon
When implementing #6738 I assumed that all flows with an `rto` of `~m2` would be dead. My thinking was that any acked/nacked packets would reset the `rto` to a smaller value, but that is evidently not the case. There are flows with no unsent fragments in in the `packet-queue` but with an rto stuck at `~m2`:
I am unsure whether this indicates a deeper bug with the way `rto` is adjusted in %ames but fixing dead flow consolidation to account for this is very simple: just check if `rto` is `~m2` and that `next-wake` is not null.
@arthyn ran into this issue when migrating Tlons stuff to 412k-rc0.
=> ames: fix bug in dead flow consolidation

pkg/arvo/sys/vane/eyre.hoon
I decided to run the upcoming 412k release on `~dinleb-rambep`. Something that immediately started occurring on every page refresh was seeing stuff like this in the dojo:
```
eyre: removing watch for non-existent channel 1692289927-d5b4c7 chat
```
It turns out the issue was that the wires being sent to Gall are formatted slightly differently after the 412k eyre changes.
```
:: old format
/channel/subscription/1692289927-d5b4c7/52/~dinleb-rambep/chat
:: new format 
/channel/subscription/1692289927-d5b4c7/52/~dinleb-rambep/chat/~dinleb-rambep
```
This resulted in old subscriptions never being cleaned up and getting some annoying eyre messages on every page refresh. This PR fixes the issue.
=> eyre: handle old wires correctly in +on-gall-response

pkg/arvo/sys/arvo.hoon
`|verb` is broken on 412k prerelease because we were casting to old-style `[ship ship]` here instead of the correct `[ship ship path]` with provenance included.
Thanks goes to @midden-fabler for the bug report and @joemfb for the fix.
=> arvo: add provenance when casting forward move

pkg/arvo/app/roller-rpc.hoon
One of these was still left in %base, can't do this anymore because of comet identities.
=> roller-rpc: do not assert team:title for http-requests

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon, tests/sys/grq.hoon
We found that dead flow consolidation (#6738) can cause degenerate network behavior in scenarios where a ship has a tremendous amount of dead flows. This happens because sending a massive amount of traffic to galaxies in a very short period of time can overwhelm their forwarding queues which are currently set to 1000 messages.
We have made the conservative decision to make dead flow consolidation opt-in for 412, `|pass [%a %stir %dead]` to toggle it on and off.
Note that core developers and others that have been syncing off `~binnec-dozzod-marzod` will continue to have dead flow consolidation turned on unless they manually turn it off. I will personally keep mine turned on, but you may want to keep yours off if you run a busy publisher ship.
=> ames: make dead flow consolidation toggleable, default off

pkg/arvo/sys/vane/eyre.hoon, tests/sys/vane/eyre.hoon
Was reminded of this by today's core architecture meeting. Figured this eyre-side fix was small enough to just implement on the spot.
Previously, for endpoints bound to agents, we would pass the request onto the agent even if the agents wasn't currently running.
Here, we make eyre check to see if the agent is actually running, before passing the request on. If the bound agent is not running, eyre serves a 503 synchronously instead.
This way, we avoid cluttering up the gall queue for the bound agent. It also improves the UX for this case, giving an immediate response instead of appearing to hang during page-load.
(Targeting the 412 branch to avoid conflicts with the significant eyre changes that live there.)
=> eyre: serve 503 if bound agent is not running

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon
Adds a task `%dear` that unix can use to notify arvo about a new lane. Made this for my [mDNS PR](https://github.com/urbit/vere/pull/511) but could be useful in other contexts as well.
=> lull, ames: add %dear task to receive lane from unix

pkg/arvo/sys/vane/eyre.hoon, tests/sys/vane/eyre.hoon
Been doing light work on [urbit/js-http-api](https://github.com/urbit/js-http-api/) as of late, and Eyre's behavior forces it to do some sub-optimal things during initial setup. Here, we update Eyre to have a slightly simpler channel creation API.
Previously, a channel could only be created by sending a PUT request,
and a GET request to receive the channel's stream would only succeed
after channel creation had happened that way. This forces client
libraries, that generally have an explicit "set up" step before allowing
normal operation, to do strange things, [like sending faux pokes
(commonly hi-ing oneself)](https://github.com/urbit/js-http-api/blob/3e17850bbed0f9a4718a5058d911acbb892da489/src/Urbit.ts#L281-L287) before connecting to the channel's stream as
normal. This was especially …
=> eyre: more permissive channel creation

pkg/arvo/sys/vane/eyre.hoon
This is an Eyre-side implementation of [UIP 0106](https://github.com/urbit/UIPs/blob/main/UIPS/UIP-0106.md), enabling scrying via browser, `curl`, etc. For example:
```
$ curl localhost:80/_~_/cx/===/sys/kelvin
[%zuse 413]
```
Mark conversion is also supported:
```
$ curl localhost:80/_~_/cx/===/gen/verb/hoon.hymn
<html><head><title>Source</title><script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/4.3.0/codemirror.js"></script><script src="/lib/syntax/hoon.js"></script><link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/4.3.0/codemirror.min.css" /><link href="/lib/syntax/codemirror.css" rel="stylesheet" /></head><body><textarea id="src">::  Tell app to print what it&#39;s doing
::
::  For apps that use lib/verb, :app +verb toggles verbosity.
::
:-  %say
|=  [* …
```
=> eyre: add HTTP scrying

pkg/arvo/sys/vane/clay.hoon
This has the exact same problem as #6807, where the result of the `%bloc` scry excludes takos that are not reachable from the latest aeon.
The `%bloc` scry is only used by `/lib/pill` to pre-populate the clay blob store. The current urbit-v2.12 bootstrap pill is already built with this fix.
=> clay: return all takos in /cs/bloc scry

pkg/arvo/sys/vane/clay.hoon
Many users have reported issues installing new desks, sometimes having them take hours. Today me and a crew consisting of @yosoyubik @joemfb @Fang- and especially @philipcmonk figured out the reason why.
When a ship does `|install` to install a new desk it fetches not only the latest version but the entire history of the desk. Many histories contain commits that do not have a direct parent. This situation messes up our conditional in `+read-at-tako` since we only analyse the reachable commits (takos) from the latest commit. The fix is to iterate over all aeons to determine whether a tako is reachable.
It is unclear why these commits are so prevalent, but older desks in the wild seem to all have them. My guess is that all desks that have been created with `|merge` from `%base` as opposed …
=> clay: iterate over all aeons in +read-at-tako

pkg/arvo/ted/runtime-version.hoon
Looks like I missed that the `slav %ta` was dropped in #6729. The `-runtime-version` thread will always indicate that the runtime is out of date until this fix is applied.
=> runtime-version: parse current version properly

pkg/arvo/sys/hoon.hoon
Fixes #6750. Looks like the bug was introduced in 1892f28c61656123698a4385c719d2436ab1fa23.
=> hoon: fix gol type enforcement for trivial %cnts

pkg/arvo/sys/hoon.hoon, tests/sys/hoon/hashes.hoon
This PR fixes jet mismatch in +shas, introduced with urcrypt in v1.6. `+shas` is used for %gall agent wires, and therefore ends up in %ames flows, so this mismatch has a dramatic and observable effect. It's the cause of the event log replay mug mismatches that effect piers booted before v1.6 and subsequently upgraded. #5304 and #5836 are representative examples. Thanks to @Fang- for tracking down an accessible reproduction, and @frodwith for helping to find the root cause.
This PR cannot be released before #5701.
=> hoon: fix jet mismatch in +shas

pkg/arvo/sys/hoon.hoon
These new APIs are unused, and I believe there are no plans to use them. They can always be added back if we need them.
=> Revert "hoon: add pin and awl arms to test and trim subaxes"

pkg/arvo/sys/vane/eyre.hoon, tests/sys/vane/eyre.hoon
This is a partial revert of the behavior updated by #6789, prompted by discussion with @arthyn about js-http-api's reconnect behavior. tldr: without a 404, it cannot practically tell its channel was reaped.
Contrary to the argument made by 4affae8, this is the _actually correct_ behavior. Not creating server-side resources in response to GETs respects the expected method semantics, and more importantly, serving a 404 is an important signal for clients trying to connect to a channel they were using previously. Without that, they have no way of telling whether, when reconnecting, if their channel was reaped in the mean time or not.
The "empty PUT" affordance provided by 34148f9 makes requiring a PUT request for channel creation more reasonable.
We leave the general refactoring done by #6789 …
=> eyre: less permissive channel creation

pkg/arvo/sys/zuse.hoon
`+de:base64:mimes:html` is misbehaving in two scenarios.
1. We do a byte swap on the result at the end of decoding. This means that any leading zeroes that should become trailing zeroes get dropped. An example input for this problem is `(de:base64:mimes:html 'AAD+wg==')`.
2. We pad zeroes at the end for every `=` padding character. This is incorrect behavior, we should instead drop two bits from the end for every padding character. An example input for this problem is `(de:base64:mimes:html '/si=')`.
This PR fixes these issues. Thanks to `~litlep-nibbyt` for discovering the problem and helping with the solution.
=> zuse: fix +de:base64:mimes:html

pkg/arvo/app/dbug.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon
The upcoming introduction of persistent nock caching allows us to get rid of the insane `+dedup-message` arm in ames. This wonky function existed to ensure reasonable memory usage in scenarios such as when a busy publisher is sending the exact same `%fact` to many ships. 
Pruning the persistent nock cache with `+dedup-message` removed presents a risk of losing structural sharing in ames `unsent-messages`. This PR refactors `unsent-messages` to store the messages as nouns instead of jammed atoms to fix the problem.
=> lull, ames: do not store jammed messages in unsent-messages

pkg/arvo/sys/vane/ames.hoon
Consider the following scenario:
`~sampel-palnet` is behind a NAT. `/app/ping` will try to ping its sponsor `~sampel` every 25 seconds. `~sampel-palnet` just booted and has no route to `~sampel` so he will try to contact `~sampel` through the galaxy `~pel`.
`~sampel` received the ping. It will respond directly to `~sampel-palnet`, but knowing that the ping came through an indirect route the star will also send the ack through `~sampel-palnet`s sponsorship chain. This is where things go wrong.
`~sampel` will enter `+send-blob`, send the direct ack, but when it enters `+try-next-sponsor` it will encounter a missing peer-state for the sponsor. This sponsor is of course `~sampel` itself. Now `~sampel` will enter this code path : https://github.com/urbit/urbit/blob/10db04b944c6cdb7ed0d4ef3a17c6 …
=> ames: do not ignore our peer-state

pkg/arvo/sys/arvo.hoon
=> arvo: persistently cache scry type checks

pkg/arvo/sys/vane/eyre.hoon
We remove the local<->eauth switching tabs entirely. The only way to see the eauth login page is if the url contains an "eauth" query parameter. (Entering the local ship name into the eauth form still brings you to the normal login screen.)
The "proceed as guest" blurp no longer shows the guest identity, and we clarify the language to indicate that it is not guaranteed to result in access to content.
Both of those changes help simplify the look and feel of the login page. Various users had complained that it was confusing, given that logging into your own ship is still the common case, and not everyone knows what "euauth" is.
For applications redirecting to the login page, it is still recommended to add the ?eauth GET parameter if non-local sessions are supported. For applications that …
=> eyre: simplify the login page ux a little bit

pkg/arvo/sys/vane/gall.hoon
As reported by @rivmud-fabwen in `~dister-dozzod-lapdeg/battery-payload`.
Consider the case where you `%grow` a path `/foo` 3 times from a gall agent. After this you decide to `%cull` the same path with the case of `[%ud 2]`, removing the cases `[%ud 0]`, `[%ud 1]` and `[%ud 2]`. Everything works as expected so far, however! The next `%grow` that happens for the path `/foo` gets written to case `[%ud 2]`, completely breaking referential transparency. This happens because of a off-by-one error in `+ap-grow`.
That's not all folks. In the previous case if you decide to `%cull` with a case of `[%ud 1]` you also cull the case `[%ud 2]` because of another off-by-one error in `+ap-cull`.
This PR fixes both of the aforementioned issues. I also decided to enforce culling cases to be between the …
=> gall: fix remote scry bug

pkg/arvo/sys/vane/gall.hoon
Adds `egg-any` cast to `%gv` scry.
This should help keep changes to `$spore` in sync with `$egg-any`.
=> gall: add egg-any cast to %gv scry

pkg/arvo/sys/vane/eyre.hoon
Apps can set-cookies in http responses, but eyre overwrites them. This PR makes eyre append its cookies instead.
=> eyre: append set-cookie header rather than clobbering

pkg/arvo/sys/zuse.hoon
It is common for RSS feeds to have a `<?xml-stylesheet ... ?>` tag beneath the initial `<?xml ... ?>` tag.
Example: https://feeds.transistor.fm/other-life (go into dev tools and look at the xml file)
These tags are called [Processing Instructions](https://en.wikipedia.org/wiki/Processing_Instruction)
This PR allows multiple processing instructions to exist at the top of an XML file. Such as:
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="https://feeds.transistor.fm/stylesheet.xsl" type="text/xsl"?>
<rss>
...
</rss>
```
... however, it also allows a technically incorrect XML file to get parsed:
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?> 
<rss>
...
</rss>
```
I think that this is not that big of a deal because `decl` is only used in …
=> Allow multiple declarations on in de-xml:html

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon
This will require accompanying changes in Vere to handle this event.  It will be used to kick off STUN pinging.
=> ames: notify vere on %born and when sponsor list changes

pkg/arvo/sys/hoon.hoon, tests/bug/wtcl-crash.hoon
This PR corrects a miscompilation of `?:`, wherein crashes in conditional expressions were eliminated along with dead branches, resulting in a type hole. This issue was isolated and reported by @mikolajpp (see https://gist.github.com/mikolajpp/6d6fbd75af6e7dc2876ead1b384faaeb). The issue is fixed by including eliminated conditional expressions in a new dynamic hint (working name `%toss`), preserving any crashes they might cause.
This PR also fixes #5540, correcting the hoon implementations of loobean compiler helpers. Existing jet mismatches are currently "fixed" by disabling the jets here (commenting out the fast hints). A quick comparison shows only a very minor performance reduction, so that may be sufficient (but should be handled through changes to the jet declarations in vere). …
=> hoon: correct ?: miscompilation, loobean jet mismatches

pkg/arvo/lib/dprint.hoon
Addresses two bugs in `lib/dprint`
The first bug originates from the handling of `%hold`s in `+return-item`, which could lead to an infinite loop with some recursive types. The fix was to introduce a check for duplicate types in the `%hold` case in `+return-item`.
To reproduce:
1. `=c -build-file %/gen/cat/hoon`
2. `# c`
3. Observe hang
The second bug was linked to the handling of the `$tune` case in `+return-face`. Previously, the function would crash if `p.type` was not a term, which lead to crashes with built files that contained `=,` expressions. This fix skips the `%face` instead of crashing when `p.type` is not a term.
To reproduce:
1. `=n -build-file %/gen/norms/hoon`
2. `# n`
3. Observe crash
Resolves #6255
=> lib/dprint: fix crashes with recursive types and =,

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/gall.hoon
Also fixes a check in `+ap-grow` that was the wrong way around. This resulted in `%grow` being broken on 411-rc0.
=> gall: separate put:of-grow to put-tend and put-grow

pkg/arvo/app/herm.hoon, pkg/arvo/sys/vane/clay.hoon
@Fang- noticed today that sometimes the clay `%cf` scry returns a mark conversion gate that's complete nonsense:
```hoon
=x .^($-(* *) %cf /=base=/hoon/json)
(x *hoon)
[1.887.072.378 0]
```
`/mar/json` or `/mar/hoon` do not contain the proper arms, yet this scry still works. The gate we get returns the bunt of `hoon` in this case (which is definitely not `json`).
The reason why this happens can be gleaned from the following snippet:
```hoon
=c |%  ++  grab  |%  ++  hello  1  --  --
hoon:grab:c
<1.fji [* <236.trs 51.enr 139.uat 33.rnj 1.pnw %139>]>
```
When trying the `+grab` arm in the mark we don't use `slob` to check whether the arm actually exists, we just trust the tisgal to get us what we want. This PR fixes the bug.
I also decided to remove some unused `+jump` mark stuff I've never …
=> clay: do not return false conversion gate from build-cast

pkg/arvo/lib/hood/drum.hoon
This PR addresses an off-by-one error in `wrd:offset`. Previously, if M-c were used on a non-alphanumeric character and there were no alphanumeric characters between the position of the cursor and the end of the buffer, `wrd:offset` would increment its counter to a value one greater than the remaining length of the buffer. As a result, this `+snag` call in `/lib/sole` would fail due to its using an out-of-bounds index, causing Dojo to crash and unlink: https://github.com/urbit/urbit/blob/4576213e53e186083d67fd65497c031b6886b8d0/pkg/base-dev/lib/sole.hoon#L86
This fix corrects the issue by modifying `wrd` to check if the next character is null (i.e. the end of the buffer) and if so to return the current value of the counter rather than incrementing, preventing the off-by-one error and …
=> drum: prevent Dojo crash with M-c on certain characters

pkg/arvo/sys/vane/clay.hoon, pkg/arvo/ted/test.hoon
When something goes wrong it should print in red.  It looks better and adds visual contrast (drawing your eye to the important bit).
Before vs after (test assertion failed):
Before vs after (build failure):
=> test thread: now prints errors/failures in red instead of gray

pkg/arvo/sys/vane/ames.hoon
My previous PR #6835 had incorrect migrations because I was parsing the bone from the perspective of the message sink instead of the message pump. This error was discovered when I put 411k-rc1 on `~marnec-dozzod-marzod` today.
=> ames: fix message-blob migration

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon
This is just a draft, stateless implementation.
We'll need to track some state for alien peers at least, and will likely want more for easy inspectability, cancellation, &c. Error handling is non-existent, the move types may need to change, and the encryption could use more efficient serialization and "additional" authenticated data.
I had initially wanted to call this `%dear`, but @pkova beat me to it in #6783.
=> ames: adds initial, two-party, encrypted remote scry

pkg/arvo/sys/hoon.hoon, pkg/arvo/sys/vane/ames.hoon
ames migration was taking 10+ hours.
run:to reduced it to seconds.
adds `run:to` to hoon.hoon
rework `+state-18-to-19` in ames.
credit to @joemfb and @pkova
=> ames, hoon: add run:to, speed up ames migration

pkg/arvo/sys/vane/ames.hoon, pkg/arvo/sys/vane/gall.hoon
=> ames, gall: fix old state migrations

pkg/arvo/gen/vat.hoon
A fresh fake ship no longer comes with the `%garden` desk installed, this is a confusing message for new developers to encounter.
=> Replace %garden with %landscape within `+vat` hint

pkg/arvo/sys/vane/gall.hoon
The restructuring in #6852 put everything under versioned scry paths. Arvo remains none the wiser and still happily scries for /whey, without a leading version number, resulting in loss of detail for gall's section in |mass output.
Here, we simply slap the current version number in front of the /whey scry path, to get it to resolve.
=> gall: respond to /whey scries (for |mass)

pkg/arvo/app/dbug.hoon, pkg/arvo/app/debug/js/index.js, pkg/arvo/sys/vane/eyre.hoon, pkg/interface/dbug/src/js/api.js, pkg/interface/dbug/src/js/components/root.js, pkg/interface/dbug/src/js/components/searchable-list.js, pkg/interface/dbug/src/js/reducers/local.js, pkg/interface/dbug/src/js/store.js, pkg/interface/dbug/src/js/views/eyre.js
The recently added eyre cache wasn't yet visible in either mass output or the debug dashboard. Here we add support for both.
Includes a little extra logic that lets the dbug agent send cache clear commands on the user's behalf.
To avoid needlessly long scrolling, we add an "open" property to the debug dashboard's `SearchableList`, which can be set to false to collapse the list by default. This is useful for eyre's debug page, which commonly contains very long lists.
=> eyre, dbug: eyre response cache visibility

pkg/arvo/sys/vane/eyre.hoon
Eyre already looks at the `Forwarded` header for the original requester's IP address, and the security level of the connection. Some proxies may modify the original `Host` header, but still provide the original in the `Forwarded` header. So, if present, we now respect that.
(For the record, for those using nginx, the full `Forwarded` header is constructed as such:
```nginx
proxy_set_header Forwarded 'proto=https;host=$host;for=$remote_addr';
```
Without this change, to get eyre to read the correct/origin `Host` header, you'll need to explicitly un-rewrite it:
```nginx
proxy_set_header Host $host;
```
)
=> eyre: respect host from Forwarded header, if set

pkg/arvo/sys/vane/eyre.hoon
We always update the eauth endpoint based on new logins from the local identity. We also let the user configure a hardcoded endpoint url. In both cases, we update a recency timestamp for the endpoint, to help us keep our scry namespace responses immutable.
However, we even updated this timestamp if the visible endpoint didn't change. That is, if the new value was identical, or if the auto-detected endpoint changed, but it was actively being overridden by a user-configured url.
Here, we update the stored timestamp only if the visible url actually changed. This should help us respond to (remote) scry requests more consistently.
(See also the note in +send-keen:)
https://github.com/urbit/urbit/blob/19f9441ce1edc794c13010c8f21c2580d390db23/pkg/arvo/sys/vane/eyre.hoon#L1751-L1757
=> eyre: update eauth endpoint timestamp less eagerly

nix/test-fake-ship.nix, pkg/arvo/app/test.hoon
This PR makes CI build all threads, just like we do with marks, generators and agents. This avoids situations like #6917 in the future.
=> ci: red checkmark if any thread fails to build

pkg/arvo/sys/vane/jael.hoon
Last week `~mister-dister-dozzod-dozzod` was corrupted and needs to breach. This is a `~zod` moon with around 30k subscribers and running `|moon-breach` on `~zod` was running out of memory even with an 8gb loom.
The issue is somewhere in our `sort` implementation, see #6920 for a reproduction.
Luckily we can just sidestep this issue in `+public-keys-give`, since we don't need to sort remote `%boons`. This has been tested on a local copy of `~zod` and breaches the moon easily with a 2gb loom.
=> jael: do not sort remote gifts

pkg/arvo/app/spider.hoon
The logic for tracking remote scry requests done via threads was removed, so we re-add it here (considering the new interface for encrypted remote scry).
(Looked at this together with @pkova)
=> spider: track remote scry requests

pkg/arvo/app/dojo.hoon
Fixes the handling of faces that begin with `dir` (e.g. `=directories`) in `+parse-command:parser-at`. Resolves #5911
=> dojo: allow assignation of faces prefixed with 'dir'

pkg/arvo/app/ping.hoon
`/app/ping` has a few problems. One of them is that we created a state machine hole with the informal pinging changes in the upcoming 411k release. This is a serious, luckily unreleased bug that would make the galaxies lose track of their planets if the planets were restarted more than once after upgrading to 411.
The other one is that the state transitions were triggered for any poke-ack even though we really only care about the galaxy.
This is my attempt at making `/app/ping` only ping the galaxy. In addition, we rip out all of the jael stuff and just scry every time since most people will be informally pinging anyways. `/app/ping` used to have more responsibilities wrt subscribing to our own keys but they should be addressed by #6838.
We also rip out the hacky `%no-nat` stuff that was …
=> ping: only ping galaxy

pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/ames.hoon
Before this, ships wouldn't start sending informal pings unless the driver was restarted. Now, as soon as we get the 411 OTA, we introduce a dummy state migration that will emit the %saxo gift to unix (same behavior that happens on-born).
(We are only doing this if we did have a unix-duct, if we don't, we skip that since the larval stage will be expecting a %born task from unix anyway, and that code path—`++on-born:ev:adult-core`—is what always sends the sponsorship chain to the driver)
Note: tested on a live ship that applies the state migration; that and booting from a pill will need to be tested once https://github.com/urbit/urbit/pull/6936 is ready.
=> ames: emit %saxo on ++molt

pkg/arvo/sys/vane/eyre.hoon
Tlon hosting has a login health check that regularly logs into the ship using the `+code`. This login happens from a sidecar and therefore thrashes the eauth-url with localhost constantly. This causes ships on Tlon hosting to have unreliable eauth currently.
Disallowing localhost as the eauth-url seems like the simplest solution to me.
=> eyre: do not store localhost as eauth-url

pkg/arvo/sys/vane/ames.hoon
The `chain` in ames ordered the wrong way around. This problem shows up on line 3335 here: https://github.com/urbit/urbit/blob/49975d9821e775241069ad6e2584a76ee5c84a44/pkg/arvo/sys/vane/ames.hoon#L3330-L3340
`num` there is always either 1 or 2. This causes the key `2` to be overwritten all the time which is obviously not good.
@yosoyubik noticed this when working on new ames, but this is wrong in 411 too.
```hoon
> =mymop ((on ,@ ,[key=@ =path]) lte)
> (pry:mymop (gas:mymop *((mop ,@ ,[key=@ =path]) lte) [2 [0x1 /hello]] [1 [0x1 /hello-2]] ~))
[~ [key=1 val=[key=1 path=/hello-2]]]
```
=> ames: fix chain mop order

pkg/arvo/gen/vats.hoon, pkg/base-dev/sur/hood.hoon
`+vats` is agonisingly slow on my ship. This speeds it up by replacing tape interpolation & pretty-printer usage with explicit printing functions and cord concatenation. It also optimised a bunch of the code & reduces excessive scrying. Additionally, it fixes the %blocking filter to correctly print only the desks that are blocking the oldest pending kernel update.
before: `took s/107.362.567` 
after: `took s/31.124.617`
=> vats: fix vats and make faster

pkg/arvo/sys/vane/clay.hoon
This PR is a fix for #6527, as an alternative to #6879. With these changes:
```
merged with strategy %init
> |merge %tmp our %base
>=
kiln: desk not live
> |start %tmp %test
>=
removed: /~zod/tmp/~2024.3.13..18.00.47..1f25/desk/bill
> |rm /=tmp=/desk/bill
>=
- /~zod/tmp/2/desk/bill
kiln: desk not live
> |start %tmp %test
>=
gall: installing %test
> |install our %tmp
>=
gall: booted %test
built   /app/acme
built   /app/aqua
....
```
It's possible that `|start` or `|rein` should also set the desk to `%live`, so as to not need the explicit `|install`.
=> clay: respect %rein for desks without a bill

pkg/base-dev/sur/hood.hoon
in my #6939 +vats update I'd got the print order backwards in the case where you give vats an explicit list of desks, as @jfranklin9000 pointed out there. This fixes that
=> vats: fix desk order

pkg/arvo/sys/vane/ames.hoon, pkg/arvo/sys/vane/gall.hoon
In %gall, %pokes to a non-running agent are dropped, and a `%flub` task is sent to %ames to "forget" about the message that has been sent by decreasing the heard (but not acked) sequence number, and removing the pending-ack from its queue.
If the %poke is a `%leave`(s), %gall automatically %acks it (giving a %done to %ames) before sending the %flub, which means that %ames has already remove the pending-ack, and we are going to crash on the %leave, and send a %nack, making the subscriber to retry the %leave forever, every ~m2.
The fix: ~~we just check that the queue is not empty.~~ don't ack %leave for non-running agents
=> gall: don't ack %leave for non-running agents

pkg/arvo/gen/hood/moon.hoon
I got bitten by this today. @pkova said he had gotten bit by this some time ago. Maybe this isn't the full, 100%, ideal & accurate fix, but it should prevent you from getting into a confusing bad state.
Apparently the operation triggered by this generator may cause the rift for the specified moon to be inaccurate if |moon-breach was run previously.
Here, detect if the moon has been created before, and recommend the other generators if that is the case.
=> gen: prevent re-creating existing moons in |moon

pkg/arvo/app/spider.hoon
in the thread-calling http interface.
Specifying a `content-type` header of `application/x-urb-jam` will make the request body be interpreted as a `@uw`-encoded jammed noun, rather than json.
Specifying an `accept` header of `application/x-urb-jam` will make the thread result in the response body be rendered as ~~a `@uw`-encoded~~ jammed noun bytes, rather than json.
For the latter, the output mark becomes unused, since we can just "render" the resulting noun directly, without needing to explicitly convert it. (This assumes that converting any mark to %noun will always result in the same noun, which isn't guaranteed in theory, but is always the case in practice.)
This ~~maps closely to~~ is adjacent to Eyre's "noun channels" support, and prepares spider for use in a nouns-based version of …
=> spider: support speaking raw nouns

nix/test-fake-ship.nix
https://github.com/urbit/urbit/pull/6955 broke CI by modifying `/app/test`, but CI still passed. This happened because we are running out tests via khan (click) and we were not catching khan errors, just errors inside the agents and threads.
=> ci: catch khan errors in ci

nix/test-fake-ship.nix, pkg/arvo/app/test.hoon
addresses @joemfb 's comment:
> I think this would be better if `$command` where `$@(test [desk test])`. Easy to default to `%base` and keep compatibility in this interface (so old CI scripts still run, &c).
https://github.com/urbit/urbit/pull/6955#issuecomment-2052925280
=> base: %test arg -> test or [desk test]

pkg/arvo/sys/vane/ames.hoon
I messed up this one too in #6970. I also did some surgery on `~binnec-dozzod-marzod` to fix everybody that was affected and waited for their clay subscriptions to be filled.
=> ames: fix spurious %10 in ++stay

pkg/arvo/sys/vane/jael.hoon
When testing `%phoenix` we discovered that a poke that the app sends when hearing about a breach was always dropped with a `gall: missing` message. This is because jael delivers breach notifications to gall the vane and gall agents in an undefined order.
Old behavior:
```hoon
(sort `(list duct)`[[i=/gall/use/ping/0w3.psfYX/~dinleb-rambep/jael t=[i=/dill t=~[//term/1]]] [i=/gall/sys/era t=[i=/dill t=~[//term/1]]] ~] sorter)
~[[i=/gall/use/ping/0w3.psfYX/~dinleb-rambep/jael t=[i=/dill t=~[//term/1]]] [i=/gall/sys/era t=[i=/dill t=~[//term/1]]]]
```
New behavior:
```hoon
(sort `(list duct)`[[i=/gall/use/ping/0w3.psfYX/~dinleb-rambep/jael t=[i=/dill t=~[//term/1]]] [i=/gall/sys/era t=[i=/dill t=~[//term/1]]] ~] sorter)
~[[i=/gall/sys/era t=[i=/dill t=~[//term/1]]] …
```
=> jael: notify gall the vane before notifying gall agents

pkg/arvo/sys/vane/ames.hoon
Consider the following scenario as experienced by `~mopfel-winrux`:
A new ship subscribes to `%hits` on `~mopfel-winrux`. The app sends an initial subscription update that consist of a large list of `%facts`. Five of these `%facts` that Gall sends to Ames get queued as normal. On the 6th `%fact` Ames clogs the flow which is certainly not ideal since we haven't even had the chance to send anything over the network yet! Remember that we are still processing a singular event.
We also noticed that the clogging will happen for the 7th `%fact` and onwards during the same event. This will cause Gall to send duplicate `%kicks` to Ames, but we investigated this with @yosoyubik today and this seems harmless. The `%kick` receiver will immediately `%cork` and the duplicate `%kicks` become no-ops. …
=> ames: do not clog live peers

pkg/arvo/sys/vane/ames.hoon
See this https://github.com/urbit/urbit/pull/6996#issuecomment-2126190938 for context.
When processing pending-vane-acks, if there are any in the queue (i.e. that we have not delivered it to the vane; seq=10) we were wrongly passing the `ok=?(%.n %.y)` of the previous message—this happens in scenarios where things come out of order (seq=10 comes before seq=9, so we enqueue 10, and when 9 is processed we dequeue it right away).
If that had been a %nack (seq=9), we wouldn't be delivering the pending-ack to the vane, and just send a naxplanation directly in `+ha-plea`, and then increasing last-acked (9 -> 10). When the vane gives the %done back to %ames (and it was an error, seq=9), we are going to send a naxplanation, but because we reference `last-acked` (10) which has already been …
=> ames: assume ok when handling next pending-vane-ack

pkg/arvo/gen/commit-event.hoon
Produces a unix commit event from the provided path. This is useful in situations where a pier is running a buggy version of a hoon file that we cannot recover from.
By making a jammed event of the commit, we can inject into the affected pier (using the "-I event.jam" flag) a restored version of the file that fixes the issue.
=> gen: add +commit-event

pkg/arvo/gen/commit-event.hoon
This works even if the desk is not mounted which is important in some recovery scenarios.
=> gen: commit %info instead of %into

pkg/arvo/sys/vane/ames.hoon
Consider the following piece of code in the Ames scry for the `%forward-lane`:
https://github.com/urbit/urbit/blob/5e7359fbb5546de171954f6092d483946c79d93e/pkg/arvo/sys/vane/ames.hoon#L6026-L6030
This piece of code is scrying jael for the sponsoring galaxy if the peer in question is `%alien`, ie we've never communicated via Ames before. Unfortunately this is always going to respond with `~` because the gang in the `rof` call is incorrectly `~` instead of `[~ ~]`. This problem has been around since #6876.
Notably this issue never matters unless somebody is making a fine request to a ship without ever having communicated with that ship before. All other codepaths end up injecting packets into Ames that eventually lead to the peer state becoming `%known`.
This problem right here is the …
=> ames: really scry jael for sponsors when peer is alien

pkg/arvo/sys/vane/eyre.hoon, tests/sys/vane/eyre.hoon
We make two changes in the hopes of improving the UX of eauth, especially around its failure cases.
1. Lower the eauth timeout from 5 minutes to 50 seconds.
- This way we serve the user a formal error page much more eagerly. In practice, most commonly, remote scry for the eauth url either gets a response reasonably fast, or not at all.
- Nginx, popularly used as a proxy server in front of urbit, times out connections after a minute unless configured otherwise. Setting the timeout to be slightly below that ensures eyre gets to serve an error page itself in those common setups.
2. Lower the eauth url scry's case rounding from 1 hour down to 5 minutes.
- The high value was interfering with UX around updated public urls. The strong rounding is supposed to give us more frequent scry cache …
=> eyre: tweak time-related eauth numbers

pkg/base-dev/lib/test.hoon
Target tested code:
```hoon
++  fail
|=  *
~|(%an-error-message !!)
```
Usage in a test thread:
```hoon
++  test-failure
%+  expect-fail-message
%an-error-message                                                         
|.  (fail:main ~)
```
A recursive `+find` could make this less cumbersome.
=> Add error message testing arm

pkg/arvo/sys/vane/ames.hoon, pkg/arvo/sys/vane/clay.hoon
All vanes except clay respect the gang system since #6876. The gang is of type `(unit (set ship))` and gets passed as an argument to the scry handler of every vane. A gang of `~` means "my identity is anybody, serve me only public data", a gang of `[~ ~]` means "I am root, give me all data", and a gang with a set of ships means that these ships are asking for the data. In other words the gang represents who is making the scry.
This PR implements the gang system for clay. As with the other vanes the multiple scryers case is not implemented, but with this change `~`, `[~ ~]` and `[~dinleb-rambep ~ ~]` work fine.
I decided to make an extra permissions check if the gang is `~` and otherwise leverage the existing clay permissions machinery. An alternative to having clay scry itself for …
=> clay: respect the gang system

pkg/arvo/sys/hoon.hoon
It was written for tapes, but can operate on arbitrary lists just fine.
We update it in-place here, for the smallest/clearest diff, but can move it into the lists section of the library as desired.
=> hoon: generalize +trim

pkg/arvo/ted/new-app.hoon, pkg/arvo/ted/retrieve-gh.hoon
Adds input fields to `-new-app`. The first input is either of three:
- just `desk=term`,
- `[desk=term branch=cord]`,
- `[desk=term branch=cord dir=cord]`,
with `branch='master'` and `dir='desk'` as default values.
Examples of input:
```
-new-app %dawn /sigilante/sunrise
```
```
-new-app [%wasm 'lia-jet'] /quodss/urwasm
```
```
-new-app [%blog 'main' 'src/backend'] /quodss/blog
```
=> `-new-app` branch and directory

pkg/arvo/sys/vane/eyre.hoon
replace `+format-ud-as-integer` with `a-co:co` 
```
> =format-ud-as-integer |=  a=@ud
^-  tape
?:  =(0 a)  ['0' ~]
%-  flop
|-  ^-  tape
?:(=(0 a) ~ [(add '0' (mod a 10)) $(a (div a 10))])
> =((a-co:co `@ud`eny) (format-ud-as-integer `@ud`eny))
%.y
```
=> eyre: use a-co:co not +format-ud-as-integer

pkg/arvo/app/ping.hoon, pkg/arvo/mar/mass.hoon, pkg/arvo/sys/lull.hoon, pkg/arvo/sys/vane/dill.hoon, pkg/arvo/sys/vane/gall.hoon, pkg/arvo/ted/mass.hoon, pkg/base-dev/lib/strandio.hoon, pkg/base-dev/mar/mass.hoon
- add -mass thread to print them
- add +mass & +take-meme to strandio
- include agent name in gall tube failure message
- add mass mark
this works in conjunction with https://github.com/urbit/vere/pull/675
=> dill: implement %mass & %meme memory reports

pkg/arvo/app/dbug.hoon
The debug dashboard that's found at `/~debug` has had broken authentication behavior since comet identities were released. `/app/dbug` uses `+require-authorization:app:server` from `/lib/server` to perform a redirect to the login page if needed, but this code has been unreachable for comet identities because of the `?>  =(our src):bowl`. In practice the fact that login redirects from `/~debug` don't work but return a 500 instead wouldn't be such a problem, however...
https://github.com/urbit/urbit/blob/effa0ba3d12e41e495c53e5dd14ce9977a8e9272/pkg/arvo/app/acme.hoon#L591-L593
`/app/acme` uses the `/~debug` endpoint to verify the dns domain the ship is running on! This relic of the pre software distribution era causes `/app/acme` to be unable to verify the domain, which means new ships are …
=> dbug: fix debug authentication redirect for comet identities

pkg/arvo/sys/vane/gall.hoon
I was investigating #6794 by running a local copy of `~finned-palmer`, manually breaching by doing `|pass [%j %ruin [~dinleb-rambep ~ ~]]` and observing the ship hang for a very long time. When I interrupted the ship by doing ctrl+c, the problem became quite evident.
`~finned-palmer` was spending all its' time in `+mo-filter-queue`. Specifically, it was iterating over 450 000 blocked moves to an agent called `%push-notify` trying to find any moves from the ship that just breached. This is an agent from the long defunct `%escape`.
This PR enables us to recover from scenarios where userspace programs do crazy stuff like this. It does potentially break some invariants, but I believe this to be worth it because this is a manual intervention.
@belisarius222 @joemfb
=> gall: delete agent blocked moves on |nuke

pkg/arvo/lib/hood/drum.hoon, pkg/arvo/sys/vane/clay.hoon
resolves #6539 
syntax errors are displayed in the correct orientation.
```
> |commit %base
>=
: /~fed/base/57/gen/help/hoon
clay: read-at-tako fail [desk=%base care=%a case=[%da p=~2024.8.7..14.09.48..4c0b] path=/gen/help/hoon]
syntax error at [12 4] in /gen/help/hoon
++ path2tape
---^
[%error-building /gen/help/hoon]
clay: %a build failed [%base 0v1p.0u5vt.s5n34.vc4u5.dbocr.fmh65.vlkji.cfh3a.6ul1m.ufoep.jfnil /gen/help/hoon]
dojo: %writ fail [i=%~.hand t=/gen/help]
> +help
/gen/help/hoon
%generator-build-fail
```
```
> |commit %base
>=
crud: %into event failed
syntax error at [5 4] in /sur/hood/hoon
+$ pike
---^
[%error-building /sur/hood/hoon]
[%error-building /app/azimuth/hoon]
[from=57 deletes={} changes={[i=~.gen t=/hood/clay/merge/help/txt] [i=~.gen t=/hood/clay/fuse/help/txt] …
```
=> clay: fix error flopping

pkg/arvo/sys/hoon.hoon
I discovered this while helping debug ares-codegen, and was surprised to the current macro-expansion. I can't think of any reason not to make this change. It will help cut down on the overhead of calls into manually deconstructed cores (like `+in`, `+by`, `+nest:ut`, &c).
=> hoon: expand =| through ^* to enable constant-folding

pkg/arvo/sys/vane/eyre.hoon
During boot, userspace might send `%set-response` tasks before eyre has received its first `%born` event. In that case, the `outgoing-duct` in state will be the bunted duct, `%give`-ing on which will result in an arvo crash that kills the boot.
Here, for safety, we simply don't emit a %grow if the duct is empty. The entry got stored in state and will be sent to the runtime as soon as we receive the `%born`.
=> eyre: don't %grow if duct not initialized yet

pkg/arvo/sys/vane/clay.hoon
This makes ++set-zest check whether the desk is zuse-compatible before setting it `%live`. Currently you can turn on desks that aren't compatible and potentially cause problems.
=> clay: don't set zest %live unless zuse compat

pkg/arvo/sys/vane/eyre.hoon, tests/sys/vane/eyre.hoon
Cookies have been the bane of eyre tests for a while. We had resorted to
hard-coding the couple of expected cookie values and being careful about
passing them in the right place, right time. This was very finicky.
Here, we update the state that's passed continuously to include a value
for the "live" cookie. The rest of the testing code and helpers are
updated to keep this value updated according to the responses emitted by
eyre, and to inject the cookie into requests we simulate. This way, we
get the desired behavior of remembering the cookie like a browser would.
We get to remove the hard-coded cookie values from most tests. In the
process, we clean up the helpers a little bit, but unfortunately also
have to add more complex helpers for pulling the cookie from state.
All in all, tests …
=> eyre: improve test ergonomics slightly

bin/solid.pill, pkg/arvo/sys/vane/ames.hoon
Consider the following:
- we achieve a direct route, on the last live flow.
- there are no other live flows, so nothing times out—no /pump timers fire
- we don't trigger any %fine requests, so those don't time out either.
- the only lane in state for that peer never gets modified—that only happens on /pump and /fine %wake timers
- a /forward-lane scry will always produce that direct route, unless sender/receiver ships initiate communication—the route gets also updated if you hear a packet on a different lane than what you have in state.
To fix that, we update the /forward-lane scry to explicitly check if the route is dead, based on the last-contact timestamp, instead of relying on the last value saved in state;
The ames driver has cached the dead lanes, and those lanes only expire on …
=> ames: expire routes on a timer

pkg/arvo/sys/vane/eyre.hoon
When creating a pill for the currently live 411k-4 release I encountered a problem where the pill was unable to be booted and errored out with `give-no-duct` in arvo. The root cause of this is that `%groups` includes an agent that primes the eyre cache with `%set-response` in `+on-init`. This happens before we ever get the `%born` in gall which means that we blast out the gift to the empty wire.
Note that it's okay to skip giving the `%grow` to the runtime here because when we later get the `%born` we do this: https://github.com/urbit/urbit/blob/199f0848c8bd6e90d329ae495a201663195ec04d/pkg/arvo/sys/vane/eyre.hoon#L3494-L3499
=> eyre: do not %grow cache when outgoing-duct is empty

pkg/arvo/sys/vane/eyre.hoon
Reverts urbit/urbit#7087
I somehow managed to miss #7078 when making my PR. This problem has already been fixed, just unreleased on master.
=> Revert "eyre: do not %grow cache when outgoing-duct is empty"

pkg/arvo/sys/hoon.hoon
To be included in hoon %137, as required by #6932.
=> hoon: adds new atom ops

pkg/arvo/sys/lull.hoon
This PR adds a new declarative atom builder, supporting incremental and hierarchal composition, with a sample that is a superset of `+can`. Needed by #6932.
=> lull: adds $plot

pkg/arvo/sys/zuse.hoon, tests/sys/zuse/crypto/ed25519.hoon
- luck:ed and sign-(octs-)raw go together
- luck:ed generates a public private keypair where the private keypair is generated from SHA512(seed) and the usual EdDSA clamping procedure is done on the first 32 bytes.
- sign-(octs-)raw allows one to sign from a keypair generated with luck (or, from sca(d/s))
- scad, scas, scap allows one to 'tweak' a public/private keypair with a scalar
- scad tweaks public and private
- scas tweaks private
- scap tweaks public
this also fixes the jet mismatch mentioned in #7072, and potentially other jet mismatches due to sign:ed taking the bit rather than the byte length, whereas the jet uses u3r_bytes_fit to obtain the length to sign (the urcrypt library, moreover, doesn't allow signing at bit-level lengths). it also removes code deduplication generating …
=> fix shar:ed jet mismatch, add luck:ed, scad:ed, scap:ed, scas:ed, sign-raw:ed, sign-octs-raw:ed

pkg/arvo/sys/vane/eyre.hoon, tests/sys/vane/eyre.hoon
Presently, eyre creates a new guest session for every unauthenticated request it gets. For ships accessible from the clearweb, crawlers and other bots cause this to happen often. Sessions time out and get cleared up by eyre after some period of inactivity. As such, the amount of stored (guest) sessions is soft-bounded at "the amount of unauthenticated requests received within [session timeout time]".
To keep normal users from having to log in after a short time away from the keyboard, we want to increase the session timeout time. But this would loosen the bound described above.
Here, we separate the timeout times for guest sessions and "real", authenticated sessions. This lets us tweak their timeouts independently. We immediately use this to increase the time for real sessions to 30 days, …
=> eyre: separate session timeout for guest and auth

pkg/arvo/lib/hood/helm.hoon, pkg/arvo/sys/vane/ames.hoon
(PS: this PR also recalculates paths in the .tip when there's a rekey event—previously this was only done in the .pit)
~~(PPS: only tested locally between fakezods; next test on a live ship)~~ done
=> mesa: test migration before sending %ahoy $plea

pkg/arvo/sys/vane/ames.hoon
The `%ping` app has a long and unfortunate history. A part of this history is the various different wires the ping app uses to poke the galaxy sponsor. This wire is a part of the duct that gets used by double boot protection to check whether a booting ship is actually the latest version of said ship. The previous logic for finding the correct flow was flawed because it would find stale ping flows on ships that are old enough to have been running the previous versions of `%ping`.
An example of an old-style duct:
```
~[/gall/sys/way/~zod/ping /gall/use/ping/0w3.psfYX/out/~zod/ping/nat/0ws/ping/~zod /dill //term/1]
```
An example of the newest version of the duct:
```
~[/gall/sys/way/~zod/ping /gall/use/ping/0w3.psfYX/out/~zod/ping/ping /dill //term/1]
```
=> ames: fix ping-bone detection in %boot scry

pkg/arvo/sys/vane/eyre.hoon
Instead of dropping the connection on the floor, we should give a response that tells a client they made a request with an unsupported method.
(OPTIONS requests also end up here if the origin domain has not been approved, but in that case the 405 is accurate enough.)
=> eyre: respond to bad methods on channels endpoint

pkg/arvo/sys/vane/ames.hoon, pkg/arvo/sys/vane/jael.hoon, pkg/base-dev/sur/hood.hoon
- The current version of the test migration is more aggressive than it should be for certain cases of unsent/live message/fragments—fix for this incoming
- This aggressive test discovered a bug where unsent messages were not added to the new payload ordered map _in its actual arrival order from gall_ 
- ~~There are certain flows with tens of thousands of duplicated messages (most of them %leaves=[%0 %u ~]) that make these migrations slow. Here we start a partial flow amnesty that filters these duplicated messages~~removed. diuplicate %leaves will remain in the queue due to the complexity of special casing them in the test, to check that we are not introducing any bugs in the filtering logic
- Subscriptions to %jael keys for moons was broken since we were only handling keys for planets and …
=> mesa: moar misc fixes

pkg/arvo/app/eth-watcher.hoon
Context: 
```
> -diagnose!azimuth
last downloaded %azimuth block: #31.996.103 on unknown
last processed %azimuth block: #21.991.360 on unknown
installed %eth-watcher? %.y
running %eth-watcher? %.y
installed %azimuth? %.y
has %eth-watcher an %azimuth subscription? %.y
has %eth-watcher a %behn timer? %.y
is %azimuth subscribed to %eth-watcher? %.y
...
(wait 5s. to run the thread again)
```
eth-watcher started downloading blocks up to a number way in the future—possible culprit `(get-latest-block:ethio url.pup)`?—making etch-watcher stuck on that block until logs show up within blocks of that range. /app/azimuth had the latest block processed correctly when the incident happened. for ~norsyr-torryn, this was around 03/07, and @pkova found out that coincidentally, that same day there was an …
=> eth-watcher: rewind last block

pkg/arvo/sys/vane/ames.hoon
- %fine does not re-derive the paths in .keens (coming from the usage of the %chum task) after hearing new keys for our peers, or our own private key.
- %mesa does not re-derive the paths in .pit for the /publ and /chum namespaces after hearing a new private key
- if there were live .keens right before migrating a peer with |ahoy, the timer was not being reset, resulting in a benign but annoying "timer for strange ship" print.
=> ames, mesa: rederive keen paths with new public/private keys

pkg/arvo/sys/vane/ames.hoon
- naxplained sequence numbers were not added when regressing back to %ames
- regressed paths in the .pit are not updated in place and transferred to .keens but rather the moves that will produce those updates are passed onto %ames itself. the check was only comparing the pre/post migrated paths in .keens, causing the migration to fail for anybody that had any blocked +peeks. to fix that we go over the produced moves, looking for %keen cards that contain the pre-migrated path.
=> mesa: improve migration/regression checks

pkg/arvo/sys/vane/ames.hoon, tests/sys/fine.hoon
+decrypt-path/spac (for %mesa paths and payloads) was sequestered in the |ev core (that focuses on one specific peer) but we were retrieving the peer any wy from .chums.ames-state. here we refactor that flow and move it to the utility chapter of the |mesa core
=> mesa: move path-decryption to helpers chapter

pkg/arvo/sys/hoon.hoon
Reverts urbit/urbit#7132.
I'll put this into `next/kelvin/409`, not develop.
=> Revert "zpgl fix"

pkg/arvo/sys/vane/ames.hoon
The randomly generated jitter is up to 12 hours with one second resolution. This is to avoid potential thundering herd problems. A dead flow is defined as a flow we've retried 100.000 times which'll amount to around two months.
=> ames: retry dead flows once a day with some jitter

pkg/arvo/lib/test/ames-gall.hoon, pkg/arvo/lib/test/mesa-gall.hoon, pkg/arvo/sys/vane/ames.hoon, tests/sys/vane/ames.hoon, tests/sys/vane/mesa/boon.hoon, tests/sys/vane/mesa/nax.hoon, tests/sys/vane/mesa/plea.hoon
- Breached peers that had been ahoyed lost communication: Previously, the breached peer would remain in .chums, ignoring the default core (%ames as the time of writing), making that all packets from the breached peer after booting would be dropped.
(note: this doesn't handle the case for people that migrated anybody, that then after breached. this would need to be done in a state migration, or as soon as a peer hears an %ames packet for a peer that only has azimuth-state, but nothing else—probably also confirming that the default core is %ames, so we prevent weird any weird behavior when the default core changes)
- If the %ack for a %cork $plea got lost, the receiver of the resend would no-op since the flow was in closing.
- The handling of migrated/regressed peers has been refactored to …
=> mesa: bug fixes

pkg/arvo/sys/vane/jael.hoon
This is similar to the way we deal with nacked leaves in gall.hoon:
- As soon as we receive a nack from ames, we set up a timer (~d1; should be configured manually un 409k adding a task in %jael) to retry any pleas for which have outstanding state (i.e. ships for which we have sent a %plea but have not received a %boon with its keys; this is only true for moons)
- this is a global timer for everything outstanding, if we have outstanding pleas because of delays in the network communication, or because the parent of the mooon is offline, the handling of the resend $plea shouldn't have any effects since it will put the same wire as listeners in the state.
- XX TODO for 409k: add a %jael task to lull so we can tune the resend timeouts.
=> jael: handle %nacked /public-keys $plea

pkg/arvo/sys/hoon.hoon
Adds `+vi` door to `hoon.hoon` with default sample being a pass-through scry gate. To call e.g. `+mole` with empty namespace:
```
(~(mole vi ~) t)
```
Breaking changes: namespacing of virtualization gates. PR includes changes to the codebase for compatibility
=> hoon: virtualization core; namespacing

pkg/arvo/sys/vane/ames.hoon
the last queued events up to state %22 had a %tune $sign that was replaced with a %sage but need to be re-added so old and new types nest—this is easier than migrating the queued %tune event into a %sage
=> ames: add %tune to $sign to not break old queued-events

pkg/arvo/lib/math.hoon
`+pow` performance degrades rapidly as the exponent grows. Here we replace the `+sqt` implementation that calls `+pow` with one that uses the Newton-Raphson method. This gives way better performance, and more accurate results to boot.
Before:
```hoon
> ~>  %bout  (sqt:rd:lm .~1e-2)
.~0.10000000022017597   ::  took ms/181.095
> ~>  %bout  (sqt:rd:lm .~1e-3)
.~0.03162277732556293   ::  took s/10.576.252
> ~>  %bout  (sqt:rd:lm .~1e-4)
.~0.010000002308497298  ::  took s/743.265.918
> ~>  %bout  (sqt:rd:lm .~1e2)
.~9.999999977324386     ::  took ms/181.242
> ~>  %bout  (sqt:rd:lm .~1e3)
.~31.622775866034136    ::  took s/10.573.055
```
After:
```hoon
> ~>  %bout  (sqt:rd:lm .~1e-2)
.~0.09999999999999999   ::  took µs/80
> ~>  %bout  (sqt:rd:lm .~1e-3)
.~0.03162277660168379   ::  took µs/78
> …
```
=> math: better +sqt with newton's method

pkg/arvo/sys/vane/clay.hoon
The essential desks feature launched with 410 suspended desks too aggressively. If a desk was marked non essential `|essential-desk <desk> %.n` this desks were always suspended on a system upgrade, even if the non-essential desk would have been compatible with the system upgrade. This PR fixes the oversight in question.
=> clay: only suspend non-essential desks when not compatible

pkg/arvo/sys/hoon.hoon, tests/sys/hoon/pith.hoon
#5887 added `$pith`, a type for "typed paths". This addition came with language-level support for both literals and patterns, as well as some stdlib utilities.
Turns out I had been negligent in my testing of those additions. This PRs addresses two problems, in the stdlib utils and syntax support respectively.
- Primarily, the `$iota` parser `+spot:stip` and the `+pave` utility that depends on it were broken. For constant symbol elements (ie, `#/foo`) the parser would produce `[%tas %foo]`. The final parse step `+soft`s the parse result into the `$iota` type, but for `@tas` that type omits the label and expects the symbol as-is. Parsing would fail. `+pave` would make this silently fall back to `[%ta ~.foo]`.  
We patch the parser to correctly produce a `@tas` for those cases. (42c8dcf)
- …
=> hoon: pith tests and fixes

pkg/arvo/sys/vane/ames.hoon, pkg/arvo/sys/vane/jael.hoon
Subscribing to %moon $keys is broken on develop. Here we fix that and also change the retry timer in %jael for this failed %pleas from ~d1 to ~m10.
=> ames: only route $key/$turf gifts to |mesa

pkg/arvo/sys/vane/ames.hoon
We need to give the %turf $gift to the driver after we have a unix-duct, so we make sure that we only do that after hearing the %born event.
(this also fixes an issue with move ordering related to %public-keys $gift being given before the %private-keys)
=> ames: remove %turf $gift from %jael

pkg/arvo/sys/hoon.hoon
Running SKA tests on hoon.hoon showed that `+sink` has its fast hint on the product of the buc arm of the core instead of the core itself. I remember that this was caught by Edward Amsden in his tests too, but I couldn't find a corresponding PR.
=> hoon: fix +sink registration

pkg/arvo/sys/hoon.hoon
Adresses https://github.com/urbit/vere/pull/865#discussion_r2310656852
Removes jet mismatch: currently the runtime exits from the inner road with no additional trace if %12 is executed with scry gate being `~`
=> mink: crash silently if no scry handler
